### ISSUE TITLE
Fix CodeQL warning - Implicit narrowing conversion in compound assignment

### ISSUE THREAD

**Issue by setiah** [opensearch-project/OpenSearch#1000]
Compound assignment statements (for example 'intvar += longvar') that implicitly cast a value of a wider type to a narrower type may result in information loss and numeric errors such as overflows.

...main/java/org/opensearch/search/aggregations/bucket/BestBucketsDeferringCollector.java#L198 

_Note:
Compound assignment statements of the form x += y or x *= y perform an implicit narrowing conversion if the type of x is narrower than the type of y. For example, x += y is equivalent to x = (T)(x + y), where T is the type of x. This can result in information loss and numeric errors such as overflows._

**Comment by frotsch** [comment]
When I read the code correct then only int's are added to the `entry.docDeltas`: https://github.com/opensearch-project/OpenSearch/blob/0ba0e7cc26060f964fcbf6ee45bae53b3a9941d0/server/src/main/java/org/opensearch/search/aggregations/bucket/BestBucketsDeferringCollector.java#L139 So even if formally a `long` is returned by `docDeltaIterator.next()` the actual values are really only int's. May a explicit cast should be added to make this more clear.

So I guess we can ignore the CodeQL warning here.

**Comment by aritra998** [comment]
can I take up this issue ?

**Comment by anasalkouz** [comment]
Hey @aritra998, are you actively working on it?

**Comment by tlfeng** [comment]
Resolved by #1403
