### ISSUE TITLE
Optimize read write lock constructs during translog upload to remote store

### ISSUE THREAD

**Issue by ashking94** [opensearch-project/OpenSearch#10013]
**Is your feature request related to a problem? Please describe.**
While performing OpenSearch Benchmark runs, discovered a potential optimisation that obstructs the add to translog when the translog upload to remote store is ongoing. 

Translog add :
https://github.com/opensearch-project/OpenSearch/blob/443cfcaeaa009f82aa544ee7e4b131ffa147a2df/server/src/main/java/org/opensearch/index/translog/Translog.java#L541-L582

RemoteFsTranslog prepareForUpload : 
https://github.com/opensearch-project/OpenSearch/blob/443cfcaeaa009f82aa544ee7e4b131ffa147a2df/server/src/main/java/org/opensearch/index/translog/RemoteFsTranslog.java#L239-L251

**Comment by msfroh** [comment]
> While performing OpenSearch Benchmark runs, discovered a potential optimisation that obstructs the add to translog when the translog upload to remote store is ongoing.

Can you clarify what the optimization is?

**Comment by ashking94** [comment]
> > While performing OpenSearch Benchmark runs, discovered a potential optimisation that obstructs the add to translog when the translog upload to remote store is ongoing.
> 
> Can you clarify what the optimization is?

Currently the translog upload to remote store is happening within the write lock. I am trying to break it up and move the upload within read lock. #9636 is an attempt to do the same.
