### ISSUE TITLE
[BUG] [Remote Store] Restoring a CLOSED index with _remotestore/_restore API with restoreAllShards should not fail.

### ISSUE THREAD

**Issue by linuxpi** [opensearch-project/OpenSearch#10017]
**Describe the bug**
- when triggering _remotestore/_restore for a CLOSED index with restoreAllShards=false. The index is not OPENED
- We need to ensure the flow doesn't break.
- Along with that the expected state should be achieved after restore

**Expected behavior**
TBD

**Comment by gbbafna** [comment]
Storage Triage : Attendees [1](https://github.com/lukas-vlcek]) [2](https://github.com/skumawat2025) [3](https://github.com/astute-decipher) [4](https://github.com/gbbafna)  [5](https://github.com/linuxpi) [6](https://github.com/sachinpkale) 

Closing as this is completed.
