### ISSUE TITLE
Extend _cat/indices with storage type to simplify index management

### ISSUE THREAD

**Issue by ict-one-nl** [opensearch-project/OpenSearch#10056]
**Is your feature request related to a problem? Please describe.**
With the implementation of searchable snapshots there are now multiple storage types. For index management purposes it would be helpful it the _cat/indices exposed the storage type.

**Describe the solution you'd like**
Extend _cat/indices with storage type

**Describe alternatives you've considered**
Getting the settings of all individual indices. Works but it's not convenient

**Additional context**
none

**Comment by tlfeng** [comment]
Thanks for requesting the feature, it's under the consideration. There is a related request in https://github.com/opensearch-project/OpenSearch/issues/6528#issuecomment-1529399581 which I summarized in https://github.com/opensearch-project/OpenSearch/issues/7332#issuecomment-1568787740.

**Comment by ict-one-nl** [comment]
Great summary, that covers it way better :)

**Comment by anasalkouz** [comment]
Closing this on behalf of #6528
