### ISSUE TITLE
publish OpenSearch RestHighLevelClient

### ISSUE THREAD

**Issue by rursprung** [opensearch-project/OpenSearch#1005]
**Is your feature request related to a problem? Please describe.**
there is currently no official OpenSearch java client - [the docs](https://opensearch.org/docs/clients/java-rest-high-level/) even explicitly say that you have to use the Elasticsearch 7.10.2 client. that in turn is an old client version and will cease to receive support (& security updates) at some point (2022-05-11 at the latest, according to the published [elastic EOL dates](https://www.elastic.co/support/eol)).
newer versions of the elasticsearch library may or may not work with OpenSearch (they seem to have started to introduce version/license checks in newer versions) and newer versions have been re-licensed to the Elastic License 2.0.

**Describe the solution you'd like**
OpenSearch already contains the [`RestHighLevelClient`](https://github.com/opensearch-project/OpenSearch/blob/main/client/rest-high-level/src/main/java/org/opensearch/client/RestHighLevelClient.java) code.
please publish it as a library to maven central & co., just as was/is done by elastic for the elasticsearch version of the library.

**Describe alternatives you've considered**
using the elasticsearch library is only a short-term solution, mid-term it's not an option due to lack of security updates & co. and long-term it won't be an option because the OpenSearch and elasticsearch APIs will have diverged.

elastic will also start moving to a new API at some point in the future: [elastic/elasticsearch-java](https://github.com/elastic/elasticsearch-java). but this is not yet available and, while it'll be under the Apache 2.0 license again, it will probably also have the license/version checks in place. since it is not yet published there are no existing consumers of it. providing an OpenSearch version of `RestHighLevelClient` allows existing consumers to switch over to OpenSearch by simply replacing the package they're importing (at least when migrating from the ES 7.10.2 version to the OpenSearch 1.x version).

**Additional context**
* [OpenSearch docs for `RestHighLevelClient`](https://opensearch.org/docs/clients/java-rest-high-level/)
* [`RestHighLevelClient` in OpenSearch code base](https://github.com/opensearch-project/OpenSearch/blob/main/client/rest-high-level/src/main/java/org/opensearch/client/RestHighLevelClient.java)
* this is also required for a proper support in `spring-data-elasticsearch`: spring-projects/spring-data-elasticsearch#1880
* forum discussions:
  * [Elastic Java clients are no longer open source](https://discuss.opendistrocommunity.dev/t/elastic-java-clients-are-no-longer-open-source/6470)
  * [OpenSearch Client Java & Python APIs](https://discuss.opendistrocommunity.dev/t/opensearch-client-java-python-apis/5639)
  * [Support for High Level Rest Client](https://discuss.opendistrocommunity.dev/t/support-for-high-level-rest-client/6308)

PS: i've now raised this in the `OpenSearch` repo since this is where the client code exists, but maybe this needs to be moved to `opensearch-build` because it's about the publishing aspect? feel free to move it if that'd be a better place for it.

**Comment by frotsch** [comment]
Seems we have at least some snapshots: https://aws.oss.sonatype.org/content/repositories/snapshots/org/opensearch/client/opensearch-rest-high-level-client/1.0.0-SNAPSHOT/

**Comment by saratvemulapalli** [comment]
Thanks for opening up the issue. As @frotsch said, the team is working on it.

Have you tried building the clients from the source? Until Maven is ready.
@mch2 / @peterzhuamazon are snapshot maven repositories ready for consumption ?

**Comment by rursprung** [comment]
thanks for looking into this!

no, i haven't tried building it from source. for now we're just using `spring-data-elasticsearch:4.1` which is using an Apache 2.0 licensed ES dependency. building it manually doesn't make much sense for us since we're using it through another dependency and don't want to have our own internal fork of `spring-data-elasticsearch`.

**Comment by minalsha** [comment]
@mch2  is OpenSearch RestHighLevelClient  already available in Maven and how do we use it?
