### ISSUE TITLE
[BUG] [Indexing Path] [Tracing] Span adding already ended span as parent.

### ISSUE THREAD

**Issue by Gaganjuneja** [opensearch-project/OpenSearch#10090]
**Describe the bug**
Already ended span is becoming the parent of all the new Spans in the indexing path.

Background - In order to automatically propagate the current span (which will become the parent of the new span created out of that context), the telemetry tracing framework is storing it in the ThreadContext and detaching it when the scope is closed.

On the indexing path a lot of places in order to make the ThreadContext as system context we are stashing the context and restoring once the work is over. Restoring the old context also restores the current span which is actually ended and cleared up downstream.

We need to see if this can be fixed easily in the indexing path or if special handling is needed in the TracingFramework for such scenarios.

Some code paths - 

https://github.com/opensearch-project/OpenSearch/blob/d7aa6dd9c7759bbfedd7263d453d3ac6c92fab7d/server/src/main/java/org/opensearch/cluster/service/MasterService.java#L982

https://github.com/opensearch-project/OpenSearch/blob/d7aa6dd9c7759bbfedd7263d453d3ac6c92fab7d/server/src/main/java/org/opensearch/indices/replication/checkpoint/PublishCheckpointAction.java#L113

**To Reproduce**

**Expected behavior**

**Plugins**
Please list all plugins currently enabled.
telemetry-otel

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**

**Comment by reta** [comment]
Should be addressed by https://github.com/opensearch-project/OpenSearch/issues/10789
