### ISSUE TITLE
[BUG] flaky org.opensearch.remotestore.RemoteStoreStatsIT.testDownloadStatsCorrectnessSinglePrimaryMultipleReplicaShards test

### ISSUE THREAD

**Issue by ashking94** [opensearch-project/OpenSearch#10152]
**Describe the bug**
`org.opensearch.remotestore.RemoteStoreStatsIT.testDownloadStatsCorrectnessSinglePrimaryMultipleReplicaShards` test is flaky. 

**To Reproduce**
```
REPRODUCE WITH: ./gradlew ':server:internalClusterTest' --tests "org.opensearch.remotestore.RemoteStoreStatsIT.testDownloadStatsCorrectnessSinglePrimaryMultipleReplicaShards" -Dtests.seed=6E1ACBAAAA8FA304 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=sr-Latn-BA -Dtests.timezone=Asia/Qostanay -Druntime.java=20

```

**Expected behavior**
Test should always pass.

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**
CI - https://build.ci.opensearch.org/job/gradle-check/25991/testReport/junit/org.opensearch.remotestore/RemoteStoreStatsIT/testDownloadStatsCorrectnessSinglePrimaryMultipleReplicaShards_2/

**Comment by reta** [comment]
Closing in favour of https://github.com/opensearch-project/OpenSearch/issues/14310
