### ISSUE TITLE
[BUG] flaky org.opensearch.search.SearchWeightedRoutingIT.testMultiGetWithNetworkDisruption_FailOpenEnabled test

### ISSUE THREAD

**Issue by ashking94** [opensearch-project/OpenSearch#10153]
**Describe the bug**
`org.opensearch.search.SearchWeightedRoutingIT.testMultiGetWithNetworkDisruption_FailOpenEnabled` is flaky. 

**To Reproduce**
```
REPRODUCE WITH: ./gradlew ':server:internalClusterTest' --tests "org.opensearch.search.SearchWeightedRoutingIT.testMultiGetWithNetworkDisruption_FailOpenEnabled" -Dtests.seed=6E1ACBAAAA8FA304 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=es-AR -Dtests.timezone=America/Fortaleza -Druntime.java=20
```

**Expected behavior**
Test should always pass

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**
CI - https://build.ci.opensearch.org/job/gradle-check/25991/

**Comment by anshu1106** [comment]
Closing as duplicate https://github.com/opensearch-project/OpenSearch/issues/10755
