### ISSUE TITLE
Open-search process crashing on using the index.lifecycle.name in the API body #102

### ISSUE THREAD

**Issue by aditjind** [opensearch-project/OpenSearch#1019]
**Describe the bug**
While applying the policy _index_template on an index, Open-search crashed on using the index.lifecycle.name in the API body. This setting is not available in open-search but it shouldn't crash the process and return with the exception.

This is occurring on a vanilla OS cluster even without index management plugin installed on the cluster. 

Issue opened in Index Management Repo: https://github.com/opensearch-project/index-management/issues/102

**To Reproduce**
* Run an open-search cluster. 
* Hit the endpoint with an API: `curl -X PUT "localhost:9200/_index_template/timeseries_template?pretty" -H 'Content-Type: application/json' -d'
{
  "index_patterns": ["*"],
  "data_stream": { },
  "template": {
    "settings": {
      "number_of_shards": 1,
      "number_of_replicas": 1,
      "index.lifecycle.name": "timeseries_policy"
    }
  }
}
'
`
* The response returned is `curl: (52) Empty reply from server`
* The log trace found in the ES logs is pasted below. 

**Expected behavior**
As the setting is not available the process shouldn't crash but return the exception as setting not found.

**Log Trace**
`
=== Standard error of node `node{::runTask-0}` ===
»   ↓ last 40 non error or warning messages from /local/home/aditjind/gh/OpenSearch/build/testclusters/runTask-0/logs/opensearch.stderr.log ↓
» fatal error in thread [opensearch[runTask-0][masterService#updateTask][T#1]], exiting
»  java.lang.AssertionError: expected [index.lifecycle.name] to be private but it was not
»       at org.opensearch.cluster.metadata.MetadataCreateIndexService.validatePrivateSettingsNotExplicitlySet(MetadataCreateIndexService.java:1047)
»       at org.opensearch.cluster.metadata.MetadataCreateIndexService.getIndexSettingsValidationErrors(MetadataCreateIndexService.java:1037)
»       at org.opensearch.cluster.metadata.MetadataIndexTemplateService.validate(MetadataIndexTemplateService.java:1305)
»       at org.opensearch.cluster.metadata.MetadataIndexTemplateService.validate(MetadataIndexTemplateService.java:1226)
»       at org.opensearch.cluster.metadata.MetadataIndexTemplateService.validate(MetadataIndexTemplateService.java:1221)
»       at org.opensearch.cluster.metadata.MetadataIndexTemplateService.addIndexTemplateV2(MetadataIndexTemplateService.java:507)
»       at org.opensearch.cluster.metadata.MetadataIndexTemplateService$4.execute(MetadataIndexTemplateService.java:403)
»       at org.opensearch.cluster.ClusterStateUpdateTask.execute(ClusterStateUpdateTask.java:60)
»       at org.opensearch.cluster.service.MasterService.executeTasks(MasterService.java:715)
»       at org.opensearch.cluster.service.MasterService.calculateTaskOutputs(MasterService.java:337)
»       at org.opensearch.cluster.service.MasterService.runTasks(MasterService.java:232)
»       at org.opensearch.cluster.service.MasterService.access$000(MasterService.java:86)
»       at org.opensearch.cluster.service.MasterService$Batcher.run(MasterService.java:164)
»       at org.opensearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:163)
»       at org.opensearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:201)
»       at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:697)
»       at org.opensearch.common.util.concurrent.PrioritizedOpenSearchThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedOpenSearchThreadPoolExecutor.java:266)
»       at org.opensearch.common.util.concurrent.PrioritizedOpenSearchThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedOpenSearchThreadPoolExecutor.java:229)
»       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
»       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
»       at java.base/java.lang.Thread.run(Thread.java:832)`

**Host/Environment (please complete the following information):**
 - OS: Linux
 - Version: 5.4.116-64.217.amzn2int.x86_64

**Comment by Bukhtawar** [comment]
Looks like the JVM parameters had assertions enabled which is the case with test clusters. So most likely the crash is localized to the test setup? Can you try disabling assertions and verifying the same?

**Comment by dblock** [comment]
Should this be an assertion though? Even with assertions enable I don't think we want to be bringing down a cluster by an external query.

**Comment by frotsch** [comment]
So what a fix could look like? Replace the assertion with an error log and a return a 400 or 500 status code? Or just ignore the lifecycle name value and log a warning?

**Comment by dblock** [comment]
> So what a fix could look like? Replace the assertion with an error log and a return a 400 or 500 status code? Or just ignore the lifecycle name value and log a warning?

From my uneducated opinion this should be treated as any invalid input and return a 400.

**Comment by dblock** [comment]
Fixed in https://github.com/opensearch-project/OpenSearch/pull/1070 and https://github.com/opensearch-project/OpenSearch/pull/1060 for OpenSearch 1.1.
