### ISSUE TITLE
HTTPS access to opensearch 500 error [BUG]

### ISSUE THREAD

**Issue by suwei999** [opensearch-project/OpenSearch#10203]
Opensearch version 2.0, k8s deployment with 3 nodes

In the same business scenario:

When opensearch is connected using HTTP, there are no issues and the business is normal

When Opensearch uses HTTPS to connect, it occasionally reports a 500 error, and the server also found through testing that one of the nodes was unable to return data normally

**Comment by HoffmannTom** [comment]
Maybe you can check the logfiles at this date and time to get a stack trace or further information about the cause.

**Comment by dblock** [comment]
@suwei999 can you please add the request that causes the 500 and the complete response with the error?

**Comment by andrross** [comment]
@suwei999 Closing this issue as there isn't enough information to act upon here. Please feel free to open a new issue if you can provide more details as requested above. Thanks!
