### ISSUE TITLE
[BUG] Git Bash can't run ./bin/opensearch command. 

### ISSUE THREAD

**Issue by davidosorno** [opensearch-project/OpenSearch#10214]
**Describe the bug**
Using Git Bash on Windows I run `./bin/opensearch` and got a Java error that can't load the main class.
```
$ ./bin/opensearch
Error: Could not find or load main class org.opensearch.tools.java_version_checker.JavaVersionChecker
Caused by: java.lang.ClassNotFoundException: org.opensearch.tools.java_version_checker.JavaVersionChecker
```

**To Reproduce**
1. Using Git Bash on Windows, go to 'OpenSearch/build/distribution/local/opensearch-3.0.0-SNAPSHOT/'
2. Run `./bin/opensearch`
3. See error.

**Expected behavior**
I expected Git Bash runs the OpenSearch project and make the localhost:9200 available.

**Screenshots**

![Screenshot 2023-09-25 084901](https://github.com/opensearch-project/OpenSearch/assets/48450162/cd7a2ee6-fb9d-4d6d-9551-38fea7a65d13)

![Screenshot 2023-09-25 082615](https://github.com/opensearch-project/OpenSearch/assets/48450162/6ec57e1c-8508-46c4-be7c-bddf87dbe4ce)

![Screenshot 2023-09-25 071001](https://github.com/opensearch-project/OpenSearch/assets/48450162/811c466c-a39c-474c-af29-5adce33825c9)

![Screenshot 2023-09-25 084717](https://github.com/opensearch-project/OpenSearch/assets/48450162/6176752f-ecae-4ee5-a4a2-a8979af8d442)

**Host/Environment (please complete the following information):**
 - OS: Windows
 - Version 11

**Comment by davidosorno** [comment]
Yeah, it worked.

![image](https://github.com/opensearch-project/OpenSearch/assets/48450162/e61b10e4-c323-48d7-a9cb-40308065fd91)

Any idea, why did it work and the ./bin/opensearch didn't?

**Comment by HJohnRoss** [comment]
I also tried ./gradlew run, it did not work for me, I'm pretty sure I had the same idle problem ass well.

**Comment by davidosorno** [comment]
Hi @HJohnRoss, I think is working. Try the following:

1. Run the command `./gradlew run` and it should finish like this (don't stop or close this window).
![image](https://github.com/opensearch-project/OpenSearch/assets/48450162/c15d7fb8-cafd-4fdb-a7d3-8dd3600106ac)

2. Then go to [http://localhost:9200/_cat/health](http://localhost:9200/_cat/health) and you should see something like this
![image](https://github.com/opensearch-project/OpenSearch/assets/48450162/36915413-cc16-4369-a759-7944fe24004f)

**Comment by davidosorno** [comment]
I updated my main branch, run the localDistro command, and run opensearch again in Git Bash and it's working.  However, there is an error at the beginning, but I was able to make a localhost request. 
@dtaivpp should we close this bug?

![image](https://github.com/opensearch-project/OpenSearch/assets/48450162/f878843e-31cf-4edb-8f30-0eb07366d9fc)

**Comment by peterzhuamazon** [comment]
It is recommended to run `opensearch-windows-install.bat` in the root of the Windows ZIP extracted folder, as we have a lot of setups happens there, before launching opensearch.

The `opensearch-windows-install.bat` is internally calling `bin/opensearch.bat` instead of `bin/opensearch`, as the latter was written with NIX* in mind afaik, not always support git bash, or even full ledge mingw/msys2. So running `bin/opensearch.bat` is always recommended for the Windows specific distribution.

Thanks.

**Comment by bbarani** [comment]
@davidosorno @HJohnRoss Please try the suggestion provided by @peterzhuamazon and let us know your feedback. Feel free to re-open this issue if you need additional assistance.
