### ISSUE TITLE
[BUG] Could not raise JVM Heap Size over the 50% RAM limit

### ISSUE THREAD

**Issue by pietrogu** [opensearch-project/OpenSearch#10212]
**Describe the bug**
Even if not recommended, I need to raise the JVM heap size over the 50% of RAM, but when I try to do it the node does not start.
I have a 64 GB RAM,

**To Reproduce**
1. Set heap size more than 32 GB RAM

**Expected behavior**
The node should run

**Host/Environment (please complete the following information):**
 - OS: Oracle Linux 8

**Comment by dblock** [comment]
@pietrogu Can you please tell us how you change the JVM heap size, and paste the relevant part of the log that shows the start failure?

**Comment by pietrogu** [comment]
It seems that restarting the machine the problem was solved.
