### ISSUE TITLE
[BUG] Mapping type issue after upgrading from Elastic search 7.8.1 to Opensearch 1.0.0 

### ISSUE THREAD

**Issue by anish-adrot** [opensearch-project/OpenSearch#1022]
**Describe the bug**
In our application we are  ingesting our  logs  using logstash.Hence when we upgrade  our application from **elastic search 7.8.1 to opensearch 1.0.0** we are  facing  some issues in  logs ingestion..  we found  differenes in terms of **mapping type** between these two versions. they are listed below

**Elasticsearch 7.8.1(indices data)**
====================
{
        "_index" : "logs-2021.07.28",
        **"_type" : "_doc"**,
        "_id" : "w2Y07XoBygU95wt4Y0zX",
        "_score" : 1.0,
        "_source" : {
          "@timestamp" : "2021-07-28T12:59:44.030Z",
          **"type" : "filebeat"**,
          "agent" : {
            "type" : "filebeat",
            "ephemeral_id" : "08dcb535-c6a0-4a5a-9435-2c2209187e49",
            "id" : "0fe68f2b-2e65-4df1-924d-fd2c05ce0b29",
            "hostname" : "log-shipper-5nwbh",
            "version" : "7.9.1",
            "name" : "log-shipper-5nwbh"
          }
} 

**Opensearch 1.0.0(Indices data)**
====================    
{
        "_index" : "logs-2021.07.28",
        **"_type" : "filebeat"**,
        "_id" : "XYsI7XoBwUWR7YpW5kfz",
        "_score" : 1.0,
        "_source" : {
          "ecs" : {
            "version" : "1.5.0"
          },
          "@version" : "1",
          **"type" : "filebeat"**,
          "log" : {
            "offset" : 6806374,
            "file" : {
              "path" : "/var/lib/docker/containers/0f91ce2eeddd9830b62bf8fa8249-json.log"
            }
          }
}

**Error from logstash**
==============
Could not index event to Elasticsearch. {:status=>400, :action=>["index", {:_id=>nil, :_index=>"logs-2021.07.28", :_routing=>nil, :_type=>"filebeat"}, #<LogStash::Event:0x6ef9010>], 
:response=>{"index"=>{"_index"=>"logs-2021.07.28", "_type"=>"filebeat", "_id"=>"DeSd8HoBBBXZ9WLoDE-f", "status"=>400, 
"error"=>{"type"=>"illegal_argument_exception", "reason"=>**"Rejecting mapping update to [logs-2021.07.28] as the final mapping would have more than 1 type: [_doc, filebeat]"}}}}**

**To Reproduce**
-> create an index on elasticsearch 7.8.1 
-> load some data which contains a  field named **type** 
     eg: **"type" : "filebeat"**
-> check the  **_type** metadata  value  of loaded document
     eg:  **"_type" : "_doc"**
-> upgrade elasticsearch 7.8.1 to opensearch 1.0.0
->  load some data which  contains a  field named **type** 
      eg: **"type" : "filebeat"**
-> now the data load will get  fail with the below mentioned error.

**Expected behavior**
Even after the upgrade the **_type** metadata should be same i.e  **_doc** and data should be loaded successfuly.
**Plugins**
Please list all plugins currently enabled.

**Screenshots**
N/A

**Host/Environment (please complete the following information):**
 - OS:  SLES 15
 - Version : 15

**Additional context**
N/A

**Comment by dblock** [comment]
Is this the client sending the wrong data based on some version logic in it? Looks similar to https://github.com/opensearch-project/OpenSearch/issues/955, which was resolved by https://github.com/opensearch-project/OpenSearch/pull/847. Try setting `override_main_response_version`, see https://opensearch.org/docs/clients/agents-and-ingestion-tools/index/ for details.

**Comment by dblock** [comment]
@anish-adrot Did you get a chance to try this? Also what version of logstash and logstash-outoput-elasticsearch are you running?

**Comment by anish-adrot** [comment]
@dblock  we are  working on it. will let you know  once we are done.

**Comment by anish-adrot** [comment]
@dblock   we  have  tried  the  fix  as you mentioned 
PUT "/_cluster/settings?pretty" -H 'Content-Type: application/json' -d'
{
  "persistent" : {
     "compatibility" : {
       "override_main_response_version" : true
   }
  }
}
'

But  we  have  queries
-> While  Rolling upgrading , this  settings  applies  only  when  all  pods are  up and  running,if  we  try  to  run  before  the  pod is  up .we are getting  error.
-> So  our concern  due  to this  will  there  be  any  data  loss ? because  this  setting applies  only when  all pods are up.what  if in paralle ingest logs  to elasticsearch while  in upgrading process

**Comment by dblock** [comment]
@anish-adrot, did the setting work? (minus your question)
 
You make a good point. A few ideas.

1. If I am not mistaken, you could put this setting in opensearch.yml as well, so each new node would come up in the backwards compatibility mode. Please correct me if I am wrong or if I am missing anything @saratvemulapalli @mch2?
2. Depending on your setup can you bring up a first node that's not getting traffic, but use it to set the cluster-wide setting?
3. What happens in your system if ES is down? You could have all kinds of failures to write, so hopefully the system can/is designed in a way where it retries, or fails over preventing data loss.

**Comment by mch2** [comment]
> 1. If I am not mistaken, you could put this setting in opensearch.yml as well, so each new node would come up in the backwards compatibility mode. Please correct me if I am wrong or if I am missing anything @saratvemulapalli @mch2?

Correct.

**Comment by mch2** [comment]
Hi @anish-adrot, you can set this in opensearch.yml as:

```
compatibility.override_main_response_version: true
```

I can see that [documentation](https://opensearch.org/docs/clients/agents-and-ingestion-tools/index/) only defines the API request.  Thanks for pointing this out, I have cut an [issue](https://github.com/opensearch-project/documentation-website/issues/163) to have our documentation updated.
