### ISSUE TITLE
Make the identification of OpenSearch configurable

### ISSUE THREAD

**Issue by ict-one-nl** [opensearch-project/OpenSearch#1023]
**Is your feature request related to a problem? Please describe.**
We are using Telegraf to collect metrics. Like more software out there Telegraf checks the version of ElasticSearch, sees version 1.0.0 and quits: not supported.

**Describe the solution you'd like**
It would be helpful to create a config option to switch the server identification between OpenSearch 1.x or the corresponding ElasticSearch version (7.x in this case).

I presume you are maintaining compatibility with the ElasticSearch API's?

**Describe alternatives you've considered**
Patching Telegraf, but this is not always possible.

**Additional context**

**Comment by dblock** [comment]
I believe you're asking for `override_main_response_version`, see https://opensearch.org/docs/clients/agents-and-ingestion-tools/index/. Does this do everything you need?

**Comment by ict-one-nl** [comment]
You are entirely correct.. Didn't find that sorry :)

**Comment by dblock** [comment]
> You are entirely correct.. Didn't find that sorry :)

No stress, here to help!
