### ISSUE TITLE
Exceptions thrown in runAfterRefreshExactlyOnce of RemoteStoreRefreshListener during primary relocation

### ISSUE THREAD

**Issue by ashking94** [opensearch-project/OpenSearch#10263]
**Is your feature request related to a problem? Please describe.**
There are exceptions thrown, caught and logged in the `runAfterRefreshExactlyOnce()` method of RemoteStoreRefreshListener. This is harmless as it is only used for updating the stats tracker with local segments information and then retried in the actual segments sync. 

**Describe the solution you'd like**
In the `runAfterRefreshExactlyOnce()` method of RemoteStoreRefreshListener, we need to have the same checks as present in `syncSegments()` method of the same class.

**Describe alternatives you've considered**

**Additional context**

**Comment by sachinpkale** [comment]
@ashking94 Please check if this is still required.

**Comment by ashking94** [comment]
Verified that this issue has been fixed in later PRs concerning the mentioned class. Closing this.
