### ISSUE TITLE
[Feature] Improve compressed request handling

### ISSUE THREAD

**Issue by peternied** [opensearch-project/OpenSearch#10260]
**Is your feature request related to a problem? Please describe.**

In some cases, a request is considered invalid from its headers and its unnecessary to inspect the body of the request. For compressed requests, decompressed bodies can sometimes be quite large so its a benefit to skip decompression if the body is only being discarded.

**Describe the solution you'd like**
There should be some mechanism that is accessible by plugins to provide guidance to continue processing a request before more resources are used.

**Describe alternatives you've considered**

**Comment by peternied** [comment]
We been exploring two approaches to address how compressed requests are handled within our system. Here's a overview of both:

### Header Verifier with early request exit [1]
Craig is looking into adjusting the timing and manner in which certain components, specifically the "rest controller components", are triggered within the core of OpenSearch. In essence, this approach brings existing request functionalities into broader usage.

#### Pros:
- Minimizes the changes needed in plugins that are connected downstream.
- Locally tested
#### Cons:
- It blurs the distinctiveness of the "request" feature's design, potentially introducing unexpected behaviors.

#### PRs
- [1] https://github.com/opensearch-project/OpenSearch/pull/10261
- [1] https://github.com/opensearch-project/security/pull/3418


### Minimal Header Verifier [2]
Peter is focusing on the security side of things. Specifically, he's rethinking how the security plugin responds to verification (or "authentication") requests.

#### Pros:
- The core system remains mostly untouched, preserving its stability.
- Tidies up sections of the security plugin that were previously a bit convoluted.
#### Cons:
- Requires a significant overhaul of the security plugin, which could be time-consuming and might introduce temporary instability.
- Still in flight.

#### PRs
- [2] https://github.com/opensearch-project/OpenSearch/pull/10290
- [2] https://github.com/opensearch-project/security/pull/3430


As we delve deeper, we'll keep everyone updated on our progress and the potential implications of each approach. Feedback and thoughts are always welcome!

**Comment by reta** [comment]
> In some cases, a request is considered invalid from its headers and its unnecessary to inspect the body of the request. 

@peternied could you please give an example of invalid request? I am thinking about wrong auth credentials fe, is that the case?

I think if we need to inspect headers and reject the request even before consuming the content, there are two options:
 - `HttpRequestDecoder` that decodes the request, including headers
 - `HttpObjectAggregator` that aggregates the request from chunk with begin / aggregate / end lifecycle

Something to be aware of, with https://github.com/opensearch-project/OpenSearch/pull/9672 the request body is consumed lazily (as a stream), so the headers could be consulted before processing the request body.

**Comment by peternied** [comment]
@reta Here is an example of what a request could look likehttps://github.com/opensearch-project/security/pull/3417/files#r1343153212

```
POST /*/_search
{
"items": [
    {"a": 123, "b":123, ...},
    {"a": 123, "b":123, ...},
    ... repeated many times ...
]
```

I think having validation processes that only use headers vs a latter part of the pipeline get the request body (whole vs stream) seems like a good way to separate these concerns of validation vs processing while lowers the resource usage on invalid / rejected requests
