### ISSUE TITLE
[Repository] Honor throttling limits on recovery for multistream downloads

### ISSUE THREAD

**Issue by andrross** [opensearch-project/OpenSearch#10282]
The relevant settings here are:

| Field | Data type | Description |
| :--- | :--- | :--- |
| indices.recovery.max_bytes_per_sec | String | Limits the total inbound and outbound recovery traffic for each node. This applies to peer recoveries and snapshot recoveries. Default is `40mb`. If you set the recovery traffic value to less than or equal to `0mb`, rate limiting will be disabled, which causes recovery data to be transferred at the highest possible rate. |
| indices.recovery.max_concurrent_file_chunks | Integer | The number of file chunks sent in parallel for each recovery operation. Default is `2`. |
| indices.recovery.max_concurrent_operations | Integer | The number of operations sent in parallel for each recovery. Default is `1`. |

I think `max_bytes_per_sec` should clearly be honored. Implementation should be a matter of wrapping the input streams with the rate limiting stream functionality that already exists.

`max_concurrent_file_chunks` and `max_concurrent_operations` are less clear. I think they were intended for limiting the peer-to-peer recovery. If the intent is to limit the load on the source node, then perhaps it is not relevant when the source is a remote object store.

**Comment by kotwanikunal** [comment]
Resolved by #10349
