### ISSUE TITLE
[Tried to install analysis-phonetic getting 403 for URL: https://artifacts.opensearch.org/releases/plugins/analysis-phonetic/1.0.0/analysis-phonetic-1.0.0.zip.asc]

### ISSUE THREAD

**Issue by vinaymaley** [opensearch-project/OpenSearch#1034]
**Describe the bug**
I need to install some plugins like analysis-phonetic and analysis-icu. When i tried to install i am getting 403 from the https://artifacts.opensearch.org/releases/plugins/analysis-icu/1.0.0/analysis-icu-1.0.0.zip.asc

**To Reproduce**
docker up
Geting to into the docker container opensearch
docker exec -it <container-id> bash
run 
bin/opensearch-plugin install analysis-phonetic

**Expected behavior**
It should install the plugin

**Plugins**
opensearch-alerting             1.0.0.0
opensearch-anomaly-detection    1.0.0.0
opensearch-asynchronous-search  1.0.0.0
opensearch-index-management     1.0.0.0
opensearch-job-scheduler        1.0.0.0
opensearch-knn                  1.0.0.0
opensearch-notebooks            1.0.0.0
opensearch-performance-analyzer 1.0.0.0
opensearch-reports-scheduler    1.0.0.0
opensearch-security             1.0.0.0
opensearch-sql                  1.0.0.0

**Screenshots**
![image](https://user-images.githubusercontent.com/58561528/127755058-723c2d84-2336-41b6-b45b-f0f0661d316d.png)

**Host/Environment (please complete the following information):**
local
Ubantu

**Additional context**

Let me know if i am missing anything. Any help would be really helpful.

**Comment by cde0** [comment]
Also the same with S3 

`Exception in thread "main" java.io.IOException: Server returned HTTP response code: 403 for URL: https://artifacts.opensearch.org/releases/plugins/repository-s3/1.0.0/repository-s3-1.0.0.zip.asc`

**Comment by vinaymaley** [comment]
I think i found a answer from this closed issues. I was able to install the plugins. This this.
bin/opensearch-plugin install https://artifacts.opensearch.org/releases/plugins/repository-s3/1.0.0/repository-s3-1.0.0.zip. 
This should download and install the plugin. 
All the Best.
