### ISSUE TITLE
[Segment Replication] Aggregate backpressure metrics at node/cluster/index level.

### ISSUE THREAD

**Issue by mch2** [opensearch-project/OpenSearch#10365]
**Is your feature request related to a problem? Please describe.**
Today failure metrics for segrep backpressure are only surfaced through the /_cat/segment_replication API.  It would be ideal to aggregate these metrics similar to indexing/search bp at the node/cluster/index level.

**Describe the solution you'd like**
Include these metrics as part of segment/segment_replication metrics when rolled up.

**Describe alternatives you've considered**
Leaving as is.

**Comment by Poojita-Raj** [comment]
Closing this in favor of #10501 - only rejection count needs aggregation - other metrics aggregated in #9709
