### ISSUE TITLE
Leader/follower checker timeouts cannot be dynamically set

### ISSUE THREAD

**Issue by jainankitk** [opensearch-project/OpenSearch#10377]
**Is your feature request related to a problem? Please describe.**
Currently, the leader/follower checker timeouts can only be statically set using the yml settings. That is unnecessary and too constraining.

**Describe the solution you'd like**
Allow leader/follower checker timeouts to be dynamically set

**Comment by dblock** [comment]
@jainankitk What's a real world scenario where you'd want to change those without restarting the node(s)?

**Comment by jainankitk** [comment]
> What's a real world scenario where you'd want to change those without restarting the node(s)?

@dblock - This is not only useful for changing the value without restarting the nodes. It allows convenient override value without changing the yml on tens of nodes for large cluster.

This was also called out as must have during Opensearch Con by OCI for 750 node cluster

**Comment by dblock** [comment]
Okay, a 750 node cluster is no small feat. +1

**Comment by shwetathareja** [comment]
+1, this would be useful for large clusters.
