### ISSUE TITLE
[BUG] Flaky test org.opensearch.search.fieldcaps.FieldCapabilitiesIT.testWithIndexFilter

### ISSUE THREAD

**Issue by peternied** [opensearch-project/OpenSearch#10433]
### Failure:
```
Error Message
java.lang.AssertionError: 
Expected: an empty iterable
     but: [<MapperParsingException[failed to parse field [timestamp] of type [date] in document with id 'azESAosByLC1Oa18-P_l'. Preview of field's value: '2020-07-08']; nested: IllegalArgumentException[failed to parse date field [2020-07-08] with format [strict_date_time_no_millis||strict_date_optional_time||epoch_millis]]; nested: DateTimeParseException[Failed to parse with all enclosed parsers];>]
```

### Standard Error
```
REPRODUCE WITH: ./gradlew ':server:internalClusterTest' --tests "org.opensearch.search.fieldcaps.FieldCapabilitiesIT" -Dtests.method="testWithIndexFilter {p0={"search.concurrent_segment_search.enabled":"true"}}" -Dtests.seed=50EB4A14086A8C23 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=fi-FI -Dtests.timezone=Europe/Volgograd -Druntime.java=20
```

### Gradle Check (Jenkins) Run Completed with:
* **RESULT:** FAILURE :x: 
* **URL:** https://build.ci.opensearch.org/job/gradle-check/27209/
* **CommitID:** ddaca29d5926ca63609dc2f7dfeba94ed700d25c
Please examine the workflow log, locate, and copy-paste the failure(s) below, then iterate to green.
Is the failure [a flaky test](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#flaky-tests) unrelated to your change?

_Originally posted by @github-actions[bot] in https://github.com/opensearch-project/OpenSearch/issues/10261#issuecomment-1749771548_

**Comment by reta** [comment]
CC @CaptainDredge
