### ISSUE TITLE
[BUG] Flaky test org.opensearch.search.fetch.subphase.highlight.HighlighterSearchIT.testHighlightQueryRewriteDatesWithNow

### ISSUE THREAD

**Issue by peternied** [opensearch-project/OpenSearch#10434]
### Failure:
```
java.lang.AssertionError: 
Expected: an empty iterable
     but: [<MapperParsingException[failed to parse field [d] of type [date] in document with id '1'. Preview of field's value: '2023-10-05T17:30:34.967Z']; nested: IllegalArgumentException[failed to parse date field [2023-10-05T17:30:34.967Z] with format [strict_date_time_no_millis||strict_date_optional_time||epoch_millis]]; nested: NotSerializableExceptionWrapper[date_time_parse_exception: Failed to parse with all enclosed parsers];>]

```

### Repro with
```
REPRODUCE WITH: ./gradlew ':server:internalClusterTest' --tests "org.opensearch.search.fetch.subphase.highlight.HighlighterSearchIT" -Dtests.method="testHighlightQueryRewriteDatesWithNow {p0={"search.concurrent_segment_search.enabled":"false"}}" -Dtests.seed=5A3F88D61C8FD270 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=es-CL -Dtests.timezone=SystemV/HST10 -Druntime.java=20
```

### Gradle Check (Jenkins) Run Completed with:
* **RESULT:** FAILURE :x: 
* **URL:** https://build.ci.opensearch.org/job/gradle-check/27137/
* **CommitID:** 02b92ab86771ea5530c66c48d4127a3a135aa8e2
Please examine the workflow log, locate, and copy-paste the failure(s) below, then iterate to green.
Is the failure [a flaky test](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#flaky-tests) unrelated to your change?

_Originally posted by @github-actions[bot] in https://github.com/opensearch-project/OpenSearch/issues/10261#issuecomment-1749366384_

**Comment by reta** [comment]
CC @CaptainDredge

**Comment by CaptainDredge** [comment]
@reta can you please close this? Not able to repro it

**Comment by dblock** [comment]
@CaptainDredge It clearly failed when this issue was opened, that's why it's flaky. It mostly passes, except when otherwise. No repro is not a good reason to close ;)

**Comment by reta** [comment]
Replied in https://github.com/opensearch-project/OpenSearch/issues/10474#issuecomment-1766394994 but the issue was addressed (not ignored or disappeared by itself)
