### ISSUE TITLE
[BUG] org.opensearch.remotestore.RemoteStoreRefreshListenerIT.testRemoteRefreshRetryOnFailure has become flaky

### ISSUE THREAD

**Issue by ashking94** [opensearch-project/OpenSearch#10459]
**Describe the bug**
`org.opensearch.remotestore.RemoteStoreRefreshListenerIT.testRemoteRefreshRetryOnFailure` has become flaky after enabling remote upload backpressure by default (https://github.com/opensearch-project/OpenSearch/pull/10356).

**To Reproduce**
CI - https://build.ci.opensearch.org/job/gradle-check/27280/, https://build.ci.opensearch.org/job/gradle-check/27287/

**Expected behavior**
Test should always pass.

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**

**Comment by dblock** [comment]
https://github.com/opensearch-project/OpenSearch/pull/10388#issuecomment-1749777271

**Comment by ashking94** [comment]
Have a fix for this issue which I am pushing shortly.

**Comment by cwperks** [comment]
I encountered this failure on this PR: https://github.com/opensearch-project/OpenSearch/pull/10442#issuecomment-1755592500
