### ISSUE TITLE
Add support for disabling TLS witohut rebuilding docker image

### ISSUE THREAD

**Issue by pavolloffay** [opensearch-project/OpenSearch#1045]
**Is your feature request related to a problem? Please describe.**

I would like to run docker image `opensearchproject/opensearch:1.0.0` without requiring HTTPS

**Describe the solution you'd like**

Pass environment variable to disable TLS e.g. 

```
docker run -p 9200:9200 -p 9600:9600 -e "discovery.type=single-node" -e "http.host=0.0.0.0" -e "plugins.security.disabled:true"  --rm -it opensearchproject/opensearch:1.0.0  
```

**Describe alternatives you've considered**

**Additional context**

Running without TLS is useful for tests and demos.

**Comment by jkowall** [comment]
@pavolloffay Thanks for bringing this up, this is related to a similar discussion we are having https://github.com/opensearch-project/OpenSearch/issues/1029 I mentioned this specific issue related to Jaeger and most other OSS projects. 

For those who do not know @pavolloffay is a maintainer of both Jaeger and OpenTelemetry.

**Comment by frotsch** [comment]
`docker run -p 9200:9200 -p 9600:9600 -e "discovery.type=single-node" -e "http.host=0.0.0.0" -e "plugins.security.disabled=true"  --rm -it opensearchproject/opensearch:1.0.0`

`curl http://localhost:9200`

works for me! But it disables also RBAC!

You should see something like that in the logs: `[2021-08-05T09:32:16,690][WARN ][o.o.s.OpenSearchSecurityPlugin] [xxx] OpenSearch Security plugin installed but disabled. This can expose your configuration (including passwords) to the public.`

**Comment by pavolloffay** [comment]
Doh I have a typo there `plugins.security.disabled:true` it should be `plugins.security.disabled=true`
