### ISSUE TITLE
[Remote Store]  NodeId in segment and translog metadata file name may contain '-'

### ISSUE THREAD

**Issue by gbbafna** [opensearch-project/OpenSearch#10450]
Coming from https://github.com/opensearch-project/OpenSearch/pull/10379#discussion_r1347046641

Relevant PR : https://github.com/opensearch-project/OpenSearch/pull/10229 

We have added nodeId in metadata file names in translog and segment . NodeId is base64 UUID  which can contain '-' . Tokenizing it using our metadata separator will not work in this case 

**Solution**

1. Process the `nodeId` to remove `-` before adding it to metadata file name . 
2. Change the separator to some other value as done in https://github.com/opensearch-project/OpenSearch/pull/10379 to `...` . In this solution, we will need to handle backward compatibility .

**Comment by rohan19a** [comment]
Hi @sejli, I would like to take up this issue as a part of OSCI

**Comment by gbbafna** [comment]
Hi @rohan19a , thanks, I already have a PR since this needs to go in as part of 2.11 .
