### ISSUE TITLE
[BUG] Some test methods in SimulatePipelineRequestParsingTests never run

### ISSUE THREAD

**Issue by gaobinlong** [opensearch-project/OpenSearch#10493]
**Describe the bug**
When working on the backport PR https://github.com/opensearch-project/OpenSearch/pull/10479, I found that the two test methods `testParseUsingPipelineStore` and `innerTestParseWithProvidedPipeline` never run in both main and 2.x branch, but run normally in 1.x branch, it seems that relates to the previous PR https://github.com/opensearch-project/OpenSearch/pull/2491 which changed the private method `innerTestParseWithProvidedPipeline` to public but maybe because the method name doesn't start with `test` so this method never runs, and also relates to PR https://github.com/opensearch-project/OpenSearch/pull/2239 which changed the private method `innerTestParseUsingPipelineStore`  to public, renamed the method name but didn't remove the input parameter, so the new method `testParseUsingPipelineStore` also never runs.

Here are the detail of the related changes:

[innerTestParseWithProvidedPipeline](https://github.com/opensearch-project/OpenSearch/pull/2491/files#diff-81b8954297a72534ee70df21c9a1bb7a23a40e12be02048c0614865484b38ea1R134)

[testParseUsingPipelineStore](https://github.com/opensearch-project/OpenSearch/pull/2239/files#diff-81b8954297a72534ee70df21c9a1bb7a23a40e12be02048c0614865484b38ea1R89)

**To Reproduce**
Run `SimulatePipelineRequestParsingTests`, you can see that only four methods are executed, `testParseUsingPipelineStore` and `innerTestParseWithProvidedPipeline` never run.

**Expected behavior**
Enable the two test methods.

**Screenshots**
<img width="468" alt="image" src="https://github.com/opensearch-project/OpenSearch/assets/15811131/f9db0372-5ced-4dfa-ba05-62490b161380">

**Host/Environment (please complete the following information):**
 - OS: [macOS]
 - Version [3.0]

**Comment by gaobinlong** [comment]
After renaming `innerTestParseWithProvidedPipeline ` to `testParseWithProvidedPipeline` and removing the input parameter   of `testParseUsingPipelineStore`, the two methods runs well.

<img width="394" alt="image" src="https://github.com/opensearch-project/OpenSearch/assets/15811131/66294f68-1633-4879-9f7d-c0e7ad3b73f1">

**Comment by dblock** [comment]
Closed via https://github.com/opensearch-project/OpenSearch/pull/10496
