### ISSUE TITLE
[BUG] `_cat/segment_replication` returns no data

### ISSUE THREAD

**Issue by andrross** [opensearch-project/OpenSearch#10515]
I have a remote store-enabled cluster running a pre-release version of 2.11. Often when I invoke the segment_replication API I get the following:

```
GET _cat/segment_replication?v
shardId target_node target_host checkpoints_behind bytes_behind current_lag last_completed_lag rejected_requests
```

This was with a cluster with a single index with 1 replica taking writes. Sometimes an entry shows up in the API response, sometimes not. I don't know exactly how to reproduce this but I'll add more data if I find anything useful.

**Comment by mch2** [comment]
I think whats going on here is the replica is filtered out if there is not an active replication occuring.

I propose we make the following change  to this API - 

Add a column indicating pri/replica
Add a column for current SegmentInfos version
Always return a result for each replica
