### ISSUE TITLE
[BUG]Wrong error code in Scroll Context limit error

### ISSUE THREAD

**Issue by shiv0408** [opensearch-project/OpenSearch#1053]
**When the max open scroll context is reached. We get Internal Server Error (500) error instead of Too Many Requests (429) error.**

**To Reproduce**
Steps to reproduce the behaviour:
1. Set max_open_scroll_context to 0. (To easily reproduce the error)
`curl --location --request PUT 'localhost:9200/_cluster/settings' \
--header 'Content-Type: application/json' \
--data-raw '{
    "persistent":{
        "search.max_open_scroll_context": 0
    }
}'`
2. Create a scroll context in your test index. 
`curl --location --request POST 'localhost:9200/test/_search?scroll=1m' \
--header 'Content-Type: application/json' \
--data-raw '{
    "query":{
        "match_all":{}
    }
}'`
3. Error with status code 500

**We should get error with 429 code.**

**Comment by Bukhtawar** [comment]
Thanks @shiv0408 we might need to throw `OpenSearchRejectedExecutionException` instead here

https://github.com/opensearch-project/OpenSearch/blob/7469bf6e2603dbdbb808b96f453b4349c5f1d87f/server/src/main/java/org/opensearch/search/SearchService.java#L658-L663

**Comment by adnapibar** [comment]
Resolved by #1054
