### ISSUE TITLE
Replace JCenter with Maven Central for Gradle Build

### ISSUE THREAD

**Issue by adnapibar** [opensearch-project/OpenSearch#1055]
**Is your feature request related to a problem? Please describe.**

On February 3 2021, JFrog [announced](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/ ) the shutdown of JCenter. Later on April 27 2021, an update was provided that the repository will only be read only and new package and versions are no longer accepted on JCenter.  This means we can no longer use JCenter for our central artifacts repository for dependency resolution.

**Describe the solution you'd like**
 Replace with Maven Central as per the [Gradle recommendation](https://blog.gradle.org/jcenter-shutdown)

**Comment by frotsch** [comment]
Can we add also `mavenLocal()` ? See https://github.com/opensearch-project/OpenSearch/issues/939
