### ISSUE TITLE
[BUG] Flaky org.opensearch.cluster.allocation.ClusterRerouteIT.testDelayWithALargeAmountOfShards 

### ISSUE THREAD

**Issue by ashking94** [opensearch-project/OpenSearch#10558]
**Describe the bug**
`org.opensearch.cluster.allocation.ClusterRerouteIT.testDelayWithALargeAmountOfShards` test is flaky. 

**To Reproduce**
CI - https://build.ci.opensearch.org/job/gradle-check/27604/testReport/junit/org.opensearch.cluster.allocation/ClusterRerouteIT/testDelayWithALargeAmountOfShards/

**Expected behavior**
Test should always pass

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**

**Comment by peternied** [comment]
+1 https://github.com/opensearch-project/OpenSearch/pull/10800#issuecomment-1773237635

**Comment by amkhar** [comment]
https://github.com/opensearch-project/OpenSearch/pull/10904#issuecomment-1778700513
