### ISSUE TITLE
[BUG] Flaky Runtime Exception while executing Painless script during Update call

### ISSUE THREAD

**Issue by r1walz** [opensearch-project/OpenSearch#10561]
**Describe the bug**

While performing updates through stored [Painless] scripts, we error out with `java.lang.UnsupportedOperationException -- java.util.Collections$UnmodifiableMap.put(Collections.java:1457) ~[?:?]` only so often.

**To Reproduce**

<details>

<summary>Steps to reproduce the behavior:</summary>

Checkout [`e4a1841`](https://github.com/opensearch-project/OpenSearch/commit/e4a1841e23dadd3351216383fdc16bf56a0b783d) from `opensearch:main`.

```sh
# run server
$ ./gradlew run

...

# Create Index
PUT sample-idx
{
  "mappings": {
    "properties": {
      "name": {
        "type": "text"
      },
      "rank": {
        "type": "integer"
      }
    }
  }
}

{
  "acknowledged": true,
  "shards_acknowledged": true,
  "index": "sample-idx"
}

# Index a Doc
POST sample-idx/_doc/1
{
  "name": "Rohit",
  "rank": 1
}

{
  "_index": "sample-idx",
  "_id": "1",
  "_version": 1,
  "result": "created",
  "_shards": {
    "total": 2,
    "successful": 2,
    "failed": 0
  },
  "_seq_no": 0,
  "_primary_term": 1
}

# Store a sample script
POST _scripts/sample_script
{
  "script": {
    "lang": "painless",
    "source": """
    params.rank = 2
    """
  }
}

{
  "acknowledged": true
}

# Perform Update through Script
POST sample-idx/_update/1
{
  "script": {
    "id": "sample_script",
    "params": {
      "name": "r1walz"
    }
  }
}

# Now, it succeeds every now-and-then ...

{
  "_index": "sample-idx",
  "_id": "1",
  "_version": 2,
  "result": "updated",
  "_shards": {
    "total": 2,
    "successful": 2,
    "failed": 0
  },
  "_seq_no": 1,
  "_primary_term": 1
}

# ... but, fails more often than not

{
  "error": {
    "root_cause": [
      {
        "type": "illegal_argument_exception",
        "reason": "failed to execute script"
      }
    ],
    "type": "illegal_argument_exception",
    "reason": "failed to execute script",
    "caused_by": {
      "type": "script_exception",
      "reason": "runtime error",
      "script_stack": [
        "java.base/java.util.Collections$UnmodifiableMap.put(Collections.java:1457)",
        "params.rank = 2\n    ",
        "      ^---- HERE"
      ],
      "script": "sample_script",
      "lang": "painless",
      "position": {
        "offset": 11,
        "start": 5,
        "end": 25
      },
      "caused_by": {
        "type": "unsupported_operation_exception",
        "reason": null
      }
    }
  },
  "status": 400
}

# Corresponding Stacktrace

java.lang.IllegalArgumentException: failed to execute script
        at org.opensearch.action.update.UpdateHelper.executeScript(UpdateHelper.java:342) ~[opensearch-3.0.0.jar:3.0.0]
        at org.opensearch.action.update.UpdateHelper.prepareUpdateScriptRequest(UpdateHelper.java:279) ~[opensearch-3.0.0.jar:3.0.0]
        at org.opensearch.action.update.UpdateHelper.prepare(UpdateHelper.java:109) ~[opensearch-3.0.0.jar:3.0.0]
        at org.opensearch.action.update.UpdateHelper.prepare(UpdateHelper.java:90) ~[opensearch-3.0.0.jar:3.0.0]
        at org.opensearch.action.update.TransportUpdateAction.shardOperation(TransportUpdateAction.java:242) ~[opensearch-3.0.0.jar:3.0.0]
        at org.opensearch.action.update.TransportUpdateAction.shardOperation(TransportUpdateAction.java:235) ~[opensearch-3.0.0.jar:3.0.0]
        at org.opensearch.action.update.TransportUpdateAction.shardOperation(TransportUpdateAction.java:90) ~[opensearch-3.0.0.jar:3.0.0]
        at org.opensearch.action.support.single.instance.TransportInstanceSingleOperationAction$ShardTransportHandler$1.doRun(TransportInstanceSingleOperationAction.java:321) [opensearch-3.0.0.jar:3.0.0]
        at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:908) [opensearch-3.0.0.jar:3.0.0]
        at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52) [opensearch-3.0.0.jar:3.0.0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: org.opensearch.script.ScriptException: runtime error
        at org.opensearch.painless.PainlessScript.convertToScriptException(PainlessScript.java:109) ~[?:?]
        at org.opensearch.painless.PainlessScript$Script.execute(sample_script:1) ~[?:?]
        at org.opensearch.action.update.UpdateHelper.executeScript(UpdateHelper.java:339) ~[opensearch-3.0.0.jar:3.0.0]
        ... 12 more
Caused by: java.lang.UnsupportedOperationException
        at java.util.Collections$UnmodifiableMap.put(Collections.java:1457) ~[?:?]
        at org.opensearch.painless.PainlessScript$Script.execute(sample_script:12) ~[?:?]
        at org.opensearch.action.update.UpdateHelper.executeScript(UpdateHelper.java:339) ~[opensearch-3.0.0.jar:3.0.0]
        ... 12 more

```

</details>

**Expected behavior**

Painless should be execute as per expectation without encountering any bugs. In this case though, it seems throwing exception is the desired behaviour as `params` Map is immutable once created and script seems to modify it. Either way, we should throw a better cause for `unsupported_operation_exception` instead for posting `null`.

**Plugins**

Standard.

**Screenshots**

https://github.com/opensearch-project/OpenSearch/assets/31043830/562a7fa6-3231-47b0-a3fd-cb70e78d650c

**Host/Environment (please complete the following information):**

- EC2 m5.2xlarge latest default ubuntu linux AMI

**Additional context**

N/A

**Comment by rohan19a** [comment]
Hi @sejli, I would like to take up this issue as a part of OSCI

**Comment by r1walz** [comment]
Hi, @rohan19a. Thanks for showing interest. As of now, no-one is working on this one. We'd love to receive contribution. Feel free to contact me through the slack if any help is needed.

@sejli: Please, work with @rohan19a and provide necessary mentorship.

Best!

**Comment by rohan19a** [comment]
Hey @r1walz , I'm having a bit of trouble getting started on this issue, could you point me as to where to start (as in which files and directory I could find the root of the issue) and possible resolutions for the issue. Thanks in advance.

**Comment by r1walz** [comment]
@rohan19a : Posting my raw thoughts here, I'll revisit them later. Until then these are points to ponder:

---

1. Do we want to "early-exit" and stop compilation?

We're using [antlr](https://www.antlr.org/) and [asm](https://asm.ow2.org/) to parse and compile script which are then stored in a cache.

When AST is generated,

- we get "statement nodes" (List<[AStatement](https://github.com/opensearch-project/OpenSearch/blob/be65f543d125965d699e493933851d0cfec7e530/modules/lang-painless/src/main/java/org/opensearch/painless/node/AStatement.java#L40)>) that hold information about what kind of [statement](https://en.wikipedia.org/wiki/Statement_(computer_science)) those represent
- Statements can be of many types, [expression](https://github.com/opensearch-project/OpenSearch/blob/be65f543d125965d699e493933851d0cfec7e530/modules/lang-painless/src/main/java/org/opensearch/painless/node/SExpression.java#L43), [block/branch](https://github.com/opensearch-project/OpenSearch/blob/be65f543d125965d699e493933851d0cfec7e530/modules/lang-painless/src/main/java/org/opensearch/painless/node/SBlock.java#L45), etc
- Each concrete statement type employ different structures to parse the underlying information. Eg: [SExpression](https://github.com/opensearch-project/OpenSearch/blob/be65f543d125965d699e493933851d0cfec7e530/modules/lang-painless/src/main/java/org/opensearch/painless/node/SExpression.java#L43) defines [AExpression](https://github.com/opensearch-project/OpenSearch/blob/be65f543d125965d699e493933851d0cfec7e530/modules/lang-painless/src/main/java/org/opensearch/painless/node/AExpression.java#L40) which can represent an [assignment](https://github.com/opensearch-project/OpenSearch/blob/be65f543d125965d699e493933851d0cfec7e530/modules/lang-painless/src/main/java/org/opensearch/painless/node/EAssignment.java#L44) or [binary math operation](https://github.com/opensearch-project/OpenSearch/blob/be65f543d125965d699e493933851d0cfec7e530/modules/lang-painless/src/main/java/org/opensearch/painless/node/EBinary.java#L44) or similar.

Now, if we can figure out that we've hit a node which implies that `params` is getting "modified" (hint: assignment?) then we can early exit in the compilation phase itself.

Let's take an example of a statement: `System.exit(-1)`

During Semantic Analysis Phase, it gets loosely translated to ...

```
- userStatementNodes[0] : SExpression
  - statementNode : ECall
    - prefixNode : ESymbol
      - symbol = "System"
    - methodName = "exit"
    - argumentNodes[0] : EUnary
      - childNode : ENumeric
        - numeric = "1"
        - radix = 10
      - operation : Operation = "SUB"
        - symbol = "-"
        - name = "subtraction"
        - Enum.name = "SUB"
```

... which gives us all the ingredients to analyze what the statement is supposed to do (call `System.exit(-1)`).

Similarly, `params.rank = 2` translates to:

```
- userStatementNodes[0] : SExpression
  - statementNode : EAssignment
  - leftNode : EDot
    - prefixNode : ESymbol
      - symbol = "params"
    - index = "rank"
  - rightNode : ENumeric
    - numeric = "2"
  - operation (null)
``` 

You can start looking at how [PainlessSemanticAnalysisPhase](https://github.com/opensearch-project/OpenSearch/blob/be65f543d125965d699e493933851d0cfec7e530/modules/lang-painless/src/main/java/org/opensearch/painless/Compiler.java#L234) of compilation works.

---

2. Do we want to improve the compilation error?

Since, we have the [stacktrace](https://github.com/opensearch-project/OpenSearch/blob/fcbec24408147f9b55b71458996c1cdb6a42dfbd/modules/lang-painless/src/main/java/org/opensearch/painless/PainlessScriptEngine.java#L463), can we somehow get the information that we may have done something stupid and attach it as auxiliary information instead of posting null?

---

Honestly, I feel that we should try to pursue (2), but I don't have idea how the information can propagate up the chain.

Folk, can we have your inputs here? Thanks (@dhwanilpatel @dblock @reta)

**Comment by reta** [comment]
> Folk, can we have your inputs here? Thanks (@dhwanilpatel @dblock @reta)

I am actually not sure what is exactly the issue here. the cause is populated:
  ```
 "script_stack": [
        "java.base/java.util.Collections$UnmodifiableMap.put(Collections.java:1457)",
        "params.rank = 2\n    ",
        "      ^---- HERE"
      ],
  ``` 

And the script fails with the right exception. We could surely throw more detailed exception here (fe "The params are immubtable, ..."). What I am missing?

**Comment by r1walz** [comment]
Yes, one of the problem lies here. Maps like `params` and `ctx` have special meaning. `params` is essentially an immutable map. But, it's easy to assume that we can modify it within the script like an object to get some desired result. For someone who's not familiar with Painless's syntax, they can get confused about the origin of this param "object". It is better to educate the user that `params` isn't intended to get modified, instead of just bailing out at `unsupported operation exception` and letting user figure out that params is indeed a passed immutable map (and not plain o' object).

Another problem is that sometimes this scenario exits with `200 OK` status code which raises suspicion and points to a deeper bug.

**Comment by reta** [comment]
> Yes, one of the problem lies here. Maps like params and ctx have special meaning. params is essentially an immutable map. 

I think these two we could wrap into the variation of immutable map with more clear exception but I am not entirely convinced we need that. The documentation should state clearly that those objects are not modifiable. 

> Another problem is that sometimes this scenario exits with 200 OK status code which raises suspicion and points to a deeper bug.

This is unexpected, could we reproduce that? This is certainly an issue

**Comment by r1walz** [comment]
https://github.com/opensearch-project/OpenSearch/assets/31043830/562a7fa6-3231-47b0-a3fd-cb70e78d650c

**Comment by r1walz** [comment]
I figured what's happening ::

Consider a multi-node setup: when a shard, holding data is required to perform an update through script, receives a request on the same node, it uses a node local client to perform `shardOperation` https://github.com/opensearch-project/OpenSearch/blob/e4a1841e23dadd3351216383fdc16bf56a0b783d/server/src/main/java/org/opensearch/action/update/TransportUpdateAction.java#L216

Here, `UpdateRequest` contains `Script` with `params` Map with type `UnmodifiableMap` https://github.com/opensearch-project/OpenSearch/blob/e4a1841e23dadd3351216383fdc16bf56a0b783d/server/src/main/java/org/opensearch/script/Script.java#L560

It results in the desired effect of throwing above exception.

But, the immutability information is lost when `Script` data is passed through `StreamInput` to other nodes:

https://github.com/opensearch-project/OpenSearch/blob/e4a1841e23dadd3351216383fdc16bf56a0b783d/server/src/main/java/org/opensearch/script/Script.java#L592

https://github.com/opensearch-project/OpenSearch/blob/e4a1841e23dadd3351216383fdc16bf56a0b783d/libs/core/src/main/java/org/opensearch/core/common/io/stream/StreamInput.java#L722

A map is always read as [mutable] `HashMap` map type (unless it's empty). Neither we enforce immutability of params map in the `UpdateScript`

https://github.com/opensearch-project/OpenSearch/blob/e4a1841e23dadd3351216383fdc16bf56a0b783d/server/src/main/java/org/opensearch/script/UpdateScript.java#L56

hence, within the compile script execution, we do not encounter the exception on put call and we continue the update flow resulting in discrepancy.

**Comment by reta** [comment]
> I figured what's happening ::

Thanks a lot for figuring this one out, @r1walz !
