### ISSUE TITLE
Correct copyright notices to reflect Copyright OpenSearch Contributors

### ISSUE THREAD

**Issue by dblock** [opensearch-project/OpenSearch#1056]
Coming from https://github.com/opensearch-project/.github/issues/21.

The correct copyright for open-source projects in opensearch-project is "Copyright OpenSearch Contributors". Please correct any places that say otherwise, especially where it says copyright Amazon. Make sure NOTICE.txt and README match. See https://github.com/opensearch-project/.github/pull/24 for an example.

**Comment by wnbts** [comment]
for new source code, is this the correct header?

```
/*
 * SPDX-License-Identifier: Apache-2.0
 *
 * The OpenSearch Contributors require contributions made to
 * this file be licensed under the Apache-2.0 license or a
 * compatible open source license.
 *
 * Modifications Copyright OpenSearch Contributors. See
 * GitHub history for details.
 */
```

Or two headers like this? 
```
/*
 * SPDX-License-Identifier: Apache-2.0
 *
 * The OpenSearch Contributors require contributions made to
 * this file be licensed under the Apache-2.0 license or a
 * compatible open source license.
 *
 * Modifications Copyright OpenSearch Contributors. See
 * GitHub history for details.
 */

/*
 * Copyright 2020 Amazon.com, Inc. or its affiliates. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License").
 * You may not use this file except in compliance with the License.
 * A copy of the License is located at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * or in the "license" file accompanying this file. This file is distributed
 * on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
 * express or implied. See the License for the specific language governing
 * permissions and limitations under the License.
 */
```

**Comment by dblock** [comment]
@hyandell Can you please comment.

@wnbts Can I pleaser ask you to contribute something to https://github.com/opensearch-project/.github on this topic?

**Comment by wnbts** [comment]
sure, after i have a clear idea about this matter, i will see what service i can do.

**Comment by hyandell** [comment]
wnbts said:
> for new source code, is this the correct header?

Broad statements are always fun :) Generally speaking, yes to your first item with just the one source header block. 

My proviso would be if you're copying Apache-2.0 licensed code (or other licensed code) from software owned by other businesses at Amazon. In those cases we should make sure we are deliberate about the decision to adjust the copyright statement (or license).

**Comment by wnbts** [comment]
Thanks for your info! @hyandell.

@dblock i made a pr https://github.com/opensearch-project/.github/pull/27 to the specified repo. Does OpenSearch repo also need that change?

**Comment by dblock** [comment]
> @dblock i made a pr [opensearch-project/.github#27](https://github.com/opensearch-project/.github/pull/27) to the specified repo. Does OpenSearch repo also need that change?

Yes it does. This issue was opened to make sure the copyright is correct in the README and NOTICE, it's currently not. If you want to PR that fix, along with any changes to CONTRIBUTING, it'd be very much appreciated.
