### ISSUE TITLE
[BUG] Min aggregate of a date in Transform Job

### ISSUE THREAD

**Issue by habid-altice** [opensearch-project/OpenSearch#10565]
**Describe the bug**
When doing Min aggregate of a date field in Transform Job, it gives a long number in place of a date, it is very very disturbing because when I want to create an index pattern, it tells me that there is no field of type date.
For some indices it works as expected and for others it gives this problem. Why the way of working of min aggregate of date is not consistent.

**Comment by noCharger** [comment]
@habid-altice Could you provide more details on this bug?
- Can you share the versions of OpenSearch and any other relevant plugins you're using? 
- Are there specific configurations or mappings on the indices where you see the issue vs. where you don't?
- A small sample or replica of your data could be very helpful.
- Are there any error messages or logs that might provide more context?

**Comment by msfroh** [comment]
Closing this for now. @habid-altice, please feel free to reopen if you're still experiencing this issue. Alternatively, you may want to create an issue in https://github.com/opensearch-project/index-management.
