### ISSUE TITLE
[FEATURE] Object Storage FrozenTier / UltraWarm equivalent 

### ISSUE THREAD

**Issue by michaelandrepearce** [opensearch-project/OpenSearch#1059]
**Is your feature request related to a problem? Please describe.**
In Elastic 7.12 it is possible to directly search object storage such as AWS S3, Microsoft Azure Storage, and Google Cloud.
Like wise in AWS's as a Service offering a similar feature named UltraWarm exists, this allows decoupling from compute and storage, and enables to reduce costs significantly.

**Describe the solution you'd like**
Ability to directly search object storage, so that we can tier down data and keep it searchable to reduce operational cost. 
An initial MVP could be a single object storage api such as S3.
In longer term should really support at least the big main cloud vendors object storage api's.

**Describe alternatives you've considered**
Switch back to Elastic :( :( :( 

**Additional context**
ref: 
- https://www.elastic.co/blog/introducing-elasticsearch-frozen-tier-searchbox-on-s3
- https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/ultrawarm.html

**Comment by frotsch** [comment]
https://discuss.opendistrocommunity.dev/t/any-plans-to-backport-ultrawarm-for-amazon-elasticsearch-service/2075/4

**Comment by tlfeng** [comment]
Related issue #740 #1052

**Comment by juanpi-meli** [comment]
Hi team! Any update regarding this thread?

**Comment by tlfeng** [comment]
Include @andrross (the author of issue [#1599](https://github.com/opensearch-project/OpenSearch/issues/1599)) for visibility.

**Comment by pmarjou22** [comment]
Has anyone tried a setup including [s3fs-fuse]( https://github.com/s3fs-fuse/s3fs-fuse) for this ?

**Comment by oded-dd** [comment]
Is there a plan to make UltraWarm part of the community, or should we abandon the project.

What is in opensearch without S3 support?

**Comment by andrross** [comment]
Closing this issue as this work is being tracked in the storage roadmap (#3739). Please feel free to comment there or reopen if there are additional questions.
