### ISSUE TITLE
create repository-oci plugin for Oracle Object Storage snapshots

### ISSUE THREAD

**Issue by anders-swanson** [opensearch-project/OpenSearch#10620]
Provide OCI-native support for Oracle Object Storage as a snapshot location, using a custom plugin. The existing S3-compatible plugin works for object storage, but does not have OCI-native support for features like OKE workload identity, or instance principal authentication.

**Comment by saratvemulapalli** [comment]
@anders-swanson not sure if you looked at https://github.com/opensearch-project/opensearch-oci-object-storage.

**Comment by anders-swanson** [comment]
Looks like this resolves it, thanks!
