### ISSUE TITLE
[Remote cluster state] Optimise updating global metadata and index metadata

### ISSUE THREAD

**Issue by dhwanilpatel** [opensearch-project/OpenSearch#10645]
**Is your feature request related to a problem? Please describe.**
For remote cluster state, we are uploading global metadata and index metadata sequentially to remote store. There is scope for improvement here, as we can upload both the files in parallel. 

This will help for the cases, where global metadata and index metadata is getting updated in single cluster state update.

Meta issue: #10523

**Comment by kiranprakash154** [comment]
Hi, are we on track for this to be released in 2.12 ?

**Comment by soosinha** [comment]
This is targetted for 2.13
