### ISSUE TITLE
[BUG] Wrong error code for Painless scripts compilation thresholds

### ISSUE THREAD

**Issue by shiv0408** [opensearch-project/OpenSearch#1064]
**Describe the bug**
When compilation threshold is breached a circuit breaker exception is called and end status of the error is 500.

**To Reproduce**
1. Create a Opensearch cluster with `./gradlew -p ./distribution/archives/no-jdk-linux-tar assemble distZip  -Drepos.mavenLocal=true` and extracting the tar.
2. Add `script.disable_max_compilations_rate: false` in config/opensearch.yml
3. After running the Opensearch, change setting by runnning this command 
`curl --location --request PUT 'localhost:9200/_cluster/settings' \
--header 'Content-Type: application/json' \
--data-raw '{
    "persistent":{
        "script.max_compilations_rate": "use-context",
        "script.context.field.max_compilations_rate": "0/1m"
    }
}'`
4. Add a doc in _test_ index, using `curl --location --request POST 'localhost:9200/test/_doc/1' \
--header 'Content-Type: application/json' \
--data-raw '{
  "my_field": 10
}'`
5. Run a painless script, run `curl --location --request GET 'localhost:9200/test/_search' \
--header 'Content-Type: application/json' \
--data-raw '{
  "script_fields": {
    "my_doubled_field": {
      "script": {
        "lang":   "painless",
        "source": "return doc['\''my_field'\''].value * params.get('\''multiplier'\'');",
        "params": {
          "multiplier": 17
        }
      }
    }
  }
}'`

**Expected behaviour**
We should get error with code 429.

**Comment by minalsha** [comment]
we need to check if this would lead to any compatibility issue with regards to any feature. Dive deep into the impact of this change and We need to repro this issue.

**Comment by shiv0408** [comment]
Updated the issue with better reproduction steps.
