### ISSUE TITLE
[Meta] Upgrade Lucene

### ISSUE THREAD

**Issue by nknize** [opensearch-project/OpenSearch#1065]
- [x] Upgrade OpenSearch 2.0 to Lucene 9 snapshot (#1067)
- [x] Upgrade OpenSearch 1.x to Lucene 8.9 (#1068)

**Comment by codebrain** [comment]
Lucene 9 was released yesterday.
https://lucene.apache.org/core/corenews.html#apache-lucenetm-900-available

**Comment by nknize** [comment]
Completed by #1109 and #2487
