### ISSUE TITLE
[BUG] [Remote State] Auto Restore during remote cluster state restore can lead to split primaries in Remote Store Domains

### ISSUE THREAD

**Issue by linuxpi** [opensearch-project/OpenSearch#10658]
**Describe the bug**
- With Remote Store domains, if Remote Cluster State is enabled, after quorum loss recovery if local disk state is lost we auto restore from remote cluster state
- During this auto restore, due to network partitions isolating existing primaries can lead to replica being promoted to primary in other network partition.
- This can eventually lead to 2 primaries writing to remote.

**To Reproduce**

**Expected behavior**
Remote cluster state Auto Restore should not lead to split primaries.

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**

**Comment by shwetathareja** [comment]
@linuxpi : wondering if this should be a configuration control where user accepts the risk and wants to enable auto restore for higher availability.

**Comment by linuxpi** [comment]
> @linuxpi : wondering if this should be a configuration control where user accepts the risk and wants to enable auto restore for higher availability.

yeah, i think we can evaluate that. restoring to a green cluster is a really good state and this a very edge case. i can keep this issue open or open a new one to evaluate that
