### ISSUE TITLE
Inconsistent behavior of icu_tokenizer when indexing cyrillic followed by digit and latin

### ISSUE THREAD

**Issue by robbertbrak** [opensearch-project/OpenSearch#10663]
**Describe the bug**

When using the `icu_tokenizer`, there is inconsistent behavior when tokenizing and searching for `2BR` in documents with the phrases `россия 2BR` versus `Foo 2BR`.

**To Reproduce**

1. Create test index

```
PUT /test-index
{
  "settings": {
      "index": {
        "analysis": {
          "analyzer": {
            "icu_analyzer": {
              "tokenizer": "icu_tokenizer"
            }
          }
        }
      }
    },
  "mappings": {
    "properties": {
      "testField": {
          "type": "text",
          "analyzer": "icu_analyzer",
          "search_analyzer": "icu_analyzer"
      }
    }
  }  
}
```

2. Add the following documents to the index.

```
PUT /test-index/_doc/1
{ "testField": "россия 2BR" }

PUT /test-index/_doc/2
{ "testField": "Foo 2BR" }

PUT /test-index/_doc/3
{ "testField": "2BR" }
``` 

3. Perform a query as follows:

```
POST /text-index/_search
{
  "query": {
    "simple_query_string": {
      "query": "2BR",
      "default_operator": "and",
      "fields": ["testField"]
    }
  }
}
```

4. Result: only documents 2 and 3 are found.

**Expected behavior**
Documents 1, 2 and 3 all contain `2BR`, so they should all be found.

**Plugins**
NA

**Screenshots**
NA

**Host/Environment (please complete the following information):**
 - OS: Linux
 - Version: OpenSearch 2.5.0

**Additional context**

Note that there is a striking difference between the term vectors of documents 1 and 2.

```
GET /test-index/_termvectors/1?fields=testField
```
Resulting terms: `россия`, `2` and `BR`

```
GET /test-index/_termvectors/2?fields=testField
```
Resulting terms: `Foo` and `2BR`

I can't tell whether this difference is intential/correct. However, even if it is, I would still expect the query in step 3 of the reproduction scenario to return document 1, because the `analyzer` and `search_analyzer` of the `testField` are the same and the discrepancies in analyzing the different documents should apply both index time and query time.

**Comment by dblock** [comment]
Looks like a legit bug. Want to try to write a unit/REST YAML test for it?

**Comment by robbertbrak** [comment]
@dblock: I think the first step would be to determine what the expectations are. Is the bug in the `icu_tokenizer` or somewhere in the processing of the `simple_query_string` query?

Also, as I'm not familiar at all with the internals of OpenSearch, if I'm going to write a test, I would need some pointers in the right direction. If I understand your question correctly, you're not asking me to create a PR, just a (failing) test. Where would I commit / post such a test?

**Comment by reta** [comment]
@robbertbrak thanks for bringing that, I think the conclusion (https://github.com/elastic/elasticsearch/issues/27290#issuecomment-1768016366) is that this is Apache Lucene issue, right?

**Comment by robbertbrak** [comment]
@reta: Yes, agreed!
