### ISSUE TITLE
[Upgrade] OpenSearch 2.0 to Lucene 9.0.0 release

### ISSUE THREAD

**Issue by nknize** [opensearch-project/OpenSearch#1067]
- [x] Replace SimpleFS with NioFS filesystem format
- [x] Update analysis classpath
- [x] Fix failing tests (#2063)

**Comment by rootcfg** [comment]
Sorry for my English, but is it true that OpenSearch does not contain any elasticsearch-oss.rpm packages? In will contain it  own package with its own name?

**Comment by saratvemulapalli** [comment]
@nknize I'm compiling a list of breaking changes for 2.0 and action items for plugins, clients to gear up for the work.
Do you happen to have a clear list of changes and what artifacts could be impacted ? 

Ref: #2480

**Comment by nknize** [comment]
> Do you happen to have a clear list of changes and what artifacts could be impacted ?

We are incrementally marking PRs as `>breaking`. You should be able to use that.


Closing this issue as complete
