### ISSUE TITLE
[Optimization] [Remote state] With every election full state shouldn't get uploaded to remote

### ISSUE THREAD

**Issue by shwetathareja** [opensearch-project/OpenSearch#10682]
**Describe the bug**
Every time there is election, it bumps up the election term and full cluster state is uploaded to remote. This ensures during version upgrades and other cases, the leader uploads the full state and shouldn't face any compatibility issues. But, the downside is that it will result in uploading a large payload to remote store if the cluster state is in MBs and would result in elections taking longer.

https://github.com/opensearch-project/OpenSearch/blob/9cc0e7db3b5dfaa9b3dd111eba9d1fb4d9185549/server/src/main/java/org/opensearch/gateway/GatewayMetaState.java#L737

**Expected behavior**
There can be optimization where a nodeId with new ephemeralId uploads the full state and in other cases we can skip uploading the full state and just upload the manifest with new term and version.

**Comment by soosinha** [comment]
Removing 2.12 tag. This will be picked up later.
