### ISSUE TITLE
[BUG] Flaky Test - org.opensearch.index.shard.IndexShardTests.testCommitLevelRestoreShardFromRemoteStore 

### ISSUE THREAD

**Issue by shwetathareja** [opensearch-project/OpenSearch#10704]
**Describe the bug**
Unrelated test failure - https://build.ci.opensearch.org/job/gradle-check/28257/
https://github.com/opensearch-project/OpenSearch/actions/runs/6561400970/job/17821007893?pr=10535

PR where encountered the failure - https://github.com/opensearch-project/OpenSearch/pull/10535

**Comment by shwetathareja** [comment]
@sachinpkale can you take a look

**Comment by sachinpkale** [comment]
Taking a look

**Comment by shwetathareja** [comment]
Failed here again - https://github.com/opensearch-project/OpenSearch/pull/12825#issuecomment-2012211470

**Comment by reta** [comment]
Closing in favour of https://github.com/opensearch-project/OpenSearch/issues/14321
