### ISSUE TITLE
[BUG] "max_analyzer_offset" highlight query setting not working for plain highlighter

### ISSUE THREAD

**Issue by drunken-monkey** [opensearch-project/OpenSearch#10702]
**Describe the bug**
The new [`highlight.max_analyzer_offset` query setting](https://opensearch.org/docs/2.11/search-plugins/searching-data/highlight/) (introduced in #3893) is not documented to be specific to the `unified` highlighter, but it appears to be ignored when using the `plain` highlighter.

**To Reproduce**
1. Create an index with a very low `index.highlight.max_analyzed_offset` setting (say, 100) and at least one text field (e.g., `text`)
2. Index a document with a `text` value exceeding that limit
3. Send a search request (matching that document) with `"highlight":{"fields":{"text":{}},"max_analyzer_offset":100,"type":"plain"}`
4. An error is returned: `The length of [text] field of [DOC] doc of [INDEX] index has exceeded [100] - maximum allowed to be analyzed for highlighting. This maximum can be set by changing the [index.highlight.max_analyzed_offset] index level setting. For large texts, indexing with offsets or term vectors, and highlighting with unified or fvh highlighter is recommended!`

```
INDEX='https://localhost:9200/test-index'
curl -X PUT "$INDEX?pretty" -H 'Content-type: application/json' -d '{"settings":{"index.highlight.max_analyzed_offset":100}}'
curl -X PUT "$INDEX/_doc/test?refresh=true&pretty" -H 'Content-type: application/json' -d '{"text":"foo bar baz foo bar baz foo bar baz foo bar baz foo bar baz foo bar baz foo bar baz foo bar baz foo bar baz"}'
curl -X POST "$INDEX/_search?pretty" -H 'Content-type: application/json' -d '{"query":{"match":{"text":"bar"}},"highlight":{"fields":{"text":{}},"max_analyzer_offset":100,"type":"plain"}}'

```

**Expected behavior**
The search is successful and returns highlighted snippets for the field value’s first 100 characters. This is the behavior actually observed when removing `,"type":"plain"` from the above search request: `curl -X POST "$INDEX/_search?pretty" -H 'Content-type: application/json' -d '{"query":{"match":{"text":"bar"}},"highlight":{"fields":{"text":{}},"max_analyzer_offset":100}}'`

**Host/Environment:**
 - OS: Linux
 - Version: 2.9.0

**Comment by dblock** [comment]
@drunken-monkey Want to try to turn this in a YAML REST (failing) test?

**Comment by drunken-monkey** [comment]
@dblock First time contributing to this project, but I tried my best. (Fingers crossed that the test actually fails, didn’t manage to run tests locally.)

**Comment by sdesbiens** [comment]
I'm also experiencing this issue. I was doing some testing, and on top of the **_max_analyzer_offset_** option being ignored with the **_plain_** highlighter, it seems like it also ignores this option with the _**unified**_ highlighter as well if the mapping for the highlighted field includes: **_"index_options": "offsets"_**.

**Comment by dblock** [comment]
@sdesbiens I see @drunken-monkey contributed a failing test in https://github.com/opensearch-project/OpenSearch/pull/10919, maybe you want to try to fix it?
