### ISSUE TITLE
[BUG] Passing wrong parameter when calling newConfigurationException method in DotExpanderProcessor

### ISSUE THREAD

**Issue by gaobinlong** [opensearch-project/OpenSearch#10734]
**Describe the bug**
The first parameter of the method [ConfigurationUtils.newConfigurationException()](https://github.com/opensearch-project/OpenSearch/blob/7936f94ef6692516c58f4c46a8a3747da9cd9f1d/server/src/main/java/org/opensearch/ingest/ConfigurationUtils.java#L399) is `processorType`, but `DotExpanderProcessor` passes [wrong parameter ](https://github.com/opensearch-project/OpenSearch/blob/7936f94ef6692516c58f4c46a8a3747da9cd9f1d/modules/ingest-common/src/main/java/org/opensearch/ingest/common/DotExpanderProcessor.java#L121)when calling it, even though it doesn't affect the response of the API.

**To Reproduce**
1. Create a ingest pipeline with dot_expander processor, and the value of `field` doesn't contain a dot:
```
PUT _ingest/pipeline/test2
{
  "processors": [
      {
        "dot_expander": {
          "field": "foobar"
        }
      }
    ]
}
```
The response has correct processor type:
```
{
  "error": {
    "root_cause": [
      {
        "type": "parse_exception",
        "reason": "[field] field does not contain a dot",
        "processor_type": "dot_expander",
        "property_name": "field"
      }
    ],
    "type": "parse_exception",
    "reason": "[field] field does not contain a dot",
    "processor_type": "dot_expander",
    "property_name": "field"
  },
  "status": 400
}
```

**Expected behavior**
Correct the first parameter when calling newConfigurationException method in DotExpanderProcessor

**Host/Environment (please complete the following information):**
 - OS: [macOS]
 - Version [2.9]

**Comment by rblcoder** [comment]
Is it that "reason": "[field] field does not contain a dot" should be "[foobar] field does not contain a dot" ?

**Comment by gaobinlong** [comment]
Fixed by https://github.com/opensearch-project/OpenSearch/pull/10737.
