### ISSUE TITLE
Search stats for coordinator node misses total search request time

### ISSUE THREAD

**Issue by jainankitk** [opensearch-project/OpenSearch#10768]
Currently, the coordinator node only publishes the phase breakdown metrics. It should also publish the total search request time as part of node stats on the coordinator node

Related #8381, #8386

**Comment by jainankitk** [comment]
@dzane17 - Are you able to take stab at this one?

**Comment by msfroh** [comment]
Is this likely to be different from the `took` time? If so, how?

**Comment by msfroh** [comment]
> Is this likely to be different from the `took` time? If so, how?

Oh... This is for the stats as opposed to the debugging info reported in SearchResponse?

**Comment by jainankitk** [comment]
> Oh... This is for the stats as opposed to the debugging info reported in SearchResponse?

Yeah, I missed that in the initial PR!

**Comment by dzane17** [comment]
Yes, I will take care of it

**Comment by jainankitk** [comment]
@dzane17 - Have we already addressed this issue?

**Comment by sandeshkr419** [comment]
@dzane17 Are you still working on this?

**Comment by dzane17** [comment]
No, the team has decided to deprioritize this for now. I will unassign myself.

**Comment by jainankitk** [comment]
As per offline discussion, @dzane17 should be able to prioritize this for 2.17. Reassigning

**Comment by dzane17** [comment]
@jainankitk Can you confirm what the final output should look like. I have added the `took` section below as a proposal. I think it should be within the "request" object since this is where we keep all coordinator-level metrics. But the name should distinguish it from other metrics within "request" which are per phase.

```
...
      "indices" : {
        "search" : {
          "open_contexts" : 0,
          "query_total" : 4,
          "query_time_in_millis" : 22,
          "query_current" : 0,
          "concurrent_query_total" : 0,
          "concurrent_query_time_in_millis" : 0,
          "concurrent_query_current" : 0,
          "concurrent_avg_slice_count" : 0.0,
          "fetch_total" : 4,
          "fetch_time_in_millis" : 3,
          "fetch_current" : 0,
          "scroll_total" : 0,
          "scroll_time_in_millis" : 0,
          "scroll_current" : 0,
          "point_in_time_total" : 0,
          "point_in_time_time_in_millis" : 0,
          "point_in_time_current" : 0,
          "suggest_total" : 0,
          "suggest_time_in_millis" : 0,
          "suggest_current" : 0,
          "search_idle_reactivate_count_total" : 0,
          "request" : {
            "took" : {
              "time_in_millis" : 71,
              "current" : 0,
              "total" : 2
            },
            "dfs_pre_query" : {
              "time_in_millis" : 0,
              "current" : 0,
              "total" : 0
            },
            "query" : {
              "time_in_millis" : 68,
              "current" : 0,
              "total" : 2
            },
            "fetch" : {
              "time_in_millis" : 3,
              "current" : 0,
              "total" : 2
            },
            "dfs_query" : {
              "time_in_millis" : 0,
              "current" : 0,
              "total" : 0
            },
            "expand" : {
              "time_in_millis" : 0,
              "current" : 0,
              "total" : 2
            },
            "can_match" : {
              "time_in_millis" : 0,
              "current" : 0,
              "total" : 0
            }
          }
        }

```

**Comment by jainankitk** [comment]
`took` sounds correct to me since it correlates directly with the client search request `took` time
