### ISSUE TITLE
Fix logging for the nodes with remote store attributes

### ISSUE THREAD

**Issue by dhwanilpatel** [opensearch-project/OpenSearch#10809]
**Is your feature request related to a problem? Please describe.**
For Remote store enabled nodes, we add multiple remote store related attributes in node. Those all attributes are getting logged in logs when node's information is being logged. 

It is creating too much noise in logs, and for the logs where multiple node's information is logged in single line it will be too long log lines.

**Fix**
We can redact the node attributes from the logs. We can remove those attribute from `toString` method of DiscoveryNode.

Meta issue: #10523

**Comment by linuxpi** [comment]
Closing as https://github.com/opensearch-project/OpenSearch/pull/10810 is merged
