### ISSUE TITLE
[BUG] Flaky test: org.opensearch.search.suggest.CompletionSuggestSearchIT.testSkipDuplicates

### ISSUE THREAD

**Issue by dhwanilpatel** [opensearch-project/OpenSearch#10808]
**Describe the bug**
Flaky test : [org.opensearch.search.suggest.CompletionSuggestSearchIT.testSkipDuplicates](https://build.ci.opensearch.org/job/gradle-check/28616/testReport/junit/org.opensearch.search.suggest/CompletionSuggestSearchIT/testSkipDuplicates__p0___search_concurrent_segment_search_enabled___true___/)

Found in this [build](https://build.ci.opensearch.org/job/gradle-check/28616/) of [PR](https://github.com/opensearch-project/OpenSearch/pull/10784)

**Comment by ashking94** [comment]
There is an issue already created for this - https://github.com/opensearch-project/OpenSearch/issues/10798. Closing this one.
