### ISSUE TITLE
[BUG] Flaky test org.opensearch.indices.replication.SegmentReplicationSuiteIT.testDropRandomNodeDuringReplication

### ISSUE THREAD

**Issue by dhwanilpatel** [opensearch-project/OpenSearch#10813]
**Describe the bug**
Flaky test : [org.opensearch.indices.replication.SegmentReplicationSuiteIT.testDropRandomNodeDuringReplication](https://build.ci.opensearch.org/job/gradle-check/28672/testReport/junit/org.opensearch.indices.replication/SegmentReplicationSuiteIT/testDropRandomNodeDuringReplication/)

Discovered in [build](https://build.ci.opensearch.org/job/gradle-check/28672/) of [PR](https://github.com/opensearch-project/OpenSearch/pull/10810).

**To Reproduce**
REPRODUCE WITH: `./gradlew ':server:internalClusterTest' --tests "org.opensearch.indices.replication.SegmentReplicationSuiteIT.testDropRandomNodeDuringReplication" -Dtests.seed=7F27855F0B132950 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=uk-UA -Dtests.timezone=SystemV/EST5 -Druntime.java=20`

**Comment by ashking94** [comment]
https://github.com/opensearch-project/OpenSearch/issues/9499 is already tracking the flaky test. Closing this.
