### ISSUE TITLE
Upgrade to Lucene 9.9

### ISSUE THREAD

**Issue by msfroh** [opensearch-project/OpenSearch#10877]
This is a tracking issue that we can use to document changes associated with the upgrade to Lucene 9.9 (to happen at some point in the future, once Lucene 9.9 is released), where we expect to see or have measured changes.

As folks review pending changes in https://github.com/apache/lucene/blob/branch_9x/lucene/CHANGES.txt, they should add comments for Lucene changes that they are following, and discuss the expected impact to OpenSearch. We will probably create spin-off issues for changes that require more detailed investigation to measure impact.

We can resolve this issue when we do eventually upgrade to Lucene 9.9 on the 2.x branch. At that point, we should have accumulated notes (and benchmark results) that will explain what upgrading to Lucene 9.9 means for OpenSearch users.

**Comment by mch2** [comment]
related https://github.com/opensearch-project/OpenSearch/issues/11414

**Comment by reta** [comment]
Closing along with https://github.com/opensearch-project/OpenSearch/issues/11414
