### ISSUE TITLE
[BUG] ChildQuerySearchIT.testAliasesFilterWithHasChildQuery is flaky - suite timeout was reached

### ISSUE THREAD

**Issue by peternied** [opensearch-project/OpenSearch#10884]
**Describe the bug**
`org.opensearch.join.query.ChildQuerySearchIT.testAliasesFilterWithHasChildQuery` test is flaky. 

#### Stacktrace
```
java.lang.Exception: Test abandoned because suite timeout was reached.
	at __randomizedtesting.SeedInfo.seed([AABBFC4C7FB026AC]:0)
```

```
java.lang.Exception: Suite timeout exceeded (>= 1200000 msec).
```

**To Reproduce**
CI - https://build.ci.opensearch.org/job/gradle-check/28624/testReport/org.opensearch.join.query/ChildQuerySearchIT/testAliasesFilterWithHasChildQuery__p0___search_concurrent_segment_search_enabled___true___/

**Expected behavior**
Test should always pass

**Comment by peternied** [comment]
Impacted https://github.com/opensearch-project/OpenSearch/pull/10800#issuecomment-1773218358

**Comment by sandeshkr419** [comment]
Closing this issue since we haven't been seeing this test as flaky for a while and if it happens again then `opensearch-ci-bot` will open up the issue back automatically.
