### ISSUE TITLE
[BUG] [Remote State] During construction of valid chain we skip valid cluster UUIDs if the are previousClusterUUIDs for invalid UUIDs

### ISSUE THREAD

**Issue by linuxpi** [opensearch-project/OpenSearch#10911]
**Describe the bug**
During construction of valid chain we skip valid cluster UUIDs if the are previousClusterUUIDs for invalid UUIDs

**To Reproduce**
1. Create a single node cluster. 
2. UUID1 is committed to remote
3. Replace the node
4. UUID2 is formed and committed. previousClusterUUID is UUID1
5. Replace the node again.
6. UUID3 is formed and published. previousClusterUUID is UUID2
7. Before committing the UUID3 in remote(precommit), replace the node again
8. The new nodes comes up, it will not consider any of the uuids in remote as valid.

**Expected behavior**
Chaining logic should not discard any valid cluster UUIDs which can be start of the final valid chain.

**Comment by soosinha** [comment]
I am working on this.
