### ISSUE TITLE
Rename artifact produced by the build to include -min

### ISSUE THREAD

**Issue by dblock** [opensearch-project/OpenSearch#1094]
**Is your feature request related to a problem? Please describe.**

Coming from https://github.com/opensearch-project/opensearch-build/issues/212, the output of `./gradlew :distribution:archives:linux-tar:assemble` produces a file called `opensearch-1.1.0-SNAPSHOT-linux-x64.tar.gz`. Then we rename it to `-min`, ie. `opensearch-min-1.1.0-SNAPSHOT-linux-x64.tar.gz`. 

**Describe the solution you'd like**

Rename output to always include `-min`.

**Comment by xuezhou25** [comment]
🙌
