### ISSUE TITLE
[BUG] Broken Upgrade from 2.7 to 2.9 for Indices with GeoShape mappings

### ISSUE THREAD

**Issue by mgodwan** [opensearch-project/OpenSearch#10958]
**Describe the bug**

**To Reproduce**
1. Create an index in OS 2.7
```
PUT testindex
{
  "mappings": {
    "properties": {
      "location": {
        "type": "geo_shape"
      }
    }
  }
}

```

2. Add documents to the index

```
POST testindex/_doc
{
  "location" : {
    "type" : "point",
    "coordinates" : [74.00, 40.71]
  }
}
```

3. Ensure segments are persisted `POST testindex/_refresh` , `POST testindex/_flush` 
4. Upgrade the cluster to OS 2.9
5. Try ingesting the document with geo shape fields again on the same index. Following error is seen:

```
{
  "error": {
    "root_cause": [
      {
        "type": "illegal_argument_exception",
        "reason": "cannot change field \"location\" from doc values type=NONE to inconsistent doc values type=BINARY"
      }
    ],
    "type": "illegal_argument_exception",
    "reason": "cannot change field \"location\" from doc values type=NONE to inconsistent doc values type=BINARY"
  },
  "status": 400
}
```

**Expected behavior**
Indexing Requests should go through

**Screenshots**
NA

**Host/Environment (please complete the following information):**
 - OS: t3.medium AL2
 - Version: OS 2.9

**Additional context**
Refer `To Reproduce`

**Comment by mgodwan** [comment]
Seems related to the PR: https://github.com/opensearch-project/OpenSearch/pull/4266 where docValues have been enabled by default for geo_shape fields due to which Lucene is throwing [error](https://github.com/apache/lucene/blob/branch_9x/lucene/core/src/java/org/apache/lucene/index/FieldInfo.java#L275-L293)

**Comment by mgodwan** [comment]
@navneet1v @nknize @heemin32 Any thoughts on this?

**Comment by navneet1v** [comment]
@mgodwan can we do the re-indexing as of now to remove the issue. Meanwhile I can see if there is a way to get around this problem?

**Comment by mgodwan** [comment]
Yes, that is a possible workaround which I was able to validate.

**Comment by navneet1v** [comment]
Closing this issue as the changes are merged and backported till 2.11.1 .

**Comment by tmturpi** [comment]
What version of OpenSearch resolves this issue?  We indexing did not resolve the issue for our team.

**Comment by navneet1v** [comment]
@tmturpi you can either use Opensearch version 2.11.1 or greater.
