### ISSUE TITLE
[BUG] Flaky test org.opensearch.action.search.SearchRequestTests.testEqualsAndHashcode

### ISSUE THREAD

**Issue by dhwanilpatel** [opensearch-project/OpenSearch#10988]
**Describe the bug**
Flaky test: [org.opensearch.action.search.SearchRequestTests.testEqualsAndHashcode](https://build.ci.opensearch.org/job/gradle-check/29218/testReport/junit/org.opensearch.action.search/SearchRequestTests/testEqualsAndHashcode/)

Discovered in [PR](https://github.com/opensearch-project/OpenSearch/pull/10984) and [build](https://build.ci.opensearch.org/job/gradle-check/29218/)

**To Reproduce**
REPRODUCE WITH: `./gradlew ':server:test' --tests "org.opensearch.action.search.SearchRequestTests.testEqualsAndHashcode" -Dtests.seed=8549570A59952751 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=es-PA -Dtests.timezone=Eire -Druntime.java=17`

**Comment by sandeshkr419** [comment]
Closing this issue since we haven't been seeing this test as flaky for a while and if it happens again then `opensearch-ci-bot` will open up the issue back automatically.
