### ISSUE TITLE
[BUG] Flaky test org.opensearch.remotestore.RemoteStoreStatsIT.testNonZeroPrimaryStatsOnNewlyCreatedIndexWithZeroDocs

### ISSUE THREAD

**Issue by dhwanilpatel** [opensearch-project/OpenSearch#10983]
**Describe the bug**
Flaky test: [org.opensearch.remotestore.RemoteStoreStatsIT.testNonZeroPrimaryStatsOnNewlyCreatedIndexWithZeroDocs](https://build.ci.opensearch.org/job/gradle-check/29209/testReport/junit/org.opensearch.remotestore/RemoteStoreStatsIT/testNonZeroPrimaryStatsOnNewlyCreatedIndexWithZeroDocs/)

Identified in [PR](https://github.com/opensearch-project/OpenSearch/pull/10968) and [build](https://build.ci.opensearch.org/job/gradle-check/29209/)

**To Reproduce**
REPRODUCE WITH: `./gradlew ':server:internalClusterTest' --tests "org.opensearch.remotestore.RemoteStoreStatsIT.testNonZeroPrimaryStatsOnNewlyCreatedIndexWithZeroDocs" -Dtests.seed=ECF0590CAE225982 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=ar-EG -Dtests.timezone=Europe/Ulyanovsk -Druntime.java=20
NOTE: leaving temporary files on disk at: /var/jenkins/workspace/gradle-check/search/server/build/testrun/internalClusterTest/temp/org.opensearch.remotestore.RemoteStoreStatsIT_ECF0590CAE225982-001`

**Comment by astute-decipher** [comment]
Taking look
