### ISSUE TITLE
[BUG] Failure in org.opensearch.remotestore.SegmentReplicationUsingRemoteStoreIT.testIndexReopenClose

### ISSUE THREAD

**Issue by ashking94** [opensearch-project/OpenSearch#10987]
**Describe the bug**
`org.opensearch.remotestore.SegmentReplicationUsingRemoteStoreIT.testIndexReopenClose` test failed. I am not sure at this point if this has happened earlier. But the PR as such does not have any change which would fail this test. 

**To Reproduce**
CI build - https://build.ci.opensearch.org/job/gradle-check/29219/

**Expected behavior**
Test must pass

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**

**Comment by reta** [comment]
Closing in favour https://github.com/opensearch-project/OpenSearch/issues/14329
