### ISSUE TITLE
[Ehancement] Enable half_float field sort query point based optimization.

### ISSUE THREAD

**Issue by gashutos** [opensearch-project/OpenSearch#10998]
Introduce `HalfFloatValueSoourceComparator` & `HalfFloatComparator` similar to https://github.com/gashutos/OpenSearch/blob/main/server/src/main/java/org/opensearch/index/search/comparators/UnsignedLongComparator.java & https://github.com/gashutos/OpenSearch/blob/main/server/src/main/java/org/opensearch/search/aggregations/bucket/composite/UnsignedLongValuesSource.java to make it work.

**Comment by macohen** [comment]
@gashutos are you interested in picking this up?

**Comment by gashutos** [comment]
@macohen Its already done, forgot to close issue :(.
