### ISSUE TITLE
[Remote State] Make manifest files cleanup less aggressive

### ISSUE THREAD

**Issue by linuxpi** [opensearch-project/OpenSearch#10990]
**Is your feature request related to a problem? Please describe.**
- We trigger manifest files deletion task on every manifest update
- Evaluate if we can control how frequently we need to execute deletion
- Also ensure last 10 cluster state update manifest are retained in remote

**Comment by kiranprakash154** [comment]
Hi, are we on track for this to be released in 2.12 ?

**Comment by soosinha** [comment]
Removing 2.12 tag. This will be picked up later

**Comment by soosinha** [comment]
Resolving in favor of #12889
