### ISSUE TITLE
Search Query Categorization (Phase 2)

### ISSUE THREAD

**Issue by deshsidd** [opensearch-project/OpenSearch#11040]
This is a followup on the Search Query Categorization (Phase 1):
https://github.com/opensearch-project/OpenSearch/issues/10250

**During Phase 1, the following enhancements were implemented:**
- Logging of query shape as a trace log.
- Capture of query type information and level information for each query and sub-query for select query types (Bool, Function Score, Match, Multi-Match, Match Phrase, QueryString, Range, Regex, Term, Wildcard).
- Recording of top-level query type information for Sort and Aggregation queries.
- Capturing the order of the sort queries (asc, desc).
- Integration with the Metrics Framework.

**In Phase 2, our objectives include:**
- Expanding the capture of query type and level information to encompass additional query types.
- Extracting field-related information, specifically the number and types of fields involved in the queries (Not done)
- Identifying and documenting the types of aggregations applied.
- Incorporating the number and types of fields as part of the response data (Not done)

We welcome any feedback or suggestions for additional information that can be included in Phase 2 of this initiative.

**Comment by deshsidd** [comment]
cc @getsaurabh02

**Comment by kiranprakash154** [comment]
Hi, are we on track for this to be released in 2.12 ?

**Comment by deshsidd** [comment]
Yes, this is released in 2.12. Closing this issue for now. Will iteratively add more metrics on the search path and will add these as future issues.
