### ISSUE TITLE
[BUG] Deprecation message spamming logs from Security plugin

### ISSUE THREAD

**Issue by vamshin** [opensearch-project/OpenSearch#1108]
**Describe the bug**
Deprecation message spamming the logs
```

**To Reproduce**
Steps to reproduce the behavior:
1. Stream logs from logstash to OpenSearch with username, password. 

**Expected behavior**
No spamming of logs

**Comment by dblock** [comment]
> Based on [elastic/elasticsearch#63274](https://github.com/elastic/elasticsearch/pull/63274) the warning should only be enabled for SNAPSHOT builds.

Help me find code that supposedly would enable the deprecation logger in snapshot builds?

**Comment by VachaShah** [comment]
The warning is being logged from: https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/cluster/metadata/IndexNameExpressionResolver.java#L368

Tried to apply custom log level while logging deprecation warnings and change the log level of the deprecation log but that would result in this warning not being printed if the log level threshold is lower.

Raised a PR to avoid logging the warning multiple times.

**Comment by dblock** [comment]
This entire method should then be deprecated. Who is calling it?

**Comment by VachaShah** [comment]
> This entire method should then be deprecated. Who is calling it?

Found a lot of instances that use the IndexNameExpressionResolver which uses the check method for system indices access.

**Comment by aw-was-here** [comment]
FWIW, under OpenDistro 1.13.2:

* single node -> no spam
* 3-node master+1 node kibana -> 5 messages every 30 seconds on every ES node

I was planning on doing 1.11.0 (what we currently have deployed) -> 1.13.2 (wait 2 weeks) -> OpenSearch 1.x.x but this log spam is going to make it nearly impossible.  Is there anything we can do to shut it up?

**Comment by dblock** [comment]
I don't know about workarounds, but possibly there's a way to disable the logger in log4j configuration?

@VachaShah is working on a solution in https://github.com/opensearch-project/OpenSearch/pull/1537

**Comment by aw-was-here** [comment]
For those of you that need a fix now, this issue was already discussed by the community a while back:

https://discuss.opendistrocommunity.dev/t/upgrading-from-odfe-1-11-0-to-1-12-0-deprection-logs-complain-about-a-lot/4389/4

**Comment by fandigunawan** [comment]
Hi everyone, I got this kind of message on OpenSearch 1.2.3
This message log perhaps will help to reproduce the bug.
`
2022-01-24 11:57:50,736 [WARN] from org.elasticsearch.client.RestClient in I/O dispatcher 2 - request [POST https://orch-db-node-2:9200/imt-orch_6/_search?scroll=60000ms] returned 1 warnings: [299 OpenSearch-1.2.3-8a529d7733432bc45baa5ac1c4ba3b2741b57dac "this request accesses system indices: [.opendistro_security], but in a future major version, direct access to system indices will be prevented by default"]
`

**Comment by dblock** [comment]
@fandigunawan The original issue is that you would see this message a ton of times. This was fixed in https://github.com/opensearch-project/OpenSearch/pull/1537. Are you still seeing this log many times in 1.2.3?
