### ISSUE TITLE
[Action Required] Ensure 2.11 branch readiness for 2.11.1 release

### ISSUE THREAD

**Issue by gaiksaya** [opensearch-project/OpenSearch#11094]
Coming from https://github.com/opensearch-project/opensearch-build/issues/4161

## What is happening?
We are planning `2.11.1` release in upcoming few weeks. Following the semver guildelines and branching strategy, this release will be based on `2.11` as a reference branch

## Why?
1. We need this release because of a critical breaking bug in the [security plug-in](https://github.com/opensearch-project/OpenSearch/issues/10802). This bug impacts everyone using logstash and the only work around is to turn off compression (which is expensive) 

1.  As a refresher, our normal process is to commit changes to main, then backport to 2.x. Since the 1.0 release, we only backport bug fixes and security changes to the current 2.x branch (in this case 2.11) so that if we need to we can quickly do a patch release. 

1. There are two reason we don’t back port features to the current release branch (right now 2.11):
    1. Because we want patch release to be as thin as possible, and the more changes you make, the more verification we need to do
    1. Adding features in a patch breaks semver.

However, looking at the list of changes for 2.11, we currently have a mix of [features that have been merged in](https://github.com/opensearch-project/opensearch-build/issues/4161#issuecomment-1788089723). After providing several options and discussing with all the component teams as well as community we came to the [conclusion](https://github.com/opensearch-project/opensearch-build/issues/4161#issuecomment-1793259396) of reverting all feature related changes from 2.11 branch.

## What do I need to do?
Please help revert all the commits that are related to new features or enhancements from 2.11 branch that were added after 2.11.0 release. 
[Here](https://github.com/opensearch-project/opensearch-build/issues/4161#issuecomment-1788089723) is a rough list of commits that went in after 2.11.0 release for each repo.

## Status
Please check-mark one of the below and close this issue once the action item is completed.

- [ ] We confirm that no features or enhancements were added to 2.11 branch. We are good to go for 2.11.1 consisting only of bug fixes and security fixes.

**OR** 

- [ ] We have reverted all the feature or ehancement related commits from 2.11 branch. We are good to go for 2.11.1 consisting only of bug fixes and security fixes.

Thank you!
cc: @bbarani @CEHENKLE @Divyaasm

**Comment by reta** [comment]
There are 3 changes merged in 2.11 that I think are legitimate and should not be reverted:
- https://github.com/opensearch-project/OpenSearch/pull/10677: this is a change to unblock Github action checks (due to `No space left on device`) 
- https://github.com/opensearch-project/OpenSearch/pull/11005: this is a bugfix that was found late and was agreed to be delivered in 2.11.1 (see please Slack thread https://opensearch.slack.com/archives/C0561HRK961/p1698428388137519)
- https://github.com/opensearch-project/OpenSearch/pull/10719: fix for release notes

I believe OpenSearch core for 2.11.1 is a good shape and does not require any reverts.

**Comment by bowenlan-amzn** [comment]
We confirm that no features or enhancements were added to 2.11 branch. We are good to go for 2.11.1 consisting only of bug fixes and security fixes.
