### ISSUE TITLE
Fix tests running with slice count of 1 for concurrent search use-case

### ISSUE THREAD

**Issue by neetikasinghal** [opensearch-project/OpenSearch#11120]
There are a bunch of tests that are running with slice count of 1 for the concurrent search use-case. The goal of this task is to track the the tests here and fix the number of slices by including the index random function introduced in [1].

- [1] Introduction of issue #11119

### Exit Criteria
- [ ] https://github.com/opensearch-project/OpenSearch/pull/11093
- [ ] https://github.com/opensearch-project/OpenSearch/pull/11076
- [ ] https://github.com/opensearch-project/OpenSearch/pull/11117
- [ ] https://github.com/opensearch-project/OpenSearch/pull/11119
- [ ] https://github.com/opensearch-project/OpenSearch/pull/11118

**Comment by neetikasinghal** [comment]
PRs fixing this: 

- https://github.com/opensearch-project/OpenSearch/pull/11093
- https://github.com/opensearch-project/OpenSearch/pull/11076
- https://github.com/opensearch-project/OpenSearch/pull/11117
- https://github.com/opensearch-project/OpenSearch/pull/11119

**Comment by jed326** [comment]
- https://github.com/opensearch-project/OpenSearch/pull/11118

**Comment by jed326** [comment]
Pending backports:
- https://github.com/opensearch-project/OpenSearch/pull/11199
- https://github.com/opensearch-project/OpenSearch/pull/11203
- https://github.com/opensearch-project/OpenSearch/pull/11202
- https://github.com/opensearch-project/OpenSearch/pull/11204

**Comment by jed326** [comment]
Last one 🙂
- https://github.com/opensearch-project/OpenSearch/pull/11259

**Comment by jed326** [comment]
All the relevant PRs have been merged, so closing out this issue
