### ISSUE TITLE
Composite aggregation cannot be used under a filter aggregation

### ISSUE THREAD

**Issue by myronmarston** [opensearch-project/OpenSearch#11131]
**Is your feature request related to a problem? Please describe.**

I'd like to be able to use a `composite` aggregation underneath a `filter` aggregation.  However, when I attempt to do so, I get a response from OpenSearch like this:

```json
{
  "type": "illegal_argument_exception",
  "reason": "[composite] aggregation cannot be used with a parent aggregation of type: [FilterAggregatorFactory]"
}
```

Specifically, I'm trying to use both of these under a `nested` aggregation so that I can filter the `nested` documents included in the aggregation, and then bucket the nested documents using a `composite` aggregation so that I can paginate over the buckets.

**Describe the solution you'd like**

I'd like a `composite` aggregation to work under a `filter` aggregation rather than returning an exception.

**Describe alternatives you've considered**

* I've considered using an alternative to the `composite` aggregation (e.g. `multi_terms`) but only the composite aggregation supports pagination, which I need here.
* I've considered trying to avoid using the `filter` aggregation, but I can't find a way to avoid it.  A top level `query` can often be used instead of a `filter` aggregation, but I don't believe there's a way to make that work for nested documents in the way I need. I need to limit which `nested` documents are included in the `composite` aggregation after already applying a filter at the top level `query` to select which root documents are included to begin with.

**Additional context**

Elasticsearch gained support for this in Elasticsearch 7.13. I'm hoping OpenSearch can add support as well.

**Comment by macohen** [comment]
Adding labels to this. @myronmarston, thanks for opening the issue. Just to check, are you interested in provide a failing test for this case?

**Comment by myronmarston** [comment]
@macohen can you point me to an example test case showing what form you'd want a failing test case in?  I'm a total newcomer to the codebase, so a pointer would be helpful.

**Comment by noCharger** [comment]
@myronmarston  There are a bunch of them under https://github.com/opensearch-project/OpenSearch/tree/6bc0cd68e25d63d31d735634b9edfc76ca4f1749/rest-api-spec/src/main/resources/rest-api-spec/test/search.aggregation, for example https://github.com/opensearch-project/OpenSearch/blob/6bc0cd68e25d63d31d735634b9edfc76ca4f1749/rest-api-spec/src/main/resources/rest-api-spec/test/search.aggregation/50_filter.yml
