### ISSUE TITLE
MetricBeat support in OpenSearch

### ISSUE THREAD

**Issue by GabiKalaora** [opensearch-project/OpenSearch#11172]
**Describe the bug**
MetricBeat support in OpenSearch, metricbeat is compatible with openserach only until metricbeat version 7.12.1 this version is old and full of vulnerabilities, I would wish that opensearch will support later versions of metricbeat.
**To Reproduce**
run scans on beats/metricbeat-oss:7.12.1 image

**Expected behavior**
opensearch is compatible for all metricbeat versions

**Additional context**
are they any future plan to let opensearch and metricbeat later versions work as expected?

**Comment by msfroh** [comment]
Unless I'm mistaken, wouldn't MetricBeat need to support publication to OpenSearch?

OpenSearch has bulk / indexing APIs that various client applications can call. For example, there is an actively maintained OpenSearch sink for Prometheus: https://github.com/Aiven-Open/prometheus-exporter-plugin-for-opensearch

**Comment by dblock** [comment]
I'm going to close this, please open an issue with metricbeat or let us know if you think there's anything OpenSearch can do @GabiKalaora!
