### ISSUE TITLE
Translog Functionality Documentation

### ISSUE THREAD

**Issue by anasalkouz** [opensearch-project/OpenSearch#1118]
**Is your feature request related to a problem? Please describe.**
We need to dive deep into the the source code to have better understanding of Translog logic. How it works? what are the affected components? Downstream/Upstream dependencies?

**Describe the solution you'd like**
Write a doc that describe in details how translog works, with code snippets.
   
**Describe alternatives you've considered**
TBD - A clear and concise description of any alternative solutions or features you've considered.

**Additional context**
TBD - Add any other context or screenshots about the feature request here.

**Comment by mch2** [comment]
This documentation is a first step in understanding what is required involved in modularizing document replication.  I think this issue should be part of a higher level meta to build out that proposal.

We can also put a separate issue in documentation-website to include a section on this behavior.

**Comment by anasalkouz** [comment]
@mch2 can you post your findings and close the issue.

**Comment by mch2** [comment]
Closing this as outdated.  Translog functionality is already documented in #1319 .
