### ISSUE TITLE
[BUG] Error invoking _stats with expand_wildcards on closed indices

### ISSUE THREAD

**Issue by mch2** [opensearch-project/OpenSearch#11180]
**Describe the bug**
The `expand_wildcards` parameter has the following options according to [docs](https://opensearch.org/docs/latest/api-reference/index-apis/stats/): 
```
- all: Expand to all open and closed indexes, including hidden indexes.
- open: Expand to open indexes.
- closed: Expand to closed indexes.
- hidden: Include hidden indexes when expanding. Must be combined with open, closed, or both.
- none: Do not accept wildcard expressions.
``` 

all and closed options are supposed to expand on closed indices.

When either of these options are provided while the cluster contains a closed index, a bad request is returned:

```
{
  "error": {
    "root_cause": [
      {
        "type": "index_closed_exception",
        "reason": "closed",
        "index": "test-index",
        "index_uuid": "DH_Phg7YTpSG-KZfAPoddQ"
      }
    ],
    "type": "index_closed_exception",
    "reason": "closed",
    "index": "test-index",
    "index_uuid": "DH_Phg7YTpSG-KZfAPoddQ"
  },
  "status": 400
}
```

**To Reproduce**
1. Create an index
2. Close the index
3. Query GET `_stats?expand_wildcards=all` or `_stats?expand_wildcards=closed`

**Expected behavior**
According to docs this request should succeed.  I would assume returning the stats that are able to be fetched from a closed index, maybe not all?

**Plugins**
None

**Screenshots**
N/A

**Host/Environment (please complete the following information):**
Any

**Additional context**
Easily reproducible with `./gradlew run` on main and 2.x branches, have not tried 1.x.
I am also not seeing any exception in stdout.

**Comment by srikanthpadakanti** [comment]
Hello @anasalkouz @ankitkala @peternied Can you please assign this bug to me. I would like to work on this. Thanks.

**Comment by srikanthpadakanti** [comment]
@ankitkala @anasalkouz @andrross @mch2 @peternied 

These are my findings so far - 

Created an index called "sample-index" with sample docs. 

curl -XPOST "http://localhost:9200/sample-index/_open"
curl -XGET "http://localhost:9200/sample-index/_stats" Printing the data 
--------------
curl -XPOST "http://localhost:9200/sample-index/_close"
curl -XGET "http://localhost:9200/sample-index/_stats"
{"error":{"root_cause":[{"type":"index_closed_exception","reason":"closed","index":"sample-index",
"index_uuid":"EOb53syfTa6SXZ-qPRfIPQ"}],"type":"index_closed_exception","reason":"closed",
"index":"sample-index","index_uuid":"EOb53syfTa6SXZ-qPRfIPQ"},"status":400}%
------------------------------------
curl -XGET "http://localhost:9200/sample-index/_stats?expand_wildcards=all&forbid_closed_indices=false" 
printing the data | default value for forbid_closed_indices is true 
curl -XGET "http://localhost:9200/sample-index/_stats?expand_wildcards=closed&forbid_closed_indices=false"
printing the data  
-----------------------------------

Is this still a legit bug? 
Can anyone please shed some light and explain more. Thanks.

**Comment by srikanthpadakanti** [comment]
Hello @ankitkala @anasalkouz @andrross @mch2 @peternied, 

Can you please answer the above?

**Comment by peternied** [comment]
[Triage - attendees [1](https://github.com/peternied/) [2](https://github.com/lukas-vlcek/) [3](https://github.com/cwperks) [4](https://github.com/scrawfor99) [5](https://github.com/reta/) [6](https://github.com/srikanthpadakanti) [7](https://github.com/Mahima081)]
From our discussion, it sounds like a valid issue.  How some parameters are treated in composition the default behavior should be different.  

In the case mention where `expand_wildcards=all` or `expand_wildcards=closed` it seems like by default value of `forbid_closed_indices` should be false.

Its conflicting cases such as `expand_wildcards=closed` & `forbid_closed_indices=true` 400 error should be returned.

**Comment by srikanthpadakanti** [comment]
Hi @ankitkala @anasalkouz @andrross @mch2 @peternied 
I raised a PR to this bug.  Can you please let me know if everything looks ok? 
https://github.com/opensearch-project/OpenSearch/pull/13012

**Comment by mch2** [comment]
Apologies for chiming in late here and thanks for taking this @srikanthpadakanti 

As @reta mentioned on the PR this would be breaking the rest spec.  When I cut this I had not considered the default behavior with forbid_closed_indices so giving a better error message here would have helped me and does enough to resolve the issue.
