### ISSUE TITLE
Segment Replication

### ISSUE THREAD

**Issue by anasalkouz** [opensearch-project/OpenSearch#1122]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by CEHENKLE** [comment]
Hello  @anasalkouz!  Can you please fill this out with more information about the enhancement you want to make? We need more information to understand the problem and the enhancement.
Thank you!

**Comment by anasalkouz** [comment]
Close this on behalf of #1123
