### ISSUE TITLE
Translog Benchmark

### ISSUE THREAD

**Issue by anasalkouz** [opensearch-project/OpenSearch#1124]
**Is your feature request related to a problem? Please describe.**
Benchmark Translog feature to get clear idea about the performance and resource improvement we could gain by deprecating Translog

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by kartg** [comment]
Note - the scope of this issue is investigation only. We need to determine the right tools and processes to run this benchmark.

The actual performance test is covered by a separate issue - #1137
