### ISSUE TITLE
500 - Internal Server Error when trying to register an Azure storage container as a snapshots repository.

### ISSUE THREAD

**Issue by RickkCedoof** [opensearch-project/OpenSearch#11252]
**Describe the bug**
The azure repository plugin produces a 500 error when trying to register an Azure storage container as a snapshots repository.

**To Reproduce**
Use the following request: 
curl -sS -XPUT -H "Content-Type: application/json" -d '{"type":"azure","settings":{"container": "snapshot"}}' http://localhost:9200/_snapshot/storageaccount;

**Expected behavior**
200  Response code
![image](https://github.com/opensearch-project/OpenSearch/assets/55671611/7e042b93-0e0f-4d47-9871-ff9066ddfc7d)

The request returns:
![image](https://github.com/opensearch-project/OpenSearch/assets/55671611/a7b86755-e81a-486f-98a5-0baabad47832)

**Plugins**
azure-repository

**Host/Environment (please complete the following information):**
 - OS: RHEL-7
 - Version: 2.6.0 and 2.8.0

**Additional context**
While checking the list of repositories, the repository seems to be created but we are not able to make any snapshot.
![image](https://github.com/opensearch-project/OpenSearch/assets/55671611/0f42453e-ee49-4ec6-bfc7-ebd2f805696e)

**Comment by dblock** [comment]
What setup are you using? Detailed steps to reproduce?

**Comment by dblock** [comment]
I googled the error and found https://groups.google.com/g/wazuh/c/aoHbA2g4poo and https://github.com/wazuh/wazuh-packages/issues/1733. Is it the same problem? In which case the fix is in wazuh?

**Comment by RickkCedoof** [comment]
Thank you @dblock ,
 I'm looking forward to your feedback
Please let me know if you need any additional information.

**Comment by dblock** [comment]
@RickkCedoof I didn't imply I am working on this, just trying to help. When I said "I'd try to ..." I meant "Would you like to try to reproduce this on a vanilla installation of OpenSearch without wazuh, starting from a basic docker pull/run?" :) Thanks for any time you can provide!

**Comment by astute-decipher** [comment]
@dblock I was able to successfully to register Azure storage container as a snapshot repository. Please follow the steps below.

Steps followed to add Azure as snapshot store:

1. Install the plugin :
    1. `bin/opensearch-plugin install repository-azure`
        
3. Define your Azure storage settings in opensearch-keystore to enable Azure repositories :
    1. `bin/opensearch-keystore add azure.client.default.account`
        Enter value for azure.client.default.account: \<Enter your azure storage account name here\>

   2. `bin/opensearch-keystore add azure.client.default.key`
        Enter value for azure.client.default.key: \<Enter Access key of your Azure storage account here\>
4. If you changed something in the opensearch.yml file, you need to restart each of the nodes. If you didn’t, you can run the following command to load up the keystore values:
    1. `curl -X POST "https://localhost:9200/_nodes/reload_secure_settings"`
5. Create snapshot repositories (for ex : ) :
    1. Below `mysnapshotrepo` is the snapshot repository name & `mysnaphotstore`  is Container name on your Azure storage account
    2. ```
        curl -X PUT "https://localhost:9200/_snapshot/mysnapshotrepo?pretty" -H 'Content-Type: application/json' -d'
                {
                  "type": "azure",
                  "settings":{
                    "container": "mysnaphotstore"
                  }
                }
                '
          ```

6. You can check the repositories created (for ex):
    1. ```
       curl -X GET "https://localhost:9200/_cat/repositories"
       Output > mysnapshotrepo azure
        ```
7. Create one snapshot like :
```
 curl -X PUT "https://localhost:9200/_snapshot/mysnapshotrepo/snapshot_1?wait_for_completion=true"
 Output > {"snapshot":{"snapshot":"snapshot_1","uuid":"aKj6hzFQTaquvnEg_gcQjw","version_id":136327927,"version":"2.11.1","remote_store_index_shallow_copy":false,"indices":[".opensearch-sap-log-types-config","security-auditlog-2024.02.20",".plugins-ml-config",".opensearch-observability",".opendistro_security"],"data_streams":[],"include_global_state":true,"state":"SUCCESS","start_time":"2024-02-20T10:21:16.746Z","start_time_in_millis":1708424476746,"end_time":"2024-02-20T10:21:22.591Z","end_time_in_millis":1708424482591,"duration_in_millis":5845,"failures":[],"shards":{"total":5,"failed":0,"successful":5}}}
```        
```
 curl -X GET "https://localhost:9200/_snapshot/mysnapshotrepo/_all?"
 Output >  {"snapshots":[{"snapshot":"snapshot_1","uuid":"aKj6hzFQTaquvnEg_gcQjw","version_id":136327927,"version":"2.11.1","remote_store_index_shallow_copy":false,"indices":[".opensearch-sap-log-types-config","security-auditlog-2024.02.20",".plugins-ml-config",".opensearch-observability",".opendistro_security"],"data_streams":[],"include_global_state":true,"state":"SUCCESS","start_time":"2024-02-20T10:21:16.746Z","start_time_in_millis":1708424476746,"end_time":"2024-02-20T10:21:22.591Z","end_time_in_millis":1708424482591,"duration_in_millis":5845,"failures":[],"shards":{"total":5,"failed":0,"successful":5}}]}
```
8. Now you can check your Azure storage account, snapshot should be in the specified container (In this case in `mysnaphotstore` )

Please let me know if you are still facing the problem.

**Comment by dblock** [comment]
@RickkCedoof see above?

**Comment by astute-decipher** [comment]
Marking this issue as closed. @RickkCedoof Please feel free to open it if you are still getting issue while setting up the repository.
