### ISSUE TITLE
Add instrumentation for inode usage by Opensearch process

### ISSUE THREAD

**Issue by sachinpkale** [opensearch-project/OpenSearch#1126]
TBD

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by CEHENKLE** [comment]
Hello @sachinpkale!  Can you please fill this out with more information about the enhancement you want to make? We need more information to understand the problem and the enhancement.
Thank you!
