### ISSUE TITLE
Ensure `jackson` default maximums introduced in 2.16.0 do not conflict with OpenSearch settings

### ISSUE THREAD

**Issue by cwperks** [opensearch-project/OpenSearch#11278]
In `jackson` 2.16.0 new settings were [added](https://github.com/opensearch-project/OpenSearch/pull/11273#issuecomment-1819201892) to configure maximum nesting on _output_ and maximum field length on _input_. OpenSearch already has [2 settings](https://github.com/opensearch-project/OpenSearch/blob/0d3d7aed741db3601d0a3fee2104f51f6c7ba8ad/server/src/main/java/org/opensearch/index/mapper/MapperService.java#L148-L161) for similar behavior:

```
public static final Setting<Long> INDEX_MAPPING_DEPTH_LIMIT_SETTING = Setting.longSetting(
    "index.mapping.depth.limit",
    20L,
    1,
    Property.Dynamic,
    Property.IndexScope
);
public static final Setting<Long> INDEX_MAPPING_FIELD_NAME_LENGTH_LIMIT_SETTING = Setting.longSetting(
    "index.mapping.field_name_length.limit",
    Long.MAX_VALUE,
    1L,
    Property.Dynamic,
    Property.IndexScope
);
```

Its possible that a user could configure the OpenSearch settings with values that exceed the maximums from Jackson, in which case, the Jackson defaults would supersede the OpenSearch settings. I'm capturing an issue to track whether OpenSearch should allow a user to configure a cluster to exceed the Jackson maximums.

It may be possible to update the XContent Parsers to configure StreadReadConstraints and StreamWriteConstraints which is already configured for 50mb max document size: https://github.com/opensearch-project/OpenSearch/blob/main/libs/x-content/src/main/java/org/opensearch/common/xcontent/json/JsonXContent.java#L81

**Comment by reta** [comment]
We already have some system properties (fe `opensearch.xcontent.string.length.max`) to configure the XContent related limits (which directly translate to `StreamReadConstraints` on Jackson side). It will probably make sense to add properties system properties to control  new `2.16.0` settings (https://github.com/opensearch-project/OpenSearch/pull/11273#issuecomment-1819201892) and make sure they do not conflict with the OpenSearch ones.
