### ISSUE TITLE
Separate backwards compatibility testing in CI workflow

### ISSUE THREAD

**Issue by peternied** [opensearch-project/OpenSearch#113]
In the `./gradlew check` process the build tasks for backwards compatibility of the previous version of elasticsearch are run.  During CI runs it would be better to block this part of the workflow until after the more basic tests are run.

**Comment by dblock** [comment]
@adnapibar this is saying something else than https://github.com/opensearch-project/OpenSearch/issues/799

**Comment by adnapibar** [comment]
> @adnapibar this is saying something else than #799, which one's right?

As the description of #799 says -  `./gradlew check` only runs a small number of bwc checks (only against compatible versions that are not yet released).

Our main goal of bwc check is to run it against compatible released versions e.g. against Elasticsearch 7.10.2. This is only run as part of `./gradlew bwcTest` . See https://github.com/opensearch-project/OpenSearch/blob/main/TESTING.md#testing-backwards-compatibility for more details.

**Comment by dblock** [comment]
So this issue as stated is incorrect and should be closed?

**Comment by adnapibar** [comment]
> So this issue as stated is incorrect and should be closed?

Yes

**Comment by dblock** [comment]
Closing, thanks! @peternied lmk if I shouldn't have ;)

**Comment by peternied** [comment]
Thanks for cleaning this up @dblock  - deferring to the newer issue!
