### ISSUE TITLE
[BUG] Same translog metadata file uploaded from old primary during a race condition 

### ISSUE THREAD

**Issue by ashking94** [opensearch-project/OpenSearch#11322]
**Describe the bug**
Across different nodes, the combination of primary term, translog generation has to be unique for the translog metadata file name.
There is a bug where the old primary can still upload a translog metadata file which has same primary term and generation which is generated as part of the relocation handoff by the new primary. This happens when there is any internal or background flush triggered around the same time as the relocation handoff but just before the primary mode becomes false on the old primary. In the cases where we found the issue, the internal flush was triggered due to no writes happening in last 5 mins on a shard and the relocation happening around the same time as of the internal flush.

https://github.com/opensearch-project/OpenSearch/blob/fe2d58529aacc1270afc49693cc2be95b1b9ef6e/server/src/main/java/org/opensearch/index/shard/IndexShard.java#L2679-L2701

**To Reproduce**
This is very difficult to reproduce and shows up at very high scale. However, we can still attempt to reproduce by creating mutliple indexes and triggering the relocation around the 5th minute of no write on the shard.

**Expected behavior**
The old primary must not upload once the control reaches the handoff stage.

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**

**Comment by kiranprakash154** [comment]
Hi, are we on track for this to be released in 2.12 ?

**Comment by ashking94** [comment]
This has been solved, the PR is referenced.
