### ISSUE TITLE
[BUG] lang-painless missing compile dependencies

### ISSUE THREAD

**Issue by prudhvigodithi** [opensearch-project/OpenSearch#11353]
**Describe the bug**
Starting `2.10.0` release the lang-painless maven package https://mvnrepository.com/artifact/org.opensearch.plugin/lang-painless/2.10.0, does not generate the compile dependencies (Maven compile dependencies are the dependencies that are required for the compilation of the project under development)

~I assume this bug was introduced  from https://github.com/opensearch-project/OpenSearch/pull/8823~, as looking at the code there are some [declared dependencies](https://github.com/opensearch-project/OpenSearch/blob/main/modules/lang-painless/build.gradle#L55-L62) but are not added in compile dependencies section of the POM file. 

**Expected behavior**
The `2.9.0` lang-painless maven package has the Compile Dependencies https://mvnrepository.com/artifact/org.opensearch.plugin/lang-painless/2.9.0

Another example of [ingest-geoip](https://mvnrepository.com/artifact/org.opensearch.plugin/ingest-geoip/2.10.0) 2.10.0 which has the compile dependencies.

**Comment by reta** [comment]
@prudhvigodithi I will take a look unless you are already looking

**Comment by prudhvigodithi** [comment]
Hey @reta thanks, looks to like with latest gradle version the ordering of `generatePomFileForNebulaPublication` is missed when added 
```
tasks.validateNebulaPom.dependsOn tasks.generatePomFileForShadowPublication
tasks.validateShadowPom.dependsOn tasks.generatePomFileForNebulaPublication
tasks.withType(AbstractPublishToMaven)*.dependsOn "generatePomFileForShadowPublication", "generatePomFileForNebulaPublication"
```

Executing the following generates the right POM file with compile dependencies.
`../../gradlew :modules:lang-painless:generatePomFileForNebulaPublication --stacktrace`

Since I'm close let me take a stab at it, if not we can collaborate on this.

**Comment by prudhvigodithi** [comment]
@reta I have a PR open, please take a look. Thanks
