### ISSUE TITLE
[Search Query Categorization] Expanding the capture of query type and level information

### ISSUE THREAD

**Issue by deshsidd** [opensearch-project/OpenSearch#11364]
In Phase 1 of Search Query Categorization we captured query type and level information for a few query types.

In Phase 2 as part of this task we need to expand this to capture more query types and try to include all the aggregation query types.

After phase 2 we will be capturing query type and level information for the following query types (Including phase 1 and 2):
BoolQuery
BoostingQuery
ConstantScoreQuery
DisMaxQuery
DistanceFeatureQuery
ExistsQuery
FieldMaskingSpanQuery
FuzzyQuery
GeoBoundingBoxQuery
GeoDistanceQuery
GeoPolygonQuery
GeoShapeQuery
IntervalQuery
MatchAllQuery
MatchPhraseQuery
MatchQuery
MultiMatchQuery
PrefixQuery
QueryStringQuery
RangeQuery
RegexpQuery
ScriptQuery
SimpleQueryString
TermQuery
WildcardQuery
FunctionScoreQuery

We will be incrementing counters for each of these query types and capturing the level information as a tag to the counters. Counters will be incremented using the Telemetry metrics framework.

Phase 1: https://github.com/opensearch-project/OpenSearch/issues/10250
Phase 2 Meta issue : https://github.com/opensearch-project/OpenSearch/issues/11040
Query Visibility Roadmap : https://github.com/opensearch-project/OpenSearch/issues/11008

**Comment by deshsidd** [comment]
cc @getsaurabh02 @msfroh @backslasht Please provide some feedback.

**Comment by backslasht** [comment]
Does phase 2 of this task include all aggregation query types? If yes, how many new metrics does it result in?

**Comment by backslasht** [comment]
I see the list in https://github.com/opensearch-project/OpenSearch/issues/11366#issue-2015048377

**Comment by backslasht** [comment]
Will there be any over head to the request with the addition of these metrics?
