### ISSUE TITLE
Support value retrieval in top_hits

### ISSUE THREAD

**Issue by cjbottaro** [opensearch-project/OpenSearch#11372]
Can we get this Elasticsearch PR ported over to Opensearch?

Here's the PR:
https://github.com/elastic/elasticsearch/pull/95828

Here's the issue:
https://github.com/elastic/elasticsearch/issues/94967

Currently, if you try to access a top hit via a pipeline aggregation, you get this error:
```json
{
 "reason" : "buckets_path must reference either a number value or a single value numeric metric aggregation, got: [InternalTopHits] at aggregation [latest]",
  "type" : "aggregation_execution_exception"
}
```

**Comment by peternied** [comment]
@cjbottaro elasticsearch's most recent license doesn't allow code to be copied from their codebase.  If you feel strongly about this issue please consider refiling this issue with the specific feature request / bug requirements without directly referencing work done in other projects.

@macohen I'd be curious if you have another kind of response in mind as we get issues like this often.
