### ISSUE TITLE
[BUG]Query support on flat_object field with dotted sub field names is unreliable

### ISSUE THREAD

**Issue by ngnwn** [opensearch-project/OpenSearch#11402]
**Describe the bug**
I have an index with a field of type “flat_object,” and the JSON object for that field contains dotted sub-field names. I’m attempting to apply a term query using the entire key and value but it doesn't work as expected

**To Reproduce**
1. Create an index with mapping:
```
PUT /my-test-os-index
{
  "mappings": {
    "properties": {
      "transcript": {"type": "flat_object"}
    }
  }
}
```
2. Index a single document
```
POST my-test-os-index/_doc
{
  "transcript": {
    "one": "FAILED",
    "two.one": "FAILED",
    "three": "FAILED"
  }
}
```
3. Run a term query
```
POST my-test-os-index/_search
{
  "query": {
    "term": {"transcript.three": "FAILED"}
  }
}
```
4. The results are empty

**Expected behavior**
We expect the one indexed document to be returned cause it matches the criteria

**Plugins**
I am using OpenSearch 2.9

**Host/Environment (please complete the following information):**
Using OS serverless

**Additional context**
```
POST my-test-os-index/_search
{
  "query": {
    "term": {"transcript.one": "FAILED"}
  }
}
```
This query retrieves the document making the results order dependent and unreliable

**Comment by peternied** [comment]
Thanks for filing this issue
