### ISSUE TITLE
Query Prioritization

### ISSUE THREAD

**Issue by getsaurabh02** [opensearch-project/OpenSearch#1140]
As part of #1042 we are planning to do resource mapping of queries, and selective rejection when in duress. We want to extend the solution to also allow query prioritisation, which provides mechanism to selectively execute queries, when there are multiple queries with different priorities contending for the same resources.

Not all queries in the workload are of equal importance to customer. Often performance of one request or set of queries might be more important than others. With query prioritisation, customers can define the relative importance of queries in a workload by setting a priority value. The priority is specified for a dynamic queue such as one of (CRITICAL, HIGHEST, HIGH, NORMAL, LOW, LOWEST). 

Opensearch will use the priority when accepting queries for execution, and to determine the amount of resources to be allocated to a query. By default, queries run with their priority set to NORMAL. These priority of query is also used under duress, to selectively cancel resource guzzling queries, and recover the system.

More details to follow.

**Comment by Bukhtawar** [comment]
Duplicate of #1017

**Comment by getsaurabh02** [comment]
Moving details to #1017 and closing this one, since it got created first.
