### ISSUE TITLE
[FEATURE] Move to Apache Lucene 9.9.0

### ISSUE THREAD

**Issue by reta** [opensearch-project/OpenSearch#11414]
**Is your feature request related to a problem? Please describe.**
The Apache Lucene 9.9.0 release vote has started [1] (and released [2]) we should expect the release bits published shortly

[1] https://lists.apache.org/thread/6bxf0fo1ypblxn2hbdfyg38y3hc8lo9g
[2] https://lucene.apache.org/core/corenews.html#apache-lucenetm-990-available -

**Describe the solution you'd like**
Move to Apache Lucene 9.9.0

**Describe alternatives you've considered**
Stay on Move to Apache Lucene 9.8.0

**Additional context**

**Comment by reta** [comment]
CC @msfroh @nknize @dblock @andrross

**Comment by dblock** [comment]
Thanks for monitoring this @reta!

**Comment by mch2** [comment]
fyi we have a 9.9.0 [snapshot](https://github.com/opensearch-project/OpenSearch/actions/runs/7023376319/job/19109758215) pushed from a few days ago `9.9.0-snapshot-eb697aa` if you'd like I can take a stab at building main to this

**Comment by reta** [comment]
> fyi we have a 9.9.0 [snapshot](https://github.com/opensearch-project/OpenSearch/actions/runs/7023376319/job/19109758215) pushed from a few days ago `9.9.0-snapshot-eb697aa` if you'd like I can take a stab at building main to this

Thanks @mch2 !
