### ISSUE TITLE
Disk water mark enhancements

### ISSUE THREAD

**Issue by tushar-kharbanda72** [opensearch-project/OpenSearch#1142]
**Is your feature request related to a problem? Please describe.**
Disk water mark setting is not being very effective in scenarios where indexing rate is very high on the instances where disk volume is low. It doesn't kicks in time to avoid a situation where manual intervention is required to bring back cluster to a green state.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by anasalkouz** [comment]
Hi @tushar-kharbanda72, Disk water mark has default setting, but can override them based on your use-case. So, I am still not sure what are you suggesting? can you elaborate more?

**Comment by anasalkouz** [comment]
Closing it due to lack of details. @tushar-kharbanda72 feel free to reopen if needed.
