### ISSUE TITLE
[Segment Replication] Cluster level setting to restrict replication type in index level settings

### ISSUE THREAD

**Issue by dreamer-89** [opensearch-project/OpenSearch#11457]
### Summary
Today, we have `cluster.indices.replication.strategy` cluster setting that sets the default replication type for any index in the cluster which can be overridden by index level settings i.e. `index.replication.type` value. As part of this change, we need to ensure the cluster level settings are not overridden by index level settings. This will be useful for admins to provide a more strict control on index replication type where they set cluster level replication type using `cluster.indices.replication.strategy` settings and allows users/consumers to create their indices. We [attempted](https://github.com/opensearch-project/OpenSearch/issues/10868) this previously but it has a [bug](https://github.com/opensearch-project/OpenSearch/issues/11078) where snapshot restore functionality was broken. Proposed new setting name is `cluster.index.restrict.replication.type`.

#### Describe the solution you'd like
Introduce a new cluster setting would help enforce a replication strategy and prevent override by the index level settings. The new settings will be `opt-in` which means it will `false` by default. 

### Related
1. https://github.com/opensearch-project/OpenSearch/issues/10868
2. https://github.com/opensearch-project/OpenSearch/issues/11078

**Comment by dreamer-89** [comment]
Some thoughts

Logically we should allow replication.type setting when it matches with the cluster level setting `cluster.indices.replication.strategy`. We should throw exception when we have `cluster.restrict.index.replication_type` and templates, index creation have a different replication.type value e.g. 

Though, this enforcement should not be applied on snapshot and restore flow because it is useful for customers to perform snapshot and restore under different replication strategies i.e. snapshot index with `DOCUMENT` replication and restore on index with `SEGMENT` replication type.

**Comment by dreamer-89** [comment]
Ping: @dagneyb @elfisher to get feedback around above behavior is expected or not.

**Comment by rohin** [comment]
I agree with the suggestion.

I only have a follow up question whether we considered a cluster level setting that can be used to check if override is allowed or not, this way we can ignore index level changes always and it might not be restricted to just replication but used wider for better cluster control.

like - cluster.indices.replication.allowoverride or something of the likes.

**Comment by dreamer-89** [comment]
> I agree with the suggestion.
> 
> I only have a follow up question whether we considered a cluster level setting that can be used to check if override is allowed or not, this way we can ignore index level changes always and it might not be restricted to just replication but used wider for better cluster control.
> 
> like - cluster.indices.replication.allowoverride or something of the likes.

Thanks @rohin for the feedback. I really like the idea of having a unique cluster level setting that governs index level overrides are allowed or not. On thinking more on this proposal, I see below challenges. 
1. Single setting favours simplicity though at the expense of granular control. Users may like to have different levers for different features/restrictions.  
2. Capping all (or multiple) index level override settings for features which are not related under a single cluster level setting may be confusing for the users ? I am taking into consideration future changes where we need to restrict different aspects of  an index.

**Comment by dreamer-89** [comment]
Closing this issue as change has been implemented.
