### ISSUE TITLE
Investigate the underlying Lucene internals to design the new NRT checkpointing behavior 

### ISSUE THREAD

**Issue by kotwanikunal** [opensearch-project/OpenSearch#11462]
**Is your feature request related to a problem? Please describe.**
SegRep checkpointing should be able to differentiate in metrics & exclude from backpressure computations the lag between checkpoints that are strictly post-merge refreshes where the searchable doc count does not change.  

**Describe the solution you'd like**
Study the underlying framework/mechanism for the [IndexWarmer](https://github.com/apache/lucene/blob/main/lucene/replicator/src/java/org/apache/lucene/replicator/nrt/PreCopyMergedSegmentWarmer.java) implementation and design the new mechanism for lag calculation

**Additional context**
- #10872

**Comment by mch2** [comment]
IndexReaderWarmer will do what we want here.  The newly merged segment will not be committed by the writer until the warmer has completed.

Some thoughts and futher items to investigate here:
- Whats the impact of slow merges on the merge scheduler? The warmer is invoked during `mergeMiddle` which doesn't hold a lock on the IW, but it would block the merge thread.
- We will need new APIs to copy out the set of files making up the segment, existing SR APIs are tied to a single SIS checkpoint.  The APIs should be designed to support any copy mechanism (n2n/remote store)
