### ISSUE TITLE
Release 1.3.14

### ISSUE THREAD

**Issue by DarthHater** [opensearch-project/OpenSearch#11495]
**Is your feature request related to a problem? Please describe.**
In the following security vulnerability, it is mentioned that 1.3.14 addresses it: https://github.com/opensearch-project/OpenSearch/security/advisories/GHSA-6g3j-p5g6-992f

However, that release doesn't appear to be actually released, and I have yet to find any information on why or where it is.

**Describe the solution you'd like**
An explanation of where the release is at, or ideally the release, released, and potentially if there is a hold up, the security vulnerability updated to reflect that there is in fact no path forward for 1.3.x consumers.

**Describe alternatives you've considered**
Strong statement but these are my alternatives: Move off of this library entirely or upgrade to 2.x?

**Additional context**
I appreciate the work everyone does on this project!

**Comment by dblock** [comment]
@davidlago

**Comment by davidlago** [comment]
@DarthHater thanks for the report. We usually fix these and they go out following the prescheduled releases (see https://opensearch.org/releases.html), so for 1.3.14 we are hoping to get that out in the next few days. Only in cases where we're talking about a critical vulnerability we might decide to expedite a release and have an ad-hoc one to get the fixes out. Hope that makes sense!
