### ISSUE TITLE
Fix left over `termQuery` in Keyword fields to be searchable with doc_values

### ISSUE THREAD

**Issue by harshavamsi** [opensearch-project/OpenSearch#11538]
**Is your feature request related to a problem? Please describe.**
Coming from #7057, there is a left over `termQuery` that needs to be searchable when only doc_values are enabled.

**Describe the solution you'd like**
Similar to the work done for term queries in #11209, override term query and then handle all three cases when index and doc_values are enabled/disabled.

**Describe alternatives you've considered**
Do nothing.

**Comment by kiranprakash154** [comment]
Hi, are we on track for this to be released in 2.12 ?

**Comment by harshavamsi** [comment]
Hi @kiranprakash154 we determined that this is something that we don't see making any impact, so we scrapped this.

**Comment by msfroh** [comment]
@harshavamsi  -- Does it make sense to still handle the DV-only case? That is, skip the IndexOrDocValuesQuery case (using the indexed query whenever we can).

That is, we wouldn't want to do this as a performance optimization, but we could handle term queries on a non-indexed keyword field that has doc values. I'm imagining a case where there's a kw field that (almost) never gets queried, but does get aggregated over, so we just have doc values. If you *do* want to query it rarely (or at least filter on it), you could do that as a DV lookup.
