### ISSUE TITLE
[BUG] Searchable snapshots - RepositoryMissingException

### ISSUE THREAD

**Issue by damslo** [opensearch-project/OpenSearch#11552]
**Describe the bug**
When I try to restore a snapshot with index.store.type: remote_snapshots I'm getting RepositoryMissingException.
When I restore without remote_snapshot setting, it's working fine.
This issue occurred on our production cluster, but I also reproduced it on "clean" opensearch from official helm chart.
I didn't test with other repo type, only azure blob.

**To Reproduce**
1. Setup azure blob repository
2. Restore snapshot with index.store.type: remote_snapshots

**Expected behavior**
Data available, cluster status green

**Plugins**
Please list all plugins currently enabled.

**Screenshots**
![image](https://github.com/opensearch-project/OpenSearch/assets/123402182/a33aa6a8-e7a6-4d23-ac12-9dddae8c3de3)

**Host/Environment (please complete the following information):**
 - OS: rockylinux:8
 - Version 2.11.0 and 2.11.1

**Additional context**
Restore request:

POST /_snapshot/azure_data_repository/remote-test/_restore
{
   "indices": "*",
   "ignore_unavailable": true,
   "include_global_state": false,              
   "rename_pattern": "(.+)",
   "rename_replacement": "observability-searchable-snap-test-$1",
   "include_aliases": false,
   "index_settings": {
      "index.store.type":"remote_snapshot"
   }
  }

Logs:
[logs-searchable-snap.log](https://github.com/opensearch-project/OpenSearch/files/13635311/logs-searchable-snap.log)

**Comment by andrross** [comment]
I think the restore command you want is:

```
POST /_snapshot/azure_data_repository/remote-test/_restore
{
  "indices": "*",
  "ignore_unavailable": true,
  "include_global_state": false,
  "rename_pattern": "(.+)",
  "rename_replacement": "observability-searchable-snap-test-$1",
  "include_aliases": false,
  "storage_type": "remote_snapshot"
}
```

I can see how this is confusing and the error message you're getting does not seem right, but can you try updating the restore command and see if that works?

**Comment by andrross** [comment]
To expand on the confusing user experience here...the `index.store.type` setting is intended to be a system-managed index setting that is configured when restoring a snapshot with `"storage_type": "remote_snapshot"`. Once a searchable snapshot index is restored that setting is not mutable, but it looks like there might be gap here if attempting to modify that setting directly in the restore API.

**Comment by damslo** [comment]
Hello @andrross, thank you for making it clear for me, it's working now.

**Comment by anasalkouz** [comment]
@andrross anything we can improve to reduce the confusion?

**Comment by anasalkouz** [comment]
I think we should add an example of restore api for searchable snapshot [here](https://opensearch.org/docs/latest/tuning-your-cluster/availability-and-recovery/snapshots/searchable_snapshot/#create-a-searchable-snapshot-index)

**Comment by andrross** [comment]
> @andrross anything we can improve to reduce the confusion?

Two things:
- Improve documentation (as you mentioned)
- Improve error handling to fail the call if the restore API attempts to set `index.store.type` to `remote_snapshot` directly
