### ISSUE TITLE
[BUG] Winlogbeat OSS 7.12.1 integration issue with OpenSearch 2.11

### ISSUE THREAD

**Issue by pietrogu** [opensearch-project/OpenSearch#11606]
Hi,

i am trying to configure winlogbeat-oss 7.12.1 to send data to Opensearch 2.11
However, the following error appears:

Winlogbeat requires the default distribution of Elasticsearch

Any idea?

Best,
Pietro

**Comment by pietrogu** [comment]
Anyone?

**Comment by dblock** [comment]
@pietrogu According to https://opensearch.org/docs/1.0/clients/agents-and-ingestion-tools/index/ it should be compatible, but you need to set `compatibility.override_main_response_version` to true. 

I'll close this, please reopen if that doesn't work.

**Comment by pietrogu** [comment]
I already set the option you indicated, but with no luck

**Comment by dblock** [comment]
What is the output of `curl -v http://host:port` on the OpenSearch instance?
