### ISSUE TITLE
[BUG] QueryProfilePhaseTests.testTerminateAfterEarlyTermination is flaky

### ISSUE THREAD

**Issue by mch2** [opensearch-project/OpenSearch#11611]
### Describe the bug

from https://github.com/opensearch-project/OpenSearch/issues/11239

### Related component

Search:Query Insights

### To Reproduce

https://build.ci.opensearch.org/job/gradle-check/30102/

### Expected behavior

Test to not be flaky

### Additional Details

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**

**Comment by jed326** [comment]
FYI @ticheng-aws @sohami -- looks like re-appearance of https://github.com/opensearch-project/OpenSearch/issues/2775
