### ISSUE TITLE
.NET Nest client fork

### ISSUE THREAD

**Issue by JaroslavMajera** [opensearch-project/OpenSearch#1164]
Hello

 I am investigating Elasticsearch replacement. Are you planning to fork Nest client or just Elasticsearch.Net?

**Comment by dblock** [comment]
Yes we are, see https://opensearch.org/blog/community/2021/08/community-clients/ that includes `-net` in the list. As with all the forks there's a bunch of work to do in private to ensure a clean fork, so this takes a bit of time , appreciate your patience. 
 
I'll close this for now, but feel free to add more questions!
