### ISSUE TITLE
[Question?] G1GC Custom Settings

### ISSUE THREAD

**Issue by andrross** [opensearch-project/OpenSearch#11649]
### Is your feature request related to a problem? Please describe

Does anyone have the history as to why [these custom G1GC tunings](https://github.com/opensearch-project/OpenSearch/blame/main/distribution/src/config/jvm.options#L42) were configured?

```
11-:-XX:G1ReservePercent=25
11-:-XX:InitiatingHeapOccupancyPercent=30
```

I believe the defaults are G1ReservePercent=5 and InitiatingHeapOccupancyPercent=45. I'm personally a fan of _not_ overriding the defaults unless there is good evidence this is better in the general case and we continually re-evaluate these settings with each JDK update. I traced this change back to #2916 where we had inadvertently changed the default GC from G1GC back to CMS when we changed OpenSearch 1.x to use JDK11 LTS. This change introduced G1GC by default for all JDKs 11 and newer, but I don't see any discussion as to _why_ these two settings were applied.

@reta Tagging you since you were involved in this change.

### Describe the solution you'd like

I'm looking for the justification for using these non-default settings. (Also looks like there is an [incorrect comment](https://github.com/opensearch-project/OpenSearch/blame/main/distribution/src/config/jvm.options#L42) in the jvm.options file that I will clean up as well)

### Related component

Search:Performance

**Comment by reta** [comment]
@andrross traced it to https://github.com/elastic/elasticsearch/pull/46169
