### ISSUE TITLE
Apply the optimization if the individual segment is match all query even though the whole shard is not

### ISSUE THREAD

**Issue by bowenlan-amzn** [opensearch-project/OpenSearch#11654]
Coming from https://github.com/opensearch-project/OpenSearch/pull/11083#discussion_r1394723095

When starting to process each segment, we get the LeafReaderContext which can provide the `numDocs` of this segment. On the other hand, the weight taking in LeafReaderContext can produce the estimate count of this segment. If these 2 are same, we can treat the weight equivelant as a match-all and it may satisfy the pre-conditions of the fast filters optimization.

**Comment by kiranprakash154** [comment]
Hi, are we on track for this to be released in 2.12 ?
