### ISSUE TITLE
[v2.12.0] Ensure CI/documentation reflect changes to default admin credentials

### ISSUE THREAD

**Issue by derek-ho** [opensearch-project/OpenSearch#11663]
## Background
Previously, when installing the security plugin demo configuration, the cluster was spun up with the default admin credentials, `admin:admin`. A change was made in `main` and backported to `2.x` for the `2.12.0` release, which now requires an initial admin password to be passed in via the environment variable `OPENSEARCH_INITIAL_ADMIN_PASSWORD`. This will break some CI/testing that relies on OpenSearch to come up without setting this environment variable. This tracking issue is to ensure compliance with the new changes.

Coming from: https://github.com/opensearch-project/security/issues/3624

## Acceptance Criteria
 - [ ] All documentation references to the old default credentials `admin:admin` are removed
 - [ ] Ensure that CI/testing is working with `main` and `2.x` branches

**Comment by kiranprakash154** [comment]
Hi, are we on track for this to be released in 2.12 ?

**Comment by peternied** [comment]
[Triage - attendees [1](https://github.com/peternied) [2](https://github.com/dbwiddis) [3](https://github.com/andrross) [4](https://github.com/reta)]
@derek-ho Core doesn't include security so it shouldn't have any specific documentation.
