### ISSUE TITLE
[Remote Store] Wait for remote store upload in case of snapshot recovery and local recovery

### ISSUE THREAD

**Issue by gbbafna** [opensearch-project/OpenSearch#11719]
### Is your feature request related to a problem? Please describe

In case we restore indices into a remote store backed cluster from snapshot or do shrink/split/clone , we don't wait for remote store to get up to date , before marking the shard as active. This can affect the durability guarantees for those indices. 

### Describe the solution you'd like

Wait for remote store to be in sync before completing the recovery . 

### Related component

Storage:Remote

**Comment by peternied** [comment]
[Triage - attendees [1](https://github.com/peternied) [2](https://github.com/lukas-vlcek/)]
@gbbafna Thanks for creating this issue - this sounds like an important improvement to the durability of remote stores
