### ISSUE TITLE
FileCache integration with warm indices

### ISSUE THREAD

**Issue by ankitkala** [opensearch-project/OpenSearch#11789]
### Is your feature request related to a problem? Please describe

Coming from https://github.com/opensearch-project/OpenSearch/issues/9987, we'll need to support tiering of data for writable warm indices. 

### Describe the solution you'd like

Integrate FileCache for writable warm indices
High level changes: 
- Initialize the FileCache on all data nodes based on the feature flag.
- Consume the FileCache with Composite Directory implementation to allow block level file fetch.
- Update the FileCache during shard lifecycle events (created, deleted, relocated, etc)

### Related component

Storage:Remote

**Comment by peternied** [comment]
[Triage - attendees [1](https://github.com/peternied) [2](https://github.com/reta) [3](https://github.com/macohen) [4](https://github.com/jainankitk)]
Thanks for filing.
