### ISSUE TITLE
Implement CacheLifecycleManager for the FileCache

### ISSUE THREAD

**Issue by ankitkala** [opensearch-project/OpenSearch#11790]
### Is your feature request related to a problem? Please describe

Coming from https://github.com/opensearch-project/OpenSearch/issues/9987, we'll need to support tiering of data for writable warm indices. 

### Describe the solution you'd like

- Support for TTL based cache eviction. 
- Support for storage overflow based eviction. 

### Related component

Storage:Remote

**Comment by peternied** [comment]
[Triage - attendees [1](https://github.com/peternied) [2](https://github.com/reta) [3](https://github.com/macohen) [4](https://github.com/jainankitk)]
Thanks for filing this issue, its hard to get the context from this issue on why to arrive at the solutions suggested could you please add more context on this issue so it stands on its own?  Please feel free to re-open after addressing.
