### ISSUE TITLE
Support for encryption with FileCache

### ISSUE THREAD

**Issue by ankitkala** [opensearch-project/OpenSearch#11792]
### Is your feature request related to a problem? Please describe

With https://github.com/opensearch-project/OpenSearch/issues/9987, we'll be implementing block level fetch for fetching segment files from remote storage to local data nodes. 

### Describe the solution you'd like

Task is to track the efforts required to support block level fetch on encryption files on remote store.  

### Related component

Storage:Remote

**Comment by peternied** [comment]
[Triage - attendees [1](https://github.com/peternied) [2](https://github.com/reta) [3](https://github.com/macohen) [4](https://github.com/jainankitk)]
From the discussion, its unclear if we'd want to support encryption at this level vs reusing the encryption done at the codec level.  It looks like [1] has more context about these scenarios. Please feel free to re-open after addressing the reason.

- [1] #3469
