### ISSUE TITLE
[Tiered Caching][Improvement] Simplifying tiered spillover cache locking mechanism

### ISSUE THREAD

**Issue by sgup432** [opensearch-project/OpenSearch#11802]
### Is your feature request related to a problem? Please describe

To address comments here - https://github.com/opensearch-project/OpenSearch/pull/10753#discussion_r1442116496
We need to see if there is a way to simplify locking mechanism which is currently hard to read.

Currently while trying to put any new item onto Heap cache, we do it under a write lock. Any evictions occuring from onHeap cache happens under the same lock after which we put it onto disk cache. The whole flow is complex to understand, need to see if there is a way better to do it.

### Describe the solution you'd like

NA

### Related component

Search:Performance

**Comment by peternied** [comment]
[Triage - attendees [1](https://github.com/peternied) [2](https://github.com/lukas-vlcek/)]
@sgup432  Thanks for creating this issue; however, it isn't being accepted due to lack of clarity around what is hard to read or in what way the improvement to should be made (e.g. can we add documentation?) . Please feel free to re-open after addressing the reason.

**Comment by sgup432** [comment]
@peternied I did mention what is the issue here
>Currently while trying to put any new item onto Heap cache, we do it under a write lock. Any evictions occuring from onHeap cache happens under the same lock after which we put it onto disk cache. The whole flow is complex to understand, need to see if there is a way better to do it.

Can you reopen this again? This was created as @Bukhtawar had some concerns on this and we need to explore a way once initial set of changes have gone in.

**Comment by peternied** [comment]
Thanks for the response @sgup432 - when reviewing this issue as the triage team this wasn't clear.

Maintainers and contributors rely on details in issues to evaluate pull requests. Please update the description with addition details.
