### ISSUE TITLE
[Segment Replication] Identify/List out all Integ Tests that must be ran with segment replication enabled

### ISSUE THREAD

**Issue by Rishikesh1159** [opensearch-project/OpenSearch#11804]
### Is your feature request related to a problem? Please describe

We need to Identify and List out the set of modules/tests that will be impacted by segment replication. Currently most of Integ Test suite in opensearch repo are ran without segment replication enabled.

### Describe the solution you'd like

As discussed in issue: https://github.com/opensearch-project/OpenSearch/issues/6761 we need list out all the tests that should be ran with segrep enabled from the following modules:

```
cluster
gateway
index
indexing
indices
ingest
recovery
remotestore
update
```

### Related component

Indexing:Replication

**Comment by kotwanikunal** [comment]
@Rishikesh1159 Did you mean to assign this to yourself?

**Comment by Rishikesh1159** [comment]
As a first step we need to identify the tests that are critical to segment replication and run them with segrep enabled.

```
indexing
ingest
recovery
```

The scope of this task will be running all tests in above modules with segment replication enabled everytime.
