### ISSUE TITLE
[Tiered Caching][Milestone 1] Integrate disk cache 

### ISSUE THREAD

**Issue by sgup432** [opensearch-project/OpenSearch#11897]
### Is your feature request related to a problem? Please describe

This is part of overall Tiered caching miletone 1 - https://github.com/opensearch-project/OpenSearch/issues/10870

As part of this, we want to integrate a disk cache which will extend the existing in-memory cache and be provided under the overall tiered cache option. Below are the requirements for that:
* We need an embedded cache library in JAVA.
* Cache should have disk tier support.
* Robust, performant, full proven and widely adopted.
* Opensource (preferably Apache v2 license). 

There are the possibly three options we have fulfilling above requires:
1. JCS
2. Ehcache
3. MapDb - (Don't see much active development from the past year, so will skip)

We are going with Ehcache in phase-1 as it is more widely adopted, has a better community support and we already have some experience with it as we did POCs with it.

### Describe the solution you'd like

As described above, we are integrating ehcache as a disk cache option.

### Related component

Search:Performance

**Comment by peternied** [comment]
[Triage - attendees [1](https://github.com/peternied) [2](https://github.com/reta) [3](https://github.com/macohen) [4](https://github.com/jainankitk)]
Thanks for filing
