### ISSUE TITLE
Keep original constructor of PluginInfo while we support custom folder name

### ISSUE THREAD

**Issue by ylwu-amzn** [opensearch-project/OpenSearch#1190]
**Is your feature request related to a problem? Please describe.**
In PR #848, we changed PluginInfo constructor by adding `customFolderName`
> public PluginInfo(String name, String description, String version, Version opensearchVersion, String javaVersion,
                      String classname, **String customFolderName**, List<String> extendedPlugins, boolean hasNativeController)

Is it possible to keep the original constructor and add a new constructor to support customFolderName ? This change caused AD test case failed. Not a big problem, but we'd better make the change backward compatible.

**Describe the solution you'd like**
Keep the original PluginInfo constructor for BWC.

**Comment by dblock** [comment]
@VachaShah Can you take it for 1.1?

**Comment by VachaShah** [comment]
Sure I can take this up.

**Comment by VachaShah** [comment]
Backported the change to 1.x: #1209
