### ISSUE TITLE
[BUG] Fix missing javadocs error for nested classes generated using protobuf

### ISSUE THREAD

**Issue by VachaShah** [opensearch-project/OpenSearch#11913]
### Describe the bug

Currently, the classes generated using protobuf are annotated with `Generated` and ignored from the missing javadoc gradle task (Done in #7604). However, the `annotate_code` in gradle task does not add the `Generated` annotation to nested classes. This is causing the missing javadoc to fail due to nested classes. For example: https://github.com/opensearch-project/OpenSearch/actions/runs/7561172941/job/20588856740?pr=11910 for proto message: https://github.com/VachaShah/OpenSearch/blob/search-protobuf-part1/server/src/main/proto/server/search/QuerySearchResultProto.proto#L36.

Current workaround is to add the classes to `javadocMissingIgnore`.

### Related component

Other

### To Reproduce

1. Created a nested proto message and generate Java code.
2. Run `./gradlew :server:missingJavadoc`.
3. See error for missing javadoc for nested classes/interfaces.

### Expected behavior

No missing javadocs error for proto generated nested code.

### Additional Details

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**
https://github.com/protocolbuffers/protobuf/issues/42#issuecomment-313925720

**Comment by peternied** [comment]
[Triage - attendees [1](https://github.com/peternied) [2](https://github.com/lukas-vlcek/)]
@VachaShah Thanks for filing.
