### ISSUE TITLE
[Feature Request] Add _timestamp field for each document

### ISSUE THREAD

**Issue by razoliver** [opensearch-project/OpenSearch#11922]
### Is your feature request related to a problem? Please describe

When indexing new documents the current options for adding a timestamp are:

1. Using ingest pipeline ('set' or 'date' processors) and setting it as the default for an index or using it in every index request.
2. Using OSI (Ingestion Pipelines) and using a 'Date' processor to add a timestamp

### Describe the solution you'd like

Every document that is indexed could have a _timestamp field by default when it's indexed. Upon update/upsert this _timestamp can be updated.

### Related component

Indexing

**Comment by peternied** [comment]
[Triage - attendees [1](https://github.com/peternied) [2](https://github.com/lukas-vlcek/)]
@razoliver Thanks for creating this issue; however, it isn't being accepted due that the caller can include their own timestamp in the document. Please feel free to re-open after addressing the reason.

**Comment by razoliver** [comment]
@peternied 
If OS is a part of a pipeline it can be very useful to have a timestamp upon indexing which will be different than the timestamp on different parts of the pipeline

**Comment by peternied** [comment]
>  very useful

@razoliver Could you describe a scenario where a timestamp added at document creation wouldn't be useful, whereas this proposal timestamp would be?

**Comment by razoliver** [comment]
@peternied 
If you want to calculate data-freshness in your pipeline you'd need both timestamps.

**Comment by peternied** [comment]
@razoliver For metrics there is a plugin [Performance Analyzer](https://opensearch.org/docs/latest/monitoring-your-cluster/pa/index/) that supports a large number of dimensions and granularities.  The use case you are after might already by supported with this plugin.

> Performance Analyzer is a plugin that contains an agent and REST API that allow you to query numerous cluster performance metrics, including aggregations of those metrics.
