### ISSUE TITLE
[BUG] upgrade dependency

### ISSUE THREAD

**Issue by CEHENKLE** [opensearch-project/OpenSearch#1194]
**Describe the bug**
Update dependency commons-compress-jar to from 1.19 to 1.21 unless it is only used in testing.

**Comment by abbashus** [comment]
@CEHENKLE what exactly is the bug with version commons-compress-jar:1.19? Do we want to fix some CVE here ?

**Comment by abbashus** [comment]
`org.apache.commons:commons-compress:1.19` is
1.  api dependency of `build-tools` and `plugins/ingest-attachment`.
2. transitive dependency of `org.apache.hadoop:hadoop-minicluster:2.10.1` in module `test/fixtures/hdfs-fixture`.

Will upgrade for case 1.
