### ISSUE TITLE
Update git secrets section on the DEVELOPER_GUIDE.md

### ISSUE THREAD

**Issue by anasalkouz** [opensearch-project/OpenSearch#1196]
Add more details how to use/configure git secrets into the https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md

**Currently** : it's provide steps to install it.

Expected: Provide into how to install and configure it in your own repo

**Comment by tlfeng** [comment]
Are we going to backport this to 1.x branch? 😉 It doesn't have any labels for the targeted version.

**Comment by dblock** [comment]
I don't think it's necessary to backport since most developers read main.
