### ISSUE TITLE
[BUG] Links unreachable in lucene-LICENSE.txt

### ISSUE THREAD

**Issue by abbashus** [opensearch-project/OpenSearch#1199]
**Describe the bug**
The following URLs are unreachable (HTTP 404)

1. http://source.icu-project.org/repos/icu/icu/trunk/license.html
2. http://www.icu-project.org

Error log https://github.com/opensearch-project/OpenSearch/pull/1197/checks

```
Errors in plugins/analysis-stempel/licenses/lucene-LICENSE.txt
✗ http://source.icu-project.org/repos/icu/icu/trunk/license.html (HTTP status client error (404 Not Found) for url (http://source.icu-project.org/repos/icu/icu/trunk/license.html))
✗ http://www.icu-project.org/ (HTTP status client error (404 Not Found) for url (http://www.icu-project.org/))

Errors in server/licenses/lucene-LICENSE.txt
✗ http://www.icu-project.org/ (HTTP status client error (404 Not Found) for url (http://www.icu-project.org/))
✗ http://source.icu-project.org/repos/icu/icu/trunk/license.html (HTTP status client error (404 Not Found) for url (http://source.icu-project.org/repos/icu/icu/trunk/license.html))

Errors in plugins/analysis-icu/licenses/lucene-LICENSE.txt
✗ http://www.icu-project.org/ (HTTP status client error (404 Not Found) for url (http://www.icu-project.org/))
✗ http://source.icu-project.org/repos/icu/icu/trunk/license.html (HTTP status client error (404 Not Found) for url (http://source.icu-project.org/repos/icu/icu/trunk/license.html))

Errors in plugins/analysis-kuromoji/licenses/lucene-LICENSE.txt
✗ http://source.icu-project.org/repos/icu/icu/trunk/license.html (HTTP status client error (404 Not Found) for url (http://source.icu-project.org/repos/icu/icu/trunk/license.html))
✗ http://www.icu-project.org/ (HTTP status client error (404 Not Found) for url (http://www.icu-project.org/))

Errors in plugins/analysis-ukrainian/licenses/lucene-LICENSE.txt
✗ http://www.icu-project.org/ (HTTP status client error (404 Not Found) for url (http://www.icu-project.org/))
✗ http://source.icu-project.org/repos/icu/icu/trunk/license.html (HTTP status client error (404 Not Found) for url (http://source.icu-project.org/repos/icu/icu/trunk/license.html))

Errors in plugins/analysis-phonetic/licenses/lucene-LICENSE.txt
✗ http://source.icu-project.org/repos/icu/icu/trunk/license.html (HTTP status client error (404 Not Found) for url (http://source.icu-project.org/repos/icu/icu/trunk/license.html))
✗ http://www.icu-project.org/ (HTTP status client error (404 Not Found) for url (http://www.icu-project.org/))

Errors in modules/lang-expression/licenses/lucene-LICENSE.txt
✗ http://source.icu-project.org/repos/icu/icu/trunk/license.html (HTTP status client error (404 Not Found) for url (http://source.icu-project.org/repos/icu/icu/trunk/license.html))
✗ http://www.icu-project.org/ (HTTP status client error (404 Not Found) for url (http://www.icu-project.org/))

Errors in plugins/analysis-smartcn/licenses/lucene-LICENSE.txt
✗ http://www.icu-project.org/ (HTTP status client error (404 Not Found) for url (http://www.icu-project.org/))
✗ http://source.icu-project.org/repos/icu/icu/trunk/license.html (HTTP status client error (404 Not Found) for url (http://source.icu-project.org/repos/icu/icu/trunk/license.html))

Errors in plugins/analysis-nori/licenses/lucene-LICENSE.txt
✗ http://www.icu-project.org/ (HTTP status client error (404 Not Found) for url (http://www.icu-project.org/))
+ echo
✗ http://source.icu-project.org/repos/icu/icu/trunk/license.html (HTTP status client error (404 Not Found) for url (http://source.icu-project.org/repos/icu/icu/trunk/license.html))
+ echo ::set-output name=exit_code::2
```

**To Reproduce**
1. Create any pull request and `link checker` Github action fails.

**Expected behavior**
- Generate new licenses with working URLs
- Or fix URLs in current license

**Comment by hyandell** [comment]
Intriguing. If I look at the archive.org for only 2 days ago, the www.icu-project.org redirects to http://site.icu-project.org/ which appears to have had a new version published. Kudos for flagging this so quickly.

Digging through their text, https://github.com/unicode-org/icu/blob/main/icu4c/LICENSE is the latest url for the license.

Looking at Lucene, this appears to be the latest version of their file:

    https://github.com/apache/lucene/blob/main/lucene/core/src/java/org/apache/lucene/util/UnicodeUtil.java

I don't know if the origin of this particular license description in our https://github.com/opensearch-project/OpenSearch/blob/main/modules/lang-expression/licenses/lucene-LICENSE.txt#L305 file is an earlier Lucene approach, or an Elastic addition, or an OpenSearch addition, but I prefer the current Lucene description. Pointing to a license by URL is just going to be wrong as that url evolves to have new text.

I do think we should upgrade the url to the ICU project as a whole; and send a patch to Lucene to upgrade their files that refer to the url.

**Comment by dblock** [comment]
> I do think we should upgrade the url to the ICU project as a whole; and send a patch to Lucene to upgrade their files that refer to the url.

@hyandell care to open an issue here for this?

**Comment by hyandell** [comment]
I can do. I'd rather see y'all growing your relationship, but I'm also very happy to put my PRs where my mouth is. :)

**Comment by dblock** [comment]
> I can do. I'd rather see y'all growing your relationship, but I'm also very happy to put my PRs where my mouth is. :)

You can assign the issue to me. I just don't want to forget and you seem to know what we need to do.
