### ISSUE TITLE
[Remote Store] Update AWS SDK version to fix connection acquisition timeout issues

### ISSUE THREAD

**Issue by shourya035** [opensearch-project/OpenSearch#12004]
### Describe the bug

We are seeing timeouts in connection acquisition from S3 client thread pool since we are hitting this AWS SDK bug: https://github.com/aws/aws-sdk-java-v2/pull/4066 . This is causing issues with remote uploads when AWS S3 has been setup as the remote store.

The fix has been released with AWS SDK `2.20.86` and above. We would need to update our AWS SDK dependency 

### Related component

Storage

### To Reproduce

N/A

### Expected behavior

There shouldn't be any leaking connections 

### Additional Details

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**

**Comment by peternied** [comment]
[Triage - attendees [1](https://github.com/peternied) [2](https://github.com/lukas-vlcek/) [3](https://github.com/rbowen)]
@shourya035 Thanks for noting this, we've gladly welcome a PR that updates the AWS SDK version.

**Comment by linuxpi** [comment]
@shourya035 can we raise a PR for this?

**Comment by rramachand21** [comment]
This needs to be fixed for 2.13

**Comment by linuxpi** [comment]
[Storage Triage - attendees [1](https://github.com/ashking94/) [2](https://github.com/sachinpkale/) [3](https://github.com/gbbafna/) [4](https://github.com/astute-decipher/) [5](https://github.com/skumawat2025/) [6](https://github.com/shourya035/) [7](https://github.com/vikasvb90/) [8](https://github.com/BhumikaSaini-Amazon/) [9](https://github.com/ltaragi/) [10](https://github.com/lukas-vlcek/) [11](https://github.com/reta/) [12](https://github.com/sachinpkale/)]

@shourya035 lets link the PR and close this issue.

**Comment by shourya035** [comment]
Closing this since the AWS SDK version was updated through: https://github.com/opensearch-project/OpenSearch/pull/12251
