### ISSUE TITLE
[Optimization] Reduce ShardId key size in AsyncShardFetch Revamp strategy

### ISSUE THREAD

**Issue by amkhar** [opensearch-project/OpenSearch#12010]
### Describe the bug

AsyncShardFetch Revamp strategy (explained [here](https://github.com/opensearch-project/OpenSearch/issues/5098#issuecomment-1596722825) ) uses ShardId object directly in the key to store metadata of all the shards received from all the nodes. So overall memory usage goes in the factor of 

ShardId object size * shard_count * node_count = this goes in GBs as ShardId object contains more data. 

### Related component

Cluster Manager

### To Reproduce

1. Use the latest code of this project
2. spin up a new cluster with 500 nodes and 500K shards
3. Restart all cluster manager nodes at once
4. We'll see heap getting full, can go up to 50GB

### Expected behavior

We should reduce the key size and not use full object, ideally use smaller sized key to reduce overall heap usage.

### Additional Details

**Screenshots**
<img width="1262" alt="async-shard-fetch-batch-dominator-tree" src="https://github.com/opensearch-project/OpenSearch/assets/85096200/ad606604-5b8d-499c-93c1-009c73550f0d">

heap dump collected from a cluster where batch size is 4000 and one batch is taking more than 500MBs.

**Comment by peternied** [comment]
[Triage - attendees [1](https://github.com/peternied) [2](https://github.com/lukas-vlcek/) [3](https://github.com/rbowen)]
@amkhar Thanks for filing, we'd welcome a pull request to address this issue.

**Comment by amkhar** [comment]
@peternied  - Sure. I'm working on making a change, it requires a bit more exhaustive testing. I'll share once that is completed. 

Change will be blocked on the rest of the PRs mentioned in the META issue https://github.com/opensearch-project/OpenSearch/issues/8098. Once initial PRs are merged, then only this change can be merged.

**Comment by amkhar** [comment]
Not needed as cache restructuring is being done as part of https://github.com/opensearch-project/OpenSearch/pull/12504 and ShardId will not get repeated.
