### ISSUE TITLE
[Remote Store] Avoid deleting already deleted file in stale segment cleanup flow

### ISSUE THREAD

**Issue by sachinpkale** [opensearch-project/OpenSearch#12019]
### Is your feature request related to a problem? Please describe

https://github.com/opensearch-project/OpenSearch/pull/11987/files#r1463460410

### Describe the solution you'd like

Do not trigger delete on already deleted file.

### Related component

Storage:Durability

**Comment by peternied** [comment]
[Triage - attendees [1](https://github.com/peternied) [2](https://github.com/lukas-vlcek/) [3](https://github.com/andrross) [4](https://github.com/CEHENKLE) [5](https://github.com/dbwiddis) [6](https://github.com/reta/) [7](https://github.com/anasalkouz) [8](https://github.com/aggarwalShivani)]
@sachinpkale Thanks for filing, please provide context for what should be addressed with this issue and reopen.
