### ISSUE TITLE
[Refactor] Replace recursive FilterPath.parse with iterative approach

### ISSUE THREAD

**Issue by cwperks** [opensearch-project/OpenSearch#12067]
### Describe the bug

This issue is related to a recent pull request: https://github.com/opensearch-project/OpenSearch/pull/11060

There is another instance of recursion used in the [FilterPath.parse](https://github.com/opensearch-project/OpenSearch/blob/main/libs/core/src/main/java/org/opensearch/core/xcontent/filtering/FilterPath.java#L112-L128) method which appears inefficient and unnecessary. It appears to be ignoring repeat `.` until the last is located and could more optimally skip until the last `.` in the sequence instead of recursing.  

### Additional Context

In https://github.com/opensearch-project/OpenSearch/pull/11060, there was a recursive method for evaluating core's own [Regex](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/common/regex/Regex.java) class. The method [simpleMatchWithNormalizedString](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/common/regex/Regex.java#L131-L153) was refactored from a recursive approach to an iterative approach for more predictable space and runtime complexity.

- [ ] Refactor FilterPath.parse to use iterative method
- [ ] Update FilterPathTests to cover more scenarios

### Related component

Search

### To Reproduce

Should maintain same behavior as now

### Expected behavior

Should maintain same behavior as now

**Comment by peternied** [comment]
[Triage - attendees [1](https://github.com/peternied) [2](https://github.com/lukas-vlcek/) [3](https://github.com/andrross) [4](https://github.com/CEHENKLE) [5](https://github.com/dbwiddis) [6](https://github.com/reta/) [7](https://github.com/anasalkouz) [8](https://github.com/aggarwalShivani)]
@cwperks Thanks for filing, we'd gladly review a pull request.

**Comment by getsaurabh02** [comment]
We discussed this in the Search community meeting today. @jainankitk  is going to take a stab at it this week.

**Comment by jainankitk** [comment]
@niyatiagg - Can you help with this issue? You fixed similar issue in the past
