### ISSUE TITLE
[Refactor] Replace recursive Glob.globMatch with iterative approach

### ISSUE THREAD

**Issue by cwperks** [opensearch-project/OpenSearch#12065]
### Describe the bug

This issue is related to a recent pull request: https://github.com/opensearch-project/OpenSearch/pull/11060

Similar to core's [Regex](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/common/regex/Regex.java) class, there is another internal class called [Glob](https://github.com/opensearch-project/OpenSearch/blob/main/libs/common/src/main/java/org/opensearch/common/Glob.java) which also uses recursion to evaluate a glob match. This method can also be updated to use an iterative approach. 

### Additional Context

In https://github.com/opensearch-project/OpenSearch/pull/11060, there was a recursive method for evaluating core's own [Regex](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/common/regex/Regex.java) class. The method [simpleMatchWithNormalizedString](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/common/regex/Regex.java#L131-L153) was refactored from a recursive approach to an iterative approach for more predictable space and runtime complexity. 

- [ ] Refactor Glob.globMatch to use iterative method
- [ ] Update FilterPathTests to cover more scenarios

### Related component

Search

### To Reproduce

Should maintain same behavior as now

### Expected behavior

Should maintain same behavior as now

**Comment by peternied** [comment]
[Triage - attendees [1](https://github.com/peternied) [2](https://github.com/lukas-vlcek/) [3](https://github.com/andrross) [4](https://github.com/CEHENKLE) [5](https://github.com/dbwiddis) [6](https://github.com/reta/) [7](https://github.com/anasalkouz) [8](https://github.com/aggarwalShivani)]
@cwperks thanks for filing, we'd gladly review a pull request for this.

**Comment by robinf95** [comment]
I'm currently working on it.

**Comment by msfroh** [comment]
@jainankitk  will find a new owner to get this PR across the line

**Comment by cwperks** [comment]
@jainankitk I would volunteer to take on this issue. I fixed a very similar issue [here](https://github.com/opensearch-project/OpenSearch/pull/11060).

**Comment by niyatiagg** [comment]
Can I pick this up if its still available?
