### ISSUE TITLE
[BUG] OpenSearch 1.0.1 root endpoint reports version as 1.0.0

### ISSUE THREAD

**Issue by ankane** [opensearch-project/OpenSearch#1207]
**Describe the bug**

OpenSearch 1.0.1 (downloaded from opensearch.org) reports the wrong version number.

```sh
{
  "name" : "fv-az212-141",
  "cluster_name" : "opensearch",
  "cluster_uuid" : "NAusPHIAQWy7GkP0dWAMZA",
  "version" : {
    "distribution" : "opensearch",
    "number" : "1.0.0",
    "build_type" : "tar",
    "build_hash" : "34550c5b17124ddc59458ef774f6b43a086522e3",
    "build_date" : "2021-07-02T23:22:21.383695Z",
    "build_snapshot" : false,
    "lucene_version" : "8.8.2",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "The OpenSearch Project: https://opensearch.org/"
}
```

**To Reproduce**

```sh
curl http://localhost:9200/  
```

**Expected behavior**

Reports version as 1.0.1.

**Host/Environment (please complete the following information):**
 - OS: Linux
 - Version: 1.0.1

**Comment by tlfeng** [comment]
Hi @ankane, thanks for reporting this issue. 😁 We are looking for a new mechanism for reporting the OpenSearch bundle version in this issue: https://github.com/opensearch-project/OpenSearch/issues/1111.
If you have any opinions on how the "bundle version" should be reported, please feel free to tell us.

The response of `http://localhost:9200/ ` can only report the version of OpenSearch core, and it is also mentioned in the forum thread: https://discuss.opendistrocommunity.dev/t/opensearch-1-0-1-is-now-available/6905.

**Comment by ankane** [comment]
Hey @tlfeng, thanks for the response. Will close this out, but I think it'd be more intuitive to report 1.0.1. If it's easiest to match the core version, maybe the core version could be bumped even when there are no changes.
