### ISSUE TITLE
[BUG] Invalid json error responses

### ISSUE THREAD

**Issue by sebmjoll** [opensearch-project/OpenSearch#12149]
### Describe the bug

When running queries against an AWS-managed OpenSearch 1.3 cluster, when the cluster is under load, we sometimes get the following error payload when trying to index a document:
```
{
  "message": "No server available to handle the request",
}
```

The trailing comma makes it invalid json and the library "@opensearch-project/opensearch" version 2.5.0 fails to parse it with errors like this:
```
Unexpected token } in JSON at position 60
```

We also get sometimes another invalid json response when searching:
```
{
  "message": "Empty or invalid response",
}
```

### Related component

Other

### To Reproduce

I don't know how to force errors like that.

### Expected behavior

If the APIs are supposed to return strictly valid JSON, then they should not return invalid JSON.

If on the other hand, these response payloads are considered legit, the javascript "@opensearch-project/opensearch" library should not fail to parse them.

### Additional Details

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**

**Comment by dblock** [comment]
This seems like an AWS-specific problem that's generated on some gateway and not inside OpenSearch, or at least I couldn't find this string anywhere in this project.

Have you opened a ticket with AWS yet? If not, could you please do that? I'd like to close it here once you did.

**Comment by sebmjoll** [comment]
We are reporting this to AWS, yes.

**Comment by dblock** [comment]
Thanks @sebmjoll, I'm going to close this here. Feel free to reopen/comment if you don't get traction or a response and I can see if I can help.
