### ISSUE TITLE
[BUG] Reduce TaskBatcher excessive logging in DEBUG mode

### ISSUE THREAD

**Issue by amkhar** [opensearch-project/OpenSearch#12249]
### Describe the bug

https://github.com/opensearch-project/OpenSearch/blob/a0b519826b2dab19f022e16e613f630a0bce253e/server/src/main/java/org/opensearch/cluster/service/TaskBatcher.java#L197-L201

While executing a pending task, we first try to log the task summary. If the pending task batchingKey has 200K tasks in the linked list, we'll end up collecting task summary of all those tasks. This takes 10 minutes which blocks the overall execution of all the tasks. This summary is being used only for logging purpose in debug setting only. 

Ideally we should not log excessive even in debug mode as calculating log string is taking minutes. 

### Related component

Cluster Manager

### To Reproduce

1. Create 200K primary shards in a cluster which can take load of these many shards
2. kill opensearch process on all cluster manager nodes, so it triggers reroute flow
3. You'll see shards will go in init mode quickly 
4. But actually starting these shards will take more than 10 minutes

### Expected behavior

Ideally we should not log the same thing if content is same just the shardId is different. We should short circuit and log a smaller sized string to avid this delay. 

### Additional Details

Hot/threads 

```
::: {6bb0987818c65f26bf4a1028fbc6d538}{l9ltzN3dT5GCddpWAkPLYg}{1JNBmxGoSrqq3Jpe4ywfgg}<redacted>
   Hot threads at 2024-02-06T16:08:40.878Z, interval=500ms, busiestThreads=3, ignoreIdleThreads=true:
   
   99.8% (498.8ms out of 500ms) cpu usage by thread 'opensearch[6bb0987818c65f26bf4a1028fbc6d538][clusterManagerService#updateTask][T#1]'
     10/10 snapshots sharing following 15 elements
       java.base@17.0.6/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
       java.base@17.0.6/java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1850)
       java.base@17.0.6/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
       java.base@17.0.6/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
       java.base@17.0.6/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
       java.base@17.0.6/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
       java.base@17.0.6/java.util.stream.ReferencePipeline.reduce(ReferencePipeline.java:662)
       app//org.opensearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:202)
       app//org.opensearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:243)
       app//org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:756)
       app//org.opensearch.common.util.concurrent.PrioritizedOpenSearchThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedOpenSearchThreadPoolExecutor.java:282)
       app//org.opensearch.common.util.concurrent.PrioritizedOpenSearchThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedOpenSearchThreadPoolExecutor.java:245)
       java.base@17.0.6/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
       java.base@17.0.6/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
       java.base@17.0.6/java.lang.Thread.run(Thread.java:833)
```

**Comment by shwetathareja** [comment]
We should look at 2 things:
1. debug log should be brief
2. trace can be more detailed but still need to be capped (considering there can be 100k more tasks being batched together), it would be too expensive to log all those in clustermanagerService#updateTask which is single threaded.

**Comment by sumitasr** [comment]
Looking into it

**Comment by sumitasr** [comment]
Tasksummary string is being computed and passed to runTasks in Masterservice

https://github.com/opensearch-project/OpenSearch/blob/a0b519826b2dab19f022e16e613f630a0bce253e/server/src/main/java/org/opensearch/cluster/service/MasterService.java#L284

Usage:

Logging - 

https://github.com/opensearch-project/OpenSearch/blob/a0b519826b2dab19f022e16e613f630a0bce253e/server/src/main/java/org/opensearch/cluster/service/MasterService.java#L287

https://github.com/opensearch-project/OpenSearch/blob/a0b519826b2dab19f022e16e613f630a0bce253e/server/src/main/java/org/opensearch/cluster/service/MasterService.java#L291

https://github.com/opensearch-project/OpenSearch/blob/a0b519826b2dab19f022e16e613f630a0bce253e/server/src/main/java/org/opensearch/cluster/service/MasterService.java#L295

https://github.com/opensearch-project/OpenSearch/blob/a0b519826b2dab19f022e16e613f630a0bce253e/server/src/main/java/org/opensearch/cluster/service/MasterService.java#L304

https://github.com/opensearch-project/OpenSearch/blob/a0b519826b2dab19f022e16e613f630a0bce253e/server/src/main/java/org/opensearch/cluster/service/MasterService.java#L310

https://github.com/opensearch-project/OpenSearch/blob/a0b519826b2dab19f022e16e613f630a0bce253e/server/src/main/java/org/opensearch/cluster/service/MasterService.java#L314

https://github.com/opensearch-project/OpenSearch/blob/a0b519826b2dab19f022e16e613f630a0bce253e/server/src/main/java/org/opensearch/cluster/service/MasterService.java#L316

https://github.com/opensearch-project/OpenSearch/blob/a0b519826b2dab19f022e16e613f630a0bce253e/server/src/main/java/org/opensearch/cluster/service/MasterService.java#L328

Passed as source parameter in ClusterChangedEvent object - 

https://github.com/opensearch-project/OpenSearch/blob/a0b519826b2dab19f022e16e613f630a0bce253e/server/src/main/java/org/opensearch/cluster/service/MasterService.java#L320

**Comment by sumitasr** [comment]
Looks like change in the summary value in ClusterChangedEvent should not have an impact on the flow. For now, i am working on introducing a short summary which will contain the task batching key instead of computing and logging full tasks details.
