### ISSUE TITLE
[BUG] Remote Purge threadpool taking too much memory  in case of too much deleted indices cleanup

### ISSUE THREAD

**Issue by gbbafna** [opensearch-project/OpenSearch#12253]
### Describe the bug

![image (1)(1)](https://github.com/opensearch-project/OpenSearch/assets/85113518/27bda813-fc60-4d99-b926-0b577e55c73b)

We use `Remote Purge` threadpool to delete segments data for deleted indices in shallow snapshots. When the number of such indices are huge, as well as the count of snapshots are huge , we see a pile up of `Remote Purge` threadpool . In the above heap dump , we can see 30 million instance of `Remote Purge` threads hogging up the memory of  around 30 GB.

### Related component

Storage:Remote

### Expected behavior

Remote Purge threadpool should be bounded . 

Shallow Snapshot Deletion also needs to be smarter to handle this deletion in a scalable way . 

### Additional Details

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**

**Comment by ashking94** [comment]
[Storage Triage - attendees [1](https://github.com/ashking94/) [2](https://github.com/sachinpkale/) [3](https://github.com/gbbafna/) [4](https://github.com/Bukhtawar/) [5](https://github.com/rramachand21/) [6](https://github.com/skumawat2025/) [7](https://github.com/shourya035/) [8](https://github.com/vikasvb90/) [9](https://github.com/BhumikaSaini-Amazon/) [10](https://github.com/ltaragi/) [11](https://github.com/lukas-vlcek/) [12](https://github.com/astute-decipher/)]

@harishbhakuni  The linked PR is closed. Will there be further PRs or this can be closed?

**Comment by harishbhakuni** [comment]
Hi @ashking94 , this issue can be closed.
