### ISSUE TITLE
[Tiered Caching][Milestone 1] Refactor Tiered caching interfaces

### ISSUE THREAD

**Issue by sgup432** [opensearch-project/OpenSearch#12296]
### Is your feature request related to a problem? Please describe

As part of initial Tiered caching framework, we had exposed StoreAwareCache([link](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/common/cache/store/StoreAwareCache.java)) and tiered spillover cache framework([link](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/common/cache/tier/TieredSpilloverCache.java)) which has all the logic to spill evicted items to the disk tier.

While reviewing further changes [here](https://github.com/opensearch-project/OpenSearch/pull/11874) and elsewhere, we discussed whether StoreAwareCache is really needed as it exposes cacheStoreType which shouldn't be needed to the consumer. And also ideally tieredSpilloverCache should be moved to a module as it is optional and not required to be within OpenSearch core. Considering we are now also maintaining cache stats within cache itself([link](https://github.com/opensearch-project/OpenSearch/issues/12258)) instead of using a listener based approach, all this required following changes as mentioned below.

### Describe the solution you'd like

So as part of this issue we will refactor following:
- Move TieredSpilloverCache to a module
- Remove StoreAwareCache interface and not expose CacheStoreType in core.
- Remove listener for hits/misses/evictions
- Provide a way for any type of cache(IndicesRequestCache for example) to initialize any kind of ICache via setting based mechanism.

### Related component

Search:Performance

**Comment by sgup432** [comment]
@msfroh

**Comment by peternied** [comment]
[Triage - attendees [1](https://github.com/peternied) [2](https://github.com/reta/) [3](https://github.com/andrross) [4](https://github.com/dbwiddis) [5](https://github.com/sohami) [6](https://github.com/lukas-vlcek) [7](https://github.com/kotwanikunal) [8](https://github.com/Bukhtawar)]
@sgup432 Thanks for opening up this issue for follow up, looking forward to these improvements.

**Comment by scrawfor99** [comment]
@opensearch-project/opensearch-core I believe this can be closed.

**Comment by getsaurabh02** [comment]
@sgup432 should we close this out?
