### ISSUE TITLE
[BUG] org.opensearch.upgrades.IndexingIT.testIndexingWithSegRep flaky

### ISSUE THREAD

**Issue by peternied** [opensearch-project/OpenSearch#12336]
### Describe the bug

org.opensearch.upgrades.IndexingIT.testIndexingWithSegRep is flaky, [jenkins logs](https://build.ci.opensearch.org/job/gradle-check/33789/testReport/org.opensearch.upgrades/IndexingIT/testIndexingWithSegRep/).

Assertion is from this codeblock:
https://github.com/opensearch-project/OpenSearch/blob/f73c82aa466cf3354b5d2e3e3f46f0613cacbb0f/qa/rolling-upgrade/src/test/java/org/opensearch/upgrades/IndexingIT.java#L119-L121

```
Suppressed: java.lang.AssertionError: expected:<0> but was:<1>
  at org.junit.Assert.fail(Assert.java:89)
  at org.junit.Assert.failNotEquals(Assert.java:835)
  at org.junit.Assert.assertEquals(Assert.java:647)
  at org.junit.Assert.assertEquals(Assert.java:633)
  at org.opensearch.upgrades.IndexingIT.lambda$waitForSearchableDocs$0(IndexingIT.java:121)
  at org.opensearch.test.OpenSearchTestCase.assertBusy(OpenSearchTestCase.java:1106)
  ... 40 more
```

### Related component

Indexing

### To Reproduce

```
REPRODUCE WITH: ./gradlew ':qa:rolling-upgrade:v2.13.0#upgradedClusterTest' --tests "org.opensearch.upgrades.IndexingIT.testIndexingWithSegRep" -Dtests.seed=326EEB751FF1EA22 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=ru-RU -Dtests.timezone=Africa/Timbuktu -Druntime.java=21
```

### Expected behavior

Test pass consistently

### Additional Details

- Might be related to https://github.com/opensearch-project/OpenSearch/issues/7679

**Comment by peternied** [comment]
@andrross @dreamer-89 @sarthakaggarwal97 @mch2 Adding you folks in since you seem to have context on the previous fix - this issue might be from a different source since the callstack don't seem to align with #7679

**Comment by peternied** [comment]
[Triage - attendees [1](https://github.com/peternied) [2](https://github.com/dbwiddis) [3](https://github.com/lukas-vlcek) [4](https://github.com/kotwanikunal) [5](https://github.com/linuxpi)]
@peternied thanks for filing, consider a pull request to resolve

**Comment by reta** [comment]
Closing in favour of https://github.com/opensearch-project/OpenSearch/issues/14302
