### ISSUE TITLE
[BUG] Remote Connection Fails to Reconnect When Remote Cluster is Restarted. 

### ISSUE THREAD

**Issue by zalseryani** [opensearch-project/OpenSearch#12358]
### Describe the bug

- Creating remote cluster connection 
```
PUT _cluster/settings
{
  "persistent": {
    "cluster": {
      "remote": {
        "my-connection-alias": {
          "seeds": ["my-opensearch-domain/service:port"]
        }
      }
    }
  }
}
```
- After creation, remote status shows its connected, 
- Restart remote cluster (prod) and check the remote connection status, you will see that its not connected. 

Kindly advise if I am missing something here for such configuration, because in case of a cluster restart, the cross cluster replication stops, and in such case we need to recreate the remote connection since the previous one does not try to reconnect again, and re-initiate the cross-cluster replication (whether it was single index or with autofollow) 

Thank you.

### Related component

Indexing:Replication

### To Reproduce

1- create prod and dr opensearch clusters
2- create remote cluster connection from dr site . 
```
PUT _cluster/settings
{
  "persistent": {
    "cluster": {
      "remote": {
        "my-connection-alias": {
          "seeds": ["my-opensearch-domain/service:port"]
        }
      }
    }
  }
}
```
3- restart prod site and check the status of the remote connection from the dr site. 
```
GET _remote/info
```

### Expected behavior

- Expected behavior that remote connection from DR to PROD site should try to reconnect every specific time. 

- I am not sure if this is configurable currently , as I checked the documentation settings for remote connection or cross-site replication and did not find configuration related to this case. 

- [Replication settings](https://opensearch.org/docs/latest/tuning-your-cluster/replication-plugin/settings/)

### Additional Details

- opensearch deployed in kubernetes. 
- both prod and dr opensearch clusters version is 2.11.1

**Comment by mgodwan** [comment]
@opensearch-project/engineering-effectiveness Can you help move this issue to github.com/opensearch-project/cross-cluster-replication?

**Comment by mgodwan** [comment]
@ankitkala Do you mind taking a look at this?

**Comment by zalseryani** [comment]
@ankitkala 
when you say address, do you mean pods IP addresses ?

**Comment by ankitkala** [comment]
> @ankitkala 
> when you say address, do you mean pods IP addresses ? 
> 

I'm talking about the address you've used as seed nodes. In this case, yes, I think it's pod's address.

**Comment by zalseryani** [comment]
@ankitkala 
The address (domain) is the same and not changed, at least it should recheck again using the same kubernetes service name. 
Am I correct ?

**Comment by zalseryani** [comment]
@ankitkala 
Yes, I have already tried to use it, but my issue is that when restarting the cluster, the replication is paused, and I have to re-creat a new remote connection in order to trigger/resume the replication again. 

I know that I can create another remote connection and trigger it again, but the case is that the engine should retry to connect to the production cluster without the need of creating another remote connection and trigger/resume the replication again 

Thank you.

**Comment by zalseryani** [comment]
- I will reproduce the scenario with the requested stack trace and status you required as soon as possible. 

Thank you.

**Comment by skumarp7** [comment]
Hi @zalseryani , 

Are you aware of what is that "decent amount of time"? Is this a configurable parameter?
