### ISSUE TITLE
[BUG] Getting error "error while sniffing nodes" while running docker compose  opensearch

### ISSUE THREAD

**Issue by lijie123bes** [opensearch-project/OpenSearch#12431]
### Describe the bug

I am getting below error while using spring data opensearch. I am using docker compose to build the image:

2024-02-19T10:24:24.994Z ERROR 1 --- [nt_sniffer[T#1]] org.opensearch.client.sniff.Sniffer      : error while sniffing nodes
os_project  | 
os_project  | java.net.ConnectException: Connection refused
os_project  |   at org.opensearch.client.RestClient.extractAndWrapCause(RestClient.java:954) ~[opensearch-rest-client-2.11.0.jar:2.11.0]
os_project  |   at org.opensearch.client.RestClient.performRequest(RestClient.java:333) ~[opensearch-rest-client-2.11.0.jar:2.11.0]
os_project  |   at org.opensearch.client.RestClient.performRequest(RestClient.java:321) ~[opensearch-rest-client-2.11.0.jar:2.11.0]
os_project  |   at org.opensearch.client.sniff.OpenSearchNodesSniffer.sniff(OpenSearchNodesSniffer.java:122) ~[opensearch-rest-client-sniffer-2.11.0.jar:2.11.0]
os_project  |   at org.opensearch.client.sniff.Sniffer.sniff(Sniffer.java:223) ~[opensearch-rest-client-sniffer-2.11.0.jar:2.11.0]
os_project  |   at org.opensearch.client.sniff.Sniffer$Task.run(Sniffer.java:154) ~[opensearch-rest-client-sniffer-2.11.0.jar:2.11.0]
os_project  |   at org.opensearch.client.sniff.Sniffer$1.run(Sniffer.java:95) ~[opensearch-rest-client-sniffer-2.11.0.jar:2.11.0]
os_project  |   at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[na:na]
os_project  |   at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
os_project  |   at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[na:na]
os_project  |   at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
os_project  |   at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]

os_project  | 2024-02-19T10:24:25.182Z  WARN 1 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.boot.autoconfigure.data.elasticsearch.ElasticsearchDataConfiguration$ReactiveRestClientConfiguration': Lookup method resolution failed
os_project  | 2024-02-19T10:24:25.187Z  INFO 1 --- [           main] j.LocalContainerEntityManagerFactoryBean : Closing JPA EntityManagerFactory for persistence unit 'default'

### Related component

Clients

### Expected behavior

I want to run my springboot application with latest opensearch integration

### Additional Details

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**

**Comment by tlfeng** [comment]
Could you double check the OpenSearch cluster configuration in your code?
I searched for some [similar problem](https://stackoverflow.com/questions/62039091/spring-boot-elastic-search-connection-refused-with-java-resthighlevelclient), and saw that:
> connection refused means that there is no cluster/server at the configured address

The error occurs in the very beginning step of the sniffer.
https://github.com/opensearch-project/OpenSearch/blob/2c355ce1a427e4a528778d4054436b5c4b756221/client/sniffer/src/main/java/org/opensearch/client/sniff/Sniffer.java#L156

**Comment by peternied** [comment]
[Triage - attendees [1](https://github.com/peternied) [2](https://github.com/reta) [3](https://github.com/lukas-vlcek/) [4](https://github.com/srikanthpadakanti) [5](https://github.com/Mahima081)]
@lijie123bes Thanks for filing this isssue - this looks related to the following issue [1], please use that issue/repository for follow up

- [1] https://github.com/opensearch-project/spring-data-opensearch/issues/121
