### ISSUE TITLE
[Feature Request] Add save search query in Discover for read-only user

### ISSUE THREAD

**Issue by sakib789** [opensearch-project/OpenSearch#12492]
### Is your feature request related to a problem? Please describe

The read-only user is not able to save a search on the Discover Tab of Opensaerch. It needs additional permission like kibana_user. Is there any way we can save the search only with read-only permission? If not request to add that feature.

### Describe the solution you'd like

Save the search query with only read-only user permission.

### Related component

Search:Query Capabilities

**Comment by rishabhmaurya** [comment]
@sakib789 could you open it in dashboard repo, thank you

**Comment by sakib789** [comment]
Okay. I will. Thank you for the information.
