### ISSUE TITLE
[BUG] Unused fetch sub phase processors initialized during fetch phase

### ISSUE THREAD

**Issue by jainankitk** [opensearch-project/OpenSearch#12502]
### Describe the bug

Opensearch initializes sub processors even if are not getting used during the fetch phase. Can be prevented by validating if size of fields is greater than zero in addition to it being non-null. Take below snippet from `InnerHitsPhase` class:

```
public FetchSubPhaseProcessor getProcessor(FetchContext searchContext) {
        if (searchContext.innerHits() == null) {
            return null;
        }
```

This should not get initialized if the innerHits count is 0

### Related component

Search:Performance

### To Reproduce

1. Add data http_logs into Opensearch
2. Run below query:
```
curl -XGET "http://localhost:9200/logs-241998/_search?pretty" -H 'Content-Type: application/json' -d'
{"size": 1000,
  "query": {
    "match_all": {}
  },"docvalue_fields":["clientip"],
 "sort": [{"size":"asc"}]
}'
```
3. Attach debugger to above code reference

### Expected behavior

Unnecessary initialization of fetch sub phase processor should be skipped

**Comment by andrross** [comment]
@jainankitk This is an enhancement not a bug, right? There's no correctness issue here right?

**Comment by jainankitk** [comment]
> @jainankitk This is an enhancement not a bug, right? There's no correctness issue here right?

I would say it is both bug and enhancement. Bug - because it was not intended to be so. Although, there should not be any  perceived difference from customer experience perspective. So, should be okay to label it as enhancement
