### ISSUE TITLE
[Derived Fields] Add basic query support with derived fields

### ISSUE THREAD

**Issue by qreshi** [opensearch-project/OpenSearch#12508]
### Is your feature request related to a problem? Please describe

Once the derived field mapper is added, basic query support with derived fields will need to be implemented.

### Describe the solution you'd like

Add a new Query (ex. `DerivedFieldQuery` or `DerivedFieldMatchQuery` if there will be multiple types) which takes a parent query and the derived field mapper objects (there can be multiple derived fields mentioned in a query).

The query will create a custom weight function (somewhat similar to `SourceFieldMatchQuery`) and execute the parent query. In the two phase iterator matches(), it will fetch the value of matching document executing the painless script associated with the runtime mapper field object. It will create a Lucene `MemoryIndex` with just one field of `type` fetched from mapper field object and value just fetched using painless script by executing against matched document _source.

### Related component

Search

**Comment by rishabhmaurya** [comment]
I have tried adding the support for query execution (https://github.com/rishabhmaurya/OpenSearch/commit/90499bfaaf2bef08cfd339104eeceb918ad2e711#diff-14a9f3c687532d5bec9cf3d510a66dce6cfe38026b07eaae85fc2be2e73a96c5 ) on derived fields on top of @qreshi change https://github.com/qreshi/OpenSearch/tree/derived-field-mapper .
It currently supports these operations - https://gist.github.com/rishabhmaurya/e5f0375ed7a4b59fb8c094d789f95d33
