### ISSUE TITLE
s There An Actively Developed Open Source Crawler/Indexer for OpenSearch for Samba Shares? ( like FSCrawler and fs2es-Indexer for ElasticSearch)

### ISSUE THREAD

**Issue by vepicurean** [opensearch-project/OpenSearch#12517]
### Is your feature request related to a problem? Please describe

See here... significant functionality missing to search Samba shares using OpenSearch engine. 

### Describe the solution you'd like

Describend here... Several people have had this issue for years. This no solution to the issue for searching Samba shares that I can see. 

https://github.com/opensearch-project/OpenSearch/issues/12456

### Related component

Indexing

### Describe alternatives you've considered

See here. The alternative is going back to ElasticSearch. 

https://github.com/opensearch-project/OpenSearch/issues/12456

### Additional context

Not sure why this was closed before... Please see here. It's a something that has been mentioned for years before. 

https://github.com/opensearch-project/OpenSearch/issues/12456

**Comment by dblock** [comment]
Please don't open duplicate issues. https://github.com/opensearch-project/OpenSearch/issues/12456 was closed because this is outside of scope of the OpenSearch core engine itself, which is this repo. Lets discuss whether to reopen that issue there.
