### ISSUE TITLE
[BUG] GET /_cluster/stats and GET /_nodes bcw broken

### ISSUE THREAD

**Issue by dblock** [opensearch-project/OpenSearch#12528]
### Describe the bug

The change in https://github.com/opensearch-project/OpenSearch/pull/12271 resulted in a breaking change within `2.x` as `GET /_cluster/stats` and `GET /_nodes` both contain the `PluginInfo` object in their response bodies, and the `opensearch_version` field has changed from a string to an array.

### Related component

Plugins

### To Reproduce

```
GET /_cluster/stats
GET /_nodes
```

### Expected behavior

Revert to 2.12 behavior.

**Comment by dblock** [comment]
@abseth-amzn

**Comment by shwetathareja** [comment]
@abseth-amzn are you looking into it on priority?

**Comment by abseth-amzn** [comment]
Looking into it

**Comment by abseth-amzn** [comment]
PR - https://github.com/opensearch-project/OpenSearch/pull/12537

**Comment by abseth-amzn** [comment]
PR for main - https://github.com/opensearch-project/OpenSearch/pull/12543
