### ISSUE TITLE
Introduce extension points in core Engine abstraction supporting customizability of subset of Engine functionalities

### ISSUE THREAD

**Issue by krishna-ggk** [opensearch-project/OpenSearch#1254]
**Is your feature request related to a problem? Please describe.**
Plugins like [cross-cluster-replication](https://github.com/opensearch-project/cross-cluster-replication/blob/main/src/main/kotlin/org/opensearch/replication/ReplicationEngine.kt), [k-NN](https://github.com/opensearch-project/k-NN/blob/1973eeaedb3aa1444db42814966c73d391e9c5c4/src/main/java/org/opensearch/knn/plugin/KNNEngineFactory.java) have a need to customize certain functionality of Engine such as translog pruning behavior,  codec. However with current abstraction mechanism provided by OpenSearch, these plugins are having to provide a full [Engine](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/index/engine/Engine.java) that is to be attached to an index (based on an index setting).

There are downsides to this such as
1. Though the functionalities customized by plugins are independent, it places [expensive restriction of only one plugin being able to provide the behavior](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/indices/IndicesService.java#L689). This means an index cannot benefit from features provided by more than one plugin.
2. Plugins have too much control and can override behavior for all indices and thus blocking other plugins from able to customize behavior.
3. Engine can be attached only during IndexShard object construction which limits dynamism. An index would have to be closed & opened to be attached with different Engine implementation (or be a default implementation which increases scope of impact). This downtime is unacceptable for many usecases.

**Describe the solution you'd like**
At a high level, it seems imminent to break up Engine and provide extension points for smaller feature set that can be customized by plugins.

As a starter, one of the question is - does it make sense to start with an abstraction where plugins can provide TranslogDeletionPolicy. Multiple plugins can provide it and the min is used to actually prune.

**Comment by mch2** [comment]
> As a starter, one of the question is - does it make sense to start with an abstraction where plugins can provide TranslogDeletionPolicy. Multiple plugins can provide it and the min is used to actually prune.

I understand the logic here but I'm concerned that having multiple plugins provide their own candidates will make debugging painful.

I suggest we start in 1.2 with a `TranslogConfigPlugin`, where a plugin may specify their own deletion policy with the restriction that only one plugin is allowed to provide the override.  I cut #1260 so we can address this one at a time.  

Completely refactoring engine to allow more than one is breaking and would need to move in a major release.

**Comment by dblock** [comment]
I believe this is resolved with the above, closing.
