### ISSUE TITLE
[BUG] org.opensearch.search.query.SimpleQueryStringIT. testDocWithAllTypes  is flaky

### ISSUE THREAD

**Issue by kkewwei** [opensearch-project/OpenSearch#12574]
### Describe the bug
org.opensearch.search.query.SimpleQueryStringIT.testDocWithAllTypes  is flaky.

The following code can create too much TermQuery
```
resp = client().prepareSearch("test").setQuery(simpleQueryStringQuery("foo Bar 19 127.0.0.1").defaultOperator(Operator.AND)).get();
```
https://github.com/opensearch-project/OpenSearch/blob/main/server/src/internalClusterTest/java/org/opensearch/search/query/SimpleQueryStringIT.java#L591

### To Reproduce

./gradlew ':server:internalClusterTest' --tests "org.opensearch.search.query.SimpleQueryStringIT" -Dtests.method="testDocWithAllTypes {p0={"search.concurrent_segment_search.enabled":"false"}}" -Dtests.seed=15CDBEEC78B94AB3 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=ms -Dtests.timezone=Europe/Zurich -Druntime.java=21

### Expected behavior

Test should pass

### Additional context
Jenkins build failure link - https://build.ci.opensearch.org/job/gradle-check/34541/

**Comment by andrross** [comment]
[Triage - attendees [1](https://github.com/andrross) [2](https://github.com/reta) [3](https://github.com/lukas-vlcek)]
@kkewwei Thanks for filing this issue. Looking forward to seeing progress on the PR.
