### ISSUE TITLE
[BUG] Include Security Reporting Instructions on README

### ISSUE THREAD

**Issue by stockholmux** [opensearch-project/OpenSearch#1266]
**Describe the bug**

Most repos include the security reporting warning ('If you discover a potential security issue...') on the README as well as in the issue template. 

**To Reproduce**
Read the README

**Expected behavior**
It has the security reporting warning

**Comment by tlfeng** [comment]
@stockholmux Could you verify if the above PR resolved the issue? Thank you. 😁
Then we could close the issue.

**Comment by peternied** [comment]
The readme has security reporting instructions
