### ISSUE TITLE
[BUG] org.opensearch.recovery.RelocationIT.testIndexSearchAndRelocateConcurrently is Flaky

### ISSUE THREAD

**Issue by harishbhakuni** [opensearch-project/OpenSearch#12675]
### Describe the bug

org.opensearch.recovery.RelocationIT.testIndexSearchAndRelocateConcurrently test is flaky.
Failed with following error in [https://build.ci.opensearch.org/job/gradle-check/34934/](https://build.ci.opensearch.org/job/gradle-check/34934/testReport/junit/org.opensearch.recovery/RelocationIT/testIndexSearchAndRelocateConcurrently__p0___cluster_indices_replication_strategy___SEGMENT___/):
```
java.lang.RuntimeException: Can't get cluster-manager node null
```

### Related component

Other

### To Reproduce

REPRODUCE WITH: ./gradlew ':server:internalClusterTest' --tests "org.opensearch.recovery.RelocationIT" -Dtests.seed=1331E65F9D8C26DF -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=en -Dtests.timezone=Etc/UTC -Druntime.java=21

However was not able to reproduce it locally with same seed.

### Expected behavior

test should always pass.

### Additional Details

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**
Another failing test from same suite: [org.opensearch.recovery.RelocationIT.testRelocationWhileIndexingRandom {p0={"cluster.indices.replication.strategy":"SEGMENT"}}](https://build.ci.opensearch.org/job/gradle-check/34934/testReport/junit/org.opensearch.recovery/RelocationIT/testRelocationWhileIndexingRandom__p0___cluster_indices_replication_strategy___SEGMENT___/)

**Comment by harishbhakuni** [comment]
Another failing test from same suite: [org.opensearch.recovery.RelocationIT.testRelocationWhileIndexingRandom {p0={"cluster.indices.replication.strategy":"SEGMENT"}}](https://build.ci.opensearch.org/job/gradle-check/34934/testReport/junit/org.opensearch.recovery/RelocationIT/testRelocationWhileIndexingRandom__p0___cluster_indices_replication_strategy___SEGMENT___/)

**Comment by andrross** [comment]
[Triage - attendees [1](https://github.com/andrross) [2](https://github.com/reta) [3](https://github.com/lukas-vlcek/) [4](https://github.com/Mahima081) [5](https://github.com/dbwiddis) [6](https://github.com/srikanthpadakanti)]
@harishbhakuni Thanks for filing.

**Comment by shwetathareja** [comment]
Failed again here - https://github.com/opensearch-project/OpenSearch/pull/14095#issuecomment-2158425016

**Comment by reta** [comment]
Closing in favour of https://github.com/opensearch-project/OpenSearch/issues/14309
