### ISSUE TITLE
[BUG] org.opensearch.common.settings.SettingTests.testMemorySizeWithFallbackValue is flaky

### ISSUE THREAD

**Issue by kkewwei** [opensearch-project/OpenSearch#12705]
### Describe the bug

org.opensearch.common.settings.SettingTests.testMemorySizeWithFallbackValue is flaky.

### Related component

Other

### To Reproduce

JvmInfo.jvmInfo().getMem().getHeapMax().getBytes()=8.0gb

./gradlew ':server:test' --tests "org.opensearch.common.settings.SettingTests.testMemorySizeWithFallbackValue" -Dtests.seed=B6AA005F20EE7928 -Dtests.security.manager=true -Dtests.jvms=1 -Dtests.heap.size=1g -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=sq -Dtests.timezone=Africa/Asmera -Druntime.java=17

if JvmInfo.jvmInfo().getMem().getHeapMax().getBytes()=8gb, (JvmInfo.jvmInfo().getMem().getHeapMax().getBytes() * 0.3) > Integex.MAX, then (long)((int) value) will lose precision.
https://github.com/opensearch-project/OpenSearch/blob/b4da802a56f6ec9ed6f57104d94a211919504b34/server/src/test/java/org/opensearch/common/settings/SettingTests.java#L222

### Expected behavior

Test should pass

### Additional Details

**Screenshots**
![image](https://github.com/opensearch-project/OpenSearch/assets/16730433/c78791cd-0090-4f3f-8fbf-f2b6f17e4d18)

**Comment by andrross** [comment]
[Triage - attendees [1](https://github.com/andrross) [2](https://github.com/reta) [3](https://github.com/lukas-vlcek/) [4](https://github.com/Mahima081) [5](https://github.com/dbwiddis) [6](https://github.com/srikanthpadakanti)]
@kkewwei Thanks for filing. Looking forward to seeing the fix merged.
