### ISSUE TITLE
[BUG] Gradle check should be required before merging changes

### ISSUE THREAD

**Issue by peternied** [opensearch-project/OpenSearch#12735]
### Describe the bug

Pull requests have been merged without a passing gradle check introducing defects into main. [1]  The gradle check is the minimal bar that all changes should pass before they are merged into main to ensure consistent code quality.  

- [1] https://github.com/opensearch-project/OpenSearch/issues/12731 

### Expected behavior

Pull requests should only be allowed to merge without a passing gradle check by the Admin team for the project.

### Additional Details

**Additional context**
- Slack conversation about this issue https://opensearch.slack.com/archives/C05L60S4UBT/p1710783271759989

**Comment by peternied** [comment]
My thoughts are that I do not think changes should be mergeable unless they pass the gradle check - save a justification that the admin team agrees with and then performs the override.

**Comment by andrross** [comment]
[Triage - attendees [1](https://github.com/andrross) [2](https://github.com/reta) [3](https://github.com/lukas-vlcek/) [4](https://github.com/Mahima081) [5](https://github.com/dbwiddis) [6](https://github.com/srikanthpadakanti)]
@peternied Thanks for filing.

**Comment by peternied** [comment]
@opensearch-project/admin Could you please update the branch protection rules to require the gradle check in all branches?  We have 3 maintainers (myself, @sohami , @reta) approving this issue.

**Comment by reta** [comment]
@msfroh @dblock FYI :-)

**Comment by bbarani** [comment]
gradle-check has been added as a mandatory check for all branches.

<img width="564" alt="Screenshot 2024-03-20 at 2 59 51 PM" src="https://github.com/opensearch-project/OpenSearch/assets/70038446/412ee4ba-b15d-4e4d-b791-16c13ef45681">

**Comment by reta** [comment]
Thanks a lot @bbarani !

**Comment by mgodwan** [comment]
> Pull requests have been merged without a passing gradle check introducing defects into main. [1] 

@peternied Please note that the referred PR has not introduced any test defects. The failing tests are due to some other changes which have been fixed by the respective owners
