### ISSUE TITLE
Adding a Concatenate Token Filter

### ISSUE THREAD

**Issue by quangmaubach** [opensearch-project/OpenSearch#1278]
name | about | title | labels | assignees
-- | -- | -- | -- | --
💭 Proposal | Adding a Concatenate Token Filter | [PROPOSAL] | proposal |  

## What kind of business use case are you trying to solve? What are your requirements?
We want to do some analysis on our text, and then combine them into a single token. Currently we use a private plugin to handle that. Moving to Amazon OpenSearch, we cannot bring the private plugin over.

Looking for `concatenate token` on search engine, there are many people that have the same/similar requirement. We think that adding a concatenate token filter will be beneficial for many OpenSearch users.

**What is the problem? What is preventing you from meeting the requirements?**
**Example:** from an input string, we want to process via an analyzer chain, which requires tokenization, synonym, stemming, and then recombine all tokens into a single one.

Input: "I am going to school"
Output after several analyzers: "I", "be", "go", "school"
Combine into 1 single token (keyword): "I be go school"

The closest thing that we have currently is `Keyword tokenizer` (link to Elasticsearch https://www.elastic.co/guide/en/elasticsearch/reference/7.9/analysis-keyword-tokenizer.html), however, it will not work with complex token filters (for example, synonyms, which, need to break a long sentence into smaller words and look up synonyms for each word).

Many people are having the same problem, for example, https://discuss.elastic.co/t/how-to-combine-all-tokens-into-one/143158/2, some even implement their own solution, for example, https://github.com/francesconero/elasticsearch-concatenate-token-filter and https://github.com/ryohashimoto/elasticsearch-concatenation-token-filter

**What are you proposing? What do you suggest we do to solve the problem or improve the existing situation?**
Implement Concatenate Token Filter in OpenSearch.

**What are your assumptions or prerequisites?**
Looking at `concatenate tokens` on search engine, I assume that there is demand for such token filter and users are not satisfied with existing solution (or not being able to install plugin onto OpenSearch).

**What are remaining open questions?**
Handling graph-like input, for example, from synonym-graph. We can choose to just pick one token from each position.

**Comment by anasalkouz** [comment]
> Currently we use a private plugin to handle that. Moving to Amazon OpenSearch, we cannot bring the private plugin over.

Did you try to upgrade the plugin to OpenSearch?
[upgrading-plugins-to-opensearch-and-opensearch-dashboards](https://github.com/opensearch-project/opensearch-plugins/blob/main/UPGRADING.md#upgrading-plugins-to-opensearch-and-opensearch-dashboards)

**Comment by quangmaubach** [comment]
@anasalkouz Sorry for not being clear, we are trying to move to Amazon OpenSearch, i.e. the managed service on AWS. Up until now, we have been using self-hosted clusters, and now we are exploring the possibility to use managed service instead. That is why we need this to be implemented in OpenSearch.

**Comment by quangmaubach** [comment]
Hi team, is there any guidance/suggestion for this issue? Should I start working on some PR for this?

**Comment by CEHENKLE** [comment]
Hey @quangmaubach !  I'm sorry for the delay in responding.  Yeah!  I think this sounds really interesting  :)

To make sure I understand -- are you thinking about implementing this as a plug-in, or adding it to Core (I think the latter, but I want to confirm).  If you're thinking about it as an extension to core, then yes. it will get into our managed service when they pick up the open source version we release in.

I would say next steps are putting up a PR -- feel free to make it a WIP -- and we can start looking at the nuts and bolts of how we can implement this.  Feel free to tag me on it so that I see it.

Thanks!
/C

**Comment by quangmaubach** [comment]
Hi @CEHENKLE ,

Thank you for your reply. Actually Lucene have already had a TokenFilter that can handle the requirement of this issue. I have added a PR to enable that TokenFilter in OpenSeearch.

Can you please help me to add Label `2.0.0` and `backport 1.x` to the PR, and review it as well? I don't think I have any permission to add Label to the PR.

**Comment by quangmaubach** [comment]
Thanks @CEHENKLE for reviewing and merging my CR above!

Can you please also backport it to `1.x` branch to also release the change to `1.3` and above? It is a non-breaking change, new feature that can be added to `1.x` without much problem. More than that, we are looking to use this feature on OpenSearch `1.x` first as we might not be ready to upgrade to OpenSearch `2.0` yet.

**Comment by kartg** [comment]
1.x backport - #2217

**Comment by quangmaubach** [comment]
PR for backporting into `1.x` https://github.com/opensearch-project/OpenSearch/pull/2219

Multiple pushed to retrigger `gradle check` but not sucessful (repo-wide issue).

**Comment by anasalkouz** [comment]
Seems, this is already implemented and backported to 1.x. Closing the issue. @quangmaubach feel free to reopen if you have anything pending.
