### ISSUE TITLE
Built-in Transliteration and Phonetic support for Indian languages

### ISSUE THREAD

**Issue by quangmaubach** [opensearch-project/OpenSearch#1280]
name | about | title | labels | assignees
-- | -- | -- | -- | --
💭 Proposal | Transliteration and Phonetic support for Indian languages | [PROPOSAL] | proposal |  

## What kind of business use case are you trying to solve? What are your requirements?
While working with Indian languages content, we face challenges to surface contents which transliterated in different way than user expected. For us, we implemented a transliteration together with a sound-alike algorithm to match and rank content into our private plugins.

Looking at moving to Amazon OpenSearch, we cannot use our private plugins anymore.

We think that a standardized transliteration and phonetic support for Indian languages will be helpful on OpenSearch.

**What is the problem? What is preventing you from meeting the requirements?**
**Definitions:**
(from https://en.wikipedia.org/wiki/Transliteration) Transliteration is a type of conversion of a text from one script to another that involves swapping letters in predictable ways. An example of transliteration from Roman input into Hindi: `jayram` => `जय्रम्`, `jayaram` => `जयरम्`.

(from https://en.wikipedia.org/wiki/Phonetic_algorithm) A phonetic algorithm is an algorithm for indexing of words by their pronunciation. Among the best-known phonetic algorithms are: soundex [...]. Taking the example above: soundex code: `जय्रम्` => `जOPNZ`, `जयरम्` => `जOPNZ`.

So with a transliteration follow by soundex code conversion, `jayram` and `jayaram` have the same soundex code.

OpenSearch do not have transliteration and phonetic support for Indian languages. The closest one that I can find is `phonetic token filter` (link from Elasticsearch https://www.elastic.co/guide/en/elasticsearch/plugins/7.9/analysis-phonetic-token-filter.html) which does not have support for Indian languages.

There are a few projects that are doing similar thing, for example, transliteration library https://github.com/irshadbhat/litcm, and soundex library https://github.com/libindic/soundex.

Can we incorporate better support for Indian languages?

**What are you proposing? What do you suggest we do to solve the problem or improve the existing situation?**
Built-in transliteration and Phonetic support (soundex).

**What are your assumptions or prerequisites?**
I assume that there is demand for Indian languages from OpenSearch users and many of us will benefit from a standardized analysis plugin.

**What are remaining open questions?**
- search/index latency implication of different approaches
- "quality" of the solution, i.e. will it work?

**Comment by rmuir** [comment]
You can already do the transliteration with the ICU plugin (https://github.com/opensearch-project/OpenSearch/blob/main/plugins/analysis-icu/src/main/java/org/opensearch/index/analysis/IcuTransformTokenFilterFactory.java). 

For the "id" parameter with the `icu_transform` token filter, easiest is to just use `Any-Latin` transform.

You can play with the ICU demo online: https://icu4c-demos.unicode.org/icu-bin/translit):
For "Compound 1", put in "Any-Latin"
For "input", key in some sample text.

![Screen_Shot_2021-09-24_at_15 07 33](https://user-images.githubusercontent.com/504194/134727643-f7d60c86-79b1-40d3-8899-4d03e3441b3a.png)

**Comment by rmuir** [comment]
For any additional phonetic (e.g. soundex) algorithms, I recommend contributing stuff to Apache Commons Codec: https://commons.apache.org/proper/commons-codec/

This is where the `lucene-phonetic` module picks up its phonetic algorithms and exposes them to the analysis chain. It can then be picked up by the opensearch `analysis-phonetic` plugin.

**Comment by quangmaubach** [comment]
@rmuir Thank you very much for your pointers. The `icu_transform` looks promising, we are testing it out.

We will open an issue on Apache Commons Codec for the phonetic (soundex) part of this.

**Comment by anasalkouz** [comment]
Closing this issue, since the recommendation to do the contribution to Apache Commons Codec. Feel free to reopen the issue if needed
