### ISSUE TITLE
Improve the validation on TikaDocTests

### ISSUE THREAD

**Issue by sandeshkr419** [opensearch-project/OpenSearch#12887]
### Describe the issue

https://github.com/opensearch-project/OpenSearch/blob/main/plugins/ingest-attachment/src/test/java/org/opensearch/ingest/attachment/TikaDocTests.java#L79

This test tries to parse a bunch of different documents and asserts whether the resulting parsed content in not null/empty - that's it. 

```
            String parsedContent = TikaImpl.parse(bytes, new Metadata(), -1);
            assertNotNull(parsedContent);
            assertFalse(parsedContent.isEmpty());
            logger.debug("extracted content: {}", parsedContent);
```

Any dependency change in tika libraries or else which could possibly impact the content of parsed content will be untracked and can introduce unknown bugs.

Recommending storing of parsed content at present version for future comparison by introduction of test which verifies the same. Also, comparing it with the parsed content from an older version to ensure that the content has remain unchanged from older OpenSearch versions.

### Related component

Indexing

### Additional Details

**Plugins**
`ingest-attachment` plugin in core.

**Comment by peternied** [comment]
[Triage - attendees [1](https://github.com/peternied) [2](https://github.com/kotwanikunal) [3](https://github.com/scrawfor99) [4](https://github.com/andrross) [5](https://github.com/jed326) [6](https://github.com/dbwiddis) [7](https://github.com/srikanthpadakanti) [8](https://github.com/hasnain2808)]
@sandeshkr419 Thanks for creating this issue

**Comment by finnegancarroll** [comment]
@peternied I'de like to work on this issue.

**Comment by mch2** [comment]
thanks for picking this up @finnegancarroll.  I've assigned to you.

**Comment by finnegancarroll** [comment]
Hi @sandeshkr419! Can I pick your brain a little more regarding this issue? Is there functionality which opensearch adds to apache tika that we hope to capture with these tests? That is to say, how would you recommend I avoid redundancy with tika's own unit tests? Thanks!
