### ISSUE TITLE
[RFC] How helpful is the compatibility checker

### ISSUE THREAD

**Issue by gaiksaya** [opensearch-project/OpenSearch#12913]
### Is your feature request related to a problem? Please describe

Few months back we added a compatibility checker workflow to this repository in order to see if a change in OpenSearch could potentially break the downstream components (plugins in this case).
Associated PR: https://github.com/opensearch-project/OpenSearch/pull/8486
Associated GH issue: https://github.com/opensearch-project/opensearch-devops/issues/114

We observed that the comments about compatibility status are usually ignored. [Example](https://github.com/opensearch-project/OpenSearch/pull/12872#issuecomment-2015678527) and many more

Before approaching to next steps which was creating issues with all associated incompatible components giving a heads-up that there is an incoming change that could break your build, we wanted to get the feedback from the community members.

### Describe the solution you'd like

This was the approach taken to solve the issue: https://github.com/opensearch-project/opensearch-devops/issues/114#issuecomment-1548868449

### Related component

Build

### Describe alternatives you've considered

If the compatibility checker is not providing any value, we would like to remove it and save resources as well as reduce noise on the PR

**Comment by gaiksaya** [comment]
OpenSearch maintainers as well plugin maintainers we would like to get your input on this issue so as to take the next steps accordingly. 
Thanks!

**Comment by peternied** [comment]
@gaiksaya To me it is not useful - the security plugin recently had a breaking change from OpenSearch come in and check found it [1] it was completely ignored.  Lets save the resources to execute the jobs and the reduce the noise on pull requests.

- [1] https://github.com/opensearch-project/OpenSearch/pull/12807#issuecomment-2010933074

**Comment by peternied** [comment]
[Triage - attendees [1](https://github.com/peternied/) [2](https://github.com/lukas-vlcek/) [3](https://github.com/cwperks) [4](https://github.com/scrawfor99) [5](https://github.com/reta/)]
@gaiksaya Thanks for creating this RFC, looking forward to the result of this discussion.

**Comment by scrawfor99** [comment]
I think the checker itself is/was a good idea. But if people are just ignoring it then I agree with @peternied and we should just get rid of it.

**Comment by dblock** [comment]
In reviewing PRs such as https://github.com/opensearch-project/OpenSearch/pull/12967 I find it helpful to know the change is not breaking any plugins. Maybe there's a way to run it on demand by checking a box in the PR description (similar to how dependabot lets you rebase on demand)?

**Comment by gaiksaya** [comment]
Tagging few plugin maintainers to get more inputs:
@ylwu-amzn @navneet1v @vamshin @anirudha @owaiskazi19 @prudhvigodithi @bharath-techie

**Comment by bbarani** [comment]
I think the main question here is - Is this surfacing the breaking changes in core with decent accuracy? The first step was to add a comment and the plan was to open an automated GitHub issue on respective plugin repo impacted by a change in core for early warning.

**Comment by owaiskazi19** [comment]
If we could establish a mechanism to notify plugin teams, either through an issue or a Slack bot in their respective channels on the OpenSearch Slack, about a breaking change being introduced from the core's side, it would be beneficial. We wouldn't necessarily need to block the core's PR for the same. Instead, we could either tag the author of the breaking change PR to address the issue or revert the change.

**Comment by gaiksaya** [comment]
@bbarani @owaiskazi19 That was the next step if this goes forward. Even today, nothing is blocked using this workflow. The workflow comments the status on the pull request rather than showing it as failed and blocking the CI. The intention of this issue is to detect whether to move to next step or stop here. 
Notification would be helpful agreed, but wondering if this will be adding to the noise of other [autocuts](https://github.com/issues?q=is%3Aopen+is%3Aissue+org%3Aopensearch-project+%5BAUTOCUT%5D++) like distribution failure or integration test failures. Many of those issues in plugin repos for past releases have not been triaged. 

The intention of the compatibility checker was to be more pro-active for incoming breaking change informing both the pull request author as well as downstream components.

**Comment by peternied** [comment]
@gaiksaya I think we should remove this check. [1]  An Java API compatibility checker has been added to the pull request workflow [2], I think this is a better long term solution to the problem.

What do you think about shifting in this direction to remove this check and close out this RFC?

- [1] https://github.com/opensearch-project/OpenSearch/pull/12971
- [2] https://github.com/opensearch-project/OpenSearch/pull/12974

**Comment by gaiksaya** [comment]
Thanks @peternied ! I have approved the PR. Looks like it is not providing more value as of now. We can always add it back if required. The main difference that I am seeing with these 2 approaches is that, compatibility checker concentrated only on the components that fell under opensearch distribution See the [list](https://github.com/opensearch-project/opensearch-plugins/blob/main/plugins/.meta). However, the breaking change detector is more universal.

Once the PR is merged, I believe we can close this RFC.
