### ISSUE TITLE
[Segment Replication] consider to decouple the rateLimiter of segrep and recovery

### ISSUE THREAD

**Issue by Ferrari248** [opensearch-project/OpenSearch#12939]
### Is your feature request related to a problem? Please describe

Hi, I am interested in [Segment Replication] and use this mod a lot. I found that when indexing pressure is a little high, the replica shards using segrep usually get a larger and larger lag time, and then breach the back pressure limit to reject indexing request. That troubles me a lot. 
Finally, I found in codes that segrep and peerRecovery share the same setting `indices.recovery.max_bytes_per_sec` and its corresponding rateLimiter, default to 40mb/s. When I raise this value up, the lag bytes and lag time decreased soon. I don't know why we use the same rateLimiter? Can we use two different settings to decouple these two? Is there anything other to consider? 

### Describe the solution you'd like

add `segrep.max_bytes_per_sec` setting for segrep.

### Related component

Indexing:Replication

**Comment by vikasvb90** [comment]
cc: @Bukhtawar @gbbafna @sachinpkale

**Comment by Ferrari248** [comment]
> [Triage - attendees [1](https://github.com/peternied/) [2](https://github.com/lukas-vlcek/) [3](https://github.com/cwperks) [4](https://github.com/scrawfor99) [5](https://github.com/reta/)] @Ferrari248 Thanks for creating this issue, we'd welcome a pull request to address.

Thanks for your reply, I will try to pull request soon.
