### ISSUE TITLE
[Feature Request] Rename ingest processor supports overriding target field if exists

### ISSUE THREAD

**Issue by gaobinlong** [opensearch-project/OpenSearch#12942]
### Is your feature request related to a problem? Please describe

The rename ingest processor always throws error when the target field exists in the document, which is not friendly:
```
POST _ingest/pipeline/_simulate
{
  "pipeline": {
    "processors": [
      {
        "rename": {
          "field": "a",
          "target_field": "b"
        }
      }
    ]
  },
  "docs": [
    {
      "_source": {
        "a":1,
        "b":2
      }
    }
  ]
}
```
, response:
```
{
  "docs": [
    {
      "error": {
        "root_cause": [
          {
            "type": "illegal_argument_exception",
            "reason": "field [b] already exists"
          }
        ],
        "type": "illegal_argument_exception",
        "reason": "field [b] already exists"
      }
    }
  ]
}
```
. Just like the [Hard_rename rule](https://docs.fluentbit.io/manual/pipeline/filters/modify) in the Modify filter plugin of fluent-bit, the rename ingest processor can support something like `override_target`, which can be used to override the target field if it does exist. 

### Describe the solution you'd like

Rename ingest processor supports overriding target field if exists.

### Related component

Indexing

**Comment by peternied** [comment]
[Triage - attendees [1](https://github.com/peternied/) [2](https://github.com/lukas-vlcek/) [3](https://github.com/cwperks) [4](https://github.com/scrawfor99) [5](https://github.com/reta/)]
@gaobinlong Thanks for filing this issue, please create a pull request to add this functionality.

Note; it sounds like this scenario might be better served with a new processor named 'move'

**Comment by gaobinlong** [comment]
> [Triage - attendees [1](https://github.com/peternied/) [2](https://github.com/lukas-vlcek/) [3](https://github.com/cwperks) [4](https://github.com/scrawfor99) [5](https://github.com/reta/)] @gaobinlong Thanks for filing this issue, please create a pull request to add this functionality.
> 
> Note; it sounds like this scenario might be better served with a new processor named 'move'

Thank you, I've created a PR for this issue, and I think `move` processor could do more things than the rename processor such as move multiple fields to an object field(just like move multiple files to a directory in Linux), will dive deep into it.

**Comment by gaobinlong** [comment]
Closed by https://github.com/opensearch-project/OpenSearch/pull/12990.
