### ISSUE TITLE
[Remote Store] Reallow index & cluster default Refresh Interval to be set as -1.

### ISSUE THREAD

**Issue by astute-decipher** [opensearch-project/OpenSearch#12984]
### Is your feature request related to a problem? Please describe

After the launch of remote store, We discontinued to allow customer to set Refresh interval = -1, as it can lead to large number of uncommitted Translog files. We want to start allowing it while controlling the number of uncommitted Translog files explicilty.

### Describe the solution you'd like

We will introduce a new index setting which will limit the concurrent number of Translog files, once it's breached we will refresh the index.

### Related component

Storage:Remote

**Comment by peternied** [comment]
[Triage - attendees [1](https://github.com/lukas-vlcek) [2](https://github.com/cwperks) [3](https://github.com/jed326) [4](https://github.com/scrawfor99) [5](https://github.com/kotwanikunal) [6](https://github.com/srikanthpadakanti) [7](https://github.com/peternied) [8](https://github.com/andrross)]
@astute-decipher Thanks for filing, we'd look forward to a pull request to address this issue.
