### ISSUE TITLE
Span_field_masking not supported?

### ISSUE THREAD

**Issue by cracanut1** [opensearch-project/OpenSearch#1299]
I'm running an Opensearch index on AWS and I need to use a "span_field_masking", unfortunately it doesn't seem to be supported currently?

Example query:
`{
  "size": 50,
  "from": 0,
  "query": {
    "bool": {
      "must": [
        {
          "span_near": {
            "clauses": [
              {
                "span_term": {
                  "title": {
                    "value": "transmission"
                  }
                }
              },
              {
                "span_field_masking": {
                  "query": {
                    "query": {
                      "span_term": {
                        "title.exact": "valve"
                      }
                    }
                  },
                  "field": "title"
                }
              }
            ],
            "slop": 5,
            "in_order": false
          }
        }
      ]
    }
  }
}`

Response:
`{
  "error" : {
    "root_cause" : [
      {
        "type" : "parsing_exception",
        "reason" : "unknown query [span_field_masking]",
        "line" : 18,
        "col" : 39
      }
    ],
    "type" : "x_content_parse_exception",
    "reason" : "[18:39] [bool] failed to parse field [must]",
    "caused_by" : {
      "type" : "parsing_exception",
      "reason" : "unknown query [span_field_masking]",
      "line" : 18,
      "col" : 39,
      "caused_by" : {
        "type" : "named_object_not_found_exception",
        "reason" : "[18:39] unknown field [span_field_masking]"
      }
    }
  },
  "status" : 400
}`

Is this something which could be implemented short term or are there any workarounds?

**Comment by xuezhou25** [comment]
Looking into this

**Comment by xuezhou25** [comment]
Hi @cracanut1 
I think change the command `"span_field_masking"` to `"field_masking_span"` can solve your problem. 
Since OpenSearch is a fork from Elastic search v7.10.2 and Elasticsearch changed this name after v7.15.0 from [there](https://github.com/elastic/elasticsearch/commit/bb37e09d92e0deacd7a2c40d038bccdead3d969a), we can only support the old name.
