### ISSUE TITLE
[Feature Request] An automation tool to help identify the optimal bulk/batch size for ingestion

### ISSUE THREAD

**Issue by chishui** [opensearch-project/OpenSearch#13009]
### Is your feature request related to a problem? Please describe

In this [batch ingestion RFC](https://github.com/opensearch-project/OpenSearch/issues/12457), we proposed a batch ingestion feature which could accelerate the ingestion with neural search processors. It introduces an additional parameter "batch size" that texts from different documents could be combined and sent to ML server in one request. Since user could have different data set, different ML servers with different resources, in order to achieve better performance, they would need to experiment with different value of batch size to get the optimal performance. To offload the burden from user, we'd like to have a automation tool which could find this optimal batch size automatically.

### Describe the solution you'd like

The automation tool would run _bulk API with different batch size to see which batch size would lead to optimal performance (high throughput & low latency & no errors). The OpenSearch-benchmark tool already provides rich features on benchmark which we could utilize for this automation. We can call benchmark with different parameters, collect and evaluate and even visualize the results then provide the recommendation.

The tool can also be used to help select bulk size and client number which we can support gradually.

### Related component

Indexing:Performance

### Describe alternatives you've considered

N/A

### Additional context

RFC for batch ingestion: https://github.com/opensearch-project/OpenSearch/issues/12457

**Comment by shwetathareja** [comment]
@chishui : The proposal here is to build an automation over OSB benchmark which can find the optimal size for bulk. This doesnt require any changes in OpenSearch core. DO you think we can track this proposal in OSB repo?

**Comment by chishui** [comment]
@shwetathareja thanks for the comment. Although the proposal will not require changes in OpenSearch core, but it's a solution to address concern in this RFC #12457 which proposes batch ingestion feature in core. The tool itself doesn't need to reside in OSB codebase, it can be a standalone package just depends on OSB. So I kind of feel here might be a better place. WDYT?

**Comment by reta** [comment]
@chishui I think the intent is good but the problem space it not fully understood. As it stands now, this is **operation** issue: the optional size of the bulk highly depends on the operational state of the cluster (available heap primarily) at given moment (please check out the Elasticsearch docs on the subject [1]). 

Yes, tool will probably help to give at least some level of confidence but won't address the root of the problem.

[1] https://www.elastic.co/guide/en/elasticsearch/reference/current/tune-for-indexing-speed.html#multiple-workers-threads

**Comment by chishui** [comment]
@reta the idea is to try many combination of the variants which could impact ingestion performance such as bulk size, client number, batch size etc and based on the benchmark results, identify the combination which leads to the optimal ingestion performance. 

And the "optimal" benchmark result could happen when OS node has more CPU, memory resource, that's true, but we are not able to have the exact same environment to run every benchmark test, and if that's the concern, maybe run the tool more times to make the results statistically make sense.

**Comment by shwetathareja** [comment]
> Just feel the tool doesn't need to part of OSB and it almost doesn't require any changes from OSB at least for now.

@chishui : This could be an enhancement to OSB where it can used for optimal tuning of different configurations.

**Comment by peternied** [comment]
[Triage - attendees [1](https://github.com/lukas-vlcek) [2](https://github.com/cwperks) [3](https://github.com/jed326) [4](https://github.com/scrawfor99) [5](https://github.com/kotwanikunal) [6](https://github.com/srikanthpadakanti) [7](https://github.com/peternied) [8](https://github.com/andrross)]
@chishui Thanks for creating this issue - this is an interesting idea, however it is outside the scope of OpenSearch core.  Consider re-creating an issue in the OpenSearch Benchmark repository where this functionality might better align.
