### ISSUE TITLE
[BUG] upgrade dependency

### ISSUE THREAD

**Issue by minalsha** [opensearch-project/OpenSearch#1301]
**Describe the bug**
Update dependency jackson-databind-2.9.10.6.jar to version com.fasterxml.jackson.core:jackson-databind:2.9.10.8 unless it is only used in testing.

**Comment by minalsha** [comment]
please review this PR:https://github.com/opensearch-project/OpenSearch/pull/1247 if it resolves this issue.

**Comment by dblock** [comment]
Closed via https://github.com/opensearch-project/OpenSearch/pull/1247
