### ISSUE TITLE
[BUG] The Changelog Verifier GitHub Action runs 26 times and sends 26 emails if changelog is omitted

### ISSUE THREAD

**Issue by dbwiddis** [opensearch-project/OpenSearch#13013]
### Describe the bug

The Changelog Verifier GitHub Action triggers when a review is requested.
https://github.com/opensearch-project/OpenSearch/blob/2dc071ff2546b0c6483b9e0a382badf9ac353cdc/.github/workflows/changelog_verifier.yml#L1-L4

Because reviews are sent to every individual listed in [CODEOWNERS](https://github.com/opensearch-project/OpenSearch/blob/main/.github/CODEOWNERS), the action runs once for each maintainer.   This spams the email of the contributor who neglected to include a change log.

One email is probably sufficient.

### Related component

Build

### To Reproduce

1. Submit a PR to OpenSearch that does not include a change log entry.
2. Check your email.
3. Count 26 emails.
4. Click delete 26 times, and submit a new commit with a change log.

Or you can review the GitHub action runs for every commit and see them scrolling past the 25-run pagination break: 
https://github.com/opensearch-project/OpenSearch/actions/workflows/changelog_verifier.yml

### Expected behavior

One email to a PR submitter who neglected to add a change log.   

Even two may be tolerable.

Perhaps three if it's more important to ensure a changelog than prevent spamming contributors' inboxes.

26 is [right out](https://youtu.be/SNTzOBKs1bA?si=Xm0MNJ7w_HBmR8FS).

### Additional Details

**Additional context**

It is likely that the `review_requested` trigger can be removed.  I'm not sure how many of the other options are really required here.

**Comment by peternied** [comment]
[Triage - attendees [1](https://github.com/lukas-vlcek) [2](https://github.com/cwperks) [3](https://github.com/jed326) [4](https://github.com/scrawfor99) [5](https://github.com/kotwanikunal) [6](https://github.com/srikanthpadakanti) [7](https://github.com/peternied) [8](https://github.com/andrross)]
@dbwiddis Thanks for filing, we'd look forward to a pull request to address this

**Comment by kotwanikunal** [comment]
@dbwiddis I have reduced the duplicate event triggers here: https://github.com/opensearch-project/OpenSearch/pull/13072
