### ISSUE TITLE
Translog Optimisation: Upload .ckp file data as object metadata of .tlog file

### ISSUE THREAD

**Issue by skumawat2025** [opensearch-project/OpenSearch#13022]
### Is your feature request related to a problem? Please describe

In the current implementation of remote translog store, for every translog generation we upload translog checkpoint(.ckp) file, translog(.tlog) file and translog_metadata file to remote store.

1. translog.tlog - Contains the actual data and operations.
2. translog.ckp - Contains the checkpoint information.
3. translog metadata file - Contains metadata related to generation (readers that have not been committed) and generation to primary term mapping.

For each specified buffer interval we upload two file translog-<gen>.tlog and translog-<gen>.ckp parallely. After the successful upload of these two files. We prepare and further upload the latest metadata file. In total we try to upload 3 files to remote store per transfer for each shard. This increase the request count and rate during upload and download flows like sync translog, failover, peer recovery. This contributes to higher TPS load to remote store. 

```
<Base Path>/
    <Index UUID>/
        <ShardID>/
            metadata/
                metadata__<primaryTerm>__<generation>__<createdTimestamp>__<nodeId>__<CURRENT_VERSION>
            data/
                <primaryTerm>/
                    translog-<gen>.ckp
                    translog-<gen>.tlog
```

### Describe the solution you'd like

We can store checkpoint file information as object metadata of tlog file blob upload to remote store. Multiple repository providers like S3, Azure, and GCP provide object metadata with a size limit. Given that checkpoint file size remains under this size limit we can store ckp file with tlog file blob object metadata. With this approach we’ll reduce the number of request calls to remote store by 33%. 

* Azure - The metadata consists of name/value pairs. The total size of all metadata pairs can be up to 8KB in size. [[REF](https://learn.microsoft.com/en-us/rest/api/storageservices/setting-and-retrieving-properties-and-metadata-for-blob-resources#Subheading1)]
* S3 - Within the PUT request header, the user-defined metadata is limited to 2 KB in size. The size of user-defined. metadata is measured by taking the sum of the number of bytes in the UTF-8 encoding of each key and value. [[REF](https://docs.aws.amazon.com/AmazonS3/latest/userguide/UsingMetadata.html#UserMetadata)]
* GoogleCloud - The metadata size limit for google cloud storage is 8KB. [[REF](https://cloud.google.com/storage/quotas#objects)]

```
<Base Path>/
    <Index UUID>/
        <ShardID>/
            metadata/
                metadata__<primaryTerm>__<generation>__<createdTimestamp>__<nodeId>__<CURRENT_VERSION>
            data/
                <primaryTerm>/
                    translog-<gen>.tlog (with translog.ckp file as object metadata).
```

### Related component

Storage:Performance

**Comment by peternied** [comment]
[Triage - attendees [1](https://github.com/lukas-vlcek) [2](https://github.com/cwperks) [3](https://github.com/jed326) [4](https://github.com/scrawfor99) [5](https://github.com/kotwanikunal) [6](https://github.com/srikanthpadakanti) [7](https://github.com/peternied) [8](https://github.com/andrross)]
@skumawat2025 Thanks for filing this issue, we'd be glad to review a pull request for this change.
