### ISSUE TITLE
[BUG] Breaking changes workflow should not run on main

### ISSUE THREAD

**Issue by dblock** [opensearch-project/OpenSearch#13029]
### Describe the bug

Breaking changes are expected on `main`. Currently the job introduced in https://github.com/opensearch-project/OpenSearch/pull/12974 is failing on `push`. 

### Related component

Build

### To Reproduce

https://github.com/opensearch-project/OpenSearch/actions/runs/8525228788/job/23351663380

### Expected behavior

Main build to be green.

**Comment by peternied** [comment]
@dblock Thanks for creating this issue, rather than have this test fail on build should it do some other action?  While in main we certainly make breaking changes, often changes are make specifically to go into the next release.

**Comment by dblock** [comment]
What's the baseline for the failure, meaning will it ever be green for PRs on main?
