### ISSUE TITLE
[RFC] Move the triage meeting from Chime to Zoom

### ISSUE THREAD

**Issue by peternied** [opensearch-project/OpenSearch#13057]
### Is your feature request related to a problem? Please describe

> Meetings are hosted regularly at 10:00a - 10:55a Central Time every Wednesday and can be joined via [Chime](https://aws.amazon.com/chime/), with this [meeting link](https://chime.aws/1988437365).

_From TRIAGING.md_

Chime is a relatively small player in the online meeting space.  When the triage meeting were created the decision to use Chime was done in isolation - specifically for the 'auto-call' feature [1].

As the meeting has been running for many months, I believe its important to revisit the meeting invite technology to see that it works for everyone as the large majority of OpenSearch-Project meetings are hosted on Zoom.

### Lets collect votes on changing the format with this issue
- 👍 Move to Zoom
- 👎 Stay on Chime

**_Voting will close at the end of the 4/10 Triage meeting [2] when a decision will be reached._**

### Additional Details
- [1] https://docs.aws.amazon.com/chime/latest/ug/join-auto-call.html 
- [2] https://www.meetup.com/opensearch/events/299486491/?utm_medium=referral&utm_campaign=share-btn_savedevents_share_modal&utm_source=link

**Comment by krisfreedain** [comment]
1. Which triage meeting?
2. Are there specific issues with Chime?

**Comment by kkhatua** [comment]
If Chime is not available as a free tier, then yes, this would make sense. Zoom is widely available and supports up to 40 minutes for free. Chime, on the other hand, provides an auto-call. If either services offers a comparable alternative. 

From a foundation perspective, it shouldn't matter how the meetings are held for a project as long as there is transparency and documented. 

I think a better thing to do would have been to share the pros and cons of each before taking a vote.

**Comment by peternied** [comment]
Thanks everyone for the comments.  Both of these meeting solutions were being funded by Amazon, but long term guidance can certainly change based on foundation if/when that occurs.

## Zoom has been selected and will be the meeting tech for the 4/17 triage meeting.

I'll be updating the calendar invites to switch over to zoom
