### ISSUE TITLE
[BUG] Get status for all sanpshot or all snapshot on repository not working

### ISSUE THREAD

**Issue by disaster37** [opensearch-project/OpenSearch#13079]
### Describe the bug

The official doc explain how we can get status for all snapshot or all snapshot on repository.
The doc is here: https://opensearch.org/docs/latest/api-reference/snapshots/get-snapshot-status/

But, in fact it always return empty list.

### Related component

Plugins

### To Reproduce

I have tested on Opensearch 2.12.0 from official docker image.

1. Create snapshot repository with name `snapshot`
2. Create snapshot on repository with name `test`
3. GET _snapshot/_status return empty list
4. GET _snapshot/snapshot/_status return empty list
5. GET _snapshot/snapshot/test/_status work as expected

### Expected behavior

When `GET _snapshot/snapshot/_status` or `GET _snapshot/_status` get a list of snapshot available.

I currently get empty list:
```
{
  "snapshots": []
}
``` 

### Additional Details

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**

**Comment by peternied** [comment]
[Triage - attendees [1](https://github.com/peternied) [2](https://github.com/reta) [3](https://github.com/vikasvb90
) [4](https://github.com/andrross
) [5](https://github.com/lukas-vlcek/
) [6](https://github.com/srikanthpadakanti)]
@disaster37 Thanks for creating this issue, it might be helpful to update/modified a test case around snapshots to reproduce this scenario cleanly.

**Comment by disaster37** [comment]
1. Create fresh Opensearch cluster base on 2.14.0
2. Create new index from devtools
`
POST test/_doc
{
  "@timestamp": "2022-07-07",
  "name": "1"
}
`

3. Create local repository
`
PUT _snapshot/test
{
"type": "fs",
    "settings": {
      "location": "/mnt/snapshot"
    }
}
`

4. Create a snapshot
`
PUT _snapshot/test/snap-test
{
  "indices": "test",
  "ignore_unavailable": true,
  "include_global_state": false,
  "partial": false
}
`

The issue:
GET _snapshot/_status
It return
`
{
  "snapshots": []
}
`
I hope the look here my snapshot `snap-test`.

`GET _snapshot/test/_status`
It return
`
{
  "snapshots": []
}
`
I hope the look here my snapshot `snap-test`.

Finally
`GET _snapshot/test/snap-test/_status`

Return that I expect
`
{
  "snapshots": [
    {
      "snapshot": "snap-test",
      "repository": "test",
      "uuid": "owjuC2cWSRWTZZYu44RjZQ",
      "state": "SUCCESS",
      "include_global_state": false,
      "shards_stats": {
        "initializing": 0,
        "started": 0,
        "finalizing": 0,
        "done": 1,
        "failed": 0,
        "total": 1
      },
      "stats": {
        "incremental": {
          "file_count": 4,
          "size_in_bytes": 4295
        },
        "total": {
          "file_count": 4,
          "size_in_bytes": 4295
        },
        "start_time_in_millis": 1717598081260,
        "time_in_millis": 0
      },
      "indices": {
        "test": {
          "shards_stats": {
            "initializing": 0,
            "started": 0,
            "finalizing": 0,
            "done": 1,
            "failed": 0,
            "total": 1
          },
          "stats": {
            "incremental": {
              "file_count": 4,
              "size_in_bytes": 4295
            },
            "total": {
              "file_count": 4,
              "size_in_bytes": 4295
            },
            "start_time_in_millis": 1717598081282,
            "time_in_millis": 0
          },
          "shards": {
            "0": {
              "stage": "DONE",
              "stats": {
                "incremental": {
                  "file_count": 4,
                  "size_in_bytes": 4295
                },
                "total": {
                  "file_count": 4,
                  "size_in_bytes": 4295
                },
                "start_time_in_millis": 1717598081282,
                "time_in_millis": 0
              }
            }
          }
        }
      }
    }
  ]
}
`

**Comment by gaobinlong** [comment]
@disaster37 `GET _snapshot/_status` and `GET _snapshot/<repository>/_status` only returns the status of the running snapshots, seems the snapshot `snap-test` completes very soon, so you cannot get it by `GET _snapshot/_status` and `GET _snapshot/<repository>/_status`, you can create an long-running snapshot to verify that.

**Comment by disaster37** [comment]
Hum. OK thx for the answer.
