### ISSUE TITLE
[BUG] org.opensearch.remotestore.SegmentReplicationUsingRemoteStoreIT.testIndexReopenClose is flaky

### ISSUE THREAD

**Issue by ashking94** [opensearch-project/OpenSearch#13084]
### Describe the bug

`org.opensearch.remotestore.SegmentReplicationUsingRemoteStoreIT.testIndexReopenClose` is flaky

### Related component

Storage:Remote

### To Reproduce
```
./gradlew ':server:internalClusterTest' --tests "org.opensearch.remotestore.SegmentReplicationUsingRemoteStoreIT.testIndexReopenClose" -Dtests.seed=187117AD655AD94B -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=ca -Dtests.timezone=Asia/Shanghai -Druntime.java=21
```

Refer PR build - https://build.ci.opensearch.org/job/gradle-check/36498/testReport/junit/org.opensearch.remotestore/SegmentReplicationUsingRemoteStoreIT/testIndexReopenClose/

### Expected behavior

Test must always pass.

### Additional Details

NA

**Comment by peternied** [comment]
[Triage - attendees [1](https://github.com/peternied) [2](https://github.com/reta) [3](https://github.com/vikasvb90
) [4](https://github.com/andrross
) [5](https://github.com/lukas-vlcek/
) [6](https://github.com/srikanthpadakanti)]
@ashking94 Could you please include the gradle command to run the test and the output of the failure?

**Comment by ashking94** [comment]
Updated the description with the command to reproduce from the ci build link.

**Comment by reta** [comment]
Closing in favour https://github.com/opensearch-project/OpenSearch/issues/14329
