### ISSUE TITLE
[Remote Store] Override index settings during restore snapshot based on direction when remote store compatibility mode is MIXED

### ISSUE THREAD

**Issue by harishbhakuni** [opensearch-project/OpenSearch#13102]
### Is your feature request related to a problem? Please describe

Currently, if the node attributes have remote store enabled, we are overriding the replication strategy to SEGMENT and adding remote store related settings. As we support remote store compatibility mode as STRICT and MIXED during migration of indices from docrep to remote store backed or vice versa. during STRICT mode, current changes will work. however during MIXED mode just checking node attributes would be sufficient to override replication strategy and remote store related settings.

### Describe the solution you'd like

During mixed mode, we need to override replication strategy and remote store related settings based on direction of migration.

### Related component

Storage:Snapshots

**Comment by harishbhakuni** [comment]
META issue: https://github.com/opensearch-project/OpenSearch/issues/12718

**Comment by gbbafna** [comment]
This is taken care in https://github.com/opensearch-project/OpenSearch/issues/12852
