### ISSUE TITLE
Release version 1.2

### ISSUE THREAD

**Issue by dblock** [opensearch-project/OpenSearch#1317]
Coming from [opensearch-build#567](https://github.com/opensearch-project/opensearch-build/issues/567), release version 1.2. Please follow the following checklist.

### Preparation

- [x] Assign this issue to a release owner.
- [x] Finalize scope and feature set and update [the Public Roadmap](https://github.com/orgs/opensearch-project/projects/1).
- [x] Create, update, triage and label all features and issues targeted for this release with `v1.2.0`.

### CI/CD

- [x] Increment version on main to `1.2.0.0`.
- [x] Ensure working and passing CI.
- [x] Re(add) this repo to the [manifest](https://github.com/opensearch-project/opensearch-build/blob/main/manifests/1.2.0).

### Pre-Release

- [x] Branch and build from a `1.2` branch.
- [x] Update your branch in the [manifest](https://github.com/opensearch-project/opensearch-build/blob/main/manifests/1.2.0).
- [x] Feature complete, pencils down.
- [x] Fix bugs that target this release.

### Release

- [x] Complete [documentation](https://github.com/opensearch-project/documentation-website).
- [x] Gather, review and publish release notes.
- [x] Verify all issued labeled for this release are closed or labelled for the next release.

### Post Release

- [ ] Create [a release tag](https://github.com/opensearch-project/.github/blob/main/RELEASING.md#tagging).
- [ ] Suggest improvements to [this template](https://github.com/opensearch-project/opensearch-plugins/templates/release.md).
- [ ] Conduct a postmortem, and publish its results.

**Comment by peternied** [comment]
@opensearch-project/opensearch-core Could we update this ticket to reflect who is assigned to the 1.2 release?

**Comment by peternied** [comment]
@mch2 Are you on target for the tomorrows date, there are a number of items in CI/CD that are still open

**Comment by mch2** [comment]
Hey @peternied, we are planning on freezing and cutting the 1.2 branch tomorrow from 1.x.

Once that happens I'll PR the manifest file update to opensearch-build & bump the version on 1.x to 1.3.

**Comment by peternied** [comment]
@mch2 Until Friday the 12th at noon PST, any tests that use distribution downloader were running against old bits and need to be rerun.  Can you please see if your team was impacted, rerun the tests, and then mark the tests run as completed in https://github.com/opensearch-project/opensearch-build/issues/954?

**Comment by peternied** [comment]
@dblock removed the `enhancement` label as it doesn't seem to fit this issue to complete the release.  Let me know if you have other thoughts.

**Comment by mch2** [comment]
I don't have permission to update this issue to click those boxes.  Everything under the Release section has been completed.

**Comment by mch2** [comment]
Created suggestion - https://github.com/opensearch-project/opensearch-build/issues/1140.

**Comment by kartg** [comment]
Post mortem will be performed once folks are back from Thanksgiving break.
Release tag - https://github.com/opensearch-project/OpenSearch/releases/tag/1.2.0
