### ISSUE TITLE
Upload code coverage report through CI

### ISSUE THREAD

**Issue by tlfeng** [opensearch-project/OpenSearch#1320]
**Is your feature request related to a problem? Please describe.**
A part of issue: #850
There hasn't got a place to see the code coverage of this repository.

**Describe the solution you'd like**
To achieve the goal of reporting test coverage, I plan to upload the code coverage report to [Codecov](https://about.codecov.io/) through CI.
We have set a [plan](https://github.com/opensearch-project/opensearch-plugins/blob/511f8d2f104787515fb7a73337a2fb7acebc7531/TESTING.md#code-coverage-reporting) for OpenSearch/Dashboards plugins to report the code coverage, and I'm going to expand it to the 
"OpenSearch".

The report can be uploaded to Codecov daily or during the "gradle check" process of Pull Requests.

The command to generate the code coverage report: [the guide in TESTING.md](https://github.com/opensearch-project/OpenSearch/blob/8ea3364bc51ee3760b71546cecb7912c30330967/TESTING.md#test-coverage-analysis)
Steps to upload the report to Codecov:
- If using "Github Actions" to create CI workflow, please refer to [the guide in opensearch-plugins repo](https://github.com/opensearch-project/opensearch-plugins/blob/511f8d2f104787515fb7a73337a2fb7acebc7531/TESTING.md#code-coverage-report-upload-through-ci-workflow).
- In general, uses "Codecov Uploader", see [docs](https://docs.codecov.com/docs/codecov-uploader) and [blog](https://about.codecov.io/blog/introducing-codecovs-new-uploader/) from Codecov.

The codecov dashboard to see all the code coverage information for opensearch-project: https://app.codecov.io/gh/opensearch-project

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by sampathbalivada** [comment]
I set up a GitHub Action workflow to test things out at my end and seems like I have an issue running the tests. This is the error code. 

./gradlew check -Dtests.coverage=true


```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':server:test'.
```

**Comment by sampathbalivada** [comment]
I set up a GitHub Action workflow to test things out at my end and seems like I have an issue running the tests. These are the tasks that I was able to run at my end. (All these are running on a replica of the `main` branch)

```bash
./gradlew check -Dtests.coverage=true
```
```bash
# the workflow run for the below task has been successful 
# because of 'true' but the build failed
./gradlew codeCoverageReport --parallel || true
```
```
./gradlew codeCoverageReportForUnitTest --parallel
```

All these tasks failed with the following exception.

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':server:test'.
```

Runs for reference:
https://github.com/sampathbalivada/OpenSearch/runs/4852410823?check_suite_focus=true
https://github.com/sampathbalivada/OpenSearch/runs/4853613540?check_suite_focus=true
https://github.com/sampathbalivada/OpenSearch/runs/4856683788?check_suite_focus=true

I am able to perform `assemble` and `precommit` tasks but not being able to generate coverage reports. My guess is that I am missing a dependency here.

The [workflow](https://github.com/sampathbalivada/OpenSearch/blob/ba09f7c49a6fd96ffac97ccfd6b7e3179956a599/.github/workflows/codecov.yml) installs JDK11 and runs the above command(s). I have some questions here.
* Are additional JDKs (8,11,14) required to run these tests?
* Is there a dependency that I am currently missing?

**Comment by dblock** [comment]
@sampathbalivada Check out #1665, that should answer many questions. Beyond setup, `./gradlew check` requires hardware that GHA can't quite handle and we've been trying several workarounds short of running our own setup (we currently do with Jenkins and a bunch of instances supplied by AWS).

**Comment by sampathbalivada** [comment]
Thank you for the information @dblock. Seems like this issue has a dependency on #39. 

Also, since we are already doing `./gradlew check`, wouldn't it be easier to add `-Dtests.coverage=true` and generate the coverage report there?

**Comment by dreamer-89** [comment]
Code coverage report upload was handled as part of [public jenkins migration work](https://github.com/opensearch-project/opensearch-build/issues/2193). Since, the work is already completed, closing this issue.
