### ISSUE TITLE
[transport] Ensure support of the transport-nio by security plugin (HTTP)

### ISSUE THREAD

**Issue by reta** [opensearch-project/OpenSearch#13245]
### Is your feature request related to a problem? Please describe

The OpenSearch `security` plugin used to tightly integrates with the transport and supported TLS/SSL for `transport-netty4` only. Since we've integrated https://github.com/opensearch-project/OpenSearch/issues/12903, it is not an issue anymore and each transport could provide secure variants.

### Describe the solution you'd like

 Ensure support of secure HTTP transports by `transport-nio` plugin

### Related component

Plugins

### Describe alternatives you've considered

N/A

### Additional context

See https://github.com/opensearch-project/OpenSearch/issues/12903

**Comment by peternied** [comment]
[Triage - attendees [1](https://github.com/vikasvb90/) [2](https://github.com/reta/) [3](https://github.com/scrawfor99) [4](https://github.com/jed326) [5](https://github.com/kotwanikunal) [6](https://github.com/peternied) [7](https://github.com/lukas-vlcek/)]
@reta Thanks for filing this issue
