### ISSUE TITLE
[BUG] DerivedFieldFetchAndHighlightTests has flaky tests

### ISSUE THREAD

**Issue by mch2** [opensearch-project/OpenSearch#13249]
### Describe the bug

From https://github.com/opensearch-project/OpenSearch/pull/13248#issuecomment-2060017484

testDerivedFieldFromIndexMapping and testDerivedFieldFromSearchMapping are flaky.

These look recently introduced with https://github.com/opensearch-project/OpenSearch/issues/12850 @rishabhmaurya and/or @msfroh Can you please take a look?

### Related component

Search

### To Reproduce

N/A

### Expected behavior

Tests should pass

### Additional Details

N/A

**Comment by peternied** [comment]
[Triage - attendees [1](https://github.com/vikasvb90/) [2](https://github.com/reta/) [3](https://github.com/scrawfor99) [4](https://github.com/jed326) [5](https://github.com/kotwanikunal) [6](https://github.com/peternied) [7](https://github.com/lukas-vlcek/)]
@mch2 Thanks for filing this issue

**Comment by rishabhmaurya** [comment]
@mch2 thanks for reporting. I will take it forward.

**Comment by froh** [comment]
@msfroh, not @froh ...

**Comment by rishabhmaurya** [comment]
@mch2 please review https://github.com/opensearch-project/OpenSearch/issues/13249 thanks

**Comment by mch2** [comment]
> @msfroh, not @froh ...

Oops sorry about that!
