### ISSUE TITLE
[Remote Store] Prevent version upgrade during MIXED compatibility mode

### ISSUE THREAD

**Issue by ltaragi** [opensearch-project/OpenSearch#13250]
### Is your feature request related to a problem? Please describe

* During migration, primary shards always move first, while during version changes, replica shards move first. 
* Thus, in `MIXED` compatibility mode, as new nodes join the cluster, nodes with a different version should not be allowed to join.

### Describe the solution you'd like

* A check for this can be added in `JoinTaskExecutor.java`, where the compatibility of the joining node with the cluster is verified inside `ensureRemoteStoreNodesCompatibility`.

### Related component

Storage:Remote

**Comment by peternied** [comment]
[Triage - attendees [1](https://github.com/vikasvb90/) [2](https://github.com/reta/) [3](https://github.com/scrawfor99) [4](https://github.com/jed326) [5](https://github.com/kotwanikunal) [6](https://github.com/peternied) [7](https://github.com/lukas-vlcek/)]
@ltaragi Thanks for filing this issue, and creating the draft PR to address
