### ISSUE TITLE
[BUG] The aggs result of NestedAggregator with sub NestedAggregator may be not accurately

### ISSUE THREAD

**Issue by kkewwei** [opensearch-project/OpenSearch#13303]
### Describe the bug

the result of NestedAggregator with sub NestedAggregator is not accurately here, the two values of doc_count should be 4.
<img width="430" alt="image" src="https://github.com/opensearch-project/OpenSearch/assets/16730433/f072cb19-5abf-4ce0-a25a-0f060f32ce0b">

### Related component

Search:Aggregations

### To Reproduce

1. create the index.
```
PUT index1_nest111
{
    "settings": {
    "index.refresh_interval":"30s"
    }, 
   "mappings": {
      "properties": {
         "nested1": {
            "type": "nested",
            "properties": {
               "name": {
                  "type": "keyword"
               }
            }
         },
         "nested2": {
            "type": "nested",
            "properties": {
               "age": {
                  "type": "long"
               }
            }
         }
      }
   }
}
```

2. put the data.
the 4 documents are same, except for the _id:
```
POST _bulk?refresh=true
{ "index": { "_index": "index1_nest111", "_id": "1" } }
{ "nested2": {"age":1}, "nested1": {"name": "name1"} }
{ "index": { "_index": "index1_nest111", "_id": "2" } }
{ "nested2": {"age":1}, "nested1": {"name": "name1"} }


POST _bulk?refresh=true
{ "index": { "_index": "index1_nest111", "_id": "3" } }
{ "nested2": {"age":1}, "nested1": {"name": "name1"} }
{ "index": { "_index": "index1_nest111", "_id": "4" } }
{ "nested2": {"age":1}, "nested1": {"name": "name1"} }
```

3. aggregation
```
POST index1_nest111/_search
{
  "aggregations": {
    "out_nested": {
      "aggregations": {
        "out_terms": {
          "aggregations": {
            "inner_nested": {
              "aggregations": {
                "inner_terms": {
                  "terms": {
                    "field": "nested1.name"
                  }
                }
              },
              "nested": {
                "path": "nested1"
              }
            }
          },
          "terms": {
            "field": "nested2.age"
          }
        }
      },
      "nested": {
        "path": "nested2"
      }
    }
  },
  "size": 0
}
```

### Expected behavior

The inner_nested.doc_count shouble alse be 4.

If it's a bug, I'm please to fix.

### Additional Details

**Host/Environment (please complete the following information):**
 - OS: os2.9

**Comment by kkewwei** [comment]
Nest2 child  is outer nested aggregation, nest1 child is inner nested aggregation.

To help explain the describe above:
<img width="535" alt="image" src="https://github.com/opensearch-project/OpenSearch/assets/16730433/7401b8a9-2648-4656-bc53-b730107fab24">

 when execute the  inner nested aggregation, the parentDoc=0(the first lucene document id) will be discarded
https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/search/aggregations/bucket/nested/NestedAggregator.java#L113

**Comment by peternied** [comment]
[Triage - attendees [1](https://github.com/peternied) [2](https://github.com/kotwanikunal) [3](https://github.com/scrawfor99) [4](https://github.com/andrross) [5](https://github.com/jed326) [6](https://github.com/dbwiddis) [7](https://github.com/srikanthpadakanti) [8](https://github.com/hasnain2808)]
@kkewwei Thanks for creating this issue, thanks for the pull request to address!
