### ISSUE TITLE
[BUG] org.opensearch.snapshots.DeleteSnapshotIT.testDeleteShallowCopySnapshot is flaky

### ISSUE THREAD

**Issue by jainankitk** [opensearch-project/OpenSearch#13312]
### Describe the bug

The test fails intermittently. Build where it failed: https://build.ci.opensearch.org/job/gradle-check/37349/testReport/

### Related component

Storage:Snapshots

### Expected behavior

The test should not fail unless there is issue

**Comment by jainankitk** [comment]
Related to #9115

**Comment by peternied** [comment]
[Triage - attendees [1](https://github.com/peternied) [2](https://github.com/kotwanikunal) [3](https://github.com/vikasvb90) [4](https://github.com/mch2) [5](https://github.com/jed326) [6](https://github.com/dbwiddis) [7](https://github.com/scrawfor99)]
@jainankitk Reopening the previous issue as the call stack looks the same as was previously reported.
