### ISSUE TITLE
[BUG] Search Pipeline API Errors in OpenSearch 2.7.0 and 2.8.0

### ISSUE THREAD

**Issue by saimedhi** [opensearch-project/OpenSearch#13339]
### Describe the bug

Search Pipeline APIs were recently added to opensearch-py. While running the REST API Spec tests [here](https://github.com/opensearch-project/OpenSearch/blob/main/rest-api-spec/src/main/resources/rest-api-spec/test/search_pipeline/10_basic.yml), I'm encountering failures in OpenSearch 2.7.0 and 2.8.0

Failures: [1](https://github.com/opensearch-project/opensearch-py/actions/runs/8757559757/job/24036460635?pr=726), [2](https://github.com/opensearch-project/opensearch-py/actions/runs/8757559757/job/24036460997?pr=726)

Even after connecting to the server directly, I still received the same error for OpenSearch 2.7.0 and 2.8.0 The API works fine for other OpenSearch versions.

```
PUT https://localhost:9200/_search/pipeline/my_pipeline

body = {
            "description": "_descrninpnvtion",
            "request_processors": [
            ]
          }

{
    "error": "no handler found for uri [/_search/pipeline/my_pipeline] and method [PUT]"
}
```

- If this is expected behavior, the [rest-api-spec test](https://github.com/opensearch-project/OpenSearch/blob/main/rest-api-spec/src/main/resources/rest-api-spec/test/search_pipeline/10_basic.yml) should skip these versions.

### Related component

Search

### To Reproduce

Go to 'https://github.com/opensearch-project/opensearch-py/actions/runs/8757559757/job/24036460997?pr=726'

### Expected behavior

- Fix the errors or skip the tests for this versions [here](https://github.com/opensearch-project/OpenSearch/blob/main/rest-api-spec/src/main/resources/rest-api-spec/test/search_pipeline/10_basic.yml).

**Comment by msfroh** [comment]
Search pipelines went GA in OpenSearch 2.9.0, didn't they?

They were announced for 2.9: https://opensearch.org/blog/introducing-opensearch-2.9.0/

Prior to that, they were gated behind a feature flag -- the integ tests were enabling the feature flag. I guess we can update the integ tests to pretend that search pipelines didn't exist at all prior to 2.9.
