### ISSUE TITLE
[BUG] Field Name Incorrectly Popped from Path in flat_object During Array Processing

### ISSUE THREAD

**Issue by naomichi-y** [opensearch-project/OpenSearch#13351]
### Describe the bug

In the `flat_object` function, which is responsible for converting nested JSON data into a flattened format, there is an issue related to handling JSON arrays containing multiple objects.
Specifically, the function incorrectly removes the array field name from the path after processing the first object within the array. As a result, when processing subsequent objects in the same array, the flattened key-path lacks the correct array field name, leading to inaccurate representation of the data structure. 

### Related component

Indexing

### To Reproduce

Here is the test code to reproduce the issue.
https://github.com/opensearch-project/OpenSearch/pull/13259#issuecomment-2070714539

### Expected behavior

The expected behavior of the test code is to correctly flatten the nested JSON structure into a simple, flat format without losing any structural context due to array processing.

### Additional Details

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**

This issue can be reproduced in OpenSearch 2.12.

**Comment by peternied** [comment]
[Triage - attendees [1](https://github.com/peternied) [2](https://github.com/kotwanikunal) [3](https://github.com/vikasvb90) [4](https://github.com/mch2) [5](https://github.com/jed326) [6](https://github.com/dbwiddis)]
@naomichi-y Thanks for creating this issue, please consider submitting a pull request to address this issue.
