### ISSUE TITLE
[BUG] The comments did not match the codes in MultiTermsAggregationBuilder

### ISSUE THREAD

**Issue by Zhikai-VM** [opensearch-project/OpenSearch#13375]
### Describe the bug

In MultiTermsAggregationBuilder.java, the comments about multiple terms aggregation did not match codes: 
```
 GET test_000001/_search
 {
      "size": 0,
      "aggs": {
        "hot": {
          "multi_terms": {
            "terms": [{
              "field": "region"
            },{
              "field": "host"
            }],
            "order": {"max-cpu": "desc"} <====
          },
          "aggs": {
            "max-cpu": { "max": { "field": "cpu" } }
          }
        }
      }
 }
```
The comment shows we can set up one order. But from the codes, it also supports an array like:
`"order": [ {"max-cpu": "desc"} , {"max-memory": "desc"}  ]`

Here are the codes to parser this field:

`PARSER.declareObjectArray(MultiTermsAggregationBuilder::order, (p, c) -> InternalOrder.Parser.parseOrderParam(p), ORDER_FIELD);`

I also go through the codes and had some local tests. I think multiple orders do work. If so, could you please update the comment and the official document about this?

### Related component

Search:Aggregations

### To Reproduce

Compare the comments and codes.

### Expected behavior

If multiple orders are supported, we should update the comments and the official document.

**Comment by dblock** [comment]
Thanks @Zhikai-VM, looks like a real issue. Do you think you could help with the updates? Make PRs?

**Comment by dblock** [comment]
I am not very familiar with this functionality, but I think we can work through this!

1. Find an existing [YAML REST test](https://github.com/opensearch-project/OpenSearch/blob/main/TESTING.md#testing-the-rest-layer) that has 1 order. 
2. See if there's a test with 2 orders, if not add one with expected change in results.
3. Now that (1) and (2) are confirmed with tests we can be sure, and can document/update with cofidence.

**Comment by Zhikai-VM** [comment]
> I am not very familiar with this functionality, but I think we can work through this!
> 
> 1. Find an existing [YAML REST test](https://github.com/opensearch-project/OpenSearch/blob/main/TESTING.md#testing-the-rest-layer) that has 1 order.
> 2. See if there's a test with 2 orders, if not add one with expected change in results.
> 3. Now that (1) and (2) are confirmed with tests we can be sure, and can document/update with cofidence.

Hi @dblock ,
I created a PR to add unit test to verify the multiple orders in multiple terms aggregation, could you please help to review it:
https://github.com/opensearch-project/OpenSearch/pull/13400 ?
