### ISSUE TITLE
[BUG] :server:japicmp failing

### ISSUE THREAD

**Issue by dblock** [opensearch-project/OpenSearch#13385]
### Describe the bug

Coming from https://github.com/opensearch-project/OpenSearch/pull/13358, `./gradlew :server:japicmp` is failing. It complains that at least the following is breaking.

```
Comparing source compatibility of  against 
***! MODIFIED CLASS: PUBLIC org.opensearch.common.cache.Cache  (not serializable)
	===  CLASS FILE FORMAT VERSION: 55.0 <- 55.0
	GENERIC TEMPLATES: === K:java.lang.Object, === V:java.lang.Object
	---! REMOVED METHOD: PUBLIC(-) java.util.function.ToLongBiFunction<K,V> getWeigher()
```

I can reproduce locally with a different set of errors, but mine runs against 2.13 (as it should?).

### Related component

Build

### To Reproduce

See https://github.com/opensearch-project/OpenSearch/pull/13358 or check out 2.x and run `./gradlew :server:japicmp`.

### Expected behavior

There's no breaking change in that PR, the check should not fail.

### Additional Details

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**

**Comment by reta** [comment]
@dblock I will take a look shortly

**Comment by reta** [comment]
@dblock should be all good now (needed rebase since someone merged the pull request with failing breaking chanhes check I suspect, affecting all other pull requests)

**Comment by dblock** [comment]
@reta I did rebase yesterday and force pushed, but I suppose the fix was not in yet? Let's see if it works now.

**Comment by reta** [comment]
> @reta I did rebase yesterday and force pushed, but I suppose the fix was not in yet? Let's see if it works now.

I believe so, I will keep this issue open to find out the culprit, but backport should be unblocked, thanks @dblock

**Comment by dblock** [comment]
Thanks and sorry for bothering you, should have retried.
