### ISSUE TITLE
[BUG] opensearch-ci-bot continues to execute CI Tests repeatedly even after the PR is marked closed

### ISSUE THREAD

**Issue by getsaurabh02** [opensearch-project/OpenSearch#1340]
**Describe the bug**
CI Tests continue to run repeatedly by opensearch-ci-bot, without manual intervention, even after the PR has been marked closed. 

PR in consideration : https://github.com/opensearch-project/OpenSearch/pull/1310
PR Closed : https://github.com/opensearch-project/OpenSearch/pull/1310#issuecomment-937172632
More than 20 CI tests runs post closure and still going on : https://github.com/opensearch-project/OpenSearch/pull/1310#issuecomment-937937385

**Comment by tlfeng** [comment]
I guess the PR #1338 got the same symptom. 🤔

**Comment by peternied** [comment]
@getsaurabh02 Looking into this
