### ISSUE TITLE
[BUG] AzureBlobContainerRetriesTests.testReadBlobWithRetries is flaky

### ISSUE THREAD

**Issue by kiranprakash154** [opensearch-project/OpenSearch#13433]
### Describe the bug

AzureBlobContainerRetriesTests.testReadBlobWithRetries is flaky
Failing on PR - https://github.com/opensearch-project/OpenSearch/pull/13413

### Related component
Storage

**Additional context**

**Comment by peternied** [comment]
[Triage - attendees [1](https://github.com/peternied) [2](https://github.com/kotwanikunal) [3](https://github.com/scrawfor99) [4](https://github.com/andrross) [5](https://github.com/jed326) [6](https://github.com/dbwiddis) [7](https://github.com/srikanthpadakanti) [8](https://github.com/hasnain2808)]
@kiranprakash154 Thanks for creating this issue


Looks like it might be related to #6090

**Comment by reta** [comment]
Closing in favour https://github.com/opensearch-project/OpenSearch/issues/14318
