### ISSUE TITLE
[Feature Request] Create setting to disable CompoundFile usage

### ISSUE THREAD

**Issue by samuel-oci** [opensearch-project/OpenSearch#13448]
### Is your feature request related to a problem? Please describe

At the moment this is impossible to choose whether we want our indices to use a compound file and the InternalEngine automatically set that to "true", see [here](https://github.com/samuel-oci/OpenSearch/blob/main/server/src/main/java/org/opensearch/index/engine/InternalEngine.java#L2344) for reference.

Avoiding the compound file can sometime be important for debugging purposes when a customer is trying to look at the Lucene files structure to determine for any issues, or alternatively in cases where we want to change codec and expose the OpenSearch Lucene index files in a snapshot to be read by a different system.
For example we might want to convert our doc values or StoredDocs to Parquet and read those from snapshot later by leveraging Apache Spark.

### Describe the solution you'd like

Allow to set the "useCompoundFile" format via a setting.

### Related component

Indexing

### Describe alternatives you've considered

NA

**Comment by peternied** [comment]
[Triage - attendees [1](https://github.com/peternied) [2](https://github.com/kotwanikunal) [3](https://github.com/scrawfor99) [4](https://github.com/andrross) [5](https://github.com/jed326) [6](https://github.com/dbwiddis) [7](https://github.com/srikanthpadakanti) [8](https://github.com/hasnain2808)]
@samuel-oci Thanks for creating this issue, thanks for creating a pull request!
