### ISSUE TITLE
[BUG] Deleting Index does not fully work

### ISSUE THREAD

**Issue by seriouz** [opensearch-project/OpenSearch#1347]
**Describe the bug**
When i delete an index via the api and create a new index, the mappings and settings from the removed one are restored.
This is bad because the old index has 3300 fields and the new one would have 150 fields.
Even when i create the index with the following body the fields from the deleted index are somehow restored.

`{
   "mappings":{
       "dynamic_templates": [],
       "properties": {}
   },
   "settings":{
   }
}`

I assume the index does not getting fully deleted.

**Host/Environment (please complete the following information):**
 - OS: Docker
 - Version opensearchproject/opensearch:1.1.0

**Comment by dcyprianrw** [comment]
@seriouz We are seeing the same issue today.  Are you able to share the solution?
