### ISSUE TITLE
[BUG] Flaky test - RemoteReplicaRecoveryIT.testReplicaRecovery() 

### ISSUE THREAD

**Issue by peteralfonsi** [opensearch-project/OpenSearch#13473]
### Describe the bug

RemoteReplicaRecoveryIT.testReplicaRecovery() sometimes fails with 1 less hit than expected. [Example](https://build.ci.opensearch.org/job/gradle-check/38082/testReport/junit/org.opensearch.remotemigration/RemoteReplicaRecoveryIT/testReplicaRecovery/) here. 

### Related component

Search

### To Reproduce

REPRODUCE WITH: ./gradlew ':server:internalClusterTest' --tests "org.opensearch.remotemigration.RemoteReplicaRecoveryIT.testReplicaRecovery" -Dtests.seed=47558462C4ABB134 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=mk -Dtests.timezone=Etc/GMT-3 -Druntime.java=21

### Expected behavior

The test should always pass.

**Comment by peternied** [comment]
[Triage - attendees [1](https://github.com/peternied) [2](https://github.com/kotwanikunal) [3](https://github.com/scrawfor99) [4](https://github.com/andrross) [5](https://github.com/jed326) [6](https://github.com/dbwiddis) [7](https://github.com/srikanthpadakanti) [8](https://github.com/hasnain2808)]
@peteralfonsi Thanks for creating this issue.

**Comment by reta** [comment]
Closing in favour of https://github.com/opensearch-project/OpenSearch/issues/14303
