### ISSUE TITLE
[Feature Request] Make UBI query_id optional

### ISSUE THREAD

**Issue by jzonthemtn** [opensearch-project/OpenSearch#13580]
### Is your feature request related to a problem? Please describe

In some cases, it may not be desirable for a client to generate a UBI on the client-side. In these cases, the `query_id` should be optional.

### Describe the solution you'd like

If a `query_id` is not provided, UBI should generate a random `query_id` (likely a UUID) and return it in the `ubi` block of `ext` in the search response.

### Additional context

This relates to UBI which is described in #12084 and #13545.

This issue can be assigned to myself.

**Comment by andrross** [comment]
[Triage - attendees [1](https://github.com/jed326) [2](https://github.com/dbwiddis) [3](https://github.com/reta/) [4](https://github.com/vikasvb90/)]
@jzonthemtn Thanks for filing.

**Comment by jzonthemtn** [comment]
Closing this RFC because the initial implementation is now available at https://github.com/opensearch-project/user-behavior-insights and new issues can be created there.
