### ISSUE TITLE
[Feature Request] Create the UBI indexes in a friendlier manner

### ISSUE THREAD

**Issue by jzonthemtn** [opensearch-project/OpenSearch#13581]
### Is your feature request related to a problem? Please describe

In #13545, the UBI indexes are only created when a search request containing a `ubi` section in `ext` is received. The `ubi_events` and `ubi_queries` indexes are then created. This requires the user to make a query to create the indexes which is not ideal, and also requires checking to see if those indexes exist for each UBI-enabeld search request.

### Describe the solution you'd like

There should be another mechanism for creating the `ubi_queries` and `ubi_events` indexes, such as a new REST endpoint to initialize UBI which creates the indexes. 

### Additional context

Related to the UBI RFC #12084 and UBI initial code in #13545.

This issue can be assigned to myself.

**Comment by andrross** [comment]
[Triage - attendees [1](https://github.com/jed326) [2](https://github.com/dbwiddis) [3](https://github.com/reta/) [4](https://github.com/vikasvb90/)]
@jzonthemtn Thanks for filing.

**Comment by jzonthemtn** [comment]
Closing this RFC because the initial implementation is now available at https://github.com/opensearch-project/user-behavior-insights and new issues can be created there.
