### ISSUE TITLE
 too_many_buckets_exception in opensearch

### ISSUE THREAD

**Issue by ganilmca** [opensearch-project/OpenSearch#13614]
### Is your feature request related to a problem? Please describe

Hi Team,

We have deployed the one prod cluster with opensearch-2.12.0 version.
When we create visualization to download csv file we were getting the below error.

**too_many_buckets_exception Trying to create too many buckets. Must be less than or equal to: [120000] but was [120001]. This limit can be set by changing the [search.max_buckets]**

But we have already increased the value 80k to 120k even we were getting this error.

Can anyone please help us to resolve this error and also what is the maximum set value for this.

Thanks & Regards,
Anil 

### Describe the solution you'd like

we want permanent solution for this one. 

### Related component

Search

### Additional context

![image](https://github.com/opensearch-project/OpenSearch/assets/84953972/7f33ae67-a02e-4d0d-993d-b922b2d2dcf2)

**Comment by andrross** [comment]
Thanks @ganilmca. In general, for support like this I'd suggest either the [forum](https://forum.opensearch.org/) or the [slack](https://opensearch.org/slack.html). I think the exception is pretty clear...you're exceeding the maximum number of search buckets. The limit exists to prevent a single search request from consuming too many resources. The maximum value allowed is technically the Java Integer.MAX_VALUE (2^31-1), though I don't think that many aggregation buckets is useful in practice. Please reopen an issue here if you think there is a bug, but for general support I recommend the forum or slack. Thanks!
