### ISSUE TITLE
[Feature Request] [Telemetry] Make available the instance of tracer and metrics registry to all the plugins

### ISSUE THREAD

**Issue by Gaganjuneja** [opensearch-project/OpenSearch#13635]
### Is your feature request related to a problem? Please describe

We want to extend the support of telemetry in the plugins so that plugin code can also be instrumented. We are working on an [issue](https://github.com/opensearch-project/performance-analyzer/issues/585)  to migrate the metrics from Performance analyzer to the telemetry framework. In order to achieve that we need to inject the telemetry objects to the plugins.

### Describe the solution you'd like

We should add a method in the plugin interface which helps in injecting the telemetry instances to all the plugins and plugin can overrirde that method and use. Instead of injecting the multiple instances we should have a one single Telemetry object which should be able to give access to specific objects like tracer and metricsRegistry.

### Related component

Other

**Comment by peternied** [comment]
[Triage - attendees [1](https://github.com/peternied) [2](https://github.com/vikasvb90/) [3](https://github.com/scrawfor99) [4](https://github.com/andrross) [5](https://github.com/reta/) [6](https://github.com/dbwiddis) [7](https://github.com/cwperks) [8](https://github.com/lukas-vlcek/)]
@Gaganjuneja Thanks for creating this issue and pull request for this functionality
