### ISSUE TITLE
New circuit breaker on context.template.max_compilations_rate trips for ingest pipelines

### ISSUE THREAD

**Issue by slylock** [opensearch-project/OpenSearch#13650]
### Describe the bug

This circuit breaker did not exist in version 2.7.  When I upgraded to 2.11, the circuit breaker started tripping for ingest pipelines that use Mustache.  Unfortunately I'm unable to increase the 75/5m limit because I'm using AWS-hosted OpenSearch.  Should this setting apply to ingest pipelines?  If so, the limit effectively makes it impossible to use Mustache in an ingest pipeline.

### Related component

Indexing

### To Reproduce

Any use of Mustache in an ingest pipeline, with a indexing job of more than 75 docs, will trip the breaker.  For example:
{
  "processors": [
    {"set": {"field": "_source.surl"          , "value": "{{_source.murl}}"}},
    {"set": {"field": "_source.llevel"           , "value": "{{_source.schoollevel}}"}}

### Expected behavior

Perhaps ingest pipeline context needs a separate setting with a much higher default limit.

### Additional Details

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**

**Comment by peternied** [comment]
[Triage - attendees [1](https://github.com/peternied) [2](https://github.com/vikasvb90/) [3](https://github.com/scrawfor99) [4](https://github.com/andrross) [5](https://github.com/reta/) [6](https://github.com/dbwiddis) [7](https://github.com/cwperks) [8](https://github.com/lukas-vlcek/)]
@slylock Thanks for creating this issue

**Comment by peternied** [comment]
@slylock You might also want to submit a support request with the AWS service as the problem could be on their end

**Comment by slylock** [comment]
I don't think this is a real bug.  After I deleted and re-PUT the offending pipeline, I'm not getting the error anymore.  So it seems like an anomaly of the AWS upgrade process only.

**Comment by dhwanilpatel** [comment]
[Indexing Triage 09/16]

Thanks for the confirmation @slylock that this is not bug. Closing the issue.
