### ISSUE TITLE
[Remote Cluster State] Download cluster state on follower nodes

### ISSUE THREAD

**Issue by soosinha** [opensearch-project/OpenSearch#13682]
### Is your feature request related to a problem? Please describe

Parent project: Cluster State Publication using Remote State
Meta issue: 

### Describe the solution you'd like

The follower nodes should download the cluster state from remote store using the term and version sent by the cluster manager node.

### Related component

Cluster Manager

**Comment by peternied** [comment]
[Triage - attendees [1](https://github.com/peternied) [2](https://github.com/vikasvb90/) [3](https://github.com/scrawfor99) [4](https://github.com/andrross) [5](https://github.com/reta/) [6](https://github.com/dbwiddis) [7](https://github.com/cwperks) [8](https://github.com/lukas-vlcek/)]
@soosinha Thanks for creating this issue, looking forward to a pull request

**Comment by soosinha** [comment]
Tracking in this issue: https://github.com/opensearch-project/OpenSearch/issues/13729
