### ISSUE TITLE
[Remote Cluster State] Add toXContent and fromXContent for DiscoveryNodes

### ISSUE THREAD

**Issue by shiv0408** [opensearch-project/OpenSearch#13691]
### Is your feature request related to a problem? Please describe

Parent project: Cluster State Publication using Remote State
Meta issue: #13683

### Describe the solution you'd like

To upload and recreate the cluster state after downloading the state from remote, we need to have proper serialization and de-serialization methods for the DiscoveryNodes object. So, need to update the current toXContent methods for DiscoveryNodes and DiscoveryNode classes to include all necessary attribute which are needed to recreate the object when we need to recreate the object from remote.

### Related component

Cluster Manager

**Comment by soosinha** [comment]
This is not required as we will be using Writable ser/de
