### ISSUE TITLE
[Remote Cluster State] Upload ephemeral cluster state objects(cluster blocks, nodes, customs) to remote

### ISSUE THREAD

**Issue by soosinha** [opensearch-project/OpenSearch#13728]
### Is your feature request related to a problem? Please describe

Meta issue: https://github.com/opensearch-project/OpenSearch/issues/13683
Ephemeral objects like cluster blocks , discovery nodes and ClusterState.custom objects are not uploaded to remote store currently.

### Describe the solution you'd like

Upload the ephemeral objects to remote store

### Related component

Cluster Manager

**Comment by peternied** [comment]
[Triage - attendees [1](https://github.com/jed326) [2](https://github.com/scrawfor99) [3](https://github.com/reta/) [4](https://github.com/srikanthpadakanti) [5](https://github.com/peternied) [6](https://github.com/lukas-vlcek/) [7](https://github.com/cwperks) [8](https://github.com/akolarkunnu) [9](https://github.com/truesellj) [10](https://github.com/mch2)]
This issue doesn't have enough context to make a clear triage choice - deferring to the Cluster Manager team triage.

**Comment by soosinha** [comment]
PR: https://github.com/opensearch-project/OpenSearch/pull/14089
