### ISSUE TITLE
[Remote Cluster State] Add new transport call to send cluster state term and version

### ISSUE THREAD

**Issue by soosinha** [opensearch-project/OpenSearch#13730]
### Is your feature request related to a problem? Please describe

meta issue: https://github.com/opensearch-project/OpenSearch/issues/13683
We need to communicate the cluster state term and version to the follower nodes during cluster state publication.

### Describe the solution you'd like

Add a new transport call which can send the cluster state term and version

### Related component

Cluster Manager

**Comment by peternied** [comment]
[Triage - attendees [1](https://github.com/jed326) [2](https://github.com/scrawfor99) [3](https://github.com/reta/) [4](https://github.com/srikanthpadakanti) [5](https://github.com/peternied) [6](https://github.com/lukas-vlcek/) [7](https://github.com/cwperks) [8](https://github.com/akolarkunnu) [9](https://github.com/truesellj) [10](https://github.com/mch2)]
This issue doesn't have enough context to make a clear triage choice - deferring to the Cluster Manager team triage.

**Comment by soosinha** [comment]
PR: https://github.com/opensearch-project/OpenSearch/pull/14137
