### ISSUE TITLE
Handle remote store custom metadata during docrep to remote migration

### ISSUE THREAD

**Issue by skumawat2025** [opensearch-project/OpenSearch#13745]
### Is your feature request related to a problem? Please describe

 During the document replication to a remote store migration of an index, we need to determine the remote custom metadata in `determineRemoteStoreCustomMetadataDuringMigration`.  In the remote custom metadata there is a flag `translog-metadata` that needs to know the translog blobstore metadata support to set it's value correctly. 

There should be a check to determine if the registered translog blobstore supports object metadata or not.
 Currently, the `blobStoreMetadataEnabled` flag is set to false because the integration tests run on the local file system, which does not support custom metadata. However, in a production environment, this flag should be set based on the capabilities of the registered blobstore.

### Describe the solution you'd like

NA

### Related component

Storage:Remote

**Comment by sachinpkale** [comment]
[Storage Triage - attendees [1](https://github.com/reta) [2](https://github.com/lukas-vlcek) [3](https://github.com/hasnain2808) [4](https://github.com/gbbafna) [5](https://github.com/linuxpi) [6](https://github.com/TODO) [7](https://github.com/sachinpkale) [8](https://github.com/astute-decipher) [9](https://github.com/BhumikaSaini-Amazon) [10](https://github.com/ltaragi) ]

Thanks for creating this issue, moved to `In Progress` based on the [PR](https://github.com/opensearch-project/OpenSearch/pull/13810)

**Comment by gbbafna** [comment]
[Storage Triage - attendees [1](https://github.com/reta) [2](https://github.com/lukas-vlcek) [3](https://github.com/akolarkunnu) [4](https://github.com/gbbafna) [5](https://github.com/linuxpi) [6](https://github.com/ltaragi) [7](https://github.com/sachinpkale) [8](https://github.com/astute-decipher) [9](https://github.com/BhumikaSaini-Amazon)  

Closing as this is not planned.
