### ISSUE TITLE
How to build OpenSearch released version package without snapshot from OpenSearch source code?

### ISSUE THREAD

**Issue by balar06** [opensearch-project/OpenSearch#1377]
I have tried to build OpenSearch release version of 1.0.0 from OpenSearch source code. 

Downloaded the code from GIT and ran "./gradlew assemble -Dsandbox.enabled=false" command. 
Build is successful, 
but the generated build package is in snapshot version.

How to build OpenSearch released version without snapshot from OpenSearch source code?

**Comment by dblock** [comment]
> why its was unknown and how to correct the **build_hash** field?

I am not sure where this comes from. Maybe do a bit of digging and open an issue if you can't figure it out?
