### ISSUE TITLE
[Feature Request] Allow setting query parameters on requests

### ISSUE THREAD

**Issue by oliverlockwood** [opensearch-project/OpenSearch#13776]
### Is your feature request related to a problem? Please describe

I am trying to migrate a complex project from Elasticsearch to OpenSearch. When using the `RestHighLevelClient` (which yes, I know is deprecated, but for various reasons, migrating away from that will be a separate follow-on piece of work!) I cannot filter out some big fields that aren't always required, which means that my search responses are much bigger than they could be; this adversely affects the performance of the application.

This problem is essentially the same as that described in #535.

### Describe the solution you'd like

At a fundamental level, I'd like to be able to set a query parameter like `?filter_path=-hits.hits._source.somethingbig` (as documented at https://opensearch.org/docs/2.3/opensearch/common-parameters/#filtered-responses.

I would be happy to implement this from scratch without inspecting the PR implementation of #536 which was closed due to the authors concerns about license infringement.  To that end, I have deliberately *not* looked at that PR.

### Related component

Clients

**Comment by peternied** [comment]
[Triage - attendees [1](https://github.com/jed326) [2](https://github.com/scrawfor99) [3](https://github.com/reta/) [4](https://github.com/srikanthpadakanti) [5](https://github.com/peternied) [6](https://github.com/lukas-vlcek/) [7](https://github.com/cwperks) [8](https://github.com/akolarkunnu) [9](https://github.com/truesellj) [10](https://github.com/mch2)]
@oliverlockwood Thanks for creating this issue, we would love a pull request to include this functionality - which I see you have already created
