### ISSUE TITLE
Bump Apache Lucene 9.11 snapshot in main to include commit 8d7bf86bbeccefe66ef67d424ffc748e56410e84

### ISSUE THREAD

**Issue by navneet1v** [opensearch-project/OpenSearch#13848]
### Is your feature request related to a problem? Please describe

I am working on Integrating KNNVectorsFormat in k-NN plugin for native engines(faiss/nmslib). To ensure that formats provided added in plugins can also be picked by SPI, I added this change in Lucene: https://github.com/apache/lucene/commit/8d7bf86bbeccefe66ef67d424ffc748e56410e84 which is approved and merged in branch_9x and main of Lucene.

### Describe the solution you'd like

I am creating this request to pull in the changes from Lucene at-least till [commit](https://github.com/apache/lucene/commit/8d7bf86bbeccefe66ef67d424ffc748e56410e84) in main branch of Opensearch. 

The last upgrade was done a month back. Ref: https://github.com/opensearch-project/OpenSearch/commit/39ac2df95dfc1344611d25a958aa54551bfe45b0

### Related component

Other

### Describe alternatives you've considered

For doing development I am currently building Lucene and Opensearch locally to ensure everything works.

### Additional context

Ref: https://github.com/opensearch-project/k-NN/issues/1087

**Comment by navneet1v** [comment]
cc: @msfroh , @reta

**Comment by reta** [comment]
@navneet1v I've triggered the Apache Lucene snapshot publishing, the latest ones `9.11.0-snapshot-4be6531` should be available so you could bump the version.

**Comment by navneet1v** [comment]
@reta thanks. Sure do let me know if there are any action items from my side.

**Comment by reta** [comment]
> @reta thanks. Sure do let me know if there are any action items from my side.

Please open the pull request with version update https://github.com/opensearch-project/OpenSearch/blob/994bfae0c0beddd8416ab88ed6138e2792638c4e/buildSrc/version.properties#L1C1-L3C1, `9.11.0-snapshot-fb97840` -> `9.11.0-snapshot-4be6531`, thank you

**Comment by navneet1v** [comment]
> > @reta thanks. Sure do let me know if there are any action items from my side.
> 
> Please open the pull request with version update https://github.com/opensearch-project/OpenSearch/blob/994bfae0c0beddd8416ab88ed6138e2792638c4e/buildSrc/version.properties#L1C1-L3C1, `9.11.0-snapshot-fb97840` -> `9.11.0-snapshot-4be6531`, thank you

Raised the PR: https://github.com/opensearch-project/OpenSearch/pull/13850
