### ISSUE TITLE
[BUG] 'index_not_found_exception' intermittently returning from `/bulk` requests when index does exist

### ISSUE THREAD

**Issue by CarterBland** [opensearch-project/OpenSearch#13856]
### Describe the bug

I'm encountering an extremely odd issue with OpenSearch while using Searchkick, a Rails gem for search functionality. I have the latest version of OpenSearch deployed in a Kubernetes cluster. The problem arises after I create and start populating an index. Randomly, I begin receiving index_not_found_exceptions after creating and attempting to fill an index using /bulk.
This is particularly perplexing because I added logs to check the index status with the following requests, `/_cat/indices/index_name` and `/index_name`. These logs confirm that the index exists, is green, and is open. I'm at an impasse and can't figure out what might be causing this issue.

Log before filling to make sure index exists and is available: 
green open staging_features_staging_20240524193642689 lGfB2eZZRXGHZ7CIspnELQ 1 1 292 0 2.1mb 1mb

Log right after:
{"type"=>"index_not_found_exception", "reason"=>"no such index [staging_features_staging_20240524193642689]", "index"=>"staging_features_staging_20240524193642689", "index_uuid"=>"lGfB2eZZRXGHZ7CIspnELQ"}

### Related component

Indexing

### To Reproduce

It's almost impossible for me to replicate reliably, but the flow I use to do it is:

1. Create a new index
2. Update mappings
3. Use bulk and attempt to populate index

### Expected behavior

There shouldn't an exception saying the index does not exist if I can log information about the index and discern it is healthy one line prior.

### Additional Details

**Plugins**
Please list all plugins currently enabled.

**Screenshots**
![image](https://github.com/opensearch-project/OpenSearch/assets/16313465/c98a1b2e-7832-423a-843a-553e73f159f2)

**Host/Environment (please complete the following information):**
 - OS: Linux
Hosted on K8s using the chart version below
- https://opensearch-project.github.io/helm-charts version: 2.19.0 (latest)

**Additional context**

**Comment by peternied** [comment]
[Triage - attendees [1](https://github.com/peternied) [2](https://github.com/reta) [3](https://github.com/andrross) [4](https://github.com/lukas-vlcek/) [5](https://github.com/dbwiddis)]
@CarterBland Thanks for creating this issue - since this might be hard to reproduce, could you see about writing or updating a test cases that would help us track down what is happening?

**Comment by CarterBland** [comment]
@peternied I'll try and get a minimal test-case up. I just started seeing this using the latest version, and I don't see this outside of the cluster.

**Comment by CarterBland** [comment]
Sorry for the delay, it's difficult for me to replicate, so I can't pass a code sample it but I can pass along logs. I added logs before and after, if the request fails, for the cluster health and health of the index. Oddly enough there is literally no difference between both cases outside of index name.

```
# Failed
Status before request: {"cluster_name":"opensearch-cluster","status":"green","timed_out":false,"number_of_nodes":3,"number_of_data_nodes":3,"discovered_master":true,"discovered_cluster_manager":true,"active_primary_shards":1,"active_shards":2,"relocating_shards":0,"initializing_shards":0,"unassigned_shards":0,"delayed_unassigned_shards":0,"number_of_pending_tasks":0,"number_of_in_flight_fetch":0,"task_max_waiting_in_queue_millis":0,"active_shards_percent_as_number":100.0,"indices":{"staging_features_staging_20240603213712303":{"status":"green","number_of_shards":1,"number_of_replicas":1,"active_primary_shards":1,"active_shards":2,"relocating_shards":0,"initializing_shards":0,"unassigned_shards":0,"shards":{"0":{"status":"green","primary_active":true,"active_shards":2,"relocating_shards":0,"initializing_shards":0,"unassigned_shards":0}}}}}
green open staging_features_staging_20240603213712303 -TbzKenQS16atpNePQ5S5A 1 1 0 0 416b 208b
Status after request: {"cluster_name":"opensearch-cluster","status":"green","timed_out":false,"number_of_nodes":3,"number_of_data_nodes":3,"discovered_master":true,"discovered_cluster_manager":true,"active_primary_shards":1,"active_shards":2,"relocating_shards":0,"initializing_shards":0,"unassigned_shards":0,"delayed_unassigned_shards":0,"number_of_pending_tasks":0,"number_of_in_flight_fetch":0,"task_max_waiting_in_queue_millis":0,"active_shards_percent_as_number":100.0,"indices":{"staging_features_staging_20240603213712303":{"status":"green","number_of_shards":1,"number_of_replicas":1,"active_primary_shards":1,"active_shards":2,"relocating_shards":0,"initializing_shards":0,"unassigned_shards":0,"shards":{"0":{"status":"green","primary_active":true,"active_shards":2,"relocating_shards":0,"initializing_shards":0,"unassigned_shards":0}}}}}
green open staging_features_staging_20240603213712303 -TbzKenQS16atpNePQ5S5A 1 1 0 0 416b 208b

# Passed
Status before request: {"cluster_name":"opensearch-cluster","status":"green","timed_out":false,"number_of_nodes":3,"number_of_data_nodes":3,"discovered_master":true,"discovered_cluster_manager":true,"active_primary_shards":1,"active_shards":2,"relocating_shards":0,"initializing_shards":0,"unassigned_shards":0,"delayed_unassigned_shards":0,"number_of_pending_tasks":0,"number_of_in_flight_fetch":0,"task_max_waiting_in_queue_millis":0,"active_shards_percent_as_number":100.0,"indices":{"staging_features_staging_20240603213846029":{"status":"green","number_of_shards":1,"number_of_replicas":1,"active_primary_shards":1,"active_shards":2,"relocating_shards":0,"initializing_shards":0,"unassigned_shards":0,"shards":{"0":{"status":"green","primary_active":true,"active_shards":2,"relocating_shards":0,"initializing_shards":0,"unassigned_shards":0}}}}}
green open staging_features_staging_20240603213846029 zgCDatcgTKOljR-vdWXCGA 1 1 0 0 416b 208b
```

**Comment by reta** [comment]
@CarterBland thank you for the details, may I ask you please to check server side logs in case there are hints (exception) why such inconsistencies might happen. Your remark

> The exception contains the UUID of the index, though it's absent in the bulk request so I'm not sure how it's in the exception response if the index isn't found from Opensearch unless it's computed from the index name.

is really hard to explain (afaik, index UUID is randomly generated and is not derived from name)

**Comment by CarterBland** [comment]
> @CarterBland thank you for the details, may I ask you please to check server side logs in case there are hints (exception) why such inconsistencies might happen. Your remark
> 
> > The exception contains the UUID of the index, though it's absent in the bulk request so I'm not sure how it's in the exception response if the index isn't found from Opensearch unless it's computed from the index name.
> 
> is really hard to explain (afaik, index UUID is randomly generated and is not derived from name)

Is there a good file to look for in /logs? Just following the logs there was no differences.

**Comment by reta** [comment]
> @reta Is there a good file to look for in the opensearch pod `/logs`? Just following the logs there was no differences.

Thanks @CarterBland , `opensearch.log` is  the default one, may be just grepping the `exception` could be easier, thanks for looking.

**Comment by CarterBland** [comment]
@reta Sorry for my confusion here, but I execute into the opensearch cluster pods and only see a logs folder with some of the following:
<img width="705" alt="Screen Shot 2024-06-04 at 11 08 32 AM" src="https://github.com/opensearch-project/OpenSearch/assets/16313465/ab265561-2893-4c53-9523-5135c41c7a96">

**Comment by reta** [comment]
Oh I see, got it, thanks @CarterBland , your cluster seems to be using stdout (typical with Docker?), in any case I will try to reproduce the issue.

**Comment by CarterBland** [comment]
@reta I really appreciate your help on this! Very strange bug. I actually have the logs screenshotted of both failed and passing STDOUT, granted there are 3 nodes but the node I am following shows both create index requests.

Passing: 
![Screen Shot 2024-06-03 at 4 23 50 PM](https://github.com/opensearch-project/OpenSearch/assets/16313465/91bfd1e7-b4d3-40ab-a2b6-5e6cfee4fea5)

Failing:
![Screen Shot 2024-06-03 at 4 25 30 PM](https://github.com/opensearch-project/OpenSearch/assets/16313465/39f3d180-5409-4a3c-9cf1-e3a32d73f646)

**Comment by reta** [comment]
Hm ... thanks @CarterBland , I think I do have a hypothesis now. It may not be an index related but mapping related: it seems like the mappings are deducted from the document(s) upon ingestion (index is auto created). Is that the case?

**Comment by CarterBland** [comment]
@reta No, I believe the index created, mapping is updated, then ingestion starts. I'm using Searchkick, a ruby gem, to abstract a lot of this, so let me get you concrete answer.

**Comment by reta** [comment]
> @reta No, I believe the index is created, mapping is updated, then ingestion starts.

Got it, thanks @CarterBland , just to clarify a possible issue here, there are 2 separate steps: 
 1. the index is created without mappings (or some basic ones?)
 2. the mappings are updated (as a separate step)

**Comment by CarterBland** [comment]
@reta Okay, as I understand it, Searchkick creates an index with basic mappings then does the bulk request. I believe at this point, through the bulk request, it gets the additional mappings?

**Comment by reta** [comment]
>  I believe at this point, through the bulk request, it gets the additional mappings?

@CarterBland that is what I would like to understand, are mapping dynamic or not

**Comment by CarterBland** [comment]
@reta Sorry for my confusion, working with packages tends to abstract a lot! I do believe mappings are dynamic. Proof below:

![Screen Shot 2024-06-04 at 2 39 34 PM](https://github.com/opensearch-project/OpenSearch/assets/16313465/1d707eb1-101d-4f60-b04c-c6d6ed9d613c)

**Comment by reta** [comment]
> @reta Sorry for my confusion, working with packages tends to abstract a lot! I do believe mappings are dynamic. Proof below:

Thank you @CarterBland , super helpful, I will try to reproduce the issue with the details we have now, will update you shortly.

**Comment by gaobinlong** [comment]
@CarterBland, do you use OpenSearch 2.13.0 and neural search? If so I think it's caused by this bug: https://github.com/opensearch-project/neural-search/pull/713 in the neural-search plugin. In 2.14.0, the bug was fixed, you can upgrade your OpenSearch version.

**Comment by CarterBland** [comment]
> @CarterBland, do you use OpenSearch 2.13.0 and neural search? If so I think it's caused by this bug: https://github.com/opensearch-project/neural-search/pull/713 in the neural-search plugin. In 2.14.0, the bug was fixed, you can upgrade your OpenSearch version.

Yes, exactly! That is most likely the issue, thanks. I will update our cluster and then close this issue.

**Comment by reta** [comment]
@gaobinlong thank you for chiming in!

**Comment by CarterBland** [comment]
@reta @gaobinlong  Thanks for your assistance with this issue, closing now!
