### ISSUE TITLE
[Feature Request] Move the Query Insights plugin out from core repo

### ISSUE THREAD

**Issue by ansjcy** [opensearch-project/OpenSearch#13881]
### Is your feature request related to a problem? Please describe

As we discussed [here](https://github.com/opensearch-project/OpenSearch/issues/11429#issuecomment-2136509138), although there are some benefits of keeping the plugin in core, but moving it to a separate repo could be a more standard and communuty friendly solution to introduce new plugins. let's kick off the process to move the query insights plugin to it's own repo.

### Describe the solution you'd like

Query insights should be in its own separate repo

### Related component

Search:Query Insights

**Comment by peternied** [comment]
[Triage - attendees [1](https://github.com/srikanthpadakanti) [2](https://github.com/peternied) [3](https://github.com/lukas-vlcek) [4](https://github.com/jed326) [5](https://github.com/reta) [6](https://github.com/andrross) [7](https://github.com/kotwanikunal)]
@ansjcy Thanks for creating this issue, thanks for driving this.
