### ISSUE TITLE
[Feature Request] Support cancellation on runaway apis.

### ISSUE THREAD

**Issue by aasom143** [opensearch-project/OpenSearch#13908]
### Is your feature request related to a problem? Please describe

Today, some APIs support only top-level timeouts, where a request is cancelled if it doesn't receive a response within the default 30-second timeout. However, the problem arises when these APIs internally make transport calls to cluster manager or other data nodes within the cluster even after the timeout expires. These internal/child calls, which are spawned by the API, are never timed out or cancelled, even though the top-level request was timed out. As a result, the cluster continues to perform unnecessary (wasteful) work and consuming resources but the user is not waiting for a response.

### Describe the solution you'd like

A new task is created for the admin API using a new transport action, which is then scheduled with a timeout to cancel the parent task. A parent-child correlation is established by setting the parent task ID in the nested transport requests, ensuring that the parent task should not be cancelled while creating the task for the nested transport actions. If the parent task is cancelled, the nested transport action will fail with an error message indicating that "the parent task was cancelled, shouldn't start any child tasks". Also if the parent task is cancelled, transport calls of nested transport actions will also with the same error.

### Related component

Cluster Manager

### Describe alternatives you've considered

Introducing a new timeout on the coordinator node to prevent timeouts from expiring before making transport calls to cluster manager/data nodes. To achieve this, we need to wrap the API's listener with a cancellation listener, where we schedule a task using a thread that allows us to cancel the task after a specified delay.. Once the listener is wrapped, we will pass it to the async call, where we make transport calls to cluster manager/data nodes. Before making any transport call, we will ensure that the task is not cancelled, and if it is, we will fail the API immediately.

_No response_

**Comment by peternied** [comment]
[Triage - attendees [1](https://github.com/srikanthpadakanti) [2](https://github.com/peternied) [3](https://github.com/lukas-vlcek) [4](https://github.com/jed326) [5](https://github.com/reta) [6](https://github.com/andrross) [7](https://github.com/kotwanikunal)]
@aasom143 thanks for creating this issue and a pull request.
