### ISSUE TITLE
[BUG] DCO check is not running for recent PRs

### ISSUE THREAD

**Issue by peteralfonsi** [opensearch-project/OpenSearch#13964]
### Describe the bug

For recent PRs into both main and 2.x, the DCO check is stuck at "Expected - waiting for status to be reported". Adding more commits or rebasing existing commits doesn't resolve this. For examples see https://github.com/opensearch-project/OpenSearch/pull/13655, https://github.com/opensearch-project/OpenSearch/pull/13961, https://github.com/opensearch-project/OpenSearch/pull/13957, https://github.com/opensearch-project/OpenSearch/pull/13801. A recent example of an open PR that doesn't have this issue is https://github.com/opensearch-project/OpenSearch/pull/13943. I believe this blocks merging as maintainers aren't able to manually rerun this check. 

### Related component

Other

### To Reproduce

Open a PR merging into main or 2.x

### Expected behavior

The check should run

**Comment by sohami** [comment]
This is a known ongoing issue and @prudhvigodithi is already looking into it.

**Comment by prudhvigodithi** [comment]
There is an ongoing issue with the external DCO app https://github.com/dcoapp/app/issues/211.
