### ISSUE TITLE
[Feature Request] Remove or shorten the PR checklist

### ISSUE THREAD

**Issue by andrross** [opensearch-project/OpenSearch#13965]
### Is your feature request related to a problem? Please describe

I personally find the PR checklist to be rote busy work that doesn't add a lot of value. Going entry by entry:

- **New functionality includes testing** - This is general software development best practice. Reviewers should be enforcing this. We have code coverage metrics published on each PR as well. I'm skeptical this checklist entry is helpful.
- **All tests pass** - PR workflows enforce this.
- **New functionality has been documented** - The `javadoc` targets enforce this as a part of the build if this refers to javadoc. If not, then this is duplicated by the "public documentation" entry below.
- **New functionality has javadoc added** - Same as above
- **API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md)** - I could be convinced this one should stay, maybe.
- **Failing checks are inspected and point to the corresponding known issue(s)** - The failing checks post a comment linking to the flaky test guide telling you want to do.
- **Commits are signed per the DCO using --signoff** - The DCO workflow enforces this
- **Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))** - The changelog workflow enforces this.
- **Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose)** - I could be convinced this one should stay, maybe.

### Describe the solution you'd like

Remove all checklist items except the "API Changes" and "Public Documentation" entries. Maybe consider removing the entire checklist if we don't have evidence the remaining two entries are effective.

### Related component

Other

**Comment by kotwanikunal** [comment]
+1 on the direction. 
Ever since we have made all checks as required, items on the checklist are redundant.

**Comment by kotwanikunal** [comment]
@peternied / @dblock - Thoughts here?

**Comment by andrross** [comment]
One potential goal of the checklist is to encourage contributors to do these things _before_ submitting a PR. However, given how many PRs I see where none of the template or checklist is filled out, I'd say the checklist has proven to be ineffective at accomplishing this goal.

**Comment by peternied** [comment]
I think of the checklist as a tool to inform on the requirements of the project and help remind maintainers what to check in on before merging a change.  However, if we feel its working counter to this purpose or hindering contributions we can certainly change it.

If you were to ask me what I would target first, I wouldn't mind the removal of the sub-bullets `All tests pass`, `New functionality has javadoc added` - want to make a PR to start trimming them down?

**Comment by peternied** [comment]
> However, given how many PRs I see where none of the template or checklist is filled out, I'd say the checklist has proven to be ineffective at accomplishing this goal.

@andrross I see you point; however, I'd offer an alternative perspective when I see empty PR templates its a great indicator to provide guidance to that contributor.

**Comment by reta** [comment]
@andrross thanks a lot for bringing this one up, I think keeping the checklist but making it shorter would be a good path forward:

**The functionality include testing**
**API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md)**
**Public documentation companion pull request [created] [created](https://github.com/opensearch-project/documentation-website/issues/new/choose)**

WDYT?

**Comment by andrross** [comment]
@reta I like it.

My remaining nitpick is that the majority of PRs do not change the REST API nor require an update to the documentation website. Is there a way to still surface those concerns when applicable without forcing every PR to check a box?

**Comment by peternied** [comment]
[Triage - attendees [1](https://github.com/srikanthpadakanti) [2](https://github.com/peternied) [3](https://github.com/lukas-vlcek) [4](https://github.com/jed326) [5](https://github.com/reta) [6](https://github.com/andrross) [7](https://github.com/kotwanikunal)]
@andrross Thanks for creating this issue, looking forward to a pull request
