### ISSUE TITLE
[BUG] A documentation issue, used CONTRIBUTING.md instead of DEVELOPER_GUIDE.md

### ISSUE THREAD

**Issue by akolarkunnu** [opensearch-project/OpenSearch#13984]
### Describe the bug

There is a statement mentioned in the gradle/ide.gradle file "For details on importing into IntelliJ see CONTRIBUTING.md."
How to import project in to IntelliJ is explained in DEVELOPER_GUIDE.md, not in CONTRIBUTING.md

### Related component

Other

### To Reproduce

Just browse through ide.gradle file.

### Expected behavior

It should be DEVELOPER_GUIDE.md instead of CONTRIBUTING.md

**Comment by peternied** [comment]
[Triage - attendees [1](https://github.com/srikanthpadakanti) [2](https://github.com/peternied) [3](https://github.com/lukas-vlcek) [4](https://github.com/jed326) [5](https://github.com/reta) [6](https://github.com/andrross) [7](https://github.com/kotwanikunal)]
@akolarkunnu Thanks for creating this issue, looks like you had opened a pull request and then closed it - want to open that back up so the change can be reivewed?
