### ISSUE TITLE
[BUG] [Github Workflow] Label(s) are not auto applied against the related component of the new issue

### ISSUE THREAD

**Issue by vikasvb90** [opensearch-project/OpenSearch#14007]
### Describe the bug

Labels do not get auto applied currently against the respective related component of the newly created issue. This increases triaging effort and component stakeholders can potentially skip paying attention to the issues.

### Related component

Other

### To Reproduce

Create a new issue with a related component e.g., ShardRouting. You won't find respective tag getting applied to the issue. This may not be applicable to all the related components though. For e.g., tag `Other` still gets auto-applied for an `other` component.

### Expected behavior

Tag for the respective related component should get auto-applied. 

### Additional Details

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**

**Comment by vikasvb90** [comment]
cc: @peternied

**Comment by peternied** [comment]
[Triage - attendees [1](https://github.com/srikanthpadakanti) [2](https://github.com/peternied) [3](https://github.com/lukas-vlcek) [4](https://github.com/jed326) [5](https://github.com/reta) [6](https://github.com/andrross) [7](https://github.com/kotwanikunal)]
@vikasvb90 Thanks for creating this issue

**Comment by msfroh** [comment]
I just tried with `ShardManagement:Placement` [here](https://github.com/opensearch-project/OpenSearch/issues/15044), and it worked.

@vikasvb90 , can you clarify which specific label isn't working for you? `ShardRouting` isn't an existing label.

You can see the various labels in the issue templates in the files here: https://github.com/opensearch-project/OpenSearch/tree/main/.github/ISSUE_TEMPLATE

The ShardManagement labels are only present for feature requests: https://github.com/opensearch-project/OpenSearch/blob/main/.github/ISSUE_TEMPLATE/feature_request.yml?plain=1

The logic to apply the labels assumes that the value in the dropdown matches an existing label. Maybe at the time you tried, the components had been added to the dropdown but the labels weren't created yet?

**Comment by vikasvb90** [comment]
@msfroh It was observed in a triage meeting hosted by @peternied . I didn't mention that `ShardRouting` is a label. `Create a new issue with a related component` I referred it as a component and no label is auto applied on this selection of component. The issue could be as simple as creating mappings between components and labels.

**Comment by msfroh** [comment]
> I didn't mention that ShardRouting is a label. Create a new issue with a related component I referred it as a component and no label is auto applied on this selection of component.

The point I was making is that the mechanism requires that components and their labels are exactly the same strings.

It sounds like the list of components in the issue template currently match the labels defined for the project, so I think we can close this.
