### ISSUE TITLE
[Feature Request] Enabling phase_took_enabled as a Search request parameter 

### ISSUE THREAD

**Issue by navneet1v** [opensearch-project/OpenSearch#14023]
### Is your feature request related to a problem? Please describe

I came across this setting `phase_took_enabled` which I liked very much, but this is a cluster level setting and once it is added the setting is enabled for all searches, which is not my usecase. My usecase is I want to get this breakdown of phase level took time for few of my expensive queries hence I want to control this setting via URL parameter of search api.

Similar thing is available for `default_allow_partial_results` where either I can set this as a setting or pass this as a URL parameter in search. 

Ref docs: https://opensearch.org/docs/latest/install-and-configure/configuring-opensearch/search-settings/

### Describe the solution you'd like

Make the setting `phase_took_enabled` also a URL parameter for Search api.

### Related component

Search

### Describe alternatives you've considered

NA

### Additional context

Ref docs: https://opensearch.org/docs/latest/install-and-configure/configuring-opensearch/search-settings/

**Comment by msfroh** [comment]
Good news! It is available as a search request parameter. 

You just need to set `&phase_took=true` in your URL:

https://github.com/opensearch-project/OpenSearch/blob/ca3796e8dde8830f21ec090cebe287d862abb264/server/src/main/java/org/opensearch/rest/action/search/RestSearchAction.java#L187-L191

It looks like we did remember to include it in the list of URL parameters in the search API documentation: https://opensearch.org/docs/latest/api-reference/search/#url-parameters

**Comment by navneet1v** [comment]
Thanks this was helpful. Closing this GH issue.
