### ISSUE TITLE
[Feature Request] How to set LogByteSizeMergePolicy minMergeSize ?

### ISSUE THREAD

**Issue by weily2** [opensearch-project/OpenSearch#14024]
### Is your feature request related to a problem? Please describe

I can set maxMergeSizeMB by add index.merge.policy.max_merged_segment in index settings ,but how to set minMergeSize , is there a dynamic settings ?

### Describe the solution you'd like

is there a dynamic settings to set minMergeSize ?

### Related component

Indexing

**Comment by msfroh** [comment]
It looks like there is a setting called `index.merge.log_byte_size_policy.min_merge`:

https://github.com/opensearch-project/OpenSearch/blob/ca3796e8dde8830f21ec090cebe287d862abb264/server/src/main/java/org/opensearch/index/LogByteSizeMergePolicyProvider.java#L68-L73

**Comment by andrross** [comment]
[Triage - attendees [1](https://github.com/scrawfor99) [2](https://github.com/reta) [3](https://github.com/andrross) [4](https://github.com/jed326/) [5](https://github.com/srikanthpadakanti/)]

Thanks @weily2. It looks like @msfroh has provided an answer. In the future, I'd recommend using the forum or slack for questions and help like this. Generally, GitHub issues are intended for feature requests and bugs more than support. Thanks!
