### ISSUE TITLE
[Remote Routing Table] Refactor Remote routing table interfaces

### ISSUE THREAD

**Issue by himshikha** [opensearch-project/OpenSearch#14067]
### Is your feature request related to a problem? Please describe

- Refactor Remote routing table interfaces to use remote interfaces from PR https://github.com/opensearch-project/OpenSearch/pull/13785
- Remove deadCode - https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/index/remote/RemoteStorePathStrategy.java#L110
- basePath to be constructed directly in RemoteRutingTableService since its moved to utils as part of refactoring https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java#L560

### Related component

ShardManagement:Routing

**Comment by peternied** [comment]
[Triage - attendees [1](https://github.com/peternied) [2](https://github.com/reta) [3](https://github.com/andrross) [4](https://github.com/jed326/) [5](https://github.com/akolarkunnu/)]
@rwali-aws Was this missed during the last triage meeting?

**Comment by rwali-aws** [comment]
@peternied Tagging for the remote routing was not clear. Going forward we will be tagging RemoteRouting issues with ShardManagement
