### ISSUE TITLE
Upgrade 1.x to latest Lucene 8.10.1 release

### ISSUE THREAD

**Issue by nknize** [opensearch-project/OpenSearch#1413]
Lucene 8.10.1 release was announced on October 18, 2021. This issue is to upgrade the 1.x branch to the latest release to pick up CVE and Bug Fixes.

**Comment by mch2** [comment]
@nknize I believe this can be closed with #1440 ?

**Comment by adnapibar** [comment]
Closing this as fixed by #1459
