### ISSUE TITLE
Apply the fast filter optimization to filter aggregation

### ISSUE THREAD

**Issue by bowenlan-amzn** [opensearch-project/OpenSearch#14189]

**Comment by andrross** [comment]
[Triage - attendees [1](https://github.com/scrawfor99) [2](https://github.com/reta) [3](https://github.com/andrross) [4](https://github.com/jed326/) [5](https://github.com/srikanthpadakanti/)]

Thanks @bowenlan-amzn, but there seems to be a lack of detail here. Please reopen if you can add more context :)
