### ISSUE TITLE
[BUG] flaky test - testCacheCleanupSkipsWithHighStalenessThreshold

### ISSUE THREAD

**Issue by kiranprakash154** [opensearch-project/OpenSearch#14242]
### Describe the bug

IndicesRequestCacheIT.testCacheCleanupSkipsWithHighStalenessThreshold  is flaky

### Related component

Search:Performance

### To Reproduce

Check this build - https://build.ci.opensearch.org/job/gradle-check/40838/testReport/junit/org.opensearch.indices/IndicesRequestCacheIT/testCacheCleanupSkipsWithHighStalenessThreshold__p0___opensearch_experimental_feature_pluggable_caching_enabled___true___/

### Expected behavior

should not be flaky

**Comment by reta** [comment]
Closing in favour of https://github.com/opensearch-project/OpenSearch/issues/14288
