### ISSUE TITLE
[BUG] Flaky Test IndicesRequestCacheIT  testCacheCleanupBasedOnStaleThreshold_thresholdUpdate

### ISSUE THREAD

**Issue by kiranprakash154** [opensearch-project/OpenSearch#14243]
### Describe the bug

testCacheCleanupBasedOnStaleThreshold_thresholdUpdate is flaky

### Related component

Search:Performance

### To Reproduce

https://build.ci.opensearch.org/job/gradle-check/40839/

### Expected behavior

not be flaky

### Additional Details

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**

**Comment by reta** [comment]
Closing in favour of https://github.com/opensearch-project/OpenSearch/issues/14288
