### ISSUE TITLE
[BUG] org.opensearch.repositories.azure.AzureBlobStoreRepositoryTests.testMultipleSnapshotAndRollback is flaky

### ISSUE THREAD

**Issue by sohami** [opensearch-project/OpenSearch#14278]
### Describe the bug

The test suite is flaky as the suite seems to be timing out

```
java.lang.Exception: Test abandoned because suite timeout was reached.
	at __randomizedtesting.SeedInfo.seed([65B308AE35ED9ED5]:0)
```

### Related component

Storage:Snapshots

### To Reproduce

The problem seems to be some of the tests are taking longer and suite level default timeout (20 min) is probably not good enough.

```
REPRODUCE WITH: ./gradlew ':plugins:repository-azure:internalClusterTest' --tests "org.opensearch.repositories.azure.AzureBlobStoreRepositoryTests" -Dtests.seed=65B308AE35ED9ED5 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=en -Dtests.timezone=Etc/UTC -Druntime.java=21
```

### Expected behavior

Test should always pass

### Additional Details

**Plugins**
Standard

**Screenshots**

**Additional context**
https://build.ci.opensearch.org/job/gradle-check/40884/testReport/junit/org.opensearch.repositories.azure/AzureBlobStoreRepositoryTests/

**Comment by prudhvigodithi** [comment]
Hey @sohami closing this issue since the automation created one issue for `AzureBlobStoreRepositoryTests`, please check https://github.com/opensearch-project/OpenSearch/issues/14291.
@andrross @dblock
