### ISSUE TITLE
[BUG] Batch ingestion appears to reorder documents in response with failures

### ISSUE THREAD

**Issue by andrross** [opensearch-project/OpenSearch#14336]
### Describe the bug

Send two documents in a bulk request with `batch_size` set to 2 or larger. Configure the ingest processor to fail on the first document and succeed on the second. The response will show success for the document that failed, and vice versa. Set the batch size to 1 and the test will pass.

### Related component

Indexing

### To Reproduce

See #14335 for a failing integration test

### Expected behavior

Tests in #14335 should pass

**Comment by chishui** [comment]
Fix PR: https://github.com/opensearch-project/OpenSearch/pull/14341

**Comment by andrross** [comment]
Resolved by #14341
