### ISSUE TITLE
[BUG] ScriptProcessor fails with Byte and Short data types

### ISSUE THREAD

**Issue by andrross** [opensearch-project/OpenSearch#14379]
### Describe the bug

#11725 introduced a regression in to OpenSearch 2.8 where the following ingest processor will fail:

```
{
  "description": "_description",
  "processors": [
    {
      "script" : {
        "source" : "ctx.byte = (byte)127;ctx.short = (short)32767"
      }
    },
    {
      "script" : {
        "source" : "ctx.other_field = 'other_field'"
      }
    }
  ]
}
```

### Related component

Indexing

### To Reproduce

Index a document using the pipeline defined above in OpenSearch 2.8 or newer

### Expected behavior

Request should not fail

**Comment by andrross** [comment]
FYI @vikasvb90

**Comment by vikasvb90** [comment]
@andrross I just reused the existing deepCopyMap to prevent self referencing objects in script. So, the problem has been there in the method even before my change. Data types were missing and surprisingly there were no tests to validate it as well.

**Comment by vikasvb90** [comment]
I validated that this breaks without my change in toXContent [here](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/action/ingest/WriteableIngestDocument.java#L141) and this is very much expected. 

So, please lets not call it regression due to my PR 😊
