### ISSUE TITLE
[BUG] Can't use use Mockito to mock static due to PriviledgedMockMaker

### ISSUE THREAD

**Issue by chishui** [opensearch-project/OpenSearch#14420]
### Describe the bug

I'm trying to use Mockito's mockStatic to write unit tests in ml-commons plugin. The plugin depends on OpenSearch-core. Core depends on org.mockito:mockito-core:5.11.0 which should already support mockStatic.

Here is the output of error when I ran the UT.
```
org.opensearch.ml.engine.algorithms.remote.AwsConnectorExecutorTest > executePredict_RemoteInferenceInput_EmptyIpAddress FAILED
    org.mockito.exceptions.base.MockitoException:
    The used MockMaker SubclassByteBuddyMockMaker does not support the creation of static mocks

    Mockito's inline mock maker supports static mocks based on the Instrumentation API.
    You can simply enable this mock mode, by placing the 'mockito-inline' artifact where you are currently using 'mockito-core'.
    Note that Mockito's inline mock maker is not supported on Android.
        at app//org.opensearch.mockito.plugin.PriviledgedMockMaker.createStaticMock(PriviledgedMockMaker.java:117)
        at app//org.opensearch.ml.engine.algorithms.remote.AwsConnectorExecutorTest.setUp(AwsConnectorExecutorTest.java:99)
```

It's because OpenSearch core provides its own version of MockMaker through [PriviledgedMockMaker.java](https://github.com/opensearch-project/OpenSearch/commit/e9635d6bfeade4a50ee75a7c2f86f909481e41c1#diff-e919cc5ce5d69e528797a7e3d5a8178abb2f13aed1fc261a757dccdbf847a76e) and configured [here](https://github.com/opensearch-project/OpenSearch/blob/112704bf2976db8b0dd71980173896029a490cd9/test/framework/src/main/resources/mockito-extensions/org.mockito.plugins.MockMaker).

The PriviledgedMockMaker's logic hasn't been touched for >3 years and obviously it doesn't include the new mockito's features.

It's very confusing when people try to write tests in all repos depending on OpenSearch by mocking static class and this is an example I found from Mockito issues: https://github.com/mockito/mockito/issues/2877#issuecomment-1797187776

### Related component

Libraries

### To Reproduce

Try to write a unit test by mocking static class e.g.
```java
 MockedStatic<Credentials> credentials = Credentials.getCredentials(any());
```

### Expected behavior

Repos depending on OpenSearch core can utilize Mockito's feature to mock static class and won't get exception.

### Additional Details

**Plugins**
I found this issue from ml-commons plugin, but it's not limited to this plugin.

**Comment by andrross** [comment]
I don't really have anything helpful to add for the specific request here, but in my experience the need to mock a static method is almost always a symptom of some other problem. I would strongly encourage you to look for other alternatives, such as refactoring the code under test to be properly testable without having to replace arbitrary functions at runtime. (Sorry, I'll get off my soapbox now)

**Comment by owaiskazi19** [comment]
@chishui does other tests of ml-commons using MockedStatic would help you? Found one reference [here](https://github.com/opensearch-project/ml-commons/blob/487f33a2e35e642429e9a3ea1eb0d715d542ea9f/ml-algorithms/src/test/java/org/opensearch/ml/engine/MLEngineTest.java#L163-L165).

**Comment by chishui** [comment]
> @chishui does other tests of ml-commons using MockedStatic would help you? Found one reference [here](https://github.com/opensearch-project/ml-commons/blob/487f33a2e35e642429e9a3ea1eb0d715d542ea9f/ml-algorithms/src/test/java/org/opensearch/ml/engine/MLEngineTest.java#L163-L165).

I'm trying to do the same, tests in the code you linked are marked as ignore and have `// TODO: fix mockito error` [code](https://github.com/opensearch-project/ml-commons/blob/487f33a2e35e642429e9a3ea1eb0d715d542ea9f/ml-algorithms/src/test/java/org/opensearch/ml/engine/MLEngineTest.java#L156-L157)

Actually, I'm already able to bypass `PriviledgedMockMaker` by defining MockMaker in ml-commons similar to [here](https://github.com/opensearch-project/OpenSearch/blob/112704bf2976db8b0dd71980173896029a490cd9/test/framework/src/main/resources/mockito-extensions/org.mockito.plugins.MockMaker) with default MockMaker in Mockito. 

The problem with `PriviledgedMockMaker` is that it needs update, otherwise, whenever people want to use Mockstatic, they run into exception but don't know how to solve as the mock is done by OpenSearch's `PriviledgedMockMaker` is not obvious to everyone https://github.com/mockito/mockito/issues/2877#issuecomment-1797187776.  And people have to either not test the function properly or ignore the tests like the [code](https://github.com/opensearch-project/ml-commons/blob/487f33a2e35e642429e)

**Comment by chishui** [comment]
> I don't really have anything helpful to add for the specific request here, but in my experience the need to mock a static method is almost always a symptom of some other problem. I would strongly encourage you to look for other alternatives, such as refactoring the code under test to be properly testable without having to replace arbitrary functions at runtime. (Sorry, I'll get off my soapbox now)

Totally agreed with you about static functions. If I'm writing a new static function, I would reconsider my choice and refactor my code. But I'm trying to add/fix tests involving existing static functions. There are static functions here and there which may lack testing and it's still beneficial if we can fix this issue and make static mock work and improve our test coverage.

**Comment by chishui** [comment]
Found another way to bypass: using customized MockMaker
```
Mockito.mockStatic(Credentials.class, new MockSettingsImpl().mockMaker("org.mockito.internal.creation.bytebuddy.InlineByteBuddyMockMaker"));
```

**Comment by peternied** [comment]
[Triage - attendees [1](https://github.com/peternied) [2](https://github.com/reta) [3](https://github.com/andrross) [4](https://github.com/jed326/) [5](https://github.com/akolarkunnu/)]
@chishui Thanks for creating this issue; however it is being closed out because this is an anti-pattern in our codebase - that hasn't yet been removed.

We would recommend that refactor the code under test not to use a static reference so this case isn't needed.

**Comment by andrross** [comment]
@chishui Can you refactor the code under test to make the `Credentials` instance injectable so that you don't need to mock that static method?
