### ISSUE TITLE
[BUG] Potential Cluster Slowdown/Lags after merging #13748(#14348) #14338(#14391) in 2.15

### ISSUE THREAD

**Issue by peterzhuamazon** [opensearch-project/OpenSearch#14442]
### Describe the bug

During [2.15.0 release process](https://github.com/opensearch-project/opensearch-build/issues/4681), Infra has generated multiple Release Candidates (RC) for testing before launch date.

Between [RC3](https://github.com/opensearch-project/opensearch-build/issues/4681#issuecomment-2169133032) and [RC4](https://github.com/opensearch-project/opensearch-build/issues/4681#issuecomment-2176871067), the only two major changes are: https://github.com/opensearch-project/opensearch-build/pull/4785
* #14348
* #14391

Once generated RC4, we have observed potential slow downs in Dashboards related plugin integTests. 
* RC3 OSD X64 TAR test: https://build.ci.opensearch.org/blue/organizations/jenkins/integ-test-opensearch-dashboards/detail/integ-test-opensearch-dashboards/5950/pipeline
* RC4 OSD X64 TAR test: https://build.ci.opensearch.org/blue/organizations/jenkins/integ-test-opensearch-dashboards/detail/integ-test-opensearch-dashboards/5964/pipeline

These failures are not all the same, but observe very similar symptoms, as elements are not loaded in on time. These behaviors seems as if OS is slowing down causing OSD GUI to load much slower as a side effect.

* securityDashboards: https://ci.opensearch.org/ci/dbc/integ-test-opensearch-dashboards/2.15.0/7742/linux/arm64/tar/test-results/5963/integ-test/securityDashboards/with-security/stdout.txt
```
  1) Home(Get Started) page
       should load Home page properly:
     AssertionError: Timed out retrying after 10000ms: Expected to find content: 'Get started' within the selector: 'h1' but never did.
      at Context.eval (http://localhost:5601/__cypress/tests?p=cypress/integration/plugins/security/get_started_spec.js:170:10)
```
* reportsDashboards: https://ci.opensearch.org/ci/dbc/integ-test-opensearch-dashboards/2.15.0/7742/linux/x64/tar/test-results/5964/integ-test/reportsDashboards/without-security/stdout.txt
```
  1) Cypress
       "before all" hook for "Visits Reporting homepage":
     AssertionError: Timed out retrying after 10000ms: Expected to find element: `div[data-test-subj="sampleDataSetCardflights"]`, but never found it.

Because this error occurred during a `before all` hook we are skipping the remaining tests in the current suite: `Cypress`
      at Context.eval (http://localhost:5601/__cypress/tests?p=cypress/integration/plugins/reports-dashboards/01-create.spec.js:167:8)
```
* queryWorkbenchDashboards: https://ci.opensearch.org/ci/dbc/integ-test-opensearch-dashboards/2.15.0/7742/linux/x64/tar/test-results/5964/integ-test/queryWorkbenchDashboards/with-security/stdout.txt
```
  1) Test PPL UI
       "before each" hook for "Confirm results are empty":
     AssertionError: Timed out retrying after 10000ms: Expected to find element: `.euiButton__text[title=PPL]`, but never found it.

Because this error occurred during a `before each` hook we are skipping the remaining tests in the current suite: `Test PPL UI`
      at Context.eval (http://localhost:5601/__cypress/tests?p=cypress/integration/plugins/query-workbench-dashboards/ui.spec.js:207:8)
```

We are able to reproduce these error locally as well. After switching from RC4 to RC3 artifacts, these errors are gone and test passes.

Please take a look and let us know the results.
Thanks!

### Related component

Other

### Expected behavior

OSD integTests passes.

### Additional Details

**Plugins**
All

**Screenshots**

**Host/Environment (please complete the following information):**
All Dist/Arch

**Additional context**

**Comment by getsaurabh02** [comment]
@SwethaGuptha @shwetathareja @soosinha Can we please verify and root cause if these changes merged between RC3 and RC4 can potentially slow down OS, thereby causing delay of OSD objects and leading to assertion failures (timeouts) on multiple fronts in the dashboard plugins. 

cc: @dblock @Pallavi-AWS @rramachand21

**Comment by zelinh** [comment]
Reproduced the with-security test failure for securityDashboards locally. 

```
  7 passing (36s)
  1 failing

  1) Home(Get Started) page
       should load Home page properly:
     AssertionError: Timed out retrying after 10000ms: Expected to find content: 'Get started' within the selector: 'h1' but never did.
      at Context.eval (http://localhost:5601/__cypress/tests?p=cypress/integration/plugins/security/get_started_spec.js:170:10)
```

**Comment by shwetathareja** [comment]
@zelinh : The local repro is with RC4? Can you try if it reproduces with RC3 as well?
Also, are you able to profile OSD to confirm if the extra time spent was in OSD itself or due to delay in OS process bootstrapping.

@SwethaGuptha / @shiv0408 to help profile the 2 PRs merged in 2.15 RC4 which are the suspects:
https://github.com/opensearch-project/OpenSearch/pull/14348
https://github.com/opensearch-project/OpenSearch/pull/14391

**Comment by shwetathareja** [comment]
The remote cluster state is disabled by default related PR - https://github.com/opensearch-project/OpenSearch/pull/14391  and also the bug fix made by https://github.com/opensearch-project/OpenSearch/pull/14348 is for fetching unassigned shards details in batch mode which is disabled by default.

The team can compare bootstrap times for OS process with RC3 and RC4

**Comment by shiv0408** [comment]
@peterzhuamazon I tried bootstrapping the OpenSearch process from RC3 and RC4 binaries. In fact, the time to bootstrap for RC3 (2.671s) was higher than RC4 (2.491s) on my system.

**Comment by peternied** [comment]
[Triage - attendees [1](https://github.com/peternied) [2](https://github.com/reta) [3](https://github.com/andrross) [4](https://github.com/jed326/) [5](https://github.com/akolarkunnu/)]
@peterzhuamazon Thanks for creating this issue

**Comment by peterzhuamazon** [comment]
Hi,

@shwetathareja @shiv0408 We use RC3 and RC4 for the test.
And securityDashboards always succeed on RC3 but failed on RC4.

As you can see this PR the only change between RC3 and RC4 code wise is these two PRs:
* https://github.com/opensearch-project/opensearch-build/pull/4785

Thanks.

**Comment by peterzhuamazon** [comment]
We are suspecting there is some side effects of these two PRs causing Dashboards to slow down.
On OpenSearch itself since I dont have enough context on the changes, I do not know if they actually slows down the bootstrap time or not.

I do think this is not just on bootstrap time, but rather when running actually queries where some returns slows down causing dashboards to not load elements quick enough in time for the tests to pass. Thanks.a

**Comment by shiv0408** [comment]
@peterzhuamazon these PRs should not cause any side effects as both of these codes only run when specific settings are enabled, which are disabled by default. 
I agree from errors it looks like not just bootstrap, but slowdown in loading UI seems to be the cause. There is something else we are missing which is causing these slowdown, these PRs can't be the culprits.

**Comment by soosinha** [comment]
Found a commit in opensearch-dashboards-functional-test repo : https://github.com/opensearch-project/opensearch-dashboards-functional-test/commit/9c17a6c7b3f9c137eb1cdf311f1692a079b4b1f4
This commit had changed the timeout of tests from 60s to 10s due to which a lot tests started failing.
So the PRs in OpenSearch repo mentioned previously should be good to go ahead with.

**Comment by peterzhuamazon** [comment]
> Found a commit in opensearch-dashboards-functional-test repo : [opensearch-project/opensearch-dashboards-functional-test@9c17a6c](https://github.com/opensearch-project/opensearch-dashboards-functional-test/commit/9c17a6c7b3f9c137eb1cdf311f1692a079b4b1f4) This commit had changed the timeout of tests from 60s to 10s due to which a lot tests started failing. So the PRs in OpenSearch repo mentioned previously should be good to go ahead with.

Thanks @soosinha for the debug together.

I will soon send a PR to revert this commit. 

And proceed with the RC5 builds. Sorry for confusion.

**Comment by peterzhuamazon** [comment]
Revert now: 
* https://github.com/opensearch-project/opensearch-dashboards-functional-test/pull/1422
