### ISSUE TITLE
[Meta] Indexing Backpressure in OpenSearch

### ISSUE THREAD

**Issue by getsaurabh02** [opensearch-project/OpenSearch#1446]
## Problem Statement

Indexing APIs in OpenSearch today such as _bulk allows you to index multiple documents in a single request. These requests are executed in a distributed manner updating multiple indices, across multiple shards, on multiple data nodes in the cluster. However, sometimes, these indexing requests could experience performance degradation due to multiple factors - incorrect cluster configuration and shard settings, changes in traffic patterns, resource starvation, hardware issues, and transient networking events. These issues could cause memory build-ups leading to out-of-memory failures and long garbage collection (GC) pauses, and affect the node’s ability to process the requests efficiently. If the affected node is not recovered immediately, it could cause a node drop event which can have cascading effect on the cluster’s performance and availability.

OpenSearch provides few control mechanisms today to prevent a data node meltdown for bulk indexing requests. These are essentially achieved by queue rejections, circuit breakers, and node-level memory limits for indexing traffic. However, these gating mechanisms are all static and reactive.

* **Thread pool queue sizes** are static in nature and do not change dynamically in real time. Every incoming request in the queue consumes resources differently.
* **Circuit Breakers** can track real-time memory utilization but most of them apply blanket level rejections without any fairness or identifying resources required for the requests. 
* **Node level Indexing Pressure limit** framework is designed to reject overwhelming indexing requests based on some pre-defined static limits on nodes. It is similar to the blanket level rejections offered by circuit breakers.

There is a need for smarter rejection mechanism at a granular level i.e. per shard request. This should help identify the underlying reason (slow indexing requests or stuck indexing tasks) for a performance breach in a cluster. Once the issue is detected, there is a need for an effective propagation of backpressure, transferring the load from the overwhelmed node to other nodes that are still healthy. The healthy nodes are capable of taking smarter backoff and short circuit decisions while processing these requests.

## Proposal For Shard Level Indexing Backpressure

The proposal is to add shard level indexing backpressure, that will introduce dynamic load shedding strategy for the incoming indexing requests when there are too many stuck/slow requests in the cluster. Shard level indexing backpressure will focus on dynamically assigning memory quota from the total memory pool to each shard based on its operational needs i.e. the incoming workloads. A combination of shard level memory utilization and throughput enables OpenSearch to decide if it should process a request. This will also prevents other nodes in the cluster from running into cascading failures due to the performance degradation caused by slow node, stuck tasks, resource intensive requests, traffic surge, or skewed shard allocation. Shard level indexing backpressure will depend on the following set of parameters to make decisions.

**Primary Parameters**

Primary parameters, are leading indicators for initial signs of duress on the node and are governed through soft limits

1. **Shard memory limit breach :** The allocated shard level memory limit is breached, and there is a need to increase the allocation.
2. **Node memory limit breach :** If the total allocated node level memory limit for indexing requests is breached. 

Breach of primary parameters reflect no actual rejections yet, but emphasize on the need to evaluate secondary signals.

**Secondary Parameters**

These parameters are based on shard level granular performance, such as request throughput and successful completion of requests. While these shard states are built with every request, they are evaluated only when the primary parameters are breached. We propose introducing two secondary parameters:

1. **Throughput:** The framework keeps track of request latency per unit byte at the shard level, and any substantial decrease in the shard throughput against its historic performance is considered as a degradation.
2. **Successful Request:** The framework also tracks successful indexing requests at the shard level, and signals if there are large number of requests pending to be served yet. This is useful in detecting memory build-ups due to stuck requests proactively and invoke the required backpressure. 

**Conclusion**

Indexing backpressure takes effect when the one of the primary parameters and secondary parameters’ thresholds are breached on the node. This results in rejection of new incoming requests/tasks for the affected shards on the node
The mechanism used by indexing backpressure is fair. The selective rejections of requests are intended only for problematic index or shard, while still allowing others to continue. 

These rejection thresholds are governed by the combination of configurable parameters which can be updated via OpenSearch dynamic settings. 

## Providing Feedback

If you have comments or feedback on our plans for Indexing Backpressure in OpenSearch, please comment on the GitHub issue (https://github.com/opensearch-project/OpenSearch/issues/478) in this project to discuss.

**Comment by getsaurabh02** [comment]
**Shard Indexing Pressure Stats**

* GET /_nodes/_local/stats/shard_indexing_pressure
    * To get the node level stats for Rejection counts. This API is also used by CW to publish metrics to customer account.
        
* GET /_nodes/stats/shard_indexing_pressure
    * To get the shard level breakup of indexing stats and rejections for every node. This only includes the hot shards i.e. shards which have active writes on them currently.
        
* GET /_nodes/_local/stats/shard_indexing_pressure?include_all
    * To get all shards level breakup of indexing stats and rejections for every node. This only includes the hot shards as well as cold shards i.e. shards which do not have active writes currently on them.
        
* GET /_nodes/_local/stats/shard_indexing_pressure?top
    * To get the top level aggregated metrics on rejections. Here is skips the per shard stats.

**Comment by elfisher** [comment]
@getsaurabh02. Did this already launch? This is still on the roadmap, but I thought this already launched.

**Comment by getsaurabh02** [comment]
Hi @elfisher yes this is already launched. Closing this as changes are already merged as part of #1336 and Meta issue covers specific items as part of https://github.com/opensearch-project/OpenSearch/issues/478
