### ISSUE TITLE
[BUG] HDFS repository plugin error

### ISSUE THREAD

**Issue by melokk97** [opensearch-project/OpenSearch#1447]
**Describe the bug**
When I try to register the repository, I get the error:
```
{
  "error" : {
    "root_cause" : [
      {
        "type" : "repository_verification_exception",
        "reason" : "[hdfs_repository] path  is not accessible on master node"
      }
    ],
    "type" : "repository_verification_exception",
    "reason" : "[hdfs_repository] path  is not accessible on master node",
    "caused_by" : {
      "type" : "i_o_exception",
      "reason" : "java.lang.NoClassDefFoundError: com/google/common/util/concurrent/internal/InternalFutureFailureAccess",
      "caused_by" : {
        "type" : "no_class_def_found_error",
        "reason" : "com/google/common/util/concurrent/internal/InternalFutureFailureAccess"
      }
    }
  },
  "status" : 500
}
```

**To Reproduce**
1. Install plugin ***repository-hdfs*** with `sudo bin/opensearch-plugin install repository-hdfs`
2. In DevTools do 
```PUT _snapshot/hdfs_repository
{
  "type": "hdfs",
  "settings": {
    "uri": "hdfs://10.92.9.148:8020/",
    "path": "rep/new"
  }
}
```
3. See error

**Plugins**
- opensearch-alerting                  1.1.0.0
- opensearch-anomaly-detection         1.1.0.0
- opensearch-asynchronous-search       1.1.0.0
- opensearch-cross-cluster-replication 1.1.0.0
- opensearch-index-management          1.1.0.0
- opensearch-job-scheduler             1.1.0.0
- opensearch-knn                       1.1.0.0
- opensearch-notebooks                 1.1.0.0
- opensearch-performance-analyzer      1.1.0.0
- opensearch-reports-scheduler         1.1.0.0
- opensearch-security                  1.1.0.0
- opensearch-sql                       1.1.0.0
- repository-hdfs                      1.1.0

**Host/Environment (please complete the following information):**
 - CentOS 7
 - docker-compose Opensearch-1.1.0

**Comment by adnapibar** [comment]
@melokk97 can you give more details on how to reproduce this.  I tried to repro this using both OpenSearch 1.1.0 linux-tar and docker image and I'm able to successfully register the snapshot repository.

**Comment by melokk97** [comment]
@adnapibar for hadoop: 
- Install hadoop 3.1.2
- make `hdfs dfs -mkdir /user/opensearch` and `hdfs dfs -chown elasticsearch /user/opensearch`
As for the opensearch, I described above: install opensearch, install plugin hdfs and try to register hdfs repo

**Comment by melokk97** [comment]
One dependency seems to be missing. I added the line `// https://mvnrepository.com/artifact/com.google.guava/failureaccess
implementation group: 'com.google.guava', name: 'failureaccess', version: '1.0.1'
` to the file `build.gradle` (https://mvnrepository.com/artifact/com.google.guava/failureaccess/1.0.1) and this solved my problem

**Comment by saratvemulapalli** [comment]
@melokk97 where was this dependency missing? 
Is this something which has to be fixed in the plugin build.gradle ?

**Comment by melokk97** [comment]
@saratvemulapalli @dblock in the latest version plugin the bug did not reproduce

**Comment by saratvemulapalli** [comment]
@melokk97 @dblock I'll close this for now. Feel free to re-open when see problems.
