### ISSUE TITLE
Regex Pattern in painless script in ingest pipeline giving "unexpected value type [class [Ljava.lang.String;]"

### ISSUE THREAD

**Issue by slylock** [opensearch-project/OpenSearch#14526]
### Describe the bug

Painless script that worked in 2.11 does not work in 2.13.  The offending code appears to be 
            Pattern p = /a/;
The error happens when the script executes during ingest:   "unexpected value type [class [Ljava.lang.String;]"
Is regex disabled in painless in 2.13?

### Related component

Indexing

### To Reproduce

Have a regex pattern in a painless script in an ingest pipeline

### Expected behavior

Regex patterns were acceptable in ingest pipelines in 2.11

### Additional Details

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**
 - AWS OpenSearch Server
 - Version 2.13
**Additional context**

**Comment by dbwiddis** [comment]
Hi @slylock can you give a specific example ingest processor example with this failing regex script?

**Comment by slylock** [comment]
> Hi @slylock can you give a specific example ingest processor example with this failing regex script?

Sorry, I misinterpreted the symptoms
