### ISSUE TITLE
Add primary preference to be set as an index setting for the warm index

### ISSUE THREAD

**Issue by neetikasinghal** [opensearch-project/OpenSearch#14543]
For a writable warm index, the default search preference should be set to primary such that the traffic is routed to the primary shards always for a warm index.

Currently, the search preference can be set only at a request level, so if a user doesn't specify the search preference as primary, the request can be routed to both primary/replica shards.

Proposal here is to create an index level setting to set the search preference  as "_primary_first" by default for a warm index. ref: https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/cluster/routing/Preference.java#L69

**Comment by peternied** [comment]
[Triage - attendees [1](https://github.com/peternied) [2](https://github.com/vikasvb90/) [3](https://github.com/srikanthpadakanti)]
@neetikasinghal Looks like a work item in the storage ecosystem

**Comment by neetikasinghal** [comment]
Checking more on how searchable snapshot deals with it - 

Its dealt with in the search path itself rather than introducing a new index setting for the warm index:
https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/cluster/routing/OperationRouting.java#L244

Something similar can be done even for the writable warm index as well.

**Comment by linuxpi** [comment]
[Storage Triage - attendees [1](https://github.com/ashking94/) [2](https://github.com/shourya035/) [3](https://github.com/gbbafna/) [4](https://github.com/andrross/) [5](https://github.com/ltaragi/) [6](https://github.com/astute-decipher/) [7](https://github.com/skumawat2025/) [8](https://github.com/linuxpi/)]

@neetikasinghal Thanks for filing this issue, please feel free to submit a pull request and add more details
