### ISSUE TITLE
[BUG] Container SIGTERM does nothing on Docker Hub images

### ISSUE THREAD

**Issue by liamwhite** [opensearch-project/OpenSearch#14577]
### Describe the bug

Sending the Docker container a SIGTERM fails to stop OpenSearch. This makes shutdown from compose extraordinarily slow as it now waits for the timeout to send a kill signal to the search server.

#13851 related, but I reproduced this issue on 2.11 as well

### Related component

Cluster Manager

### To Reproduce

```
$ docker run -d --ulimit nofile=65536:65536 --rm -e 'discovery.type=single-node' -e 'OPENSEARCH_INITIAL_ADMIN_PASSWORD=Hunter2!IsInsecure' opensearchproject/opensearch:2.14.0
69e99a4309fe9f1cbd7a8591c5b82361a5f234ae5dd18adb8e778e50e33f1d5f
$ sleep 5
$ docker kill --signal=SIGTERM 69e99a4309fe9f1cbd7a8591c5b82361a5f234ae5dd18adb8e778e50e33f1d5f
69e99a4309fe9f1cbd7a8591c5b82361a5f234ae5dd18adb8e778e50e33f1d5f
$ sleep 5
$ docker ps
CONTAINER ID   IMAGE                                 COMMAND                  CREATED          STATUS          PORTS                                    NAMES
69e99a4309fe   opensearchproject/opensearch:2.14.0   "./opensearch-docker…"   25 seconds ago   Up 24 seconds   9200/tcp, 9300/tcp, 9600/tcp, 9650/tcp   serene_chebyshev
```

### Expected behavior

OpenSearch should shut down after receiving a SIGTERM.

**Comment by happydude** [comment]
might be a duplicate of https://github.com/opensearch-project/OpenSearch/issues/13851

It does seem to work in v1

**Comment by liamwhite** [comment]
Was fixed by https://github.com/opensearch-project/opensearch-build/pull/4694 in the 2.15 release.
