### ISSUE TITLE
[Feature Request] Optimise collections in Shard Allocators

### ISSUE THREAD

**Issue by Bukhtawar** [opensearch-project/OpenSearch#14644]
### Is your feature request related to a problem? Please describe

During reroute of 200k shards, the collections weren't performing optimally
1. https://github.com/opensearch-project/OpenSearch/pull/14613
2. https://github.com/opensearch-project/OpenSearch/issues/14645

### Describe the solution you'd like

Change to optimal collections, that can facilitate faster executions

### Related component

ShardManagement:Performance

**Comment by rwali-aws** [comment]
[Triage - attendees [1](https://github.com/rwali-aws) [2](https://github.com/reta) [3](https://github.com/akolarkunnu) [4](https://github.com/sumitasr) [5](https://github.com/lukas-vlcek/) [6](https://github.com/kpinkuprakash)]


@Bukhtawar Thanks for filing this issue. This looks to be duplicate with https://github.com/opensearch-project/OpenSearch/issues/14532. Is there any additional/incremental you want to track as part of this issue?
