### ISSUE TITLE
[Feature Request] Generic Numeric Type Converters for Numeric Field Data

### ISSUE THREAD

**Issue by sarthakaggarwal97** [opensearch-project/OpenSearch#14657]
### Is your feature request related to a problem? Please describe

With an ongoing introduction of Star Tree (Composite Field), there was a requirement to convert the sortable long value of a field to an original numeric type value in order to perform aggregations via star tree. 

Currently, we picked up different numeric conversions for different numeric types to incorporate for star tree. This is prone to inconsistent results in cases where the type conversion implementation changes in the original aggregation flow.

### Describe the solution you'd like

A generic utility to perform numeric type conversion across OpenSearch. This will become a one-stop utility for numeric conversions.

### Related component

Indexing

**Comment by mgodwan** [comment]
> A generic utility to perform numeric type conversion across OpenSearch. This will become a one-stop utility for numeric conversions.

Won't using this utility still be an opt-in. Can we bake something to achieve this within the contract for these mappers?
