### ISSUE TITLE
[BUG] High CPU Usage reported reported for ClusterManager node by _node/stats API.

### ISSUE THREAD

**Issue by gargharsh3134** [opensearch-project/OpenSearch#14667]
### Describe the bug

Users are reporting high CPU usage percent being reported by the _node/stats API for clusterManager node post upgrading to 2.11 version from 1.3 version. With little to no change in workload, the cluster on 1.3 version was never reporting a CPU usage percent above 40%, however post upgrading, the percent is intermittently spiking to even around 90%.
Need to investigate potential cause of regression (either in the functionality or the metric being reported) leading to CPU usage spikes.

Cluster Configuration on which spikes were observed:
3 Data Nodes (r6gd.4xlarge)
3 Master Nodes (r6gd.large)
Total Number of shards -> 150

### Related component

Cluster Manager

### To Reproduce

1. Monitoring the CPU usage percent provided by _node/stats API for clusterManager node, before and after upgrading from 1.3 version to 2.13 version.

### Expected behavior

Given the workload remained pretty much constant, the intermittent CPU spikes should not have been observed.

**Comment by dblock** [comment]
[Catch All Triage - [1](https://github.com/dblock), [2](https://github.com/krisfreedain), [3](https://github.com/andrross), [4](https://github.com/reta)]

**Comment by chanon-onman** [comment]
We also see this issue with AWS OpenSearch 2.11

**Comment by gargharsh3134** [comment]
The API was returning the correct CPU utilisation. It was an issue with our host setup, where a background component was intermittently taking up more CPU. 
Since, Opensearch process was not the one causing spikes and APIs response was cross-verified by taking ```top``` dumps, I'm closing this issue.

**Comment by gargharsh3134** [comment]
The API was returning the correct CPU utilisation. It was an issue with our host setup, where a background component was intermittently taking up more CPU.
Since, Opensearch process was not the one causing spikes and APIs response was cross-verified by taking ```top``` dumps, I'm closing this issue.
