### ISSUE TITLE
[RFC] Should we decommission the Core Triage meeting?

### ISSUE THREAD

**Issue by peternied** [opensearch-project/OpenSearch#14706]
### Is your feature request related to a problem? Please describe

> Check the [OpenSearch Meetup Group](https://www.meetup.com/opensearch/) for the latest schedule and details for joining each meeting. Each component area has its own meetup series: [Search](https://www.meetup.com/opensearch/events/300929493/), [Storage](https://www.meetup.com/opensearch/events/299907409/), [Cluster Manager](https://www.meetup.com/opensearch/events/301082218/), [Indexing](https://www.meetup.com/opensearch/events/301734024/), and [Core](https://www.meetup.com/opensearch/events/301061009/).

_From TRIAGING.md_

In the past two months the Core triage meeting has always triaged down to zero issues and attendance has flagged, from more than 10 participants down to an average of three.  I would attribute this to the five standing triage meetings run for OpenSearch that provide additional time options and different domain experts to consult.

The core triage meeting was created when there was a large backlog of untriaged issues and there were no standing meetings, with todays posture the OpenSearch project seems in very good health and I'd recommend retiring this series at the end of this month.

### Lets collect votes to end the core triage meeting
- 👍 End the core triage meeting series on July 31st
- 👎 Keep running the core triage meetings

**_Voting will close at the end of the 7/24 Triage meeting [2] when a decision will be reached._**

### Additional Details
- [1] https://www.meetup.com/opensearch/events/301175394/

**Comment by andrross** [comment]
I'm in favor of decommissioning the core meeting in favor of the domain-specific meetings. How do we ensure we get 100% coverage on new issues across the different meetings though? Currently each component only looks at a subset of labels and core was functioning as a catch-all.

**Comment by dblock** [comment]
I hear that the component triages do look at issues outside of their component, so the weekly [catch-all triage](https://github.com/opensearch-project/.github/blob/main/TRIAGING.md#issue-triage) is happy to be the catch all for all repos, including core, for the things that do fall through.

**Comment by peternied** [comment]
[Triage - attendees [1](https://github.com/peternied) [2](https://github.com/jed326) [3](https://github.com/reta)]
@peternied Thanks for creating this issue.

**Comment by peternied** [comment]
[Triage - attendees [1](https://github.com/peternied) [2](https://github.com/imvtsl)]
Based on votes, we are going to select `End the core triage meeting series on July 31st`  - Thanks everyone for your input.
