### ISSUE TITLE
Keyword field slowdown while using `IndexOrDocValues`

### ISSUE THREAD

**Issue by harshavamsi** [opensearch-project/OpenSearch#14755]
I was working on a query that contains a terms query on a keyword field like so

```
"query": {
    "bool": {
      "filter": [],
      "must_not": [
        {
          "bool": {
            "filter": [],
            "must": [],
            "must_not": [],
            "should": [
              {
                "terms": {
                  "field1": [
                    "value1"
                  ]
                }
              },
              {
                "terms": {
                  "field2": [
                    "value2"
                  ]
                }
              }
            ]
          }
        }
      ],
      "should": []
    }
  },
```

Since this is a terms query on the keyword field, it naturally delegates to `IndexOrDocValuesQuery`.

**Comment by peternied** [comment]
[Triage - attendees [1](https://github.com/peternied) [2](https://github.com/jed326) [3](https://github.com/reta)]
@harshavamsi Thanks for creating this issue, however, it isn't clear what outcome you'd expect from the ticket.  Please open a new issue with the issue template.  Deferring to search team for final accept/reject decision.
