### ISSUE TITLE
[Feature Request] Build Sort Search Processor and Split Search Processor

### ISSUE THREAD

**Issue by jackiehanyang** [opensearch-project/OpenSearch#14758]
### Is your feature request related to a problem? Please describe

The Machine Learning Inference Processor is designed to improve the ease of using machine learning models for processing ingest/search requests. It utilizes a machine learning model to read from the data and add the prediction outcome to the data being ingested through the ingest pipeline, or return the prediction outcomes along with the search response through the search pipeline. Each ml-commons remote inference includes a pre-process function and a post-process function. The process function, written with a painless script, defines the pre-process and post-process data transformations needed for the ml-commons remote inference use case.

Given that we are on a path to reduce Painless script usage due to its complexity for customers, we introduced a JSONPath dependency to replace the Painless script process functions. However, JSONPath has some functional limitations that cannot fulfill the ml-commons inference processor data transformation requirements. Therefore, we propose introducing two response processors: the sorting response processor and the split response processor, to address the functional limitations of JSONPath.

### Describe the solution you'd like

Similar as [Sort Ingest Processor](https://opensearch.org/docs/latest/ingest-pipelines/processors/sort/#:~:text=The%20sort%20processor%20sorts%20an,input%20is%20not%20an%20array.) and [Split Ingest Processor](https://opensearch.org/docs/latest/ingest-pipelines/processors/split/), we would like to build a `Sort Search Processor` and `Split Search Processor`

### Related component

Search

**Comment by dbwiddis** [comment]
@jackiehanyang are these Response processors? Or do we need both Request and Response processors?
