### ISSUE TITLE
[Feature Request] Support pre-aggregated data in Star Tree

### ISSUE THREAD

**Issue by sarthakaggarwal97** [opensearch-project/OpenSearch#14767]
### Is your feature request related to a problem? Please describe

Coming here from this: https://github.com/opensearch-project/OpenSearch/pull/14512#discussion_r1678850554

There are cases where the users would want to ingest already aggregated data by specifying the `_doc_count` field. This way, during star-tree aggregation, we can account for the number of documents while calculating accurate metrics.

### Describe the solution you'd like

Support for pre-aggregated data with Star Tree

### Related component

Indexing:Performance

### Additional context

 https://opensearch.org/docs/2.4/opensearch/bucket-agg/#account-for-pre-aggregated-data

**Comment by mgodwan** [comment]
[Indexing Triage Meeting 07/22]

@sarthakaggarwal97 Thanks for filing this. Please tag the issue with the release you're targeting this for.

**Comment by bharath-techie** [comment]
https://github.com/opensearch-project/OpenSearch/issues/15288 -- with _doc_count support changes, we should solve this as well. so closing this.
