### ISSUE TITLE
Shard routing awareness seems to be hard constraint even when forced awareness is not enabled

### ISSUE THREAD

**Issue by patelsmit32123** [opensearch-project/OpenSearch#14789]
### Describe the bug

The opensearch documentation says that shard allocation awareness is a soft constraint.
https://opensearch.org/docs/2.0/opensearch/cluster/#advanced-step-6-configure-shard-allocation-awareness-or-forced-awareness

But as per my understanding of the code, it seems to be a hard constraint that if there are 3 zones available and 2 of them already have a shard copy, then it will only allow placement of the 3rd copy on the 3rd zone, for the other two zones which already have a copy, the placement will fail with this decision. I had faced this issue recently in one of our clusters.

https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/cluster/routing/allocation/decider/AwarenessAllocationDecider.java#L224

### Related component

Cluster Manager

### To Reproduce

1. Create a cluster with 1 primary shard and 2 replica shards, with some awareness attribute (A).
2. Place these 3 shard copies on 3 different nodes with different values of A.
3. Remove any node which has replica shard.

The replica shard will remain unassigned

Cluster Settings:
`{
  "persistent": {
    "plugins": {
      "index_state_management": {
        "template_migration": {
          "control": "-1"
        }
      }
    }
  },
  "transient": {
    "cluster": {
      "routing": {
        "allocation": {
          "enable": "all",
          "exclude": {
            "_name": "esdock-databook-opensearch-cluster-phx-bahib-vitoh"
          }
        }
      }
    }
  }
}`

### Expected behavior

The replica shard should get allocated to the other two nodes, if it were a soft constraint

### Additional Details

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**

**Comment by rajiv-kv** [comment]
[Triage - attendees [1](https://github.com/rwali-aws) [2](https://github.com/reta) [3](https://github.com/shiv0408) [4](https://github.com/rajiv-kv)] 
@patelsmit32123  Thanks for creating the issue. Could you please include the Cluster settings of test cluster under steps to reproduce.

**Comment by patelsmit32123** [comment]
@rajiv-kv added the cluster settings, what is the expected behaviour here? I am confused if the documentation is incorrect or the code is not working as expected
