### ISSUE TITLE
Add baseline comparison results to pull requests for performance benchmarks

### ISSUE THREAD

**Issue by rishabh6788** [opensearch-project/OpenSearch#14826]
### Is your feature request related to a problem? Please describe

Continuing from #14553 creating this issue to track progress on adding feature that will also add baseline performance comparison results on the pull request after benchmark run has completed. 

### Describe the solution you'd like

opensearch-benchmark provided out of the box [compare](https://opensearch.org/docs/latest/benchmark/reference/commands/compare/) command that compares the benchmark results between two runs and publishes the results highlighting differences between each operation. 
The idea is to extend the existing workflow (https://github.com/opensearch-project/OpenSearch/pull/14760) to also add the comparison results on the PR once the performance run has completed for the same PR. 

### Related component

Other

**Comment by peternied** [comment]
[Triage - attendees [1](https://github.com/peternied) [2](https://github.com/imvtsl)]
@rishabh6788 Thanks for creating this issue, look forward to seeing a pull request that adds this functionality.

**Comment by rishabh6788** [comment]
All required changes have been merged, the feature is live now. 
Apart from getting performance benchmark numbers, the users now will also see baseline comparison results as well.
