### ISSUE TITLE
Do we really need modules?

### ISSUE THREAD

**Issue by saratvemulapalli** [opensearch-project/OpenSearch#1486]
**Is your feature request related to a problem? Please describe.**
Looking through the code base, I see all modules are plugins but handled separately spread across the code base.
All modules are taken care very similarly as plugins but we have duplicate code for handling plugins and modules.
Ref: https://github.com/opensearch-project/OpenSearch/blob/996d33adb22ac6a523962166f3677f8dc6ac9c1f/server/src/main/java/org/opensearch/plugins/PluginsService.java#L128

**Describe the solution you'd like**
I understand modules are loaded by default where are plugins are optional. 
Can we update the plugin interfaces to take in a load by default parameter and remove the terminology of modules across the code base?

Opening this issue to discuss and understand if there is any history or pieces that might break.

**Comment by saratvemulapalli** [comment]
Tagging @nknize for thoughts.

**Comment by Bukhtawar** [comment]
I think modules are ways to organise non-core features better while plugins on the other hand are customized extensions to functionalities written in either modules or core. Plugin authors are free to extend them in ways without having to worry about the functionality itself.

**Comment by adnapibar** [comment]
> I think modules are ways to organise non-core features better while plugins on the other hand are customized extensions to functionalities written in either modules or core. Plugin authors are free to extend them in ways without having to worry about the functionality itself.
> 
> Modules in general should help in organizing code better and making server leaner. So I definitely see value in retaining modules unless we have a better way around this

+1 

The main idea on this design is that,
- modules are actually core features but may need different permissions, so that is why they are separated. 
- plugins are features that fulfill a specific need for a subset of users. 

The underlying implementation is same for both modules and plugins. However, I think, having the distinction in the code based on the purpose is a good idea.

**Comment by saratvemulapalli** [comment]
Thanks @Bukhtawar @adnapibar , I definitely understand the logical sense of having modules. 
But internally modules are just extending/implementing Plugin class/interfaces. 

But looks we would still prefer having dedicated code for handling modules. 
Thanks for the thoughts!
