### ISSUE TITLE
[BUG] Can't search_after empty value

### ISSUE THREAD

**Issue by bertrandda** [opensearch-project/OpenSearch#1490]
**Describe the bug**
When we list items with two attributes as sorting keys and last item request has null/empty sort value, next request with `search_after` does not work with js clients.
Last item in first request response has sort value `"sort" : [-9223372036854775808, 1635414030931]` but in js max value is 2^53, `search_after` can't send [-9223372036854775808, 1635414030931] (client rounds up `-9223372036854775808` in `-9223372036854776000` number becomes too big for Java). Our js limit workarround was to put number as string in `search_after` -> `["-9223372036854775808", 1635414030931]` but since OpenSearch (or ES7.6) it's not allowed any more.

**To Reproduce**
1. Create 4 items with attributes `created_at` (all set) and `edited_at` (1 set, 3 empty)
2. request with sort by `edited_at` and `created_at`
```
GET user_back/_search
{
  "query": {
    "bool": {
      "must": {
        "bool": {
          "must_not": {
            "exists": {
              "field": "deleted_at"
            }
          }
        }
      }
    }
  },
  "size": 3,
  "sort": [
    {
      "edited_at": "desc"
    },
    {
      "created_at": "desc"
    }
  ]
}
```

Response:
```
{
  "took" : 9,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : {
      "value" : 4,
      "relation" : "eq"
    },
    "max_score" : null,
    "hits" : [
      {
        "_index" : "user_back_1635413448227",
        "_type" : "_doc",
        "_id" : "04834ea6-1af8-4a16-b368-10a1a7cfed9c",
        "_score" : null,
        "_source" : {
          "user_back_id" : "04834ea6-1af8-4a16-b368-10a1a7cfed9c",
          "created_at" : "2021-10-28T09:40:31.510Z",
          "deleted_at" : null,
          "edited_at" : "2021-10-28T09:40:51.509Z",
          "username" : "Rebekah_Block16"
        },
        "sort" : [
          1635414051509,
          1635414031510
        ]
      },
      {
        "_index" : "user_back_1635413448227",
        "_type" : "_doc",
        "_id" : "30ae6fdc-9a10-46bc-9f32-5fd455032f1e",
        "_score" : null,
        "_source" : {
          "user_back_id" : "30ae6fdc-9a10-46bc-9f32-5fd455032f1e",
          "created_at" : "2021-10-28T09:40:32.030Z",
          "deleted_at" : null,
          "edited_at" : null,
          "username" : "Bradley_Heidenreich"
        },
        "sort" : [
          -9223372036854775808,
          1635414032030
        ]
      },
      {
        "_index" : "user_back_1635413448227",
        "_type" : "_doc",
        "_id" : "a0425b67-9cbe-468d-b60d-87483494ae55",
        "_score" : null,
        "_source" : {
          "user_back_id" : "a0425b67-9cbe-468d-b60d-87483494ae55",
          "created_at" : "2021-10-28T09:40:30.931Z",
          "deleted_at" : null,
          "username" : "Shaun_Cartwright80"
        },
        "sort" : [
          -9223372036854775808,
          1635414030931
        ]
      }
    ]
  }
}
```

3. Second request with last item sort in `search_after` (js can't handle `-9223372036854775808` so we change it to `"-9223372036854775808"` throught js client):
```
GET user_back/_search
{
  "query": {
    "bool": {
      "must": {
        "bool": {
          "must_not": {
            "exists": {
              "field": "deleted_at"
            }
          }
        }
      }
    }
  },
  "size": 3,
  "sort": [
    {
      "edited_at": "desc"
    },
    {
      "created_at": "desc"
    }
  ],
  "search_after": [
    "-9223372036854775808",
    1635414030931
  ]
}
```

We receive 3 items with empty `edited_at` not only the last one

**Expected behavior**
Second request returns the fourth item

**Host/Environment (please complete the following information):**
 - OS: macOS (issue also on linux)
 - JS client (tested all compatible versions ES/OpenSearch)

**Comment by adnapibar** [comment]
@bertrandda  It is a problem on JS that it cannot handle 64-bit integer. Having said that, you can try using the `missing` parameter in the sort field and set it to the JS `Number.MIN_SAFE_INTEGER`. 

For instance, you can modify your query to 

```
{
  "query": {
    "bool": {
      "must": {
        "bool": {
          "must_not": {
            "exists": {
              "field": "deleted_at"
            }
          }
        }
      }
    }
  },
  "sort": [
    {
      "edited_at": {
        "order": "desc",
        "missing": -9007199254740991
      }
    },
    {
      "created_at": "desc"
    }
  ],
  "search_after": [
    -9007199254740991,
    1635414032030
  ]
}
```

**Comment by bertrandda** [comment]
It seems to work, `missing` parameter is what I searched. Thanks @adnapibar

**Comment by nedgar** [comment]
Can use `"missing": 0` for date/time fields, or any other 64-bit value that's a valid "milliseconds from Unix epoch" value. Less magic, but should only use 0 if your date/time values are after 1970-01-01 00:00 UTC.
