### ISSUE TITLE
[BUG] Schedule reroute after allocator timeout

### ISSUE THREAD

**Issue by imRishN** [opensearch-project/OpenSearch#14945]
### Describe the bug

When the existing shards allocator would timeout in batch mode, we would need to attempt another reroute such that next iteration is in line. Currently, applyStartedShards, applyFailedShards, async fetch, etc would internally trigger a subsequent reroute from the previous batch. But this behaviour might not be guaranteed.

Related PR comment - https://github.com/opensearch-project/OpenSearch/pull/14848#discussion_r1689072743

### Related component

Other

### Expected behavior

Trigger subsequent reroute on timeout

### Additional Details

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**

**Comment by peternied** [comment]
[Triage - attendees [1](https://github.com/peternied) [2](https://github.com/imvtsl)]
@imRishN Thanks for creating this issue, could you make a pull request to address this or update the description to remove to make it clearer what should be done for another community member?
