### ISSUE TITLE
[BUG] Validate lower limit for Allocator Timeout

### ISSUE THREAD

**Issue by imRishN** [opensearch-project/OpenSearch#14941]
### Describe the bug

With this https://github.com/opensearch-project/OpenSearch/pull/14848 we added cluster settings for allocator's timeout of which default value is `MINUS_ONE`. We would want to add a min limit to this setting such that very small values are not added to these settings.

Related PR Comments - https://github.com/opensearch-project/OpenSearch/pull/14848#discussion_r1687381948

### Related component

Other

### Expected behavior

Min limit for allocator timeout

### Additional Details

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**

**Comment by peternied** [comment]
[Triage - attendees [1](https://github.com/peternied) [2](https://github.com/imvtsl)]
@imRishN Thanks for creating this issue, could you make a pull request to address this or update the description to remove to make it clearer what should be done for another community member?
