### ISSUE TITLE
[Feature Request] extend `constant_keyword` field type usage scope

### ISSUE THREAD

**Issue by kkewwei** [opensearch-project/OpenSearch#14986]
### Is your feature request related to a problem? Please describe

Now `constant_keyword` can only support one value, the usage is as follows:
```
PUT romcom_movies
{
  "mappings" : {
    "properties" : {
      "field1" : {
        "type": "constant_keyword",
        "value" : "value1"
      }
    }
  }
}
```
`field1` can only support one value, In fact, we can extend the count of value, such as add a parameter:
```values:[value1, value2,value3]```, the values is multiple fixed.
There are two benefits:
1. encoding the values,  so we can save the storage(`Byte` can encode 128 values). 
2. In some case, it can speed the search.

There are many usage scenarios, such as field name is `age`, `school`, and `city`. It doesn't affect existing functionality.

### Describe the solution you'd like
add a new `values`, support multiple fixed values.
```
PUT romcom_movies
{
  "mappings" : {
    "properties" : {
      "field1" : {
        "type": "constant_keyword",
        "values" : [value1, value2,value3......]
      }
    }
  }
}
```
If needed, I'm pleasure to implement it.

### Related component

Indexing

**Comment by dblock** [comment]
@kkewwei makes sense! go for it
