### ISSUE TITLE
[Feature Request] Concurrent search support with Derived Fields

### ISSUE THREAD

**Issue by mch2** [opensearch-project/OpenSearch#15007]
### Is your feature request related to a problem? Please describe

Today it is [documented](https://opensearch.org/docs/latest/field-types/supported-field-types/derived/#:~:text=Derived%20fields%20allow%20you%20to,from%20a%20field's%20doc%20values.) that Derived Fields are not supported with concurrent segment search.  While documented there is nothing preventing a user executing concurrent search code paths while using derived field queries or aggs.

### Describe the solution you'd like

Add compatibility, silently ignore concurrent search paths, or at a minimum throw an error.

### Related component

Search:Query Capabilities

### Describe alternatives you've considered

Do nothing...

### Additional context

From - https://github.com/opensearch-project/OpenSearch/pull/14618#issuecomment-2256603381

**Comment by jed326** [comment]
Added `SimplePainlessIT#testSimpleDerivedFieldsQuery` and `SimplePainlessIT#testSimpleDerivedFieldsAgg` in #15072 with concurrent search path muted to help debug.
