### ISSUE TITLE
[BUG] Rolling Upgrade from Elasticsearch Basic to OpenSearch fails in cluster validation

### ISSUE THREAD

**Issue by ronniepg** [opensearch-project/OpenSearch#1502]
Rolling Upgrade from Elasticsearch 7.8.1 Basic (NOT Elasticsearch OSS) to OpenSearch 1.1.0 fails in cluster validation with the following error
`java.lang.IllegalArgumentException: Unknown NamedWriteable [org.opensearch.cluster.metadata.Metadata$Custom][licenses]`

**To Reproduce**
1. Setup Elasticsearch 7.8.1 (or greater) Basic cluster with xpack security disabled.
2. Upgrade from Elasticsearch Basic to OpenSearch using the rolling upgrade option described here - https://opensearch.org/docs/latest/upgrade-to/upgrade-to/#upgrade-to-opensearch

The first node which was upgraded to OpenSearch could not join the existing ElasticSearch cluster. The cluster validation fails with above mentioned error. Complete stack trace available here https://discuss.opendistrocommunity.dev/t/upgrade-from-elasticsearch-basic-to-opensearch/7351/4

**Expected behavior**
The rolling upgrade should work as per suggestions in https://discuss.opendistrocommunity.dev/t/upgrade-from-elasticsearch-basic-to-opensearch/7351/5

**Plugins**
NA

**Screenshots**
NA

**Host/Environment (please complete the following information):**
 - OS: CentOS
 - Version 7

**Additional context**
NA

**Comment by anasalkouz** [comment]
Hi @ronniepg , we do only support the upgrade from ElasticSearch OSS to OpenSearch. [https://opensearch.org/docs/latest/upgrade-to/upgrade-to/#upgrade-paths](https://opensearch.org/docs/latest/upgrade-to/upgrade-to/#upgrade-paths)

**Comment by anasalkouz** [comment]
Closing the issue. feel free to re-open if you have other thoughts.
