### ISSUE TITLE
[Pull Request Checks] Migrate pull request checks into a jenkinsfile

### ISSUE THREAD

**Issue by peternied** [opensearch-project/OpenSearch#1504]
Combine gradle precommit and checks into a single workflow.  Then switch the jenkins job to use this file so pull request configuration is managed in this repository.

There is also room for improvement as the `gradle precommit` check can fail and when this happens the more intensive `gradle check` will also fail and maybe not provide useful results.  Maybe there is a way to reduce resource usage or provide faster results.

**Comment by dblock** [comment]
The Jenkinsfile could live in this repo, too.

**Comment by peterzhuamazon** [comment]
Before we can resolve the issue where PR builder is able to run on pipeline this is not solvable at this point https://github.com/opensearch-project/opensearch-build/issues/851

**Comment by peterzhuamazon** [comment]
I dont want to introduce more issues by using precommit to trigger gradle check directly in freestyle.

**Comment by minalsha** [comment]
Please reopen if this issue still persists. We have public Jenkins now and seems this should have been resolved. Thanks
