### ISSUE TITLE
[Feature Request] Trying to reproduce https://github.com/opensearch-project/OpenSearch/issues/14007

### ISSUE THREAD

**Issue by msfroh** [opensearch-project/OpenSearch#15044]
### Is your feature request related to a problem? Please describe

Trying to reproduce https://github.com/opensearch-project/OpenSearch/issues/14007

### Describe the solution you'd like

Trying to reproduce https://github.com/opensearch-project/OpenSearch/issues/14007

### Related component

ShardManagement:Placement

**Comment by dblock** [comment]
Catch All Triage - [1](https://github.com/dblock), [2](https://github.com/krisfreedain), [3](https://github.com/andrross)
