### ISSUE TITLE
[META] Snapshot V2 - Scaling Snapshot Operations

### ISSUE THREAD

**Issue by anshu1106** [opensearch-project/OpenSearch#15084]
### Please describe the end goal of this project

The goal of this project is to make snapshot operations more deterministic and scale independent of the number of shards in the cluster. 

### Supporting References

-  https://github.com/opensearch-project/OpenSearch/issues/15083

### Issues

- https://github.com/opensearch-project/OpenSearch/issues/15123
- https://github.com/opensearch-project/OpenSearch/issues/15255
- https://github.com/opensearch-project/OpenSearch/issues/15316
- https://github.com/opensearch-project/OpenSearch/issues/15459
- https://github.com/opensearch-project/OpenSearch/issues/15461
- https://github.com/opensearch-project/OpenSearch/issues/15466
- https://github.com/opensearch-project/OpenSearch/issues/15463

### Bugs
- https://github.com/opensearch-project/OpenSearch/issues/15516
- https://github.com/opensearch-project/OpenSearch/pull/15602

### Related component

Storage:Snapshots

**Comment by dblock** [comment]
[Catch All Triage - [1](https://github.com/andrross), [2](https://github.com/dblock), [3](https://github.com/AmiStrn), [4](https://github.com/reta), [5](https://github.com/finnegancarroll)]
