### ISSUE TITLE
[BUG] [Star tree] Nodes with -1 as dimension value gets overriden with star node

### ISSUE THREAD

**Issue by bharath-techie** [opensearch-project/OpenSearch#15097]
### Describe the bug

Documents which has dimensions as '-1' , results in getting overriden with star nodes as star nodes are assigned '-1' when constructing star tree.

```
[-1,1]
[1,1]
[1,1]

Map<Long, InMemoryTreeNode> children = constructNonStarNodes(startDocId, endDocId, childDimensionId);
children.put((long) ALL, constructStarNode(startDocId, endDocId, childDimensionId));

ALL here is '-1'
```

### Related component

Indexing:Performance

### To Reproduce

Add documents with -1 as dimensions when creating star tree

### Expected behavior

Documents with -1, null and any values in Long range should work with star tree

### Additional Details

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**

**Comment by mgodwan** [comment]
Lets get rid of

```
    public static final int ALL = -1;
```

in TreeNode. That would ensure we have a good rewrite.

Having a starChild separately should help

**Comment by bharath-techie** [comment]
Fixed as part of https://github.com/opensearch-project/OpenSearch/pull/14809
