### ISSUE TITLE
[Flaky Test] Fix unit test MasterServiceTests.testClusterStateUpdateLoggingWithDebugEnabled 

### ISSUE THREAD

**Issue by sumitasr** [opensearch-project/OpenSearch#15117]
### Describe the bug

Reported in https://github.com/opensearch-project/OpenSearch/pull/15053#issuecomment-2264145434
https://github.com/opensearch-project/OpenSearch/pull/14464#issuecomment-2263761642

### Related component

Cluster Manager

### To Reproduce

Run unit test locally for 5000 iterations

### Expected behavior

N/A

**Comment by sumitasr** [comment]
Looking into it

**Comment by dblock** [comment]
@sumitasr any of the linked PRs fixed this? Close?

**Comment by dblock** [comment]
[Catch All Triage - [1](https://github.com/andrross), [2](https://github.com/dblock), [3](https://github.com/AmiStrn), [4](https://github.com/reta), [5](https://github.com/finnegancarroll)]

**Comment by sumitasr** [comment]
> @sumitasr any of the linked PRs fixed this? Close?

Tracking fix closure here https://github.com/opensearch-project/OpenSearch/pull/15204

**Comment by sumitasr** [comment]
Fix is merged - https://github.com/opensearch-project/OpenSearch/pull/15204
