### ISSUE TITLE
Improve logging for failures due to client missing certs

### ISSUE THREAD

**Issue by setiah** [opensearch-project/OpenSearch#1514]
**Describe the issue**
When client does not trust the self-signed certificates used on the server side, it fails to connect to security enabled OpenSearch with error https://gist.github.com/setiah/ecd58925379bf711a207196fecc4d10d

This error is not helpful. The proposal is to improve the messaging to provide informative and actionable messaging to user around the potential configuration issue and what they could do to fix this.

Related to #1393

**Comment by owaiskazi19** [comment]
@ryanbogan I see https://github.com/opensearch-project/OpenSearch/pull/1602 is merged. Can we close this issue?
