### ISSUE TITLE
[Feature Request] Changelog verifier should fail if CHANGELOG-3.0.MD is modified and a backport label is applied.

### ISSUE THREAD

**Issue by jed326** [opensearch-project/OpenSearch#15155]
### Is your feature request related to a problem? Please describe

Had an issue earlier where a changelog entry was added to 3.0 and also backported to 2.x: https://github.com/opensearch-project/OpenSearch/pull/15150

This means the changelog for 3.0 was wrong and will probably break auto backport for other PRs. We should be able to add an automated check to the changelog verifier to catch this case.

### Describe the solution you'd like

Suggested by @andrross here: https://github.com/opensearch-project/OpenSearch/pull/15150#issuecomment-2274321630

### Related component

Build

**Comment by jed326** [comment]
Self assigning for now but if anyone else is interested in picking this up feel free

**Comment by sandeshkr419** [comment]
To add on to the discussion https://github.com/opensearch-project/OpenSearch/pull/15150#issuecomment-2274321630 - Let's also enforce in changelog verifier CI that `>breaking` label and `backport-2.x` label do not also exist together - this bubbles up that that no breaking changes go to 2.x as well.
