### ISSUE TITLE
[Concurrent Segment Search] Provide index level setting for controlling slice count at index level

### ISSUE THREAD

**Issue by sohami** [opensearch-project/OpenSearch#15268]
### Is your feature request related to a problem? Please describe

Currently in concurrent segment search we have dynamic slice count setting at cluster level which users can use to control per query parallelism. However, we don't have control over per index level which can be useful for setup like hot indices hosted on instance type with more vCPU vs searchable snapshot indices or warm indices on search nodes which have fewer vCPUs. We would like to control the slice count differently for these different indices type hosted on different instance configurations.

### Describe the solution you'd like

Introduce an index level setting to control the slice count for search requests

### Related component

Search:Performance

### Describe alternatives you've considered

N/A

**Comment by Gankris96** [comment]
Thanks @sohami for creating this issue.
