### ISSUE TITLE
[BUG] <analysis-phonetic is no longer usable for OpenSearch 2.16 >

### ISSUE THREAD

**Issue by hafnerkai** [opensearch-project/OpenSearch#15272]
### Describe the bug

After updating from 2.15 to 2.16 today, I was told that analysis-phonetic is no longer usable as it is only available up to version 2.15. 

To be able to start my OpenSearch at all I had to uninstall the plugin, only then could it be started again. 

### Related component

Plugins

### To Reproduce

1. run the update from 2.15 to 2.16 and have installed the plugin. 

2. after completing the update, the service will not start because the plugin cannot be used for version 2.16. 

3. the service can only be started again without errors after uninstalling the plugin. 

### Expected behavior

Since I need the plugin for my systems, the expected behavior is that when there is an update to a new version that the plugins are either adapted or the update is created so that the plugins still work for the beginning or you are informed before running the update that the following plugins are no longer usable after the update.

**Comment by dblock** [comment]
@hafnerkai was this a plugin that was installed in 2.15 by default and somehow was removed, or is it something you installed yourself in 2.15?
