### ISSUE TITLE
Rename field_masking_span to span_field_masking

### ISSUE THREAD

**Issue by xuezhou25** [opensearch-project/OpenSearch#1531]
**Is your feature request related to a problem? Please describe.**
 According to customer confusion from this issue [#1299](https://github.com/opensearch-project/OpenSearch/issues/1299)
In Span Queries group, queries are like `span_containing` `span_first` `span_within` etc. Currently the `field_masking_span` query is the only one that end with `_span` instead of starting with `span_`.

**Describe the solution you'd like**
Rename `field_masking_span` to `span_field_masking`.

**Describe alternatives you've considered**

**Additional context**
https://github.com/opensearch-project/OpenSearch/blob/996d33adb22ac6a523962166f3677f8dc6ac9c1f/server/src/main/java/org/opensearch/index/query/QueryBuilders.java#L413

**Comment by kartg** [comment]
PR merged. Closing this issue.
