### ISSUE TITLE
[Snapshot V2] Integrate clone snapshot flow with pinned timestamp

### ISSUE THREAD

**Issue by anshu1106** [opensearch-project/OpenSearch#15316]
### Is your feature request related to a problem? Please describe

- The snapshots created with pinned timestamp need to pin the same timestamp for the cloned snapshot.
More details can be found in the [RFC](https://github.com/opensearch-project/OpenSearch/issues/15083) 

### Related component

Storage:Snapshots

### Describe alternatives you've considered

NA

### Additional context

NA

**Comment by sachinpkale** [comment]
@anshu1106 Can you please add more details on the approach?
