### ISSUE TITLE
[BUG] Suspicious usage of Map in ActionModule line 1205

### ISSUE THREAD

**Issue by dk2k** [opensearch-project/OpenSearch#15388]
### Describe the bug

Passed value has type Route, but declaration is Map<NamedRoute, RestSendToExtensionAction>
NamedRoute is subtype of Route
But there is at least one more subtype - ReplacedRoute
It's about type safety

### Related component

Other

### Expected behavior

-

### Additional Details

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**

**Comment by dbwiddis** [comment]
Extensions should only be sending `NamedRoute`.  I'll look into this and see if there's anywhere we can enforce that type.

**Comment by dbwiddis** [comment]
Interestingly, that method is never called anywhere (including tests).

Given that it's API I don't think we can change the argument type but should be easy to type check and return null if it's the wrong type.
