### ISSUE TITLE
[BUG] Couple of cases of infinite recursion

### ISSUE THREAD

**Issue by dk2k** [opensearch-project/OpenSearch#15387]
### Describe the bug

Methods getFloatVectorValues(String field) and getByteVectorValues(String field) in TranslogLeafReader class

### Related component

Indexing

### Expected behavior

-

### Additional Details

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**

**Comment by dbwiddis** [comment]
https://github.com/opensearch-project/OpenSearch/blob/6152afeef3ceb3fe4f18f6be2d55ac60256bc2db/server/src/main/java/org/opensearch/index/engine/TranslogLeafReader.java#L266-L274

Introduced in https://github.com/opensearch-project/OpenSearch/pull/6078 but the diff shows something similar prior to that:

https://github.com/opensearch-project/OpenSearch/blob/c557f2717ad45627cacd88e8243893dd84a56623/server/src/main/java/org/opensearch/index/engine/TranslogLeafReader.java#L257-L260

That was introduced in https://github.com/opensearch-project/OpenSearch/pull/1109

It's not clear what it should be.  @nknize any idea?

**Comment by dblock** [comment]
I would at least raise a not implemented exception here to begin with, I imagine all tests will pass, this code is obviously not executed.
