### ISSUE TITLE
[Feature Request] Support Scaled Floats with Star Tree

### ISSUE THREAD

**Issue by sarthakaggarwal97** [opensearch-project/OpenSearch#15443]
### Is your feature request related to a problem? Please describe

With the support of numeric types in Star Tree, it is important to extend the support to scaled floats (which is also a numeric type, but available via [Mapping Extras](https://github.com/opensearch-project/OpenSearch/blob/main/modules/mapper-extras/src/main/java/org/opensearch/index/mapper/MapperExtrasModulePlugin.java#L46) module)

More information on the documentation: https://opensearch.org/docs/latest/field-types/supported-field-types/numeric/#scaled-float-field-type

### Describe the solution you'd like

Support for scaled floats in Star Tree

### Related component

Search:Aggregations

**Comment by sandeshkr419** [comment]
Do are we targeting this for 2.17?

**Comment by sarthakaggarwal97** [comment]
@sandeshkr419 yes we are targeting 2.17
