### ISSUE TITLE
[Snapshot V2] Add support for remote store files cleanup

### ISSUE THREAD

**Issue by anshu1106** [opensearch-project/OpenSearch#15466]
### Is your feature request related to a problem? Please describe

As part of shallow snapshot delete flow, we need to handle deletion of remote store files for deleted indices. 

### Describe the solution you'd like

There is a logic in place to handle deletion of remote store files for indices that have been deleted but are part of the snapshot. The existing logic looks at snapshot shard metadata file to figure out the remote store path strategy and algorithm for deletion. Since snapshot v2 is not writing per shard snapshot metadata file in the snapshot repo, it needs to get the path from index metadata.

### Related component

Storage:Snapshots

**Comment by shourya035** [comment]
@anshu1106 Please add the estimate and the planned release version
