### ISSUE TITLE
[BUG] Construct StarTreeMetadata prior to Writes

### ISSUE THREAD

**Issue by sarthakaggarwal97** [opensearch-project/OpenSearch#15467]
### Describe the bug

Currently, we rely on a bunch of parameters to construct the star tree metadata. Instead, to improve readability, we can construct the StarTreeMetadata, and use getters to write it

### Related component

Indexing:Performance

### To Reproduce

N/A

### Expected behavior

Construct StarTreeMetadata in BaseStarTreeBuilder to improve readability

### Additional Details

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**

**Comment by vikasvb90** [comment]
[Indexing Triage - 09/02] 
Thanks @sarthakaggarwal97 for raising this! Can you please add more details around what you mean by improving the readability and how this falls under the category of a bug? 
It would also be good if you can add some code pointers as well for better understanding of the issue.

**Comment by bharath-techie** [comment]
Marking this as closed , @sarthakaggarwal97 can provide more details as requested
