### ISSUE TITLE
[BUG] detect-breaking-change must be required to pass for backport changes

### ISSUE THREAD

**Issue by jainankitk** [opensearch-project/OpenSearch#15484]
### Describe the bug

Currently, detect-breaking-change is not required for merging the backported the changes

### Related component

Build

### Expected behavior

detect-breaking-change must be passing to avoid mistakes like https://github.com/opensearch-project/OpenSearch/pull/15473

### Additional Details

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**

**Comment by reta** [comment]
@gaiksaya @peterzhuamazon may need your help here, as always, the check for breaking changes is only run against `2.x` branch but not `main`. Could if configure it to be mandatory for 2.x only? Thank you.

**Comment by gaiksaya** [comment]
Hi @reta I do not see this check mandatory in the required workflows (repo settings).
This workflow needs to be removed from 2.x branch https://github.com/opensearch-project/OpenSearch/blob/2.x/.github/workflows/detect-breaking-change.yml

**Comment by reta** [comment]
> This workflow needs to be removed from 2.x branch https://github.com/opensearch-project/OpenSearch/blob/2.x/.github/workflows/detect-breaking-change.yml

If we remove it, it won't be running, right? We need it to be mandatory for 2.x (but not main)

**Comment by gaiksaya** [comment]
Sorry for the confusion. I meant needs to be removed from main branch https://github.com/opensearch-project/OpenSearch/blob/main/.github/workflows/detect-breaking-change.yml
However, I see that `main` branch is ignored anyway in the above workflow https://github.com/opensearch-project/OpenSearch/blob/main/.github/workflows/detect-breaking-change.yml#L4-L5
So it should not be running. The PR mentioned in the issue description has 2.x base branch and the workflow did run which is correct.

**Comment by reta** [comment]
Got it, thank you, could we make it required?

**Comment by jainankitk** [comment]
@gaiksaya - Yes, the workflow is running as expected. We just need it to be required check for backport PRs to disable squash and merge in case it is failing!

**Comment by gaiksaya** [comment]
> @gaiksaya - Yes, the workflow is running as expected. We just need it to be required check for backport PRs to disable squash and merge in case it is failing!

Sorry did not get you. Why would we disable for backport PRs if the base branch is 2.x?
Won't that defy the purpose of breaking changes not to be included in minor versions?

**Comment by jainankitk** [comment]
> > @gaiksaya - Yes, the workflow is running as expected. We just need it to be required check for backport PRs to disable squash and merge in case it is failing!
> 
> Sorry did not get you. Why would we disable for backport PRs if the base branch is 2.x? Won't that defy the purpose of breaking changes not to be included in minor versions?

Probably you misread, [detect-breaking-change](https://github.com/opensearch-project/OpenSearch/blob/main/.github/workflows/detect-breaking-change.yml) should disable "squash/merge option" if it fails for backport PR

**Comment by gaiksaya** [comment]
I see! I don't think that is possible as pull request merge options are not branch but more of repository based.
<img width="809" alt="image" src="https://github.com/user-attachments/assets/d428650b-2137-490f-96d6-7579b7917ffa">

**Comment by jainankitk** [comment]
![Screenshot 2024-08-28 at 2 28 55 PM](https://github.com/user-attachments/assets/659af9d8-9f14-4bcc-b48b-b9656164ed92)

**Comment by peterzhuamazon** [comment]
Since @gaiksaya is already taking care of it, I will let her finish the config.
Adding the check to be required for any backport branch per branch rule should be the right setup.
I dont think we need to specifically create a rule for 2.x tho.

**Comment by gaiksaya** [comment]
It's not @peterzhuamazon Looks like if you had 2.x the `*` rule would remove 2.x from its list.
I added new rule for 2.x with exact same rules as `*` and additional `detect-breaking-change` as required workflow
![image](https://github.com/user-attachments/assets/f1d8fe51-3c60-4f79-9c9b-2ff536c7f244)

**Comment by jainankitk** [comment]
> @jainankitk @reta Please verify. Looking at #15485 looks like it is applied now.

@gaiksaya - nice, thanks!

**Comment by jainankitk** [comment]
Fixed now, closing this issue!

**Comment by kaushalmahi12** [comment]
This issue makes sense though at repo level but this is not applicable in context of the mentioned PR 
The mentioned PR should not be breaking in my opinion because of the following

* The enum has been moved from one package to another package which only affects the implicit serialisation of enum objects since it depends on the fully qualified classpath.
* Now given we are not serialising the ResourceType objects it should be fine and this should not break anything

on a object level this library does the following
* Check binary compatibility: This basically checks there is no illegal changes in access modifiers, class heirarchy
* Check object serialisability: This is to ensure that all `java.io.Serialisable` objects do not break java object serialisability in two versions

Key classes in the library to understand it
* **JApiCmpWorkerAction** (Main class that starts the actual work in the `run` method)
* **JarArchiveComparator**
* **JavaObjectSerializationCompatibility**

here are few snaps from the gradle plugin code

```
private void checkJavaObjectSerializationCompatibility(List<JApiClass> jApiClasses) {
		JavaObjectSerializationCompatibility javaObjectSerializationCompatibility = new JavaObjectSerializationCompatibility();
		javaObjectSerializationCompatibility.evaluate(jApiClasses);
}


List<JApiClass> compareClassLists(JarArchiveComparatorOptions options, List<CtClass> oldClasses, List<CtClass> newClasses) {
		ClassesComparator classesComparator = new ClassesComparator(this, options);
		classesComparator.compare(oldClasses, newClasses);
		List<JApiClass> classList = classesComparator.getClasses();
		if (LOGGER.isLoggable(Level.FINE)) {
			for (JApiClass jApiClass : classList) {
				LOGGER.fine(jApiClass.toString());
			}
		}
		checkBinaryCompatibility(classList);
		checkJavaObjectSerializationCompatibility(classList);
		OutputFilter.sortClassesAndMethods(classList);
		return classList;
	}
```
**JavaObjectSerializationCompatibility**
```
private JApiJavaObjectSerializationCompatibility.JApiJavaObjectSerializationChangeStatus checkChanges(JApiClass jApiClass) {
		JApiJavaObjectSerializationCompatibility.JApiJavaObjectSerializationChangeStatus state = JApiJavaObjectSerializationCompatibility.JApiJavaObjectSerializationChangeStatus.SERIALIZABLE_COMPATIBLE;
		if (jApiClass.getChangeStatus() == JApiChangeStatus.REMOVED) {===========> This is causing the issue!!!!!!!!!
			return JApiJavaObjectSerializationCompatibility.JApiJavaObjectSerializationChangeStatus.SERIALIZABLE_INCOMPATIBLE_CLASS_REMOVED;
		}
		state = checkChangesForClassType(jApiClass, state);
		if (state != JApiJavaObjectSerializationCompatibility.JApiJavaObjectSerializationChangeStatus.SERIALIZABLE_COMPATIBLE) {
			return state;
		}
		state = checkChangesForSuperclass(jApiClass, state);
		if (state != JApiJavaObjectSerializationCompatibility.JApiJavaObjectSerializationChangeStatus.SERIALIZABLE_COMPATIBLE) {
			return state;
		}
		state = checkChangesForFields(jApiClass, state);
		if (state != JApiJavaObjectSerializationCompatibility.JApiJavaObjectSerializationChangeStatus.SERIALIZABLE_COMPATIBLE) {
			return state;
		}
		state = checkChangesForInterfaces(jApiClass, state);
		return state;
}
```

```
private static boolean isCtClassSerializable(JarArchiveComparatorOptions options, CtClass clazz, JarArchiveComparator jarArchiveComparator) {
		ClassPool pool = clazz.getClassPool();
		try {
			return clazz.subtypeOf(pool.get("java.io.Serializable"));
		} catch (NotFoundException e) {
			if (options.getIgnoreMissingClasses().ignoreClass(e.getMessage())) {
				return false;
			} else {
				throw JApiCmpException.forClassLoading(e, clazz.getName(), jarArchiveComparator);
			}
		}
	}
```



What do you think @jainankitk @peterzhuamazon @gaiksaya @reta ?

**Comment by reta** [comment]
Thanks a mill @gaiksaya !
