### ISSUE TITLE
[BUG] Async Translog Durability restriction is not being honored when indices are created through templates

### ISSUE THREAD

**Issue by shourya035** [opensearch-project/OpenSearch#15493]
### Describe the bug

Today, when we set the `cluster.remote_store.index.restrict.async-durability` setting, indices cannot be created with the `index.translog.durability` setting as `async`. However, this behavior is bypassed when the index is created through index templates. 

### Related component

Storage:Remote

### To Reproduce

- Create a cluster with `cluster.remote_store.index.restrict.async-durability` set to `true`
- Create an index template with the following setting:
```
"index.translog.durability": "async"
```
- Index would get created with Async translog durability

### Expected behavior

Index template creation should be blocked in this case

### Additional Details

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**

**Comment by ashking94** [comment]
Closing this issue as the reference PR has been merged already.
[Triage - attendees [1](https://github.com/ashking94) [2](https://github.com/linuxpi) [3](https://github.com/ashking94) [4](https://github.com/sachinpkale) [5](https://github.com/skumawat2025)]
