### ISSUE TITLE
[BUG] [SnapshotV2] Create API respond with snapshot info details with `wait_for_completion` set to false

### ISSUE THREAD

**Issue by anshu1106** [opensearch-project/OpenSearch#15516]
### Describe the bug

With current implementation of shallow snapshot v2, the create api respond with snapshot info details irrespective of the value set for wait_for_completion in the request.

**Expected Response**

For shallow snapshots v2, if wait_for_completion=false, the api response should be

```
{
  "accepted" : true
}
```
if wait_for_completion=true, the api response should be
```
{
  "snapshot" : {
    "snapshot" : "my_snapshot_3",
    "uuid" : "URJArTYOTOmIFtbv6mbSXQ",
    "version_id" : 137217827,
    "version" : "3.0.0",
    "remote_store_index_shallow_copy" : true,
    "pinned_timestamp" : 1724855317025,
    "indices" : [
      "my-index-1"
    ],
    "data_streams" : [ ],
    "include_global_state" : true,
    "state" : "SUCCESS",
    "start_time" : "2024-08-28T14:28:37.025Z",
    "start_time_in_millis" : 1724855317025,
    "end_time" : "2024-08-28T14:28:37.026Z",
    "end_time_in_millis" : 1724855317026,
    "duration_in_millis" : 1,
    "failures" : [ ],
    "shards" : {
      "total" : 1,
      "failed" : 0,
      "successful" : 1
    }
  }
}
```

### Related component

Storage:Snapshots

### Expected behavior

NA

### Additional Details

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**

**Comment by shourya035** [comment]
@anshu1106 If this is fixed, can you add the corresponding PR and close this issue?
