### ISSUE TITLE
[BUG] Escaped wildcard character in wildcard query not handled correctly

### ISSUE THREAD

**Issue by HUSTERGS** [opensearch-project/OpenSearch#15555]
### Describe the bug

When use wildcard query on wildcard field, raw `*` (and maybe include raw `?`), is not handled correctly, while the same wildcard query can work well on keyword field. Possibly the escape logic is not implemented in `opensearch/index/mapper/WildcardFieldMapper.java`.

### Related component

Search

### To Reproduce

1. Create a simple index containing both wildcard and keyword type
      ```
      PUT escape_index
      {
        "mappings": {
          "properties": {
            "wild": {
              "type": "wildcard",
              "fields": {
                "keyword": {
                  "type": "keyword"
                }
              }
            }
          }
        }
      }
      ```
2. Insert data with raw `*`
      ```
      POST escape_index/_doc
      {
        "wild": "* test *"
      }
      ```
3. search on both field with the same wildcard query
    **Search on KEYWORD type:**
      ```
      GET escape_index/_search
      {
        "query": {
          "wildcard": {
            "wild.keyword": {
              "value": "\\**"
            }
          }
        }
      }
      ```
    **Result:**
    ```
    {
      "took": 2,
      "timed_out": false,
      "_shards": {
        "total": 2,
        "successful": 2,
        "skipped": 0,
        "failed": 0
      },
      "hits": {
        "total": {
          "value": 1,
          "relation": "eq"
        },
        "max_score": 1,
        "hits": [
          {
            "_index": "escape_index",
            "_id": "xMi6opEB80UGmJnvgJSB",
            "_score": 1,
            "_source": {
              "wild": "* test *"
            }
          }
        ]
      }
    }
    ```
    **Search on WILDCARD type**
      ```
      GET escape_index/_search
      {
        "query": {
          "wildcard": {
            "wild": {
              "value": "\\**"
            }
          }
        }
      }
      ```
    **Result:**
    ```
    {
      "took": 1,
      "timed_out": false,
      "_shards": {
        "total": 2,
        "successful": 2,
        "skipped": 0,
        "failed": 0
      },
      "hits": {
        "total": {
          "value": 0,
          "relation": "eq"
        },
        "max_score": null,
        "hits": []
      }
    }
    ```

### Expected behavior

get the correct results when wildcard query contains raw `*` and `?` characters

**Comment by msfroh** [comment]
That sounds like bug!

In particular, the methods [`findNonWildcardSequence`](https://github.com/opensearch-project/OpenSearch/blob/b71e547e938876c2cec9fcc0328ffbd6b4a50db6/server/src/main/java/org/opensearch/index/mapper/WildcardFieldMapper.java#L522-L530) and [`getNonWildcardSequence`](https://github.com/opensearch-project/OpenSearch/blob/b71e547e938876c2cec9fcc0328ffbd6b4a50db6/server/src/main/java/org/opensearch/index/mapper/WildcardFieldMapper.java#L511-L520) just scan through characters, splitting on `?` or `*`. They don't check if those characters are escaped.

@HUSTERGS, are you willing to fix those methods? If not, I can take care of it (but probably not in time for the 2.17 release, which we expect to freeze today/tomorrow).

**Comment by HUSTERGS** [comment]
OF COURSE! 
bugfix is here #15737. And the original implementation cannot handle empty wildcard query strings, which will cause `String index out of range` on https://github.com/opensearch-project/OpenSearch/blob/19356506f3eeae30031536288793662caf05bf65/server/src/main/java/org/opensearch/index/mapper/WildcardFieldMapper.java#L479

So I add a simple shortcut at the beginning of `getRequiredNGrams` to fix it all together
