### ISSUE TITLE
Replace or remove the "slave" terminology used in a test data

### ISSUE THREAD

**Issue by tlfeng** [opensearch-project/OpenSearch#1556]
**Is your feature request related to a problem? Please describe.**
Replace or remove the non-inclusive terminology from the code base.

**Describe the solution you'd like**
There is only 1 usage in the code base that can be replaced or removed, which is a test data:
https://github.com/opensearch-project/OpenSearch/blob/15e9f137622d878b79103df8f82d78d782b686a1/modules/mapper-extras/src/test/resources/org/opensearch/index/mapper/metricbeat-6.0.template.json#L4601

Document from Elatic that explains the fields in the template: https://www.elastic.co/guide/en/beats/metricbeat/7.10/exported-fields-redis.html

**Describe alternatives you've considered**
None.

**Additional context**
Related issue #472

**Comment by Rishikesh1159** [comment]
I will look into this.

**Comment by kartg** [comment]
Change merged, backport pending. Leaving this issue open until that is complete.
