### ISSUE TITLE
[BUG] terms query on wildcard field returns wrong result

### ISSUE THREAD

**Issue by HUSTERGS** [opensearch-project/OpenSearch#15571]
### Describe the bug

when apply terms query on wildcard field, the result is not correct

### Related component

Search

### To Reproduce

1. Create a simple index contains wildcard field
    ```
    PUT terms_query_index
    {
      "mappings": {
        "properties": {
          "wild": {
            "type": "wildcard"
          }
        }
      }
    }
    ```
3. Insert data
    ```
    POST terms_query_index/_doc
    {
      "wild": "term"
    }
    ```
5. Search wildcard field with terms query
    ```
    GET terms_query_index/_search
    {
      "query": {
        "terms": {
            "wild": ["term"]
        }
      }
    }
    ```
    **Search Result:**
    ```
    {
        "took": 37,
        "timed_out": false,
        "_shards": {
            "total": 1,
            "successful": 1,
            "skipped": 0,
            "failed": 0
        },
        "hits": {
            "total": {
                "value": 0,
                "relation": "eq"
            },
            "max_score": null,
            "hits": []
        }
    }
    ```

### Expected behavior

the terms query should return the inserted data, instead of nothing

**Comment by dblock** [comment]
@HUSTERGS thanks for reporting this. Want to try and implement a [YAML REST test](https://github.com/opensearch-project/OpenSearch/blob/main/TESTING.md#testing-the-rest-layer) for this?

**Comment by HUSTERGS** [comment]
bugfix and YAML REST test is here #15607

> @HUSTERGS thanks for reporting this. Want to try and implement a [YAML REST test](https://github.com/opensearch-project/OpenSearch/blob/main/TESTING.md#testing-the-rest-layer) for this?
