### ISSUE TITLE
Integ test framework should allow to create multiple clusters

### ISSUE THREAD

**Issue by sachinpkale** [opensearch-project/OpenSearch#15581]
### Is your feature request related to a problem? Please describe

https://github.com/opensearch-project/OpenSearch/pull/15462#discussion_r1740832376

### Describe the solution you'd like

https://github.com/opensearch-project/OpenSearch/pull/15462#discussion_r1740832376

### Related component

Other

**Comment by mgodwan** [comment]
This should already be possible from a framework perspective. 

https://github.com/opensearch-project/OpenSearch/blob/9f814797d0fe57457359a1f8a1b222cea80dc003/test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java#L2012-L2081


Following is an example to create 3 clusters which I had tried in the past for some local verification:

```
    private InternalTestCluster[] clusters;
    
    @Before
    public void setupClusters() throws Exception {
        clusters = new InternalTestCluster[3];
        clusters[0] = (InternalTestCluster) buildTestCluster(Scope.TEST, randomLong());
        clusters[1] = (InternalTestCluster) buildTestCluster(Scope.TEST, randomLong());
        clusters[2] = (InternalTestCluster) buildTestCluster(Scope.TEST, randomLong());
    }

    @After
    public void teardownClusters() throws Exception {
        for (InternalTestCluster testCluster: clusters) {
            for (String nodeName : testCluster.getNodeNames()) {
                testCluster.getNode(nodeName).close();
            }
            testCluster.afterTest();
            testCluster.close();
        }
    }
```

**Comment by andrross** [comment]
[Catch All Triage - [1](https://github.com/AmiStrn), [2](https://github.com/mch2), [3](https://github.com/andrross)]

@sachinpkale Can you follow up if @mgodwan's example will solve your issue?
