### ISSUE TITLE
[BUG] Flaky 'org.opensearch.search.approximate.ApproximatePointRangeQueryTests.testApproximateRangeShortCircuit' test

### ISSUE THREAD

**Issue by bharath-techie** [opensearch-project/OpenSearch#15600]
### Describe the bug

https://build.ci.opensearch.org/job/gradle-check/46344/
https://build.ci.opensearch.org/job/gradle-check/46340/
https://build.ci.opensearch.org/job/gradle-check/46333/

Many gradle builds are failing

### Related component

Search

### Expected behavior

Test must pass

### Additional Details

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**

**Comment by mgodwan** [comment]
Looks like the change is related to this PR https://github.com/opensearch-project/OpenSearch/issues/13788

**Comment by Bukhtawar** [comment]
Another failure on this PR https://github.com/opensearch-project/OpenSearch/pull/15218

**Comment by Bukhtawar** [comment]
Should we revert the commit to unblock commits for the 2.17 cut?

**Comment by mgodwan** [comment]
@harshavamsi Could you please look into fixing the underlying cause?

**Comment by mch2** [comment]
related fix https://github.com/opensearch-project/OpenSearch/pull/15590
