### ISSUE TITLE
[BUG] SharedClusterSnapshotRestoreIT.testSnapshotCanceledOnRemovedShard (Random test failure)

### ISSUE THREAD

**Issue by CEHENKLE** [opensearch-project/OpenSearch#1562]
Describe the bug
Random test failure. :( Please dig in and figure out what went wrong :(

[https://ci.opensearch.org/logs/ci/workflow/OpenSearch_CI/PR_Checks/Gradle_Check/gradle_check_736_reports.zip](https://ci.opensearch.org/logs/ci/workflow/OpenSearch_CI/PR_Checks/Gradle_Check/gradle_check_736_reports.zip)

**Comment by adnapibar** [comment]
This issue is over a year old, it hasn't reoccured and locally not reproducible.
