### ISSUE TITLE
[BUG] MinimumMasterNodesIT.testThreeNodesNoMasterBlock (random test failure)

### ISSUE THREAD

**Issue by CEHENKLE** [opensearch-project/OpenSearch#1563]
**Describe the bug**
Random test failure :(  Please dig in and figure out what went wrong :(

[https://fork-jenkins.searchservices.aws.dev/job/OpenSearch_CI/job/PR_Checks/job/Gradle_Check/1079/artifact/gradle_check_1079.log/*view*/](https://fork-jenkins.searchservices.aws.dev/job/OpenSearch_CI/job/PR_Checks/job/Gradle_Check/1079/artifact/gradle_check_1079.log/*view*/)

**Comment by andrross** [comment]
Another failure (different test within same class) here: https://fork-jenkins.searchservices.aws.dev/job/OpenSearch_CI/job/PR_Checks/job/Gradle_Check/1429/artifact/gradle_check_1429.log/*view*/

```
./gradlew ':server:internalClusterTest' --tests "org.opensearch.cluster.MinimumMasterNodesIT.testTwoNodesNoMasterBlock" -Dtests.seed=8C423154E3EBD680 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=el-GR -Dtests.timezone=Asia/Aden -Druntime.java=17
```

**Comment by tlfeng** [comment]
Ran the command to run the test for 1k times, and there were 2 failure occurs.
`./gradlew ':server:internalClusterTest' --tests "org.opensearch.cluster.MinimumClusterManagerNodesIT.testTwoNodesNoClusterManagerBlock" -Dtests.iters=1000
`

**Comment by r1walz** [comment]
Hi, @andrross, @tlfeng. It looks same as #10006. Since, test run history isn't available on this issue. Shall we close it and track progress on #10006 instead?

**Comment by andrross** [comment]
Closing in favor of #10006
