### ISSUE TITLE
[BUG] :test:fixtures:s3-fixture:composeUp (random test failure)

### ISSUE THREAD

**Issue by CEHENKLE** [opensearch-project/OpenSearch#1566]
**Describe the bug**
Random Test Failure. Please dig in, and figure out what went wrong :(

[https://ci.opensearch.org/logs/ci/workflow/OpenSearch_CI/PR_Checks/Gradle_Check/gradle_check_1067_reports.zip](https://ci.opensearch.org/logs/ci/workflow/OpenSearch_CI/PR_Checks/Gradle_Check/gradle_check_1067_reports.zip)

**Comment by andrross** [comment]
Another instance of same failure: https://fork-jenkins.searchservices.aws.dev/job/OpenSearch_CI/job/PR_Checks/job/Gradle_Check/1447

**Comment by reta** [comment]
@CEHENKLE could you please close this one as duplicate of https://github.com/opensearch-project/OpenSearch/issues/1806, thank you.

**Comment by CEHENKLE** [comment]
Thanks @dblock  (and @reta for pointing it out :) )  

/C
