### ISSUE TITLE
[BUG] org.opensearch.backwards.PluginInfoIT.testPluginInfoSerialization is flaky

### ISSUE THREAD

**Issue by shiv0408** [opensearch-project/OpenSearch#15693]
### Describe the bug

https://metrics.opensearch.org/_dashboards/app/dashboards#/view/e5e64d40-ed31-11ee-be99-69d1dbc75083?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-30d,to:now))&_a=(description:'',filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'2e729590-eb26-11ee-b008-6583d3dd450c',key:test_name,negate:!f,params:(query:org.opensearch.backwards.PluginInfoIT.testPluginInfoSerialization),type:phrase),query:(match_phrase:(test_name:org.opensearch.backwards.PluginInfoIT.testPluginInfoSerialization)))),fullScreenMode:!f,options:(hidePanelTitles:!f,useMargins:!t),query:(language:kuery,query:''),timeRestore:!t,title:'OpenSearch%20Gradle%20Check%20Report',viewMode:view)

`org.opensearch.backwards.PluginInfoIT.testPluginInfoSerialization` has turned flaky for last few days. 
ex: https://build.ci.opensearch.org/job/gradle-check/46915/

### Related component

Plugins

### To Reproduce

```
REPRODUCE WITH: ./gradlew ':qa:mixed-cluster:v2.17.0#mixedClusterTest' --tests "org.opensearch.backwards.PluginInfoIT.testPluginInfoSerialization" -Dtests.seed=B3FC3B5288F29674 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=az-Cyrl -Dtests.timezone=America/Winnipeg -Druntime.java=21
NOTE: leaving temporary files on disk at: /var/jenkins/workspace/gradle-check/search/qa/mixed-cluster/build/testrun/v2.17.0#mixedClusterTest/temp/org.opensearch.backwards.PluginInfoIT_B3FC3B5288F29674-001
NOTE: test params are: codec=Asserting(Lucene99): {}, docValues:{}, maxPointsInLeafNode=663, maxMBSortInHeap=6.738775660853971, sim=Asserting(RandomSimilarity(queryNorm=true): {}), locale=az-Cyrl, timezone=America/Winnipeg
NOTE: Linux 5.15.0-1064-aws amd64/Eclipse Adoptium 21.0.4 (64-bit)/cpus=32,threads=1,free=309847440,total=536870912
NOTE: All tests run in this JVM: [ExceptionIT, IndexingIT, MixedClusterClientYamlTestSuiteIT, PluginInfoIT]
```

### Expected behavior

Test should always pass

**Comment by andrross** [comment]
[Catch All Triage - [1](https://github.com/AmiStrn), [2](https://github.com/mch2), [3](https://github.com/andrross)]

Closing in favor of autocut: #15814
