### ISSUE TITLE
search_after queries are not performing as expected

### ISSUE THREAD

**Issue by manuel-pancorbo** [opensearch-project/OpenSearch#1570]
#### Disclaimer: the origin of this issue was a [post](https://discuss.elastic.co/t/search-after-queries-are-not-performing-as-expected/289174) in ElasticSearch discuss.

**Is your feature request related to a problem? Please describe.**

We began to use the search_after parameter for solving our issues related to pagination consistency. This works fine until we realized that our query slow log started to have a lot of entries. At some moments this lead us to high CPU usage and high search latency, which degraded our service.

All of these log entries show us queries without filters or search terms and use the search_after parameter. This kind of query is taking ~400ms to be resolved. The issue is that its equivalent using a simple from/size pagination is taking just ~20ms.

So, why ES is taking more time/resources to resolve the query with "search_after" than its equivalent with from/size?

**Describe the solution you'd like**
After some query profiling, the team of ElasticSearch came with the explanation:

> I see what's happening.
> 
> From 7.6 we introduced an optimization 2 for sort queries, we rewrite a sort query as LongDistanceFeatureQuery that can skip over blocks of documents. This makes sort queries under certain conditions much faster. The optimization is currently not applied to search_after case. From 7.16 it will be applied to search_after as well, so sort queries with search_after also will be much faster under certain conditions.

So, this issue is just to ask for including this optimization to improve search_after queries in OpenSearch too.

**Describe alternatives you've considered**
In the meantime, the only thing we can do is add index sorting, which improves dramatically the issue, but just for one sort criteria.

**Additional context**

**Comment by Rishikesh1159** [comment]
I will work on this

**Comment by Rishikesh1159** [comment]
For search_after queries, sort optimization has not been applied. In some certain scenarios like @manuel-pancorbo said there is performance latency with search_after queries and some improvement needs to be done by applying sort optimization to search_after queries. The latest Lucene version has the sort optimization capability and I am planning to make use of this to optimize search_after queries. I will be comparing the benchmark results of OpenSearch using Lucene's capability for optimizing with current OpenSearch version. Based on results, we will further move forward with this optimization.
