### ISSUE TITLE
[BUG] "no index mapper found for field" warning appears after upgrade when indexing with nested type index mapping

### ISSUE THREAD

**Issue by jameshinstac** [opensearch-project/OpenSearch#15728]
### Describe the bug

A warning appears in the logs when indexing a document that has `"type": "nested"` in the index mapping. 

The warning: 

`[2024-09-05T02:34:56,685][WARN ][o.o.i.s.IndexShard ] [ip-10-0-11-60] [index][0] no index mapper found for field: [_type] returning default postings format`

It depends on the index being created in an earlier version than OpenSearch 2.x and then upgraded to OpenSearch 2.x. 

This gives an impression that there could be an issue with data that has been indexed. 

### Related component

Indexing

### To Reproduce

1. Create an OpenSearch 1.x cluster. This example uses OpenSearch 1.3.17. 
2. Create an index 

`put /index`

3. Add index mapping 

```
put /index/_mapping -d '
{
  "properties": {
    "aspect": {
      "type": "nested"
    }
  }
}'
```

4. Index a document 

```
post "/index/_doc" -d '{
  "aspect": {
    "name": "James"
  }
}'

POST /_refresh
```

5. Upgrade cluster to OpenSearch 2.x. This example uses OpenSearch 2.14.0.
6. Index another document 

```
post "/index/_doc" -d '{
  "aspect": {
    "name": "James"
  }
}'

POST /_refresh
```

7. Check OpenSearch logs. See warning like: 

`[2024-09-05T02:34:56,685][WARN ][o.o.i.s.IndexShard ] [ip-10-0-11-60] [index][0] no index mapper found for field: [_type] returning default postings format`

### Expected behavior

Documents should index without warning the same as if the cluster had not been upgraded.

### Additional Details

**Plugins**
opensearch-custom-codecs
opensearch-geospatial
opensearch-job-scheduler
opensearch-security
repository-azure
repository-gcs
repository-s3

**Host/Environment (please complete the following information):**

Running in a docker container 

 - OS: Debian
 - Version 11

**Additional context**
This issue looks similar to https://github.com/opensearch-project/k-NN/issues/537 but in this example, the k-NN plugin is not in use.

**Comment by dhwanilpatel** [comment]
Indexing Triage [09/16]

@jameshinstac  Thanks for filing the issue, the log line which you are referring is not for the index mapping, but for the internal `_type` field. This `_type` field was deprecated on 2.x version, that's why you might see the log line. But it should be okay to ignore the log line and it might get removed once `_type` field is completely removed in next major version.
