### ISSUE TITLE
[Flaky Test] org.opensearch.index.translog.RemoteFsTimestampAwareTranslogTests.testSimpleOperationsUpload is flaky

### ISSUE THREAD

**Issue by sachinpkale** [opensearch-project/OpenSearch#15731]
### Describe the bug

https://build.ci.opensearch.org/job/gradle-check/47104/testReport/junit/org.opensearch.index.translog/RemoteFsTimestampAwareTranslogTests/testSimpleOperationsUpload/

### Related component

Storage:Snapshots

### To Reproduce

https://build.ci.opensearch.org/job/gradle-check/47104/testReport/junit/org.opensearch.index.translog/RemoteFsTimestampAwareTranslogTests/testSimpleOperationsUpload/

### Expected behavior

Test should pass/fail deterministically

### Additional Details

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**

**Comment by prudhvigodithi** [comment]
Hey @sachinpkale the automation flagged the class `RemoteFsTimestampAwareTranslogTests` showing some flaky tests, please check https://github.com/opensearch-project/OpenSearch/issues/15818. Can we close this issue?
Thanks
@dblock @rednaksi91 @andrross @getsaurabh02
