### ISSUE TITLE
[BUG] Missing validations in shallow snapshot V2 repo creation

### ISSUE THREAD

**Issue by sachinpkale** [opensearch-project/OpenSearch#15913]
### Describe the bug

- While creating repository for shallow snapshot V2, we have following validations missing:
  - There can be multiple repositories with the shallow v2 flag enabled.
  - Repo name can contain a delimiter that is used in the pinning entity

Without these validations, remote store data cleanup will not be straightforward and can lead to zombie data.

**Comment by sachinpkale** [comment]
Need to get this change in 2.17. PR: https://github.com/opensearch-project/OpenSearch/pull/15911

**Comment by ashking94** [comment]
Closing this issue since the associated PR is already merged.
[Triage - attendees [1](https://github.com/ashking94) [2](https://github.com/linuxpi) [3](https://github.com/ashking94) [4](https://github.com/sachinpkale) [5](https://github.com/skumawat2025)]
