### ISSUE TITLE
[BUG] Unbounded execution for write threads when parsing a flat_object field provided as array

### ISSUE THREAD

**Issue by mgodwan** [opensearch-project/OpenSearch#15982]
### Describe the bug

Unbounded execution for write threads when parsing a flat_object field provided as array.
Ideally, this should error out gracefully.

### Related component

Indexing

### To Reproduce

```
PUT dummy
{
    "mappings": {
        "properties": {
            "ArrField": {
                "type": "flat_object"
            }
        }
    }
}

# Succeeds
POST dummy/_doc
{
    "ArrField": {
        "ObjKey": "ObjVal"
    }
}

# Stuck forever
POST dummy/_doc
{
    "ArrField": ["ArrVal"]
}
```

### Expected behavior

Error out due to lack of support.

### Additional Details

**Plugins**
none

**Screenshots**

**Host/Environment (please complete the following information):**
 - OS: Mac
 - Version: Sonoma

**Additional context**

**Comment by msfroh** [comment]
I just found this:

```
    public XContentParser parseObject() throws IOException {
        assert currentToken() == Token.START_OBJECT;
        parser.nextToken(); // Skip the outer START_OBJECT. Need to return on END_OBJECT.

        builder.startObject();
```

That `assert` is useless in production if we're not guarding this entry-point. I'll add the appropriate check.
