### ISSUE TITLE
[RFC] Pluggable Storage / Warm Tier

### ISSUE THREAD

**Issue by andrross** [opensearch-project/OpenSearch#1599]
Propose a change to implement tiered storage (e.g. Ultrawarm) on top of a pluggable object store architecture.

**Comment by reta** [comment]
I think there are too many issues on the subject, see please https://github.com/opensearch-project/OpenSearch/issues/1059, https://github.com/opensearch-project/OpenSearch/issues/740, https://github.com/opensearch-project/OpenSearch/issues/1052 :-)

**Comment by andrross** [comment]
Closing this issue as it's a duplicate and not helpful :)
