### ISSUE TITLE
Add new notebooks via API

### ISSUE THREAD

**Issue by inf17101** [opensearch-project/OpenSearch#1612]
**Is your feature request related to a problem? Please describe.**
We want to automate the creation of opensearch notebooks via api requests.
I cannot find any way to do this. We have tried to pull a notebook from opensearch-notebooks index and change existing text and then indexed again the same notebook with a different name. The notebook is created, we can see in the WebUI, but the changes are not visible.

**Describe the solution you'd like**
It would be very nice to have a notebooks api endpoint to pull existing notebooks, change the paragraphs (texts and visualization) and create them via api request.
I think notebooks has only a value at if developers can automate the process of the creation of notebooks, because if you have hundreds of notebooks with just different text for different users and some visualizations changes, you do not edit each notebook for simple changes manually.

**Comment by AmiStrn** [comment]
Hi @inf17101 
The notebook feature is a plugin. Perhaps add these issues to https://github.com/opensearch-project/dashboards-notebooks
? There are a few you have opened in this repo that may belong there. 
This would help get tge relevant people involved:)

**Comment by inf17101** [comment]
Hi @AmiStrn
Thanks for your reply, I have opened the issues again at the dashboard-notebooks repo, like you have suggested.
I thought it is also suitable here, because API and dashboard features are maybe a core feature not plugin specific.

**Comment by anasalkouz** [comment]
Closing this issue. Since another issue already opened in dashboard-notebooks repo. Please feel free to reopen if anything required from opensearch core.

**Comment by dblock** [comment]
> Closing this issue. Since another issue already opened in dashboard-notebooks repo. Please feel free to reopen if anything required from opensearch core.

@anasalkouz Link?
