### ISSUE TITLE
Opensearch Webcrawl feature

### ISSUE THREAD

**Issue by gautamkct** [opensearch-project/OpenSearch#1615]
Hi Team,

Wondering if opensearch support Web crawling out of box or any plans to inlcude in near future.

Thanks
Gautam Sharma

**Comment by setiah** [comment]
It doesn't today, but that's a great feature ask. Having a crawler to automatically pull new content and ingests in an OpenSearch cluster would be very useful for website search use case and compliment https://github.com/opensearch-project/OpenSearch/issues/1219 nicely

**Comment by gautamkct** [comment]
Thanks @setiah for adding this to [1219 ](https://github.com/opensearch-project/OpenSearch/issues/1219)

**Comment by smacrakis** [comment]
The open source [StormCrawler web crawler](https://stormcrawler.net/) was ported to OpenSearch a few months ago.
DigitalPebble, the authors of StormCrawler, are [an OpenSearch partner](https://opensearch.org/partners/digitalpebble.html) and provide consulting services if you need them.

**Comment by dblock** [comment]
I'm going to close this since at least some solutions exist and I don't think crawling should be a feature of core. Thanks everyone!
