### ISSUE TITLE
[BUG] `Detect Breaking Changes` check does not fail on new method added to an @PublicApi interface

### ISSUE THREAD

**Issue by sachinpkale** [opensearch-project/OpenSearch#16175]
### Describe the bug

- Today, `Detect Breaking Changes` runs on each PR build to avoid introducing any breaking changes to 2.x branch.
- But it does not detect breaking change to a public interface where a new method is added.
- Example: https://github.com/opensearch-project/OpenSearch/pull/15569/files#diff-15dd2c1859d8b3091b1b702af9c5bbdd680224671444870daf9f392d4e838fa1R194

### Related component

Build

### To Reproduce

- Add a method to any public interface.
  - It is possible that the bug exists only if the new method is overloaded method of existing method.
- Raise PR against 2.x branch.
- `Detect Breaking Changes` will not fail.

### Expected behavior

- For any new method introduced in a public interface, `Detect Breaking Changes` should fail unless a default implementation is provided.

**Comment by reta** [comment]
Thanks @sachinpkale for bringing it up, I believe the API check does binary compatible changes at the moment: adding a new method to the interface is binary compatible change. We may need to make the check more strict by enforcing source compatibility.
