### ISSUE TITLE
[BUG] Identity feature flag should be set to `true` while the feature is first released

### ISSUE THREAD

**Issue by peternied** [opensearch-project/OpenSearch#16173]
### Describe the bug

In 2.17 the identity feature flag was in place and is disabled by default.  With #16024 backported to 2.x, in the identity feature is enabled with no way to disable.  We have skipped past the step where its enabled by default and had several releases to confirm everything is working as expected.

I would advice caution with this feature roll out to be sure we aren't creating any blocking issue.  Lets add the flag back but flip the state to enabled by default.

### Additional Details

- https://github.com/opensearch-project/OpenSearch/pull/16024

**Comment by peternied** [comment]
FYI @reta @cwperks

**Comment by cwperks** [comment]
Thank you for filing this issue @peternied! All usages of Identity are currently gates behind the Extensions FeatureFlag.

There are 2 locations where methods from IdentityService are called:

1. In [RestSendToExtensionAction](https://github.com/opensearch-project/OpenSearch/blob/4e3a6d038dfc37660c7b9e47f570a32b0f2be4d4/server/src/main/java/org/opensearch/extensions/rest/RestSendToExtensionAction.java#L251-L253)
2. In [ExtensionsManager](https://github.com/opensearch-project/OpenSearch/blob/4e3a6d038dfc37660c7b9e47f570a32b0f2be4d4/server/src/main/java/org/opensearch/extensions/ExtensionsManager.java#L460-L463)

There are no other usages. I think this qualifies as being under a feature flag, but let me know what you think.

**Comment by reta** [comment]
Thanks @peternied , adding to that, I believe this feature flag is not used at all it the wild (safe to remove). Also, all feature flags have to be disabled by default but we could flip it on in `opensearch.yml` if you think think we have to bring it back ( `shiro` plugin is not installed by default).

**Comment by peternied** [comment]
Thanks for double checking - false alarm!
