### ISSUE TITLE
Provide a certificate management tool for opensearch distributions

### ISSUE THREAD

**Issue by setiah** [opensearch-project/OpenSearch#1633]
Provide a certificate management tool that helps users create self-signed certificates and install them on OpenSearch by configuring all keystore and truststore settings. The idea is to replace install_demo_configurations.sh tool with this tool as self-signed certificates are relatively more secure than demo certs and qualify as better default. It is important that the ease of use is maintained for a quick getting started experience and to achieve that, self-signed certificate tool can work in two modes - default (use -f) and interactive (use -i). In default mode, the tool could assume default values so users can still enjoy the single click experience for quick getting started. The interactive mode (-i), on the other hand, helps users to setup the self-signed certificate in an interactive fashion with user-provided inputs. In both modes, the tool auto-configures the OpenSearch security settings based on the new certificates. 

- [x] Define the input parameters in both default and interactive mode, for the tool. 
- [x] Check OpenSsl availability on different platforms for self-signed certificate generation.
- [x] ~~Dismantle and replace existing `install_demo_configurations.sh` tool with the new certificate management tool in build workflows and elsewhere~~

Related to #1618

**Comment by setiah** [comment]
Pasting logs for the new setup experience which seems much cleaner than what we have today. The `install_ssl_configuration.sh` (tool name #tbd) will be used for setting up all security configurations with freshly created self-signed certs that are unique to every user, unlike the demo certs today. The tool is capable of running in `auto-mode` (with -y option) and `interactive-mode` (without -y option). In `interactive mode`, the tool seeks inputs like 1. Certificate validity duration, 2. Root, Admin, Node certificate Subject Names, 3. Should initialize security module?, and sets up these configurations. In `auto-mode`, it assumes the certificate validity duration as 365 days, and pre-defined defaults for certificate Subject names to provide a single-click user experience. Below is the output for a run in `auto-mode`.

I am leaning towards deprecating the old install_demo_configurations.sh in favor of this new tool. The same will be done for  the docker distribution to replace demo certs with shiny new self-signed certs on first-time container start, PR - https://github.com/opensearch-project/opensearch-build/pull/1370

Would love to hear more thoughts. @opensearch-project/security @rursprung 

cc/ @elfisher @CEHENKLE @jimishs 

```
➜  opensearch-1.2.0 ./plugins/opensearch-security/tools/install_ssl_configuration.sh  -c -y

=========== OpenSearch Security Dev Configurations Installer ============

#############################
Step 1: Generating self-signed certificates using OpenSSL
#############################

Root certificates created at /Users/setiah/Downloads/opensearch-1.2.0/config/root-ca.pem
Admin certificates created at /Users/setiah/Downloads/opensearch-1.2.0/config/kirk.pem
Node certificates created at /Users/setiah/Downloads/opensearch-1.2.0/config/esnode.pem

#############################
Step 2: Installing self-signed certificates
#############################

Certificates installed successfully! See updated settings in config/opensearch.yml

#############################
Step 3: Initialize security
#############################

Skipping initializing OpenSearch Security based on the provided input.
After the whole cluster is up execute:
"/Users/setiah/Downloads/opensearch-1.2.0/plugins/opensearch-security/tools/securityadmin.sh" -cd "/Users/setiah/Downloads/opensearch-1.2.0/plugins/opensearch-security/securityconfig" -icl -key "/Users/setiah/Downloads/opensearch-1.2.0/config/kirk-key.pem" -cert "/Users/setiah/Downloads/opensearch-1.2.0/config/kirk.pem" -cacert "/Users/setiah/Downloads/opensearch-1.2.0/config/root-ca.pem" -nhnv
Or
run ./securityadmin_demo.sh
After that you can also use the Security Plugin ConfigurationGUI

#############################
Setup complete!
#############################

Single node setup successful! You can now start the cluster with bin/opensearch

To access your secured cluster open https://<hostname>:<HTTP port> and log in with admin/admin. Example
curl -k https://localhost:9200 -u admin:admin
(Ignore the SSL certificate warning because we installed self-signed certificates)

Follow the steps below to setup multi-node cluster
1. Execute this script now on all your nodes
2. Start all nodes with bin/opensearch

For configuring language clients like Java, Python, Go, and tools like Logstash, Grafana, etc.,
please refer to the "CLIENTS AND TOOLS" documentation on https://opensearch.org/docs/latest

#############################
Disclaimer!
#############################

 ** Warning: Do not use on production or public reachable systems **
Self signed certificates installed via this tool are good for development or use within a trusted private network.
For any production use, we recommend using trusted CA provided certificates.
```

**Comment by elfisher** [comment]
I really like this new approach. Just wondering, in the docker use case, how would someone get the certs setup across their containers and a local client?

**Comment by rursprung** [comment]
is this purely for dev/demo/test environments (like the old script) or is this also meant to be used in production?

in production most will be using a multi-cluster setup (after all, the recommendation is to use at least three master-eligible nodes for production) and in that case the certificates need to be signed by the same CA. and at that point you IMHO shouldn't generate them on any specific node anymore but instead issue them wherever you have the private key of the CA (which may or may not be self-signed).

and how do you handle certificate rotation if the certificates expire after 365 days?

in a containerised environment i'd expect you to run it on kubernetes or a similar infrastructure. in that case the best option would be to have an operator ([discussions ongoing in the forum](https://discuss.opendistrocommunity.dev/t/opensearch-kubernetes-operator/8106)) which takes care of the whole certificate handling and otherwise you'd use something like [cert-manager](https://cert-manager.io/) to handle the certificates (also not trivial! OpenSearch security will still need to be able to handle certificate reloads, in the best case by file system monitoring, in the worst case by some ugly scripts doing the same next to it and triggering the re-load).
with something like this in place the certificates get signed by a central CA (which may or may not be a self-signed one, e.g. cert-manager supports anything from self-signed to using an external CA like let's encrypt).

also, in a containerised environment - even if it isn't on kubernetes - i'd probably not run this script at all, i'd instead generate the necessary certificates elsewhere and then just mount them into the container, so that i don't need any ephemeral storage but only use the read-only container image plus external mounts.
and in a container (and also in general?) you don't want some script to suddenly update your application configuration - this should be baked into the image, with the relevant parts being exposed as parameters (usually ENV variables) or read from externally mounted files.

**Comment by setiah** [comment]
Thanks @rursprung. I'm on the same page with you. Let me clarify a few things. 

Self-signed certs generated via this tool are meant for dev use, and while it is not recommended to be used for production, it should be fine if used within a private trusted network. For production, the recommendation is to use certificates from a trusted CA (_see disclaimer_)

The purpose of this tool is to simplify the getting started experience, make it more user-friendly and verbose and also secure the defaults by replacing hardcoded demo certs with new self-signed certs. It will also replace demo certificates used by docker image and docker compose by installing new self-signed certificates first time the container starts from a docker image.

>in production most will be using a multi-cluster setup (after all, the recommendation is to use at least three master-eligible nodes for production) and in that case the certificates need to be signed by the same CA. and at that point you IMHO shouldn't generate them on any specific node anymore but instead issue them wherever you have the private key of the CA (which may or may not be self-signed).

Right, multi-node setup will be different. It can use kubernetes or tools like ansible for the orchestration. The operator will take care of whole certificate thing in that case. There is a separate issue to track the multi-node setup orchestration. Also thanks for pointing to the forum thread. I like the idea of using cert-manager in containers for all-things-certificates. 

>and how do you handle certificate rotation if the certificates expire after 365 days?
>OpenSearch security will still need to be able to handle certificate reloads, in the best case by file system monitoring, in the worst case by some ugly scripts doing the same next to it and triggering the re-load

The security plugin provides an API for hot reloading ssl certificates, once they have been replaced by the user or an operator on the node. The API invocation hot reloads the new certificates.

@elfisher - For docker, this tool will be baked in the docker image. For single node setup, the certificates will be setup automatically when a container starts from the docker image first time. Every subsequent container stop/start will use the previously installed certificates. Also these certificates will be generated on the host running docker and can be easily replaced with user-provided certs later. This would work for docker-compose as well which sets up 2 opensearch containers and 1 opensearch-dashboard container on a single node today. As for multi-node docker setup, we don't have that today. It will use a different mechanism with kubernetes.
 
_(Apologies for the delayed response. I am on a planned vacation. Will get back with more details soon as I can.)_

**Comment by setiah** [comment]
Hi @opensearch-project/security team, could someone please review these changes

**Comment by setiah** [comment]
>also, in a containerised environment - even if it isn't on kubernetes - i'd probably not run this script at all, i'd instead generate the necessary certificates elsewhere and then just mount them into the container, so that i don't need any ephemeral storage but only use the read-only container image plus external mounts.
and in a container (and also in general?) you don't want some script to suddenly update your application configuration - this should be baked into the image, with the relevant parts being exposed as parameters (usually ENV variables) or read from externally mounted files.

To add a bit more clarity for how it works in containers - Certificates are stored in [docker volume](https://docs.docker.com/storage/volumes/) and do not get updated on container restarts. They are part of the host storage and can be shared among multiple containers. Also, maintaining certs in docker volume prevents them from any accidental replacement. They have to be explicitly replaced with other certs (e,g, trusted CA certs) by using docker cli copy commands and hot reloaded using API
