### ISSUE TITLE
We're missing a GH release for v2.17.1 (but we have the tag), is this GA? 

### ISSUE THREAD

**Issue by mamccorm** [opensearch-project/OpenSearch#16350]
### Describe the bug

The latest GH release for this repo is currently v2.17.0:

<img width="1052" alt="Screenshot 2024-10-16 at 14 45 15" src="https://github.com/user-attachments/assets/ee38b04a-64ca-4b95-a83b-269127a42e7e">

However ~1 month ago [a new v2.17.1 tag was cut.](https://github.com/opensearch-project/OpenSearch/releases/tag/2.17.1), but there is no GH release for this.

For comparison, if we look at opensearch-build, that repo does have a v2.17.1 tag cut:
- https://github.com/opensearch-project/opensearch-build/releases

is opensearch v2.17.1 considered GA? and if so are there plans to cut a new GH release for this tag, to bring it into line with the other repos?

Thanks in advance

### Related component

Build

### To Reproduce

Not relevant

### Expected behavior

GH release for v2.17.1 if it's a GA release

### Additional Details

N/A

**Comment by mamccorm** [comment]
Another example, there looks to be an image built for v2.171.1 as well:
 - https://hub.docker.com/layers/opensearchproject/opensearch/2.17.1/images/sha256-ab6db8c14062060cda5f0428364e76ffe2a6f03ad265589b70182c0cecb7f9d7?context=explore

But no GH release created?

**Comment by Divyaasm** [comment]
Hey @dbwiddis , the 2.17.1 was out on October 1st and tags were automatically generated. Can you draft a new release using the tag 2.17.1 .

**Comment by gaiksaya** [comment]
Looks like the release workflow failed https://github.com/opensearch-project/OpenSearch/actions/runs/11134219928

**Comment by Divyaasm** [comment]
Hi @reta , can you please draft a new release for 2.17.1 on Github.
Thanks

**Comment by reta** [comment]
Thanks @gaiksaya , manually drafted the release https://github.com/opensearch-project/OpenSearch/releases/tag/2.17.1
