### ISSUE TITLE
[BUG] Windows build broken

### ISSUE THREAD

**Issue by mann2108** [opensearch-project/OpenSearch#1637]
**Describe the bug**
I am trying to run OpenSearch on my local windows machine, and after running `gradlew.bat run` it's throwing an error.
![image](https://user-images.githubusercontent.com/44433995/144201415-16f3ae8b-bde8-472a-9f9d-0a7cabb9edd5.png)

Also, gradlew.bat check command throwing an error. Please find an attached snapshot for your reference.
![image](https://user-images.githubusercontent.com/44433995/144202338-0d54767b-f61e-47bc-b5ca-28e9b8a8e2a7.png)
![image](https://user-images.githubusercontent.com/44433995/144202424-6770b6df-03c5-4052-8f6b-c9a78ccdae21.png)
![image](https://user-images.githubusercontent.com/44433995/144202507-0662e54e-1af1-43fb-9415-94e7db718012.png)

**To Reproduce**
1. Clone the opensearch from opensearch-project.
2. Set up the JAVA_HOME with OpenJDK 11
3. Run the command `gradlew.bat run`

**Expected behavior**
It should run properly without any error.

**Plugins**
No plugins are enabled right now.

**Screenshots**
![image](https://user-images.githubusercontent.com/44433995/144201660-d5b02e46-51d1-44cb-8a19-25c8ebd8a683.png)

**Host/Environment (please complete the following information):**
 - OS: Windows
 - Version Windows 10
 - OpenJDK - 11

**Comment by dblock** [comment]
Looks like there are a couple of problems on Windows.

1. A CR/LF mismatch between *nix/windows that causes spotless checks to fail. Care to try running the suggestions above (`./gradlew.bat :benchmarks:spotlessApply`) and PRing the changes?
2. Failure in `:distribution:processOutputs` with igest:geoip. This needs debugging, likely a .tar.gz vs. .zip problem.

We don't run CI regularly on Windows, but we should. Maybe we can add a GHA workflow for `./gradlew check` on both Windows and Linux here? 

There's also a meta item in https://github.com/opensearch-project/opensearch-build/issues/33 for a Windows distribution with a bunch of other workitems.

**Comment by dblock** [comment]
@mann2108 This should be now fixed on main.

**Comment by mann2108** [comment]
@dblock Thanks 👍🏼
