### ISSUE TITLE
[BUG] ignore_malformed param is not working

### ISSUE THREAD

**Issue by Subrahmanyam-Gollapalli** [opensearch-project/OpenSearch#16451]
### Describe the bug

Here I am creating an index named my-index-000001 with index.mapping.ignore_malformed setting. The ignore_malformed parameter is set on the index level and I am trying to index two documents to the index my-index-000001 as mentioned below.
```
curl -X PUT "localhost:9200/my-index-000001?pretty" -H 'Content-Type: application/json' -d'
{
  "settings": {
    "index.mapping.ignore_malformed": true 
  },
  "mappings": {
    "properties": {
      "number_one": { 
        "type": "byte"
      },
      "number_two": {
        "type": "integer",
        "ignore_malformed": false 
      }
    }
  }
}
'
```

```
curl -X PUT "localhost:9200/my-index-000001/_doc/1?pretty" -H 'Content-Type: application/json' -d'
{
  "text":       "Some text value",
  "number_one": "foo" 
}
'
```

```
curl -X PUT "localhost:9200/my-index-000001/_doc/2?pretty" -H 'Content-Type: application/json' -d'
{
  "text":       "Some text value",
  "number_two": "foo" 
}
'
```

Ideally, the first document should be indexed, and the second document should be rejected with a number_format exception. But, in the OpenSearch version 2.13, second document also gets indexed, whereas in the Elasticsearch version 6.8 and 8.15 the ignore_malformed parameter is working as expected(second doc gets rejected). Any idea on why the ignore_malformed setting is not working as expected in OpenSearch.

### Related component

Indexing

### Expected behavior

```
curl -X PUT "localhost:9200/my-index-000001?pretty" -H 'Content-Type: application/json' -d'
{
  "settings": {
    "index.mapping.ignore_malformed": true 
  },
  "mappings": {
    "properties": {
      "number_one": { 
        "type": "byte"
      },
      "number_two": {
        "type": "integer",
        "ignore_malformed": false 
      }
    }
  }
}
'
```

```
curl -X PUT "localhost:9200/my-index-000001/_doc/1?pretty" -H 'Content-Type: application/json' -d'
{
  "text":       "Some text value",
  "number_one": "foo" 
}
'
```

```
curl -X PUT "localhost:9200/my-index-000001/_doc/2?pretty" -H 'Content-Type: application/json' -d'
{
  "text":       "Some text value",
  "number_two": "foo" 
}
'
```

If I create the index using the first command and index 2 documents using the second and third commands then the second document should reject with exception.

### Additional Details

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**

**Comment by dblock** [comment]
If you have time, try turning this into a (failing) YAML REST test (https://github.com/opensearch-project/OpenSearch/blob/main/TESTING.md#testing-the-rest-layer)?

**Comment by RS146BIJAY** [comment]
Seems duplicate for this issue: https://github.com/opensearch-project/OpenSearch/issues/16599
