### ISSUE TITLE
[BUG] Task `:distribution:bwc:minor:buildBwcLinuxArm64Tar` fails on Linux ARM

### ISSUE THREAD

**Issue by andrross** [opensearch-project/OpenSearch#16535]
### Describe the bug

```
> Task :distribution:bwc:minor:buildBwcLinuxArm64Tar FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':distribution:bwc:minor:buildBwcLinuxArm64Tar'.
> Building 2.19.0 didn't generate expected file /home/ubuntu/OpenSearch/distribution/bwc/minor/build/bwc/checkout-2.x/distribution/archives/linux-arm64-tar/build/distributions/opensearch-min-2.19.0-SNAPSHOT-linux-arm64-x64.tar.gz
```

### Related component

Build

### To Reproduce

Execute `./gradlew :distribution:bwc:minor:buildBwcLinuxArm64Tar` on a Graviton AWS EC2 instance with Ubuntu installed.

It expects the file `opensearch-min-2.19.0-SNAPSHOT-linux-arm64-x64.tar.gz` but the actual file that is created is `opensearch-min-2.19.0-SNAPSHOT-linux-arm64.tar.gz` (there's an extra "-x64" in the expected file).

I believe the problem is here:

https://github.com/opensearch-project/OpenSearch/blob/d158ec6d431615b16192c34490b46752f3eb3e0f/buildSrc/src/main/java/org/opensearch/gradle/internal/InternalDistributionBwcSetupPlugin.java#L184

If I remove that trailing `"-x64"` then it works, though I'm sure that change would break the build for the non-ARM case.

### Expected behavior

task succeeds

### Additional Details

`m8g.4xlarge` EC2 instance running Ubuntu 24.04

**Comment by sandeshkr419** [comment]
> If I remove that trailing "-x64" then it works, though I'm sure that change would break the build for the non-ARM case.

the file name `opensearch-min-2.19.0-SNAPSHOT-linux-arm64.tar.gz` seems correct as having both the suffixes `-arm64-x64` looks buggy. I'm surprised why it hasn't failed before. 
I suppose there should be a conditional suffix `-x64` or `-arm64` based on the architecture type.

@rishabh6788 Thoughts?
