### ISSUE TITLE
What do I need to w

### ISSUE THREAD

**Issue by Ashleycho35** [opensearch-project/OpenSearch#1656]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by CEHENKLE** [comment]
@Ashleycho35 Hi!  It looks like your issue might have gotten cut off while you were writing it.  Can you tell us more about what's going on?  Thanks!

**Comment by anasalkouz** [comment]
Closing this, due to lack of details. @Ashleycho35  feel free to reopen once you fill in the details
