### ISSUE TITLE
[BUG] Error adding "cluster.routing.allocation.balanced_shards_allocator.allocator_timeout" setting 

### ISSUE THREAD

**Issue by RamakrishnaChilaka** [opensearch-project/OpenSearch#16713]
### Describe the bug

Unable to set "cluster.routing.allocation.balanced_shards_allocator.allocator_timeout" setting in 2.13, while the same works in 2.15.

### Related component

Other

### To Reproduce

1. Clone openserch
2. checkout to 2.13
3. Try to add this setting curl --location --request PUT 'http://localhost:9200/_cluster/settings' \ --header 'Content-Type: application/json' \ --data '{ "persistent" : { "cluster.routing.allocation.balanced_shards_allocator.allocator_timeout" : "30s" } }'
4. Fails with {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"persistent setting [cluster.routing.allocation.balanced_shards_allocator.allocator_timeout], not recognized"}],"type":"illegal_argument_exception","reason":"persistent setting [cluster.routing.allocation.balanced_shards_allocator.allocator_timeout], not recognized"},"status":400}%

### Expected behavior

The same works in 2.15
```
bcd07443cc66 % curl --location --request PUT 'http://localhost:9200/_cluster/settings' \
--header 'Content-Type: application/json' \
--data '{
  "persistent" : {
    "cluster.routing.allocation.balanced_shards_allocator.allocator_timeout" : "30s"
  }
}'
{"acknowledged":true,"persistent":{"cluster":{"routing":{"allocation":{"balanced_shards_allocator":{"allocator_timeout":"30s"}}}}},"transient":{}}%
```

### Additional Details

**Plugins**
No plugin is enabled

**Screenshots**

**Host/Environment (please complete the following information):**
 - OS: macos
 - Version 2.13

**Comment by shwetathareja** [comment]
@RamakrishnaChilaka this setting is present from OpenSearch 2.17 onwards.
Pull request - https://github.com/opensearch-project/OpenSearch/pull/15239
