### ISSUE TITLE
Remove LegacyVersion.V_6.x Constants and Deprecated Code in OpenSearch 2.0

### ISSUE THREAD

**Issue by adnapibar** [opensearch-project/OpenSearch#1674]
This is a clean up meta issue to track the removal of all `LegacyVersion.V_6.x` constants and code that are deprecated to be removed in OpenSearch 2.0. 

- [x] #1658
- [x] #1681
- [x] #1686
- [x] #1691
- [x] #1787
- [x] #1794
- [x] #1804
- [x] #1807
- [x] #1869
- [x] #1216
- [x] #1639
- [ ] Remove copy_settings parameter from split and shrink API
- [x] #1761
- [ ] Remove boost parameter on field mappings 
- [x] #1870
- [x] #1781
- [x] #1903 
- [x] #2029 
- [x] #2151

**Comment by saratvemulapalli** [comment]
Just saw this issue, can we also take care of `TransportClient` ? 
Here is an issue I opened up yesterday: #1669

**Comment by adnapibar** [comment]
> Just saw this issue, can we also take care of `TransportClient` ? Here is an issue I opened up yesterday: #1669

Thanks @saratvemulapalli !

**Comment by lukas-vlcek** [comment]
I think there are still some leftovers, at least in `org.opensearch.gradle.testclusters` package.

For example `OpenSearchCluster` or `OpenSearchNode` classes still contain several conditions that use string constants like "6.2.0", "6.3.0", "6.5.0" ... etc. (They do not make use of `Version` or `LegacyESVersion` instance, maybe that is why these cases were not handled yet?)

**Comment by adnapibar** [comment]
> I think there are still some leftovers, at least in `org.opensearch.gradle.testclusters` package.
> 
> For example `OpenSearchCluster` or `OpenSearchNode` classes still contain several conditions that use string constants like "6.2.0", "6.3.0", "6.5.0" ... etc. (They do not make use of `Version` or `LegacyESVersion` instance, maybe that is why these cases were not handled yet?)

Thanks @lukas-vlcek - we will be removing those as well. Feel free to raise a PR if you'd like to contribute :)

**Comment by davidlago** [comment]
We depend on the `TransportClient` in the security plugin. The effort to remove is significant (i.e. in the tens of hours of work). Without these changes, this is a build-breaking issue (we will not have working 2.0 builds until this is addressed). Would it be OK if we postpone this removal until the next major version? I'm weighing in the risks of breaking the build and delaying the release vs. removing [something that has been deprecated since 7.0](https://www.elastic.co/guide/en/elasticsearch/client/java-api/current/transport-client.html)

**Comment by CEHENKLE** [comment]
@nknize I hate dragging this to 3.0, but I don't see an immediate harm to keeping it around but deprecated.  What do you think?

**Comment by dblock** [comment]
@davidlago Do you have an open child issue from here yet?

**Comment by dblock** [comment]
> @nknize I hate dragging this to 3.0, but I don't see an immediate harm to keeping it around but deprecated. What do you think?

I think we should do the work in the security plugin, and not punt this.

**Comment by nknize** [comment]
> most plugins currently are building 1.3.0 in main

This is the bigger concern. The main branch has quickly diverged from 1.x so plugins really need to have a branch that can build from 2.0.0 core; even if it's just a feature branch. Unfortunately we're going to run into more than just TransportClient conflicts (e.g., security also still supports soft-delete parameter which is now removed in main) and as that list grows so will the amount of delay to having a functional 2.0 stack ready for public preview.

**Comment by saratvemulapalli** [comment]
> > most plugins currently are building 1.3.0 in main
> 
> This is the bigger concern. The main branch has quickly diverged from 1.x so plugins really need to have a branch that can build from 2.0.0 core; even if it's just a feature branch. Unfortunately we're going to run into more than just TransportClient conflicts (e.g., security also still supports soft-delete parameter which is now removed in main) and as that list grows so will the amount of delay to having a functional 2.0 bundle ready for public preview.

+1 when we started setting up the branches 2.0.0 was far down the line. 
I am worried plugins will see lot more problems than we can guess (eg: Gradle 7, TransportClient etc). 
We should start replicating the same branching strategy as OpenSearch for rest of the bundle.

**Comment by kavilla** [comment]
So just be clear we no longer support migrating from 6.8 to OpenSearch latest? https://opensearch.org/docs/latest/upgrade-to/upgrade-to/#upgrade-paths

**Comment by anasalkouz** [comment]
Moving remaining effort to 3.0. #2773. Closing this for now
