### ISSUE TITLE
[BUG] Gradle clean failing after a failed gradle check

### ISSUE THREAD

**Issue by VachaShah** [opensearch-project/OpenSearch#1675]
**Describe the bug**
I am facing the following error in `./gradlew clean` after a failed gradle check:

```
> Task :distribution:docker:clean FAILED
> Task :qa:remote-clusters:clean FAILED

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':distribution:docker:clean'.
> java.io.IOException: Unable to delete directory '/home/ubuntu/OpenSearch/distribution/docker/build'
    Failed to delete some children. This might happen because a process has files open or has its working directory set in the target directory.
    - /home/ubuntu/OpenSearch/distribution/docker/build/logs/1
    - /home/ubuntu/OpenSearch/distribution/docker/build/logs/2
    - /home/ubuntu/OpenSearch/distribution/docker/build/logs

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':qa:remote-clusters:clean'.
> java.io.IOException: Unable to delete directory '/home/ubuntu/OpenSearch/qa/remote-clusters/build'
    Failed to delete some children. This might happen because a process has files open or has its working directory set in the target directory.
    - /home/ubuntu/OpenSearch/qa/remote-clusters/build/logs/1
    - /home/ubuntu/OpenSearch/qa/remote-clusters/build/logs/2
    - /home/ubuntu/OpenSearch/qa/remote-clusters/build/logs
```

The `./gradlew check` fails with the following error:

```
1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':qa:remote-clusters:composeUp'.
> Container 9e86c7459baccbc08abe6e6d07d6d8f5807844d19901429c0f8fc5626e8f1208 of opensearch-1_1 is not running. Logs:


* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':distribution:docker:integTest'.
```

I tried cleaning up docker containers but this issue keeps happening. Not sure if there is some problem with my environment or a bigger issue.

**To Reproduce**
1. Run `./gradlew check` on OpenSearch

**Expected behavior**
The check and clean should run successfully.

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**
 - OS: Linux
 - Version

**Additional context**

**Comment by tlfeng** [comment]
I also suffered from the `./gradlew clean` failed after `./gradlew check` was interrupted or failed, maybe only a system reboot can recover. 😒 Since then, I tried avoiding using Ctrl+C to terminate the `./gradlew check` process, in case the cleaning up procedure of a test is not triggered. 😅

**Comment by VachaShah** [comment]
I tried that too, but the `':qa:remote-clusters:clean'` and `':distribution:docker:integTest'` keeps failing for me in the gradle check.

**Comment by tlfeng** [comment]
That's so annoying even the problem is not solved after system reboot. 🙁 
I think the ultimate solution for the issue should be enhancing those tests so that they can start whatever the current status is. and also don't leave leftover. My comment mainly aims to prove the issue is present, instead of being closed. 😏

**Comment by reta** [comment]
@VachaShah Sad to admit, but I also see a similar problems from time to time when build fails, the majority of them (for me) are related to the fact that some files are created by `root` user (everything points - Docker to blame), so the cleanup tasks cannot remove or overwrite them. If you still have the problematic build available, could you please share the owners of the files/folders:

```
ls -Alc /home/ubuntu/OpenSearch/distribution/docker/build/
ls -Alc /home/ubuntu/OpenSearch/distribution/docker/build/ 
```
Thank you.

**Comment by VachaShah** [comment]
> @VachaShah Sad to admit, but I also see a similar problems from time to time when build fails, the majority of them (for me) are related to the fact that some files are created by `root` user (everything points - Docker to blame), so the cleanup tasks cannot remove or overwrite them. If you still have the problematic build available, could you please share the owners of the files/folders:
> 
> ```
> ls -Alc /home/ubuntu/OpenSearch/distribution/docker/build/
> ls -Alc /home/ubuntu/OpenSearch/distribution/docker/build/logs
> ```
> 
> Thank you.

@reta I don't have the problematic build available but for me as well, it is the same problem. The build folders created under `root` user and the cleanup is not able to perform any actions on them.

**Comment by reta** [comment]
Thanks @VachaShah , I will try to look into it shortly, but for now the workaround I have to use is `sudo` + manual remove :-(  (if it helps)

**Comment by reta** [comment]
Ok, @VachaShah at least this particular issue is clear, the `composeUp` needs  `preProcessFixture` to be executed before, otherwise the folders:

```
distribution/docker/build/logs/1
distribution/docker/build/logs/2
```

won't exists and will be created by `Docker` under `root` user:

```
drwxrwxr-x 3 user.user user.user 4.0K Nov 29 15:40 classes
drwxrwxr-x 4 user.user user.user 4.0K Nov 30 10:03 docker
drwxrwxr-x 3 user.user user.user 4.0K Nov 29 15:38 forbidden-apis-config
drwxrwxr-x 3 user.user user.user 4.0K Nov 29 15:40 generated
drwxrwxr-x 2 user.user user.user 4.0K Nov 29 15:45 heapdump
drwxr-xr-x 4 root         root         4.0K Dec 14 11:24 logs
drwxrwxr-x 2 user.user user.user 4.0K Nov 29 15:44 markers
drwxrwxrwx 2 user.user user.user 4.0K Dec 13 09:20 repo
drwxrwxr-x 4 user.user user.user 4.0K Nov 29 15:45 reports
```

The fix is on the way

**Comment by VachaShah** [comment]
> Ok, @VachaShah at least this particular issue is clear, the `composeUp` needs `preProcessFixture` to be executed before, otherwise the folders:
> 
> ```
> distribution/docker/build/logs/1
> distribution/docker/build/logs/2
> ```
> 
> won't exists and will be created by `Docker` under `root` user:
> 
> ```
> drwxrwxr-x 3 user.user user.user 4.0K Nov 29 15:40 classes
> drwxrwxr-x 4 user.user user.user 4.0K Nov 30 10:03 docker
> drwxrwxr-x 3 user.user user.user 4.0K Nov 29 15:38 forbidden-apis-config
> drwxrwxr-x 3 user.user user.user 4.0K Nov 29 15:40 generated
> drwxrwxr-x 2 user.user user.user 4.0K Nov 29 15:45 heapdump
> drwxr-xr-x 4 root         root         4.0K Dec 14 11:24 logs
> drwxrwxr-x 2 user.user user.user 4.0K Nov 29 15:44 markers
> drwxrwxrwx 2 user.user user.user 4.0K Dec 13 09:20 repo
> drwxrwxr-x 4 user.user user.user 4.0K Nov 29 15:45 reports
> ```
> 
> The fix is on the way

Thank you @reta for looking into this!
