### ISSUE TITLE
[BUG] Dashboards 2.18 Release

### ISSUE THREAD

**Issue by SebastianThorn** [opensearch-project/OpenSearch#16767]
### Describe the bug

https://github.com/opensearch-project/OpenSearch-Dashboards/issues/8982

### Related component

Other

### Expected behavior

Dashboards to release on github at the same time as opensearch.

**Comment by dblock** [comment]
AFAIK everything was released, but either way https://github.com/opensearch-project/OpenSearch-Dashboards/issues/8982 is the right place for the issue, closing this one.
