### ISSUE TITLE
[BUG] no permissions for [] and User [name=admin, backend_roles=[admin], requestedTenant=null] on .opensearch-cluster-control 

### ISSUE THREAD

**Issue by boomcubist** [opensearch-project/OpenSearch#16872]
### Describe the bug

Following upgrade to 2.18.0 on a single node cluster the .opensearch-cluster-control has number_of_replicas: "1". 

Attempting to change this to number_of_replicas: "0" returns the following error even for the initial admin user. 

{
    "error": {
        "root_cause": [
            {
                "type": "security_exception",
                "reason": "no permissions for [] and User [name=admin, backend_roles=[admin], requestedTenant=null]"
            }
        ],
        "type": "security_exception",
        "reason": "no permissions for [] and User [name=admin, backend_roles=[admin], requestedTenant=null]"
    },
    "status": 403
}

### Related component

Indexing:Replication

### To Reproduce

curl --location --request PUT 'https://<url>/.opensearch-control-center/_settings' \
--header 'Content-Type: application/json' \
--header 'Authorization: Basic xxx' \
--data '{"index.number_of_replicas":0}'

### Expected behavior

The number of replicas should change from 1 to 0.

### Additional Details

**Host/Environment (please complete the following information):**
 - OS: Container runnning on Docker on Rocky Linux 9.4
 - Version 2.18.0

**Comment by cwperks** [comment]
Regular users are not able to access system indices and make changes. If you need direct access to a system index, you need to use the admin certificate when making a request: https://opensearch.org/docs/latest/security/configuration/system-indices/

Closing this issue.
