### ISSUE TITLE
[BUG] Failure to add Azure snapshot repository

### ISSUE THREAD

**Issue by PaulLesur** [opensearch-project/OpenSearch#1735]
**Describe the bug**
We get 500 when we try to register an Azure storage container as a snapshots repository

**To Reproduce**
Follow these steps:
```
curl -sS -XPUT -H "Content-Type: application/json" -d '{"type":"azure","settings":{"client": "default", "container": "prod-snapshots-os"}}' http://localhost:9200/_snapshot/prod-snapshots-os;
```
The request returns : 
```
{
  "error": {
    "root_cause": [
      {
        "type": "repository_verification_exception",
        "reason": "[prod-snapshots-os] cannot delete test data at "
      }
    ],
    "type": "repository_verification_exception",
    "reason": "[prod-snapshots-os] cannot delete test data at ",
    "caused_by": {
      "type": "rejected_execution_exception",
      "reason": "event executor terminated",
      "suppressed": [
        { "type": "exception", "reason": "#block terminated with an error" }
      ]
    }
  },
  "status": 500
}
```

**Expected behavior**
Get a 200.

**Plugins**
- azure repository plugin
- disabled: security plugin

**Host/Environment (please complete the following information):**
 - Docker image: opensearchproject/opensearch:1.2.1
 - Version 1.2.1

**Aditionnal information**
Even if we get an error, the repo is added to the list of repos (we can see it with a GET _cat/repositories). We are able to make snapshots successfuly.

**Comment by PaulLesur** [comment]
Probably a duplicate of #1734

**Comment by reta** [comment]
@PaulLesur yes, that is the same reason
