### ISSUE TITLE
Release including log4j 2.16.0

### ISSUE THREAD

**Issue by mattlorimor** [opensearch-project/OpenSearch#1743]
A release including the already-merged log4j bump to 2.16.0 should probably be created sooner rather than later: https://www.praetorian.com/blog/log4j-2-15-0-stills-allows-for-exfiltration-of-sensitive-data/

**Comment by dblock** [comment]
Actively working on it, ETA is ASAP, please see https://github.com/opensearch-project/opensearch-build/issues/1333.
closing as dup

**Comment by mattlorimor-bnch** [comment]
@dblock - Thanks! Apologies, hadn't seen the build!

**Comment by dblock** [comment]
@mattlorimor-bnch No apology needed, there's a lot going on!
