### ISSUE TITLE
[CI] oldClusterTest fails intermittently

### ISSUE THREAD

**Issue by dblock** [opensearch-project/OpenSearch#1793]
**Describe the bug**

```
* What went wrong:
Execution failed for task ':qa:full-cluster-restart:v1.3.0#oldClusterTest'.
> `node{:qa:full-cluster-restart:v1.3.0-0}` failed to wait for ports files after 120000 MILLISECONDS
```

https://github.com/opensearch-project/OpenSearch/pull/1791#issuecomment-999800839

**Comment by dblock** [comment]
https://github.com/opensearch-project/OpenSearch/pull/1725

**Comment by owaiskazi19** [comment]
@reta is this issue related to https://github.com/opensearch-project/OpenSearch/issues/1826?

**Comment by reta** [comment]
@owaiskazi19 hm ... no, I believe it is closely related to https://github.com/opensearch-project/OpenSearch/issues/1806, but I could be mistaken

**Comment by andrross** [comment]
No references in over a year. Closing.
