### ISSUE TITLE
Replace attribute keys for netty channel

### ISSUE THREAD

**Issue by marevol** [opensearch-project/OpenSearch#1795]
**Is your feature request related to a problem? Please describe.**

Netty4HttpServerTransport uses es-http-channel and es-http-server-channel as an attribute key for netty channel.
This `es-` is a prefix of elasticsearch.
I think it's better to use other names, such as `opensearch-`.

**Describe the solution you'd like**

The fix is like this: https://github.com/marevol/OpenSearch/commit/38b6e65481596822322c6aa065fac847c0bb2731

**Describe alternatives you've considered**

None.

**Additional context**

None.

**Comment by adnapibar** [comment]
@marevol  thanks for the issue, would you like to create the PR?

**Comment by marevol** [comment]
Yes, I'll create it.

**Comment by andrross** [comment]
Resolved in https://github.com/opensearch-project/OpenSearch/pull/1799
