### ISSUE TITLE
"build_hash" : "unknown" in Opensearch 1.2.3 

### ISSUE THREAD

**Issue by balar06** [opensearch-project/OpenSearch#1833]
Title: "build_hash" : "unknown" in Opensearch 1.2.3

We have built the OpenSearch 1.2.3 source code using "./gradlew assemble -Dbuild.snapshot=false"
The build was successful and a non-snapshot version was generated,
but I see "build_hash" : "unknown", in Rest GET / API call.

**To Reproduce**
Downloaded source code : https://github.com/opensearch-project/OpenSearch/releases/tag/1.2.3
./gradlew assemble -Dbuild.snapshot=false
Used no-jdk-linux-tar (Dir: opensearch/distribution/archives/no-jdk-linux-tar/build/distributions)

rest api GET method returns below o/p with "build_hash" : "unknown",
rest GET /
{
"name" : "eric-data-search-engine-data-0",
"cluster_name" : "eric-data-search-engine",
"cluster_uuid" : "G-5gK8QFT7WJ3Mfr2HMVVQ",
"version" : {
"number" : "7.10.2",
"build_type" : "tar",
"build_hash" : "unknown",
"build_date" : "2021-12-27T09:04:55.654676Z",
"build_snapshot" : false,
"lucene_version" : "8.10.1",
"minimum_wire_compatibility_version" : "6.8.0",
"minimum_index_compatibility_version" : "6.0.0-beta1"
},
"tagline" : "The OpenSearch Project: https://opensearch.org/"
}

**Expected behavior**
rest api GET method should return some "build_hash" : "xxxxx",

**Host/Environment 
- OS: no-jdk-linux-tar
- Version 1.2.3

Note: we have used the same procedure to build OS 1.0.0.

**Comment by dblock** [comment]
This looks suspicious, did you get a chance to debug it? AFAIK this just returns current version `.hash()`.

**Comment by balar06** [comment]
sorry, haven't debug.
I have downloaded the tar.gz file from https://opensearch.org/versions/opensearch-1-2-3.html and tested it.
facing the same issue.
 rest GET /
{
  "name" : "eric-data-search-engine-ingest-tls-865464d8fc-9bhlk",
  "cluster_name" : "eric-data-search-engine",
  "cluster_uuid" : "aQVf6McmR6CNAOpJIsMphw",
  "version" : {
    "number" : "7.10.2",
    "build_type" : "tar",
    "build_hash" : "unknown",
    "build_date" : "2021-12-27T09:04:55.654676Z",
    "build_snapshot" : false,
    "lucene_version" : "8.10.1",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "The OpenSearch Project: https://opensearch.org/"
}



followed the same procedure to build OS 1.0.0 source code, this issue was not happening in OS 1.0.0.

**Comment by dblock** [comment]
I'll move it to OpenSearch, something has changed.

**Comment by balar06** [comment]
Do we have any update?

**Comment by dblock** [comment]
> Do we have any update?

I don't think anyone is looking at this, appreciate if someone/you could.

**Comment by dblock** [comment]
I am having hard time reproducing this, but I have definitely seen this elsewhere. Something else is going on. 

@balar06 care to help?

```
$ uname -a
Linux ip-172-31-42-1 5.11.0-1027-aws #30~20.04.1-Ubuntu SMP Thu Jan 13 11:46:53 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

$ wget https://artifacts.opensearch.org/releases/bundle/opensearch/1.2.3/opensearch-1.2.3-linux-x64.tar.gz
tar vfxz opensearch-1.2.3-linux-x64.tar.gz

$ cd opensearch-1.2.3
$ ./opensearch-tar-install.sh

$ curl -k https://localhost:9200 -uadmin:admin
{
  "name" : "ip-172-31-42-1",
  "cluster_name" : "opensearch",
  "cluster_uuid" : "7FRzJ7m4T469KW_dLBOrlg",
  "version" : {
    "distribution" : "opensearch",
    "number" : "1.2.3",
    "build_type" : "tar",
    "build_hash" : "8a529d77c7432bc45b005ac1c4ba3b2741b57d4a",
    "build_date" : "2021-12-21T01:36:21.407473Z",
    "build_snapshot" : false,
    "lucene_version" : "8.10.1",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "The OpenSearch Project: https://opensearch.org/"
}

**Comment by dblock** [comment]
This is likely coming from https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/Build.java#L115 which looks suspiciously over-engineered for returning a build hash, we just need a reliable way to reproduce.

**Comment by minalsha** [comment]
@balar06 how can we reproduce this issue? Do you still see this issue on latest OpenSearch 2.1 or OpenSearch 1.3.4 ?

**Comment by balar06** [comment]
later I haven't faced this issue.

**Comment by dblock** [comment]
Let's close.
