### ISSUE TITLE
Add wait_for_completion flag to snapshot delete api

### ISSUE THREAD

**Issue by b-lancaster** [opensearch-project/OpenSearch#1836]
**Is your feature request related to a problem? Please describe.**

We keep a retention period of 90 days for our snapshots and use a lambda function to delete any snapshots outside of that period. When using the API to delete snapshots, there are a couple of issues
1. Timeouts
2. Prevented from making other calls because one is in progress

**Describe the solution you'd like**

It would be nice to have the wait_for_completion flag added to the snapshot delete API so that we can move forward with other tasks. 

**Describe alternatives you've considered**

Alternatively, we have set specific wait periods using AWS lambda after making the api call, however it seems that the time required for a snapshot to delete often varies from 30s to 10m and theres no way of knowing how long it could take

**Comment by andrross** [comment]
Are you looking for something with the same semantics as the `wait_for_completion` flag that can be [passed to the API to create a snapshot](https://opensearch.org/docs/latest/opensearch/snapshot-restore/#take-snapshots)? Will the flag be useful to you in cases where the delete operation takes multiple minutes (because synchronous APIs tend not to work well for use cases like that)?

**Comment by andrross** [comment]
@b-lancaster Can you also detail the scenarios where delete takes 30 seconds to 10 minutes? I ran a couple tests locally and the delete operation is completing quite quickly.

**Comment by b-lancaster** [comment]
@andrross Sorry for the delayed response. Originally we thought that the `wait_for_completion` flag would be the solution but after some further investigation, we found that the API is not what's causing the issue. We use the [curator](https://github.com/elastic/curator) provided by Elastic and that is what is causing our problems because it is trying to delete the same snapshot multiple times within a very short amount of time. Our cloudwatch logs made it seem as though adding the flag would help but to your point, trying to run the synchronous APIs wouldnt work (Because thats pretty much what it's doing now).

I appreciate your responses and willingness to help!
