### ISSUE TITLE
[BUG] Compiling AD Plugin failing since several packages are missing

### ISSUE THREAD

**Issue by amitgalitz** [opensearch-project/OpenSearch#1851]
**Describe the bug**
Compiling the Opensearch AD plugin fails on several missing packages errors.
The main packages that are getting a "does not exist" error after running `./gradlew :build` on the AD plugin are `org.apache.commons.lang3.*`. This results in `error: cannot find symbol` for code that uses the imported packages. When further inspecting the code on the IDE. Different imports of packages such as `org.opensearch.test.OpenSearchIntegTestCase`, `org.opensearch.common.unit.TimeValue`,  `org.opensearch.common.xcontent.NamedXContentRegistry`, `org.opensearch.common.xcontent.XContentParser`
`opensearch.jobscheduler.spi.JobSchedulerExtension` can't be resolved, however this isn't shown when AD build workflow fails.
**To Reproduce**
1. Clone the AD plugin repo from main
2. run `./gradlew :build`
3. See compile error

or re-run this workflow: [here](https://github.com/opensearch-project/anomaly-detection/runs/4694198083?check_suite_focus=true)

**Expected behavior**
AD plugin should be compiled and built

**Screenshots**

Failing workflow example: [here](https://github.com/opensearch-project/anomaly-detection/runs/4694198083?check_suite_focus=true)

![Screen Shot 2022-01-05 at 1 35 39 PM](https://user-images.githubusercontent.com/67072393/148270376-8514be6e-0f22-4ab7-be62-26cd2eaf6649.png)

**Host/Environment (please complete the following information):**
 - OS: [Linux 5.4.156-94.273.amzn2int.x86_64
 - Opensearch 1.3.0 snapshot used

**Additional context**
There has been no changes to AD that seemed to cause this issue and AD CI has started to fail the past few days on some packages that should be imported from opensearch.

**Comment by saratvemulapalli** [comment]
@amitgalitz thanks for reporting this. Could you also add details on the version of OpenSearch you are seeing problems with?
I assume 1.2.* is fine?

**Comment by amitgalitz** [comment]
> @amitgalitz thanks for reporting this. Could you also add details on the version of OpenSearch you are seeing problems with? I assume 1.2.* is fine?

The workflow we have right now actually uses 1.3.0

**Comment by saratvemulapalli** [comment]
@amitgalitz could you try including `org.apache.commons:commons-lang3:3.9` explicitly in AD build.gradle dependencies? 
Looks like only a couple of plugins have been using it in OpenSearch but it's not imported across the project. 

The next question which pops on to my mind is, how did this work for OpenSearch releases < 1.3.0. 
My best guess is that it being imported by a transitive dependency. 

```
./plugins/repository-hdfs/build.gradle:  api 'org.apache.commons:commons-lang3:3.7'
./plugins/ingest-attachment/build.gradle:  api 'org.apache.commons:commons-lang3:3.9'
./plugins/repository-azure/build.gradle:  api 'org.apache.commons:commons-lang3:3.4'
```

**Comment by ylwu-amzn** [comment]
Checked AD 1.2.4, the dependency `org.apache.commons:commons-lang3` is introduced by `opensearch-job-scheduler-spi`. But seems it's removed from `opensearch-job-scheduler-spi-1.3.0`.

**Comment by saratvemulapalli** [comment]
> Checked AD 1.2.4, the dependency `org.apache.commons:commons-lang3` is introduced by `opensearch-job-scheduler-spi`. But seems it's removed from `opensearch-job-scheduler-spi-1.3.0`.

That makes sense. Thanks @ylwu-amzn !
Closing this.
