### ISSUE TITLE
Add regex interval

### ISSUE THREAD

**Issue by mattweber** [opensearch-project/OpenSearch#1858]
**Is your feature request related to a problem? Please describe.**
Add a regex interval provider.

**Describe the solution you'd like**
Add a regex interval provider that ultimately uses the lucene `Intervals.multiterm(Automaton automaton, int maxExpansions, String pattern)` api.

**Describe alternatives you've considered**
Making intervals pluggable.

**Additional context**
None

**Comment by mattweber** [comment]
BTW, I am willing to do this work if it has a chance of being accepted.

**Comment by dblock** [comment]
Nice work @mattweber !
