### ISSUE TITLE
Integration with MISP

### ISSUE THREAD

**Issue by pietrogu** [opensearch-project/OpenSearch#1865]
Hi,

it is possible (or it would be) to easily integrate Opensearch with MISP?

I was thinking about  automatically import data from MISP and use them to enrich data: for example, if a document contains an IP which is also in MISP, a "is_misp" field will be setted to true. 
Or maybe realize an alerting rule if something matchet with MISP

Thanks,
Pietro

**Comment by anasalkouz** [comment]
Hi @pietrogu, Thanks for reaching out. I think this is a specific use-case that be handled inside your application.

**Comment by anasalkouz** [comment]
Closing this issue. Please feel free to re-open incase you have more questions.

**Comment by pietrogu** [comment]
Hi,

the example are sure personal use-cases, but the question was if there is a native way to integrate MISP and Opensearch or the only way in this moment is to build a custom service to do it.

So, should I assume that this integration is not possible natively right now?
Thank you again
