### ISSUE TITLE
[BUG] ignore_malformed parameter on ip_range data_type throws mapper_parsing_exception

### ISSUE THREAD

**Issue by SaiSatwik** [opensearch-project/OpenSearch#1873]
**Describe the bug**

Using ignore_malformed on a dynamic_template mapping of `ip_range` data_type throwing mapper_parsing_exception when trying to index a document with a new field that matches the template.
This used to work fine with elasticsearch 7.1.1 but creating an issue with opensearch 1.2.2. 

Seems this is a known issue in elasticsearch 7.10.1 (from which opensearch has been forked) and issue has been resolved in elasticsearch 7.11. Link for the issue on elasticsearch https://github.com/elastic/elasticsearch/issues/66765.

**To Reproduce**

1. Index creation & Mapping
```
PUT /my_index
{
    "mappings": {
        "dynamic_templates": [
            {
                "ip_range": {
                    "match": "*ip_range",
                    "mapping": {
                        "type": "ip_range",
                        "ignore_malformed": true
                    }
                }
            }
        ]
    }
}
```
2. Creating a document
PUT /my_index/_doc/1
```
{
    "source_ip_range": "192.168.1.1/32"
}
```
Output:
```
{
    "error": {
        "root_cause": [
            {
                "type": "mapper_parsing_exception",
                "reason": "unknown parameter [ignore_malformed] on mapper [source_ip_range] of type [ip_range]"
            }
        ],
        "type": "mapper_parsing_exception",
        "reason": "unknown parameter [ignore_malformed] on mapper [source_ip_range] of type [ip_range]"
    },
    "status": 400
}
```

**Expected behavior**
Indexing of ip_range should not throw any error.

**Plugins**
No plugins are used

**Screenshots**
Nil

**Host/Environment (please complete the following information):**
 - OS: [e.g. iOS] Mac
 - Version [e.g. 22] 11.4

**Additional context**
Please let us know if there is any workaround. In case of not a bug, please let us know what changes we need to do in order to ignore_malformed field_value without effecting the indexing of the document.

**Comment by deng47** [comment]
I think I encounter the same issue. I set `ignore_malformed` on the index level
```
"settings": {
    "index.mapping.ignore_malformed": true 
  }
```
However, when I reindex data from Elasticsearch to pensearch, it failed like below
```
"failures" : [
      {
        "index" : "log-reindex-000002",
        "type" : "_doc",
        "id" : "OGhp5WsBbP2HYYS8ruYn",
        "cause" : {
          "type" : "mapper_parsing_exception",
          "reason" : "object mapping for [NL] tried to parse field [NL] as object, but found a concrete value"
        },
        "status" : 400
      }
    ]
```

**Comment by reta** [comment]
@dblock @anasalkouz I will take a look at it
