### ISSUE TITLE
Improve javadoc on SortSpec to inform use of preferredName as a unique key

### ISSUE THREAD

**Issue by nknize** [opensearch-project/OpenSearch#1905]
PR #1856 enhanced the [SearchPlugin](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/plugins/SearchPlugin.java) to enable pluggable SortBuilders. The mechanism uses a new `SortSpec` to define the specification of the builder and parser and exposes through the named registry. This named registry keys the sort specification off the `preferredName` which is required to be unique. Contributors may not be aware of other sort builders that share the same name. 

This issue is to improve the javadocs to provide better documentation of this requirement.

relates #221

**Comment by andrross** [comment]
Resolved by #1909
