### ISSUE TITLE
Support for code coverage in Integ Test

### ISSUE THREAD

**Issue by ankitkala** [opensearch-project/OpenSearch#1928]
**Is your feature request related to a problem? Please describe.**
We rely on Integration tests for most of the testing for cross-cluster-replication plugin. We're tying to add code coverage to our repo using jacoco plugin but it doesn't work as the test clusters are on separate JVM and jacoco agent doesn't get attached to the Opensearch process locally.
Alerting and ISM ran into same issue and are currently using a workaround that works for testing with single node. But the same won't work for us as we need multiple clusters for testing.
- https://github.com/opensearch-project/alerting/blob/main/alerting/build.gradle#L306-L309
- https://github.com/opensearch-project/index-management/blob/c739190a9f807232cc500acd12bc1f57d5d37c7e/build-tools/coverage.gradle#L6-L18

**Describe the solution you'd like**
We'd like to have the support to make jacoco work with TestClusters.
We should be able to get all the java agents on the process that executes the integTest and also pass those to TestClusters. My guess is that it should work but we haven't tried it out yet. 
Also open to any alternative suggestion.

**Comment by ankitkala** [comment]
PRs for the fix: 
- Add code coverage to CCR plugin: https://github.com/opensearch-project/cross-cluster-replication/pull/284
- Add hook to execute custom logic before Integ test task starts: https://github.com/opensearch-project/OpenSearch/pull/1969

**Comment by dblock** [comment]
@ankitkala What remains to be done here? Document? Close?

**Comment by minalsha** [comment]
@ankitkala  I am closing this issue since you have PRs merged. Feel free to reopen if you still have any questions to discuss. thanks
