### ISSUE TITLE
[BUG] Can't use mockK for unit test

### ISSUE THREAD

**Issue by ankitkala** [opensearch-project/OpenSearch#1929]
**Describe the bug**
For cross-cluster-replication, we want to improve the unit tests. Since its a kotlin plugin, the ability to use mockK will simplify writing UTs significantly. 
Currently if we try to introduce the dependency, we're running into jarHell issue

```
Caused by: java.lang.IllegalStateException: jar hell!
class: org.objenesis.ObjenesisHelper
```
Objenesis jars are packaged with secureMock which is also a dependency of mockK.

**To Reproduce**
Add mockK dependency to OS or any plugin and run unit tests.

**Expected behavior**
Support for adding mockK dependency should be available.

**Comment by dblock** [comment]
Adding the dependency to OpenSearch proper won't solve the jarhell problem, there's a version incompatibility in a dependency (objenesis?), you should be able to force that dependency to match the version that comes from OpenSearch.

**Comment by minalsha** [comment]
@ankitkala  what is causing JarHell? Is it conflicting with Java Mockito?

**Comment by ankitkala** [comment]
Correct. Objenesis jars which are packaged with secureMock cause this issue. I'll close this issue now as we got around this by relying on integ tests entirely.
