### ISSUE TITLE
Unable to load CSV files successfully when CSV file size reaches 1 million records

### ISSUE THREAD

**Issue by FrankXia** [opensearch-project/OpenSearch#1947]
**Describe the bug**

We tried load data from a S3 bucket contains 10 CSV files with each containing 1 million records. It failed to finish the job with following error message: 

[Spark task failed due to an exception. Stack trace: {0}] ["org.elasticsearch.hadoop.rest.EsHadoopInvalidRequest: org.elasticsearch.hadoop.rest.EsHadoopRemoteException: rejected_execution_exception: rejected execution of coordinating operation (coordinating_and_primary_bytes=0, replica_bytes=0, all_bytes=0, coordinating_operation_bytes=108113911, max_coordinating_and_primary_bytes=107374182):::LF:::
{"index":{"_index":"esri-ds-data_86dc7bb1-b991-44fb-8e52-be5069629fb0_es-7-3-0_202201","_type":"_doc"}}:::LF:::
{"---geo_hash---":(-43.85883,68.79605),"col_6":734,"Geometry":(-43.85883,68.79605),"---timestamp---":1641919673572,"col_3":205.37,"col_4":5230.94,"col_7":"Nejanilini Lake Airport","objectid":5320000,"globalid":"{75C82AB7-F94E-65BA-F605-A28B51F1E165}","col_10":-43.85883,"col_5":94.29,"col_9":-1,"col_11":68.79605,"col_1":733,"col_8":"Athen Helenikon Airport","col_2":1512098658447}:::LF:::{"index":{"_index":"esri-ds-data_86dc7bb1-b991-44fb-8e52-be5069629fb0_es-7-3-0_202201","_type":"_doc"}}:::LF::: ... ... 

However, the same Spark app works perfectly fine with Elasticsearch 7.10.2 cluster.  

**To Reproduce**

**Expected behavior**

The Index should show exactly 10 million records. 

**Plugins**
No plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**
 - OS: Ubuntu 18.04.6 LTS
 - Version: 18.04.6
 -  Architecture:  amd64
 - Kernel Version:  5.4.0-1062-azure

**Additional context**
The OpenSearch was running in a Kubernestes cluster.

**Comment by reta** [comment]
@FrankXia The Opensearch has introduced additional Indexing Back-Pressure (see please https://github.com/opensearch-project/OpenSearch/issues/478) logic in order to stabilize cluster behaviour under heavy load / heavy queries. It seems like you have triggered memory back-pressure conditions, you could:
 - increase server JVM memory settings
 - tailor "**indexing_pressure.memory.limit**"  setting (default is set to **10%** of the max heap)

**Comment by FrankXia** [comment]
Thanks @reta for the advice, I was able to resolve the problem with doubling the JVM memory in all Master nodes.
