### ISSUE TITLE
[BUG] gradle precommit is broken due to transportClientRatio

### ISSUE THREAD

**Issue by saratvemulapalli** [opensearch-project/OpenSearch#1954]
**Describe the bug**
Gradle precommit on local desktop is broken

```
/home/ubuntu/sarat-opensearch/server/src/test/java/org/opensearch/cluster/routing/MovePrimaryFirstTests.java:23: error: cannot find symbol
@OpenSearchIntegTestCase.ClusterScope(scope = OpenSearchIntegTestCase.Scope.TEST, numDataNodes = 0, transportClientRatio = 0)
                                                                                                    ^
  symbol:   method transportClientRatio()
  location: @interface ClusterScope
```

Not sure why GHA action for precommit is going through. But its quite reproducible on local machine.
**To Reproduce**
1. Checkout OpenSearch
2. Run `./gradlew precommit`

**Host/Environment (please complete the following information):**
 - OS: Mac OS BigSur, Ubuntu (Linux)

**Comment by saratvemulapalli** [comment]
This is now fixed in main.
The changes are not backported yet to 1.x: https://github.com/opensearch-project/OpenSearch/pull/1445
@jainankitk can you take care of this when you back port it to 1.x.

Another follow up question, I do not know why GHA for Precommit passes consistently while on local it consistently fails.

**Comment by jainankitk** [comment]
@saratvemulapalli - Sure, thanks!

**Comment by jainankitk** [comment]
@saratvemulapalli - My bad, I missed it. Thanks for taking care of this!
