### ISSUE TITLE
Need to support POST method for Search template

### ISSUE THREAD

**Issue by AlanYuXuan** [opensearch-project/OpenSearch#1960]
**Is your feature request related to a problem? Please describe.**
We used to use GET method + search template to get the result and we find in elasticsearch 7.13 it supports POST + search template. We had tested that if using this method the connection will keep alive not close. https://www.elastic.co/guide/en/elasticsearch/reference/7.13/search-template-api.html#search-template-api

**Describe the solution you'd like**
Support this api in opensearch client

**Describe alternatives you've considered**
No

**Additional context**
No

**Comment by CEHENKLE** [comment]
Hi @AlanYuXuan !  Can you give us more information about the use case you're trying to solve?  Is keeping the connection alive critical to your use case?

Thanks!

**Comment by dblock** [comment]
@AlanYuXuan I am personally not against supporting both GET and POST for the same queries, but you should be able to keep-alive on GETs too. Are you seeing different headers in one vs. the other? Is the client library you're using configured not to keep-alive on GET?

**Comment by anasalkouz** [comment]
Closing this issue, due to lack of information. @AlanYuXuan please feel free reopen once you have more details and answers for the existing questions.
