### ISSUE TITLE
[Remove] Type mapping param from REST end-points

### ISSUE THREAD

**Issue by dreamer-89** [opensearch-project/OpenSearch#1996]
Remove type param from REST end-points

- [ ] #1999
- [x] #2003
- [ ] #2002
- [ ] #2004
- [ ] RestUpdateByQueryAction
- [ ] RestGetFieldMappingAction
- [ ] RestGetMappingAction
- [ ] RestPutMappingAction
- [ ] RestValidateQueryAction
- [ ] RestBulkAction
- [ ] RestDeleteAction
- [ ] RestGetAction
- [ ] RestGetSourceAction
- [x] #2010
- [ ] #2014
- [ ] #1997
- [ ] RestMultiTermVectorsAction
- [ ] RestTermVectorsAction
- [ ] #2028
- [ ] search/RestCountAction
- [ ] RestExplainAction
- [ ] RestMultiSearchAction
- [ ] RestSearchAction

**Additional context**
Parent: https://github.com/opensearch-project/opensearch/issues/1940

**Comment by dblock** [comment]
Let's not create individual issues for each one of these, it's hard to grok from the issue what needs to be done. The parent is plenty to track progress and PRs can just link back to it and we can check [x] boxes here once they are merged?

**Comment by dreamer-89** [comment]
Closing this issue, as meta (#1940 ) is already tracking each rest action.
