### ISSUE TITLE
Which is better ElasticSearch or OpenSearch?

### ISSUE THREAD

**Issue by Chetan11-dev** [opensearch-project/OpenSearch#2006]
For creating an ecommerce application is opensearch better?

**Comment by jkowall** [comment]
It really depends on whether you want something open source or not. Functionality wise, they are very close to one another. If you provide more details on the application you are trying to make, I would be happy to provide more details.

**Comment by CEHENKLE** [comment]
Hi @Chetan11-dev Well, this is the OpenSearch project, so we're probably a little biased over here :)

I'd suggest you take a look at the getting started documentation for OpenSearch and for Elastic, download them both and try them out.  You could also ask in the forums what people's experience are with each product.

Thanks!
/C
