### ISSUE TITLE
[BUG] Docker distribution builds are failing

### ISSUE THREAD

**Issue by reta** [opensearch-project/OpenSearch#2023]
**Describe the bug**

Docker distribution builds are failing across the board [1]

```
CentOS Linux 8 - AppStream                      144  B/s |  38  B     00:00    
| [91mError: Failed to download metadata for repo 'appstream': Cannot prepare internal mirrorlist: No URLs in mirrorlist
| [0myum error: retry 1 in 10s
| CentOS Linux 8 - AppStream                      176  B/s |  38  B     00:00    
| [91mError: Failed to download metadata for repo 'appstream': Cannot prepare internal mirrorlist: No URLs in mirrorlist
| [0myum error: retry 2 in 10s
| CentOS Linux 8 - AppStream                      228  B/s |  38  B     00:00    
| [91mError: Failed to download metadata for repo 'appstream': Cannot prepare internal mirrorlist: No URLs in mirrorlist
| [0myum error: retry 3 in 10s
| CentOS Linux 8 - AppStream                      209  B/s |  38  B     00:00    
| [91mError: Failed to download metadata for repo 'appstream': Cannot prepare internal mirrorlist: No URLs in mirrorlist
| [0myum error: retry 4 in 10s
| CentOS Linux 8 - AppStream                      405  B/s |  38  B     00:00    
| [91mError: Failed to download metadata for repo 'appstream': Cannot prepare internal mirrorlist: No URLs in mirrorlist
| [0myum error: retry 5 in 10s
| CentOS Linux 8 - AppStream                       86  B/s |  38  B     00:00    
| [91mError: Failed to download metadata for repo 'appstream': Cannot prepare internal mirrorlist: No URLs in mirrorlist
| [0myum error: retry 6 in 10s
```

It seems like Centos 8, which we use for building Docker images is EOLed [3]. The workarounds for now are 
a) use http://vault.centos.org for repositories 
b)  migrate from CentOS Linux 8 to CentOS Stream 8. 
In the long term, we probably should change the base image.

[1] https://ci.opensearch.org/logs/ci/workflow/OpenSearch_CI/PR_Checks/Gradle_Check/gradle_check_2136.log
[2] https://forums.centos.org/viewtopic.php?f=54&t=78708
[3] https://www.centos.org/centos-linux-eol/

**To Reproduce**
Steps to reproduce the behavior: `./gradlew :distribution:docker:buildDockerImage`

**Expected behavior**
The Docker image should be built successfully

**Plugins**
N/A

**Screenshots**

**Host/Environment (please complete the following information):**
CI or local builds

**Additional context**
N/A

**Comment by AnanthGopal** [comment]
I got the same error, i fixed this error by using below link

https://stackoverflow.com/questions/70926799/centos-through-vm-no-urls-in-mirrorlist

**Comment by Shashwat-05** [comment]
Centos is end of life from 31 dec, 2021. So instead, centos:7 can be used.
