### ISSUE TITLE
Add URL option to InstallPluginCommand help instructions

### ISSUE THREAD

**Issue by lukas-vlcek** [opensearch-project/OpenSearch#2041]
**Is your feature request related to a problem? Please describe.**
The `InstallPluginCommand` tool does not let user know they can use URL as an option to install the plugin from.

**Describe the solution you'd like**
1. Improve the output of `./bin/opensearch-plugin install --help` accordingly
2. Improve the online documentation as well (see below for details)

**Describe alternatives you've considered**
All considered alternatives seem to be less useful. 

**Additional context**

While the JavaDoc of [InstallPluginCommand](https://github.com/opensearch-project/OpenSearch/blob/1.2.4/distribution/tools/plugin-cli/src/main/java/org/opensearch/plugins/InstallPluginCommand.java) does [expliticly document use of URL option](https://github.com/opensearch-project/OpenSearch/blob/1.2.4/distribution/tools/plugin-cli/src/main/java/org/opensearch/plugins/InstallPluginCommand.java#L114) to install plugins from the [help instruction does not](https://github.com/opensearch-project/OpenSearch/blob/1.2.4/distribution/tools/plugin-cli/src/main/java/org/opensearch/plugins/InstallPluginCommand.java#L221).

For the reference this is the output of the command:

```sh
# Assuming OpenSearch 1.2.4
% ./bin/opensearch-plugin install --help
Install a plugin

The following official plugins may be installed by name:
  analysis-icu
  analysis-kuromoji
  analysis-nori
  analysis-phonetic
  analysis-smartcn
  analysis-stempel
  analysis-ukrainian
  discovery-azure-classic
  discovery-ec2
  discovery-gce
  ingest-attachment
  mapper-annotated-text
  mapper-murmur3
  mapper-size
  repository-azure
  repository-gcs
  repository-hdfs
  repository-s3
  store-smb
  transport-nio

Non-option arguments:
plugin id            

Option             Description                                            
------             -----------                                            
-E <KeyValuePair>  Configure a setting                                    
-b, --batch        Enable batch mode explicitly, automatic confirmation of
                     security permission                                  
-h, --help         Show help                                              
-s, --silent       Show minimal output                                    
-v, --verbose      Show verbose output
```

BTW: It is also missing in online Documentation: [Install OpenSearch / OpenSearch plugins](https://opensearch.org/docs/1.2/opensearch/install/plugins/) (I believe this contributes to UX issues like [this one](https://discuss.opendistrocommunity.dev/t/add-exporter-plugin-to-opensearch/7115/5)).

I suggest updating the **Non-option arguments** instructions to:

```
Non-option arguments:
plugin <name|URL>
```
Or something along these line based on <http://jopt-simple.github.io/jopt-simple/> conventions (ideally providing more info about how URL option can be used).

---

Notice: the command help instructions use an **"id"** in **Non-option arguments** part. Maybe a (nitpicking) detail but this can create an impression that besides `plugin name` there is also `plugin id`. The terminology is not consistent which can be confusing.

Actually, the internal class for
[PluginPropertiesExtension](https://opensearch.org/javadocs/1.2.4/OpenSearch/buildSrc/build/docs/javadoc/org/opensearch/gradle/plugin/PluginPropertiesExtension.html) uses the `name`. As far as I can tell all the other places in the code seem to refer to plugin `name` as opposed to plugin `id`. Even the _"sister"_ [RemovePluginCommand](https://github.com/opensearch-project/OpenSearch/blob/1.2.4/distribution/tools/plugin-cli/src/main/java/org/opensearch/plugins/RemovePluginCommand.java#L73) refers to `plugin name`.

On the other hand when the distribution is built the list of (built-in) plugins is [populated from plugins located under the plugins folder](https://github.com/opensearch-project/OpenSearch/blob/e3a44fa71b290fb265a94ef4297f044b9a63a762/server/build.gradle#L205). In this case the `plugin name` is based on folder name which is unique thus the terminology should be IMO leaning towards `plugin id` but that would result into code changes on many places.

**Comment by CEHENKLE** [comment]
@lukas-vlcek Thanks for this call out! :)

**Comment by owaiskazi19** [comment]
Closing this issue. As the related PRs are merged.

**Comment by lukas-vlcek** [comment]
Amazing, thanks! ❤️
