### ISSUE TITLE
Expose Lucene's `Intervals.unorderedNoOverlaps`

### ISSUE THREAD

**Issue by mattweber** [opensearch-project/OpenSearch#2053]
Expose Lucene's `Intervals.unorderedNoOverlaps` from [LUCENE-8828](https://issues.apache.org/jira/browse/LUCENE-8828) which is useful to prevent overlapping issues such as `NEAR(a, a)` matching a document containing a single `a`.

I will do the work required for this change.

**Comment by CEHENKLE** [comment]
@mattweber Thanks, this is a great idea.  Look forward to seeing the PR!
