### ISSUE TITLE
[BUG] Integration tests fail on Linux kernel version 5.16.x

### ISSUE THREAD

**Issue by willyborankin** [opensearch-project/OpenSearch#2061]
**Describe the bug**
The new Kernel version 2.16.x has 5 properties in the file `/sys/fs/cgroup/cpu/cpu.stat` 
as result integration tests fail due to the fact that `OsProbe` class in the method `readSysFsCgroupCpuAcctCpuStat` has such assert:

```java
assert lines != null && lines.size() == 3;
``` 

**To Reproduce**
```bash
./gradlew clean build 
```
for any plugin which has integration tests 

**Expected behavior**
Working integration tests

**Host/Environment (please complete the following information):**
 - OS: `Fedora Linux`
 - Version `35`
 - Kernel `5.16.5-200.fc35.x86_64`

**Comment by willyborankin** [comment]
There are 2 possible solutions t fix this issue:
- just use such assert like it was done in other `OsProbe` methods:
```java
assert lines != null && lines.isEmpty();
```
- add logging to `OsProbe` and log a warning message for missing `cgroups` CPU stats

**Comment by dblock** [comment]
Would appreciate a PR @willyborankin ! Thanks.

**Comment by dblock** [comment]
> I'm on the way. Will try to do it today. A small question does it make sense to extend support for Kernel 5.16 in the `OsProbe` class with additional CPU stat fields?

I don't know what those additional stat fields are to say for sure, but if you think that's useful and easy to do, go for it.

**Comment by willyborankin** [comment]
Sorry for the inconvenience, should've added description or the new properties in the beginning. There are 2 new properties were added:
- `nr_bursts`  - the number of CPU bursts triggered by the child cgroup
- `burst_time` - the cumulative length of CPU burst time for the child cgroup

**Comment by owaiskazi19** [comment]
Hi @willyborankin! I tried running gradle check on CentOS and got the below error for the test `testLogWarnCpuMessageOnlyOnes`
```
  2> REPRODUCE WITH: ./gradlew ':server:test' --tests "org.opensearch.monitor.os.OsProbeTests.testLogWarnCpuMessageOnlyOnes" -Dtests.seed=7047AE5E76B4DB61 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=es-US -Dtests.timezone=Europe/Dublin -Druntime.java=17
  2> Wanted but not invoked:
    logger.warn(<any string>);
    -> at org.opensearch.monitor.os.OsProbeTests.testLogWarnCpuMessageOnlyOnes(OsProbeTests.java:302)

    However, there was exactly 1 interaction with this mock:
    logger.debug(
        "error reading control group stats",
        java.nio.file.NoSuchFileException: /sys/fs/cgroup/cpuacct/docker/977bf74e63e9b9ba50a1e777408ec54d7398b843f8365fb0becb09d2cc5a6724/cpuacct.usage
    );
    -> at org.opensearch.monitor.os.OsProbe.getCgroup(OsProbe.java:588)
        at __randomizedtesting.SeedInfo.seed([7047AE5E76B4DB61:B8D135F609AAE36F]:0)
        at app//org.opensearch.monitor.os.OsProbeTests.testLogWarnCpuMessageOnlyOnes(OsProbeTests.java:302)
```
Do you have any idea for the same?

**Comment by owaiskazi19** [comment]
> Hi @owaiskazi19, what kernel version do you have? and do you have such file `/sys/fs/cgroup/cpu` in you system?

I should have mentioned that. The kernel version is `Linux 5.11.0-1020-aws`, CentOS version is `CentOS Linux release 7.9.2009 (Core)` and yes, I have the above mentioned directory in my system.

**Comment by reta** [comment]
@owaiskazi19 sorry, one more thing, are you running tests in Docker? 

>         java.nio.file.NoSuchFileException: /sys/fs/cgroup/cpuacct/docker/977bf74e63e9b9ba50a1e777408ec54d7398b843f8365fb0becb09d2cc5a6724/cpuacct.usage

**Comment by owaiskazi19** [comment]
Hey @reta! Yes, I'm running the gradle check in Docker and the image is `opensearchstaging/ci-runner:centos7-x64-arm64-jdkmulti-node10.24.1-cypress6.9.1-20211028`.

**Comment by owaiskazi19** [comment]
Created https://github.com/opensearch-project/OpenSearch/issues/2592 for the above issue.
