### ISSUE TITLE
[Meta] Lucene 9 Upgrade Punch List

### ISSUE THREAD

**Issue by nknize** [opensearch-project/OpenSearch#2063]
The following outstanding (and currently muted) test failures still need to be addressed as part of the Lucene 9 upgrade:

- [x] PluginsServiceTests failures due to `AccessControlException`
- [x] CustomUnifiedHighlighterTests
- [x] HighlighterWithAnalyzersTests.testPhrasePrefix
- [x] ChildQuerySearchIT.testHighlightersIgnoreParentChild
- [x] HighlighterSearchIT failures
- [x] IndexShardHotspotTests
- [x] RelocationIT.testRelocationWhileIndexingRandom (seed `-Dtests.seed=6158774967A60B81`)
- [ ] NumberFieldTypeTests.testIndexSortIntRange
- [x] IndexPrimaryRelocationIT (#2488)

relates #1109

**Comment by reta** [comment]
These ones should be fixed now:

CustomUnifiedHighlighterTests
HighlighterWithAnalyzersTests.testPhrasePrefix
ChildQuerySearchIT.testHighlightersIgnoreParentChild
HighlighterSearchIT failures

But we would need to work on accommodating these change: https://github.com/apache/lucene/pull/362/files

**Comment by reta** [comment]
For `NumberFieldTypeTests`, opened https://issues.apache.org/jira/browse/LUCENE-10466

**Comment by reta** [comment]
PluginsServiceTests are green, https://github.com/opensearch-project/OpenSearch/pull/2484

**Comment by reta** [comment]
@nknize I am working on  NumberFieldTypeTests.testIndexSortIntRange

**Comment by nknize** [comment]
IndexShardHotspotTests are passing but this one test is taking upwards of 25 minutes+. @ashwinpankaj can we reduce [this test](https://github.com/opensearch-project/OpenSearch/blob/77d106015fdc28ba29bb758ba76e0cf790f61da3/server/src/test/java/org/opensearch/cluster/routing/allocation/IndexShardHotSpotTests.java#L114) from 100 indices + 5 shards to something much more expedient? 

I don't want to unmute if this is going to kill our tests on each PR.

**Comment by reta** [comment]
:+1: @nknize that's the same cause as NumberFieldTypeTests.testIndexSortIntRange
