### ISSUE TITLE
remove "blank issue" from options

### ISSUE THREAD

**Issue by CEHENKLE** [opensearch-project/OpenSearch#2070]
**Is your feature request related to a problem? Please describe.**
When folks create an issue using the "not seeing your issue?  Create a blank issue" option.  When this happens, the triage label isn't applied, which means we don't see the issue in our triage meeting. 

**Describe the solution you'd like**
Remove the option to create a blank issue by setting blank_issues_enabled to false, per https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository

**Describe alternatives you've considered**
None

**Comment by joshpalis** [comment]
I'll take it
