### ISSUE TITLE
[Enhancement] Allow user to define OPENSEARCH_SD_NOTIFY without hardcoding it to rpm/deb build

### ISSUE THREAD

**Issue by peterzhuamazon** [opensearch-project/OpenSearch#2073]
Follow up from #2043 to build bundled RPM from tarball:

`OPENSEARCH_SD_NOTIFY` does not notify systemctl if the core is built for `tar`.
This only runs if the core is built for `rpm` and `deb`.
https://github.com/opensearch-project/OpenSearch/blob/37ac3788a3937ed415039edb2671da08e6450ed5/modules/systemd/src/main/java/org/opensearch/systemd/SystemdPlugin.java#L80-L84

@dblock any insight on this one?
Thanks.

**Comment by dblock** [comment]
I think the solution is to natively support an RPM/DEB distribution type in OpenSearch, and not build the RPM package based on the tar distribution.

**Comment by peterzhuamazon** [comment]
> I see
> 
> https://github.com/opensearch-project/OpenSearch/blob/37ac3788a3937ed415039edb2671da08e6450ed5/modules/systemd/src/main/java/org/opensearch/systemd/SystemdPlugin.java#L75
> that seems to natively support DEB/RPM?

Remember we are building a tar artifact then use the tar artifact to build deb/rpm with a different toolset.
We are not directly using the existing deb/rpm build in core.

Thanks.
a

**Comment by dblock** [comment]
> Remember we are building a tar artifact then use the tar artifact to build deb/rpm with a different toolset. We are not directly using the existing deb/rpm build in core.

Why?

**Comment by peterzhuamazon** [comment]
Because the default rpm generation does not include all plugins.

**Comment by dblock** [comment]
Ok, what's the _right_ fix that gets rid of all the hacks?

**Comment by peterzhuamazon** [comment]
Use `rpm` to produce core but not package it in build workflow, send the output to assemble workflow to install all plugins then package into a rpm with rpmbuild.
