### ISSUE TITLE
[BUG] mapper_parsing_exception: No handler for type [unsigned_long] declared

### ISSUE THREAD

**Issue by slavafomin** [opensearch-project/OpenSearch#2083]
**Describe the bug**
I've tried to create an index field of the type `unsigned_long`, but got the following error:

```
ResponseError: mapper_parsing_exception: [mapper_parsing_exception] Reason: No handler for type [unsigned_long] declared on field [field-name]
```

**Host/Environment (please complete the following information):**
I'm using latest version of OpenSearch (1.1) managed by AWS.

**Additional context**
The `unsigned_long` type is [defined](https://www.elastic.co/guide/en/elasticsearch/reference/7.10/number.html) in ElasticSearch 7.10 documentation. Isn't OpenSearch based on it?

**Comment by dblock** [comment]
According to that documentation it was only part of X-Pack, which was not APLv2.

**Comment by CEHENKLE** [comment]
@slavafomin Hi!  Would you mind adding more information about your use case?  Thanks!

**Comment by getorca** [comment]
Just ran into this as well trying to migrate from ES to opensearch. I guess the work around is to use a long?

**Comment by ywilkof** [comment]
We have a use case: we are trying to save the result of XXHash algorithm as a number property, and the output of the algorithm is of type unsigned long. These are too big for the long range and these indexing operations fail as a result.

**Comment by reta** [comment]
@ywilkof may I ask you please to share a bit more how you use `the result of XXHash algorithm`, do you search by it fe? The possible options (since the `unsigned_long` is absent) depend on the way this property is being used, thank you.

**Comment by reta** [comment]
> Just ran into this as well trying to migrate from ES to opensearch. I guess the work around is to use a long?

Correct, assuming the value fits into `signed long` interpretation

**Comment by robcowart** [comment]
I will add to the use-cases where unsigned values are important.

It is very common for IT observabillity-related metrics to be counters, which by definition are unsigned values.  In particular for network devices high-capacity, 64-bit counters are common. While 63-bits (the maximum positive value of a 64-bit signed integer) is a very large value, a 400Gb interface's count of bytes can reach the limit of a `long` within 3 years. Aggregated links of such interfaces can reach this limit even quicker. Values will fail to be indexed by OpenSearch once this limit is reached. It isn't uncommon for network equipment to run for many years without being upgraded or restarted, so this is more than just a hypothetical problem.

**Comment by reta** [comment]
@dblock @CEHENKLE will take a look at this issue
