### ISSUE TITLE
Create geonames benchmark data S3 bucket.

### ISSUE THREAD

**Issue by adnapibar** [opensearch-project/OpenSearch#211]
We need to create a bucket and update the README accordingly

https://github.com/opendistro-for-elasticsearch/search/tree/main/client/benchmark#bulk-indexing

**Comment by dblock** [comment]
Does this need a corresponding ticket/belong in https://github.com/opensearch-project/opensearch-build ?

**Comment by minalsha** [comment]
@adnapibar what is needed for this issue to be resolved? I am unable to understand the problem here.

**Comment by adnapibar** [comment]
> @adnapibar what is needed for this issue to be resolved? I am unable to understand the problem here.

Currently the dataset for the benchmarking is downloaded from the S3 bucket hosted by Elastic (http://benchmarks.elasticsearch.org.s3.amazonaws.com/corpora/geonames/documents-2.json.bz2).

The issue is to host the dataset in an OpenSearch managed bucket.

**Comment by dagneyb** [comment]
@adnapibar can you provide details of the impact of this?

**Comment by adnapibar** [comment]
> @adnapibar can you provide details of the impact of this?

The S3 bucket is managed by elastic, which I don't think should be in the README. Also, the S3 URL can change and in that case the instructions in the README will become inaccurate.

**Comment by kotwanikunal** [comment]
Looks like we utilize our own providers now: https://github.com/opensearch-project/opensearch-benchmark-workloads/commit/5b502c1818e3813f8c22d93919d72309b8fa5f03
