### ISSUE TITLE
'runtime_mappings' not supported on query

### ISSUE THREAD

**Issue by fastluca** [opensearch-project/OpenSearch#2144]
The runtime_mappings feature was added as stable on Elasticsearch starting from version [7.12](https://www.elastic.co/guide/en/elasticsearch/reference/7.12/runtime-search-request.html).
Is there something equivalent on OpenSearch? I cannot find nothing on the official documentation about that.
It is a very powerful feature.

**Comment by reta** [comment]
@fastluca please check out this issue https://github.com/opensearch-project/OpenSearch/issues/1133

**Comment by dblock** [comment]
Closing as dup of #1133.
