### ISSUE TITLE
[BUG] :distribution:docker:buildDockerImage failures downloading from http://vault.centos.org

### ISSUE THREAD

**Issue by andrross** [opensearch-project/OpenSearch#2154]
Gradle task :distribution:docker:buildDockerImage fails occasionally with a timeout from http://vault.centos.org

```
| Errors during downloading metadata for repository 'baseos':
|   - Curl error (28): Timeout was reached for http://vault.centos.org/centos/8/BaseOS/x86_64/os/repodata/repomd.xml [Connection timed out after 30001 milliseconds]
|   - Curl error (28): Timeout was reached for http://vault.centos.org/centos/8/BaseOS/x86_64/os/repodata/repomd.xml [Operation too slow. Less than 1000 bytes/sec transferred the last 30 seconds]
|   - Curl error (28): Timeout was reached for https://vault.centos.org/centos/8/BaseOS/x86_64/os/repodata/repomd.xml [Operation timed out after 30000 milliseconds with 0 out of 0 bytes received]
| Error: Failed to download metadata for repo 'baseos': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
```

Example: https://github.com/opensearch-project/OpenSearch/pull/2147#issuecomment-1042492480

**Comment by reta** [comment]
@andrross I think the best we can do is switch to another distribution (question - which one? amazonlinux:2? ubuntu? debian?), @dblock do you have thoughts? thanks!

**Comment by andrross** [comment]
My questions: Is that CentOS endpoint really that flakey? Are we getting throttled or something? Is something else misconfigured on our side?

**Comment by reta** [comment]
CentOS is dead, for better or worst, taking into account we use for 1 week only and it was done already - it looks flaky at this moment. The problem was affecting everyone - all my local builds were failing, same for others.

**Comment by reta** [comment]
@andrross down again: https://github.com/opensearch-project/OpenSearch/pull/2244#issuecomment-1054739655

**Comment by CEHENKLE** [comment]
Hmmm...if we're using amazonlinux for our distribution, it makes sense to me change it to that.  @bbarani any concerns if we make that switch?  (also curious if engineering effectiveness would make the switch or the core team, but he who is less important that what)

**Comment by peterzhuamazon** [comment]
In my experience centos is that flaky on endpoint.
Previously I just manually force it to use official mirror instead of other vault.

We cannot change to another distro at this point due to dependencies from knn.

**Comment by owaiskazi19** [comment]
Can we use `vault.epel.cloud` for more reliability here as a mirror?

**Comment by bbarani** [comment]
> In my experience centos is that flaky on endpoint. Previously I just manually force it to use official mirror instead of other vault.
> 
> We cannot change to another distro at this point due to dependencies from knn.

FYI.. KNN dependency might not be an issue starting 2.0 as they are not going to be built in the distribution (rather built as standalone plugin) https://github.com/opensearch-project/opensearch-build/issues/1670

**Comment by gaiksaya** [comment]
> In my experience centos is that flaky on endpoint. Previously I just manually force it to use official mirror instead of other vault.
> 
> We cannot change to another distro at this point due to dependencies from knn.

If this is related only to OpenSearch tests (example gradle check) is switching distribution still an issue?

**Comment by reta** [comment]
> If this is related only to OpenSearch tests (example gradle check) is switching distribution still an issue? (Not the distribution just the min)
@gaiksaya it is related to OpenSearch Docker distribution (and consequently, tests).

**Comment by owaiskazi19** [comment]
Closing this issue for now as the mirror url has been changed. Let's reopen if we face anymore downtime issue and have a plan to change the distribution.
