### ISSUE TITLE
Extension Latency

### ISSUE THREAD

**Issue by saratvemulapalli** [opensearch-project/OpenSearch#2231]
The goal of issue is to measure latency for extension running within OpenSearch vs outside of OpenSearch.

- [x] Build a new extension which is called in the critical lifecycle of searching/indexing.
- [x] Integrate with TransportService, extension startup script from https://github.com/opensearch-project/OpenSearch/issues/1619)

**Comment by saratvemulapalli** [comment]
Some how I can't assign it. 
@joshpalis can you assign it your self or get help from @CEHENKLE

**Comment by joshpalis** [comment]
Here is the work done to create the new [custom extension](https://github.com/joshpalis/latency-tester/tree/latency-tester-plugin)

Here is the work done to integrate the new extension with the [transport service](https://github.com/joshpalis/latency-tester/tree/transport-service-integration)

**Comment by joshpalis** [comment]
Created new [issue](https://github.com/opensearch-project/OpenSearch/issues/3012) for work done to conduct benchmarking
