### ISSUE TITLE
Add new tests to verify bwc scenarios

### ISSUE THREAD

**Issue by dreamer-89** [opensearch-project/OpenSearch#2240]
Verify older OS versions are compatible with OS 2.0 post type removal.  Sample upgrades scenarios to add:

1.  Index. Verify indices created with types (or without) allows ingestion in OS 2.0
2. Templates. Verify templates created on OS 1.x with types, allows new index creation.
3. Searching. Verify older indices created with types, are searchable on OS 2.0 without returning type information.
4. Snapshots. Verify older indices are getting snapshots successfully in OS 2.0. It should be possible to recover older index from snapshot in OS 2.0.

**Comment by dreamer-89** [comment]
@reta @nknize : Are there other use-cases that needs to be added ?

**Comment by kotwanikunal** [comment]
I'll take a look at this.

**Comment by reta** [comment]
@dreamer-89 I would add reindexing (`/_reindex`, where type used to be manipulable)

**Comment by dreamer-89** [comment]
Thank you so much @reta for sharing this. We will include re-indexing tests as well.
