### ISSUE TITLE
Release version 2.0.0 (RC1)

### ISSUE THREAD

**Issue by peterzhuamazon** [opensearch-project/OpenSearch#2245]
This is a component issue for release 2.0.0 (RC1).

Coming from https://github.com/opensearch-project/opensearch-build/issues/1624, please refer to the dates in that post. 

Please also follow the following checklist.

<details><summary>How to use this component issue</summary>
<p>

## This Component Issue
This component issue captures the state of the OpenSearch release, on component/plugin level, its assignee is responsible for driving the release of the component.  Please contact them or @mention them on this issue for help. 

## Release Steps
There are several steps to the release process, components that are behind present risk to the release.  Component owners resolve tasks on this ticket to communicate with the overall release owner.

Steps have completion dates for coordinating efforts between the components of a release; components can start as soon as they are ready far in advance of a future release.

You can find all the corresponding dates of each step in the release issue above.

## What should I do if my plugin isn't making any changes?
If including changes in this release, increment the version on 2.0 branch to `2.0.0` for Min/Core, and `2.0.0.0` for components. Otherwise, keep the version number unchanged for both.

</p>
</details>

### Preparation

- [x] Assign this issue to a release owner.
- [x] Finalize scope and feature set and update [the Public Roadmap](https://github.com/orgs/opensearch-project/projects/1).
- [x] All the tasks in this issue have been reviewed by the release owner.
- [x] Create, update, triage and label all features and issues targeted for this release with v2.0.0.

### CI/CD

- [x] All code changes for 2.0.0 are complete.
- [x] Ensure working and passing CI.
- [x] Re(add) this repo to the (if not exist) [opensearch input manifest](https://github.com/opensearch-project/opensearch-build/blob/main/manifests/2.0.0/opensearch-2.0.0.yml).

### Pre-Release

- [x] Update your branch in the [opensearch input manifest](https://github.com/opensearch-project/opensearch-build/blob/main/manifests/2.0.0/opensearch-2.0.0.yml).
- [x] Confirm that all changes for 2.0.0 have been merged.
- [x] Complete integration tests, and update results in the comment, [example](https://github.com/opensearch-project/opensearch-build/issues/1118).
- [ ] Find/fix bugs using latest tarball and docker image provided in meta issue.
- [ ] Completed release candidate testing build #TBD.
- [ ] All intermittent test failures have issues filed.

### Release

- [ ] Complete [documentation](https://github.com/opensearch-project/documentation-website).
- [x] Gather, review and publish release notes.
- [x] Verify all issued labeled for this release are closed or labelled for the next release.

### Post Release

- [ ] Create [a release tag](https://github.com/opensearch-project/.github/blob/main/RELEASING.md#tagging).
- [ ] Suggest improvements to [this template](https://github.com/opensearch-project/opensearch-build/blob/main/.github/ISSUE_TEMPLATE/release_template.md).
- [ ] Conduct a retrospect, and publish its results.

**Comment by kartg** [comment]
> Verify all issued labeled for this release are closed or labelled for the next release.

#3026  / #3093 is still pending but will likely be merged after RC1 release. Most of the remaining [v2.0.0](https://github.com/opensearch-project/OpenSearch/labels/v2.0.0) and [backport 2.0](https://github.com/opensearch-project/OpenSearch/labels/backport%202.0) issues have been triaged

**Comment by kartg** [comment]
> Gather, review and publish release notes.

https://github.com/opensearch-project/OpenSearch/pull/3086

**Comment by kartg** [comment]
> Complete integration tests, and update results in the comment

Note that OpenSearch core does not currently have any integration tests to run, so this has been marked as completed
