### ISSUE TITLE
Release version 1.3

### ISSUE THREAD

**Issue by zelinh** [opensearch-project/OpenSearch#2257]
This is a component issue for release 1.3.0.<br/>
Coming from [opensearch-build#889](https://github.com/opensearch-project/opensearch-build/issues/889), release version 1.3. Please follow the following checklist.

### Preparation

- [x] Assign this issue to a release owner.
- [x] Finalize scope and feature set and update [the Public Roadmap](https://github.com/orgs/opensearch-project/projects/1).
- [x] Create, update, triage and label all features and issues targeted for this release with `v1.3.0`.

### CI/CD

- [x] Increment version on main to ~~`1.3.0.0`~~ `1.4.0.0`
- [x] Ensure working and passing CI.
- [x] Re(add) this repo to the (if not exist) [manifest](https://github.com/opensearch-project/opensearch-build/blob/main/manifests/1.3.0/).

### Pre-Release

- [x] Branch and build from a `1.3` branch.
- [x] Update your branch in the [manifest](https://github.com/opensearch-project/opensearch-build/blob/main/manifests/1.3.0).
- [x] Feature complete, pencils down.
- [x] Fix bugs that target this release.

### Release

- [ ] Complete [documentation](https://github.com/opensearch-project/documentation-website).
- [x] Gather, review and publish release notes.
- [x] Verify all issued labeled for this release are closed or labelled for the next release.

### Post Release

- [x] Create [a release tag](https://github.com/opensearch-project/.github/blob/main/RELEASING.md#tagging).
- [x] Suggest improvements to [this template](https://github.com/opensearch-project/opensearch-build/blob/main/.github/ISSUE_TEMPLATE/release_template.md).
- [x] Conduct a postmortem, and publish its results.

**Comment by dreamer-89** [comment]
Branch `1.3` created. 
https://github.com/opensearch-project/OpenSearch/compare/1.x...1.3?expand=1

**Comment by dreamer-89** [comment]
To generate release notes, used below command
```
git checkout 1.x (# ensure your 1.x is upto date)
git-release-notes ce7b091da6ae50bbc3c015a78b7611923475386c..a61080d9d027a970784825f8486f686a63aa951c markdown > /tmp/1.3_release_notes. (commits identified from previous releases commit messages)
```

**Comment by dreamer-89** [comment]
Opened issue on opensearch-website for documentation side changes.
https://github.com/opensearch-project/documentation-website/issues/448

**Comment by dreamer-89** [comment]
Based on my first release manager experience, sharing below points for improvement. 

### Generic
- There should be some rough timelines on when specific task needs to be started (and completed if other process is dependent on it). 
### Preparation
-  Triaging and labeling issues for release should be done on recurring basis. Doing this as one time activity before release is error prone.
### CI/CD
- Add step for incrementing the main next release version. Added here: https://github.com/opensearch-project/OpenSearch/pull/2430
- Add step for incrementing the next patch version. Added here: https://github.com/opensearch-project/OpenSearch/pull/2509
- `Re(add) this repo to the (if not exist) [manifest](https://github.com/opensearch-project/opensearch-build/blob/main/manifests/1.3.0/).` This step is not applicable for OpenSearch engine as it being core repository.
### Release
   -  As mentioned [here](https://github.com/opensearch-project/OpenSearch/issues/2257#issuecomment-1067290867), we can make use of tools like git-release-notes to get release notes in markdown. 
   -   Remove the dependabot commits (feedback from @dblock @stockholmux ) from generated release notes.
### Post Release
- `Create a release tag` can be removed as there is already automation in place to create those automatically.

**Comment by dreamer-89** [comment]
Following up with @elfisher on documentation task, before closing on this one.

**Comment by dreamer-89** [comment]
Release retro issue https://github.com/opensearch-project/opensearch-build/issues/1775

**Comment by dreamer-89** [comment]
Still waiting for closure on [documentation issue](https://github.com/opensearch-project/documentation-website/issues/448) before closing this one.
