### ISSUE TITLE
Rest layer bwc compatibility post `type` removal

### ISSUE THREAD

**Issue by dreamer-89** [opensearch-project/OpenSearch#2296]
The idea is to add bwc compatibility post type removal (#1940 ) as it decouples users from client side changes/upgrades with Opensearch upgrades. Adding bwc compatibility here means; keep supporting the deprecated typed end-points and map those end-points to typeless end-points but without guaranteeing the same behavior.

**Comment by dreamer-89** [comment]
@nknize @reta @CEHENKLE : What is your opinion on maintaining rest layer bwc compatibility ?

**Comment by reta** [comment]
@dreamer-89 I think we should not mimic the API to support bwc compatibility, 2.0 is major release with a number of breaking changes, removing deprecated endpoints is one of those (in my opinion).

**Comment by dreamer-89** [comment]
As per discussion with team and @reta's feedback; the general consensus is not to include API bwc compatibility for now. Closing this issue.

**Comment by dreamer-89** [comment]
An issue is identified with OpenSearch 2.0 where elastic/beat client integration broke. As per discussion, rest layer versioning is a required feature and is getting tracked separately in https://github.com/opensearch-project/OpenSearch/issues/3035
