### ISSUE TITLE
[BUG] de.thetaphi.forbiddenapis.gradle.ForbiddenApisPlugin fails to initialize on JDK17

### ISSUE THREAD

**Issue by dblock** [opensearch-project/OpenSearch#2299]
**Describe the bug**

Coming from https://github.com/opensearch-project/job-scheduler/pull/130, builds fail on JDK 17 when using Gradle 6.

```
A problem occurred evaluating root project 'opensearch-job-scheduler'.
> Failed to apply plugin class 'de.thetaphi.forbiddenapis.gradle.ForbiddenApisPlugin'.
   > Could not create plugin of type 'ForbiddenApisPlugin'.
      > Could not initialize class de.thetaphi.forbiddenapis.gradle.ForbiddenApisPlugin
```

**Comment by reta** [comment]
Just to add details here: Gradle 6.x does not support JDK-17, only Gradle 7 (and above) does.

**Comment by dblock** [comment]
Closed in https://github.com/opensearch-project/job-scheduler/pull/138.
