### ISSUE TITLE
[Proposal] Swap Adopt OpenJDK for Coretto

### ISSUE THREAD

**Issue by dblock** [opensearch-project/OpenSearch#2312]
**Is your feature request related to a problem? Please describe.**

Coming from https://github.com/opensearch-project/opensearch-build/issues/1682#issuecomment-1055923578, consider swapping AdoptOpenJDK for Coretto. 

**Describe the solution you'd like**

Swap AdoptOpenJDK for [Coretto](https://aws.amazon.com/corretto/).

**Additional Context**

I'd like to hear thoughts from the community on this.

**Comment by dblock** [comment]
cc: @spotaws

**Comment by jkowall** [comment]
On the fence with this idea, I understand the pros of this for testing purposes, but I also understand the optics of it may not be the best idea in liu of the most popular open source Java distribution.

**Comment by reta** [comment]
@dblock why not Temurin ?

**Comment by dblock** [comment]
> @dblock why not Temurin ?

I don't have any good reason for/against one or the other, Temurin is what we ship with now. I only wanted to bring up the discussion so everybody can say why one distribution is preferred to them vs. another.

**Comment by reta** [comment]
Temurin is vendor-neutral (comes from Eclipse foundation) and fully certified OpenJDK binary distribution. I have nothing against Amazon Correto / Microsoft / Azul Zulu / Bellsoft / SAP / RedHat / ... OpenJDK distributions, but my main argument - having vendor-neutral  bundled JDK for open source project makes sense.

**Comment by minalsha** [comment]
@dblock based on above discussion, how should we proceed for this issue? Should we swap AdoptOpenJDK for new JDK(Temurin) ?

**Comment by reta** [comment]
@minalsha we use Temurin for JDK-8/11/17, sadly JDK-14 is only available from AdoptOpenJDK (it is used for BWC tests)

**Comment by dblock** [comment]
Let'd close this. We've decided that OpenSearch will continue using a vendor neural JDK.
