### ISSUE TITLE
Pickup Java version from .properties in OpenSearch gradle check

### ISSUE THREAD

**Issue by dblock** [opensearch-project/OpenSearch#2395]
### Is your feature request related to a problem? Please describe

Coming from https://github.com/opensearch-project/opensearch-build/issues/74#issuecomment-956496829. Use different JDKs depending on which branch of OpenSearch is being built.

### Describe the solution you'd like

OpenSearch has CI defined in a private freestyle project that runs gradle check on OpenSearch#main, branches and PRs. It will get extracted into a Jenkinsfile that is committed to the OpenSearch repo in https://github.com/opensearch-project/opensearch-build/issues/851.

It will then needs to pickup the JDK version to use from https://github.com/opensearch-project/OpenSearch/blob/main/.ci/java-versions.properties#L16.

**Comment by minalsha** [comment]
@bbarani  is this already addressed?

**Comment by dblock** [comment]
@peterzhuamazon would know - show us where we get the java version in gradle checks?

**Comment by peterzhuamazon** [comment]
> @peterzhuamazon would know - show us where we get the java version in gradle checks?

You can improve it by getting it from versions.properties, and sent from webhook to Jenkins runs.
https://github.com/opensearch-project/opensearch-build/blob/main/vars/runGradleCheck.groovy#L36-L42

**Comment by dblock** [comment]
Thanks @peterzhuamazon - @minalsha this is not done, care to queue it up?

**Comment by reta** [comment]
@peterzhuamazon @dblock since build infra is open now, I could take it (if there are no objections)
