### ISSUE TITLE
Integration and Unit Tests for SDK

### ISSUE THREAD

**Issue by saratvemulapalli** [opensearch-project/OpenSearch#2417]
- [X] Test Structure
- [X] Gradle Project Setup for Tests

Unit Tests
- [X] Test for the main script (RunPlugin.java)

Integration Tests
- [X] Test that transport service information is properly exposed
- [X] Test the action listener
- [X] Test for message format
- [X] Test for message protocol
- [ ] Test for deserialize/ serialize message

**Comment by joshpalis** [comment]
@minalsha No, this issue is outdated now as these tests were related to the initial version of the SDK
