### ISSUE TITLE
[BUG] Flaky test failure - v1.2.5#mixedClusterTest - yaml rest test - indices.get_field_mapping

### ISSUE THREAD

**Issue by tlfeng** [opensearch-project/OpenSearch#2440]
**Describe the bug**
Seen in https://github.com/opensearch-project/OpenSearch/pull/2437#issuecomment-1064790619

Gradle run result:
[Log 3252](https://ci.opensearch.org/logs/ci/workflow/OpenSearch_CI/PR_Checks/Gradle_Check/gradle_check_3252.log)
[Reports 3252](https://ci.opensearch.org/logs/ci/workflow/OpenSearch_CI/PR_Checks/Gradle_Check/gradle_check_3252_reports.zip)

**To Reproduce**
I can't reproduce it locally. 🙂
The below shows in the log of Gradle check.
```
REPRODUCE WITH: ./gradlew ':qa:mixed-cluster:v1.2.5#mixedClusterTest' --tests "org.opensearch.backwards.MixedClusterClientYamlTestSuiteIT" -Dtests.method="test {p0=indices.get_field_mapping/20_missing_field/Return empty object if field doesn't exist, but index does}" -Dtests.seed=9FC2465A92C8B157 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=uk-UA -Dtests.timezone=Australia/Hobart -Druntime.java=17

org.opensearch.backwards.MixedClusterClientYamlTestSuiteIT > test {p0=indices.get_field_mapping/20_missing_field/Return empty object if field doesn't exist, but index does} FAILED
    java.lang.AssertionError: Failure at [indices.get_field_mapping/20_missing_field:13]: expected [2xx] status code but api [indices.get_field_mapping] returned [404 Not Found] [{}]
        at __randomizedtesting.SeedInfo.seed([9FC2465A92C8B157:179679803C34DCAF]:0)
        at org.opensearch.test.rest.yaml.OpenSearchClientYamlSuiteTestCase.executeSection(OpenSearchClientYamlSuiteTestCase.java:442)
        at org.opensearch.test.rest.yaml.OpenSearchClientYamlSuiteTestCase.test(OpenSearchClientYamlSuiteTestCase.java:415)
```

**Expected behavior**
test passes.

**Plugins**
none.

**Screenshots**
none.

**Host/Environment (please complete the following information):**

**Additional context**
Occurred since Mar.10th, 2022.

The BWC test running with OpenSearch v1.3.0 can also fail.
gradle command: `./gradlew ':qa:mixed-cluster:v1.3.0#mixedClusterTest' --tests "org.opensearch.backwards.MixedClusterClientYamlTestSuiteIT" -Dtests.method="test {p0=indices.get_field_mapping/20_missing_field/Return empty object if field doesn't exist, but index does}" -Dtests.seed=2E22A45097655A52`
see https://github.com/opensearch-project/OpenSearch/pull/2438#issuecomment-1065435468

**Comment by tlfeng** [comment]
There is an attempt to fix in the commit https://github.com/opensearch-project/OpenSearch/pull/2439/commits/4577e73f2c5cfc96616ed4ab26ca4325ed49c7c4

**Comment by tlfeng** [comment]
I tested the REST API manually in OpenSearch single node of both 1.x branch and 2.0 branch:
```
PUT http://localhost:9200/test_index

{
    "mappings": {
      "properties": {
        "text": {
          "type": "text",
          "analyzer": "whitespace"
        }
      }
    }
}
```
```
GET http://localhost:9200/test_index/_mapping/field/not_existent
```
Unfortunately, I didn't get 404 response code, or empty response body `{}`. Maybe it will only shows error in cluster with nodes of both 1.x and 2.0 versions.

**Comment by nknize** [comment]
Muting test in #2452. It looks related to the intermediate state we're in for types removal. Should resolve once that's complete.

**Comment by gaobinlong** [comment]
This flaky test still exists, see the [failed test](https://build.ci.opensearch.org/job/gradle-check/34750/testReport/org.opensearch.backwards/MixedClusterClientYamlTestSuiteIT/test__p0_indices_get_field_mapping_20_missing_field_Return_empty_object_if_field_doesn_t_exist__but_index_does_/.).
