### ISSUE TITLE
[BUG][OpenSearch] - [ERROR][o.o.s.f.SecurityFilter   ] [host34.company.com.sa] OpenSearch Security not initialized for indices:admin/get

### ISSUE THREAD

**Issue by DiogoGoncalves** [opensearch-project/OpenSearch#2470]
I've did an upgrade at an on-prem instalation from OpenDistro 7.10.2 to OpenSearch 1.2.9 with tarball and upgrade tool, on a 3 masters and 9 data nodes configuration.
After upgrade on all nodes, I've started the masters but the cluster health remains RED, the master1 (first initiated) records warnings regarding the disc space, despite only 2% of the mountpoint is being used. Then is the OpenSearch security index that doesnt start.
....OpenSearch Security not initialized for indices:admin/get and after the unavailable_shards_exception.
Tried to execute the securityadmin.sh to load new index for the security but it fails, I belive because cluster is RED.

 - OS: Red Hat Enterprise Linux Server release 7.9 (Maipo)

**Comment by dblock** [comment]
@DiogoGoncalves Was this coincidental or was the failure avoidable and caused by the upgrade?

**Comment by DiogoGoncalves** [comment]
@dblock I believe it wasn't from the OpenDisto -> OpenSearch upgrade.
I didn't stop logstash because I was doing a node by node upgrade, and I guess it kept pumping logs into OpenSearch that were not treated (removed). There was also a problem with the OpenSearch dashboard that kept sending debug messages to OpenSearch because he couldn't connect to it (at this time the cluster was yellow). I didn't check the status of the cluster before  I started the OpenSearch dashboard, so I suspect that those messages fill the HDDs.
I'll be doing the upgrade soon in another environment doing all nodes upgrade at once, so I'll check if this happens again.
