### ISSUE TITLE
[CI] flaky test failure - o.o.indices.stats.IndexStatsIT.testFilterCacheStats

### ISSUE THREAD

**Issue by tlfeng** [opensearch-project/OpenSearch#2501]
Caught from PR https://github.com/opensearch-project/OpenSearch/pull/2424#issuecomment-1071889507:

❌   Gradle Check failure https://github.com/opensearch-project/OpenSearch/commit/90f143afca0b28eb9d15d3b210bcc8339816230a
[Log 3504](https://ci.opensearch.org/logs/ci/workflow/OpenSearch_CI/PR_Checks/Gradle_Check/gradle_check_3504.log)

[Reports 3504](https://ci.opensearch.org/logs/ci/workflow/OpenSearch_CI/PR_Checks/Gradle_Check/gradle_check_3504_reports.zip)

In log 3504:
```
> Task :server:internalClusterTest

REPRODUCE WITH: ./gradlew ':server:internalClusterTest' --tests "org.opensearch.indices.stats.IndexStatsIT.testFilterCacheStats" -Dtests.seed=D48688166EC0CB86 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=fr -Dtests.timezone=GMT -Druntime.java=17

org.opensearch.indices.stats.IndexStatsIT > testFilterCacheStats FAILED
    java.lang.AssertionError: expected:<0> but was:<1>
        at __randomizedtesting.SeedInfo.seed([D48688166EC0CB86:B1B97553DEC8CCFF]:0)
        at org.junit.Assert.fail(Assert.java:89)
        at org.junit.Assert.failNotEquals(Assert.java:835)
        at org.junit.Assert.assertEquals(Assert.java:647)
        at org.junit.Assert.assertEquals(Assert.java:633)
        at org.opensearch.indices.stats.IndexStatsIT.testFilterCacheStats(IndexStatsIT.java:1225)
```

**Comment by andrross** [comment]
Another failure: https://build.ci.opensearch.org/job/gradle-check/6332/

**Comment by dblock** [comment]
https://github.com/opensearch-project/OpenSearch/pull/3633

**Comment by andrross** [comment]
#5365

**Comment by Rishikesh1159** [comment]
#5332

**Comment by mch2** [comment]
I've gotten this to reproduce locally.  Its failing on [this](https://github.com/opensearch-project/OpenSearch/blob/b9f04405d6dfabcc2b8e87a86d4f83b003b3ffe7/server/src/internalClusterTest/java/org/opensearch/indices/stats/IndexStatsIT.java#L1225) line that asserts there is nothing in the query cache.  At this point in the test no searches have been initiated from the test but there is occasionally an entry in the cache.

Up until that point in the test the only reqs made are to index a random set of docs.  Looks like a query is being made somewhere from inside engine on the index path that reuses the same querycache, I think that is [here](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/index/engine/InternalEngine.java#L1282) where only if assertions are enabled we check if the doc is not actually in the index from [indexIntoLucene](https://github.com/opensearch-project/OpenSearch/blob/44aabe9bb57e33716fbafcc81d29c5385a55f34f/server/src/main/java/org/opensearch/index/engine/InternalEngine.java#L1098).  I don't think this is related to randomization, but that the query is only occasionally cached or evicted before the test fetches stats. 

I've nulled out / used DisabledQueryCache impl on this searcher and am no longer able to repro the failure.
