### ISSUE TITLE
Feature Freeze 2.0.0 Public Preview

### ISSUE THREAD

**Issue by nknize** [opensearch-project/OpenSearch#2530]
Meta issue for Feature freezing Version 2.0.0 for Public Preview:

- [x] Cut 2x branch
- [x] Cut 2.0 branch
- [x] Bump 2x to version 2.1.0 and update bwc versions
- [x] Bump main to version 3.0.0 and update bwc versions

**Comment by saratvemulapalli** [comment]
@nknize looks all of them are done. Is there anything else we need to take care of for this issue?
