### ISSUE TITLE
[BUG] Auto-backport tool fails a lot

### ISSUE THREAD

**Issue by cliu123** [opensearch-project/OpenSearch#2554]
[Auto-backport tool](https://github.com/opensearch-project/OpenSearch/pull/1600) fails on a few backport PRs, for example:
It failed to backport [this PR](https://github.com/opensearch-project/security/pull/1679) to `1.0`, `1.1` and `1.2` branches.
It failed to backport [this PR](https://github.com/opensearch-project/security/pull/1541) to `1.3` branch.

**Comment by dblock** [comment]
This is expected without clean merges, no?

**Comment by saratvemulapalli** [comment]
Thanks @cliu123 @peternied . Lets use https://github.com/opensearch-project/OpenSearch/issues/2561 to track this problem.
