### ISSUE TITLE
[BUG] BWC testing for new "manager" nomenclature

### ISSUE THREAD

**Issue by nknize** [opensearch-project/OpenSearch#2577]
This was caught by backport PR #2574 which is the first time the terminology change has run in a mixedCluster environment.

```
2> REPRODUCE WITH: ./gradlew ':qa:mixed-cluster:v2.0.0#mixedClusterTest' --tests "org.opensearch.backwards.ExceptionIT.testOpensearchException" -Dtests.seed=39271DF23C0B9649 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=es-AR -Dtests.timezone=Pacific/Midway -Druntime.java=17
```

```
  2> org.opensearch.client.WarningFailureException: method [GET], host [http://127.0.0.1:34269/], URI [_cat/master?h=id], status line [HTTP/1.1 200 OK]
    Warnings: [[GET /_cat/master] is deprecated! Use [GET /_cat/cluster_manager] instead.]
    ZAHYRqxQRgaDUro01kI6Fw
        at __randomizedtesting.SeedInfo.seed([39271DF23C0B9649:96DED86A9A18A3B3]:0)
        at app//org.opensearch.client.RestClient.convertResponse(RestClient.java:346)
        at app//org.opensearch.client.RestClient.performRequest(RestClient.java:320)
        at app//org.opensearch.client.RestClient.performRequest(RestClient.java:295)
        at app//org.opensearch.backwards.ExceptionIT.logClusterNodes(ExceptionIT.java:50)
        at app//org.opensearch.backwards.ExceptionIT.testOpensearchException(ExceptionIT.java:28)
```

This can be handled either by:

1. using `setWarningsHandler` in the `2.x` branch as exemplified by [SystemIndexRestIT](https://github.com/opensearch-project/OpenSearch/blob/2e9f89a89efb2b44adc783d378e433bce79273c0/qa/smoke-test-http/src/test/java/org/opensearch/http/SystemIndexRestIT.java#L141) to handle the expected warnings
2. refactoring the deprecated `master` nomenclature to `manager` terminology in the `.backwards` namespace in the `2.x` branch

**Comment by nknize** [comment]
The above failure (`ExceptionIT`) is fixed by #2574 but we may have other test failures. If so, we'll keep this open

**Comment by nknize** [comment]
The fix in #2574 was merged so I'm going to give this 24 hours to bake. If no recurring failures we can close and re-open if/when one occurs.

**Comment by Rishikesh1159** [comment]
@nknize any update on this?

**Comment by nknize** [comment]
:+1: no failures for sometime so I'll close. @tlfeng will reopen if we hit this again.
