### ISSUE TITLE
[Bug][DISTRIBUTION][2.0.0]: Plugin build fails for JDK lower than 17 (11 and 14)

### ISSUE THREAD

**Issue by martin-gaievski** [opensearch-project/OpenSearch#2581]
### Describe the bug

Build for kNN plugin PRs fail when JDK 11 or JDK 14 has been used. 

Example of failed build - https://github.com/opensearch-project/k-NN/runs/5668411237?check_suite_focus=true. 

Error in the log:

```
Reaper process died unexpectedly! Check the log at /home/runner/work/k-NN/k-NN/.gradle/reaper/build-1813/reaper.log
```

reaper.log:

```
Error: LinkageError occurred while loading main class org.opensearch.gradle.reaper.Reaper
        java.lang.UnsupportedClassVersionError: org/opensearch/gradle/reaper/Reaper has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 58.0
```

More details exception is here - https://gist.github.com/martin-gaievski/ea1d3918e940c348f5e13dc5f9cc27a6. 

The error comes at the very end of the build, when all tasks are finished successfully.  

Locally I'm able to build is successfully for JDK 17, same as a github action has been cancelled as soon as build for JDK 14 fails. 

This PR that uses OpenSearch 2.0.0-alpha1-SNAPSHOT, with added support for the build.version_qualifier.  

### To reproduce

Feel free to restart https://github.com/opensearch-project/k-NN/runs/5668411237?check_suite_focus=true failed task for JDK 11 or JDK 14, or download https://github.com/martin-gaievski/k-NN/tree/integrate/opensearch20-lucene91 and try to build is locally with JDK 14. 

### Expected behavior

Build should finish successfully, same as for JDK 17.

**Comment by Rishikesh1159** [comment]
moved to opensearch repo, so closing this issue here for now.

**Comment by Rishikesh1159** [comment]
Looks like this PR was causing the failures on plugin https://github.com/opensearch-project/OpenSearch/pull/2407. When I revert this PR, build was successful. I will further dig and see which change in PR caused this and update more info here

**Comment by Rishikesh1159** [comment]
This https://github.com/opensearch-project/OpenSearch/blob/cc0e66b1dcc2cfe17b76bcea1168ebb996fbb090/buildSrc/src/main/java/org/opensearch/gradle/testclusters/OpenSearchNode.java#L913 line in PR where method call registerPid() happens, is having problem. This call tries to register and then later kill Pid, this is failing somehow and plugins are getting failed here. I will try to sync up and get suggestions from @dblock in how to move forward to a fix for this.

**Comment by dblock** [comment]
The reaper code was taken out when we re-introduced compatibility with JDK8, then put back in #2407. If the reaper is broken, it should just be fixed.

**Comment by reta** [comment]
@dblock looking, the source/runtime level should be 11

**Comment by Rishikesh1159** [comment]
Thank you @reta I tried your fix in local. It fixed this issue.

**Comment by CEHENKLE** [comment]
@reta You are a rockstar :)
