### ISSUE TITLE
Concurrent Searching: Support Aggregations

### ISSUE THREAD

**Issue by reta** [opensearch-project/OpenSearch#2585]
**Is your feature request related to a problem? Please describe.**
The aggregations are implemented using Apache Lucene collectors and are not yet compatible with the concurrent search over segments.

**Describe the solution you'd like**
It should be possible to use concurrent search over segments for aggregations.

**Describe alternatives you've considered**
The implementation falls back to sequential search right now

**Additional context**
N/A

**Comment by sohami** [comment]
@reta I will be taking a stab at this but wanted to check if there is any initial analysis which you did which can help with this item ?

**Comment by anasalkouz** [comment]
Sure @sohami. Go for it. Please see this [META](https://github.com/opensearch-project/OpenSearch/issues/2587) issue for whole effort related to concurrent search. I think @reta took the first stab on implementing the concurrent search as a sandbox plugin.

**Comment by reta** [comment]
@sohami @anasalkouz the main blocker for any further work is this issue [1], the concurrent search sandbox plugin is not published anywhere and we do not provide a convenient way for people to try it. It is just sitting in the repo, unless someone does manual builds and installation.

[1] https://github.com/opensearch-project/OpenSearch/issues/3677

**Comment by sohami** [comment]
@reta Sorry for delayed response. That issue seems more on to help users of concurrent search to easily try the experimental feature which from discussion seems like we can move to a feature flag model. However, there should not be a blocker from developing other missing pieces. To that I was able to spend some cycles on looking into current implementation and will be adding some update this week.

**Comment by sohami** [comment]
@reta @anasalkouz I have added details in a new issue: https://github.com/opensearch-project/OpenSearch/issues/6798. Was unable to update the description of this issue. Also I am wondering if we can add all the tasks list in a single place potentially reference #3677  and #6798  to the META issue #2587 itself

**Comment by anasalkouz** [comment]
@sohami I have updated the META Issue. Shall I close this issue in the favor of #6798 ?

**Comment by sohami** [comment]
@anasalkouz Sounds good. Thanks!
