### ISSUE TITLE
[BUG] org.opensearch.monitor.os.OsProbeTests > testLogWarnCpuMessageOnlyOnes FAILED

### ISSUE THREAD

**Issue by owaiskazi19** [opensearch-project/OpenSearch#2592]
**Describe the bug**
Coming from https://github.com/opensearch-project/OpenSearch/issues/2061. The test is failing in docker for ubuntu.

```
REPRODUCE WITH: ./gradlew ':server:test' --tests "org.opensearch.monitor.os.OsProbeTests.testLogWarnCpuMessageOnlyOnes" -Dtests.seed=BDC5BBA6F734E6C6 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=ar-SD -Dtests.timezone=Europe/Ulyanovsk -Druntime.java=17

org.opensearch.monitor.os.OsProbeTests > testLogWarnCpuMessageOnlyOnes FAILED
    Wanted but not invoked:
    logger.warn(<any string>);
    -> at org.opensearch.monitor.os.OsProbeTests.testLogWarnCpuMessageOnlyOnes(OsProbeTests.java:302)

    However, there was exactly 1 interaction with this mock:
    logger.debug(
        "error reading control group stats",
        java.nio.file.NoSuchFileException: /sys/fs/cgroup/cpuacct/docker/7550e3db5fa6ac2f81f2705282960c903563d569862219c3240ae1c31de0d648/cpuacct.usage
    );
    -> at org.opensearch.monitor.os.OsProbe.getCgroup(OsProbe.java:588)
        at __randomizedtesting.SeedInfo.seed([BDC5BBA6F734E6C6:7553200E882ADEC8]:0)
        at app//org.opensearch.monitor.os.OsProbeTests.testLogWarnCpuMessageOnlyOnes(OsProbeTests.java:302)
```
File not found: `/sys/fs/cgroup/cpuacct/docker/7550e3db5fa6ac2f81f2705282960c903563d569862219c3240ae1c31de0d648/cpuacct.usage`

**To Reproduce**
1. Pull [opensearchstaging/ci-runner:ci-runner-ubuntu1804-build-v1](https://hub.docker.com/layers/opensearchstaging/ci-runner/ci-runner-ubuntu1804-build-v1/images/sha256-2c7bb2780bc08cd4e7e3c382ac53db414754dabd52f9b70e1c7e344dfb9a0e5e?context=explore)
2. Run `./gradlew check`

**Expected behavior**
`./gradlew check` should pass.

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**
 - OS: Ubuntu (Docker image)
 - Version: 18.04

**Comment by reta** [comment]
@owaiskazi19 I will take it, too annoying :-\
