### ISSUE TITLE
[Enhancement] Rename CPU architectures for deb and rpm packages

### ISSUE THREAD

**Issue by saratvemulapalli** [opensearch-project/OpenSearch#2598]
**Describe the bug**
The CPU architecture was renamed for archives in opensearch-project/OpenSearch#612 to keep it consistent with plugins and trends on google.
But the deb and rpm packages used `amd64` and `x86_64`. 
How do we like to rename them?

**Comment by peterzhuamazon** [comment]
Possible issues if we directly rename inside core:
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1401

**Comment by saratvemulapalli** [comment]
> @saratvemulapalli We dont really need to do this now as the final release artifact will be rename to the correct name anyway.

Cool. I'll close this one for now. Feel free to re-open if we need it.

**Comment by dblock** [comment]
I'm reading this issue and it sounds like OpenSearch generates `opensearch-min-2.0.0-SNAPSHOT.x86_64.rpm` and it should really be `opensearch-min-2.0.0-SNAPSHOT.arm64.rpm`. To work around this we are doing renaming in opensearch-build? As @saratvemulapalli points out in https://github.com/opensearch-project/OpenSearch/issues/2598#issuecomment-1075590534, we should make this change here and not rename files later in distribution scripts. @peterzhuamazon WDYT? Want to give it a try?

**Comment by peterzhuamazon** [comment]
Hi @dblock,
It should be x64 not arm64 for x86_64, tho it really does not matter as that is not the product we will release anyway.
Plus the manifest will also use the existing name of the file so it will not mess up anything is the build.

Thanks.

**Comment by peterzhuamazon** [comment]
Also @dblock I fear the changes might somehow cause the min rpm to not able to install like in OSD, and that is why I am very hesitate to even change this, see:
* https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1401
