### ISSUE TITLE
[FEATURE] Provide dedicated Test Containers support for OpenSearch

### ISSUE THREAD

**Issue by reta** [opensearch-project/OpenSearch#2603]
**Is your feature request related to a problem? Please describe.**
Test Containers [1] is a widely used test scaffolding for running tests against Docker containers on JVM. A number of integrations is already bundled into Test Containers, including Elasticsearch [2], however the proposal to include the Opensearch support (fully contributed) was rejected [3]

[1] https://www.testcontainers.org/
[2] https://www.testcontainers.org/modules/elasticsearch/
[3] https://github.com/testcontainers/testcontainers-java/issues/4782

**Describe the solution you'd like**
Provide dedicated Test Containers integration (standalone artifact) for running OpenSearch Docker containers, similarly to [4], so to simplify testing against OpenSearch servers on JVM. The vast majority of the work has been done already as part of Apache Flink connector implementation [5].

[4] https://github.com/dasniko/testcontainers-keycloak
[5] https://github.com/apache/flink/blob/712c6bfd83e10de35b284d65e91b859da194c2ef/flink-connectors/flink-connector-opensearch/src/test/java/org/apache/flink/testcontainers/opensearch/OpensearchContainer.java

**Describe alternatives you've considered**
The integration could be a part of OpenSearch repository (preferred) or outside of it (Aiven Oy), hosted under `testcontainers-opensearch` repository. 

**Additional context**
Aiven Oy team is ready to contribute.

**Comment by reta** [comment]
@dblock do you think we could have `opensearch-testcontainers` repository under OpenSearch organization? I should be able to submit the pull request for implementation, thank you!

**Comment by dblock** [comment]
Sorry for the delay @reta, @CEHENKLE @bbarani  you're cool with a new `opensearch-testcontainers` repo?

**Comment by reta** [comment]
@CEHENKLE @bbarani any thoughts from your side? thanks!

**Comment by CEHENKLE** [comment]
Sure!  I'll go cut the tickets etc to go create the repos unless you've already done it, @dblock

**Comment by CEHENKLE** [comment]
Would you prefer opensearch-project/opensearch-testcontainers or just opensearch-project/testcontainers ?

**Comment by CEHENKLE** [comment]
(Ticket Cut)

**Comment by dblock** [comment]
@reta ^

**Comment by reta** [comment]
@CEHENKLE `opensearch-project/opensearch-testcontainers` would be preferred (to me), if @dblock has no objections

**Comment by CEHENKLE** [comment]
@reta Question from our OSPO team:  "Want to make sure I understand, did we start from the Elastic integration to create the OpenSearch integration?"

**Comment by reta** [comment]
@CEHENKLE Not entirely - the API is similar (to Elasticsearch test container) but this is brand new implementation, with security enabled / disabled, HTTP(s) and self-signed certificates support.

**Comment by CEHENKLE** [comment]
@reta thanks....will continue to nudge this along (we're close)

**Comment by minalsha** [comment]
Hi @CEHENKLE , assigning this issue to you since you are handling it. Thanks

**Comment by CEHENKLE** [comment]
https://github.com/opensearch-project/opensearch-testcontainers created, PR raised to add you as a maintainer, @reta  :) 

Almost there :)

**Comment by CEHENKLE** [comment]
Okay!  repo up, @reta there's an invite waiting for you to be a maintainer :) 

Resolving this, see you at https://github.com/opensearch-project/opensearch-testcontainers :)

**Comment by reta** [comment]
> Okay! repo up, @reta there's an invite waiting for you to be a maintainer :)

Thanks a lot @CEHENKLE ! Got the invitation, pull request on its way!
