### ISSUE TITLE
[BUG] Plugins unable to load classes with ServiceLoader

### ISSUE THREAD

**Issue by gressc** [opensearch-project/OpenSearch#2650]
**Describe the bug**
OpenSearch Plugins are unable to find classes using ServiceLoader

**To Reproduce**
[Minimal Reproducible Example](https://github.com/gressc/opensearch-plugin-broken-service-loader)

**Expected behavior**
ServiceLoader searched class is found in plugin

**Host/Environment (please complete the following information):**
 - OS: Linux
 - Version: CentOS 7 [e.g. 22]

**Comment by reta** [comment]
Hey @gressc , I believe you are not feeding the ServiceLoader the right classloader (it takes the thread context one, but it is bot where your plugin services live):

```
    private final HelloWorldService serviceImpl;

    public RestHelloWorldAction() {
		serviceImpl = ServiceLoader.load(HelloWorldService.class, HelloWorldService.class.getClassLoader()).iterator().next();
	}
```

The tests should run after that (+ adding new line to spec files).

**Comment by gressc** [comment]
@reta, I appreciate your help in looking at this. I have confirmed that ServiceLoader does work as long as it is possible to specify the classloader. I will put a bug request into the libraries that we are using to allow us to specify the classloader to use.

**Comment by saratvemulapalli** [comment]
Thanks @reta !
@gressc do you have any other questions, if not can we close this issue?
