### ISSUE TITLE
[BUG] Deprecation messages refers to elasticsearch v.8 version

### ISSUE THREAD

**Issue by Yury-Fridlyand** [opensearch-project/OpenSearch#2659]
**Describe the bug**
`OpenSearch` is able to warn a use about upcoming deprecation of API used. Some of deprecation messages refers to `Elasticsearch` version instead of `OpenSearch`.
There are deprecations seen by .Net client automated test:
```
299 OpenSearch-1.3.0-e45991597c86ba1bbcc36ee1dfdc165197a913af "Parameter [boost] on field [name] is deprecated and will be removed in 8.0"
299 OpenSearch-1.3.0-e45991597c86ba1bbcc36ee1dfdc165197a913af "Parameter [similarity] has no effect on type [scaled_float] and will be removed in future"
299 OpenSearch-1.3.0-e45991597c86ba1bbcc36ee1dfdc165197a913af "Parameter [boost] on field [lastActivity] is deprecated and will be removed in 8.0"
299 OpenSearch-1.3.0-e45991597c86ba1bbcc36ee1dfdc165197a913af "Parameter [similarity] has no effect on type [integer] and will be removed in future"
299 OpenSearch-1.3.0-e45991597c86ba1bbcc36ee1dfdc165197a913af "Parameter [boost] on field [state] is deprecated and will be removed in 8.0"
299 OpenSearch-1.3.0-e45991597c86ba1bbcc36ee1dfdc165197a913af "Field parameter [strategy] is deprecated and will be removed in a future version."
299 OpenSearch-1.3.0-e45991597c86ba1bbcc36ee1dfdc165197a913af "Deprecated field [cutoff_frequency] used, replaced by [you can omit this option, the [multi_match] query can skip block of documents efficiently if the total number of hits is not tracked]"
299 OpenSearch-1.3.0-e45991597c86ba1bbcc36ee1dfdc165197a913af "[types removal] Specifying types in multi search requests is deprecated."
299 OpenSearch-1.3.0-e45991597c86ba1bbcc36ee1dfdc165197a913af "Deprecated field [field_masking_span] used, expected [span_field_masking] instead"
299 OpenSearch-1.3.0-e45991597c86ba1bbcc36ee1dfdc165197a913af "The moving_avg aggregation has been deprecated in favor of the moving_fn aggregation."
299 OpenSearch-1.3.0-e45991597c86ba1bbcc36ee1dfdc165197a913af "Type exists requests are deprecated, as types have been deprecated."
299 OpenSearch-1.3.0-e45991597c86ba1bbcc36ee1dfdc165197a913af "[match][1:129] Deprecated field [ordered] used, this field is unused and will be removed entirely"
```

.Net client automated test detects and logs all seen deprecations. You can see one of test runs here: https://github.com/opensearch-project/opensearch-net/runs/5742568684?check_suite_focus=true. If this log is deleted, go to [integration tests](https://github.com/opensearch-project/opensearch-net/actions/workflows/integration.yml), open any test run, open any job, open `Integration tests` step and scroll to the very bottom.

**Plugins**
- ingest-attachment,
- analysis-kuromoji,
- analysis-icu,
- analysis-phonetic,
- mapper-murmur3,
- analysis-nori

**Host/Environment (please complete the following information):**
 - OS: ubuntu-latest from GitHub Actions env
 - Version: 1.3.0

**Additional context**
Unfortunately, it is impossible to run these tests on a dev build of OpenSearch. Only released versions are supported at the moment.

```bash
egrep -rRn '[^0-9][7-8]\.[0-9x\*]' | less
```
yields a lot of interesting results. Some of them might hurt in future when OpenSearch version will grow further, but it is already out of scope of current bug. Just an example:
```
distroVersion.onOrAfter("7.0.0")
```

**Comment by mch2** [comment]
Thanks for reporting @Yury-Fridlyand.  I suggest we change these to "a future version" unless otherwise known.

**Comment by amitchakraborti9** [comment]
Hello, I would like to try working on this issue.
