### ISSUE TITLE
Design and support for initial extension point (IndicesModule)

### ISSUE THREAD

**Issue by saratvemulapalli** [opensearch-project/OpenSearch#2711]
Add extension support for Indices Module as the first extension point.

**Comment by owaiskazi19** [comment]
Possible Solution to the above problem:
1. Create an extension.yml file and pass only the extension points, its listeners and the method extension wants to invoke. Based on the request provided by yml file handle it on the OpenSearch end.
2. Use RPC calls to invoke remote methods of OpenSearch from the extension.
3. Use JNA to call native functions using natural Java method invocation.

**Comment by saratvemulapalli** [comment]
Will close this issue as we were able to get IndicesModule up for Latency Tester. 
Will copy the comment in a dedicated issue.

**Comment by saratvemulapalli** [comment]
Code: https://github.com/saratvemulapalli/OpenSearch/commit/2d068dfa3942d70b1d7e455b5c9f92ca57d016ab has been merged for first extension point.

**Comment by saratvemulapalli** [comment]
PR #3107 merged to feature branch!
