### ISSUE TITLE
Add `positive_score_impact` support for `rank_features`

### ISSUE THREAD

**Issue by Hronom** [opensearch-project/OpenSearch#2724]
**Is your feature request related to a problem? Please describe.**
No support for `positive_score_impact` parameter for `rank_features`

**Describe the solution you'd like**
Add support

**Comment by Hronom** [comment]
Partially relates to https://github.com/opensearch-project/OpenSearch/issues/977

**Comment by kartg** [comment]
Closing since #2725 has been merged
