### ISSUE TITLE
[Version] Remove all Legacy 7.x Compatibility in 3.0

### ISSUE THREAD

**Issue by nknize** [opensearch-project/OpenSearch#2748]
This is a meta issue to track all tasks for removing legacy compatibility in 3.0

- [ ] #2746 
- [x] #2747

**Comment by anasalkouz** [comment]
@nknize do we need to provide a deprecation message in the next minor release? or this should be the right expectation and no need for a notice.

**Comment by kartg** [comment]
Note - this task is now OBE/obsolete since we need to retain legacy compatibility for [opensearch-migrations](https://github.com/opensearch-project/opensearch-migrations/issues/23)
