### ISSUE TITLE
[BUG] Aggregation on termX field gets 400 status code. & failed to create query: [nested] nested object under path [my_nested_object] is not of nested type

### ISSUE THREAD

**Issue by cliu123** [opensearch-project/OpenSearch#2776]
**Describe the bug**
2 requests that got 200 response now get 400 response from core.
Branch：https://github.com/cliu123/security/tree/upgrade_to_opensearch_2.0.0_alpha1

1. The [test](https://github.com/cliu123/security/blob/upgrade_to_opensearch_2.0.0_alpha1/src/test/java/org/opensearch/security/dlic/dlsfls/DlsTest.java#L343) passed until OpenSearch 2.0.0-SNAPSHOT, but starts failing since 2.0.0-alpha1.

```
{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Text fields are not optimised for operations that require per-document field data like aggregations and sorting, so these operations are disabled by default. Please use a keyword field instead. Alternatively, set fielddata=true on [termX] in order to load field data by uninverting the inverted index. Note that this can use significant memory."}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":0,"index":"logs","node":"wdsYHp_iRLi3gQHdAP0mQg","reason":{"type":"illegal_argument_exception","reason":"Text fields are not optimised for operations that require per-document field data like aggregations and sorting, so these operations are disabled by default. Please use a keyword field instead. Alternatively, set fielddata=true on [termX] in order to load field data by uninverting the inverted index. Note that this can use significant memory."}}],"caused_by":{"type":"illegal_argument_exception","reason":"Text fields are not optimised for operations that require per-document field data like aggregations and sorting, so these operations are disabled by default. Please use a keyword field instead. Alternatively, set fielddata=true on [termX] in order to load field data by uninverting the inverted index. Note that this can use significant memory.","caused_by":{"type":"illegal_argument_exception","reason":"Text fields are not optimised for operations that require per-document field data like aggregations and sorting, so these operations are disabled by default. Please use a keyword field instead. Alternatively, set fielddata=true on [termX] in order to load field data by uninverting the inverted index. Note that this can use significant memory."}}},"status":400}
```

2. Another [test](https://github.com/cliu123/security/blob/main/src/test/java/org/opensearch/security/dlic/dlsfls/DlsNestedTest.java#L80) starts failing since 2.0.0-alpha1 too.

**Response**
```
"error" : {
    "root_cause" : [
      {
        "type" : "query_shard_exception",
        "reason" : "failed to create query: [nested] nested object under path [my_nested_object] is not of nested type",
        "index" : "deals",
        "index_uuid" : "hR3R1jlwRz63UOMbbDoQhw"
      }
    ],
    "type" : "search_phase_execution_exception",
    "reason" : "all shards failed",
    "phase" : "query",
    "grouped" : true,
    "failed_shards" : [
      {
        "shard" : 0,
        "index" : "deals",
        "node" : "05SczuM4SpWsP-GURvChGw",
        "reason" : {
          "type" : "query_shard_exception",
          "reason" : "failed to create query: [nested] nested object under path [my_nested_object] is not of nested type",
          "index" : "deals",
          "index_uuid" : "hR3R1jlwRz63UOMbbDoQhw",
          "caused_by" : {
            "type" : "illegal_state_exception",
            "reason" : "[nested] nested object under path [my_nested_object] is not of nested type"
          }
        }
      }
```

**Comment by davidlago** [comment]
Did the change removing mapping types get in after that old `2.0.0-SNAPSHOT`? this smells like a mapping type issue

**Comment by cliu123** [comment]
> Did the change removing mapping types get in after that old `2.0.0-SNAPSHOT`? this smells like a mapping type issue
```
2.0.0-SNAPSHOT/	Wed Mar 09 01:41:04 UTC 2022	 	
2.0.0-alpha1-SNAPSHOT/	Tue Apr 05 21:48:15 UTC 2022
```
Some of the removing types changes got in after `2.0.0-SNAPSHOT`(`Tue Apr 05 21:48:15 UTC 2022`).

**Comment by nknize** [comment]
I locally updated the security plugin to 2.0.0-alpha1 and after tidying up some build failures from [missed type removals](https://github.com/opensearch-project/security/blob/2972bd15a98dbaa8c571b9b302268de076d20ee0/src/test/java/org/opensearch/security/TracingTests.java) and other lucene 9.x changes the offending test passes. I did not run the entire test suite but all of `DlsTest.java` passes for me.

```
 BUILD SUCCESSFUL in 2m 1s
```

Unrelated: I noticed security isn't following the [SPDX header standard](https://github.com/opensearch-project/OpenSearch/blob/main/buildSrc/src/main/resources/license-headers/license-header.txt) adopted by OpenSearch and is instead using the [old ALv2 header](https://github.com/opensearch-project/security/blob/2972bd15a98dbaa8c571b9b302268de076d20ee0/src/test/java/org/opensearch/security/TracingTests.java#L17). Probably something we want to remedy sooner than later.

Note also: a quick indication of the stale OpenSearch-2.0.0 build was the lucene 8.10 transitive dependency pulled in by gradle. 2.0.0 is now running on Lucene 9.1 yet gradle pulled in an old 8.10 build. Let's make sure no other plugin repos are accidentally running w/ old versions.

**Comment by cliu123** [comment]
@nknize Thanks for checking! The failures are in this branch:https://github.com/cliu123/security/tree/upgrade_to_opensearch_2.0.0_alpha1
Github workflow where failures are: https://github.com/opensearch-project/security/runs/5839382149?check_suite_focus=true

**Comment by nknize** [comment]
> The failures are in this branch...


I bumped the main branch locally and tests pass. Maybe check if there is something else changed on the feature branch causing the failure.

**Comment by nknize** [comment]
In [DlsTest.java#L276](https://github.com/cliu123/security/blob/dbbb490c1b98fa450c9479a6b7889549a877847f/src/test/java/org/opensearch/security/dlic/dlsfls/DlsTest.java#L276)

Set the mapping as follows:

```
            client.admin().indices().create(new CreateIndexRequest("logs").simpleMapping("termX", "type=keyword")).actionGet();
```

The [mainline code here](https://github.com/opensearch-project/security/blob/2972bd15a98dbaa8c571b9b302268de076d20ee0/src/test/java/org/opensearch/security/dlic/dlsfls/DlsTest.java#L276) is different from your branch which is why my this test is passing in my local change.

**Comment by cliu123** [comment]
@nknize That's a good way to verify. I wonder how you bumped OpenSearch core version to `2.0.0-alpha1-SNAPSHOT` on `main` branch though. I bumped version and verified that the new version is `alpha1`, but I got compilation error as you can see in the screenshots because new changes in core that got in after `2.0.0-SNAPSHOT`, which was why I made those changes.
![Screen Shot 2022-04-06 at 8 05 44 AM](https://user-images.githubusercontent.com/16925774/162006528-5a11d665-2213-4704-8931-c7c9b03378d3.png)
![Screen Shot 2022-04-06 at 9 14 01 AM](https://user-images.githubusercontent.com/16925774/162020219-74f3408c-109a-4f64-b25d-af5502244840.png)

**Comment by nknize** [comment]
> I wonder how you bumped OpenSearch core version to 2.0.0-alpha1-SNAPSHOT on main branch though.


I checked out the main branch, bumped the version in the build gradle file, cleared gradle cache, then fixed the errors locally and ran the test.

**Comment by cliu123** [comment]
> In [DlsTest.java#L276](https://github.com/cliu123/security/blob/dbbb490c1b98fa450c9479a6b7889549a877847f/src/test/java/org/opensearch/security/dlic/dlsfls/DlsTest.java#L276)
> 
> Set the mapping as follows:
> 
> ```
>             client.admin().indices().create(new CreateIndexRequest("logs").simpleMapping("termX", "type=keyword")).actionGet();
> ```
> 
> The [mainline code here](https://github.com/opensearch-project/security/blob/2972bd15a98dbaa8c571b9b302268de076d20ee0/src/test/java/org/opensearch/security/dlic/dlsfls/DlsTest.java#L276) is different from your branch which is why my this test is passing in my local change.

Nice! This fixes the test. I applied the similar fix to the other test. It also passes now. Thanks for the guide! @nknize
