### ISSUE TITLE
[BUG] System indices creation fails on max shard limit validator

### ISSUE THREAD

**Issue by jainankitk** [opensearch-project/OpenSearch#2824]
**Describe the bug**
The system index like opensearch dashboard should not be prevented from opening or created due to max shard limit validation

**To Reproduce**
Create single node cluster with 1000 shards and install opensearch dashboard plugin. The plugin will fail to open

**Expected behavior**
Max shard limit should be for user created data indices that consume significant resources on node, not system indices storing the critical information

**Error Message**
```
{"type":"log","@timestamp":"2022-03-31T18:35:45Z","tags":["error","opensearch","data"],"pid":18804,"message":"[illegal_argument_exception]: Validation Failed: 1: this action would add [2] total shards, but this cluster currently has [21295]/[6000] maximum shards open;"}
```

**Comment by saratvemulapalli** [comment]
Changes are merged to 3.0 and 2.1.0. Thanks @jainankitk !
