### ISSUE TITLE
[BUG]max virtual memory areas vm.max_map_count [65530] is too low 

### ISSUE THREAD

**Issue by dineshnaik** [opensearch-project/OpenSearch#2874]
**Describe the bug**
Bootstrap check failure while running OpenSearch using Helm, which does not allow opensearch to come up.
Below error can be seen : 

ERROR: [1] bootstrap checks failed
[1]: max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]

**To Reproduce**
1. Change to the opensearch directory:
    cd charts/opensearch
2. Package the Helm chart:
    helm package .
3. Deploy OpenSearch:
    helm install --generate-name opensearch-1.0.0.tgz
4. See error by getting pod name 
    kubectl get pods
    kubectl get logs opensearch-cluster-master-0

-----
[2022-04-12T10:26:44,172][INFO ][o.o.b.BootstrapChecks    ] [opensearch-cluster-master-0] bound or publishing to a non-loopback address, enforcing bootstrap checks
**ERROR: [1] bootstrap checks failed**
**[1]: max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]**
ERROR: OpenSearch did not exit normally - check the logs at /usr/share/opensearch/logs/opensearch-cluster.log
[2022-04-12T10:26:44,180][INFO ][o.o.n.Node               ] [opensearch-cluster-master-0] stopping ...
[2022-04-12T10:26:44,206][INFO ][o.o.n.Node               ] [opensearch-cluster-master-0] stopped
----

**Expected behavior**
Opensearch service should come up without any errors/issues.

**Comment by dineshnaik** [comment]
Issue can be solved by changing the value for param : 
sudo sysctl -w vm.max_map_count=262144

or by adding below line in opensearch.yml  (temporary solution , not recommended for production cluster.
node.store.allow_mmap: false

**Comment by zalseryani** [comment]
why this error appeared ? can someone explain the reason behind this error ? 

Thanks in advance.
