### ISSUE TITLE
[BUG] Test failure exists but Gradle 'check' task passes

### ISSUE THREAD

**Issue by tlfeng** [opensearch-project/OpenSearch#2878]
**Describe the bug**
The Gradle `check` task may pass, even if test failure occurred.

I'm not sure if this is by design, not to fail the task in the following scenario:
- test failure occurs in YAML REST API BWC test
example: https://github.com/opensearch-project/OpenSearch/pull/2660#issuecomment-1088068474
- test failed by unexpected deprecation warning occurs in YAML REST API test and High-Level-Rest-Client test
example: https://github.com/opensearch-project/OpenSearch/pull/2678#issuecomment-1095703323 and https://github.com/opensearch-project/OpenSearch/pull/2875#issuecomment-1097215194

Maybe the kind of tests is not critical, so that it's not failing the build.

**To Reproduce**

**Expected behavior**
If not to fail the Gradle `check` task is by design, then keep it as it is. Otherwise, fail the `check` task when there are test failures in the above situation.

**Plugins**
none.

**Screenshots**
none.

**Host/Environment (please complete the following information):**
n/a

**Additional context**
none.

**Comment by owaiskazi19** [comment]
@tlfeng can we close this issue?

**Comment by tlfeng** [comment]
Hi @owaiskazi19, before closing the issue, I would like to find out the code or the reason that not to fail the build when test failure occurs in these kinds of tests (YAML REST API test and High-Level-Rest-Client test).

**Comment by dreamer-89** [comment]
This issue can result in failure to identify changes, which actually break backword compatibility. Thus, adding `high-priority` label.

**Comment by andrross** [comment]
This is actually the desired behavior that was added in #2547

The idea is to do limited retries with the same seed. If it passes on a retry then it is a flaky test, but we don't necessarily want to fail the build in such a case.

**Comment by dblock** [comment]
I think this is working as expected. I'm closing this, reopen if you can show an example where all retries failed and we still reported success.
