### ISSUE TITLE
Remove usages of MultiTermQuery.setRewriteMethod

### ISSUE THREAD

**Issue by nknize** [opensearch-project/OpenSearch#2896]
`query.setRewriteMethod` is [removed in Lucene 9.2](https://github.com/apache/lucene/pull/726) so we will need to refactor all references to this method. In it's place we should use [MultiTermQuery.CONSTANT_SCORE_REWRITE](https://github.com/apache/lucene/blob/e6fb74f9090db2bc274af94c17d80739697bdc01/lucene/core/src/java/org/apache/lucene/search/MultiTermQuery.java#L81) as the default `method` parameter [whenever `null` is used](https://github.com/opensearch-project/OpenSearch/blob/c4b684d3ae0f56786f0b2c40b48d4329bd595a24/server/src/test/java/org/opensearch/index/mapper/TextFieldTypeTests.java#L175).  

Related #2879

**Comment by ruanwenjun** [comment]
@nknize @Va
Hi, I find this issue is mainly needing to reconstruct some code, I think I can do this, and I have submitted a PR #2997, please help to take a look, thanks.
