### ISSUE TITLE
[BUG] I can't find the dependencies of the plugin

### ISSUE THREAD

**Issue by akamachi95** [opensearch-project/OpenSearch#2915]
I am going to customize a plugin as I did in ES. But I can't find the dependencies of these file.
I just copy the classes from this project as below
```
import org.opensearch.index.analysis.TokenFilterFactory;
import org.opensearch.index.analysis.TokenizerFactory;
import org.opensearch.indices.analysis.AnalysisModule.AnalysisProvider;
import org.opensearch.plugins.AnalysisPlugin;
import org.opensearch.plugins.Plugin;
```
Where can I got all these, I didm't find it in the Maven Repository.

**Comment by dblock** [comment]
@akamachi95 Take a look at a working sample in https://github.com/opensearch-project/opensearch-plugin-template-java? If that doesn't help, post your project/a minimal non-working project to GitHub so we can try to help you?

**Comment by owaiskazi19** [comment]
Hi @akamachi95! Can you share your build.gradle file and can you confirm if you are using `https://aws.oss.sonatype.org/content/repositories/snapshots` as the maven url?

**Comment by minalsha** [comment]
@akamachi95  please feel free to open up this issue again or ask any follow up question. for now we will close this issue since we havent heard from you.
