### ISSUE TITLE
[META] Searchable Snapshot Tracking Issue

### ISSUE THREAD

**Issue by andrross** [opensearch-project/OpenSearch#2919]
- [x] #2900
- [x] #3895

Issues:
- [x] #2922
- [x] #2923
- [x] #4138
- [x] #3113
- - [x] #3114 
- - [x] #3961
- - [x] #3991
- - [x] #3115 
- [x] #4152 
- - [x] #4306
- - [x] #4420  
- - [x] #4535
- - [x] #4759
- - - [x] #4776
- - - [x] #4777
- [x] #4652 
- [x] #4655
- [x] #4778
- [x] #4797
- [x] #4962

**Comment by elfisher** [comment]
@andrross can we add the label for 2.4?
