### ISSUE TITLE
[BUG] min compatible version error message for 6.8

### ISSUE THREAD

**Issue by kavilla** [opensearch-project/OpenSearch#2936]
**Describe the bug**

Error message references non existence version of OpenSearch:
`**index** was created with version [6.8.1] but the minimum compatible version is [7.0.0]. It should be re-indexed in OpenSearch 7.x before upgrading to 2.0.0.`

**To Reproduce**
* With OpenSearch Dashboards
* Run `yarn test:bwc -d https://ci.opensearch.org/ci/dbc/distribution-build-opensearch-dashboards/2.0.0-rc1/2963/linux/x64/tar/dist/opensearch-dashboards/opensearch-dashboards-2.0.0-rc1-linux-x64.tar.gz -o https://ci.opensearch.org/ci/dbc/distribution-build-opensearch/2.0.0-rc1/latest/linux/x64/tar/dist/opensearch/opensearch-2.0.0-rc1-linux-x64.tar.gz -v odfe-0.10.0`

**Expected behavior**
Error message gives a valid upgrade message.

**Plugins**
all

**Screenshots**
n/a

**Host/Environment (please complete the following information):**

**Additional context**
n/a

**Comment by dblock** [comment]
@kavilla Still want this for 2.0?

**Comment by dblock** [comment]
@anasalkouz We should take a look for 2.0.

**Comment by kartg** [comment]
@dblock does this need to be investigated/resolved before 2.0.0 RC1 ?

**Comment by dblock** [comment]
@kartg I think so, but @anasalkouz should triage
