### ISSUE TITLE
OpenSearch dashboards v1.2 issue - Invalid index name [_hot][_warn], must not start with '_'

### ISSUE THREAD

**Issue by AlKapkone** [opensearch-project/OpenSearch#2939]
Hello, I’ve updated from AWS OpenSearch 1.1 to the latest 1.2. And now I’ve got an issue when trying to list my **hot** and **warm** indices.
What should I do to fix it? Any ideas?

_OpenSearch Dashboards → Index Management → Hot/Warm indices._

Full error:
```Error fetching warm indices. {"error":{"root_cause":[{"type":"invalid_index_name_exception","reason":"Invalid index name [_warm], must not start with '_'.","index":"_warm","index_uuid":"_na_"}], "type":"invalid_index_name_exception", "reason":"Invalid index name [_warm], must not start with '_'.","index":"_warm","index_uuid":"_na_"},"```

Is it a global issue or should I discuss it with the AWS OpenSearch support team for example?

**Comment by AlKapkone** [comment]
<img width="1792" alt="Знімок екрана 2022-04-17 о 16 14 01" src="https://user-images.githubusercontent.com/24461114/163802972-872ff334-4b9f-4ed3-b448-9f76b58722ea.png">

**Comment by AlKapkone** [comment]
@VachaShah Thanks for adding labels. Any ideas when this issue may be processed and investigated by the OpenSearch community?

**Comment by dbbaughe** [comment]
This is an issue in the managed service specifically, not OpenSearch.

If you are running into this issue please cut a support ticket as there is a fix that can be applied to your domain.

**Comment by dblock** [comment]
Thanks @dbbaughe, closing.

**Comment by AlKapkone** [comment]
Thanks, @dbbaughe
