### ISSUE TITLE
Remove mapping type usage

### ISSUE THREAD

**Issue by dreamer-89** [opensearch-project/OpenSearch#2979]
### Is your feature request related to a problem? Please describe.
As part of https://github.com/opensearch-project/OpenSearch/issues/1940 we completed all breaking changes as part of `2.0` release. In this issue, we plan to remove all remaining type usages from OpenSearch engine internals.

### Background
The mapping types have been deprecated in Elasticsearch (starting from 7.0) [1] with breaking changes to the index creation, put mapping, get mapping, put template, get template and get field mappings APIs and on track to be removed in 8.0 [2]. This is the debt Opensearch has inherited and the code related to mapping types support has to be removed. 
[1] https://www.elastic.co/guide/en/elasticsearch/reference/current/removal-of-types.html
[2] https://github.com/elastic/elasticsearch/issues/41059

#### Additional context
[Removal of mapping types] (https://www.elastic.co/guide/en/elasticsearch/reference/current/removal-of-types.html)
Captures remaining pending changes for Type mapping removal

Related: https://github.com/opensearch-project/OpenSearch/issues/1940

Pending changes
- [ ] https://github.com/opensearch-project/OpenSearch/issues/2357
- [ ] https://github.com/opensearch-project/OpenSearch/issues/2986
- [ ] https://github.com/opensearch-project/OpenSearch/issues/3131
- [ ] https://github.com/opensearch-project/OpenSearch/pull/3196
- [ ] https://github.com/opensearch-project/OpenSearch/issues/3074

**Comment by elfisher** [comment]
Are we tracking this as part of a campaign to remove mapping types usage?

**Comment by dreamer-89** [comment]
> Are we tracking this as part of a campaign to remove mapping types usage?

This tracks the pending `internal` and `non-breaking` remaining changes around removing mapping types.

**Comment by dreamer-89** [comment]
@reta @nknize : I listed down remaining `_type` references in the code base. Need your input on below. 
1. Run bulk index benchmark takes user input for typeName. Code [usage](https://github.com/opensearch-project/OpenSearch/blob/main/client/benchmark/src/main/java/org/opensearch/client/benchmark/AbstractBenchmark.java#L78), [defined here](https://github.com/opensearch-project/OpenSearch/blob/03fbca3f500d8541b4b32c1456997a8493ebe4f5/client/benchmark/src/main/java/org/opensearch/client/benchmark/rest/RestClientBenchmark.java#L81). type is taken as input from CLI. Is this benchmark still used today ?
2. BulkRequestParser.java has elseif [check](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/action/bulk/BulkRequestParser.java#L221) on _type field. This check should be removed as `_type` should be addressed as any other random word in request body; which is already handled [here](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/action/bulk/BulkRequestParser.java#L250). See this added previously and referred in BulkRequestParserTests inside `testTypesStillParsedForBulkMonitoring`. 
3. Can we remove [type validation](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/index/mapper/MapperService.java#L443) from MapperService & clean up [tests](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/test/java/org/opensearch/index/mapper/MapperServiceTests.java#L80https://github.com/opensearch-project/OpenSearch/blob/main/server/src/test/java/org/opensearch/index/mapper/MapperServiceTests.java%23L80). In 2.0 no type field is accepted and older indices would have already been validated.


Identified other references which can be removed without any issue. 

1. [ScriptProcessor](https://github.com/opensearch-project/OpenSearch/blob/main/modules/ingest-common/src/main/java/org/opensearch/ingest/common/ScriptProcessor.java#L67), [ConditionalProcessor](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/ingest/ConditionalProcessor.java#L63). Is it possible to provide _type from curl request and get these deprecations ?
2. Multiple references of _type in `_ingest/pipeline/_simulate` API across multiple places. Verified that `_type` is ignored by engine. Reference in a. [IngestRequestConverterTests.java](https://github.com/opensearch-project/OpenSearch/blob/main/client/rest-high-level/src/test/java/org/opensearch/client/IngestRequestConvertersTests.java#L124) b. IngestClientIT.java in [testSimulatePipeline](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/internalClusterTest/java/org/opensearch/ingest/IngestClientIT.java#L114) c. [grok_120.yml](https://github.com/opensearch-project/OpenSearch/blob/main/modules/ingest-common/src/yamlRestTest/resources/rest-api-spec/test/ingest/120_grok.yml#L137) yaml tests
3. ForEachProcessorTests.java  need to remove fieldValue in [TestProcessor constructor](https://github.com/opensearch-project/OpenSearch/blob/main/modules/ingest-common/src/test/java/org/opensearch/ingest/common/ForEachProcessorTests.java#L130).
4. [60_deprecated.yml](https://github.com/opensearch-project/OpenSearch/blob/main/rest-api-spec/src/main/resources/rest-api-spec/test/bulk/60_deprecated.yml) verifying deprecated `type` in bulk action. 
5. [CustomScriptPlugin](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/internalClusterTest/java/org/opensearch/search/fields/SearchFieldsIT.java#L145) adds `_type` field. Probably ignored on engine side and thus can be removed
6. [MultiTermVectorsResponse.java](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/action/termvectors/MultiTermVectorsResponse.java#L152) has `_type` defined in Fields class. It is not referenced and can be removed.
7. [UpdateHelper.java](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/action/update/UpdateHelper.java#L476) defines _type in ContextFields but not referenced anywhere.
8. Bunch of _type references in mocked API responses of reindex module `modules/reindex/src/test/resources/responses/*.json`
9. Tests for tests `ClientYamlTestSuitesTests, DoSectionTests, OpenSearchClientYamlSuiteTestCaseTests` have hard-coded request body.  
10. HLRC [TermsVectorRequest](https://github.com/opensearch-project/OpenSearch/blob/main/client/rest-high-level/src/main/java/org/opensearch/client/core/TermVectorsRequest.java#L270) still uses _type in toXContent.

**Comment by reta** [comment]
Thanks for summarizing, @dreamer-89, regarding your questions

> 1. Run bulk index benchmark takes user input for typeName. Code [usage](https://github.com/opensearch-project/OpenSearch/blob/main/client/benchmark/src/main/java/org/opensearch/client/benchmark/AbstractBenchmark.java#L78), [defined here](https://github.com/opensearch-project/OpenSearch/blob/03fbca3f500d8541b4b32c1456997a8493ebe4f5/client/benchmark/src/main/java/org/opensearch/client/benchmark/rest/RestClientBenchmark.java#L81). type is taken as input from CLI. Is this benchmark still used today ?

I actually don't know to be honest, but cleaning it up would be good in any case.

> 3. Can we remove [type validation](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/index/mapper/MapperService.java#L443) from MapperService & clean up [tests](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/test/java/org/opensearch/index/mapper/MapperServiceTests.java#L80https://github.com/opensearch-project/OpenSearch/blob/main/server/src/test/java/org/opensearch/index/mapper/MapperServiceTests.java%23L80).

It looks safe to be removed, 1.x does validate mapping types, so 2.0 should not run into that, @nknize wdyt?

**Comment by dreamer-89** [comment]
> Thanks for summarizing, @dreamer-89, regarding your questions
> 
> > 1. Run bulk index benchmark takes user input for typeName. Code [usage](https://github.com/opensearch-project/OpenSearch/blob/main/client/benchmark/src/main/java/org/opensearch/client/benchmark/AbstractBenchmark.java#L78), [defined here](https://github.com/opensearch-project/OpenSearch/blob/03fbca3f500d8541b4b32c1456997a8493ebe4f5/client/benchmark/src/main/java/org/opensearch/client/benchmark/rest/RestClientBenchmark.java#L81). type is taken as input from CLI. Is this benchmark still used today ?
> 
> I actually don't know to be honest, but cleaning it up would be good in any case.

Thanks @reta. Created issue https://github.com/opensearch-project/OpenSearch/issues/3074 to track this.

**Comment by dreamer-89** [comment]
This plugin seems to be not updated since 6.x as it uses custom typed end-point `/geonames/{type}/_noop_bulk` for ingestion. This `type` param (taken from CLI) is used only in [action meta data](https://github.com/opensearch-project/OpenSearch/blob/main/client/benchmark/src/main/java/org/opensearch/client/benchmark/rest/RestClientBenchmark.java#L83); while hard-coded type is used in rest end-point (`/geonames/type/_noop_bulk`); which means for all values of this param except type; this tool was broken. With removal of `type` param; this PR also fixes this issue. 

CC: @saratvemulapalli @VachaShah

**Comment by dreamer-89** [comment]
Closing this one as most of the changes have been completed except type validation removal from MapperService which needs more discussion (pointed below). Will open a separate issue to track that (and other type related usages if any). Closing this one as remaining changes have been merged. 

> Can we remove [type validation](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/index/mapper/MapperService.java#L443) from MapperService & clean up [tests](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/test/java/org/opensearch/index/mapper/MapperServiceTests.java#L80https://github.com/opensearch-project/OpenSearch/blob/main/server/src/test/java/org/opensearch/index/mapper/MapperServiceTests.java%23L80). In 2.0 no type field is accepted and older indices would have already been validated.

**Comment by mathemaphysics** [comment]
I'm trying to understand why over night (tonight), I'm being told my documents are using types when they're not and never have. I didn't upgrade. Nothing changed, but not Kibana tells me on the index template page that I'm using types and it now won't load or show anything of my mapping in the interface.

I started using composable component templates. That is the only change. And there are no complaints when running the curl commands to install the components and index templates which use them.

I'm extremely confused now.
