### ISSUE TITLE
support async search using RestHighLevelClient

### ISSUE THREAD

**Issue by Wildsoft** [opensearch-project/OpenSearch#2982]
Apparently, unlike elastic search, OpenSearch does not support submitting async searches (https://opensearch.org/docs/latest/search-plugins/async/index/)

It would be great to get it supported

Thank you,
Boris

**Comment by dblock** [comment]
@Wildsoft Are you looking for https://github.com/opensearch-project/asynchronous-search? I'll close this, but feel free to open new issues in that project if there are any gaps in this functionality in OpenSearch
