### ISSUE TITLE
Remove support for `_type` in searches

### ISSUE THREAD

**Issue by dreamer-89** [opensearch-project/OpenSearch#2986]
This issue tracks the removal of `_type` from all search request related classes (FieldTypeLookUp, TypeFieldType etc). There are few ITs still using `_type` for terms, sorted terms queries. As part of this issue, need to remove them all. 

Verified that `_type` reference in terms query, ids query throws proper unknown field exception 

Sample Request
```
curl -X PUT localhost:9200/test-index

curl -X POST localhost:9200/test-index/_doc -d '{ 
    "field" : "value"
}'

curl -X POST localhost:9200/test-index/_doc -d '{ 
    "field" : "value2"
}'

curl -XPOST localhost:9200/test-index/_search?pretty -d '{
    "query": {
        "terms": {
            "field": {
                "index": "test-index",
                "id": "lfy6Q4ABr3FIIAx0k9_1",
                "path": "",
                "type": "_doc"
            }
         }
    }
}'
```

Response
```
{
    "error": {
        "root_cause": [
            {
                "type": "x_content_parse_exception",
                "reason": "[8:17] [terms_lookup] unknown field [type]"
            }
        ],
        "type": "x_content_parse_exception",
        "reason": "[8:17] [terms_lookup] unknown field [type]"
    },
    "status": 400
}
```

Related: #2979

**Comment by dreamer-89** [comment]
I see `exists` query with `_type` value in `field` fetches all record. I am not sure if this is a bug and should be fixed in `2.0` release. @nknize @reta : WDYT about this ?

Request
```
curl -XPOST localhost:9200/test-index/_search?pretty -d '
{
    "query": {
        "exists": {
            "field": "_type"
         }
    }
}'
```

Response
```
{
    "took": 2,
    "timed_out": false,
    "_shards": {
        "total": 1,
        "successful": 1,
        "skipped": 0,
        "failed": 0
    },
    "hits": {
        "total": {
            "value": 4,
            "relation": "eq"
        },
        "max_score": 1.0,
        "hits": [
            {
                "_index": "test-index",
                "_id": "kvyyQ4ABr3FIIAx07N_Z",
                "_score": 1.0,
                "_source": {
                    "field": "value"
                }
            },
            {
                "_index": "test-index",
                "_id": "lfy6Q4ABr3FIIAx0k9_1",
                "_score": 1.0,
                "_source": {
                    "field": "value2"
                }
            }
        ]
    }
}
```

**Comment by reta** [comment]
> I see exists query with _type value in field fetches all record. I am not sure if this is a bug and should be fixed in 2.0 release

thanks @dreamer-89, I think it is a bug, the `_type` field should not be exposed anywhere (since we removed relevant queries as well).

**Comment by dreamer-89** [comment]
> > I see exists query with _type value in field fetches all record. I am not sure if this is a bug and should be fixed in 2.0 release
> 
> thanks @dreamer-89, I think it is a bug, the `_type` field should not be exposed anywhere (since we removed relevant queries as well).

Thanks @reta. Created https://github.com/opensearch-project/OpenSearch/issues/2989 to track this.

**Comment by dreamer-89** [comment]
A straightforward fix is to have check on `_type` in `ExistsQueryBuilder` [here](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/index/query/ExistsQueryBuilder.java#L70) but that would mean a separate handling for `_type` fields and throwing exception.

This will not be a good solution as it introduces explicit check for `_type` keyword. Instead of this, engine should return empty response as it does for any other random field.

**Comment by dreamer-89** [comment]
This is implemented in https://github.com/opensearch-project/OpenSearch/pull/3016 and thus can be closed.
