### ISSUE TITLE
Support use of IRSA for repository-s3 plugin credentials

### ISSUE THREAD

**Issue by scaswell-tsys** [opensearch-project/OpenSearch#2999]
**Is your feature request related to a problem? Please describe.**
The corporate standard at our organization for products running inside AWS EKS is to use IAM Roles for Service Accounts (IRSA) to provide credentials for authentication to AWS services such as S3. This does not appear to be supported in the repository-s3 plugin.

**Describe the solution you'd like**
The ability to omit access key and secret key and have the repository-s3 plugin rely on the identity provided to the Pod running OpenSearch for credentials.

**Describe alternatives you've considered**
There are not a lot of alternatives. Until IRSA is supported we will be forced to use an access key/secret key combination. However this is contrary to the standard imposed by our Infosec organization and we'll be forced to obtain an exception (not an attractive proposition).

**Additional context**
We are specifically trying to deploy OpenSearch and repository-s3 plugin version 1.2.4. We have not tried to use version 1.3.1 but as far as I can tell (based on source code, documentation, and forums) IRSA is not supported in 1.3.1.

**Comment by reta** [comment]
@Poojita-Raj taking it if no one is working on it

**Comment by reta** [comment]
@scaswell-tsys do you have the opportunity to verify the IRSA flow? (it was tested successfully on AWS EKS)
