### ISSUE TITLE
[BUG] Nebula Gradle info plugin upgrade errors

### ISSUE THREAD

**Issue by VachaShah** [opensearch-project/OpenSearch#3002]
**Describe the bug**
After upgrading the nebula gradle info plugin (#2831), when applying `opensearch.build` plugin in gradle, it is causing the below error:

```
A problem occurred evaluating root project 'bwc-test'.
> Failed to apply plugin 'nebula.info-basic'.
   > Cannot obtain value from provider of system property 'user.name' at configuration time.
     Use a provider returned by 'forUseAtConfigurationTime()' instead.
```

Security plugin faced this issue when moving to 2.0 for bwc tests - #2987 

**To Reproduce**
Added in #2987 

**Expected behavior**
The upgrade does not cause errors.

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**

**Comment by andrross** [comment]
@VachaShah I see that we are using the [upgraded version on main currently](https://github.com/opensearch-project/OpenSearch/blob/main/buildSrc/build.gradle#L110). Does this mean that plugins are currently broken on main (3.0) because of this?

**Comment by saratvemulapalli** [comment]
Another PR related to the same package: https://github.com/opensearch-project/OpenSearch/pull/3250

**Comment by owaiskazi19** [comment]
Hi @cliu123! Coming from https://github.com/opensearch-project/OpenSearch/issues/2987. I tried to change the gradle version [here](https://github.com/opensearch-project/security/blob/main/bwc-test/gradle/wrapper/gradle-wrapper.properties#L3) to 7.3.3-bin and bwc test did pass for me. Can you try it out and let us know if it resolves the issue?

**Comment by dbwiddis** [comment]
This appears to have been a bug in Gradle 6.X which was fixed in Gradle 7: https://github.com/gradle/gradle/issues/13333

The failing github action in the link was running on Gradle 6.9.

Believe no action is required here other than to ensure Gradle 7.x+ is used to build.

**Comment by dbwiddis** [comment]
Identified3 plugins using 6.x gradle wrapper.  Will submit PRs to update.

**Comment by dbwiddis** [comment]
Closing this issue:
 - The version is already updated in OpenSearch and has been shown not to have issues with Gradle 7+
 - PR submitted to opensearch.build to upgrade there
 - data-prepper already upgraded
 - perftop has older version but doesn't build due to other compatibilities; project appears currently unmaintained to address these
