### ISSUE TITLE
Remove JavaVersion in favour of standard Runtime.Version (java-version-checker)

### ISSUE THREAD

**Issue by reta** [opensearch-project/OpenSearch#3008]
**Is your feature request related to a problem? Please describe.**
Since JDK-9, the JDK provide standard means to manipulate runtime version using  `Runtime` and `Runtime.Version`.

**Describe the solution you'd like**
Remove `JavaVersion` in favour of standard `Runtime.Version`

**Describe alternatives you've considered**
Keep this duplicate hierarchy of classes

**Additional context**
Since 2.0 set JDK-11 as baseline, we could use `Runtime.Version` in  `java-version-checker` and drop all checks for JDK-8/9/10

**Comment by elfisher** [comment]
Thanks for raising this @reta! Is this going to be a breaking change?

**Comment by reta** [comment]
Thanks @elfisher , it could be considered a breaking change: the `JavaVersion` is public class and in general and it could be used outside of core (fe in plugins), I will add it to the list of breaking changes for 2.0.
