### ISSUE TITLE
[BUG] release build with no-jdk still ship the jdk15

### ISSUE THREAD

**Issue by spk** [opensearch-project/OpenSearch#3024]
**Describe the bug**

Currently `./gradlew :distribution:packages:no-jdk-deb:assemble` build still ship the jdk15 in the deb package and use it on runtime

Related with https://github.com/opensearch-project/opensearch-build/issues/99

**To Reproduce**
1. Build `./gradlew :distribution:packages:no-jdk-deb:assemble`
2. Check the resulting package in `distribution/packages/deb/build/distributions`
3. Inside the data.tar.gz the `/./usr/share/opensearch/jdk/bin/` is present where it should not

**Expected behavior**

`/./usr/share/opensearch/jdk` should not be present

**Plugins**

none

**Screenshots**

**Host/Environment (please complete the following information):**
 - OS: Linux

**Additional context**

I think the issue have been introduced in https://github.com/opensearch-project/OpenSearch/commit/83e87f7e541bf1153645762261f54c73bb766ee6#diff-f56331345059500af66c2e736bf18b5ee62d763d1d43af57a95a7709da1894ddR344 the second argument should have been kept (its currently true but it should be false for no-jdk build since first arg is jdk now)

On ES 7.10 https://github.com/elastic/elasticsearch/blob/7.10/distribution/packages/build.gradle#L371

**Comment by dblock** [comment]
@spk Would appreciate a fix! Also note https://github.com/opensearch-project/opensearch-build/issues/99, which needs more work
