### ISSUE TITLE
[Doc] Thread Pool documentation for opensearch

### ISSUE THREAD

**Issue by Vineet-Sharma29** [opensearch-project/OpenSearch#3041]
**Is your feature request related to a problem? Please describe.**
I was looking through response of `_cat/thread_pool` API and couldn't find documentation for threadpools. I am unable to get clarity of which threadpool is meant for what purpose.

**Describe the solution you'd like**
Separate documentation for threadpools in opensearch

**Describe alternatives you've considered**

**Additional context**
 Particularly in my case, I am working with async search and unable to get clarity on `opensearch_asynchronous_search_generic` threadpool.

**Comment by Poojita-Raj** [comment]
Issue moved to [opensearch-project/documentation-website #524](https://github.com/opensearch-project/documentation-website/issues/524) via [**ZenHub**](https://www.zenhub.com/)
