### ISSUE TITLE
Change default no_master_block from write to metadata_write

### ISSUE THREAD

**Issue by Bukhtawar** [opensearch-project/OpenSearch#3045]
**Is your feature request related to a problem? Please describe.**
When there is no master in the cluster, or a node is partitioned off the cluster all writes see a 5xx, this leads to availability drop espl when there is a master quorum loss(writes do not need a quorum to succeed)
https://github.com/opensearch-project/OpenSearch/blob/1193ec101b5d840c78ff3fa7a76cc0488f99f7ab/server/src/main/java/org/opensearch/cluster/coordination/NoMasterBlockService.java#L74-L81

**Describe the solution you'd like**
We can switch the default to only fail metadata writes as a part of index creation/dynamic mapping updates but let other writes succeed. Dynamic mapping updates is not the recommended way to handle mappings.
The caveat with this change is is the node is partitioned off and there was no replication configured, rarely the partitioned node can keep taking traffic, acknowledging all writes, reads might not be able to see those writes for as long as the node remains partitioned.  
This however is not a problem with replica enabled, since when the primary starts to replicate, the replica node(which automatically gets promoted to primary post partition) rejects those writes coming from the partitioned node, ultimately failing the write request.
So in essence this should help cases where there is loss of quorum due to losing more than one dedicated masters at once transiently

**Describe alternatives you've considered**

**Additional context**

**Comment by shwetathareja** [comment]
>This however is not a problem with replica enabled, since when the primary starts to replicate, the replica node(which automatically gets promoted to primary post partition) rejects those writes coming from the partitioned node, ultimately failing the write request. 

@Bukhtawar Network partitioning could still be an issue in case multiple nodes are partitioned like 2 nodes hosting primary & replica both gets partitioned (e.g. in case of index with 1 shard).

One option I am thinking is lets say, there is a background monitor which maintains count of no. of nodes in the cluster always and when no_master _block is applied, data nodes exchange this count and will only accept document writes till the count remains same and at any point if the count changes (it can only go down), then they would stop taking writes. They can figure out this count going down using `NodeConnectionsService.java` if the connection with any other data node goes down. Thoughts?

**Comment by gbbafna** [comment]
> @Bukhtawar Network partitioning could still be an issue in case multiple nodes are partitioned like 2 nodes hosting primary & replica both gets partitioned (e.g. in case of index with 1 shard).

Wouldn't that return 5XX to the call and should be okay ? Even in the current scenario of `no_master_block` , it would return a 5XX to the reads.  With `metadata_write`,  the writes would go through  and even the reads when it lands on the partitioned nodes.

**Comment by Bukhtawar** [comment]
> @Bukhtawar Network partitioning could still be an issue in case multiple nodes are partitioned like 2 nodes hosting primary & replica both gets partitioned (e.g. in case of index with 1 shard).

@tharejas I think reads would return 5xx as @gbbafna also pointed if both primary and replica shards are partitioned off, however in this case we won't have divergent writes to start with which would otherwise impact data consistency. Do you still have concerns with the proposed change without additional monitoring in place?

**Comment by Bukhtawar** [comment]
Closing as fixed https://github.com/opensearch-project/OpenSearch/pull/3621
