### ISSUE TITLE
[Searchable Snapshot] Understand and document the current file system and directory structure for snapshots

### ISSUE THREAD

**Issue by kotwanikunal** [opensearch-project/OpenSearch#3113]
- Remote Storage will function as a primary or secondary data store in the future based on the cluster configuration
- We need documentation on the current file system and directory structure of how snapshots are currently structured
- This will enable us to work backwards in designing and optimizing the Store structure for Remote Storage

**Comment by dreamer-89** [comment]
@kotwanikunal : Is there any documentation you compiled as part of this issue ? Will be super useful for users and will assist in understanding design of remote searchable snapshots.

**Comment by AmiStrn** [comment]
> @kotwanikunal : Is there any documentation you compiled as part of this issue ? Will be super useful for users and will assist in understanding design of remote searchable snapshots.

This is what I expected when I read the title. was expecting a document:)

**Comment by kotwanikunal** [comment]
> > @kotwanikunal : Is there any documentation you compiled as part of this issue ? Will be super useful for users and will assist in understanding design of remote searchable snapshots.
> 
> This is what I expected when I read the title. was expecting a document:)

@dreamer-89 This issue was related to the current mechanisms of OpenSearch snapshots. I do have compiled notes and previous documents which do cover the underlying files and actual snapshot process within OpenSearch.
@AmiStrn I'll try to find the right location to publish it and put this out soon.

**Comment by kotwanikunal** [comment]
@AmiStrn @dreamer-89 The post is out [here](https://opensearch.org/blog/technical-post/2022/09/snapshot-operations/).
