### ISSUE TITLE
[Searchable Snapshot] Design and define the interfaces for file and directory structures for Remote Storage

### ISSUE THREAD

**Issue by kotwanikunal** [opensearch-project/OpenSearch#3114]
- Remote Storage will function as a primary or secondary data store in the future based on the cluster configuration
- The goal of this issue is to design the interfaces for the basic building blocks of remote storage - file system, directory and store mechanisms 

Additional Context: 
- https://github.com/opensearch-project/opensearch/issues/3113

**Comment by sachinpkale** [comment]
@kotwanikunal As part of https://github.com/opensearch-project/OpenSearch/issues/2700, I am working on defining `RemoteDirectory` interface. PR link: https://github.com/opensearch-project/OpenSearch/pull/3102 . Do you think this issue has overlap with `RemoteDirectory` interface?

**Comment by kotwanikunal** [comment]
> @kotwanikunal As part of #2700, I am working on defining `RemoteDirectory` interface. PR link: #3102 . Do you think this issue has overlap with `RemoteDirectory` interface?

There will be overlap and I will work with the currently defined interfaces to enable a read-only mechanism for the searchable snapshot use case.

**Comment by kotwanikunal** [comment]
Design proposal: https://github.com/opensearch-project/OpenSearch/issues/3869

**Comment by kotwanikunal** [comment]
Published the detailed design here: #4033
