### ISSUE TITLE
[Feature/extensions] Add Rest Handlers support for extensions

### ISSUE THREAD

**Issue by saratvemulapalli** [opensearch-project/OpenSearch#3130]
Plugins register custom REST APIs and expose them to users.
Extensions framework should add support to these Rest Handlers. 

https://github.com/opensearch-project/OpenSearch/blob/21468279b2731aea5556f290c6e4fca7ea0e291e/server/src/main/java/org/opensearch/plugins/ActionPlugin.java#L102

**Comment by minalsha** [comment]
This has been completed as part of https://github.com/opensearch-project/opensearch-sdk-java/issues/64
