### ISSUE TITLE
[Remote Segment Store] Delete merged away segment files from remote segment store

### ISSUE THREAD

**Issue by sachinpkale** [opensearch-project/OpenSearch#3142]
**Describe the solution you'd like**
Lucene segments are immutable files. Once segments are created, they can be deleted due to various flows, one of the flows could be segment merge. These merged away segments are deleted from local filesystem. To keep remote segment store in-sync with the local filesystem, we need to delete these segments from remote segment store as well. 
The delete flow need not be in sync and can be done in periodic manner. But to keep the data integrity, we need to mark the files as deleted.

**Comment by mch2** [comment]
I'd imagine we could reuse these incremental updates as snapshots vs needing a separate snapshot/restore flow.  Should we provide some way of marking specific incremental uploads so they are not deleted?
