### ISSUE TITLE
[Question] spatial query deprecation?

### ISSUE THREAD

**Issue by rhysstubbs** [opensearch-project/OpenSearch#3180]
**Is your feature request related to a problem? Please describe.**
No

**Additional context**

Also, elastic search deprecated `geo_polygon` queries in 7.12 ([see here](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-geo-polygon-query.html
)) - is the same true for OpenSearch, is this deprecated also?

Excuse what perhaps might seem like a stupid question but I am using OpenSearch but referencing documentation from elastic.co, does OpenSearch have it's own documentation? I'm struggling to answer my own questions because I can't read OpenSearch documentation and instead stuck making assumption from Elastic Search docs...

**Comment by dblock** [comment]
No stupid questions here. OpenSearch documentation is at https://opensearch.org/docs/latest.

The `geo_polygon` queries have not been deprecated AFAIK. OpenSearch is a fork at Elasticsearch 7.10, so consider them as two different products.

I'll close this, but feel free to ask more questions here or maybe https://forum.opensearch.org/.
