### ISSUE TITLE
[Feature/extensions] Gradle check failures

### ISSUE THREAD

**Issue by saratvemulapalli** [opensearch-project/OpenSearch#3282]
- [ ] SniffConnectionStrategyTests.testConnectFailsIfNoConnectionsOpened
- [ ] TransportServiceHandshakeTests.testNodeConnectWithDifferentNodeI
[test files](https://github.com/opensearch-project/OpenSearch/files/8665407/test.zip)

**Comment by minalsha** [comment]
This is already addressed and taken care of by @ryanbogan . Gradle check is passing on feature/extension branch. Hence closing the issue.
