### ISSUE TITLE
[BUG] The deprecation message of `DeprecatedRoute` doesn't show in the API response

### ISSUE THREAD

**Issue by cliu123** [opensearch-project/OpenSearch#3290]
**Describe the bug**
The [deprecation message](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/rest/RestHandler.java#L199) of `DeprecatedRoute` doesn't show in the API response

**To Reproduce**
1. Checkout [the branch](https://github.com/cliu123/security/tree/add_allowlist_configuration_and_deprecate_whitelist)
2. Check the [DeprecatedRoute](https://github.com/opensearch-project/security/pull/1808/files#diff-966c00b72e7b722154a67d2fb411925edfea951320a0f4b28b9f6b2d77d9a36eR81-R85). Wait for a couple of seconds to allow the page to be redirected to the highlighted lines.
This is the same approach using `DeprecatedRoute` as [here](https://github.com/opensearch-project/OpenSearch/blob/86f8dd65a45810ae671ee1f607a2d5287649d66b/server/src/main/java/org/opensearch/rest/action/admin/cluster/RestNodesHotThreadsAction.java#L99-L107).
4. Build security plugin: `./gradlew clean build -Dbuild.snapshot=false -x test`
5. Get the security plugin zip file from `build/distribution` folder.
6. Install security plugin on OpenSearch 2.0
7. Log into OpenSearch node and go to the folder `opensearch/config`
8. Send the whitelist API request with super admin certs.
```
curl -k -i --cert kirk.pem --key kirk-key.pem https://localhost:9200/_plugins/_security/api/whitelist\?pretty -u admin:admin --insecure
```
**Expected response**
The deprecation message(`"[/whitelist] is a deprecated endpoint. Please use [/allowlist] instead."`) should show in the response

**Actual response**
The deprecation message doesn't show in the response or the logs.
```
HTTP/1.1 200 OK
content-type: application/json; charset=UTF-8
content-length: 171

{
  "config" : {
    "enabled" : false,
    "requests" : {
      "/_cluster/settings" : [
        "GET"
      ],
      "/_cat/nodes" : [
        "GET"
      ]
    }
  }
}
```

**Plugins**
Security plugin

**Comment by tlfeng** [comment]
@cliu123 Thanks for reporting this issue.

As far as I know, there is a warning header added to the HTTP response, and can be retrieved by Java Rest Client. I guess the warning header doesn't meet the protocol, so it isn't shown in browser or curl command, while I need to validate this doubt.
The deprecation log should be written into the log directory, `logs/opensearch_deprecation.log`, and is not shown in the console output. I validated that using deprecated REST API of OpenSearch (core), such as `GET cat/master`, there will be deprecation log generated. But I need to validate the behavior of using deprecated REST API from a plugin.

**Comment by cliu123** [comment]
> @cliu123 Thanks for reporting this issue.
> 
> As far as I know, there is a warning header added to the HTTP response, and can be retrieved by Java Rest Client. I guess the warning header doesn't meet the protocol, so it isn't shown in browser or curl command, while I need to validate this doubt. The deprecation log should be written into the log directory, `logs/opensearch_deprecation.log`, and is not shown in the console output. I validated that using deprecated REST API of OpenSearch (core), such as `GET cat/master`, there will be deprecation log generated. But I need to validate the behavior of using deprecated REST API from a plugin.

@tlfeng Thanks for checking this! The deprecation message doesn't even get logged in `logs/opensearch_deprecation.log` in this case.

**Comment by tlfeng** [comment]
After calling `/_plugins/_security/api/whitelist` API using your curl command, I saw there is new lines of deprecation notice logged in the 2 files:

logs/opensearch_deprecation.log
```
[2022-05-12T21:57:58,299][DEPRECATION][o.o.d.r.RestController   ] [ip-172-31-15-168] [/whitelist] is a deprecated endpoint. Please use [/allowlist] instead.
```
logs/opensearch_deprecation.json
```
{"type": "deprecation", "timestamp": "2022-05-12T21:57:58,299-07:00", "level": "DEPRECATION", "component": "o.o.d.r.RestController", "cluster.name": "opensearch", "node.name": "ip-172-31-15-168", "message": "[/whitelist] is a deprecated endpoint. Please use [/allowlist] instead.", "cluster.uuid": "2ytBlTbVTPqhxTXEF1YXBw", "node.id": "sjIP6WxwQHy4cO-SvTi5cw"  }
```

**Comment by cliu123** [comment]
I realized that I didn't build the latest changes in security plugin. After building on the latest change, I see the deprecation logs in `logs/opensearch_deprecation.log` and `logs/opensearch_deprecation.json` now.
Is it possible at all to feed the deprecation messages to the API response?

**Comment by tlfeng** [comment]
😄 Thanks for the update!
I think the same deprecation notice is added in to the HTTP response header, with a warning code 299, but I have no idea how to make it shown in browser and curl command.
The code: https://github.com/opensearch-project/OpenSearch/blob/2.0.0-rc1/server/src/main/java/org/opensearch/common/logging/HeaderWarning.java#L84 

I don't have idea either about the other way to show a deprecation messages in the API response, so need to spend some time thinking of it.

**Comment by reta** [comment]
@cliu123 you should be able to get `Warning` header by by adding

```
appender.header_warning.type = HeaderWarningAppender
appender.header_warning.name = header_warning                                                
```

to `config/log4j2.properties`.

**Comment by adnapibar** [comment]
No pending code changes for 2.0.0 release, removing the label.

**Comment by cliu123** [comment]
The expected behavior has been clarified! Thanks @tlfeng @reta! Closing the issue.
