### ISSUE TITLE
[BUG]The index template does not support configuring ism policy？ 

### ISSUE THREAD

**Issue by lliu0947** [opensearch-project/OpenSearch#3294]
**Describe the bug**
I want to create a data stream and add ism policy to the data stream。How to add an ism policy when creating an index template？ the [index template documentation](https://opensearch.org/docs/latest/opensearch/index-templates/) does not give the corresponding example and the fields supported by the template。

**To Reproduce**
create index template

> 

PUT _index_template/logs-index-template
{

      "index_patterns": "logs-index",
      "data_stream": {
            "timestamp_field": {
                  "name": "request_time"
             }
      },
     "priority": 200,
     "template": {
          "aliases": {
               "my_logs": {}
           },
       "settings": {
            "number_of_shards": 1,
             "number_of_replicas": 0,
            "index":{
               "lifecycle": {
                   "name": "test-ism-api"
               }
           }
         }
    }
 }

some error like this：

 `{
  "error" : {
    "root_cause" : [
      {
        "type" : "invalid_index_template_exception",
        "reason" : "index_template [logs-index-template-1] invalid, cause [Validation Failed: 1: unknown setting [index.lifecyle.name] please check that any required plugins are installed, or check the breaking changes documentation for removed settings;2: expected [index.lifecyle.name] to be private but it was not;]"
      }
    ],
    "type" : "invalid_index_template_exception",
    "reason" : "index_template [logs-index-template-1] invalid, cause [Validation Failed: 1: unknown setting [index.lifecyle.name] please check that any required plugins are installed, or check the breaking changes documentation for removed settings;2: expected [index.lifecyle.name] to be private but it was not;]"
  },
  "status" : 400
}
`

so The template object field can only configure index setting、alias and mappings？Or how to add an ism policy when creating an index template

In addition, it supports adding policy configuration when creating an index template in es，an example:

 PUT _index_template/ilm-test
 {
      "version": 5,
       "priority": 2147483647,
       "template": {
             "settings": {
                  "index": {
                       "lifecycle": {
                              "name": "ilm-history-ilm-policy">                       
                        },
                 "number_of_shards": "1",
                 "number_of_replicas": "0"
              }
   },
     "index_patterns": [
          "ilm-history-5*"
  ]
}

GET _index_template/logs-index-template
{
  "index_templates" : [
    {
      "name" : "logs-index-template",
      "index_template" : {
        "index_patterns" : [
          "logs-index"
        ],
        "template" : {
          "settings" : {
            "index" : {
              "lifecycle" : {
                "name" : "test-ism-api"
              },
              "number_of_shards" : "1",
              "number_of_replicas" : "0"
            }
          },
          "aliases" : {
            "my_logs" : { }
          }
        },
        "composed_of" : [ ],
        "priority" : 200,
        "data_stream" : {
          "hidden" : false
        }
      }
    }
  ]
}

**Expected behavior**
index template support configure ism policy, and if supported, I hope the document can be written in more detail

**Comment by dblock** [comment]
@lliu0947 did you solve your problem? how?

**Comment by lliu0947** [comment]
> 
yeah，i have solved。Do you have plans to migrate the bug fix patch of the higher es version to opensearch？

**Comment by dblock** [comment]
@lliu0947 how did you solve it? what bug fix patch?

OpenSearch cannot copy non-APLv2 code from ES 7.10+, but feel free to reimplement any fixes independently and PR them into OpenSearch.

**Comment by saketjain01** [comment]
Hello,

Curious to know if there is any fix available in opensearchapi-go for implementing ISM policy for the data streams.
Appreciate any pointers or alternative implementation for achieving it.

**Comment by max-ch-88** [comment]
@lliu0947 how did you solve your problem?
