### ISSUE TITLE
Add equivalent to "terms lookup" to fetch list of terms from different index

### ISSUE THREAD

**Issue by wfscot** [opensearch-project/OpenSearch#3300]
**Is your feature request related to a problem? Please describe.**
We would like a feature similar to Elastic's "terms lookup" (https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-terms-query.html#query-dsl-terms-lookup)

An example of how this might be used:
- Suppose you have an index that represents individual sales with both customerId and productId fields.
- This data could be rolled up to a different index with tiers of customers and products (highest selling, lowest selling, etc.)
- If there was some way to lookup terms from this rollup index, you could then easily filter sales data by customer and/or product tiers

**Describe the solution you'd like**
We are certainly open to alternative solutions, but something like Elastic's terms lookup seems like a nice solution.

It is completely understood that this terms lookup would only work with relatively small sets of terms (e.g. thousands of terms at most) and that the full list of terms would need to be shared out to all nodes involved in the containing query.

**Describe alternatives you've considered**
It's hard to think of another way to do this without doing something entirely outside of OpenSearch, for example:
- Manually running the term lookup query and then copying/pasting results (again, up to thousands of terms) into each term query that needs it
- Doing the above only via some scheduled external process (AWS Lambda, etc.)

**Additional context**
No additional content.

Thank you!

**Comment by mattweber** [comment]
@wfscot did you try terms lookup in OpenSearch?  Elastic's terms lookup was available before the fork and should exist in OpenSearch.  OpenSearch docs are not great so refer to [elastic's docs for 7.10](https://www.elastic.co/guide/en/elasticsearch/reference/7.10/index.html) which is what OpenSearch is based on. For the most part, if you see it in elastic's docs it should work in OpenSearch.

**Comment by wfscot** [comment]
My bad! That does indeed work. Thank you!

Lesson learned on the docs. I'll be sure to keep this in mind going forward.  Closing the issue.
