### ISSUE TITLE
Measuring the distance between two distributions of vectors

### ISSUE THREAD

**Issue by igaloly** [opensearch-project/OpenSearch#3342]
I have 2 buckets.
Each bucket holds documents.
Each document has a vector field.
I want to measure the distance between them.
To measure the distance, I need to **take the mean vector out of each bucket**, and calculate the delta between them.

What the best way to save the vectors (`knn_vector` ? spread the vector to discrete field `x0`, `x1`, `x2`?) and perform the calculation of the mean vector? (Painless script that iterates the vector, save in the state the sum of each dimension and calculate the average in the `reduce_script`?)

**Comment by dblock** [comment]
This feels like a job for https://github.com/opensearch-project/k-nn, https://opensearch.org/docs/latest/search-plugins/knn/index, specifically https://opensearch.org/docs/latest/search-plugins/knn/painless-functions/. Does this help?

This is probably best asked in https://forum.opensearch.org/, GH is for issues/bugs, I'll close the issue for now, but feel free to reopen if you feel like there's a problem.

**Comment by igaloly** [comment]
I don't see how can I utilize the sources you sent to perform my task.
I'll ask in the forum. Thank you!
