### ISSUE TITLE
[Upgrade] OpenSearch 2.0 to Lucene 9.2

### ISSUE THREAD

**Issue by nknize** [opensearch-project/OpenSearch#3382]
[Lucene 9.2 Release Vote](https://t.co/5iFsv4RIHz) has started. This means Lucene 9.2 is on track to be released before OpenSearch 2.0 GA. OpenSearch 2.0 RC1 was [released with Lucene 9.1](https://github.com/opensearch-project/OpenSearch/blob/2.0.0-rc1/buildSrc/version.properties#L2). I propose upgrading 2.0 branch and release OpenSearch 2.0 GA w/ Lucene 9.2.

**Comment by dblock** [comment]
@nknize Let's PR that update when Lucene 9.2 gets released and see whether we've started the release process for the distribution already, which would then require doing a reset and changing the release date
