### ISSUE TITLE
[BUG] Lucene Snapshot Github Action Failing

### ISSUE THREAD

**Issue by nknize** [opensearch-project/OpenSearch#3383]
There was an error in the OpenSearch Lucene Snapshots github action when trying to [publish latest lucene-9.2.0-snapshot](https://github.com/opensearch-project/OpenSearch/runs/6495589643?check_suite_focus=true#step:6:67). The error is below:

```
Execution failed for task ':checkJdkInternalsExportedToGradle'.
> Certain gradle tasks and plugins require access to jdk.compiler internals, your gradle.properties might have just been generated or could be out of sync (see help/localSettings.txt)
```

This needs to be looked at so we can quickly build an updated 9.2. snapshot in prep for upgrading main and 2.x branches ([and possibly 2.0](https://github.com/opensearch-project/OpenSearch/issues/3382))

**Comment by mch2** [comment]
Looks like #3396 [fixed](https://github.com/opensearch-project/OpenSearch/actions/runs/2352771731) the issue.  Closing.
