### ISSUE TITLE
[Remote Store] Handle transient and permanent un-availability of the remote store

### ISSUE THREAD

**Issue by sachinpkale** [opensearch-project/OpenSearch#3397]
**Describe the solution you'd like**
When remote store is un-available, either we need to stop ingestion in order to keep the durability guarantees or ingestion continues and data is back-filled once remote store is available. There are various scenarios that need to be considered while handling these failures. This task describes all such scenarios and provide implementation.

**Comment by ashking94** [comment]
we have implemented refresh retry and remote segments upload backpressure - #7363 and #6851.

**Comment by ashking94** [comment]
@sachinpkale  closing this issue for now. Lets think if there are more things that we can add and reopen if needed.
