### ISSUE TITLE
Where to start to understand OpenSearch code better before start contributing

### ISSUE THREAD

**Issue by baleshkumar** [opensearch-project/OpenSearch#3399]
Hi Team,

I want to contribute to OpenSearch and before I do that I need to learn how code is structured, important classes/packages/modules (along with their responsibilities), how request flows etc. 

I have checked the developer guide but it only provide first level of details like high project layout. Could someone please share the document link of any other tips to understand the code please.

Thanks

**Comment by adnapibar** [comment]
@baleshkumar thanks for showing interest and we welcome you to contribute to OpenSearch.  I think the best way to learn is to work on an issue, we have a bunch of issues tagged as [good first issue](https://github.com/opensearch-project/OpenSearch/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22+) , feel free to pick one. 

The  https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md is the starting point. Also, 
 check out the [Java doc](https://opensearch.org/javadocs/2.0.0-rc1/OpenSearch/server/build/docs/javadoc/index.html)

**Comment by dblock** [comment]
I'm going to close this issue, thanks @adnapibar. @baleshkumar feel free to ask more specific questions here/or on forums as well (https://forum.opensearch.org/)
