### ISSUE TITLE
[BWC] How should support be handled for OpenSearch / Plugins versions?

### ISSUE THREAD

**Issue by peternied** [opensearch-project/OpenSearch#3440]
With the release of 2.0.0, plugin branches are migrating to versions 2.1 and 3.0.  Is there a recommendation for common settings for backwards compatibility?

> 
> We support the last major and the current previous major, so we should have tests for 1.3 -> 2.1 and 2.0 -> 2.1, can we make sure we test both?
> 
> stated differently, we should have tests that cover:
> 
> * last supported major version (1) and its most recent minor version (3) to current version
> * current major version (2) and its most recent minor version (0) to current version
>
> if we really wanted to be thorough I think we would add checks for every minor version on the current major version (e.g. if we were on 2.4, we would have BWC tests for 1.3, 2.0, 2.1, 2.2, and 2.3) (e.g.2 if we were on 3.1 we would have BWC tests for 2.3 and 3.0)

**Comment by peternied** [comment]
> We support the last major and the current previous major

I've made this statement and cannot find documentation to substantiate it.  Does someone have a link, or is this something we need to codify?

**Comment by saratvemulapalli** [comment]
Trying to understand the context. 
Is the question tailored to plugins backwards compatibility testing?   

Branching strategy is documented in https://github.com/opensearch-project/.github/blob/main/RELEASING.md#opensearch-branching. Are you looking for something similar:
- Documented 
- Automated testing [1]

[1] https://github.com/opensearch-project/opensearch-build/issues/90

**Comment by peternied** [comment]
[Recapping from offline conversation with @saratvemulapalli]

* In future release of OpenSearch, the BWC tests versions targets will be supplied from as part of the distribution build, so all plugins will need to be updated to pull those versions from gradle properties.  Plugins running BWC tests on there own is an option for early failure detection.

* To setup these BWC tests for a plugin on its own, as version numbers are incremented, previous versions should be folded into the BWC test matrix, so if we had `1.3.0` for the `2.0.0` release, when we go to version `2.1.0` the matrix should now include `1.3.0` & `2.0.0`.  We should not remove/replace items from the BWC test matrix until they are no longer supported.

**Comment by peternied** [comment]
@dblock I'll create a pull request in that repo to document then after it is merged this issue should be closed out.
