### ISSUE TITLE
Validation of shard copies to be a multiple of unique values of awareness attribute 

### ISSUE THREAD

**Issue by gbbafna** [opensearch-project/OpenSearch#3461]
**Is your feature request related to a problem? Please describe.**

In cloud HA deployments , customer usually deploy over multiple zones. zone is usually the awareness.attributes in there . However, there is no enforcement of all copies spread evenly across all zones . This can cause uneven distribution of shards and also create shard hotspots. Failure in a single zone might also cause data loss and unavailability for that shard if the copies aren't evenly spread out.

This is the first solution listed in https://github.com/opensearch-project/OpenSearch/issues/3367 

**Describe the solution you'd like**

A boolean cluster level setting `cluster.routing.allocation.awareness.balance` which is false by default . When true, we would validate that total copies is always a maximum of awareness attribute value count . If not, we will throw a validation exception. For ex, if there are 2 Awareness Attributes, zones and rack ids, each having 2 possible values , total copies needs to be multiple of 2.

**Describe alternatives you've considered**

**Additional context**

**Comment by kartg** [comment]
Closing this as per the updates in https://github.com/opensearch-project/OpenSearch/issues/3367

@gbbafna please reopen if i've closed this incorrectly
