### ISSUE TITLE
[Feature/Extensions] getNamedWriteables - Add support for extensions

### ISSUE THREAD

**Issue by joshpalis** [opensearch-project/OpenSearch#3495]
Add extension framework support for getNamedWriteables extension point.

**Comment by joshpalis** [comment]
Design for default extension point support for getNamedWriteables.

Extension Point Purpose :

- When plugins override getNamedWriteables() with their own implementation, they are able to register custom parsers for Named Objects that implement the Writeable class within the NamedWriteableRegistry. Similar to the NamedXContent registry, the Named Writeable Registry entries consist of a category class, a unique name associated with the writeable object, and a parser. The category class and name is used to validate that the parser has been registered during OpenSearch bootstrap. 
- The main difference between the two default extension points is that the NamedWriteableRegistry is used to deserialize named objects between nodes, allowing nodes to transfer and understand objects passed across the wire using the OpenSearch inter-node communication protocol outlined by StreamInput/StreamOutput, while the NamedXContentRegistry is used to parse xcontent (ie json, yaml, cbor, smile formatted data) that is sent across the wire.

Previous workflow:

- Traditionally installed plugins override the getNamedWriteableRegistry() extension point and return a collection of NamedWriteableRegistry.Entry's
- During OpenSearch bootstrap within Node.java, Named Writeable Registries from various modules (ie: search, index, network, cluster) and all installed plugins are consolidated into a central NamedWriteableRegistry.
- This registry is then used to create components for all installed plugins, indices service, network module, discovery module, and a module builder used for dependency injection.

Extensibility workflow:

- In order to enable independent plugins to register xcontent registry entries across the wire using the inter-node communication protocol, it is necessary for these xcontent entry category classes to be first registered within the NamedWriteableRegistry
- This results in a conundrum since both extension point architectures are quite similar and thus the category class of the NamedWriteableRegistry is not able to be deserialized by opensearch after it is sent across the wire
- In order to circumvent this issue, modifications to the NamedWriteableRegistry entry category class field must be made such that only the string form of the class name is sent across the wire and registered in the central named writeable registry within Node.java
- This is possible since the named writeable registry only uses the class name for registration verification, while the named xcontent registry verification also uses the category class of the entry to cast the object sent across the wire, requiring that particular entry category class to already be class loaded within the jvm that opensearch is running on
-  after all installed plugin writeable registries are collected, extensions orchestrator will send out requests to all extensions that have been previously discovered for any entries they want to register
- Upon receiving the request, the independent plugins would return a response consisting of all the entries that it wants to register, however, instead of providing the custom parser within the entry, the reader will be replaced with a callback method to send a request from opensearch to the extension for object deserialization
- The work done to handle object deserialization will be done by the extension in order to maintain the separation of concerns between it and OpenSearch. In the case that the extension goes down, the entries corresponding to the extension must then be deregistered from the NamedWriteableRegistry
- Once all NamedWriteable registry entries from the extensions have been collected, the registry will then be passed onto various services that are created during bootstrap
- When xcontent registry entries are then collected, the extension entries sent across the wire can then be identified by the named writeable registry and then parsed into the correct object

**Comment by minalsha** [comment]
Love the details @joshpalis . TY

**Comment by saratvemulapalli** [comment]
Thanks @joshpalis for detailed notes.

To give out a summary, we are trying to run plugins as a standalone process. 
`getNamedWriteables` adds support to understand messages transported by plugins. 
Unfortunately when we'd like to run them as extensions, we do not have the class definitions to deserialize the messages (Because OpenSearch wouldn't not understand it or has the capability to decrypt it).

@nknize @rmuir  What are your thoughts on solving this problem of running extensions independently yet still enable OpenSearch to decrypt it?

**Comment by minalsha** [comment]
#4067
