### ISSUE TITLE
[Bug]: Failed gradle check job reported as success on github 

### ISSUE THREAD

**Issue by dreamer-89** [opensearch-project/OpenSearch#3506]
### Describe the bug

Gradle check failure https://fork-jenkins.searchservices.aws.dev/job/OpenSearch_CI/job/PR_Checks/job/Gradle_Check/5766/artifact/gradle_check_5766.log has legit failures but job marked as succeeded on jenkins. It can be a legit gradle bug or scripts we have written but need some deep dive.

Identified in https://github.com/opensearch-project/OpenSearch/pull/3505

### To reproduce

Checkout branch (dreamer-89:bulk_type_fix_2x) or changes and raise PR

### Expected behavior

Job should be marked failed if there are test failures.

### Host / Environment

Jenkins host

### Relevant log output

```shell
Tests with failures:
 - org.opensearch.backwards.MixedClusterClientYamlTestSuiteIT.test {p0=bulk/11_with_deprecated_types/empty action}
 - org.opensearch.backwards.MixedClusterClientYamlTestSuiteIT.test {p0=bulk/11_with_deprecated_types/List of strings}
 - org.opensearch.backwards.MixedClusterClientYamlTestSuiteIT.test {p0=bulk/11_with_deprecated_types/Array of objects}

1185 tests completed, 6 failed, 33 skipped
There were failing tests. See the report at: file:///var/CITOOL/workflow/OpenSearch_CI/PR_Checks/Gradle_Check/search/qa/mixed-cluster/build/reports/tests/v2.0.0%23mixedClusterTest/index.html

> Task :qa:mixed-cluster:v2.0.0#bwcTest
> Task :qa:mixed-cluster:bwcTestSnapshots
> Task :qa:mixed-cluster:check
build complete, generating: /var/CITOOL/workflow/OpenSearch_CI/PR_Checks/Gradle_Check/search/build/5766.tar.bz2

BUILD SUCCESSFUL in 39m
2594 actionable tasks: 2594 executed
```
```

**Comment by tlfeng** [comment]
Similar to issue https://github.com/opensearch-project/OpenSearch/issues/2878. I also found that gradle check passes even if YAML REST API BWC test failed. 😄

**Comment by dreamer-89** [comment]
Thanks @tlfeng for sharing this. Closing this issue in favour of #2878
