### ISSUE TITLE
[Remote Store] Delete data from remote store (translog and segments) on index delete

### ISSUE THREAD

**Issue by sachinpkale** [opensearch-project/OpenSearch#3511]
**Describe the solution you'd like**
When an index is deleted, corresponding translog and segment data should be deleted from remote translog and remote segment store.

**Comment by andrross** [comment]
@gbbafna @sachinpkale Are we sure this is the right experience? With remote store uses get the "durable by default" behavior and I don't know if it is intuitive that deleting the index also deletes the data from remote. If I understand correctly, if we implement the behavior in #7682, then the experience is as follows (assuming I have a remote-backed index named `my-index` with data in it):

Use case 1: Permanently delete all data in `my-index`:

`DELETE my-index`

**Comment by sachinpkale** [comment]
@andrross As part of https://github.com/opensearch-project/OpenSearch/issues/6483, we are introducing interoperability with snapshot. Snapshot interoperability will allow us to create a snapshot referencing data in the remote store. It is also introducing a concept of ref count. With this, a segment in remote store can only be deleted if it is not referenced by any snapshot. This will hold true for index deletion as well.

**Comment by andrross** [comment]
@samuel-oci FYI
