### ISSUE TITLE
"Failed to update the monitor" after updating existing monitor config (and selecting notification channel)

### ISSUE THREAD

**Issue by olwe0002** [opensearch-project/OpenSearch#3526]
After updating to Opensearch 2.0.0 (via Helm Chart 2.0.1), there is a new error in place:

On updating an existing monitor config, e.g. selecting a channel on a notification entry and click on "Update", the following message occurs:

`[illegal_state_exception] Can't get text on a START_OBJECT at 1:1552`
depending on the monitor config sometimes a different line number:
`[illegal_state_exception] Can't get text on a START_OBJECT at 1:1536`

steps to reproduce:

1. open existing monitor config and click "Edit"
2. scroll down to the triggers and extend the actions. Note that the "Channel" field is filled out with a channel name
3. do not change anything and click on "Update"
4. the error message occurs
5. reload the page
6. scroll down to the triggers and extend the actions. Note that the "Channel" field is NOT filled out any more (now: "Select Channel to notify")
7. click on "Update"
8. message `Fix all highlighted error(s) before continuing.` comes up
9. select a channel (hard to do, several clicks are needed, leaving the field seems to trigger the stuff!)
10. click on "Update" again. Sometimes it works, depending on how you selected the channel maybe. Can't tell in which cases.

So it seems like its related to the change from Alerting Destinations to Notifications Channels. Please have a look

**Comment by xuezhou25** [comment]
Hi @olwe0002, looks like you are working on updating the monitor and this is more of alerting issue. Will transfer this issue to alerting repo. 
@opensearch-project/transfer-request

**Comment by olwe0002** [comment]
thanks. Seems like this transfer did not work. So I created the issue there too - https://github.com/opensearch-project/alerting/issues/470 and will close it here.
