### ISSUE TITLE
Support for unsigned_long as same as in elastic search

### ISSUE THREAD

**Issue by chandu54** [opensearch-project/OpenSearch#3538]
**Is your feature request related to a problem? Please describe.**
Yes. We had a requirement where we need to ignore the sign (+/-) while searching the data. 

**Describe the solution you'd like**
Provide unsigned_long data type as same as in elastic search. 
Refer https://www.elastic.co/guide/en/elasticsearch/reference/current/number.html
**Opensearch Doc**: https://opensearch.org/docs/latest/search-plugins/sql/datatypes/

**Describe alternatives you've considered**
We are trying to manipulate the query to ignore the sign while preparing the terms/term query.

**Comment by dblock** [comment]
AFAIK nobody is working on this @chandu54, please feel free to contribute a PR!
