### ISSUE TITLE
Update merge on refresh and merge on commit defaults in Opensearch (Lucene 9.3)

### ISSUE THREAD

**Issue by reta** [opensearch-project/OpenSearch#3553]
**Is your feature request related to a problem? Please describe.**
The Apache Lucene 9.3 made merge-on-refresh enabled by default [1]. 

[1] https://github.com/apache/lucene/pull/921/files

**Describe the solution you'd like**
The Opensearch merge policy has to be updated in order to accommodate this change.

**Describe alternatives you've considered**
N/A

**Additional context**
Related to https://github.com/opensearch-project/OpenSearch/pull/3537

**Comment by reta** [comment]
@nknize fyi

**Comment by elfisher** [comment]
@reta is there anything we should consider documenting regarding this change? Does it have performance implications for users or anything else we should cover in opensearch.org/docs?

**Comment by reta** [comment]
@elfisher yes, I will submit the documentation update for 2.1.0 / 2.2.0. Trying to find out the best place for it and not sure 9.3 will be released before 2.1.0 is out. In general, the change should have only positive performance implications, but we are providing the option to disable it.
