### ISSUE TITLE
[Rename] elasticsearch references in docs which are not under docs/ directory

### ISSUE THREAD

**Issue by setiah** [opensearch-project/OpenSearch#360]
For example, 

It appears that /rest-api-spec/src/main/resources/rest-api-spec/test/README.asciidoc  and /rest-api-spec/README.markdown contains ‘elasticsearch’ -- Kyle Davis

**Comment by abbashus** [comment]
The content renaming was fixed by #432.
The url renaming and leftover renaming is fixed by #530.

**Comment by dblock** [comment]
This has all been taken care of. If new instances of elasticsearch used where it shouldn't are found, let's open new issues.
