### ISSUE TITLE
[META] Provide extension points for Remote Translog 

### ISSUE THREAD

**Issue by Bukhtawar** [opensearch-project/OpenSearch#3600]
**Is your feature request related to a problem? Please describe.**
We have Translog Reader and TranslogWriters, we need to provide extension support for remote translog 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by kotwanikunal** [comment]
@Bukhtawar Can you please add more details to the issue?

**Comment by linuxpi** [comment]
[Storage Triage - attendees [1](https://github.com/ashking94/) [2](https://github.com/shourya035/) [3](https://github.com/gbbafna/) [4](https://github.com/andrross/) [5](https://github.com/ltaragi/) [6](https://github.com/astute-decipher/) [7](https://github.com/skumawat2025/) [8](https://github.com/linuxpi/)]

Looks like we already have it now!
