### ISSUE TITLE
[BUG] 403 forbidden from REST client with Apache interceptor that generates Sigv4 with compression and chunked transfer encoding enabled

### ISSUE THREAD

**Issue by jiten1551** [opensearch-project/OpenSearch#3640]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:
1. create openSearch domain in (AWS) which support IAM based  AuthN/AuthZ
2. send signed request to opensearch cluster using java rest client (https://docs.aws.amazon.com/opensearch-service/latest/developerguide/request-signing.html)
3. create rest-client in java with compression enabled (https://opensearch.org/docs/latest/clients/java-rest-high-level/)
4. ```public static RestHighLevelClient searchClient(String serviceName, String region) {
        AWS4Signer signer = new AWS4Signer();
        signer.setServiceName(serviceName);
        signer.setRegionName(region);
        HttpRequestInterceptor interceptor = new AWSRequestSigningApacheInterceptor(serviceName, signer, new DefaultAWSCredentialsProviderChain());
        RestHighLevelClient restHighLevelClient = new RestHighLevelClient(RestClient.builder(HttpHost.create(host))
                .setHttpClientConfigCallback(hacb -> hacb.addInterceptorLast(interceptor))
                .setCompressionEnabled(true)); <------ set compression enabled

        return restHighLevelClient;
    }```

5. then use this client to access open-search cluster it will fail with below error

**Expected behavior**
java Rest-client should be able to work when compression  enabled with IAM based AuthN/AuthZ (SIGV4)

**ERROR**

```
If applicable, add screenshots to help explain your problem.
OpenSearchStatusException[Unable to parse response body]; nested: ResponseException[method [PUT], host [https://xxxx.amazonaws.com], URI [/custom-index?master_timeout=30s&timeout=30s], status line [HTTP/1.1 403 Forbidden]
{"message":"The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details"}];
	at org.opensearch.client.RestHighLevelClient.parseResponseException(RestHighLevelClient.java:1653)
	at org.opensearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1407)
	at org.opensearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1379)
	at org.opensearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:1346)
	at org.opensearch.client.IndicesClient.create(IndicesClient.java:150)
	at RESTClientTest.main(RESTClientTest.java:48)
	Suppressed: ParsingException[Failed to parse object: expecting field with name [error] but found [message]]
		at org.opensearch.common.xcontent.XContentParserUtils.ensureFieldName(XContentParserUtils.java:62)
		at org.opensearch.OpenSearchException.failureFromXContent(OpenSearchException.java:621)
		at org.opensearch.rest.BytesRestResponse.errorFromXContent(BytesRestResponse.java:192)
		at org.opensearch.client.RestHighLevelClient.parseEntity(RestHighLevelClient.java:1673)
		at org.opensearch.client.RestHighLevelClient.parseResponseException(RestHighLevelClient.java:1650)
		... 5 more
```

**Host/Environment (please complete the following information):**
 - OS: IOS
 - Version NA

**Additional context**
similar issue raised in 2020
https://github.com/amazon-archives/aws-request-signing-apache-interceptor/issues/10

**Comment by saratvemulapalli** [comment]
@jiten1551 I am trying to understand the ask. 
Are you trying to use the Rest High Level Client to communicate with a domain in Amazon OpenSearch service? 
Our client is agnostic of a service provider.

**Comment by jiten1551** [comment]
Yes I'm trying to use Rest High Level client.
I did some debugging found out that compression logic in RestClient.java file returns uncompressed HTTP request. and only returns compressed content when getContent() (ContentCompressingEntity) is called.

**Comment by dblock** [comment]
See https://github.com/opensearch-project/OpenSearch/pull/3665#issuecomment-1166056937 for a suggested fix.

**Comment by dblock** [comment]
The original issue is still present, we don't know how to sign Sigv4 chunked requests. The workaround is now to `setChunkedEnabled(false)`.
