### ISSUE TITLE
[BUG] Is it possible to use dynamic_templates

### ISSUE THREAD

**Issue by mirisu2** [opensearch-project/OpenSearch#3648]
**Describe the bug**
If I set the type statically (like second test-2) it works as expected. But I would like to be able to set type dynamically, because it is not known what fields will be in the future.
The first example test-1 doesn’t work as expected.
Maybe I didn't configure something else? Or maybe I did something wrong? Is it even possible to use dynamic_templates?

**To Reproduce**
```
PUT _index_template/test-1
{
  "index_patterns" : [
    "test-*"
  ],
  "template" : {
    "mappings" : {
      "dynamic_templates" : [
        {
          "log_processed.data" : {
            "match_pattern" : "regex",
            "match" : "^log_processed.data.*",
            "match_mapping_type":"*",
            "mapping" : {
              "type" : "text"
            }
          }
        }
      ]
    }
  }
}
PUT _index_template/test-2
{
  "index_patterns" : [
    "test-*"
  ],
  "template" : {
    "mappings" : {
      "properties": {
        "log_processed.data.a": {
          "type" : "text"
        }
      }
    }
  }
}
```

**Expected behavior**
to be able to use mapping feature like dynamic_templates

**Plugins**
opensearch-alerting
opensearch-anomaly-detection
opensearch-asynchronous-search
opensearch-cross-cluster-replication
opensearch-index-management
opensearch-job-scheduler
opensearch-knn
opensearch-ml
opensearch-observability
opensearch-performance-analyzer
opensearch-reports-scheduler
opensearch-security
opensearch-sql

**Host/Environment (please complete the following information):**
 - Opensearch: 1.3.3
 - OS: CentOS 7.9

**Comment by ildarmf** [comment]
+1

**Comment by dblock** [comment]
I believe this is a feature request. It was added in ES 7.13, https://www.elastic.co/guide/en/elasticsearch/reference/7.13/docs-bulk.html#bulk-api-request-body.

**Comment by erasmodominguezdc** [comment]
+1

**Comment by campidelli-wcq** [comment]
+1

**Comment by dblock** [comment]
Looks like there's a lot of interest for this feature! Anyone wants to pick it up and contribute?

**Comment by trautonen** [comment]
Is there any updates regarding this? We have a case with a lot of complex dynamic fields that automatic mappings would not work so this feature would be really helpful.

**Comment by gaobinlong** [comment]
By my test, dynamic_templates works well in OpenSearch 2.11, and I also find the related doc in ES 7.10: [dynamic templates](https://www.elastic.co/guide/en/elasticsearch/reference/7.10/dynamic-templates.html#path-match-unmatch). 
In the above case, `path_match` should be used instead of regex match pattern, like this:
```
PUT _index_template/test-1
{
  "index_patterns" : [
    "mytest-*"
  ],
  "template" : {
    "mappings" : {
      "dynamic_templates" : [
        {
          "log_processed.data" : {
            "path_match" : "log_processed.data.*",
            "match_mapping_type":"*",
            "mapping" : {
              "type" : "text"
            }
          }
        }
      ]
    }
  }
}
```
, after creating a template, we index a doc:
```
POST mytest-1/_doc/1?refresh
{
  "log_processed.data.a":"x",
  "ab":1
}
```
, then see the mapping of the index is:
```
{
  "mytest-1": {
    "mappings": {
      "dynamic_templates": [
        {
          "log_processed.data": {
            "path_match": "log_processed.data.*",
            "mapping": {
              "type": "text"
            }
          }
        }
      ],
      "properties": {
        "ab": {
          "type": "long"
        },
        "log_processed": {
          "properties": {
            "data": {
              "properties": {
                "a": {
                  "type": "text"
                }
              }
            }
          }
        }
      }
    }
  }
}
```

**Comment by stowns** [comment]
Can confirm @gaobinlong 's comment. `dynamic_templates` do work and are support in OpenSearch Serverless. The template must exist before the index is created in order for `dynamic_templates` to be applied.

**Comment by dblock** [comment]
I am closing this as already exists. Please let me know if I misunderstood the issue.
