### ISSUE TITLE
Support for HTTP/2 (server-side)

### ISSUE THREAD

**Issue by adnapibar** [opensearch-project/OpenSearch#3651]
**Is your feature request related to a problem? Please describe.**

OpenSearch currently only supports HTTP/1 which is a single request/response protocol. HTTP/2 allows multiple requests to be in progress at the same time on a single connection with the mechanism of streams. There are workarounds with HTTP/1 such as to maintain multiple open connections or to send fewer large requests (e.g. bulk API). Both has their own problems.  

**Describe the solution you'd like**
HTTP/2 has been around for sometime and is supported in Netty. However, we need to do some work to make sure HTTP/2 works without any issue.

**Describe alternatives you've considered**
Keep using HTTP/1

**Comment by reta** [comment]
@adnapibar @dblock would you mind if I pick it up? Did some work on Netty + HTTP/2 integration before
