### ISSUE TITLE
[Question] Order of initialization in Node.java

### ISSUE THREAD

**Issue by anandpatel9998** [opensearch-project/OpenSearch#3657]
**Describe the Question**
In [Node.java](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/node/Node.java), on line [598](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/node/Node.java#L598) It is trying to get getDirectoryFactories from all the plugins and later those directory factories are being used to initialize [IndicesService on line 623](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/node/Node.java#L623-L641). But create component for each plugin is called after that [on line 677](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/node/Node.java#L677)

I wanted to understand the reasoning behind calling create components after getDirectoryFactories by Node class. Lets says I have a use case where I want to register new directory factory by writing a plugin and initializing the directory factory by overriding createComponents method and return it by overriding getDirectoryFactories() method in my Plugin. Currently it will not work. because plugin's getDirectoryFactories method is invoked before createComponents() method by Node class when Node is initialized.

I tried changing the order in node.java (I moved [create components](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/node/Node.java#L677) calls to all plugins before calling [getDirectoryFactories](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/node/Node.java#L597) method for all plugins) and everything worked as expected for me.

Is this an intentional behavior that [getDirectoryFactories](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/node/Node.java#L597)  is invoked before  [create components](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/node/Node.java#L677)?

**Comment by minalsha** [comment]
@saratvemulapalli  could you please share status of the progress for this issue? Thanks

**Comment by saratvemulapalli** [comment]
From what I see, `getDirectoryFactories` [1] is a dependency to create `IndicesService`[2]. 
For `CreateComponents`, it has none of the parameters which depend on `IndicesService`. 
So it should be safe to change the order of initialization. I dont think there is any other specific reason, it just built that way.

let me know if you need anything else.


[1] https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/node/Node.java#L650
[2] https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/node/Node.java#L698
