### ISSUE TITLE
Unable to use Systemd module with tar distribution

### ISSUE THREAD

**Issue by Ripolin** [opensearch-project/OpenSearch#3666]
Why use of Systemd module is limited to RPM and DEB installations ?

To me there is no relationship between Sytemd and package managers and it could be possible to use Systemd module for installations using tar distribution.

https://github.com/opensearch-project/OpenSearch/blob/7005b9eb42f66912507b8f973b79734c260bdfe9/modules/systemd/src/main/java/org/opensearch/systemd/SystemdPlugin.java#L75

**Comment by dblock** [comment]
@peterzhuamazon do you know anything about this?

**Comment by peterzhuamazon** [comment]
Hi @Ripolin @dblock .

Sure, there is no limit saying you can only use systemd with deb/rpm.
However, deb/rpm have pre/post scripts and setup folder structure/configs specifically, so the corresponding systemd service scripts can execute without issues.

You can certainly write a service script yourself for things like tar, but that relies on you to setup rules for that script.
It is easy to tweak tarball extract locations and configuration / data folder / log folder directories and that is not suitable for systemd as it is asking for pre-defined setups.

The code here is just saying DEB/RPM is having packagedistro type, I see no issues with this setup tho.

Please let me know your thoughts.

Thanks.

**Comment by Ripolin** [comment]
Hi @peterzhuamazon and thx for your response

I exactly do what you say ;p

Indeed I create my own Systemd service of type "notify", init env var ```OPENSEARCH_SD_NOTIFY``` with ```true``` value and add systemd module in my installation (by default this module is not present in TAR distribution).

The problem is it only works after edit ```bin/opensearch-env``` file to modify ```OPENSEARCH_DISTRIBUTION_TYPE``` entry with value ```rpm```

Refer to line : https://github.com/opensearch-project/OpenSearch/blob/7005b9eb42f66912507b8f973b79734c260bdfe9/modules/systemd/src/main/java/org/opensearch/systemd/SystemdPlugin.java#L80

and line :

https://github.com/opensearch-project/OpenSearch/blob/7005b9eb42f66912507b8f973b79734c260bdfe9/modules/systemd/src/main/java/org/opensearch/systemd/SystemdPlugin.java#L148

TAR  installation cannot notify Systemd to tell service is really up because ```isPackageDistribution``` and ```enabled```vars are initialized with  ```false``` value.

The only way to use Systemd with TAR distribution without hack  opensearch-env file is to use a "simple" service and not a "notify" one. But using a simple service make systemd module useless and can creates issues when  service starts because the system thinks service is fully up but it's not the case.

**Comment by peterzhuamazon** [comment]
@Ripolin if you are talking about that `notify` thing, yeah that is only supported in DEB/RPM.
When I 1st create opensearch/dashboards rpm from tar I see the same issue.
My solution is just create the bundle rpm from core rpm instead of core tar.

If you think the above setup is not ideal, would you mind raise a PR to fix it?
@dblock I have no concerns to allow `notify` available in tarball.
Any comments from you on this?

Thanks.

**Comment by Ripolin** [comment]
@peterzhuamazon OK I'll do a PR soon :thumbsup:

**Comment by dblock** [comment]
> If you think the above setup is not ideal, would you mind raise a PR to fix it? 😄 @dblock I have no concerns to allow `notify` available in tarball, but I dont know the historical reason why it is limited. Any comments from you on this?

Neither do I :(
