### ISSUE TITLE
[BUG] testCreateEmptyDirNoPermissions when running gradle check in docker container

### ISSUE THREAD

**Issue by peterzhuamazon** [opensearch-project/OpenSearch#3674]
Just grab a centos7 docker container like this one:
https://hub.docker.com/r/opensearchstaging/ci-runner/tags?page=1&ordering=last_updated&name=ci-runner-centos7-gradle-check-v1

Export these envvar:
JAVA11_HOME="/opt/java/openjdk-11
JAVA17_HOME="/opt/java/openjdk-17"
JAVA8_HOME="/opt/java/openjdk-8"
JAVA_HOME="/opt/java/openjdk-17"

Check out main or 2.0 branch, run `./gradlew check --no-daemon --no-scan`.

The error log is like this:
```
> Task :build-tools:test FAILED

org.opensearch.gradle.EmptyDirTaskTests > testCreateEmptyDirNoPermissions FAILED
    java.lang.AssertionError at EmptyDirTaskTests.java:81

org.opensearch.gradle.EmptyDirTaskTests > testCreateEmptyDirNoPermissions FAILED
    java.lang.AssertionError at EmptyDirTaskTests.java:81

org.opensearch.gradle.EmptyDirTaskTests > testCreateEmptyDirNoPermissions FAILED
    java.lang.AssertionError at EmptyDirTaskTests.java:81

```

Related to this:
https://github.com/opensearch-project/OpenSearch/blob/main/buildSrc/src/test/java/org/opensearch/gradle/EmptyDirTaskTests.java#L90-L92

Thanks.

**Comment by owaiskazi19** [comment]
Looks like we can restrict this test for docker. Just like did [here](testCreateEmptyDirNoPermissions) for Windows. @reta since you have worked on something similar for docker [here](https://github.com/opensearch-project/OpenSearch/issues/2592). WDYT?

**Comment by peterzhuamazon** [comment]
We unblock this temporarily by not using container, but ec2 instance directly to run gradle check.
