### ISSUE TITLE
[Segment Replication] Support enabling/disabling segment replication for an existing index.

### ISSUE THREAD

**Issue by mch2** [opensearch-project/OpenSearch#3685]
**Is your feature request related to a problem? Please describe.**
Segrep right now can be enabled only during index creation.  This means converting an existing index to use segrep requires a full reindex.

**Describe the solution you'd like**
Support converting an existing index to use segment replication without reindexing.

**Describe alternatives you've considered**
None

**Additional context**

**Comment by mch2** [comment]
Closing as this is now supported.

**Comment by ikosmopoulos-st** [comment]
Hello @mch2, is it actually supported? I don't see any documentation. The only process described is re-indexing
