### ISSUE TITLE
Add failure analytics for OpenSearch

### ISSUE THREAD

**Issue by dreamer-89** [opensearch-project/OpenSearch#3713]
**Is your feature request related to a problem? Please describe.**
Today, CI gradle check fails often due to existing flaky tests. Issues are created to track these failures ([Meta issue](https://github.com/opensearch-project/OpenSearch/issues/1715)).  There is no existing mechanism to answer below questions:
1. Identify top hitter for prioritization. 
2. Identify commit introduced a flaky test or increase freq of existing test failure.
3. Build failure trend to identify health of software.
4. Developers impacted due to flaky tests.
5. Test history. 

With growth of OpenSearch, it is not possible to continue to use manual approach to track flaky test issues. There should be a mechanism to identify top hitter (prioritise right flaky test), commit that introduced a new failure, service health in general, faster debugging etc. 

**Describe the solution you'd like**
Enable failure analytics using gradle enterprise, which provides out of the box failure analytics and solves use cases in description and much more.

**Describe alternatives you've considered**
1. Continue existing manual approach. This is not scalable.
2. Use OpenSearch to store gradle logs or gradle scan data by calling gradle APIs.

**Comment by andrross** [comment]
We now have test failure metrics as detailed here: https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#gradle-check-metrics-dashboard
