### ISSUE TITLE
[BUG] Failed to parse mapping [_doc]: No handler for type [flattened] declared on field

### ISSUE THREAD

**Issue by mirisu2** [opensearch-project/OpenSearch#3733]
Hi,
I would like to use type `flattened` to prevent mapping explosion like [this ](https://www.elastic.co/guide/en/elasticsearch/reference/current/flattened.html#flattened)example. I got an error while creating `_index_template`
```
{
  "error" : {
    "root_cause" : [
      {
        "type" : "illegal_argument_exception",
        "reason" : "composable template [fluentbit-dev] template after composition is invalid"
      }
    ],
    "type" : "illegal_argument_exception",
    "reason" : "composable template [fluentbit-dev] template after composition is invalid",
    "caused_by" : {
      "type" : "illegal_argument_exception",
      "reason" : "invalid composite mappings for [fluentbit-dev]",
      "caused_by" : {
        "type" : "mapper_parsing_exception",
        "reason" : "Failed to parse mapping [_doc]: No handler for type [flattened] declared on field [log_processed.data.Body]",
        "caused_by" : {
          "type" : "mapper_parsing_exception",
          "reason" : "No handler for type [flattened] declared on field [log_processed.data.Body]"
        }
      }
    }
  },
  "status" : 400
}
```
**To Reproduce**
```
PUT _index_template/fluentbit-dev
{
	"index_patterns" : [
	  "fluentbit-dev-*"
	],
	"template" : {
	  "settings" : {
		"index" : {
		  "number_of_shards" : "1",
		  "number_of_replicas" : "0",
		  "mapping": {
		    "total_fields": {
		      "limit": 100
		    }
		  }
		}
	  },
	  "mappings" : {
  		"_source" : {
  		  "enabled" : true
  		},
  		"properties" : {
  		  "log_processed.data.Body": {
  		    "type": "flattened"
  		  }
  		}
	  }
	},
	"composed_of" : [ ]
}
```

**Expected behavior**
I expect to create `_index_template` with `"type": "flattened"` configuration.

**Plugins**
opensearch-alerting
opensearch-anomaly-detection
opensearch-asynchronous-search
opensearch-cross-cluster-replication
opensearch-index-management
opensearch-job-scheduler
opensearch-knn
opensearch-ml
opensearch-observability
opensearch-performance-analyzer
opensearch-reports-scheduler
opensearch-security
opensearch-sql

**Screenshots**

**Host/Environment (please complete the following information):**
Opensearch: 1.3.3
OS: CentOS 7.9

Is it possible to use such configuraton while creating `_index_template` ? Or I can use only [this ](https://opensearch.org/docs/latest/opensearch/mappings/#dynamic-mapping-types)types?
Is it possible at all to prevent to index part of fields?

**Comment by reta** [comment]
@mirisu2 `flattened` is Elasticsearch X-Pack feature, not supported by OpenSearch, see please [1]

[1] https://github.com/opensearch-project/OpenSearch/issues/1018

**Comment by mirisu2** [comment]
Does anyone know, is it possible to prevent to index part of fields?
![image](https://user-images.githubusercontent.com/13135139/176446288-fad82935-8ade-4185-96d9-5953801eaefe.png)
If I got it right, by the documentation, if i define something in `dynamic_templates` block, it doesn't override fields I defined in the `properties` block. But this `_index_template` doesn't work properly :(  The fields in path `log_processed.data.*` doesn't index
