### ISSUE TITLE
Add CI on whether a change will break plugins 

### ISSUE THREAD

**Issue by dblock** [opensearch-project/OpenSearch#3740]
**Is your feature request related to a problem? Please describe.**
In https://github.com/opensearch-project/OpenSearch/pull/2692 we have backported a Gradle upgrade to 7.4.2 that broke plugins. It was late in the game for 2.1 release and shouldn't have. Had I known that it will break plugins we wouldn't have merged it.

**Describe the solution you'd like**
Add CI that attempts to run tests for one/some/all the plugins to execute as part of a PR. This way we will know that "this PR will break plugins like so".

**Comment by dblock** [comment]
@ylwu-amzn you'll probably have a lot of thoughts on this one!

**Comment by ylwu-amzn** [comment]
hi, @dblock thanks for creating this issue to improve our release process. I think plugin team should be aware of such breaking changes as early as possible. Adding CI to run some/all plugins can help catch any breaking part easily. Just have some concern that that means OpenSearch core CI will take much longer time and sometimes the breaking change is expected like change `master` to `cluster_management`. So plugin CI failure should not block changes in OpenSearch core.  

I think plugin team should make sure they keep same version in `<major_version>.x` branch with OpenSearch core. Then infra team can run some daily build workflow to check if plugins can build successfully with OpenSearch.

**Comment by downsrob** [comment]
While running the entirety of CI takes a long time, just doing build and unit tests likely would take less time than the OpenSearch core tests which would run in parallel. Plugin integration tests are also very flaky, so I think that introducing CI in core to build and maybe run unit tests would help catch these issues immediately. Also, the breaking change would be caught by the person introducing the change, and they will be the most informed on what the plugin owners will need to fix. It may also help to catch cases where a core change breaks plugins without knowing it.

I think that tlfeng brings up a valid point but once we have all plugins on the same branching and we are using automatic version bumps then waiting on plugins to bump versions shouldn't be a big problem.

**Comment by andrross** [comment]
@dblock Does the [check compatibility](https://github.com/opensearch-project/OpenSearch/blob/main/.github/workflows/check-compatibility.yml) workflow solve this problem?

**Comment by dblock** [comment]
@andrross Yes it did! Closing.
