### ISSUE TITLE
Support geo_point as an object using GeoJSON format

### ISSUE THREAD

**Issue by VijayanB** [opensearch-project/OpenSearch#3775]
**Is your feature request related to a problem? Please describe.**
geo_point doesn't accept GeoJSON format with type "Point"

**Describe the solution you'd like**
```
PUT test-index
{
  "mappings": {
    "properties": {
      "location": {
        "type": "geo_point"
      }
    }
  }
}

PUT test-index/_doc/1
{
  "text": "Support geo_point as GeoJSON Point object",
  "location": { 
    "type": "Point",
    "coordinates": [-88.0, 21.12]
  }
}
```

**Describe alternatives you've considered**
Manually convert GeoJSON into previously supported geo_point format

**Additional context**
Indexing GeoJSON Point as geo_shape is expensive and geo_shape doesn't support all aggregation as geo_point. Users can easily get benefitted by allowing GeoJSON format of type only "Point".

**Comment by Yury-Fridlyand** [comment]
Tested it on a68733af8af and it works. I think it could be closed now.
Or we need to add tests and then close.

**Comment by heemin32** [comment]
Test is added along with the code implementation. We can close this issue.
