### ISSUE TITLE
Dependabot does not scan for versions in versions.properties

### ISSUE THREAD

**Issue by saratvemulapalli** [opensearch-project/OpenSearch#3782]
**Is your feature request related to a problem? Please describe.**
Coming from: https://github.com/opensearch-project/OpenSearch/pull/3772#issuecomment-1175484840
Dependabot does a great job of automatically upgrading dependent libraries while checking CVE databases. 

For OpenSearch we use `versions.properties`[1] as a version catalog for all gradle projects within the repository. 
Dependabot workflow does not support scanning through this catalog file of versions.

**Describe the solution you'd like**
Dependabot support for dependencies listed in `versions.properties`.

[1] https://github.com/opensearch-project/OpenSearch/blob/main/buildSrc/version.properties

**Comment by reta** [comment]
Related discussions:
 - https://github.com/dependabot/dependabot-core/issues/1618
 - https://github.com/dependabot/dependabot-core/issues/1164
