### ISSUE TITLE
Adds option to do not abort the query when highlighting

### ISSUE THREAD

**Issue by hauck-jvsh** [opensearch-project/OpenSearch#3842]
I have an index with very large texts inside a field, and when a search with highlighting is made against it, the following error is returned:

> The length of [content] field of [106071] doc of [arquivos-dre-040-duplorisco] index has exceeded [1000000] - maximum allowed to be analyzed for highlighting. This maximum can be set by changing the [index.highlight.max_analyzed_offset] index level setting. For large texts, indexing with offsets or term vectors is recommended!

I think that it will be better if the query can execute and only the highlight is disabled. Another option is to add an max_analyzed_offset option to the highlighter and ignore all after this option similar to what is done in the current Elasticsearch version.

**Comment by hauck-jvsh** [comment]
Do you guys needs more info? I can link the Elasticsearch issue here or it is forbidden?

**Comment by dblock** [comment]
You should feel free to link issues. If you want to contribute a fix, and if ES has fixed this issue, please feel free to reimplement and confirm that you have not been looking at any non-APLv2-compatible-licensed code.
