### ISSUE TITLE
[Extensions]Have all development work behind a feature flag or configuration

### ISSUE THREAD

**Issue by minalsha** [opensearch-project/OpenSearch#3851]
**Is your feature request related to a problem? Please describe.**
As we are working on Extensions, lets ensure that we are tracking all the development for extensions behind a feature flag or configuration to ensure current plugin architecture is not impacted. 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by minalsha** [comment]
#1422

**Comment by owaiskazi19** [comment]
@ryanbogan are we good to close this issue?
