### ISSUE TITLE
[Searchable Snapshot] [Design Proposal] Block Based Storage

### ISSUE THREAD

**Issue by kotwanikunal** [opensearch-project/OpenSearch#3869]
This document outlines a proposal for implementing new block based storage and caching mechanisms without any external dependencies. This is a WIP. Please feel free to leave comments below with any thoughts or suggestions!

## Overview

Lucene utilizes [IndexInput](https://lucene.apache.org/core/9_1_0/core/org/apache/lucene/store/IndexInput.html) and [IndexOutput](https://lucene.apache.org/core/9_1_0/core/org/apache/lucene/store/IndexOutput.html) classes to enable reads and writes for index files. In case of OpenSearch, these index files are located locally on the disk of the corresponding node. 

[Searchable Remote Snapshots](https://github.com/opensearch-project/OpenSearch/issues/2919) (https://github.com/opensearch-project/OpenSearch/issues/2919) enable a read-only mechanism for the snapshots stored in a repository. The approach for remote storage will include a new block based mechanism around the mentioned [IndexInput](https://lucene.apache.org/core/9_1_0/core/org/apache/lucene/store/IndexInput.html) to enable minimized fetching and caching parts of the Lucene index files.

#### Correctness

The storage layer is at the bottom of OpenSearch, one byte error in storage would cause indices to fail to open or query failures.

#### Minimizing downloads

Downloading blocks of data when queried will help enable the remote storage philosophy and will prevent downloading entire files on the node, reducing the downloads and storage needed.

#### Transparency to upper layer

Changes in the storage layer should not affect normal operations from the upper layers. Block-based file system should be able to serve queries without any changes in the upper layers. Also, this design will initially work with snapshot files in the object store, but because it is an abstraction on the Lucene [IndexInput](https://lucene.apache.org/core/9_1_0/core/org/apache/lucene/store/IndexInput.html) it can be easily adapted to other formats such as Lucene files stored directly in the object store.

#### Cloud agnostic

Block-based storage will utilize the [Repository](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/repositories/Repository.java) interface for all interactions with the object store. This will allow users to use any existing or new repository implementation, decoupling the feature from any specific cloud technology or vendor.

### Approach

At a high level, the block based file system will enable fetching parts of the Lucene [IndexInput](https://lucene.apache.org/core/9_1_0/core/org/apache/lucene/store/IndexInput.html) files from the snapshot within the repository instead of downloading the entire file on disk — only download the bytes accessed by the query. The fetch when required mechanism will lead to a reduction in the total storage requirements for the node. 

The solution aims at implementing a wrapper around the [IndexInput](https://lucene.apache.org/core/9_1_0/core/org/apache/lucene/store/IndexInput.html) class to manage the block calculation, fetching and seeking mechanisms. This wrapper will work as a virtual file which will the utilized by Lucene to read index files and will internally keep track of the necessary blocks and the calculation required to fetch other blocks as per the query.

![image](https://user-images.githubusercontent.com/17763813/178855831-c83d880f-867a-4d38-80ca-a410cb4c33d6.png)

Lucene [IndexInput](https://lucene.apache.org/core/9_1_0/core/org/apache/lucene/store/IndexInput.html)'s read APIs are usually in the form below

`readXXX(int offset, int len)`

With offset and len, we can calculate which blocks need to be downloaded on demand.  To ensure performance, the size of the block is typically a power of two.  Thus the blocks for the above operation are from offset >>> blockSizeShift to  (offset + len) >>> blockSizeShift.

## Caching

The proposed block-based solution aims at minimizing the downloads for the local nodes by fetching chunks of data based on the query. Given the repeated nature of queries, it will be beneficial to store the blocks for a specified timeframe locally on disk to serve these queries without downloading the block again. 

Remote Searchable Snapshot will encompass a caching mechanism where the downloaded blocks will be stored temporarily on the local disk to serve future, repeated queries. The caching mechanism will utilize the [reference count mechanism](https://github.com/opensearch-project/OpenSearch/blob/main/libs/core/src/main/java/org/opensearch/common/util/concurrent/RefCounted.java) to keep track of blocks currently in use which will help the algorithm with decisions around invalidation and eviction. The amount of cache storage will be configurable by the user by updating the node settings within the cluster.

*This document was created with the help of the following contributors - Min Zhou, Rama Kotla*

**Comment by kotwanikunal** [comment]
Implemented as a part of #4892

**Comment by parasjain1** [comment]
The link to [reference count mechanism](https://github.com/opensearch-project/OpenSearch/blob/main/libs/core/src/main/java/org/opensearch/common/util/concurrent/RefCounted.java) in the issue description is broken. Can we update it?

**Comment by kotwanikunal** [comment]
> The link to [reference count mechanism](https://github.com/opensearch-project/OpenSearch/blob/main/libs/core/src/main/java/org/opensearch/common/util/concurrent/RefCounted.java) in the issue description is broken. Can we update it?

Should be fixed now.
