### ISSUE TITLE
[Remote Store] Validation of Peer Recovery esp. Translog replay part 

### ISSUE THREAD

**Issue by ashking94** [opensearch-project/OpenSearch#3946]
**Is your feature request related to a problem? Please describe.**
As part of remote store work, we will start storing the translogs remotely. Peer recovery has a stage where it downloads the translogs from the primary and replays it on the target shard. Given translogs are not stored locally, we would need to make use of abstractions created in #3945. 

**Describe the solution you'd like**
This story is to make sure that PEER recovery works as expected when the remote store has been brought to working state.

**Describe alternatives you've considered**

**Additional context**

**Comment by Bukhtawar** [comment]
Peer recovery uses PRRL(peer recovery retention leases) on the LuceneChangesSnapshot so the translog files aren't involved. Do you still want to pursue this?

**Comment by ashking94** [comment]
Ah, Ok. Then we could have a common issue for keeping checklist of what all things must be validated as part of this effort. We can create a generic issue if it does not exist already.
