### ISSUE TITLE
[Zone Decommission] Removal of nodes in decommissioned zone

### ISSUE THREAD

**Issue by gbbafna** [opensearch-project/OpenSearch#3956]
**Design Proposal**

https://github.com/opensearch-project/OpenSearch/issues/3402

**Feature Proposal**

https://github.com/opensearch-project/OpenSearch/issues/3917

**Describe the solution you'd like**

1. Remove all the nodes in  decommissioned zone. 
2. Make sure that they don't join back again . We can add one more Join Validator in [here](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/cluster/coordination/JoinTaskExecutor.java#L459) to reject joins coming from nodes in decommissioned zone and Kill-Switch for Decommission is Off.

**Comment by imRishN** [comment]
Implemented as part of https://github.com/opensearch-project/OpenSearch/pull/4084 . Can close the issue now
