### ISSUE TITLE
[Segment Replication] Update shard promotion algorithm to consider replica checkpoints.

### ISSUE THREAD

**Issue by mch2** [opensearch-project/OpenSearch#3988]
With segment replication we would like to avoid situations replicas contain a segment that is different from the primary's version.  After a read-only replica is promoted as the new primary, we will need to index operations that exist in its xlog that do not exist in the index and make them searchable.  The presence of these ops in the replica's xlog means the previous primary had indexed the op, and not finished pushing out the latest segments to any/all segments before failure.

As suggested in #2212, to avoid this situation we would like to implement a best-effort approach to select the furthest ahead replica as the new primary and avoid reindexing. 

https://github.com/opensearch-project/OpenSearch/issues/2212#issuecomment-1176493330 suggests that we can accomplish this by extending [PrimaryShardAllocator's](https://github.com/opensearch-project/OpenSearch/blob/4d3da00c1235fbceb65239336a027936ec781dc2/server/src/main/java/org/opensearch/gateway/PrimaryShardAllocator.java#L93) async fetch, that fetches which shards are in sync, to include checkpoint data from each shard when selecting a new primary.

**Comment by dreamer-89** [comment]
Set of crude steps for this task
- [ ] Write a unit test with 1p and 2 replica on different checkpoints. Fail primary and check replica is promoted irrespective of which of checkpoint state.
- [ ] Update AysncShard.fetchData to include the checkpoint info
- [ ] Ensure unit tests above passes
- [ ] Milestone 1. Primary promotion with segrep happy path works
- [ ] Update PrimaryShardAllocatorTests to add more unit tests around recovery/failover
- [ ] Wait for https://github.com/opensearch-project/OpenSearch/issues/3989 or add stub to prevent failure during primary promotions
- [ ] Write a basic integration test mimicking unit test above. 
- [ ] Add more integration tests with different failover scenarios/events
- [ ] Fix bugs if any

**Comment by dreamer-89** [comment]
There are couple of use cases related to primary allocation
1. [RoutingNodes.failShard](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/cluster/routing/RoutingNodes.java#L594). This workflow comes into picture when a primary fails on node. This chooses the replica which has highest node version
   - CancelAllocationCommand. REROUTE_CANCELLED. Cancelling existing allocation/recovery
   - gateway.ReplicaShardAllocator.  REALLOCATED_REPLICA - Cancel existing allocation when a better replica is identified i.e. one resulting in No-Op recovery.
   - ShardStateAction. Shard failure during replication
2. Cluster reroute actions. Cluster reroute API allows user to `move` shards (including primary) from node A to B. Not sure the impact of this action. 
3. Shard balancing. This applies during new index creation.

**Comment by dreamer-89** [comment]
It appears AllocationService orchestrates the shard allocation. It does allocation handling by using RoutingNodes (responsbile for maintaining shards routing state) and shard allocators (which perform actual shard allocation). Checking more using an integration test.

**Comment by dreamer-89** [comment]
On shard failure, master first tries to promote active replica (identified from cluster state in routing Nodes) which has highest engine version. In case, there is no available replica, master waits for cluster updates to trigger primary assignment via PrimaryShardAllocator.

With this info, separate handling needs to be done for RoutingNodes.failShard workflow.

**Comment by dreamer-89** [comment]
Evaluated option of ignoring the [primary promotion](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/cluster/routing/RoutingNodes.java#L690) in `RoutingNodes.failShard` during shard failure. The NodeRemovalClusterStateTaskExecutor (on node left) triggers the shard reroute (and unassigned primary allcoation) via PrimaryShardAllocator. 

Ignoring logic to primary promotion in RoutingNodes.failShard lead to multiple assertion failures at different levels. Removing this logic will need multiple changes in core allocation mechanism and will be a huge effort.

**Comment by dreamer-89** [comment]
PR to handle PrimaryShardAllocator primary promotion logic: https://github.com/opensearch-project/OpenSearch/pull/4041

**Comment by dreamer-89** [comment]
Closing this in favour of https://github.com/opensearch-project/OpenSearch/issues/4131 which tackles the second part of handling shard failure in RoutingNodes.
