### ISSUE TITLE
[Searchable Snapshot] Implement the Directory classes for block-based storage

### ISSUE THREAD

**Issue by kotwanikunal** [opensearch-project/OpenSearch#3991]
**Is your feature request related to a problem? Please describe.**
- The snapshot mechanisms in OpenSearch restore the entire index including the segment files for restoring an index
- Searchable snapshot adds support for searching an index without downloading the entire files to disk
- To enable the custom block based mechanism [1], need custom directory implementation

**Describe the solution you'd like**
- The new Directory implementation will be composed of the necessary interfaces and the custom IndexInput implementation as in #3961 

**Describe alternatives you've considered**
N/A

**Additional context**
[1] #3869

**Comment by aabukhalil** [comment]
I will be working on this
