### ISSUE TITLE
[BUG] The index setting "ignore_malformed" is not working properly

### ISSUE THREAD

**Issue by hauck-jvsh** [opensearch-project/OpenSearch#4002]
**Describe the bug**
The "ignore_malformed" option should allow inconsistent data to be indexed, losing only the malformed fields, but it is ignoring the entire item. 

**To Reproduce**
1. Create an empty index with the setting "ignore_malformed": "true".
2. insert the following data {
    "name":"test 1",
    "other_field":"string content"
}
3. insert the following data {
    "name":"test 2",
    "other_field":{"comment":"object content","size":2}
}

**Expected behavior**
In this situation the second item should be indexed only the field "other_field" should be missed, but the hole item is lost.

**Host/Environment (please complete the following information):**
 - OS: centos 8
 - Version 2.1

**Additional context**
I'm using this to index a lot of unstructured data, and sometimes a few fields are invalid, but it shouldn't lose the valid fields.

**Comment by hauck-jvsh** [comment]
Should I try to make a fix?

**Comment by dblock** [comment]
@hauck-jvsh Please!

**Comment by hauck-jvsh** [comment]
Sorry for the delay, but I finally get some time to work on this.

**Comment by hauck-jvsh** [comment]
Should I close this?

**Comment by dblock** [comment]
Yep, assuming https://github.com/opensearch-project/OpenSearch/pull/4494 closes this.
