### ISSUE TITLE
[BUG] /usr/share/opensearch/bin/systemd-entrypoint: 6: set: Illegal option -o pipefail

### ISSUE THREAD

**Issue by shdubsh** [opensearch-project/OpenSearch#4005]
**Describe the bug**
OpenSearch unable to start after fresh install:
```
Jul 25 20:34:15 localhost systemd-entrypoint[25956]: /usr/share/opensearch/bin/systemd-entrypoint: 6: set: Illegal option -o pipefail
Jul 25 20:34:15 localhost systemd[1]: opensearch.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
```

**To Reproduce**
1. Build deb package
2. Install artifact on debian buster host
3. Run `systemctl start opensearch.service`
4. Systemd reports `Job for opensearch.service failed because the control process exited with error code.`
5. Check logs `sudo journalctl -xe`

**Expected behavior**
OpenSearch should start

**Plugins**
None

**Host/Environment (please complete the following information):**
 - OS: Debian Buster
 - Version: OpenSearch 2.1.0 (min)

**Additional context**
It seems `set -e -o pipefail` was added as part of #3278 but accidentally added where the option was not supported.  Easiest workaround would be to set the shebang line to `#!/usr/bin/env bash`

**Comment by andrross** [comment]
Thanks for the contribution @shdubsh
