### ISSUE TITLE
[BUG] Empty geometry when building MultiPolygon using RestHighLevelClient.

### ISSUE THREAD

**Issue by Wild-Soul** [opensearch-project/OpenSearch#4010]
**Describe the bug**
When trying to create the geometry, MultiPolygon, by providing coordinates, it's not working.

Scenerio:
I had a bunch of coordinates that I wanted to provide to the MultiPolygonBuilder in order to get a ShapeBuilder.

**To Reproduce**
1. Create an instance of org.locationtech.jts.geom.Coordinate[].
2. Create a multipolygon builder using the above coordinates.
       `ShapeBuilder sb = new MultiPolygonBuilder().coordinates(coordinates);`
3. Create a geometry out of shapebuilder
`sb.buildGeometry()`
4. Notice that it'll say **MultiPolygon EMPTY.**

**Expected behavior**
Should be able to build the geometry.

**Screenshots**
<img width="520" alt="Screenshot 2022-07-26 at 4 08 39 PM" src="https://user-images.githubusercontent.com/30602486/180987337-166b693b-3c0d-4ad1-a9b0-fe69b4ec227a.png">
<img width="878" alt="Screenshot 2022-07-26 at 4 09 39 PM" src="https://user-images.githubusercontent.com/30602486/180987352-6a4327d0-fb92-4fec-a3d5-3eba91ff48dc.png">
<img width="590" alt="Screenshot 2022-07-26 at 4 09 51 PM" src="https://user-images.githubusercontent.com/30602486/180987361-e81b1b4b-d54a-4cd5-a26f-af6924d187f6.png">

**Host/Environment (please complete the following information):**
 - OS: [e.g. MacOS]

**Additional context**
Here's the geometry that I used:
`"geometry": {
        "type": "Multipolygon",
        "coordinates": [[
          [
            [
              91.4501953125,
              65.33017791526855
            ],
            [
              89.384765625,
              64.54844014422517
            ],
            [
              89.1650390625,
              62.2679226294176
            ],
            [
              96.5478515625,
              63.918058296491104
            ],
            [
              94.6142578125,
              65.45826097864811
            ],
            [
              91.4501953125,
              65.33017791526855
            ]
          ]
        ]]
      }`
The same thing when I tried with PointBuilder, it worked.
`return new PointBuilder().coordinate(coordinates[0]);`

Since this is a method in ShapeBuilder interface all the Class ( that extends the interface) should work in a similar manner.

P.S: It could be that what I'm trying is wrong, in that case can someone point me in the right direction i.e. to build Different Shapes using coordinates.

**Comment by dbwiddis** [comment]
Looking into the `MultiPolygon` class it appears to hold a list of polygons, and you don't directly build one from coordinates.

My suggestion (completely untested but hopefully pointing you in the right direction) would be to try something along the lines of:
```java
new MultiPolygonBuilder().polygon(new PolygonBuilder().coordinates().buildGeometry()).buildGeometry()
```

**Comment by Wild-Soul** [comment]
Yes there is a constructor that access a  List<PolygonBuilder> .
So first I had to build the polygons and then provide them to MultiPolygonBuilder.
That's working fine.

 But maybe this feature can be added to build the MultiPolygon using coordinate, if it's possible. Same goes for all Multi* shape builders.
 
 Thanks for the help
