### ISSUE TITLE
[FEATURE] Feature Flag Behavior

### ISSUE THREAD

**Issue by andrross** [opensearch-project/OpenSearch#4024]
I just wanted to open a discussion about the [feature flag mechanism](https://github.com/opensearch-project/OpenSearch/blob/d8e2e757e348e45a55fddfc67560f1091ab2fbf5/server/src/main/java/org/opensearch/common/util/FeatureFlags.java) that has been recently introduce into OpenSearch. The goal of this mechanism is to allow integration of not-ready-for-primetime features into the main branches (and therefore the CI/CD process) as early as possible, while still keeping them disabled/hidden by default so an unsuspecting user doesn't start using a feature that isn't production ready. This should allow us to get feedback faster on features under development and avoid major merge pain that happens with long-lived feature branches.

All that being said, there's a few questions I want to open up to discussion:

### How to enable feature flags?
Currently, these flags are passed as JVM args. I believe the general convention today is that JVM args are mostly used for tuning the JVM itself, and OpenSearch application configuration is specified via settings in opensearch.yml (I could be wrong about this though...). Should we change feature flags to be a configuration option in opensearch.yml, i.e. something like `experimental.features: ["feature-1", "feature-2"]`? This probably isn't super important, more a question of consistency/preference.

### How to enforce cluster consistency?
A feature flag is enabled per-node in a cluster. I suspect most or maybe even all features will likely only make sense when every node in the cluster is configured the same. I believe this is the case for segment replication. Should there be a check to force that when a node joins a cluster it has the same feature flags enabled as the existing nodes?

### How to enforce data consistency?
Segment replication is a property of an index. It is possible to create an index with segment replication enabled, then restart the cluster with the segment replication feature flag disabled. I believe this should result in an error. This may be feature-specific behavior, as opposed to general feature flag behavior, but I suspect we may have lots of features in the future that involve data-at-rest like this.

**Comment by andrross** [comment]
@kartg @mch2 I'm interested in your opinions here

**Comment by mch2** [comment]
@andrross Thanks for raising this.  I like the idea of transitioning to a yml setting from a usability perspective as long as we document very clearly that these are expert settings that should not be enabled in a production setting.

With that said, I understand the intention behind enforcing cluster & data consistency but I'm not sure its worth it for experimental/test only situations?

**Comment by andrross** [comment]
> With that said, I understand the intention behind enforcing cluster & data consistency but I'm not sure its worth it for experimental/test only situations?

That's fair. We'd just want to clearly document this, i.e. "If nodes within a cluster have differing feature flags enabled, or if you later access data with a feature flag disabled that was enabled at index time, then behavior is undefined."

**Comment by ankitkala** [comment]
Moving these flags to yml sounds like a decent option. Essentially these would be static setting which customer can modify and restart the OS process. 

Can we define the feature flags as combination of static/dynamic and cluster/index level settings instead? 
- Depending on the feature, index level setting can provide a finer control to the customer where he can experiment with the feature on a particular index. 
- These setting can also be dynamic(not for all features obviously) and allow user to toggle at runtime without having to restart the OS process.

**Comment by andrross** [comment]
@ankitkala I think we're kind of intentional about making this a two step process. For example, segment replication is an index setting, but a user must enable the feature flag for that index setting to be available. But once it is enabled, a user can experiment on a per-index basis. Making the overall feature flags dynamically configurable to avoid needing to restart the process is definitely something we could do, but maybe that could be a future enhancement?

I think what we're settling on here is that feature flags would provide a more consistent experience if they were statically defined as a setting in the yml file, as opposed to a JVM system property. @nknize Do you have any objection or other suggestions?

If we settle on that, I'll close out this issue and open a new one specifically detailing the requested change.

**Comment by nknize** [comment]
> Should we change feature flags to be a configuration option in opensearch.yml

I'm +0 on this. The reasoning behind transitioning to a yml config entry is sound and I don't disagree, but I think there are other CLI parameters that can be passed that aren't jvm specific (e.g., `tests.opensearch.path.data`, `tests.opensearch.http.port`). I wonder if this opens a can of consistency worms?


> Should there be a check to force that when a node joins a cluster it has the same feature flags enabled as the existing nodes?

You're correct that this can be trappy. I'm +0 as I think this is a nice to have as well. I'm not losing sleep if we don't get this done in the super near term.


> It is possible to create an index with segment replication enabled, then restart the cluster with the segment replication feature flag disabled.

Another great point. I'm +0 this enhancement for similar reasons as above.


In general I agree. I don't think these are high sev issues, though, as they pertain to developmental features we don't want customer to easily enable. Maybe mark this issue as a meta issue that links to smaller `good first issue` or `low hanging fruit` issues? I like the idea of the community helping out here and they might be able to build merit by knocking out some of these changes?

**Comment by andrross** [comment]
I created a low hanging fruit issue for changing how the feature flags are specified. I'm on board with the other safety checks are probably not super important for experimental features. I'm going to close this issue. We can revisit if we find that doing the other things is necessary.
