### ISSUE TITLE
Dashboards: Index Patterns field list requires manual refresh

### ISSUE THREAD

**Issue by mikespharss** [opensearch-project/OpenSearch#4046]
**Is your feature request related to a problem? Please describe.**
Dashboards requires a manual field refresh of the Index Pattern when new fields are added to events before those fields can be utilized in searches.

**Describe the solution you'd like**
New fields are automatically available for use in searches when they are added to events, without manual intervention and within some reasonable timeframe

**Additional context**
Kibana removed the field cache in v7.11: https://github.com/elastic/kibana/pull/82223

If this has already been addressed in current versions of Dashboards, my apologies, I tried searching but couldn't find any references. We're currently running OpenSearch 1.1 R20211203-P4

**Comment by VachaShah** [comment]
Moving to https://github.com/opensearch-project/OpenSearch-Dashboards

**Comment by mikespharss** [comment]
Apologies, I missed there was a separate project for Dashboards when I was looking for existing issues.

I believe this is a duplicate of https://github.com/opensearch-project/OpenSearch-Dashboards/issues/913

**Comment by VachaShah** [comment]
No problem! Closing this one since there is an existing issue in Dashboards.

**Comment by CEHENKLE** [comment]
Man, I snooze I lose ;) :)  Thanks for opening this @mikespharss  :)
