### ISSUE TITLE
[BUG]Gradle Check running longer than 2 hours

### ISSUE THREAD

**Issue by peterzhuamazon** [opensearch-project/OpenSearch#4080]
Hi,

Recently I have seen some cases where gradle check is running longer than 2 hours, and jenkins abort it due to timeout set to 2hr.

https://build.ci.opensearch.org/job/gradle-check/1221/console

This is quite surprising as it normally takes max 50min to complete the run.

Seems like there is no errors in the run either, it is just very slow overall.

Thanks.

**Comment by reta** [comment]
@peterzhuamazon it seems to be a variation of Java heap space issue:

```
An exception has occurred in the compiler (17.0.3). Please file a bug against the Java compiler via the Java bug reporting page (http://bugreport.java.com/) after checking the Bug Data**** (http://bugs.java.com/) for duplicates. Include your program, the following diagnostic, and the parameters passed to the Java compiler in your report. Thank you.
java.lang.OutOfMemoryError: Java heap space
```

**Comment by reta** [comment]
Closing this one, will track OOM in https://github.com/opensearch-project/OpenSearch/issues/7746
