### ISSUE TITLE
[BUG] index it can't refresh automatically for my created

### ISSUE THREAD

**Issue by cindy850322** [opensearch-project/OpenSearch#4139]
**Describe the bug**
The parameter of index:"refresh_interval" is to set the default value, the index of the auditlog document count will be refreshed automatically.
But the index that I created is not refreshed automatically, I need to refresh the index manually.

**Screenshots**
1.Before refresh index manually 
![image](https://user-images.githubusercontent.com/58366025/182985040-c38a6a46-d9ae-4e48-8d59-ec3ef7942bcd.png)

2. After 1mins
![image](https://user-images.githubusercontent.com/58366025/182985573-fa4c6325-cc59-4153-8c00-0f0029395a11.png)

3.After refresh index manually 
![image](https://user-images.githubusercontent.com/58366025/182985804-0edddff3-6156-4802-9a8b-97345779cf44.png)

**Expected behavior**
I expected  I created the index can refresh automatically like auditlog.

**Host/Environment (please complete the following information):**
 - OS: CentOS Linux release 7.9.
 - Version Opensearch 1.3.3

Please help me this solution ! thanks so much.
Cindy

**Comment by tlfeng** [comment]
@cindy850322 According to the documents:
https://www.elastic.co/guide/en/elasticsearch/reference/7.10/indices-refresh.html#refresh-api-desc
https://www.elastic.co/guide/en/elasticsearch/reference/7.10/index-modules.html#dynamic-index-settings
OpenSearch periodically refreshes indices every second, but only on indices that have received one search request or more in the last 30 seconds (which is the default value of the setting `index.search.idle.after`).

Even if refresh operation is not executed due to no search request, new searches that hit an idle shard where a refresh is pending will wait for the next background refresh (within the default 1s).
(This behavior aims to automatically optimize bulk indexing in the default case when no searches are performed.)

Could you have a try to verify refresh operation can be done automatically if there is a recent search request on the index?

**Comment by tlfeng** [comment]
I did a simple test to verify the refresh mechanism I mentioned above, and it shown that the fresh function is acting properly.
I will close the issue for now, and please re-open it if you have further question.

1 start an OpenSearch cluster
2 run the script to ingest data to an index continuously
``` shell
for i in {1110..19000};
do echo $i;
t=`date -u +"%Y-%m-%dT%T.%3N"`;
echo $t;
sleep 1 ;
curl -XPOST http://localhost:9200/test-index/_doc/$i -H 'Content-Type: application/json' -d'{"date":"'$t'" ,  "v":"'$i'"}';
done
```
3 run "cat indices" API to see the current status of document count and storage size
```
$ curl "http://localhost:9200/_cat/indices?v&pretty"
health status index      uuid                   pri rep docs.count docs.deleted store.size pri.store.size
yellow open   test-index 8cX3HfwEQtGCQWxZxzUZfA   1   1          1            0      4.1kb          4.1kb
```
4 wait a minute and re-run "cat indices" API, there was no change in any column.
5 run a search request to the index
``` shell
curl -XGET http://localhost:9200/test-index/_search?pretty \
-H 'Content-Type: application/json' -d '
{
    "query": {
        "match_all": {}
    }
}
';
```
6 re-run "cat indices" API
``` shell
# [23:51:29]
$ curl "http://localhost:9200/_cat/indices?v&pretty"           
health status index      uuid                   pri rep docs.count docs.deleted store.size pri.store.size
yellow open   test-index 8cX3HfwEQtGCQWxZxzUZfA   1   1        448            0      4.1kb          4.1kb

# [23:51:31] 
$ curl "http://localhost:9200/_cat/indices?v&pretty"
health status index      uuid                   pri rep docs.count docs.deleted store.size pri.store.size
yellow open   test-index 8cX3HfwEQtGCQWxZxzUZfA   1   1        449            0      4.1kb          4.1kb

# [23:51:32] 
$ curl "http://localhost:9200/_cat/indices?v&pretty"
health status index      uuid                   pri rep docs.count docs.deleted store.size pri.store.size
yellow open   test-index 8cX3HfwEQtGCQWxZxzUZfA   1   1        460            0     44.8kb         44.8kb

# [23:51:44] 
$ curl "http://localhost:9200/_cat/indices?v&pretty"
health status index      uuid                   pri rep docs.count docs.deleted store.size pri.store.size
yellow open   test-index 8cX3HfwEQtGCQWxZxzUZfA   1   1        463            0     44.8kb         44.8kb

# [23:51:47]
$ curl "http://localhost:9200/_cat/indices?v&pretty"
health status index      uuid                   pri rep docs.count docs.deleted store.size pri.store.size
yellow open   test-index 8cX3HfwEQtGCQWxZxzUZfA   1   1        465            0     44.8kb         44.8kb

# [23:52:13]
$ curl "http://localhost:9200/_cat/indices?v&pretty"
health status index      uuid                   pri rep docs.count docs.deleted store.size pri.store.size
yellow open   test-index 8cX3HfwEQtGCQWxZxzUZfA   1   1        475            0       35kb           35kb
```
7 It shows that refresh operation will automatically run for an index only when there was a recent search request to the index.
