### ISSUE TITLE
[BUG] org.opensearch.cluster.routing.allocation.decider.DiskThresholdDeciderIT.testRestoreSnapshotAllocationDoesNotExceedWatermark

### ISSUE THREAD

**Issue by Bukhtawar** [opensearch-project/OpenSearch#4162]
**Describe the bug**

**To Reproduce**
```
REPRODUCE WITH: ./gradlew ':server:internalClusterTest' --tests "org.opensearch.cluster.routing.allocation.decider.DiskThresholdDeciderIT.testRestoreSnapshotAllocationDoesNotExceedWatermark" -Dtests.seed=683FC95AAA3080A9 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=en-IN -Dtests.timezone=America/Santarem -Druntime.java=17
```

Build failure : https://build.ci.opensearch.org/job/gradle-check/1566/testReport/junit/org.opensearch.cluster.routing.allocation.decider/DiskThresholdDeciderIT/testRestoreSnapshotAllocationDoesNotExceedWatermark/

**Expected behavior**

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**

**Comment by peternied** [comment]
+1 failure, see https://build.ci.opensearch.org/job/gradle-check/3072/console

**Comment by peternied** [comment]
+1 failure, see https://build.ci.opensearch.org/job/gradle-check/3649/testReport/junit/org.opensearch.cluster.routing.allocation.decider/DiskThresholdDeciderIT/testRestoreSnapshotAllocationDoesNotExceedWatermark/
