### ISSUE TITLE
[BUG] Project build is failing on Mac M1

### ISSUE THREAD

**Issue by vzez** [opensearch-project/OpenSearch#4173]
**Describe the bug**
Build is failing with below err
Could not determine the dependencies of task ':qa:full-cluster-restart:v2.1.1#upgradedClusterTest'.
> Could not resolve all task dependencies for configuration ':qa:full-cluster-restart:opensearch_distro_extracted_testclusters-qa-full-cluster-restart-v2.1.1-1-2.1.1-'.
   > Could not resolve project :distribution:bwc:bugfix.
     Required by:
         project :qa:full-cluster-restart
      > Project :qa:full-cluster-restart declares a dependency from configuration 'opensearch_distro_extracted_testclusters-qa-full-cluster-restart-v2.1.1-1-2.1.1-' to configuration 'expanded-darwin-arm64-tar' which is not declared in the descriptor for project :distribution:bwc:bugfix.

**To Reproduce**
pull latest code and run a gradle build on mac m1

**Expected behavior**
gradle build and gradle check must be completed without any errors

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**
 - OS: Mac M1
 - Version: 12.3.1

**Additional context**
@saratvemulapalli

**Comment by saratvemulapalli** [comment]
Thanks for opening this up @vzez. 
I dont have an M1 machine, the code says we do build a distribution for darwin-arm64[1]. 
Anybody here can help run this and confirm ? 

[1] https://github.com/opensearch-project/OpenSearch/tree/main/distribution/archives/darwin-arm64-tar

**Comment by heemin32** [comment]
I see the same issue.
Following is from the previous conversation. https://github.com/opensearch-project/OpenSearch/pull/1668

> I rebased my changes. I did more debugging on my side from on an Apple Silicon Mac, and it looks like the BWC process is checking compatibility with previous versions (starting from 7.x) with the darwin-arm4 arch. The problem is that these distributions don't exist. I would need to explicitely say that the first darwin-arm64 version is this one for the backward compatibility checks, but couldn't find out how.

**Comment by dblock** [comment]
Related https://github.com/opensearch-project/OpenSearch/issues/1449 is still open, and would love someone who cares about Mac to contribute, even if it's just the precommit checks.

**Comment by peterzhuamazon** [comment]
Re-open as disable macos bwc only happens on main, not 2.x.

With this issue completed we now have both x64 and arm64 MacOS Core Snapshot tarball:
* https://github.com/opensearch-project/opensearch-build/issues/4670
Would love to see this get properly supported on MacOS.
I will take a look since I now have a M macbook now.

Thanks.

**Comment by peterzhuamazon** [comment]
Current 2.x error:
```

$ ./gradlew check
Picked up JAVA_TOOL_OPTIONS: -Dlog4j2.formatMsgNoLookups=true

> Task :buildSrc:compileJava
Note: /Users/zhujiaxi/amazonworks/sourcecodes/opensearch-project/OpenSearch/buildSrc/src/main/java/org/opensearch/gradle/test/DistroTestPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

> Task :buildSrc:compileGroovy
Picked up JAVA_TOOL_OPTIONS: -Dlog4j2.formatMsgNoLookups=true
Note: /Users/zhujiaxi/amazonworks/sourcecodes/opensearch-project/OpenSearch/buildSrc/src/main/groovy/org/opensearch/gradle/test/TestWithSslPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/zhujiaxi/amazonworks/sourcecodes/opensearch-project/OpenSearch/buildSrc/src/main/groovy/org/opensearch/gradle/test/TestWithSslPlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':qa:full-cluster-restart:v1.3.19#upgradedClusterTest'.
> Could not resolve all dependencies for configuration ':qa:full-cluster-restart:opensearch_distro_extracted_testclusters-qa-full-cluster-restart-v1.3.19-0-1.3.19-'.
   > Could not resolve project :distribution:bwc:maintenance.
     Required by:
         project :qa:full-cluster-restart
      > A dependency was declared on configuration 'expanded-darwin-arm64-tar' which is not declared in the descriptor for project :distribution:bwc:maintenance.

* Try:
> Review the variant matching algorithm at https://docs.gradle.org/8.9/userguide/variant_attributes.html#sec:abm_algorithm.
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Get more help at https://help.gradle.org.

BUILD FAILED in 27s
8 actionable tasks: 5 executed, 3 up-to-date
```

**Comment by peternied** [comment]
[Triage - attendees [1](https://github.com/peternied) [2](https://github.com/reta) [3](https://github.com/andrross) [4](https://github.com/enjoychange) [5](https://github.com/lukas-vlcek/)]
Thanks for engaging on this issue @vzez & @peterzhuamazon this was just fixed a little bit ago.  Please create any new issues if you have troubles, thanks.
- https://github.com/opensearch-project/OpenSearch/pull/15036

**Comment by peterzhuamazon** [comment]
```

All projects evaluated.
Task path 'qa:full-cluster-restart:v3.1.0#bwcTest' matched project ':qa:full-cluster-restart'
Task name matched 'v3.1.0#bwcTest'
Selected primary task 'v3.1.0#bwcTest' from project :qa:full-cluster-restart
Failed to get resource: GET. [HTTP HTTP/1.1 403 Forbidden: https://ci.opensearch.org/ci/dbc/snapshots/lucene/adoptium_25/mac/25.0.1/mac-25.0.1.pom)]
Failed to get resource: HEAD. [HTTP HTTP/1.1 403 Forbidden: https://artifacts.opensearch.org/releases/core/opensearch/3.1.0/opensearch-min-3.1.0-darwin-arm64.tar.gz)]
Failed to get resource: HEAD. [HTTP HTTP/1.1 403 Forbidden: https://artifacts.opensearch.org/release-candidates/core/opensearch/3.1.0/opensearch-min-3.1.0-darwin-arm64.tar.gz)]

[Incubating] Problems report is available at: file:///Users/zhujiaxi/amazonworks/sourcecodes/peterzhuamazon/OpenSearch/build/reports/problems/problems-report.html

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':qa:full-cluster-restart:v3.1.0#upgradedClusterTest'.
> Could not resolve all dependencies for configuration ':qa:full-cluster-restart:opensearch_distro_extracted_testclusters-qa-full-cluster-restart-v3.1.0-1-3.1.0-'.
   > Could not resolve opensearch-distribution:opensearch:3.1.0.
     Required by:
         project ':qa:full-cluster-restart'
      > Could not resolve opensearch-distribution:opensearch:3.1.0.
         > Could not get resource 'https://artifacts.opensearch.org/releases/core/opensearch/3.1.0/opensearch-min-3.1.0-darwin-arm64.tar.gz'.
            > Could not HEAD 'https://artifacts.opensearch.org/releases/core/opensearch/3.1.0/opensearch-min-3.1.0-darwin-arm64.tar.gz'. Received status code 403 from server: Forbidden
      > Could not resolve opensearch-distribution:opensearch:3.1.0.
         > Could not get resource 'https://artifacts.opensearch.org/release-candidates/core/opensearch/3.1.0/opensearch-min-3.1.0-darwin-arm64.tar.gz'.
            > Could not HEAD 'https://artifacts.opensearch.org/release-candidates/core/opensearch/3.1.0/opensearch-min-3.1.0-darwin-arm64.tar.gz'. Received status code 403 from server: Forbidden

* Try:
> Run with --debug option to get more log output.
> Run with --scan to generate a Build Scan (powered by Develocity).
> Get more help at https://help.gradle.org.

* Exception is:
org.gradle.api.internal.tasks.TaskDependencyResolveException: Could not determine the dependencies of task ':qa:full-cluster-restart:v3.1.0#upgradedClusterTest'.
```

**Comment by peterzhuamazon** [comment]
In theory, since we only push mac artifacts to `snapshots` on `ci.opensearch.org`, and never in `releases` or `release-candidates` on `artifacts.opensearch.org`, this commend should never even run.

However, it is possible something got altered between August and now, so that `snapshots` was used instead of `release-candidates` in some PR.

I see two ways of solving this:
1. Since we already publish mac snapshots, no hard to add another publishing target to `release-candidates`, not `releases` tho as it is not ready.
2. Figure out what cause the diff between then and now.

Thanks.

**Comment by peterzhuamazon** [comment]
Revert in [#5857](https://github.com/opensearch-project/opensearch-build/pull/5857) as it has issues with the jenkinsfile size.

**Comment by peterzhuamazon** [comment]
Will need to take a closer look on what to do to resolve this.
Prefer to fix in core so we dont need to update the builds.
