### ISSUE TITLE
Performance testing using OpenSearch Benchmark

### ISSUE THREAD

**Issue by bharath-techie** [opensearch-project/OpenSearch#4188]
As part of this we'll add PIT performance tests to 'opensearch-benchmark-workloads' and also extensively performance test PIT APIs using opensearch benchmark.

Parent issue - https://github.com/opensearch-project/OpenSearch/issues/3959

**Comment by dhruv16dhr** [comment]
@bharath-techie @Arpit-Bandejiya Please close this task as testing is already completed.
Also link the PR for this issue.
