### ISSUE TITLE
[BUG] Fix thirdPartyAudit gradle task for test/frameworks for OpenSearch.

### ISSUE THREAD

**Issue by adnapibar** [opensearch-project/OpenSearch#420]
**Describe the bug**
Currently the thirdPartyAudit task is failing for the test:framework module after renaming to OpenSearch.

```
ERROR: Scanned 2238 class file(s) for forbidden API invocations (in 3.14s), 3 error(s).
ERROR: Check for forbidden API calls failed, see log.
==end of forbidden APIs==
Missing classes:
  * org.apache.tools.ant.BuildException
  * org.apache.tools.ant.DirectoryScanner
  * org.apache.tools.ant.Task
  * org.apache.tools.ant.types.FileSet
Classes with violations:
  * org.objenesis.instantiator.sun.UnsafeFactoryInstantiator
```

**To Reproduce**

From the root directory, run

`./gradlew :test:framework:thirdPartyAudit --stacktrace`

**Expected behavior**
Task should pass.

**Comment by anasalkouz** [comment]
Hi @adnapibar, I see couple of PL already merged to address the issue, anything else pending? can you close the issue?

**Comment by owaiskazi19** [comment]
Looks like ` ./gradlew :test:framework:thirdPartyAudit` is working on `main` now.

**Comment by dblock** [comment]
Closing. Reopen if this isn't finished.
