### ISSUE TITLE
[BUG] Fix flaky test org.opensearch.index.ShardIndexingPressureConcurrentExecutionTests.testReplicaThreadedUpdateToShardLimitsAndRejections

### ISSUE THREAD

**Issue by reta** [opensearch-project/OpenSearch#4212]
**Describe the bug**
New flaky test `org.opensearch.index.ShardIndexingPressureConcurrentExecutionTests.testReplicaThreadedUpdateToShardLimitsAndRejections` ,  spotted in [1]

```
java.lang.AssertionError: expected null, but was:<org.opensearch.index.stats.IndexingPressurePerShardStats@5eae0090>
	at __randomizedtesting.SeedInfo.seed([9EFE9529CF42C133:9166A1D8EFC3EFA6]:0)
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotNull(Assert.java:756)
	at org.junit.Assert.assertNull(Assert.java:738)
	at org.junit.Assert.assertNull(Assert.java:748)
	at org.opensearch.index.ShardIndexingPressureConcurrentE
```

[1] https://build.ci.opensearch.org/job/gradle-check/1711/testReport/junit/org.opensearch.index/ShardIndexingPressureConcurrentExecutionTests/testReplicaThreadedUpdateToShardLimitsAndRejections/

**To Reproduce**
```
REPRODUCE WITH: ./gradlew ':server:test' --tests "org.opensearch.index.ShardIndexingPressureConcurrentExecutionTests.testReplicaThreadedUpdateToShardLimitsAndRejections" -Dtests.seed=9EFE9529CF42C133 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=fr-LU -Dtests.timezone=America/Goose_Bay -Druntime.java=17
```

**Expected behavior**
Test should pass

**Plugins**
Standard

**Screenshots**

**Host/Environment (please complete the following information):**
 - OS: CI
 - Version `main`

**Additional context**

**Comment by dblock** [comment]
https://github.com/opensearch-project/OpenSearch/pull/3633

**Comment by dblock** [comment]
https://github.com/opensearch-project/OpenSearch/pull/5283#issuecomment-1319863171

**Comment by dblock** [comment]
https://github.com/opensearch-project/OpenSearch/pull/5069#issuecomment-1320706981

**Comment by dblock** [comment]
This was added in https://github.com/opensearch-project/OpenSearch/pull/1336

**Comment by Rishikesh1159** [comment]
Looked into this test a bit. The test fails only when rejection count if full i.e rejection count is equal to NUM_THREADS. Two possible for workaround/Questions:
-> Can rejection count be allowed to be equal to NUM_THREADS? is this something we should happening in test? or
-> Should we update logic of asserting to null when all the releasable's are null.

@getsaurabh02 can you please give your thoughts on it flaky test.

**Comment by dblock** [comment]
https://github.com/opensearch-project/OpenSearch/pull/4587#issuecomment-1332837125

**Comment by getsaurabh02** [comment]
Thanks for sharing the info @Rishikesh1159. I agree with the adding the optional null check as above, since the ``shardStoreStats`` objects move from [hot to cold store](https://github.com/opensearch-project/OpenSearch/blob/139c2cfdf7d274a6e72d49f0673e7dc4ef38a327/server/src/main/java/org/opensearch/index/ShardIndexingPressureStore.java) in case they are not updated in a while. 

Here, if rejection count equals to the ``NUM_THREADS`` which means rejections happened until the last request, the `` shardIndexingPressure.shardStats().getIndexingPressureShardStats(shardId1)`` will return the ``shardStoreStats`` which was updated on the last request. In other cases, the ``shardStoreStats`` simply moves to the cold store and is returned null.

**Comment by Rishikesh1159** [comment]
Thanks @getsaurabh02 for your detail explanation. What you said makes sense. I have put out a small PR to fix this behavior of test by adding the optional null check as we discussed. Can you please review the [PR](https://github.com/opensearch-project/OpenSearch/pull/5439)
