### ISSUE TITLE
[BUG] Flakey test failure in SortedSetDVStringFieldDataTests testSortMissingLast

### ISSUE THREAD

**Issue by kartg** [opensearch-project/OpenSearch#4238]
**Describe the bug**

First observed in https://github.com/opensearch-project/OpenSearch/pull/4183#issuecomment-1215586520, but I hit the same failure several times in #4222 and was able to reproduce it locally:

```
REPRODUCE WITH: ./gradlew ':server:test' --tests "org.opensearch.index.fielddata.SortedSetDVStringFieldDataTests.testSortMissingLast" -Dtests.seed=BC7C1431A4F70C5D -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=ga-IE -Dtests.timezone=Europe/Belgrade -Druntime.java=17

org.opensearch.index.fielddata.SortedSetDVStringFieldDataTests > testSortMissingLast FAILED
    java.lang.AssertionError: expected:<1105> but was:<1023>
```

**To Reproduce**
See above

**Expected behavior**
Test consistently passes

**Plugins**
None

**Screenshots**
N/A

**Host/Environment (please complete the following information):**

**Additional context**

**Comment by kartg** [comment]
@nknize are you poking at this?

**Comment by nknize** [comment]
Yes. It's new as of the Lucene 9.4 snapshot PR. Only reproducible if you run the entire Test class, not the individual case.

**Comment by owaiskazi19** [comment]
https://github.com/opensearch-project/OpenSearch/pull/4066

**Comment by dbwiddis** [comment]
Suspect there was a regression in #4183 in changes to [`BytesRefFieldComparatorSource.java`](https://github.com/opensearch-project/OpenSearch/pull/4183/files#diff-062662899cc9abd5a86a57447ef1d38b6a16ef0700b4143f53bacba69e7948c1)

**Comment by dbwiddis** [comment]
Some more investigation.  The number of documents in the search impacts the failure.  The random flakiness is introduced by this line, where it succeeds half the time:
https://github.com/opensearch-project/OpenSearch/blob/05a58192433f6e007ade61b4b4f21d0f068d50e0/server/src/test/java/org/opensearch/index/fielddata/AbstractStringFieldDataTestCase.java#L282

The failures occur in an edge case where the last element of the document list is null.  In the repro case listed above, there are 1105 documents, but the last one is null, and any number of documents 1103 or below fails (both 1104 and 1105 succeed).

**Comment by dbwiddis** [comment]
From Lucene's [`IndexSearcher`](https://lucene.apache.org/core/9_0_0/core/org/apache/lucene/search/IndexSearcher.html?is-external=true) javaDoc:
> NOTE: The [search(org.apache.lucene.search.Query, int)](https://lucene.apache.org/core/9_0_0/core/org/apache/lucene/search/IndexSearcher.html?is-external=true#search(org.apache.lucene.search.Query,int)) and [searchAfter(org.apache.lucene.search.ScoreDoc, org.apache.lucene.search.Query, int)](https://lucene.apache.org/core/9_0_0/core/org/apache/lucene/search/IndexSearcher.html?is-external=true#searchAfter(org.apache.lucene.search.ScoreDoc,org.apache.lucene.search.Query,int)) methods are configured to only count top hits accurately up to 1,000 and may return a [lower bound](https://lucene.apache.org/core/9_0_0/core/org/apache/lucene/search/TotalHits.Relation.html) of the hit count if the hit count is greater than or equal to 1,000. On queries that match lots of documents, counting the number of hits may take much longer than computing the top hits so this trade-off allows to get some minimal information about the hit count without slowing down search too much. The [TopDocs.scoreDocs](https://lucene.apache.org/core/9_0_0/core/org/apache/lucene/search/TopDocs.html#scoreDocs) array is always accurate however.

This conflicts with the assertion here:
https://github.com/opensearch-project/OpenSearch/blob/05a58192433f6e007ade61b4b4f21d0f068d50e0/server/src/test/java/org/opensearch/index/fielddata/AbstractStringFieldDataTestCase.java#L285

The value of `topDocs.totalHits.value` is not reliable if it is above 1000.  (If you output `topDocs.totalHits` in this case you will get the String `1001+`.)

This test needs to be adjusted to account for this possible inaccuracy.
