### ISSUE TITLE
[BUG] : Error while doing gradle check

### ISSUE THREAD

**Issue by navneet1v** [opensearch-project/OpenSearch#4239]
**Describe the bug**
Getting this error while doing the gradle check.

```
2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':distribution:bwc:staged:buildBwcLinuxTar'.
> Building 2.2.0 didn't generate expected file /var/jenkins/workspace/gradle-check/search/distribution/bwc/staged/build/bwc/checkout-2.2/distribution/archives/linux-tar/build/distributions/opensearch-min-2.2.0-SNAPSHOT-linux-x64.tar.gz
```

CI link: https://build.ci.opensearch.org/job/gradle-check/1786/console

**To Reproduce**
1. Checkout the github repo: OpenSearch.
2. Do a ./gradlew check

**Expected behavior**

**Plugins**
NA

**Screenshots**

**Host/Environment (please complete the following information):**
 - OS: MAC OS

**Additional context**

**Comment by owaiskazi19** [comment]
@navneet1v can you try to run gradle check now on the latest `main` and update if you face the same issue?

**Comment by navneet1v** [comment]
Hi,
I tried with the latest version of the https://build.ci.opensearch.org/job/gradle-check/1946/ which is still failing.

**Comment by owaiskazi19** [comment]
I see a successful build for the above mentioned gradle check. Am I missing anything here?
```
BUILD SUCCESSFUL in 20m 17s
2602 actionable tasks: 2588 executed, 2 from cache, 12 up-to-date

**Comment by navneet1v** [comment]
Yeah I think for this specific check it is working but now others some other check is failing.

**Comment by owaiskazi19** [comment]
Can you open an issue for those specific checks? We can close this one.
