### ISSUE TITLE
[META] Support for HTTP/2 (client side)

### ISSUE THREAD

**Issue by reta** [opensearch-project/OpenSearch#4257]
**Is your feature request related to a problem? Please describe.**
The HTTP/2 support on the server side is getting closer to the first milestone (see please [1]), however the client side is falling behind. The key reason is that all OpenSearch clients (rest-client., RHLC, opensearch-java) use Apache HttpComponents / Core 4.x, which are already EOLed and superseded by Apache HttpClient / Core 5.x. The migration to the Apache HttpClient / Core 5.x is a necessary undertaking (not only to benefit from HTTP/2 support but also to rely on maintanable libraries). In scope of this issue, we need to:

 - [Migrate to Apache HttpClient / Core 5.x](https://github.com/opensearch-project/OpenSearch/issues/4256) - https://github.com/opensearch-project/OpenSearch/issues/4256
 - [Introduce HTTP/2 compatible client transports](https://github.com/opensearch-project/opensearch-java/pull/281) - https://github.com/opensearch-project/opensearch-java/pull/281

[1] [Support for HTTP/2 ](https://github.com/opensearch-project/OpenSearch/issues/3651)

**Comment by dblock** [comment]
Would it be easier to remove all REST clients from this repo in 3.0?

**Comment by reta** [comment]
We could, but we'll keep them (rest, RHLC, ...) anyway, right?

**Comment by reta** [comment]
@dblock we have only one issue left here [1], please help to get it in, the repo looks unmaintaned 

[1] https://github.com/opensearch-project/common-utils/pull/287

**Comment by reta** [comment]
This is done, closing it
