### ISSUE TITLE
[Segment Replication][BUG] Failing test: SegmentReplicationIndexShardTests.testNRTReplicaPromotedAsPrimary

### ISSUE THREAD

**Issue by Poojita-Raj** [opensearch-project/OpenSearch#4267]
**Describe the bug**
During gradle check the test - SegmentReplicationIndexShardTests.testNRTReplicaPromotedAsPrimary - is failing. This failure could be reproduced locally as well by running the test. 

**Expected behavior**
The test should pass.

**Screenshots**

Test fails a few different ways: 

<img width="1021" alt="image" src="https://user-images.githubusercontent.com/20815824/185688945-fb6af88f-f511-46b5-9b61-0ac12dfc57dc.png">

<img width="1001" alt="image" src="https://user-images.githubusercontent.com/20815824/185689413-f132346a-d53c-41a3-acb3-1d1a0fbe70ab.png">

<img width="1052" alt="image" src="https://user-images.githubusercontent.com/20815824/185689508-20d7dc9a-7fa1-4e9a-980d-6e00edba26fc.png">

<img width="1030" alt="image" src="https://user-images.githubusercontent.com/20815824/185689548-2d2e8180-b124-4ac9-837c-92dc65e2b4c3.png">

**Comment by dreamer-89** [comment]
Ran this test with 100 iterations without any failure. Closing this issue, @Poojita-Raj feel free to reopen if you encounter this again.
