### ISSUE TITLE
Setup Maven and Ivy repos for OpenSearch

### ISSUE THREAD

**Issue by setiah** [opensearch-project/OpenSearch#430]
Some tests in BuildPluginIT.java depend on Maven and Ivy repos of OpenSearch

**Comment by abbashus** [comment]
@setiah can this be closed? Did we have the `http://s3.amazonaws.com/artifacts.opensearch.org/maven` and `http://s3.amazonaws.com/artifacts.opensearch.org/ivy` repos setup?

**Comment by CEHENKLE** [comment]
Covering this here:  https://github.com/opensearch-project/opensearch-build/issues/20
