### ISSUE TITLE
[FEATURE] Support filter queries for approximate k-NN that is based on Nmslib

### ISSUE THREAD

**Issue by martin-gaievski** [opensearch-project/OpenSearch#4329]
**Is your feature request related to a problem? Please describe.**
We do not have support to effectively filter docs and then apply k-NN specifically on the filtered docs. This will help guarantee to obtain k Nearest Neighbors on the filtered set. Please note, we're requesting only for [Nmslib](https://github.com/nmslib/nmslib) based approximate k-NN search.

**Describe the solution you'd like**
Ideally we'd like to do k-NN approximate search on a sub-set of docs that match filtering criteria and have a guarantee of top K docs in result. We want to be able to define the filter(s) in knn query and use existing OpenSearch queries as filters (boolean, term etc.). 

**Describe alternatives you've considered**
Pre-filtering is supported with scoring script but in form of exact brute-force k-NN search. Post-filtering can be done as approximate search with post-processing, but problem is that top k results are not guaranteed. 

**Additional context**
We'd like to have parity with k-NN powered by Lucene, https://github.com/opensearch-project/k-NN/issues/376

**Comment by dblock** [comment]
Should this issue live in the k-nn repo?

**Comment by martin-gaievski** [comment]
agree, let me close this one
