### ISSUE TITLE
Support cross-cluster replication for data streams

### ISSUE THREAD

**Issue by laszloszurok** [opensearch-project/OpenSearch#4436]
Right now CCR does not work with data streams.

This should work. Elasticsearch has this functionality. The data stream name can be used as the autofollow pattern and backing indicies will be replicated. Here is the relevant PR on Elasticsearch side: https://github.com/elastic/elasticsearch/pull/61993/files

**Comment by gbbafna** [comment]
Hi @laszloszurok  , we do have a backlog item in ccr repo  : https://github.com/opensearch-project/cross-cluster-replication/issues/357 .

**Comment by laszloszurok** [comment]
Thank you @gbbafna, I did not find that issue earlier. I will close this then.
