### ISSUE TITLE
Add plugin install flag akin to -y/--yes/--assume-yes 

### ISSUE THREAD

**Issue by voidshard** [opensearch-project/OpenSearch#4467]
**Is your feature request related to a problem? Please describe.**
It's annoying when installing plugins being forced to type 'y' (or requiring some yes | opensearch-plugin install abomination). I'm fine with the prompt being the default, but at least let us avoid it at the user's discretion.

**Describe the solution you'd like**
Ideally we'd have a simple -y flag that skips the prompt.

**Describe alternatives you've considered**
- I could make my own docker container with the plugins installed already
- using 'yes | opensearch-plugin install' or similar

**Additional context**
Install command calls confirmPolicyExceptions
https://github.com/opensearch-project/OpenSearch/blob/54364a5d45ed0a20de42abb53cca8f33cfed88eb/distribution/tools/plugin-cli/src/main/java/org/opensearch/plugins/InstallPluginCommand.java#L884

Assuming any new perms are required, the user is prompted 
https://github.com/opensearch-project/OpenSearch/blob/54364a5d45ed0a20de42abb53cca8f33cfed88eb/server/src/main/java/org/opensearch/plugins/PluginSecurity.java#L85

Which is a straight print / scan for input with no option to avoid
https://github.com/opensearch-project/OpenSearch/blob/54364a5d45ed0a20de42abb53cca8f33cfed88eb/server/src/main/java/org/opensearch/plugins/PluginSecurity.java#L89

**Comment by voidshard** [comment]
Closed for not reading the help file closely. It was not obvious to me that -b / --batch was what I was wanting

**Comment by dblock** [comment]
+1 is this poorly documented? Care to improve?

**Comment by voidshard** [comment]
It is documented, rather I think the flag is badly named. -b / --batch sounds to me like I want to install a bunch of plugins at once and/or maybe with support to read plugins from a file or something.

I guess I read through the names of the flags I could pass and figured "no none of those sound like they do what I want" .. and it's not until I read the description of the flags - including the one I didn't think was in any way related - that I realised it *does* do what I want .. as a side .. effect?

Or maybe I was just coffee deprived and should have read the entire output of help. Eh who am I kidding, I never do that.
