### ISSUE TITLE
OpenSearch should participate in Hacktoberfest

### ISSUE THREAD

**Issue by dbwiddis** [opensearch-project/OpenSearch#4482]
**Is your feature request related to a problem? Please describe.**

[Hacktoberfest](https://hacktoberfest.com/) is an annual event run by DigitalOcean that encourages people to contribute to Open Source projects.

Participants who complete four qualifying Pull Requests during October receive swag (T-shirt) or a tree planted in their name.

I've participated as a project on my own Open Source project the past few years, and there is no shortage of new contributors coming by and looking for those "good first issues" to contribute to, particularly in the first week of October.  A few years ago I got about half of my unit tests migrated to a new platform thanks to Hacktoberfest.

**Describe the solution you'd like**

See https://hacktoberfest.com/participation/#maintainers

1. The main OpenSearch project repo should add a tag to the `hacktoberfest` topic
2. Some of the `good first issue` issues should have a `hacktoberfest` tag added.
3. A tag `hacktoberfest-accepted` should be created for PRs which are not merged during October but which should qualify

**Describe alternatives you've considered**

We could choose not to participate.

**Additional context**

This will require a little extra attention by maintainers to new contributors during the month of October, usually at the beginning of the month.

**Comment by dblock** [comment]
Should we move this to project-meta? Do we want the org to do this and create a label for every repo?

**Comment by dbwiddis** [comment]
Closing this issue as support is happening and the project is configured.  Looks like some people were planning this before I even thought of asking!
