### ISSUE TITLE
[Remote Store] Include Codec header and footer for segment metadata

### ISSUE THREAD

**Issue by Bukhtawar** [opensearch-project/OpenSearch#4605]
**Is your feature request related to a problem? Please describe.**
The segment upload to remote store also uploads the metadata containing the primary term and uuid however to this might be susceptible to silent data errors.

**Describe the solution you'd like**
We need to ensure we write the checksum as footer and also ensure we include a header to maintain file versions which should be helpful to read older version segment file metadata once we start to add new attribute to newer version.
**Describe alternatives you've considered**

**Additional context**

**Comment by kartg** [comment]
Closing this issue since the related PRs have been merged, and the changes were backported to `2.x` - 

* https://github.com/opensearch-project/OpenSearch/pull/5749
* https://github.com/opensearch-project/OpenSearch/pull/6406
