### ISSUE TITLE
Add getter for `path` field in `NestedQueryBuilder`

### ISSUE THREAD

**Issue by psmagin** [opensearch-project/OpenSearch#4609]
**Is your feature request related to a problem? Please describe.**
The only way now to get `path` from `NestedQueryBuilder` is a reflection

**Comment by saratvemulapalli** [comment]
@psmagin thanks for opening up the issue. Trying to understand, what is the use case of using `path`?
Also on a side note, could you contribute the change? (It should be pretty straight forward)[1]

[1] https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/index/query/NestedQueryBuilder.java

**Comment by psmagin** [comment]
@saratvemulapalli, it could be useful for creating some complicated queries, the path could be used as a key field to combine nested queries in one.
