### ISSUE TITLE
[Proposal] Strictly define OS version in GHA

### ISSUE THREAD

**Issue by Yury-Fridlyand** [opensearch-project/OpenSearch#4610]
## Is your feature request related to a problem? Please describe.
Now all GHA workflows use `ubuntu-latest` runners. The version of OS might be changed in future which might cause failures or crashes.
See example:
https://github.com/opensearch-project/OpenSearch/blob/9b2202aeb3a881c0c2ad72522fa1e2656d5d4d1e/.github/workflows/gradle-check.yml#L13

## Describe the solution you'd like
I propose to strictly define the OS version which should be used there. Currently `ubuntu-latest` = `ubuntu-20.04` ([link](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources)). The proposed fix should change all references to `ubuntu-latest` by `ubuntu-20.04`.

## Describe alternatives you've considered
Do nothing until GH publish OS version change for `ubuntu-latest`. There will be a few month period to update and fix all workflows if needed.

## Additional context
**Tags**: GHA, CI, ubuntu, ubuntu-latest, runner, OS version

I can to the fix (a PR) on my own, but I need an approval to that idea first.

**Comment by saratvemulapalli** [comment]
@Yury-Fridlyand thanks for the proposal.
Would it be better if we test against new and old versions, instead of just being static with the versions we know it works with? (GHA supports running with a matrix)[1]

[1] https://devblogs.microsoft.com/premier-developer/github-actions-overview/#matrix-builds

**Comment by saratvemulapalli** [comment]
@Yury-Fridlyand are you open to contributing the change?

**Comment by Yury-Fridlyand** [comment]
Yes. I'll run tests first.

**Comment by saratvemulapalli** [comment]
@Yury-Fridlyand i'll assign it to you, as you are working on it. If not let me know.

**Comment by Yury-Fridlyand** [comment]
@saratvemulapalli,
I see that GHA works on all ubuntu versions: https://github.com/Yury-Fridlyand/OpenSearch/pull/2
It is OK if I will try to update `ubuntu-latest` to `ubuntu-22.04` or `ubuntu-20.04` (no update actually)?

**Comment by Yury-Fridlyand** [comment]
*picture of tumbleweed*

**Comment by dblock** [comment]
Sounds OK to me!

**Comment by Yury-Fridlyand** [comment]
`ubuntu-latest` was bumped recently from `20.04` to `22.04`, and fortunately nothing was broken (unlike python 3.5 projects).
I tried to implement my proposal in #5612, which is closed, because it is irrelevant anymore.
