### ISSUE TITLE
[Feature Proposal] Given a Raw Search Query, Relevance Engineers/Business Owners Can Compare Two Search Configurations

### ISSUE THREAD

**Issue by macohen** [opensearch-project/OpenSearch#4626]

**Comment by macohen** [comment]
### Summary

Choosing different ranking algorithms can have drastically different effects on the users' search experience. Additionally, any operations on the query after the user submits and before results retrieval or after results are retrieved and before they are displayed can impact the user. This proposal is to build a simple UI in OpenSearch Dashboards to allow a user to visually and manually compare results of two different ranking algorithms for a given search query.

**Comment by saratvemulapalli** [comment]
@macohen thanks for opening up the issue. Could you share more details on the proposal and how it would benefit the community?

**Comment by saratvemulapalli** [comment]
Also is this something you are willing to take up and work on it?

**Comment by macohen** [comment]
> @macohen thanks for opening up the issue. Could you share more details on the proposal and how it would benefit the community? 
 Yes. I could have left this in draft a little longer, but will add the detail. The idea overall is to build more into the distribution for measuring relevance ranking in search applications so search application owners can more easily understand how different search configurations produce different results and choose one that works well for their use case. More to come and thanks for the comment, @saratvemulapalli

**Comment by macohen** [comment]
> Also is this something you are willing to take up and work on it?

Absolutely!

**Comment by saratvemulapalli** [comment]
Assigned it to you.

**Comment by macohen** [comment]
Closing this as https://github.com/opensearch-project/dashboards-search-relevance/issues/2 supersedes it.
