### ISSUE TITLE
[Searchable Snapshots] Add a new node role for remote search capabilities

### ISSUE THREAD

**Issue by kotwanikunal** [opensearch-project/OpenSearch#4652]
**Is your feature request related to a problem? Please describe.**
- Searchable snapshots will utilize a remote shard mechanism in which the entire shard will not be downloaded onto the node
- To suit this use case, we would like to have a set of nodes which can provide this capability. It will be enabled by adding support for a new `REMOTE_SEARCHER` node role

**Describe the solution you'd like**
- Currently, OpenSearch supports a variety of roles like `cluster_manager`, `data`, `ingest` listed [here](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/cluster/node/DiscoveryNodeRole.java). 
- For searchable snapshots as well as future phases of the storage roadmap, we would like to add a new role which can provide querying capabilities for a remote shard. 
- This role should be configured as a part of the configuration file for the node.
- A reference for the same can be found here: https://github.com/kotwanikunal/OpenSearch/pull/4

**Additional context**
- #2919
- #4152

**Comment by dblock** [comment]
Is this an important static capability, or is it an optimization that can it be modeled with dynamic node role that doesn't always exist? Meaning if no node was "remote searcher", could you fall back to a "data" node? If that's the case then you can use https://github.com/opensearch-project/OpenSearch/pull/3436 with no code changes.

**Comment by kotwanikunal** [comment]
> Is this an important static capability, or is it an optimization that can be modeled with dynamic node role that doesn't always exist and is simply preferred? Meaning if no node was "remote searcher", could you fall back to a "data" node? If that's the case then you can use #3436 with no code changes.

This is a required capability where we will need additional node configuration for a node to perform as a remote searcher.

**Comment by andrross** [comment]
My intuition is that we want this as an important static capability. I believe it's _possible_ to design the system to work that a regular data node can fallback to acting as a remote searcher, but it is generally a sub-optimal setup. The static role would require a user to be intentional about such a setup by applying both roles to a given node.

Having typed all of that, I suspect that is true about any of the dynamic roles that are used to select "preferred" nodes, so I'm open to being convinced otherwise.

**Comment by dblock** [comment]
@kotwanikunal What are things that would go into the additional node configuration?

@andrross Maybe my question implied fallback too much. We can also use the dynamic node capability without fallback. 

Reading the issue the tl;dr difference between a remote search node and a regular data node in which the entire shard will not be downloaded onto the node, correct? Is there more to this node? Does it need to be a first class node type? 

Finally, is there a better name than "remote searcher"? Is "search" a better name for this that can in the future collect other search-only capabilities?

**Comment by andrross** [comment]
@dblock 

> Reading the issue the tl;dr difference between a remote search node and a regular data node in which the entire shard will not be downloaded onto the node, correct? Is there more to this node? Does it need to be a first class node type?

The intent is for the role to serve two purposes:

1. Requires that part of the local disk is reserved for caching the remote index data (this is the additional configuration)
2. Ensures that "remote" shards are only allocated to these nodes

**Comment by andrross** [comment]
@dblock 

I do expect there to be separate "index" and "search" nodes as has been discussed. It's a fair question whether the "remote" aspect of it should be baked into the role. The purpose of the "remote" part is to ensure the requisite cache configuration has been supplied, but we could either define reasonable defaults or fail at runtime if the required configuration is not present. I do like the simplicity of "index" and "search".

(Note that there may well be a remote variant of indexers as well, i.e. indexers that index to local disk and replicate via seg rep versus indexers that write directly to a remote store and searchers access the remote data. If we go with the "remote search" role then we're potentially looking at 4 distinct roles.)

**Comment by dblock** [comment]
I would be much more comfortable with a "search" role vs. "remote search" as a "node optimized for search" and other parameters such as whether "part of disk is reserved for cache" becomes a configuration parameter that is independent of the role (but may have some semantics like "cannot be enabled on a node that's not "search").

**Comment by tlfeng** [comment]
A new node role `search` which is dedicated for search operation is added.

In `main` branch (version 3.0): PR https://github.com/opensearch-project/OpenSearch/pull/4689 / commit https://github.com/opensearch-project/OpenSearch/commit/c1272c181e6bd96d1db725dfbbcd5ac8e6058502.
In `2.x` branch (version 2.4.0):  PR https://github.com/opensearch-project/OpenSearch/pull/4739
