### ISSUE TITLE
[Searchable Snapshots] Fail gracefully with proper error message for invalid operations (e.g. writes)

### ISSUE THREAD

**Issue by andrross** [opensearch-project/OpenSearch#4655]
Searchable snapshot indexes are inherently read only. This goal of this task is to enumerate the operations that are invalid for a read-only searchable snapshot index, and then implement the behavior to respond with a proper error message. The concept of read-only indexes is not new in OpenSearch so existing capabilities may be able to be used here. This task does depend on #4138 to implement the initial framework that will be built upon.

The expected outcome of this task is the design for how this will be implemented. There are existing write block capabilities, but a perhaps important difference here is that the write blocks should not be able to be changed by the user for the life of this type of index, so that may be different than what the current capability allows for.

**Additional context**
- #2919

**Comment by Vishalks** [comment]
I am looking into this
