### ISSUE TITLE
[Segment Replication] Fix Failing RelocationIT tests with Segment Replication Enabled.

### ISSUE THREAD

**Issue by Rishikesh1159** [opensearch-project/OpenSearch#4665]
**Describe the bug**
Currently few tests in [RelocationIT](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/internalClusterTest/java/org/opensearch/recovery/RelocationIT.java) fail with segment replication enabled. Scope of this issue would be fixing those failing tests and creating an entire new IntegTest class for RelocationIT tests with segrep always enabled.

**To Reproduce**
Run testRelocationWhileRefreshing() of RelocationIT with Segment Replication enabled. It fails with exceptions and errors.

**Expected behavior**
A new IntegTest class having all RelocationIT tests and passing with segment replication enabled.

**Comment by Rishikesh1159** [comment]
RelocationIT has following 3 integ tests failing with segment replication enabled:
* testRelocationWhileRefreshing
* testRelocationWhileIndexingRandom
* testIndexSearchAndRelocationConcurrently

**Comment by mch2** [comment]
@Rishikesh1159 I believe we have versions of these tests now in SegmentReplicationRelocationIT - can this be closed?
