### ISSUE TITLE
[BUG] JPS keep showing `-Xms1g -Xmx1g`,  even after I specified it in OPENSEARCH_JAVA_OPTS

### ISSUE THREAD

**Issue by jianwu** [opensearch-project/OpenSearch#4666]
**Describe the bug**
When I start OpenSearch in Docker, I specified the `OPENSEARCH_JAVA_OPTS="-Xms3g -Xmx3g"`, but this value won't be reflected in `jps`. Not sure if this is just `jps` display problem or the memory setting is not applied at all. 

**To Reproduce**
1. Run: `docker run --env OPENSEARCH_JAVA_OPTS="-Xms3g -Xmx3g"  -p 9200:9200 -p 9600:9600 -e "discovery.type=single-node" opensearchproject/opensearch:2.3.0`
2. Get the docker container id
3. Run: `docker exec 1df18c38f96a jps -v`, it will response following information (Notice the `-Xms1g` is not reflection the overridden value: 
```
 docker exec 1df18c38f96a jps -v
105 OpenSearch -Xshare:auto -Dopensearch.networkaddress.cache.ttl=60 -Dopensearch.networkaddress.cache.negative.ttl=10 -XX:+AlwaysPreTouch -Xss1m -Djava.awt.headless=true -Dfile.encoding=UTF-8 -Djna.nosys=true -XX:-OmitStackTraceInFastThrow -XX:+ShowCodeDetailsInExceptionMessages -Dio.netty.noUnsafe=true -Dio.netty.noKeySetOptimization=true -Dio.netty.recycler.maxCapacityPerThread=0 -Dio.netty.allocator.numDirectArenas=0 -Dlog4j.shutdownHookEnabled=false -Dlog4j2.disable.jmx=true -Djava.locale.providers=SPI,COMPAT -Xms1g -Xmx1g -XX:+UseG1GC -XX:G1ReservePercent=25 -XX:InitiatingHeapOccupancyPercent=30 -Djava.io.tmpdir=/tmp/opensearch-10577715761831694178 -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=data -XX:ErrorFile=logs/hs_err_pid%p.log -Xlog:gc*,gc+age=trace,safepoint:file=logs/gc.log:utctime,pid,tags:filecount=32,filesize=64m -Dclk.tck=100 -Djdk.attach.allowAttachSelf=true -Djava.security.policy=/usr/share/opensearch/config/opensearch-performance-analyzer/opensearch_security.policy --add-opens=jdk.attach/sun.tools.a
106 PerformanceAnalyzerApp -Xshare:auto -Xms4m -Xmx64m -XX:+UseSerialGC -Dlog4j.configurationFile=/usr/share/opensearch/config/opensearch-performance-analyzer/log4j2.xml -Xms64M -Xmx64M -XX:+UseSerialGC -XX:CICompilerCount=1 -XX:-TieredCompilation -XX:InitialCodeCacheSize=4096 -XX:MaxRAM=400m -Dopensearch.path.home=/usr/share/opensearch -Dopensearch.path.conf=/usr/share/opensearch/config -Dopensearch.distribution.type=tar
447 Jps -Dapplication.home=/usr/share/opensearch/jdk -Xms8m -Djdk.module.main=jdk.jcmd
```

**Expected behavior**
The jps should show the value that specified with `OPENSEARCH_JAVA_OPTS`

**Plugins**
Default plugins

**Screenshots**

**Host/Environment (please complete the following information):**
 - OS: Docker
 - Version 2.3.0

**Additional context**

**Comment by reta** [comment]
@jianwu see please https://github.com/opensearch-project/opensearch-devops/issues/93

**Comment by dblock** [comment]
Closing as dup of https://github.com/opensearch-project/opensearch-devops/issues/93.
