### ISSUE TITLE
[UPGRADE] Minimum metadata format version for opensearch-keystore.

### ISSUE THREAD

**Issue by adnapibar** [opensearch-project/OpenSearch#468]
**Describe the bug**

The `opensearch-keystore` tool is currently failing to load and update older versions of keystores created using the `elasticsearch-keystore` tool.

This results in couple of failing tests for bwc and upgrade of the older versions of keystore files.

```
 - org.opensearch.common.settings.UpgradeKeyStoreCommandTests.testKeystoreUpgrade
 - org.opensearch.common.settings.KeyStoreWrapperTests.testLegacyV3
```

**To Reproduce**

Run `./gradlew :distribution:tools:keystore-cli:check`

**Expected behavior**

No test failures.

**Additional context**

Should we set the minimum supported version for `opensearch-keystore` to the current version (4) and remove the tests?

**Comment by nknize** [comment]
Fixed by #796
