### ISSUE TITLE
Supporting community contributed clients on OpenSearch

### ISSUE THREAD

**Issue by setiah** [opensearch-project/OpenSearch#473]
The community contributed clients for Elasticsearch may not directly work for OpenSearch due to the refactoring and namespace changes. This issue tracks the task to support some popular clients on OpenSearch. We look forward to active community participation in closing this gap.

**Comment by dblock** [comment]
This was a good idea, but we haven't used this issue as meta, so I'm going to close this. If anyone runs into an issue with any client, open a specific issue for that and we'll take a look! Most should work out of the box [in backwards-compatibility mode](https://opensearch.org/docs/clients/agents-and-ingestion-tools/index/).
