### ISSUE TITLE
[Weighted Shard Routing] Fail open weighed away AZ

### ISSUE THREAD

**Issue by anshu1106** [opensearch-project/OpenSearch#4735]
**Is your feature request related to a problem? Please describe.**
https://github.com/opensearch-project/OpenSearch/issues/2859 aims to support weighted shard routing policy. The search request at the coordinator performs a weighted round robin to route requests to shard copies. 

These weights are set by making PUT [API](https://github.com/opensearch-project/OpenSearch/issues/3639) call
```
PUT /_cluster/routing/awareness/<attribute>/weights
{ 
      "zone_1": "1", 
      "zone_2": "1", 
      "zone_3": "0"
}
```

Once the weights are set, the search request is tried on shard copies in weighed round robin manner.
Normally if search request on a shard copy fails, the request is retried on all remaining copies until it succeeds. In case a zone is weighed away by setting weighted routing weight to 0, the shard search request is not performed on shard copies present in that zone.

So in this case, if shard search request returns 5xx from all shard copies in non-weighed away zone, the response returned is 5xx even though there are shard copies in weighed away zone that can serve the request.

**Describe the solution you'd like**
In these scenarios we can fail open i.e. coordinator request for shard copies can go to nodes in weighed away zone. This helps in reducing the number of 5xx responses as well as better shard availability. In other case, where shard search requests return 4xx due to throttling from shard copies in non-weighed away zone, we don't need to fail open. So basically if the request fails due to internal issues in the cluster we fail open for search requests.

**Comment by anasalkouz** [comment]
Hi @anshu1106 , thanks for your suggestion, but based on my understanding, if a shard put in a weighted away zone, that was for purpose and this shard won't expect any search request. So, I don't think it make sense to route failed search request to this zone.

**Comment by anshu1106** [comment]
@anasalkouz , the search request gets routed to weighed away az only in cases there are 5xx returned from remaining azs ie there are no healthy shard copies to serve the request. Since write requests are sent to data nodes in weighed away az until they are decommissioned in case of AZ failures, we are expecting shard copies to be available. This will help in increasing the availability of cluster for read requests.

**Comment by saratvemulapalli** [comment]
@anshu1106 this is tagged 2.5, do you need any help getting this done?
Code freeze is tomorrow.

**Comment by anshu1106** [comment]
Thanks for checking. We were able to merge the changes today.

**Comment by kotwanikunal** [comment]
> Thanks for checking. We were able to merge the changes today.

@anshu1106 Can you please close the issue to mark it done?
