### ISSUE TITLE
[BUG] Exception in RestClient when Content-Encoding header is missing 

### ISSUE THREAD

**Issue by isabelleingato** [opensearch-project/OpenSearch#4736]
**Describe the bug**
Using OpenSearch sdk version 1.3.5 with an OpenSearch domain on v1.3, I am trying to use the `RestClient` to GET `/_ingest/pipeline/[id]` via the API `ingest().getPipeline()`. But an exception is thrown on this line https://github.com/opensearch-project/OpenSearch/blame/main/client/rest/src/main/java/org/opensearch/client/RestClient.java#L361 `.map(HttpEntity::getContentEncoding)`, due to `Content-Encoding` being null (although the response itself has 200 status). This occurs both with and without:`compressionEnabled(true)` and custom `RequestOptions` that add an `Accept-Encoding` header input to `ingest().getPipeline()`. This code was/is working with Elasticsearch Java High Level REST client v7.1.1.

Can a fallback be added in the code in case the `Content-Encoding` header is not present on a response?

**To Reproduce**
1. Create an OpenSearch domain v1.3
2. Set up OpenSearch RestClient v1.3.5
3. Create an ingest pipeline
4. Try to get the ingest pipeline config using the RestClient's `ingest().getPipeline()` with `RequestOptions.DEFAULT`
5. Observe exception

**Expected behavior**
Exception should not be thrown

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**
I am seeing a similar stack trace as reported in: https://forum.opensearch.org/t/we-are-facing-call-site-initialization-exception/10857.
https://opensearch.org/docs/1.3/opensearch/rest-api/ingest-apis/get-ingest/

**Comment by anasalkouz** [comment]
Is this issue exists in 2.x branch?

**Comment by isabelleingato** [comment]
The answer to https://github.com/aws/aws-sdk-java-v2/issues/652 resolved this for me. I had to upgrade org.apache.httpcomponents:httpcore to version 4.4.9.
