### ISSUE TITLE
How does opensearch perform in a update heavy use-case?

### ISSUE THREAD

**Issue by hiteshghia** [opensearch-project/OpenSearch#4752]
This is a question for which I could not find enough documentation/best practices. 
How does opensearch perform in a update heavy use-case. 
i.e store documents, update them daily with latest data and query them?
what are the performance implications? 
Is this is valid usecase for opensearch?

**Comment by andrross** [comment]
Hey @hiteshghia! First off, [the OpenSearch forum](https://forum.opensearch.org/) is probably the best place for this type of discussion. But to answer your question, OpenSearch can work well with update heavy use cases. As with anything performance related, the specifics of your workload will matter a lot. The best way to determine this is to setup a cluster and run experiments with data simulating your expected workload, and then measure the results. I hope this helps!
