### ISSUE TITLE
[BUG] Explicit maven group setting for pluginZip broke

### ISSUE THREAD

**Issue by prudhvigodithi** [opensearch-project/OpenSearch#4756]
**Describe the bug**
Coming from https://github.com/opensearch-project/OpenSearch/pull/4733#issuecomment-1276599104, with PR https://github.com/opensearch-project/OpenSearch/pull/4733 merge, the pluginZip functionality to choose the groupID `org.opensearch.plugin` broke.
1) The default groupID is not getting applied as `org.opensearch.plugin`.
2) If we add specifically the group = org.opensearch.plugin not only the zips but the jars are also being pushed to org.opensearch.plugin

**To Reproduce**
1) `/build.sh manifests/2.4.0/opensearch-2.4.0.yml --component OpenSearch`
2) `/build.sh manifests/2.4.0/opensearch-2.4.0.yml --component job-scheduler`

**Expected behavior**
When added group `org.opensearch.plugin` to `pluginZip` the other publications should not use this and vice versa.
The zips should be part of org.opensearch.plugin and jars should be part of org.opensearch group.

**Additional context**

**Comment by reta** [comment]
Ok, together with @prudhvigodithi we figured out, there is confusion regarding `group` and `groupId` settings, the `pluginZip` must set `groupId` (not `group`), otherwise it affects project's wide setting and overrides all publications
