### ISSUE TITLE
Create a new type of threadpool queue "SifiResizableBlockingQueue" to dynamically adjust write/search queue size in runtime.

### ISSUE THREAD

**Issue by rguo-aws** [opensearch-project/OpenSearch#476]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Create a new type of threadpool queue "SifiResizableBlockingQueue" to dynamically adjust write/search queue size in runtime. This would allow other plugin to adjust write/search queue without restarting the OpenSearch process

**Describe alternatives you've considered**
n/a

**Additional context**

**Comment by AmiStrn** [comment]
What is Sifi? "Save it forget it"? I'm a little rusty on some acronyms:)

**Comment by dblock** [comment]
Looks like this is implemented in https://github.com/opensearch-project/OpenSearch/pull/826

**Comment by anasalkouz** [comment]
Hi @rguo-aws, what is pending on this feature?

**Comment by anasalkouz** [comment]
Please feel free to re-open if there is pending work

**Comment by saratvemulapalli** [comment]
@reta assigned this to you as you've already picked up this work.
