### ISSUE TITLE
Add new threadpool executor with EWMA enabled

### ISSUE THREAD

**Issue by rguo-aws** [opensearch-project/OpenSearch#477]
**Is your feature request related to a problem? Please describe.**
The executor of our new SiFi resizable search queue is OpenSearchThreadPoolExecutor which unfortunately does not keep track of queueSize/EWMA execution time. 

**Describe the solution you'd like**
We should ideally Add EWMA enabled threadpool executor for search/write queue to keep track of EWMA time of each request.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by minalsha** [comment]
Could you please share what problem are we solving for OpenSearch with this issue? Is there a generic way to solve this issue for OpenSearch instead of just SiFi feature?

**Comment by anasalkouz** [comment]
Hi @rguo-aws, can you please look into this?

**Comment by anasalkouz** [comment]
Closing this issue, @rguo-aws feel free to reopen if this is still needed
