### ISSUE TITLE
[Zone Decommission] Recommision flow should set the weights back to the value prior to decommission value

### ISSUE THREAD

**Issue by pranikum** [opensearch-project/OpenSearch#4803]
**Is your feature request related to a problem? Please describe.**
As part of decommission request we set the weight of decommission awareness attribute to 0 and the other regions to 1.
Should recommission set the weights back or we should leave on the client to handle that. 

Based on comment: https://github.com/opensearch-project/OpenSearch/pull/4586#discussion_r995657247

**Describe the solution you'd like**
NA

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by imRishN** [comment]
This is not needed
