### ISSUE TITLE
[BUG] Rewriting querybuilders that require async actions fail

### ISSUE THREAD

**Issue by jmazanec15** [opensearch-project/OpenSearch#4814]
**Describe the bug**
Currently, it is possible in OpenSearch to register an asynchronous request in order to rewrite a querybuilder (see [QueryRewriteContext.registerAsyncAction](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/index/query/QueryRewriteContext.java#L113)). Internally, this makes its way to the static method [Rewriteable.rewriteAndFetch](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/index/query/Rewriteable.java#L102) where the pending asynchronous actions are executed and querybuilders are rewritten.

This functionality is used for query types like [AbstractGeometryQueryBuilder](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/index/query/AbstractGeometryQueryBuilder.java#L514), and a new query type I am helping to build ([NeuralQueryBuilder](https://github.com/jmazanec15/neural-search/blob/issue-14/src/main/java/org/opensearch/neuralsearch/plugin/query/NeuralQueryBuilder.java#L197)).

The problem is that in SearchSourceBuilder, RescoreBuilders [call Rewritable.rewrite](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/search/builder/SearchSourceBuilder.java#L1018) instead of Rewritable.rewriteAndFetch. Internally, this will continue to rewrite the queries inside the rescore context, but will never call the async actions. So, if the query should be rewritten until the async actions completes (in my case this is required), it will eventually throw a 500 saying there have been too many rewrite rounds:
```
curl -XPOST "localhost:9200/test-index/_search?pretty" -H 'Content-Type: application/json' -d'
{
  "query": {
    "match_all": {}
  },
  "rescore": {
    "window_size": 50,
    "query": {
      "rescore_query": {
        "script_score": {
          "query": {
            "neural": {
              "cool_field": {
                "query_text": "biggest land animal",
                "model_id": "Yr725oMBizWWjtGmFzhE",
                "k": 1000
              }
            }
          },
          "script": {
            "source": " 10.0 + 1"
          }
        }
      }
    }
  },
  "_source": []
}
'

{
  "error" : {
    "root_cause" : [
      {
        "type" : "illegal_state_exception",
        "reason" : "too many rewrite rounds, rewriteable might return new objects even if they are not rewritten"
      }
    ],
    "type" : "illegal_state_exception",
    "reason" : "too many rewrite rounds, rewriteable might return new objects even if they are not rewritten"
  },
  "status" : 500
}
```

**Expected behavior**
QueryBuilders can be rewritten with async actions when present in rescorers.

It seems there should be another method, rewriteAndFetch, that operates on lists, similar to [Rewriteable.rewrite](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/index/query/Rewriteable.java#L148).

**Plugins**
No plugins required, but I ran into error when:
1. opensearch-knn
2. opensearch-ml
3. opensearch-neuralsearch

**Comment by jmazanec15** [comment]
Actually, I believe I made a mistake in my querybuilder class. When the object does not change, I still return a copy, which will result in an error.

Instead, I should follow the geo builder and do:
```
        if (vectorSupplier()) {
            return vectorSupplier.get() != null ? new KNNQueryBuilder(fieldName(), vectorSupplier.get(), k()) : this;
        }

        if (vectorSupplier() == null) {
            SetOnce<float[]> vectorSetOnce = new SetOnce<>();
            queryRewriteContext.registerAsyncAction(
                ((client, actionListener) -> ML_CLIENT.inferenceSentence(modelId(), queryText(), ActionListener.wrap(floatList -> {
                    vectorSetOnce.set(vectorAsListToArray(floatList));
                    actionListener.onResponse(null);
                }, actionListener::onFailure)))
            );
            vectorSupplier(vectorSetOnce::get);

            return new NeuralQueryBuilder(fieldName(), queryText(), modelId(), k(), vectorSupplier());
        }

        return this;
```

**Comment by mattweber** [comment]
This is probably still an issue on a list of rewritables.  I am pretty sure I ran across the same issue with rewritable sort builders.
