### ISSUE TITLE
Edit github workflow to have a new workflow file for Windows trigger, on cron, on manual. It should have a new param to enter the platform of the test.

### ISSUE THREAD

**Issue by anasalkouz** [opensearch-project/OpenSearch#4815]
Right now the cron job is set to 0 0 * * * which will run at midnight UTC, which is 17:00 PDT. This can be modified on further discussion on how frequently and when we should run gradle check on windows. 
Additionally, the timeout value is 160 minutes for now. 

Opened a draft PR for the infra team to try it out in a Jenkins staging environment and make changes/iterations as needed.

**Comment by peterzhuamazon** [comment]
Close this as we dont plan to add gradle check windows to github yet.
