### ISSUE TITLE
[BUG] Failed Integ test testDecommissionStatusUpdatePublishedToAllNodes

### ISSUE THREAD

**Issue by imRishN** [opensearch-project/OpenSearch#4824]
**Describe the bug**
Test testDecommissionStatusUpdatePublishedToAllNodes fails after #4751 got merged.

**To Reproduce**
1. Run the integ test

**Expected behavior**
Test should pass

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**

**Comment by imRishN** [comment]
Closing as PR got merged

**Comment by dblock** [comment]
This failed again in https://github.com/opensearch-project/OpenSearch/pull/4912, reopening and marking as flaky.
