### ISSUE TITLE
Add Github action to ensure code coverage requirements are met

### ISSUE THREAD

**Issue by dreamer-89** [opensearch-project/OpenSearch#4844]
As part of this issue, we need to add a git action to ensure code coverage requirements are met without which PR merge is blocked. The [codecov integration](https://app.codecov.io/gh/opensearch-project/OpenSearch) is already done. The [codecov configuration](https://github.com/opensearch-project/OpenSearch/blob/main/codecov.yml) defines the config around code coverage. As part of this change, we need to add a job which ensures this configuration is honoured. 

#### Related
#850
#1320
https://docs.codecov.com/docs/codecov-yaml

**Comment by rblcoder** [comment]
Referring to https://docs.codecov.com/docs/commit-status, any further settings to be added for https://github.com/opensearch-project/OpenSearch/blob/main/codecov.yml?

**Comment by rblcoder** [comment]
@dreamer-89 Referring to https://docs.codecov.com/docs/commit-status, any further settings to be added for https://github.com/opensearch-project/OpenSearch/blob/main/codecov.yml?
Using similar codecov.yml, I see an error here https://github.com/rblcoder/daily_sleep_tracker/pull/9

**Comment by dreamer-89** [comment]
Thanks @rblcoder for the comment. Yes, there are no changes required. Closing this issue.
