### ISSUE TITLE
Cluster health should distinguish RED from "no master"

### ISSUE THREAD

**Issue by mgodwan** [opensearch-project/OpenSearch#485]
**Is your feature request related to a problem? Please describe.**
A RED cluster health means that there is either no master or else at least one primary is unassigned. However, since 7.0 there seems to be no simple way for clients to distinguish these two cases, and it would be useful to do so. For example:

a per-node health check should verify the node-level property of cluster membership, but may not be interested in the cluster-wide property of whether all the primaries are assigned.

an orchestrator may wish to wait for a freshly-started node to join a cluster before performing some followup actions, again without caring about whether all the primaries are assigned. Today this often happens by waiting for the HTTP port to be open, but this is unreliable: if no master is discovered within discovery.initial_state_timeout (default 30s) then we open the HTTP port anyway.

**Describe the solution you'd like**
Add an attribute in cluster health API response to denote if the master has been discovered or not. 
i.e. "discovered_master": true

**Describe alternatives you've considered**
Return a 503 when the master is not discovered but that may not communicate to the customer the reason due to which 503 is returned.

**Additional context**

Sample Response:

```
{
  "cluster_name" : "runTask",
  "status" : "green",
  "timed_out" : false,
  "number_of_nodes" : 1,
  "number_of_data_nodes" : 1,
  "discovered_master" : true,
  "active_primary_shards" : 0,
  "active_shards" : 0,
  "relocating_shards" : 0,
  "initializing_shards" : 0,
  "unassigned_shards" : 0,
  "delayed_unassigned_shards" : 0,
  "number_of_pending_tasks" : 0,
  "number_of_in_flight_fetch" : 0,
  "task_max_waiting_in_queue_millis" : 0,
  "active_shards_percent_as_number" : 100.0
}
```

**Comment by minalsha** [comment]
@mgodwan looks like this issue is closed by PR: https://github.com/opensearch-project/OpenSearch/pull/656. If thats not the case, please feel free to reopen this issue. Thanks
