### ISSUE TITLE
[BUG] Unexpected behaviour of auto_expand_replica setting when replica count is enforced

### ISSUE THREAD

**Issue by Arpit-Bandejiya** [opensearch-project/OpenSearch#4865]
**Describe the bug**
The bug was found when the following feature is enabled: https://github.com/opensearch-project/OpenSearch/pull/3462/files#diff-013717f93370bf1d9635d1b84aee81e7e003e3fd6c6bb7c74b9890a1327a04b6

There are two bugs that were found related to auto_expand_replica setting

1. The index creation is failing if auto_expand_replica setting is provided since it is validating for only `number_of_replicas` 

```
PUT _index_template/template_1
{
  "index_patterns": ["opensearch_dashboards_sample_data_ecommerce"],
  "template": {
    "settings": {
      "number_of_shards": 1,
      "auto_expand_replicas": "0-5"
    }
  },
  "priority": 1000
}
```
We will get the following validation error:

```
{
  "error" : {
    "root_cause" : [
      {
        "type" : "invalid_index_template_exception",
        "reason" : "index_template [template_1] invalid, cause [Validation Failed: 1: expected total copies needs to be a multiple of total awareness attributes [3];]"
      }
    ],
    "type" : "invalid_index_template_exception",
    "reason" : "index_template [template_1] invalid, cause [Validation Failed: 1: expected total copies needs to be a multiple of total awareness attributes [3];]"
  },
  "status" : 400
}
```

2. The auto_expand_replica setting takes precedence over the number_of_replica setting so we can use it to bypass the validation check

```
PUT /sample-index-6
{
  "settings": {
    "index": {
      "number_of_shards": 1,
      "number_of_replicas": 2,
      "auto_expand_replicas": "0-0"
    }
  },
  "mappings": {
    "properties": {
      "age": {
        "type": "integer"
      }
    }
  }
}
```
```
GET /sample-index-6/_settings

{
  "sample-index-6" : {
    "settings" : {
      "index" : {
        "number_of_shards" : "1",
        "auto_expand_replicas" : "0-0",
        "provided_name" : "sample-index-6",
        "creation_date" : "1666328942435",
        "number_of_replicas" : "0",
        "uuid" : "GxVFeFSOQBC3H2d2YtOFiQ",
        "version" : {
          "created" : "135248027"
        }
      }
    }
  }
}
```

**Comment by rockybean** [comment]
I think this is expected. As your max replica count is `5` and your `total awareness attributes ` value is `3` from the exception log.

And `5` is not multiple of `3`. 

right?

**Comment by Arpit-Bandejiya** [comment]
> I think this is expected. As your max replica count is `5` and your `total awareness attributes ` value is `3` from the exception log.
> 
> And `5` is not multiple of `3`.
> 
> right?

5(replica)+1(primary) will be checked in the validation. Therefore we expect it to pass.
