### ISSUE TITLE
[Enhancement]: Discuss the Node draining state feasiblity.

### ISSUE THREAD

**Issue by pranikum** [opensearch-project/OpenSearch#4866]
**Is your feature request related to a problem? Please describe.**
As part of Decommission request we have added DRAINING state having the exact state when the decommission process fails.
We can check if we need to have this state altogether.

**Describe the solution you'd like**
Remove the DRAINING state and use IN_PROGRESS

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by minalsha** [comment]
@pranikum  are you planning to contribute to this issue?

**Comment by pranikum** [comment]
Closing the issue. Have pushed the changes as part of 
https://github.com/opensearch-project/OpenSearch/pull/4586

**Comment by pranikum** [comment]
Closing the issue. Have pushed the changes as part of 
https://github.com/opensearch-project/OpenSearch/pull/4586

**Comment by pranikum** [comment]
Closing the issue. Have pushed the changes as part of 
https://github.com/opensearch-project/OpenSearch/pull/4586
