### ISSUE TITLE
[BUG] OperationRoutingTests.testWeightedOperationRoutingWeightUndefinedForOneZone failure

### ISSUE THREAD

**Issue by andrross** [opensearch-project/OpenSearch#4881]
Failure here: https://build.ci.opensearch.org/job/gradle-check/5293/

This test failure appears to be reproducible with the given seed:

```
./gradlew ':server:test' --tests "org.opensearch.cluster.routing.OperationRoutingTests.testWeightedOperationRoutingWeightUndefinedForOneZone" -Dtests.seed=B1745FEE14F29C02 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=ar-EG -Dtests.timezone=Asia/Magadan -Druntime.java=17
```

I haven't investigated at all but should be easily fixable given that it is deterministic.

**Comment by andrross** [comment]
Maybe not a one-off...another failure here: https://build.ci.opensearch.org/job/gradle-check/5299/

**Comment by iofit** [comment]
I've submitted https://github.com/opensearch-project/OpenSearch/pull/4980 as an attempt to fix this issue. I've observed that there are different behaviors when using java17 specially with those related to math,

**Comment by dblock** [comment]
https://github.com/opensearch-project/OpenSearch/pull/5241#issuecomment-1314323208

**Comment by dblock** [comment]
@anshu1106 looks like this was introduced in https://github.com/opensearch-project/OpenSearch/pull/4241, can you please take a look?

**Comment by anshu1106** [comment]
> @anshu1106 looks like this was introduced in #4241, can you please take a look?

Raise PR with the fix

**Comment by adnapibar** [comment]
Resolved by https://github.com/opensearch-project/OpenSearch/pull/5289
