### ISSUE TITLE
[BUG] Failures with org.opensearch.smoketest.SmokeTestMultiNodeClientYamlTestSuiteIT.test {yaml=search/30_limits/Regexp length limit}

### ISSUE THREAD

**Issue by kotwanikunal** [opensearch-project/OpenSearch#4899]
**Describe the bug**
- Test `org.opensearch.smoketest.SmokeTestMultiNodeClientYamlTestSuiteIT.test {yaml=search/30_limits/Regexp length limit}` is failing for an unrelated change

**To Reproduce**
Re run the test with the following seed -
```
 ./gradlew ':qa:smoke-test-multinode:integTest' --tests "org.opensearch.smoketest.SmokeTestMultiNodeClientYamlTestSuiteIT.test {yaml=search/30_limits/Regexp length limit}" -Dtests.seed=45E07907A235AA6A -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=es-HN -Dtests.timezone=SystemV/PST8PDT -Druntime.java=17
```

**Expected behavior**
- Test should pass

**Plugins**
- minimal build from forked repo

**Screenshots**

**Host/Environment (please complete the following information):**
 - OS: MacOS
 - Version 12.6

Also on the Jenkins server: https://build.ci.opensearch.org/job/gradle-check/5481/console

**Additional context**
- Using a random seed leads to success.

**Comment by dblock** [comment]
https://build.ci.opensearch.org/job/gradle-check/6767/
  https://build.ci.opensearch.org/job/gradle-check/6761/
  https://build.ci.opensearch.org/job/gradle-check/6740/
