### ISSUE TITLE
[BUG]400 Bad Request: {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Action/metadata line [1] contains an unknown parameter [_type]

### ISSUE THREAD

**Issue by 19914039** [opensearch-project/OpenSearch#4904]
Hello, team! I am trying to send cpu metrics from fluentbit to opensearch. Getting error:  [2022/10/25 16:10:07] [error] [output:opensearch:opensearch.0] HTTP status=400 URI=/_bulk, response:
{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Action/metadata line [1] contains an unknown parameter [_type]"}],"type":"illegal_argument_exception","reason":"Action/metadata line [1] contains an unknown parameter [_type]"},"status":400} (edited) 
[4:15](https://fluent-all.slack.com/archives/C0CTQGHKJ/p1666694721126419)
Fluentbit command is : ./fluent-bit -i cpu -t cpu -o opensearch -p Host=10.12.3.193 -p Port=9200 -p Index=my_index -m '*' -o stdout -m '*' -f 5 (edited) 
[4:18](https://fluent-all.slack.com/archives/C0CTQGHKJ/p1666694932354789)
I tried to configure the opensearch using "compatibility.override_main_response_version" : true; ref: https://github.com/opensearch-project/OpenSearch/issues/3484; still no use. I am getting the error. Please help me

**Comment by dblock** [comment]
This is a dup, see https://github.com/opensearch-project/OpenSearch/issues/4864#issuecomment-1287284114 for details and next steps.
