### ISSUE TITLE
[BUG] Java Heap Space Causing Gradle Check Failures

### ISSUE THREAD

**Issue by scrawfor99** [opensearch-project/OpenSearch#4907]
When testing a change to the feature/identity repo, I encountered an issue with the gradle check Jenkins process. After the check running for 17 minutes, the build fails with approximately 30 instances of the failure "Java heap space" presumably relating to the heap memory allocation. 

Full logs can be found here: https://build.ci.opensearch.org/job/gradle-check/5471/console

**To Reproduce**
1. Go to https://github.com/scrawfor99/OpenSearch/tree/feature/identity and clone the branch
2. Create a new PR for the new code
3. Wait for the automated processes to run on GitHub Actions 
4. Click the Jenkins link produced on failure
5. Check the Jenkins console output for errors once the gradle-check fails. 

**Expected behavior**
The check passes (or doesn't) regardless of memory allocation. 

**Screenshots**
Here is a screenshot of the bottom part of the gradle-check console: 
<img width="851" alt="Screen Shot 2022-10-25 at 9 51 04 AM" src="https://user-images.githubusercontent.com/65832608/197791717-1802283f-8133-4b1e-b6e4-9d3b2cf70587.png">

**Comment by reta** [comment]
This is interesting, suppossed to be fixed by https://github.com/opensearch-project/OpenSearch/issues/3973 but ... Gradle cache?

```
> Task :plugins:repository-azure:compileInternalClusterTestJava
Exception in thread "/127.0.0.1:35375 to /127.0.0.1:42646 workers Thread 4" java.lang.OutOfMemoryError: Java heap space
> Task :qa:multi-cluster-search:jarHell

> Task :plugins:analysis-icu:compileTestJava
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

> Task :distribution:docker:compileTestJava
> Task :modules:ingest-user-agent:forbiddenApisYamlRestTest FAILED
> Task :libs:opensearch-nio:compileTestJava
> Task :libs:opensearch-grok:forbiddenApisTest FAILED
Failed to execute org.gradle.cache.internal.AsyncCacheAccessDecoratedCache$$Lambda$415/0x0000000801034000@6112ffa9.
java.lang.OutOfMemoryError: Java heap space
```

**Comment by peternied** [comment]
We haven't merged from main in a little bit, will see if https://github.com/opensearch-project/OpenSearch/pull/4916 resolves this

**Comment by peternied** [comment]
@scrawfor99 Can you rebase and see if this issue is resolved?

**Comment by mch2** [comment]
Closing this as it seems to have been fixed.  @scrawfor99 Please re-open if you still hit this issue.
