### ISSUE TITLE
Decouple throttling limits for new and old indices

### ISSUE THREAD

**Issue by itiyamas** [opensearch-project/OpenSearch#491]
Is your feature request related to a problem? Please describe.

When there are a lot of relocations in the cluster e.g. as a result of zone outages, shards created for new index are starved till ongoing recoveries complete, leading to yellow index. The new index remains yellow for longer duration. This increases the potential of dataloss even with a single node outage.  

This happens because both new and existing shards share the same throttling limit, leading to starvation of new shards when old shards are being relocated.

This was originally submitted as a discuss to Elasticsearch.

Describe the solution you'd like
We would like to decouple throttling limits for old shards and new shards. This is because new shards are empty and can be allocated immediately. Because primaries are created empty, we don't need to add any limit for them. We will add a limit for replica shards because

1. We need a limit for replicas as replica assignment can be delayed due to any reason- e.g. total_shards_per_node is breached initially along with awareness constraints and hence replica does not get assigned initially. Replica gets assigned after there is a lot of data in primary once we remove total_shards_per_node on a rotated index. This will cause network bandwidth to be utilized even for new replicas and hence it is better to cap them.
2. The current capped number is set to 2 per node and will remain same for all shards. The reasoning here is that if replica assignment is cheap, it will go through quickly. 

Describe alternatives you've considered

A work around for this is to not rollover till the index becomes green. This is however difficult to control as an atomic operation and has to be added as an extra management feature.

Additional context

Elastic [discuss](https://discuss.elastic.co/t/new-indices-remain-yellow-when-there-are-relocations-in-the-cluster/215345)

**Comment by itiyamas** [comment]
Updating documentation is pending for the new setting.

**Comment by anasalkouz** [comment]
Hi @itiyamas, did you finish the documentation for the new setting? could please close the issue?

**Comment by anasalkouz** [comment]
Closing the issue, feel free to re-open if needed
