### ISSUE TITLE
Unsafe Bootstrap Command with user defined cluster wide read_only block setting

### ISSUE THREAD

**Issue by harmishlakhani** [opensearch-project/OpenSearch#492]
**Is your feature request related to a problem? Please describe.**
Sometimes Opensearch cluster faces quorum loss (half or more than half of master eligible nodes are lost). We have opensearch-node unsafe-bootstrap command which allow us to bootstrap cluster (but with some data loss). Many times Cx would not know about this data loss. One way to fix this is by restoring cluster from snapshot.

**Describe the solution you'd like**
During bootstraping cluster if we apply read only block to whole cluster (cluster.blocks.read_only) and give some kind of notification (quorum loss + unsafe-bootstrap), Cx can take appropriate actions from their side. No write request should execute successfully by any node of cluster after bootstrap to prevent data corruption (Atomicity of bootstrap + application of read only block). Cx can recover data by restoring cluster from snapshot in case any. To apply read only block after unsafe bootstrap is optional (default is false, but true is recommended).

**Describe alternatives you've considered**
opensearch-node unsfe-bootstrap command already has a warning message and confirmation before running the tool. This is just an extra layer of soft signal we can provide to prevent data loss.

**Additional context**

**Comment by shwetathareja** [comment]
> > Why should we provide read only block as part of unsafe bootstrap command? Can't you apply the setting externally from your orchestration system that sends out the notification as well?
> 
> Think about following race condition.
> 
> We want that settings to be in cluster immediately after bootstrap so that any node which joins newly formed cluster has that setting applied. Basically we want both operation "to apply read only block" and "bootstrap the cluster" in atomic way. Otherwise assume any node which joins cluster before applying read only block from external orchestration, can allow write request to cluster followed by application of read only block, can lead to data corruption for cx.
> 
> So best way to do this is applying settings before bootstrap, hence we should take this as arguments of unsafe-bootstrap command.

@harmishlakhani can you please update the description of the issue with these details as it is not clear why we want to introduce read_only block during unsafe-bootstrap
