### ISSUE TITLE
Timeout on cat/stats APIs

### ISSUE THREAD

**Issue by dhwanilpatel** [opensearch-project/OpenSearch#494]
### **Is your feature request related to a problem? Please describe.**
On few Stats/Cat API, master undefinetly waits for response from data nodes. If cluster have bad node and is not able to respond to master calls, then such API calls stays in master memory. Frequent calls of such API will cause **memory pile up on master**. 
We should make master resilient to such API calls when there is bad node in cluster.

Few APIs for which master gathers information from data nodes:
* /_cat/nodes
* /_cat/nodeattrs
* /_cat/thread_pool
* /_cat/allocation
* /_cat/recovery
* /_cat/plugins
* /_nodes
* /_stats

###  **Describe the solution you'd like**
We can add **timeout in communication between master and data nodes**. If timeout occurs and master don't get response from data nodes then it will just return the whatever response collected as API response and clear the memory in master.

###  **Describe alternatives you've considered**
None.

###  **Additional context**
As a next step of improvement, we should make the transport call as cancelable, so once master timeouts on data nodes then it will cancel the transport request so bad data node will also clear memory from their side. Otherwise it might worsen the situation on bad node.

Here our motive is to first make the master resilient, as memory pile up on master affects the availability/performance of whole cluster.

**Comment by dblock** [comment]
@dhwanilpatel This looks done as described in #552? Should we close or wait for #551?

**Comment by minalsha** [comment]
Closing since https://github.com/opensearch-project/OpenSearch/pull/495 is closed. Feel free to reopen if thats not the case.
