### ISSUE TITLE
[BUG] OpenSearch Persistent Task framework incorrectly cancels the running tasks

### ISSUE THREAD

**Issue by saikaranam-amazon** [opensearch-project/OpenSearch#4952]
**Describe the bug**
OpenSearch persistent task framework ensures tasks are in running state within the cluster. In case of node drops, these tasks are spun on other healthy nodes.This task framework has clean-up mechanism in-place to cancel the local running task which is not registered on the cluster state. In rare cases, after the node drops and joins the cluster with persistent task running on the node, the clean-up mechanism kicks-in on this node and cancel the running task. This cancellation mechanism works based on the `task_id` 

**To Reproduce**
1. Trigger persistent tasks and ensure that the tasks are in running state.
2. Identify the node(node1) running the persistent task.
3. Ensure OpenSearch process is still up on the node(node1) but induce any network failure to stop all connections to this node.
4. Wait for the cluster manager to mark the node(node1) as unhealthy and let the persistent task registered in step#1 run on new node(node2).
5. Let the node1 join the cluster again.
6. See that the task is in cancelled state.

**Expected behavior**
After the task is running on the healthy node, only stale entry on the old node should be cleaned-up with reason for cancellation

**Host/Environment (please complete the following information):**
 - OS: OS 1.2 (checked on this version and should be applicable on rest of the versions as well).

**Comment by andrross** [comment]
@saikaranam-amazon Have you attempted to write an integration test that deterministically reproduces the failure? That would be a great help to start making progress.

**Comment by saikaranam-amazon** [comment]
@andrross sure. i will work on providing fix for this issue.

**Comment by saikaranam-amazon** [comment]
Figured out a way to differentiate the active and stale tasks from the plugin side.
Closing this issue. If needed, will re-open this issue
