### ISSUE TITLE
[Searchable Snapshot] Finalize behavior of settings API

### ISSUE THREAD

**Issue by andrross** [opensearch-project/OpenSearch#4966]
Currently, searchable snapshots disallow all settings updates. I think we’ll need to be smarter here and allow some settings to be writable whereas others not. For example, most (all?) search-related settings (e.g. “index.max_result_window”) should be configurable, whereas all write-related settings should not be allowed to change (e.g. “index.refresh_interval”). This logic applies to both changing settings of an existing searchable snapshot index (e.g. PUT myindex/_settings) as well as when specifying the “settings” parameter when creating a searchable snapshot index via the restore API.

**Comment by adnapibar** [comment]
@andrross Do we have a list of settings which we would want to be updatable? Not sure if there is documentation on such (search/indexing) categorization?

**Comment by andrross** [comment]
There's no list. Part of this task is to figure it out :)

Looking at what AWS UltraWarm allows to be updated is probably a good place to start.
