### ISSUE TITLE
[Searchable Snapshot] Prevent deletion of snapshots that are backing searchable snapshot indexes

### ISSUE THREAD

**Issue by andrross** [opensearch-project/OpenSearch#4967]
The system is missing the protection to prevent a snapshot from being deleted if it is currently backing a searchable snapshot index. The desired behavior is that a user should delete all such indexes before deleting the snapshot is allowed.

**Comment by Vishalks** [comment]
I am working on this task.

**Comment by nandi-github** [comment]
Can we look into keeping a reference count of active backup in progress. If the count is non-zero both command line and Ux can prevent it from deletion.

**Comment by opencmit1** [comment]
A snapshot is a backup of data, and it can be restored to this cluster or other opensearch clusters. Therefore, deleting snapshots and deleting indexes should not be directly related.

**Comment by andrross** [comment]
@opencmit1 A searchable snapshot is a new feature under development. You can follow the progress in #2919 A searchable snapshot index uses a snapshot instance as its source of data and fetches the data on demand at search time. Deleting that snapshot would render the index inoperable, hence the desire to add this protection.

**Comment by andrross** [comment]
> Can we look into keeping a reference count of active backup in progress. If the count is non-zero both command line and Ux can prevent it from deletion.

@nandi-github Can you explain what "active backup in progress" means here?

**Comment by Vishalks** [comment]
@andrross I think what @nandi-github is referring to is the same as what we discussed earlier: If there is any index backed up by the remote snapshot, deny deletion using a reference count for such backed up indices. Eventual consistency in some of the repository implementations might lead to this approach being incorrect.

**Comment by nandi-github** [comment]
Do you need further clarification or it is good for now ?
