### ISSUE TITLE
[BUG] Missing spotless-lib-2.30.0.jar causing build failures

### ISSUE THREAD

**Issue by ketanv3** [opensearch-project/OpenSearch#4987]
**Describe the bug**
Gradle checks are failing due to a missing dependency JAR issue (404 error).

```
A problem occurred configuring root project 'OpenSearch'.
> Could not resolve all files for configuration ':classpath'.
   > Could not find spotless-lib-extra-2.30.0.jar (com.diffplug.spotless:spotless-lib-extra:2.30.0).
     Searched in the following locations:
         https://plugins.gradle.org/m2/com/diffplug/spotless/spotless-lib-extra/2.30.0/spotless-lib-extra-2.30.0.jar
   > Could not find spotless-lib-2.30.0.jar (com.diffplug.spotless:spotless-lib:2.30.0).
     Searched in the following locations:
         https://plugins.gradle.org/m2/com/diffplug/spotless/spotless-lib/2.30.0/spotless-lib-2.30.0.jar
```

It appears that the JAR has vanished from [this repo](https://repo.gradle.org/ui/native/jcenter/com/diffplug/spotless/spotless-lib/2.30.0/) for version 2.30.0, but is available for other versions.

Failed builds:
* https://build.ci.opensearch.org/job/gradle-check/5935/console
* https://build.ci.opensearch.org/job/gradle-check/5937/console

**To Reproduce**
Trigger Gradle checks via Jenkins.

**Expected behavior**
Dependencies should be found.

**Comment by VachaShah** [comment]
@ketanv3 I don't see this issue happening for gradle checks now. Are you still facing this issue?

**Comment by ketanv3** [comment]
This seems to be a transient issue that impacted all builds for a brief period yesterday. I'll go ahead and close this for now.
