### ISSUE TITLE
Establish procedure for putting migration development tools under source control

### ISSUE THREAD

**Issue by sumobrian** [opensearch-project/OpenSearch#5000]
There are tools that we the migrations team needs to create to assist with migration validations. These tools may not be ready for public consumption but I want to make sure that we keep them under version control. Given that this is an Open Source project we need to determine the right place for these tools and who should have access. 

* Should they be public from the beginning?
* Should they have criteria that moves them from private to public?

Review the "contributing to OpenSearch" documentation and if these questions are not answers open an issue tagging a technical lead within OpenSearch.

**Comment by sumobrian** [comment]
Request sent and pending approval for new migrations umbrella repo to store tools.

**Comment by dblock** [comment]
We're creating `opensearch-migrations`, a new repo. Let's close this issue here.
