### ISSUE TITLE
[Meta] Promote searchable snapshot out of experimental

### ISSUE THREAD

**Issue by andrross** [opensearch-project/OpenSearch#5087]
This is a meta task to track the work required to promote the searchable snapshot feature out from behind the experimental feature flag to a production ready feature.

- [x] #4964
- [x] #4965
- [x] #4966
- [x] #4967
- [x] #4968
- [x] #5217
- [x] #5218 
- [x] #5243
- [x] #5244
- [x] #5508 
- [x] #5981  
- [x] #6274

**Comment by anasalkouz** [comment]
Now, you can track the progress of Searchable Snapshots on this [board](https://github.com/orgs/opensearch-project/projects/55/views/1).
If you are interested and want to contribute, feel free to pick any of the pending task.
cc: @reta
