### ISSUE TITLE
[Optimization] TaskBatcher to use ConcurrentHashMap for batching tasks per executor

### ISSUE THREAD

**Issue by shwetathareja** [opensearch-project/OpenSearch#5099]
**Describe the bug**

In TaskBatcher.java, for batching it maintains a HashMap ```tasksPerBatchingKey``` and uses synchronized block to find duplicates using the batching key (which is based on task executor) and update the tasks for the given key. It can use ConcurrentHashMap instead which will only lock the segment and use computeIfPresent for computing updated tasks.

https://github.com/opensearch-project/OpenSearch/blob/082f0594582116713355ae00fe5ad001774a511d/server/src/main/java/org/opensearch/cluster/service/TaskBatcher.java#L97-L100

**Expected behavior**
The tasks belonging to different batchingKey can be submitted in parallel and will make submitTasks faster.

**Comment by amkhar** [comment]
This is closed as part of https://github.com/opensearch-project/OpenSearch/pull/5827
