### ISSUE TITLE
[BUG] testCoordinatingPrimaryThreadedUpdateToShardLimitsAndRejections is flaky

### ISSUE THREAD

**Issue by dblock** [opensearch-project/OpenSearch#5157]
**Describe the bug**

```
REPRODUCE WITH: ./gradlew ':server:test' --tests "org.opensearch.index.ShardIndexingPressureConcurrentExecutionTests.testCoordinatingPrimaryThreadedUpdateToShardLimitsAndRejections" -Dtests.seed=3AA0904AC11EAEA5 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=uk-UA -Dtests.timezone=America/Argentina/Jujuy -Druntime.java=19

org.opensearch.index.ShardIndexingPressureConcurrentExecutionTests > testCoordinatingPrimaryThreadedUpdateToShardLimitsAndRejections FAILED
    java.lang.AssertionError: expected null, but was:<org.opensearch.index.stats.IndexingPressurePerShardStats@3a0179b7>
        at __randomizedtesting.SeedInfo.seed([3AA0904AC11EAEA5:BC95A9DD94E04AA8]:0)
        at org.junit.Assert.fail(Assert.java:89)
        at org.junit.Assert.failNotNull(Assert.java:756)
        at org.junit.Assert.assertNull(Assert.java:738)
        at org.junit.Assert.assertNull(Assert.java:748)
        at org.opensearch.index.ShardIndexingPressureConcurrentExecutionTests.testCoordinatingPrimaryThreadedUpdateToShardLimitsAndRejections(ShardIndexingPressureConcurrentExecutionTests.java:274)
```

https://github.com/opensearch-project/OpenSearch/pull/5143

**Comment by andrross** [comment]
This is a very similar test and failure as mentioned in #4212. I suspect the fix will be the same for both. I'm capturing the notes I've collected on this so far below:

The test expects [`shardIndexingPressure.shardStats().getIndexingPressureShardStats(shardId1)` to return null](https://github.com/opensearch-project/OpenSearch/blob/e61fbacec340c15d4f85c5ba717a0075874e2809/server/src/test/java/org/opensearch/index/ShardIndexingPressureConcurrentExecutionTests.java#L332-L333).

In theory, [this close call](https://github.com/opensearch-project/OpenSearch/blob/e61fbacec340c15d4f85c5ba717a0075874e2809/server/src/test/java/org/opensearch/index/ShardIndexingPressureConcurrentExecutionTests.java#L324) should clean up everything being tracked and result in that assertion being true. The only suspect I have is that the close [conditionally cleans up](https://github.com/opensearch-project/OpenSearch/blob/7b75fb425f9df2b96049dac8c7dc13273f5026fd/server/src/main/java/org/opensearch/index/ShardIndexingPressure.java#L329-L330) the stats being tracked. I suspect there may be a race preventing the values getting to zero tested in that condition. I haven't figured out how that might be possible though.

**Comment by dblock** [comment]
https://build.ci.opensearch.org/job/gradle-check/6762/
  https://build.ci.opensearch.org/job/gradle-check/6761/
  https://build.ci.opensearch.org/job/gradle-check/6759/

**Comment by Rishikesh1159** [comment]
Similar to falky test : #4212 , test only fails when rejectionCount is equal to NUM_THREADS. Possible fix/workaround would be similar to this [comment](https://github.com/opensearch-project/OpenSearch/issues/4212#issuecomment-1325497657). Need @getsaurabh02 opinion on this to move forward with fix.

**Comment by getsaurabh02** [comment]
thanks @Rishikesh1159 . Could you pls check https://github.com/opensearch-project/OpenSearch/issues/4212#issuecomment-1335798199

**Comment by Rishikesh1159** [comment]
Closing this as #5439 is merged, which fixes the issue. Please feel free to reopen if this test fails again.
