### ISSUE TITLE
Task Cancellation Enhancement

### ISSUE THREAD

**Issue by Bukhtawar** [opensearch-project/OpenSearch#520]
**Is your feature request related to a problem? Please describe.**
The task cancellation results in a ban on child tasks and marking the task cancelled in the task manager, however if the child tasks continue to run without checking on the cancellation(it does so at some points) via `CancellableTask#isCancelled`, the list task API continues to show the task on the task manager without an indication of whether the task/child task was cancelled, though it might eventually fail/abort.

**Describe the solution you'd like**
The task manager needs to indicate if the task was cancelled from the point it was cancelled till the task completes and moves out of the task manager

**Describe alternatives you've considered**
None

**Additional context**

**Comment by anasalkouz** [comment]
Hi @Bukhtawar, are you actively working on this?

**Comment by meghasaik** [comment]
I will look into this.

**Comment by meghasaik** [comment]
Hi @Bukhtawar, Can you elaborate on more steps to reproduce this?

**Comment by Bukhtawar** [comment]
You could use one of the the TaskCancellation [integ tests](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/internalClusterTest/java/org/opensearch/action/admin/cluster/node/tasks/CancellableTasksIT.java#L97) in tandem with a [ScriptedBlockPlugin](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/internalClusterTest/java/org/opensearch/search/SearchCancellationIT.java#L122) to simulate a long-running task, trigger a cancellation and perform a list task API call to see that a previous running task is still running, which would eventually abort.

**Comment by kartg** [comment]
Related PR is closed. Closing this issue.
