### ISSUE TITLE
 Preventing increase in cluster pending tasks with number of shards during relocation

### ISSUE THREAD

**Issue by jainankitk** [opensearch-project/OpenSearch#521]
**Is your feature request related to a problem? Please describe.**

We have observed that during forced relocation on a cluster with high number of shards(7K), the shard-started event(relocation complete status update task) takes a huge amount of time to execute(close to 4 seconds). With more number of relocation going on in the system due to forced relocation- this causes an increase in the pending task queue resulting in timeouts of index creation and update mappings.

What causes the time taken for the task to increase to 4 seconds?
The OpenSearch relocation completion status update task iterates through all shards and takes a move and allocation decision for each one of them. The move decision and allocation decision is based on multiple factors: excluded ips, shard limit, number of allowed shard relocations per node etc. In a steady state during forced relocation, all nodes will be relocating maximum number of shards based on the throttling limit. All tasks are serialized at the master. Hence, once a relocation finishes, we might have to relocate only a single shard in steady state. There is no point of iterating through all shards in the cluster. Similarly, there is no point of iterating through shards of nodes that is not excluded as move happens from excluded nodes to non-excluded nodes. Also, there is no point of iterating through shards of nodes which already have maximum number of relocations going in parallel as we already know that a “DON’T MOVE” decision will be taken for all shards of that node.

The fundamental problem with this algorithm is the abstraction that is used to make allocation and move decision. We iterate through all shards and make a decision, while most of the decisions can be taken at a node level and all shards for that node can be skipped as ultimately a don’t move decision will anyway be taken for all shards of that node.

**Describe the solution you'd like**
We changed the abstraction to make allocation and move decision to node+shard rather than shard. Hence, if a node is not excluded - we do not iterate through any shard it has. Similarly, if a node is already throttled on maximum outgoing recoveries - we do not iterate through any more shards of that node. As a result, we reduced the number of shards being iterated to a very small value- 1-2 in most cases as opposed to number of shards in the cluster in the older algorithm.
Similarly, we changed the decision to rebalance to be decided at node+shard level instead of checking shard by shard.

From the code perspective,
we have basically added a new canRemain method for allocation deciders that returns decision at a node level rather than at a shard level. Nodes for which (canRemain returned true for all deciders)
or (if outgoing recoveries is equal to throttle limit- basically decision is THROTTLE for any decider) the node gets skipped.
We have added a canRemain method per node for FilterAllocationDecider and ThrottlingAllocationDecider

**Describe alternatives you've considered**
Some decisions can be taken at a cluster level like if total number of relocations happening in the cluster are equal to node incoming times number of included nodes or node outgoing recoveries times number of excluded nodes, we can skip the move shards decision.

**Additional context**
Steps to reproduce
We have a cluster with 7k shards spread over 100 data nodes. Now we wish to upgrade the cluster to a better data node configuration, for which we spin-up another 100 node cluster and exclude the IPs of older data nodes. This triggers relocation of the shards. Node incoming and outgoing recoveries is set to 6 and cluster concurrent rebalance is set to 10. The problem does not depend a lot on shard size but on number of shards in the cluster. We checked the time it takes for Allocation service method to execute both with and without the optimizations and we saw the time taken being reduced from a range of 1s-3.5s to 60ms.

**Comment by itiyamas** [comment]
Original stalled issue created with Elastic: https://github.com/elastic/elasticsearch/issues/27427

**Comment by jainankitk** [comment]
@setiah - I guess we can remove backport pending label?
