### ISSUE TITLE
[BUG] org.opensearch.cluster.coordination.AwarenessAttributeDecommissionIT/testInvariantsAndLogsOnDecommissionedNodes flaky

### ISSUE THREAD

**Issue by dblock** [opensearch-project/OpenSearch#5221]
org.opensearch.cluster.coordination.AwarenessAttributeDecommissionIT/testInvariantsAndLogsOnDecommissionedNodes

 - https://build.ci.opensearch.org/job/gradle-check/6792/
 - https://build.ci.opensearch.org/job/gradle-check/6738/
 - https://build.ci.opensearch.org/job/gradle-check/6825/

**Comment by kartg** [comment]
Closing since #5252 has been merged
