### ISSUE TITLE
Add API to check per awareness attribute value health.

### ISSUE THREAD

**Issue by nishchay21** [opensearch-project/OpenSearch#5230]
**Is your feature request related to a problem? Please describe.**
As of today opensearch only shows health for full cluster however health per awareness attribute is still not seen. We need an API today to monitor the cluster availability status per [awareness attribute](https://opensearch.org/docs/2.0/opensearch/cluster/#advanced-step-6-configure-shard-allocation-awareness-or-forced-awareness) (If this is configured Shard allocation awareness attempts to separate primary and replica shards across multiple awareness attribute values) as that would give use more information on how many shards are assigned per  awareness attribute value, how many nodes are distributes per awareness attribute value etc.

**Describe the solution you'd like**
Would like to get a single API that would help solve the above issue. A cluster can have multiple awareness attribute and getting the health per awareness attribute will be good. Following things can be shown per awareness attribute value  [e.g. rack as attribute]:
- Total number of nodes per rack
- Total shards per rack.
- Weights given per rack if defined.
- If "cluster.routing.allocation.awareness.balance" is enforced we can also predict the unassigned shards.

**Describe alternatives you've considered**
As of now no alternative is available. One have to call multiple API 's to formulate a total result which can cause inconsistency in result.

**Additional context**
The API can be considered to use the following paths:
[1] _cluster/awareness/{awareness_attribute}/health [create a new API path]
[2] _cluster/health/_awareness/{awareness_attribute} [use the same _cluster/health API]

The output could look similar to something like below where the first half would give the cluster level information and the second part would give the awareness attribute level information. We can pass the cluster awareness attribute to the path and have the cluster health information around it. 

```
{
  "cluster_name" : "runTask",
  "status" : "yellow",
  "number_of_nodes" : 2,
  "number_of_data_nodes" : 2,
  "discovered_cluster_manager" : true,
  "active_primary_shards" : 3,
  "active_shards" : 6,
  "relocating_shards" : 0,
  "initializing_shards" : 0,
  "unassigned_shards" : 6,
  "delayed_unassigned_shards" : 0,
  "number_of_pending_tasks" : 0,
  "number_of_in_flight_fetch" : 0,
  "task_max_waiting_in_queue_millis" : 0,
  "active_shards_percent_as_number" : 50.0,
  "<awareness_attribute_name>" : {
    "value_1" : {
      "active_shards" : 3,
      "initializing_shards" : 0,
      "relocating_shards" : 0,
      "unassigned_shards" : 3,
      "data_nodes" : 1,
      "weight" : 1.0
    },
    "value_2" : {
      "active_shards" : 3,
      "initializing_shards" : 0,
      "relocating_shards" : 0,
      "unassigned_shards" : 3,
      "data_nodes" : 1,
      "weight" : 1.0
    }
  }
}
```

**Comment by dblock** [comment]
I'd like to see the RESTful routes proposed.

- Does it make sense to extend the existing health API or is this going to be a new route?
- Does it make sense to support retrieving health per multiple awareness attributes in one query?

**Comment by nishchay21** [comment]
> Where can I read about awareness attributes? What are the examples of awareness attributes that are most used?
> 
> I'd like to see the RESTful routes proposed.
> 
>     * Does it make sense to extend the existing health API or is this going to be a new route?
> 
>     * Does it make sense to support retrieving health per multiple awareness attributes in one query?

Added the proposed paths to above issue.

**Comment by Bukhtawar** [comment]
I'd prefer 
1. `_cluster/health?level=awareness_attributes` : For retrieving health per multiple awareness attributes in one query
2. `_cluster/health?level=awareness_attributes&awareness_attribute=zone` : For retrieving health for a single awareness attribute

`level` is a pre-existing query param with `levels` supported as cluster, indices and shards

**Comment by saratvemulapalli** [comment]
@nishchay21 this is tagged 2.5. Are there any other changes to get this done? 
Code freeze is 1/10.

**Comment by gbbafna** [comment]
@saratvemulapalli  : The [PR](https://github.com/opensearch-project/OpenSearch/pull/5694) is near to completion . We will merge it and backport to 2.5 & 2.x today .
