### ISSUE TITLE
[BUG] Gradle check retry not working as expected

### ISSUE THREAD

**Issue by kotwanikunal** [opensearch-project/OpenSearch#5239]
**Describe the bug**
- As a part of https://github.com/opensearch-project/OpenSearch/issues/2547 and https://github.com/opensearch-project/OpenSearch/pull/2638/, a retry mechanism was introduced to rerun failed tests during `gradle check`
- With the increased flakiness in tests, one issue that was noticed is the retries do not always run for tests on the build server

Sample runs - 
- https://build.ci.opensearch.org/job/gradle-check/6825/consoleFull
- https://build.ci.opensearch.org/job/gradle-check/6782/

**To Reproduce**
1. Run gradle check for a PR with a test failure

**Expected behavior**
- Retries to be present within the console output with `x tests completed, y failed` with y > 1 in case of failed tests with a retry

**Plugins**
- N/A

**Screenshots**
- https://build.ci.opensearch.org/job/gradle-check/6825/consoleFull
- https://build.ci.opensearch.org/job/gradle-check/6782/

**Host/Environment (please complete the following information):**
- Jenkins build server for OpenSearch

**Additional context**
-  https://github.com/opensearch-project/OpenSearch/issues/2878

**Comment by andrross** [comment]
Just as an example, from [this test run](https://github.com/opensearch-project/OpenSearch/pull/2660#issuecomment-1088064862) back in April, if we drill into the report we can see 3 failures of the same test:

![Screen Shot 2022-11-14 at 10 28 04 AM](https://user-images.githubusercontent.com/9160839/201738338-82983c43-354a-48f1-a2ea-bf676a60963e.png)

But it succeeded on the 4 attempt so the overall test run is marked as successful. Not conclusive, but I have never seen an example of a test failing but succeeding on retry since we moved to the public Jenkins runner.

**Comment by andrross** [comment]
Ok, now I do have an example of a test succeeding after retry from just a few minutes ago: https://build.ci.opensearch.org/job/gradle-check/6876/testReport/org.opensearch.index/ShardIndexingPressureConcurrentExecutionTests/ You can see that the test `testCoordinatingPrimaryThreadedUpdateToShardLimitsAndRejections` failed twice but succeeded on the third attempt. You can also observe the retries in the console output. (The overall test failed for a different reason causing a test to fail 4 times).

**Comment by dblock** [comment]
I think this is working as expected. I'm closing this, unless someone can show an example where all retries failed and we still reported success.

**Comment by andrross** [comment]
> reopen if you can show an example where all retries failed and we still reported success

@dblock I think we have the opposite problem. The retries are working, but even when a test succeeds on retry we still fail the overall test run. [See here](https://build.ci.opensearch.org/job/gradle-check/6825/testReport/org.opensearch.cluster.coordination/AwarenessAttributeDecommissionIT/) for an example. `AwarenessAttributeDecommissionIT.testInvariantsAndLogsOnDecommissionedNodes` both failed and succeeded in the same run. Don't we expect the overall test result to be success in such a case?

**Comment by andrross** [comment]
Again looking at [6825](https://build.ci.opensearch.org/job/gradle-check/6825/console), we see the "BUILD SUCCESSFUL" result in the output (tests succeeded on retry):

```
BUILD SUCCESSFUL in 25m 35s
2626 actionable tasks: 2612 executed, 2 from cache, 12 up-to-date
...
Finished: UNSTABLE
```

The gradle check jenkins run completes with the result ["UNSTABLE"](https://github.com/opensearch-project/OpenSearch/pull/5225#issuecomment-1312288647) and results in a failure of the GitHub action. Is this the right behavior? I think the point of the retries is to pass the gradle check when tests pass on retry so this seems wrong to me.

**Comment by kotwanikunal** [comment]
I'll look at other `UNSTABLE` gradle checks to check if it's the same cause.

**Comment by dblock** [comment]
I think that if a retry succeeded, the build should be a SUCCESS.

**Comment by kotwanikunal** [comment]
Fix: https://github.com/opensearch-project/opensearch-build/pull/2902
