### ISSUE TITLE
[Remote Store] Support refresh level durability

### ISSUE THREAD

**Issue by sachinpkale** [opensearch-project/OpenSearch#5251]
**Is your feature request related to a problem? Please describe.**
- As part of [remote store feature](https://opensearch.org/docs/latest/opensearch/remote) that was introduced in OpenSearch 2.3, segments are uploaded to remote store post each refresh. 
- This means remote segment store contains segments that were part of last refresh.
- But the `_remotestore/_restore` API only supports commit level durability.
- This feature will add refresh level durability support to the restore API.

**Comment by sachinpkale** [comment]
Currently, I am thinking of using the same flow that segment replication uses when replica receives the publish checkpoint.

https://github.com/opensearch-project/OpenSearch/blob/b43e985fa6601a2b44d69a91b138a4462f15fde8/server/src/main/java/org/opensearch/index/store/Store.java#L869-L884

**Comment by mch2** [comment]
@sachinpkale Why do we need to support refresh level durability here? Could remote store use commit level durability until we implement remote store as the source of replication for segrep?  There is a lot of overlap here with that effor.
