### ISSUE TITLE
[Feature/extensions] Merge to main tracking -  Initial extensions framework

### ISSUE THREAD

**Issue by ryanbogan** [opensearch-project/OpenSearch#5264]
This is a tracking issue for the first merge of feature/extensions into main.

PR/Commit to Cherry-Pick:

- Commit ID: https://github.com/opensearch-project/OpenSearch/commit/be1a605479a8da1809e6d706abbd0b0e59dea16f

- https://github.com/opensearch-project/OpenSearch/pull/3830

This merge contains the following PR's in addition to the one above:

- https://github.com/opensearch-project/OpenSearch/pull/2796
- https://github.com/opensearch-project/OpenSearch/pull/3107
- https://github.com/opensearch-project/OpenSearch/pull/3173
- https://github.com/opensearch-project/OpenSearch/pull/3188
- https://github.com/opensearch-project/OpenSearch/pull/3366
- https://github.com/opensearch-project/OpenSearch/pull/3380
- https://github.com/opensearch-project/OpenSearch/pull/3381
- https://github.com/opensearch-project/OpenSearch/pull/3411
- https://github.com/opensearch-project/OpenSearch/pull/3449
- https://github.com/opensearch-project/OpenSearch/pull/3265
- https://github.com/opensearch-project/OpenSearch/pull/3721
- https://github.com/opensearch-project/OpenSearch/pull/3753
- https://github.com/opensearch-project/OpenSearch/pull/3750

**Comment by minalsha** [comment]
@ryanbogan can you add details on what each commit consists of?
