### ISSUE TITLE
[Feature/extensions] Merge to main tracking -  getSettings() support, ActionListener onFailure(), and initial createComponents support

### ISSUE THREAD

**Issue by ryanbogan** [opensearch-project/OpenSearch#5272]
This is a tracking issue for the third merge of feature/extensions into main.

PR/Commit to Cherry-Pick:
- Commit ID: b2ba1695f98ff64ff453571a0a36f2db774a5497
- https://github.com/opensearch-project/OpenSearch/pull/4553

This merge contains the following PR's in addition to the one above:

- https://github.com/opensearch-project/OpenSearch/pull/4430
- https://github.com/opensearch-project/OpenSearch/pull/4479
- https://github.com/opensearch-project/OpenSearch/pull/4191
- https://github.com/opensearch-project/OpenSearch/pull/4519
- https://github.com/opensearch-project/OpenSearch/pull/4517
- https://github.com/opensearch-project/OpenSearch/pull/4581

**Comment by minalsha** [comment]
@ryanbogan  can you add details on what each commit consists of?
