### ISSUE TITLE
[DISCUSS] Publish docker images to container registry.

### ISSUE THREAD

**Issue by adnapibar** [opensearch-project/OpenSearch#529]
Opened this issue to start a discussion on which container registries we should publish the OpenSearch docker images to. There are several options including Amazon ECR, Docker Hub (default and most popular), and GitHub Container Registry (public beta).  I would like to see community response on this.

Once we decide which one(or more), we can open separate issues to work on.

**Comment by Bonitas** [comment]
I prefer GitHub. The pull limit on Docker is unfortunatly really annoying. Also, I expect even better integration into the GitHub ecosystem.

**Comment by louwers** [comment]
Docker Hub for sure.

**Comment by davido** [comment]
Docker Hub to start with.

**Comment by aparo** [comment]
Docker Hub is the most common, but why don't publish it on different hosts?

**Comment by dgomesbr** [comment]
Public ECR for overcoming the Docker hub pull limits.

**Comment by DavidSpek** [comment]
Just stopping by to say that I would recommend against using the ECR public gallery. It is missing very many basic features for a public container registry, like viewing the digest hash in the UI or more importantly a publicly accessible endpoint to list the latest tags. See https://github.com/aws/containers-roadmap/issues/1262. 

This has already caused problems for using automation tools such as Renovate for parts of the Kubeflow project.

Dockerhub has a process for getting an exception for the pull limits for open source projects. https://www.docker.com/partners#formbelow

**Comment by ace03uec** [comment]
- Dockerhub should have a maintained copy, since it's the default for most projects.
- Pushes can be also be made to other registries for convenience. (Like rate limits etc)

**Comment by DavidSpek** [comment]
Just remember that ECR also has rate limits according to the announcement. 

“ Anyone who pulls images anonymously gets 500 GB of free data bandwidth each month after which they can sign up for or sign in to an AWS account. Simply authenticating with an AWS account increases free data bandwidth to 5 TB each month when pulling images from the internet.”
https://aws.amazon.com/about-aws/whats-new/2020/12/announcing-amazon-ecr-public-and-amazon-ecr-public-gallery/

**Comment by adnapibar** [comment]
Thanks everyone for taking part in the discussion. I agree that it's not a one vs other decision and we may eventually publish to multiple registries. However, the discussions do give us an idea where to focus our immediate efforts on and with the help of the community we will able to provide more options to our customers quickly afterwards.

**Comment by j-klemm** [comment]
Agree with @davido that Docker Hub makes sense in the short term. Although Amazon ECR will be helpful for those of us keeping things in the Amazon ecosystem.

**Comment by nelsonVE** [comment]
Docker Hub 100%

**Comment by umpa385** [comment]
agreed on docker hub, especially for alpha. Easy to spin up and test

**Comment by deepankarmalhan** [comment]
I would agree with Docker Hub to start with too since corporate environments night not to be set up to pull from GH or other registries and Docker Hub is a safe bet to start with.

**Comment by errazudin** [comment]
DH

**Comment by adnapibar** [comment]
https://hub.docker.com/r/opensearchproject/opensearch
