### ISSUE TITLE
[BUG] Bulk api silently ignores unknown operations

### ISSUE THREAD

**Issue by adnapibar** [opensearch-project/OpenSearch#5299]
**Describe the bug**

The bulk api supports the following actions: `create, delete, index, update`. However, if the request contains an invalid operation then it silently ignores it. 

**To Reproduce**

Given the following bulk request

```
{ "create" : { "_index" : "foo", "_id" : "1" } }
{ "id": "1", "field1" : "value1"}
{ "remove" : { "_index" : "foo", "_id" : "2" } }
{ "id": "2", "field1" : "value2"}

```
The `_bulk` api successfully returns

```
{
    "took": 1366,
    "errors": false,
    "items": [
        {
            "create": {
                "_index": "foo",
                "_id": "1",
                "_version": 1,
                "result": "created",
                "_shards": {
                    "total": 2,
                    "successful": 1,
                    "failed": 0
                },
                "_seq_no": 0,
                "_primary_term": 1,
                "status": 201
            }
        }
    ]
}
```

**Expected behavior**
The api call should fail resulting in a proper error message, something like

```
{
    "error": {
        "root_cause": [
            {
                "type": "illegal_argument_exception",
                "reason": "Unknown action line [3], expected one of [create, delete, index, update] but found [remove]"
            }
        ],
        "type": "illegal_argument_exception",
        "reason": "Unknown action line [3], expected one of [create, delete, index, update] but found [remove]"
    },
    "status": 400
}

```

**Host/Environment (please complete the following information):**
 - OS: macOS 
 - Version 12.6.1

**Additional context**
None

**Comment by andrross** [comment]
The API will report [partial failures](https://opensearch.org/docs/latest/api-reference/document-apis/bulk/#response) in other cases. This appears to fail the entire request in one item has an invalid action. Why the difference?

**Comment by adnapibar** [comment]
> The API will report [partial failures](https://opensearch.org/docs/latest/api-reference/document-apis/bulk/#response) in other cases. This appears to fail the entire request in one item has an invalid action. Why the difference?

This is invalid request, I don't think we should be processing this request at all. Partial failures happen for valid requests during indexing time.

**Comment by andrross** [comment]
What's the behavior if there is a line of malformed JSON or if a line omits the action all together? I think I agree that invalid requests should be rejected completely, but we should be consistent for all invalid cases.

**Comment by adnapibar** [comment]
> What's the behavior if there is a line of malformed JSON or if a line omits the action all together? I think I agree that invalid requests should be rejected completely, but we should be consistent for all invalid cases.

It rejects the request - https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/action/bulk/BulkRequestParser.java#L155-L273
