### ISSUE TITLE
elasticsearch-head cannot connect to OpenSearch

### ISSUE THREAD

**Issue by harold-wang** [opensearch-project/OpenSearch#53]
Popular elasticsearch App (https://github.com/mobz/elasticsearch-head) could not connect to OpenSearch.

I did not check other elasticsearch appliations yet, official Kibana also failed to connect due to xpact license issue. Not sure if this will affect all the elasticsearch App, will update with more findings.

**Comment by tlfeng** [comment]
I tested with the "Elasticsearch Head" [Chrome extension](https://github.com/mobz/elasticsearch-head#running-as-a-chrome-extension) and OpenSearch [1.0.0-beta1](https://github.com/opensearch-project/OpenSearch/releases/tag/1.0.0-beta1), 
OpenSearch can be connected, and elasticsearch-head looks working well.
<img width="894" alt="image" src="https://user-images.githubusercontent.com/78394866/117374240-a3612900-ae81-11eb-8932-b42b42ed08b5.png">

However, somehow the if running "elasticsearch-head" by the [built-in sever](https://github.com/mobz/elasticsearch-head#running-with-built-in-server), I didn't manage to connect OpenSearch, and even Elasticsearch.

**Comment by dblock** [comment]
> I also have the idea to having a new issue to collect all the compatibility issues for client applications designed for Elasticsearch.
> For the "elasticsearch-head", I didn't find issue when connecting with OpenSearch, but may need a testing plan to ensure.

If elasticsearch-head works now, we should close this issue. @tlfeng 

Every client is very different, so I would open separate issues. You can label them the same way if you want, maybe a new "client-compatibility" label?

**Comment by tlfeng** [comment]
Thanks dB for your opinion. That's a good idea, we can create the new label when there are more issues around the clients 😄.

**Comment by tlfeng** [comment]
When OpenSearch has got security plugin enabled, and require user credential for authentication, I didn't manage to make it connect with elasticsearch-head, so need more testing in this scenario.

**Comment by nknize** [comment]
@tlfeng do you want to take this one?  I'm going to bump to 1.1 given the 1.0 feature freeze

**Comment by tlfeng** [comment]
> @tlfeng do you want to take this one? I'm going to bump to 1.1 given the 1.0 feature freeze

Hi Nick, sure, I will test it based on OpenSearch 1.0.0.

**Comment by tlfeng** [comment]
Tested that "[Elasticsearch Head](https://github.com/mobz/elasticsearch-head#running-as-a-chrome-extension)" Chrome extension works with OpenSearch 1.0.0 [Minimal Distribution](https://opensearch.org/artifacts/opensearch/opensearch-1-0-0-min-linux-x64.html)

**Comment by dblock** [comment]
Should we close this then?

**Comment by dblock** [comment]
I think that's a problem with elasticsearch-head unfortunately, and someone/we should contribute a fix. Let's close this.
