### ISSUE TITLE
Create a community repo in the opensearch-project GH org

### ISSUE THREAD

**Issue by geekygirldawn** [opensearch-project/OpenSearch#532]
Since there is no good place to file an organization-wide GitHub issue, I'm putting it here :) 

Now would be a good time to create a separate “community” repo where you can put all of things that are common across both projects, like community meetings, governance, guiding principles, etc. Here’s a nice, simple [example from the Contour project](https://github.com/projectcontour/community).

I am happy to help with building out the content for this repo if someone is willing to create it!

**Comment by geekygirldawn** [comment]
@stockholmux Maybe this is something you could help me do?

**Comment by stockholmux** [comment]
@geekygirldawn First, I don't have the ability to create a new repo directly. It's a process (like everything). I have the ability kick the process off, but I don't have a button to click.

Secondly, I'm generally supportive. One blocker is that we had a community repo for Open Distro that was recently moved to become a [sample-code repo](https://github.com/opendistro-for-elasticsearch/sample-code). To be honest, I don't completely recall why we went from 'community'->'sample-code' on that one. I want to make sure there isn't something I'm missing on why we made the transition. @Jon-AtAWS, you commit frequently to that repo - do you have details on the transition?

In any case, from your example/description it doesn't seem to overlap much with that repo. 

A few things to clarify @geekygirldawn:
1) Would this contain any runnable-code? (e.g. vs just being markdown?)
2) Let's define each item you mentioned a little bit more (type of file / short description of content / frequency of change, etc)
- community meetings
- governance
- guiding principles

Any thoughts @nknize, @CEHENKLE, @spotaws?

**Comment by spotrh** [comment]
I don't think having a repo for "documentation that spans all of OpenSearch" is a bad thing, though, I do wonder if people who just go to a single OpenSearch subproject will think to look for it in a separate repo. I suppose pointing to it from all the subproject READMEs could work (but notably, Contour does not do this).

**Comment by spotaws** [comment]
Reposting from my aws account (too many accounts):

I don't think having a repo with docs that span the entire OpenSearch community is a bad idea, though, I do wonder if people visiting a specific OpenSearch project repo will think to look for a separate repo for community docs. We could point people there from all the READMEs, but Contour doesn't do that, as an example.

**Comment by nknize** [comment]
It would be great if the docs lived on opensearch.org (asciidoc, markdown, whatever) w/  concrete implementation in the project-website or separate {to_be_named} repo. 

Something [like this](https://lucene.apache.org/site-instructions.html)

**Comment by stockholmux** [comment]
@spotaws Good point. One thing I learned from Open Distro is that github orgs with lots of repos that move frequently are confusing for new folks. This will be the case once the Open Distro plugins get integrated into the same org. 

I'm wondering if a `start-here` repo  ([example](https://github.com/dwyl))might make sense? Pinned at the top of the org (along side `opensearch-project/OpenSearch` and `opensearch-project/OpenSearch-Dashboards`). This could house some of the same content that @geekygirldawn is suggesting along with a good README to orient first-time visitors.

**Comment by geekygirldawn** [comment]
Most of the projects that I contribute to have a community repo, so I do think it's something that people know to look for, and is pretty much a standard at this point. It's a great place to start defining roles and helping people understand how they can get involved and eventually move up in the project ([Contributor Ladder](https://github.com/cncf/sig-contributor-strategy/blob/master/contributor-growth/drafts/contributor-ladder.md)).

This is actually very different from a start-here repo. As the project grows, you will need something like a community repo as a home for all of the things that cut across the projects, so I would recommend doing it sooner, rather than later. We'll eventually need this to build out the governance along with all of the other things I mentioned earlier. Also, here are a few more examples: [Knative](https://github.com/knative/community), [Kubernetes](https://github.com/kubernetes/community), [Istio](https://github.com/istio/community).

**Comment by geekygirldawn** [comment]
> A few things to clarify @geekygirldawn:
> 
> 1. Would this contain any runnable-code? (e.g. vs just being markdown?)
> 2. Let's define each item you mentioned a little bit more (type of file / short description of content / frequency of change, etc)
> 
> * community meetings
> * governance
> * guiding principles

I'd recommend that this be just markdown, not runnable code. All of these will change frequently in the first few months as the community grows and you start to build out all of these things with the community's help.

I think the best way to visualize this is through examples, and use the best of what works for other projects. 

This is a [good example of a meeting schedule](https://github.com/projectcontour/community/blob/main/MEETING_SCHEDULE.md). It has the timing details, how to join, meeting notes, and recordings if you miss a meeting and want to catch up. This is a much lower barrier to entry than needing to join a Meetup Group and rsvp for each meeting to get the details.

Here are a couple of governance examples. [Harbor's governance doc](https://github.com/goharbor/community/blob/master/GOVERNANCE.md) is a fairly simple example, and something similar would work as a starting point for this community.

The Guiding Principles right now are duplicated into the READMEs of all of your repos, and it would be nice to have them here in one place.

**Comment by geekygirldawn** [comment]
@jcgraybill said ...

> What we learned from the Open Distro community repo, and the reason we converted it into a sample-code repo, was that in practice it caused confusion, especially for newcomers. The active community discussion was happening in the forums, and the repo siphoned off some of that energy. Newcomers would ask questions, propose features, or ask for support - and generally get no response or a super delayed response, which was a bad experience.

I've not seen this issue in other communities that I've been a part of. Generally, one of the first things in the community repo README should be details about communications and where to go for discussions, which in this case would be the forums.

**Comment by stockholmux** [comment]
@geekygirldawn OK. Personally, I don't have any problems with the content of what is being proposed. I do think there is some value in having the principles duplicated on each README though (for visibility).

Prior to launch the team decided that the website was the [holder of the canonical principles copy](https://github.com/opensearch-project/project-website/blob/main/_data/principles.yml) (although it doesn't have to stay this way).

On run-able code, this does change how I would propose the repo and what would be required on my end. Of the examples given it looks like both kubernetes and knative have embedded golang. So, I'd like 'no code' to be a hard line should it go forward.

**Comment by spotaws** [comment]
I think "no code" is fine for a community documentation repo.

**Comment by geekygirldawn** [comment]
@stockholmux said ... 

> On run-able code, this does change how I would propose the repo and what would be required on my end. Of the examples given it looks like both kubernetes and knative have embedded golang. So, I'd like 'no code' to be a hard line should it go forward.

I think most of the runnable code in those repos is for automation of various tasks, which isn't something we'd need. I think a no-code policy in this repo makes total sense.

**Comment by jcgraybill** [comment]
It looks like a lot of the docs we're talking about hosting in a community repo are thing we'd want to also make available on the website. Governance docs, SOPs, meeting schedules, principles & tenets. If we use the [project website](https://github.com/opensearch-project/project-website) as their home, it seems like we get both: easy to edit & discuss, and easy to read.

**Comment by nknize** [comment]
> If we use the [project website](https://github.com/opensearch-project/project-website) as their home, it seems like we get both: easy to edit & discuss, and easy to read.

:100:  Something [like this](https://lucene.apache.org/site-instructions.html)


Also, there is a wealth of good developers that sparsely visit forums for various reasons. :raised_hand_with_fingers_splayed:   I'm often "guilty" of this and have to be pinged to weigh in on implementation questions or bugs. My personal reasoning (whether right or wrong) is that the code lives in the repo and I like to live where the code is so I can make as educated comments as possible based on actual implementation. Bouncing between tools (repo, issues, PR, forum, website) to do the same gets to be exhausting and I'm convinced my fingers only have a certain number of keystrokes in them before they lock up for life :laughing:

**Comment by geekygirldawn** [comment]
I think it's important to think about the difference between building a community of users (which OpenDistro has done) and building a community of contributors, which is what I'm hoping we'll do here. Users tend to go to the website and forums. Contributors tend to live in the repo and expect to find things there. It's 2 completely different audiences and 2 different communities, and we need to meet the needs of both of them with information where they will find it.

**Comment by stockholmux** [comment]
I'm less convinced that `project-website` should be merged with this effort. As a new person approaches the repo, it could be quite confusing to see all the required Jekyll stuff.

The other issue is the change model - the website repo should be able to change rapidly with pretty light weight reviews. Changes to documents like governance or principles are the opposite - almost never changing and changes should be reviewed carefully. 

I'm all for removing this type of content from the website repo and pull it in from the proposed repo to build the site (so we're not repeating ourselves & have a single point of truth).

**Comment by jcgraybill** [comment]
> I think it's important to think about the difference between building a community of users (which OpenDistro has done) and building a community of contributors, which is what I'm hoping we'll do here. Users tend to go to the website and forums. Contributors tend to live in the repo and expect to find things there. It's 2 completely different audiences and 2 different communities, and we need to meet the needs of both of them separately with information where they will find it.

Great point. I'd expect that especially in the early days while these communities are coming together, there's probably going to be considerable overlap between the two. I'd love to not rush into drawing boundaries and pushing people who could happily exist as both-contributors-and-users for a good long period of time into choosing a side, or optimizing for one group at the expense of the other. Have you seen good practices out there for early-stage projects like this?

I'm thinking, for example, about community meeting announcements and agendas. Everybody is welcome at the community meetings. Do we announce those on GitHub only? On the website only? Neither feels great to me. What's a good practice for reaching both audiences equally - as well as the folks who wear both hats?

**Comment by nknize** [comment]
> I think it's important to think about the difference between building a community of users (which OpenDistro has done) and building a community of contributors

100%!  I'm curious how having that info in a markdown or asciidoc on a repo that's also referenced by the website does not technically achieve that? IMHO, it feels like the best of both worlds. Contributors can reference it in the repo and users can reference that same doc (w/ CSS sugar) on the website?

Like Jules I'm very curious what other seamless approaches are taken by other orgs and communities.

**Comment by geekygirldawn** [comment]
My focus is more on the contributor side than on users, so I mostly care about what we have in the repo, since that tends to be the focus for contributors.

With that said, I think pulling some of content from the community repo onto the website might make sense for some common items, but this should be done a bit carefully. Knative has been pulling all of the content from the community repo to display on the website, but they are in the process of changing this because as the project grows, it's become problematic in a few ways. To quote the person (Evan Anderson) who is driving this change:
* It adds complexity to our website build.
* My mental model is that contributors are generally viewing our content through GitHub, and mostly aren’t thinking about website rendering in community.
* Avoids community breaking the website by accident (see elekto recently) 

Even if we pull some pages onto the website, it will drastically simplify things if we only allow markdown files in the community repo, and then use the website infra to pull that markdown content into the website.

**Comment by geekygirldawn** [comment]
@stockholmux There has been a lot of discussion on this issue, so I think we ultimately need to decide whether to create the community repo or close the issue?

**Comment by dblock** [comment]
FWIW we created https://github.com/opensearch-project/OpenSearch-plugins for all things plugins to avoid polluting this repository with general plugin-related content and questions. Not sure that it was the right thing to do, but we will learn over time. 

I personally feel that if I had a "general OpenSearch issue" I'd probably open it here since this repository is called ... OpenSearch. 

Don't feel strongly either way.

Agreed with @geekygirldawn that @stockholmux should decide one way or another.

**Comment by stockholmux** [comment]
Actually, I'm not seeing alignment here - I'm seeing a lot of ideas. 

The original problem (a canonical place to put non-repo specific files) seems valid but it doesn't _have_ to be solved by a `opensearch-project/community` repo. I think @jcgraybill's point about duplication between opensearch.org and the proposed repo is real. The key here is how do we create the highest visibility w/o duplication, while still not gating access/contributions/etc.

My gut says we might want to get feedback from a larger group on where they would seek this information out and work towards what the feedback tells us.

**Comment by geekygirldawn** [comment]
@stockholmux  I'd be happy to work with you on drafting a couple of short survey questions that we could send out via the forums or other channels! Should we do this as something quick and standalone on just this topic or as part of something bigger that includes other topics, too? Does the forum have a built-in survey / polling mechanism?

**Comment by stockholmux** [comment]
@geekygirldawn Let's do it. I know there was talk about a more comprehensive survey, but I'd opt for single use in this case (the more focused, the less bogged down it'll get). The forums do have a survey mechanism, but I think it has some limits. I've setup a [topic on the forum to discuss](https://discuss.opendistrocommunity.dev/t/meta-community-survey/5756).

**Comment by dblock** [comment]
Regarding the original issue that asked for a community repo, I think https://opensearch.org/ is where content such as community meetings should go - and in fact they do, [here](https://opensearch.org/events/). It would make things double clear that that repo is the info on the org if the repo itself were to be called opensearch.org (https://github.com/opensearch-project/project-website/issues/44).

**Comment by stockholmux** [comment]
I think with the expansion of project-website/opensearch.org, we can classify this issue as stale.

**Comment by dblock** [comment]
I'm going to close this because I think we answered the original ask: community type content should go into project-website and technical content in .github.
