### ISSUE TITLE
Fix gradle check on 1.3/1.x

### ISSUE THREAD

**Issue by Poojita-Raj** [opensearch-project/OpenSearch#5324]
These are the failures in 1.x and 1.3 branch from the latest CI runs on windows -

- [x] InternalDistributionArchiveCheckPluginFuncTest. fails on unexpected notice content
- [x] InternalDistributionArchiveCheckPluginFuncTest. plain class files in distribution tar archives are detected
- [x] InternalDistributionArchiveSetupPluginFuncTest. registered distribution provides archives and directory variant

**Comment by minalsha** [comment]
@Poojita-Raj  what is pending on this issue?
