### ISSUE TITLE
Docs for OpenSearch?

### ISSUE THREAD

**Issue by davidshtian** [opensearch-project/OpenSearch#533]
**Is your feature request related to a problem? Please describe.**
Yes, I believe users need to have docs to guide them install, configure and tune OpenSearch.

**Describe the solution you'd like**
Docs for users to read.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by stockholmux** [comment]
@davidshtian I know there are folks working on this type of documentation and more. Let me ask you this:

What's the priority for you as far as docs? Is it just install/configure/tune?

**Comment by davidshtian** [comment]
> @davidshtian I know there are folks working on this type of documentation and more. Let me ask you this:
> 
> What's the priority for you as far as docs? Is it just install/configure/tune?

Thanks for the reply~ For docs, it would be better to have at least _install - configure - management - tuning_ covered.

**Comment by CEHENKLE** [comment]
@davidshtian  As of today we've put out the first version of the docs site: https://docs-beta.opensearch.org/  Let us know what you think, and feel free to [contribute changes](https://github.com/opensearch-project/documentation-website) if you find things that could be better.  :)

**Comment by davidshtian** [comment]
> @davidshtian As of today we've put out the first version of the docs site: https://docs-beta.opensearch.org/ Let us know what [you think](https://github.com/opensearch-project/documentation-website/issues), and feel free to [contribute changes](https://github.com/opensearch-project/documentation-website) if you find things that could be better. :)

Cool! Thanks so much~

**Comment by lukas-vlcek** [comment]
@CEHENKLE It would be very useful if OpenSearch version is part of the documentation URL.

**Comment by CEHENKLE** [comment]
@lukas-vlcek Totally agree.  I know we want to have the version (and language) in the URL, but we're ready to go with that, so that's why we put it into doc-beta for now.  @aetter @stockholmux would know more :)

**Comment by stockholmux** [comment]
@lukas-vlcek Yup. I believe the intention is to have `/docs/<lang-code>/<major-minor-version>`. This is one reason the beta-docs are on a subdomain and don't hang on the opensearch.org primary structure yet.

**Comment by lukas-vlcek** [comment]
That is great. Just one comment on this. I think it should be in reverse order, version first, lang second. Also it would be practical if the second parameter can be missing (the lang) in which case it would default to EN.

**Comment by dblock** [comment]
With https://opensearch.org/docs/ I am going to close this. I did open https://github.com/opensearch-project/documentation-website/issues/103 for versioning which doesn't seem like what we did here.
