### ISSUE TITLE
Maintainer areas of responsibility

### ISSUE THREAD

**Issue by geekygirldawn** [opensearch-project/OpenSearch#537]
It would be great if we could also add people's areas of responsibilities to the new [MAINTAINERS file](https://github.com/opensearch-project/OpenSearch/blob/main/MAINTAINERS.md). This helps people understand which of these maintainers is responsible for a particular area. We could add this as a new column to the existing table or as a separate section of the file. I'm happy to do if someone wanted to let me know which people are responsible for what.

Here's an [example](https://github.com/goharbor/community/blob/master/MAINTAINERS.md)

**Comment by geekygirldawn** [comment]
@CEHENKLE - Maybe this is something that you could help me with?

**Comment by nknize** [comment]
This is interesting. What's the motivation? I can see the natural human desire to classify "typical duties" to understand and maybe communicate a complex community dynamic but I'm curious the unintended consequences of imposing these types of labels or "job jar" classifications on contributors (or potential and flyby contributors). My "area of expertise" is spatial indexing and analysis. Does that mean the community doesn't want me poking around relevancy and scoring, or BM25? Probably not? Or maybe; and I'm just naive? I can't help but think, though, if the Lucene project had this unintended stove-piping (even at an informal level) how many BKD and tessellation PRs might not have received contributions from some of those amazing developers that do not consider themselves spatial indexing members, experts, knowledgeable. Above and beyond all I think we want to make sure we're doing everything we can to be extremely open and welcoming, keep the perceived bar to contribute very low, and maintain a large diversity of thought.

**Comment by getsaurabh02** [comment]
I agree with @nknize idea of not classifying experts or area owners. However, at the same time we should also think of how to increase traction of maintainers on PR which let's say is already reviewed by a fellow reviewer, and is awaiting merge. Pinging/tagging on the PR is one option, but is again debatable. Else should we have more explicit labels/tags classifying a feature/area to help maintainers or reviewers focus on specific set of issues/PR by choice. 

Another thought is around the readiness of a PR before merge. For example, once the reviewer has approved, should we automate `gradlew check` and rather not wait for maintainer's manual trigger. It can save cycles on the iteration here I believe.

**Comment by nknize** [comment]
> once the reviewer has approved, should we automate `gradlew check` and rather not wait for maintainer's manual trigger

I really truly hope so! For now the way the automated tooling is set up makes this a bit tricky. Then there's the added headache of requiring gradle check for simple PRs like documentation changes. Under the automation approach, a 40 minute CI job will be kicked off when a maintainer approves a spelling correction in README. :man_facepalming: 

In the meantime, contributors have to wait for a small pool of maintainers to comment on the PR to kick off that job. That's a bad time.

**Comment by geekygirldawn** [comment]
> This is interesting. What's the motivation? I can see the natural human desire to classify "typical duties" to understand and maybe communicate a complex community dynamic but I'm curious the unintended consequences of imposing these types of labels or "job jar" classifications on contributors (or potential and flyby contributors). My "area of expertise" is spatial indexing and analysis. Does that mean the community doesn't want me poking around relevancy and scoring, or BM25? Probably not? Or maybe; and I'm just naive? I can't help but think, though, if the Lucene project had this unintended stove-piping (even at an informal level) how many BKD and tessellation PRs might not have received contributions from some of those amazing developers that do not consider themselves spatial indexing members, experts, knowledgeable. Above and beyond all I think we want to make sure we're doing everything we can to be extremely open and welcoming, keep the perceived bar to contribute very low, and maintain a large diversity of thought.

@nknize I think maybe we're talking about 2 different things. I'm definitely not talking about putting people into "job jars" or "stove-piping". The motivation for my suggestion is to help the rest of us outside of Amazon better understand the maintainers and what they are likely to be working on. The key here is likely and not exclusively. Having a bit more info helps the rest of us:
* understand who to talk to if we need to escalate a PR if gets neglected for a long time or if something urgent comes up.
* learn about potential gaps that we could fill - maybe no one from Amazon is focused in a particular area that one of us has expertise in.
* we're all individuals interacting with each other, and if I know a bit more about the people in leadership positions, it can help the rest of us understand where you're coming from.

**Comment by geekygirldawn** [comment]
There was a bit of discussion, but no decision on this one, so I wanted to check in to see if this is something that we are going to do? If not, we should close the issue.

**Comment by CEHENKLE** [comment]
Hey @geekygirldawn Sorry I lost this thread for a bit.  

The thing I've been chewing on here is helping maintainers define what it is they're doing and how they do it.  I'm thinking of it less as "Bob does X and Alice does Y", but more "Maintainers do X, and here's how they think about doing it and/or actually, tactically do it".   

So that might answer some of your question (I think?  Maybe?), but it wouldn't help with "who are these folks and what, specifically, are they working on?"  There are so few of us that we haven't really started to specialize yet beyond repos (folks who are working on Dashboards/OpenSearch/Plugins), so at least for as while we'll be all over the place :)   As folk start to naturally gravitate towards areas (like, for example,  @setiah into security), I'm encouraging them to write blog posts describing their journeys.  Would that help? 

Thanks,
/C

**Comment by CEHENKLE** [comment]
> > once the reviewer has approved, should we automate `gradlew check` and rather not wait for maintainer's manual trigger
> 
> I really truly hope so! For now the way the automated tooling is set up makes this a bit tricky. Then there's the added headache of requiring gradle check for simple PRs like documentation changes. Under the automation approach, a 40 minute CI job will be kicked off when a maintainer approves a spelling correction in README. 🤦‍♂️
> 
> In the meantime, contributors have to wait for a small pool of maintainers to comment on the PR to kick off that job. That's a bad time.

yeah, there's some back and forth about whether it's a [bug or a feature](https://github.com/opensearch-project/OpenSearch/issues/597), but I think everybody agrees it's bad, and we don't like it at all.

**Comment by dblock** [comment]
I was independently trying to PR something related in https://github.com/opensearch-project/.github/pull/11 to distinguish between admins and maintainers. I think it's a non-controversial start and I believe we could use the `.github` repo for project-wide versions of that and link them from the opensearch.org website.

**Comment by dblock** [comment]
As asked, a first draft of maintainer responsibilities have been spelled out in https://github.com/opensearch-project/.github/blob/main/MAINTAINERS.md.
