### ISSUE TITLE
Add an API to collect metrics only for a subset of indices

### ISSUE THREAD

**Issue by tntruong723** [opensearch-project/OpenSearch#5380]
**Is your feature request related to a problem? Please describe.**
The volume of metrics to be handled increases when the number of indices increases.

**Describe the solution you'd like**
Add an API to collect metrics only for a subset of indices.

**Describe alternatives you've considered**

**Additional context**
I've found that in IndicesStatsResponse class when getIndices is invoked, all IndicesStats are returned. That leads to the volume of metrics to be handled increasing when the number of indices increases.
So I think we need to have the option to collect metrics only for a subset of indices.
It will be great if the fix is applied from version 1.3.2

Reference: https://github.com/opensearch-project/OpenSearch/blob/1.3.2/server/src/main/java/org/opensearch/action/admin/indices/stats/IndicesStatsResponse.java

**Comment by adnapibar** [comment]
Have you tried using a comma separated indices in the url? e.g. `/index1,index2/_stats`

**Comment by andrross** [comment]
I'm going to close this as I believe this functionality exists, as described by @adnapibar above. Please reopen if the existing APIs don't work for your use case.

**Comment by tntruong723** [comment]
@adnapibar Thanks. But actually, I need an API for Prometheus to collect metrics. You can see lines 100-119 in org.opensearch.action.admin.indices.stats.IndicesStatsResponse.java (1.3.2), when getIndices is invoked, it returns index stats for all indices.
So in case, I have many indices (such as logstash-*, alarms-*, mylog-*, kibana-*, task-* ...), the load of index stats increases. But I only want to collect metrics for a subset of indices such as alarms-*, mylog-*

**Comment by andrross** [comment]
> But I only want to collect metrics for a subset of indices such as alarms*, mylog*

You can achieve that by invoking the API with the desired index patterns specified as parameters, e.g. `GET /alarms*,mylog*/_stats`.

**Comment by tntruong723** [comment]
@andrross Thank you so much.
I sent `GET /alarms*,mylog*/_stats`, and it returned metrics from expected indices.
Then I looked at the OpenSearch source code and found that I could use the indices method from IndicesStatsRequest class for filtering.
`https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/rest/action/admin/indices/RestIndicesStatsAction.java
    indicesStatsRequest.indices(Strings.splitStringByCommaToArray(request.param("index")));`
So apply it for Prometheus Exporter Plugin.
