### ISSUE TITLE
 Windows CI support: Add unit tests only to the PR gate - start with buildTools only.

### ISSUE THREAD

**Issue by minalsha** [opensearch-project/OpenSearch#5400]
**Is your feature request related to a problem? Please describe.**
coming from #1448  wherein goal is to add unit tests only to the PR gate,  start with buildTools only for Windows.

**Comment by minalsha** [comment]
@mch2  do we need do any work for this issue?

**Comment by mch2** [comment]
I think we should close this issue.  Few if any these test suites are able to run on GH as a gate, and provide little value.  We should instead move the entire check on PR from Jenkins.
