### ISSUE TITLE
Spring Data for ElasticSearch support /   collaboration

### ISSUE THREAD

**Issue by jvmlet** [opensearch-project/OpenSearch#542]
Hello
What are OpenSearch team plans with  respect to  [SpringData for ElasticSearch]( https://github.com/spring-projects/spring-data-elasticsearch) support ? 
Would you be interested in supporting smooth integration by  contributing  directly to  the repo/ forking it/ designing common abstraction over ES and OS  with DATA ES team ? ([back reference](https://github.com/spring-projects/spring-data-elasticsearch/issues/1770 ))

**Comment by CEHENKLE** [comment]
@jvmlet Hey, thanks for bringing this up.  It seems like an amazing project..  Right now, we've got our hands full getting OpenSearch to General Availability, but I'd absolutely love to see someone else in the community run with it.  If someone else wants to tackle it, we would be happy to review PRs and generally provide consultation.

You also might want to put up a forum post (https://discuss.opendistrocommunity.dev/c/forking-elasticsearch-kibana/50) to get more visibility on the topic.

Thanks,
/C
