### ISSUE TITLE
[BUG] Index is being created as string instead of JSON

### ISSUE THREAD

**Issue by Dinakar4323** [opensearch-project/OpenSearch#5422]
**Describe the bug**
I reported the bug here https://forum.opensearch.org/t/updating-creating-index-using-high-level-java-client/11649

**To Reproduce**
Code snipped provided in the link above

**Expected behavior**
index should have json instead of string with double quotes

**Plugins**
Please list all plugins currently enabled.

**Screenshots**
added the sample output in the link

**Host/Environment (please complete the following information):**
 - OS: Windows and Linux
 - This bug is independent of OS

**Additional context**

**Comment by owaiskazi19** [comment]
@Dinakar4323 thanks for opening up this issue. Looks like there's a slight confusion here. The XContentType provides a generic abstraction on top of handling content, inspired by JSON and pull parsing. It comes with 4 [types](https://github.com/opensearch-project/OpenSearch/blob/main/libs/x-content/src/main/java/org/opensearch/common/xcontent/XContentType.java#L46) JSON, SMILE, YAML and COBR for XContent to understand how do we want to typecast the data. The string passed basically allows an index to a typed JSON document.
Even for XContentType.YAML type we pass string like:
```
Source("value: [ 2, 3 ]", XContentType.YAML)
```
I hope this answers your question.

**Comment by Dinakar4323** [comment]
Thanks for your response. I am trying to insert a json ---({\n "uuid": "123456",\n "status": "S",\n "comments": "Test record only"}--- to the index with root element as record in the following index as mentioned in the example, is there any alternate way to achieve it?
current output
{
“_index”: “record_index”,
“_type”: “_doc”,
“_id”: “123456”,
“_version”: 1,
“_score”: 0,
“_source”: {
“record”: “{\n "uuid": "123456",\n "status": "S",\n "comments": "Test record only"}”
}

expected output
{
“_index”: “record_index”,
“_type”: “_doc”,
“_id”: “123456”,
“_version”: 1,
“_score”: 0,
“_source”: {
“record”: {\n "uuid": "123456",\n "status": "S",\n "comments": "Test record only"}
}

**Comment by owaiskazi19** [comment]
@reta @andrross any idea for the above?

**Comment by reta** [comment]
@Dinakar4323 the way your are using the payload (as a Map<String, String>) is not going to work:

```
	HashMap<String, String> stringMapping = new HashMap<String, String>();
		
		stringMapping.put("record", json);
```

Instead please try to send the "record" as map (not as a string):

```
	Map<String, Object> record= new HashMap<String, Object>();	
        record.put("uuid", "123456");
        ...

	Map<String, Object> stringMapping = new HashMap<String, Object>();	
	stringMapping.put("record", record);
```

**Comment by Dinakar4323** [comment]
Thanks, for your response, is there a way to update part of an existing index with json?
For eg:
Current index
{
“_index”: “record_index”,
“_type”: “_doc”,
“_id”: “123456”,
“_version”: 1,
“_score”: 0,
“_source”: {
“record”: “{\n “uuid”: “123456”,\n “status”: “S”,\n “comments”: “Test record only”}”
}
}

update it to
{
“_index”: “record_index”,
“_type”: “_doc”,
“_id”: “123456”,
“_version”: 1,
“_score”: 0,
“_source”: {
“record”: “XYZ”
}
}

where XYZ is a json

something like this
XContentBuilder jb = XContentFactory.jsonBuilder();
jb.startObject().field(“record”, XYZ).endObject();

**Comment by reta** [comment]
@Dinakar4323 please check Update APIs: https://opensearch.org/docs/1.0/opensearch/rest-api/document-apis/update-document/
