### ISSUE TITLE
[BUG]  org.opensearch.http.SearchRestCancellationIT.testAutomaticCancellationDuringFetchPhase flaky

### ISSUE THREAD

**Issue by dblock** [opensearch-project/OpenSearch#5426]
https://github.com/opensearch-project/OpenSearch/pull/4587#issuecomment-1332837125

**Comment by dbwiddis** [comment]
```
REPRODUCE WITH: ./gradlew ':qa:smoke-test-http:integTest' --tests "org.opensearch.http.SearchRestCancellationIT.testAutomaticCancellationDuringFetchPhase" -Dtests.seed=DC332A722C0FD5DF -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=ar-SY -Dtests.timezone=SystemV/HST10 -Druntime.java=19
```
Suspect this requires flushing to clear pending commits similar to #5655.  Will attempt the same fix.

**Comment by dbwiddis** [comment]
Both failing test runs (7167,7463) had node failures.  The test failures may be a random symptom.

**Comment by dbwiddis** [comment]
Ran test 500 times, no repro.

**Comment by ashking94** [comment]
https://github.com/opensearch-project/OpenSearch/pull/6262#issuecomment-1423787039

**Comment by Gankris96** [comment]
I also see [org.opensearch.http.SearchRestCancellationIT.testAutomaticCancellationDuringQueryPhase](https://build.ci.opensearch.org/job/gradle-check/29691/testReport/junit/org.opensearch.http/SearchRestCancellationIT/testAutomaticCancellationDuringQueryPhase/) in this same test suite SearchRestCancellationIT is also flaky

**Comment by reta** [comment]
Closing in favour of https://github.com/opensearch-project/OpenSearch/issues/14311
