### ISSUE TITLE
Getting Started

### ISSUE THREAD

**Issue by ruanwenjun** [opensearch-project/OpenSearch#544]
Hi, is there any document about how to get started with OpenSearch. Specifically, how can I deploy, thanks.

**Comment by jkowall** [comment]
Hello @ruanwenjun try looking at the dev guide https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md 

There will be a packaged build soon, but for now you must build OpenSearch and OpenSearch Dashboards yourself.

**Comment by jkowall** [comment]
You can assign to me, or just close this as we've fixed this in #549 thx!

**Comment by ruanwenjun** [comment]
@jkowall Cool
