### ISSUE TITLE
[Proposal] Enable searchable snapshots to read legacy versions

### ISSUE THREAD

**Issue by kartg** [opensearch-project/OpenSearch#5451]
**Is your feature request related to a problem? Please describe.**
Expand [searchable snapshots](https://opensearch.org/docs/latest/opensearch/snapshots/searchable_snapshot/) to support read-only access to snapshots written by legacy versions. This would be useful to customers storing data for long periods of time (and thereby across major version upgrades) for log analysis or audit use-cases.

**Describe the solution you'd like**
Leverage Lucene 9's ability to [read older versions](https://github.com/apache/lucene/commit/c1ae6dc07c9a988533cbe7176bdeb49e2fca1d9c) to expand backwards compatibility for searchable snapshots to allow reading older snapshots.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by dblock** [comment]
What is considered "legacy" @kartg in 1.x, 2.x, and 3.x?

**Comment by kartg** [comment]
> What is considered "legacy" @kartg in 1.x, 2.x, and 3.x?

@dblock IMO a "legacy" version is any version older than OpenSearch's standard backwards compatibility guarantee (one prior major version). So:
* For `3.x`, OpenSearch 1.x (or ElasticSearch 7.10.2) and lower versions are considered legacy
* For `2.x` -> ElasticSearch 6.x and lower
* For `1.x` -> ElasticSearch 5.x and lower

I think these should also have a lower bound, but I don't have a value in mind at this time. For example, the implementation in [my fork](https://github.com/kartg/OpenSearch/tree/2x-backwardCompat) does not currently work for ElasticSearch 5.x snapshots, but I believe I can get it to function.

**Comment by kartg** [comment]
PR - https://github.com/opensearch-project/OpenSearch/pull/5429

**Comment by kartg** [comment]
PR to `main` - #5812
