### ISSUE TITLE
[Remote Store] Add upload timestamp to metada file to be used in conflict resolution

### ISSUE THREAD

**Issue by sachinpkale** [opensearch-project/OpenSearch#5475]
**Is your feature request related to a problem? Please describe.**
- Currently, we store metadata file in the remote store with: `metadata__<Primary Term>__<Generation>__<UUID>`. 
- Primary term and generation are used to compare 2 metadata files and to get the latest one. 
- But in some cases like primary - primary recovery, primary term and generation will be same. 
- For this, we use UUID based comparison to have random but consistent way of resolving conflicts.
- As we are adding support for refresh level durability, it is important to get the latest uploaded metadata file.
- We can't just add timestamp in the filename as it will result in too many metadata files. 
- The initial approach we are thinking of is to add timestamp info in the contents of metadata file.

**Comment by sachinpkale** [comment]
Moving to 2.7.0

**Comment by DarshitChanpura** [comment]
Hey @sachinpkale This issue will be marked for next-release `v2.8.0` on (Apr 17) as that is the [code-freeze](https://opensearch.org/releases.html) date for `v2.7.0`. Please let me know if otherwise.

**Comment by sachinpkale** [comment]
This is not required anymore
