### ISSUE TITLE
Expose matching fields and scores in the search response

### ISSUE THREAD

**Issue by ngadkari** [opensearch-project/OpenSearch#5487]
Related to Similar Ask on Elastic Search backlog: https://github.com/elastic/elasticsearch/issues/54335

Could not find a similar issue so opening this feature request.

Along with the search response, provide a list of document fields which caused each document to match the query.

This is a useful ML (Machine Learning) feature for training models used for e.g. ranking search results.

Additional features, which would be really useful in ML model training, would be textual match scores, such as:

Term Frequency (TF) and separately Inverse Document Frequency (IDF) as described [here](https://en.wikipedia.org/wiki/Tf%E2%80%93idf).
Best Match 25 (BM25) as described [here](https://opensourceconnections.com/blog/2015/10/16/bm25-the-next-generation-of-lucene-relevation/).
No concrete response format is required, as long as all of the above are present in the search response and it's possible to correlate the documents, matching fields and match scores

**Comment by msfroh** [comment]
@ngadkari  -- Would the [explain](https://opensearch.org/docs/latest/api-reference/explain/) API do what you're looking for?

**Comment by msfroh** [comment]
Closing this pending further information. @ngadkari - please feel free to reopen if the explain API doesn't do what you need. Thanks!

**Comment by Dharin-shah** [comment]
@msfroh Explain is inefficient if fired with each query, it would be nice to get this as meta information without explicit explain.
