### ISSUE TITLE
[BUG] Gradle task `:wrapper` fails with org.gradle.util.DistributionLocator deprecated

### ISSUE THREAD

**Issue by DarshitChanpura** [opensearch-project/OpenSearch#5494]
*NOT URGENT, but should be looked into at some point*

**Describe the bug**
[Wrapper task](https://github.com/opensearch-project/OpenSearch/blob/main/build.gradle#L532) to update gradle version fails with `The org.gradle.util.DistributionLocator type has been deprecated`.

```
> Task :wrapper
The org.gradle.util.DistributionLocator type has been deprecated. This is scheduled to be removed in Gradle 9.0. Consult the upgrading guide for further information: https://docs.gradle.org/7.6/userguide/upgrading_version_7.html#org_gradle_util_reports_deprecations
        at build_4d0q822uef9ladyhg6p6yk3ft$_run_closure17$_closure85.doCall(.../OpenSearch/build.gradle:535)
        (Run with --stacktrace to get the full stack trace of this deprecation warning.)
Added checksum to wrapper properties
Updated minimum Gradle Version

FAILURE: Build failed with an exception.

* Where:
Build file '.../OpenSearch/build.gradle' line: 535

* What went wrong:
Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0
```

**To Reproduce**
Run `./gradlew  wrapper --gradle-version 7.6 --distribution-type all`

**Expected behavior**
Task should be successful.

**Host/Environment (please complete the following information):**
 - OS: `main` as of commit: ce25dec

**Comment by minalsha** [comment]
This needs an upgraded Gradle verion 8. We are presently on 7.6 Gradle version.
