### ISSUE TITLE
Cancellable transport calls to data node for Cat/Stats API.

### ISSUE THREAD

**Issue by dhwanilpatel** [opensearch-project/OpenSearch#551]
### **Is your feature request related to a problem? Please describe.**
On few Stats/Cat API, master collects data from the data nodes. If there is bad node in cluster and if it is not able to respond to this master calls, then this calls will be piled up on data node. Now data node was already in bad shape and was not able to respond to master node calls, then such pile up calls from this Stats/Cat API will worsen the situation on data node. 

We need to make such calls as cancellable transport calls. As part of #494  we have introduced the timeout between master/data node communications. Master will not wait for data node response after timeout. Master should cancel this calls so it wont pile up on bad node.

### **Describe the solution you'd like**
Make transport calls between data node and master node as cancellable for Stats/Cat API where master is no longer waiting for data node's response.

**Comment by minalsha** [comment]
@dhwanilpatel Are these 2 issues related: https://github.com/opensearch-project/OpenSearch/issues/551 and https://github.com/opensearch-project/OpenSearch/issues/494? If so, could you please share details on how.

**Comment by anasalkouz** [comment]
Hi @dhwanilpatel, seems this issue already addressed into #494. Closing the issue, please feel free to reopen incase anything still missing.
