### ISSUE TITLE
[BUG] Opensearch 2.3 400 Bad Request: {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Action/metadata line [1] contains an unknown parameter [_type]

### ISSUE THREAD

**Issue by ahmednassar** [opensearch-project/OpenSearch#5516]
**Describe the bug**
I'm getting the below error with AWS `opensearch_2.3`, I tried to follow the fix in [BUG](https://github.com/opensearch-project/OpenSearch/issues/3484) but it does not work.

I confirmed the `override_main_response_version` as shown below,

```
aws opensearch describe-domain-config --domain-name opensearch-domain-1|grep override_main_response_version
                "override_main_response_version": "true",

```

**Comment by dblock** [comment]
The `type` parameter has been removed in OpenSearch 2.0. See https://opensearch.org/docs/2.0/breaking-changes/ and https://github.com/opensearch-project/opensearch/issues/1940. I'll close this issue, but happy to help if you're still stuck - 
 what are you using to write data (it needs to be compatible with OpenSearch 2.x)?

**Comment by lehmat** [comment]
Hi @dblock

I encountered the same error while following AWS guide to send cloudwatch logs to opensearch (on different account with VPC peering) [HERE](https://aws.amazon.com/premiumsupport/knowledge-center/opensearch-stream-data-cloudwatch/)

It seems the "default" lambda that you delpoy directly from cloudwatch subscription filter (UI generated) holds the `_type` which breaks it:

![image](https://user-images.githubusercontent.com/31982442/207538106-b9a82084-e69c-4368-8e60-1c9f2cd3f9ee.png)

**Comment by dblock** [comment]
Thank @lehmat, I'll try to track this down. If you haven't opened a customer support ticket with AWS you should. They have a path to track all this stuff too.
