### ISSUE TITLE
Provide ZIP for repository-s3 plugin

### ISSUE THREAD

**Issue by Snoopy2077** [opensearch-project/OpenSearch#5525]
Unfortunately we cannot install the repository-s3 plugin currently (unless I missed something)

Neither on our build pipelines nor on the container itself do we have internet access, which means
We can't install through Maven because it doesn't support mirrors (which we don't have)
We can't install by name because again, no connectivity
We can't install by zip because we didn't find the zip hosted anywhere

Any suggestions on how to resolve this?

**Comment by Snoopy2077** [comment]
found a way buried in some other issue ;)

**Comment by dblock** [comment]
Link for the next person @Snoopy2077 ?
