### ISSUE TITLE
[BUG] Cannot run OpenSearch "A problem occurred evaluating project ':benchmarks'." 

### ISSUE THREAD

**Issue by jkowall** [opensearch-project/OpenSearch#554]
**Describe the bug**
The gradle run process is not working. I have tried on clean installations of Ubuntu 20.04.02 and 20.10

**To Reproduce**
1. Install ubuntu version
2. apt install git openfdk-14-jre
3. git clone https://github.com/opensearch-project/OpenSearch.git
4. ./gradlew --stacktrace run 
 (works as expected, downloaded Gradle 6.6.1)

```
FAILURE: Build failed with an exception.

* Where:
Build file '/home/jkowall/opensearch/OpenSearch/benchmarks/build.gradle' line: 40

* What went wrong:
A problem occurred evaluating project ':benchmarks'.
> Could not create task ':benchmarks:test'.
   > Cannot set maxParallelForks to a value less than 1.

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.GradleScriptException: A problem occurred evaluating project ':benchmarks'.
        at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:93)
        at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl.lambda$apply$0(DefaultScriptPluginFactory.java:133)
        at org.gradle.configuration.ProjectScriptTarget.addConfiguration(ProjectScriptTarget.java:77)
```

**Expected behavior**
Expected compile and run to work

**Host/Environment (please complete the following information):**
 - OS: Ubuntu 20.04.02 and 20.10

**Comment by adnapibar** [comment]
@jkowall How many CPUs have you got on that machine?

**Comment by jkowall** [comment]
@adnapibar Changed the VM to use 2 CPUs and all is working. Probably should add that to requirements if we think that's necessary. 

Let me know, I can submit a PR.

**Comment by rmuir** [comment]
This happens to me as well on real hardware (2 cores, 4 threads). Its definitely a bug in the build. I work around it by adding `-Ptests.jvms=4`. Super strange since i already have that exact line specified in `~/.gradle/gradle.properties`...

**Comment by jkowall** [comment]
When I changed my VM to 2 CPUs it worked fine.
