### ISSUE TITLE
[BUG] AUTO PRs for version increments don't sign DCO

### ISSUE THREAD

**Issue by dblock** [opensearch-project/OpenSearch#5562]
These AUTO PRs failed DCO.

https://github.com/opensearch-project/OpenSearch/pull/5558
https://github.com/opensearch-project/OpenSearch/pull/5559
https://github.com/opensearch-project/OpenSearch/pull/5560

Manually fixed them with:

```
git checkout [branch]
git commit -s --amend
git push origin [branch] -f
```

**Expected behavior**
Auto PRs to sign DCO.

**Comment by rblcoder** [comment]
[version.yml](https://github.com/opensearch-project/OpenSearch/blob/main/.github/workflows/version.yml) has signoff: true
Not sure what I am missing here.
Do we need to create an issue here https://github.com/peter-evans/create-pull-request?

**Comment by rblcoder** [comment]
@dblock [version.yml](https://github.com/opensearch-project/OpenSearch/blob/main/.github/workflows/version.yml) has signoff: true
Shall I create an issue here https://github.com/peter-evans/create-pull-request?

**Comment by dblock** [comment]
This is very old. We have since stopped using the DCO workflow and are using the GH app to check DCO. Closing.
