### ISSUE TITLE
[Remote Store] Segment Replication checkpoint publication to sync with remote store upload

### ISSUE THREAD

**Issue by sachinpkale** [opensearch-project/OpenSearch#5578]
**Is your feature request related to a problem? Please describe.**
As part of https://github.com/opensearch-project/OpenSearch/issues/4555, once we integrate remote segment store with segment replication, we need to sync the refresh listeners of segment replication checkpoint publish and remote segment store upload.

This issue is created based on the comment: https://github.com/opensearch-project/OpenSearch/pull/5253#discussion_r1047545058

**Comment by ankitkala** [comment]
PR for the change: https://github.com/opensearch-project/OpenSearch/pull/7394
