### ISSUE TITLE
Allow extension of core index setting for plugins

### ISSUE THREAD

**Issue by martin-gaievski** [opensearch-project/OpenSearch#5609]
**Is your feature request related to a problem? Please describe.**
Currently the expected way for index settings overrides/extensions is via index settings. If such change is required for existing index then manual manipulations with settings/indices are required (like close/update/open or reindex to a new index with updated index setting). In addition to that, it can be a time-consuming process if update is required for many indices.   

For cases when index setting is consumed on plugin side that can be solved by changing code of a plugin. But if setting is consumed on core OpenSearch side this approach is not very flexible and can be improved.

For example, if we need to add more file extensions to the list for mmap directory read we need to override index setting "store.hybrid.mmap.extensions". 

**Describe the solution you'd like**
Additional suppliers for index settings can be defined in plugin and registered via https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/index/IndexModule.java. Core can combine list of all additional settings and append to default hardcoded ones. 

**Describe alternatives you've considered**
Default setting can be changed directly in core code, e.g. for "store.hybrid.mmap.extensions" we can add more extensions in https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/index/IndexModule.java#L159. Drawback of this approach is that control is on core side not in plugin. Having everything to core may affect different plugin differently, what works good for one plugin may make things worse for the other.

**Additional context**
The request arise after investigation for issue https://github.com/opensearch-project/k-NN/issues/637. We've found that in Lucene 9.4 segment merge has changed comparing to 9.3, and merged segments are persisted to vem/vex/vec files. These files are not listed as extensions for mmap, so core reads them via NIOFS.

**Comment by dbwiddis** [comment]
@martin-gaievski is this a request for a specific handling of this list setting, or a more general request for how OpenSearch handles list settings?

We would want to make sure any configurable behavior only adds to an existing list.   Are there other use cases besides this specific one?

**Comment by martin-gaievski** [comment]
@dbwiddis Currently we do have only one scenario with vector format related files, these were added to the official Lucene list of extensions in 9.4 [lucene94/package-summary.html#file-names](https://lucene.apache.org/core/9_4_0/core/org/apache/lucene/codecs/lucene94/package-summary.html#file-names). As a plugin maintainer I'd love to have control on adding new file as part of the plugin. Although I'm not sure if that is something that core team willing to provide as extensions are handled and applied in core, and giving control to a plugin is an exchanging of upstream and downstream. 
Just appending not overriding extensions totally makes sense, otherwise merging such lists from multiple plugins can be problematic due to potential conflicts (plug1 removes extension x, while plugin2 has it in the list)

**Comment by dbwiddis** [comment]
Hey @martin-gaievski, looks like from PR #5735 you were able to find a way to implement this without additional functionality.  Closing this issue as well, feel free to re-open it if you think there's a need to do anything else with it.
