### ISSUE TITLE
Opensearch notifications permission

### ISSUE THREAD

**Issue by IvanLM95** [opensearch-project/OpenSearch#5624]
**Describe the bug**
Hi team, i have created an acion group for some users, i want them to have access to the notifications and alerts panels in version 2.4.0
About alerts i have granted the permissions
![image](https://user-images.githubusercontent.com/121100220/209325210-89f1ee3c-ce68-4707-a8cb-ae3013f67074.png)
All go fine with this, but for notifications they dont' have access
![image](https://user-images.githubusercontent.com/121100220/209325278-5747125e-ca27-4925-95fd-9cab008306a6.png)
After check, i added the cluster:admin/opensearch* permission and then they can see, but this grants permissions over machine learning, snapshots and so on i don't want them to have (even if this permissions doesn't appear in the documentation https://opensearch.org/docs/latest/security-plugin/access-control/permissions/)
![image](https://user-images.githubusercontent.com/121100220/209336751-5cc6309f-f3d8-45c9-8d6c-908d82990b2e.png)
I have try to find the permission under cluster:admin/opensearch that grants the access to notifications, but even trying in the most generic way (cluster:admin/opensearch/ml* cluster:admin/opensearch/snapshot_management* cluster:admin/opensearch/observability* ) the access is not granted, only works with cluster:admin/opensearch*

**To Reproduce**
Create a action group
Add a user without permissions to this group
Set the permissions in the above images and text 

**Expected behavior**
Have a concrete permission that grants access to notifications

**Additional context**
Version of opensearch and opensearch-dashboards are 2.4.0 

Any needed info only ask

Regards

**Comment by cwperks** [comment]
Hi @IvanLM95 have you tried mapping users to the reserved roles for these plugins?

Alerting has 3 reserved roles:

- alerting_read_access
- alerting_ack_alerts
- alerting_full_access

Notifications has 2 reserved roles:

- notifications_full_access
- notifications_read_access

Reserved roles should already exist when browsing to `Security -> Roles` where you can map the user there.

You can find a list of reserved roles here: https://github.com/opensearch-project/security/blob/main/config/roles.yml

**Comment by IvanLM95** [comment]
Hi, even if it doesn't suggest it, is working fine 
![image](https://user-images.githubusercontent.com/121100220/209659995-72609511-20e4-4d97-98b0-ec5e1723f262.png)
So much thanks!!
