### ISSUE TITLE
Cut an initial GitHub release

### ISSUE THREAD

**Issue by philoserf** [opensearch-project/OpenSearch#563]
As a OpenSearch user
In order to use the source
I need a release target

**Comment by nknize** [comment]
Can you expand a bit on "release target"? e.g., Are you wanting a date the artifacts will be available in maven central? We currently have a PR open to merge the [opensearch/rebaseVersion](https://github.com/opensearch-project/opensearch/tree/opensearch/rebaseVersion) feature branch to main which will be backported to 1.x then version bumped to 2.0.0 in main. 

You can build the artifacts yourself on that feature branch if you don't want to wait:

```
./gradlew -Dbuild.version_qualifier=alpha1 assemble publish
```

**Comment by geekygirldawn** [comment]
> Can you expand a bit on "release target"?

@nknize I think most people would expect to find releases published on GitHub here: https://github.com/opensearch-project/OpenSearch/releases 

Since the README says that the project is currently in the Alpha stage, I would expect to see an alpha release (or likely several with point release updates) published at the GitHub link above.

**Comment by rmuir** [comment]
> @nknize I think most people would expect to find releases published on GitHub here: https://github.com/opensearch-project/OpenSearch/releases

you just need to push a tag to do this.

**Comment by nknize** [comment]
> you just need to push a tag to do this.

ah! That's what was meant by release target! Thank you for proposing this. I think it's a simple great idea!

**Comment by philoserf** [comment]
Closed by https://github.com/opensearch-project/OpenSearch/releases/tag/1.0.0-alpha1
