### ISSUE TITLE
[Remote Store] Integrate translog download in failover (replica-primary promotion)

### ISSUE THREAD

**Issue by ashking94** [opensearch-project/OpenSearch#5637]
**Is your feature request related to a problem? Please describe.**
For remote backed indices with remote translog enabled, the incoming write request by the client gets served by the primary shard. In a pure local storage backed index, when a write request lands on the primary, the same is stored as a translog and then request fans out to all eligible replicas where the request is replayed similarly as the primary. With remote store backed translog, the translog is stored only on the primary along with remote store for durability and replicas are not subjected to translog. With this, now whenever a replica to primary promotion happens, there is a need for the translog to be downloaded from remote store and be played against the engine. 

**Describe the solution you'd like**
Integrate remote translog download with failover.

**Describe alternatives you've considered**

**Additional context**

**Comment by saratvemulapalli** [comment]
@ashking94 this is labelled 2.5, code freeze is 1/10 do you think you can make it?

**Comment by ashking94** [comment]
@saratvemulapalli  this will be closed before the code freeze.
