### ISSUE TITLE
audit logs about queries 

### ISSUE THREAD

**Issue by taltsafrirpx** [opensearch-project/OpenSearch#5648]
hi, we are using opensearch, and wanted to know if there is any feature in audit logs that we can see which user ran the query.
also is there any feature to see the query content?
(we have a problem with users running heavy queries and we want to investigate)

**Comment by jkowall** [comment]
https://opensearch.org/docs/latest/opensearch/logs/

**Comment by taltsafrirpx** [comment]
@jkowall I need to see the content of the query using audit logs, maybe one of this can help?
<img width="643" alt="Screen Shot 2022-12-28 at 12 15 18" src="https://user-images.githubusercontent.com/95569352/209871455-f23a82f0-d975-4208-9f38-618e9b67dc65.png">

**Comment by noCharger** [comment]
@taltsafrirpx  Do you think slow log fits into your use case? https://opensearch.org/docs/latest/opensearch/logs/#slow-logs

**Comment by Hailong-am** [comment]
@taltsafrirpx how about `audit_request_body` field in audit log?
https://opensearch.org/docs/latest/security-plugin/audit-logs/field-reference/#rest-authenticated-attributes

https://opensearch.org/docs/latest/security-plugin/audit-logs/field-reference/#transport-authenticated-attributes

**Comment by taltsafrirpx** [comment]
thanks! I saw that I had exclude categories and that's why I didnt see the request body
