### ISSUE TITLE
[Version] Remove unused V_EMPTY version label

### ISSUE THREAD

**Issue by nknize** [opensearch-project/OpenSearch#566]
This issue is created as an offshoot of https://github.com/opensearch-project/OpenSearch/pull/555#discussion_r614403704. It appears the `V_EMPTY` version and companion id variable is not used anywhere and can be removed. We opted to take care of this in a follow up issue to ensure there aren't any adverse side effects.

**Comment by harold-wang** [comment]
@nknize  I found that we could not clear V_EMPTY version and companion id

- that V_EMPTY is sill used by https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/cluster/metadata/IndexMetadata.java#L282

**Comment by nknize** [comment]
This version is currently used in a few places throughout the build so I'm going to keep it in for now. I'll remove the version label so this stays on the  backlog.

**Comment by minalsha** [comment]
@nknize  can we close this issue if it is done?

**Comment by nknize** [comment]
> can we close this issue if it is done?

It wasn't done but it is stale so good call out. We need V_EMPTY for now and after some time going through versioning I don't think it's an issue keeping it around so I'm closing and labeling w/ `wontfix`. Thx for circling back!
