### ISSUE TITLE
(Re-)Add coalesceToEmpty method to o.o.common.Strings util class

### ISSUE THREAD

**Issue by dbwiddis** [opensearch-project/OpenSearch#5664]
**Is your feature request related to a problem? Please describe.**

A [relatively common use case](https://github.com/search?q=org%3Aopensearch-project%20coalesceToEmpty&type=code) during REST handling is to replace a null String with an empty String:
```java
public static String coalesceToEmpty(@Nullable String s) {
    return s == null ? "" : s;
}
```
Such a method exists in [ml-commons](https://github.com/opensearch-project/ml-commons/blob/606226f44f6460ed964579a053cd777045b8d4de/plugin/src/main/java/org/opensearch/ml/utils/RestActionUtils.java#L162) and [anomaly-detection](https://github.com/opensearch-project/anomaly-detection/blob/20d2c5f94811f62a7077142ba505bed272a83549/src/main/java/org/opensearch/ad/util/RestHandlerUtils.java#L243) plugins and is [being added to job-scheduler](https://github.com/opensearch-project/job-scheduler/pull/289/files).

This exists in the current release (2.4.1) of the `Strings` class [here](https://github.com/opensearch-project/OpenSearch/blob/f2f809ea280ffba217451da894a5899f1cec02ab/server/src/main/java/org/opensearch/common/Strings.java#L878) and is [referenced by the alerting plugin](https://github.com/opensearch-project/alerting/blob/88536b233c56d687ae61b7c31b69b883b7b1affe/alerting/src/main/kotlin/org/opensearch/alerting/util/RestHandlerUtils.kt#L21) but was removed in #5288 as "unused".  (This broke the AD plugin [which prompted re-adding](https://github.com/opensearch-project/anomaly-detection/pull/736) its own method.)

**Describe the solution you'd like**

Don't repeat code.  Add this method back to the `Strings` class.

Additionally, I'm curious why this util class is marked "internal" as it's useful for dependent classes to use (which at least the alerting plugin does).  The removal was not marked deprecated nor mentioned in the change log (likely because of its "internal" usage) but there is a lot of use of other methods in this class.

**Describe alternatives you've considered**

It may be a better idea to create a util class with all the `RestHandlerUtils` in the above-linked plugin packages.

**Additional context**

The method [appears to have originated](https://github.com/opensearch-project/OpenSearch/commit/a6ffe8f6d50e207b44c327c99cb304f20bb07027) in `com.google.common.base.Strings` and was moved to the `Strings` class (in open-source ES pre-fork) to remove that external dependency.  

If we want to remove "internal" util classes/methods like this, we should consider either using external dependencies or creating a separate supported (API) project with util classes to provide the same functionality without duplicating code.

**Comment by dblock** [comment]
I think we can all agree that `coalesceToEmpty` is not "OpenSearch-specific business logic", thus isn't not an API I think OpenSearch should expose. However, having helpers to make life easier for plugin authors may make sense if we wanted to continue building tightly-coupled plugins. Introducing `RestHandlerUtils` would be one way to do it. Which tells me that the right place for this method *was* indeed in `com.google.common.base.Strings`, a helper library whose only purpose in life was to do things about strings, aka `coalesceToEmpty` was its business logic. We just didn't want the extra dependency for such a silly method.

If we go all in with helpers, the risk is that `RestHandlerUtils` grows out of control and becomes [common-utils](https://github.com/opensearch-project/common-utils), a kitchen sink of unrelated functions. 

All that to say that I think putting this method back into this project and unmarking it from internal is harmless, but that I hope ~a plugin~ an extension author will not care whether we do or don't.

**Comment by dbwiddis** [comment]
Closing this request as I have decided it's the wrong answer to a real problem.

I'll consider a future request for an API `RestHandlerUtils` class.
