### ISSUE TITLE
[BUG] Openseach stores the fields when I set the "store: false" parameter

### ISSUE THREAD

**Issue by filipetavares** [opensearch-project/OpenSearch#5673]
**Describe the bug**
Using the example in https://opensearch.org/docs/latest/quickstart/#create-an-index-and-field-mappings-using-sample-data, I've modified the mapping of the `customer_first_name` field with the parameter `store: false` but when I query the index, the field `customer_first_name`  is still returned in the _source.

**To Reproduce**
1 - Follow the instructions in https://opensearch.org/docs/latest/quickstart/#create-an-index-and-field-mappings-using-sample-data
2 - Modify the `customer_first_name` field in mapping file https://raw.githubusercontent.com/opensearch-project/documentation-website/2.4/assets/examples/ecommerce-field_mappings.json like so:
```JSON
...
      "customer_first_name" : {
        "type": "text",
        "store": false,    <--- added this
        "fields" : {
          "keyword" : {
            "type" : "keyword",
            "ignore_above" : 256,
            "store": false <--- and this just to make sure
          }
        }
      },
...
```
3 - Add the bulk data as shown in the tutorial
4 - Perform the query using the `customer_first_name` as shown in the tutorial.

**Expected behavior**
We should be able to perform the query, but the field `customer_first_name` should not be part of the _source.

**Plugins**
The default on the docker-compose of the tutorial, but I've disabled the SSL plugins on all nodes and dashboard.

**Host/Environment (please complete the following information):**
 - OS: Windows 10 - WSL2 Ubuntu 20.04 - Docker
 - Windows Version 10.0.19044
 - Docker Version 20.10.18
 - Opensearch Version 2.4.1

**Comment by dblock** [comment]
That would be a bug. Want to try implementing a (failing) unit test for it?

**Comment by filipetavares** [comment]
Sorry I would like to, but I have no knowledge of java. The tests that I did were purely REST calls.

**Comment by dblock** [comment]
Scratch what I said. Where did you find the documentation for "store"?

**Comment by filipetavares** [comment]
I didn't see the docs. I know the configuration from Elasticsearch, so I assumed it should work the same here, also since Opensearch API doesn't support other "random" parameters, I again assumed that this was a supported parameter.

Skimming through the Opensearch Docs I can't find the parameter, but in the Elasticsearch docs there is this https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-store.html.

**Comment by dblock** [comment]
We forked at 7.10, so the relevant equivalent docs would be https://www.elastic.co/guide/en/elasticsearch/reference/7.10/mapping-store.html. There's definitely code that seems to evaluate `store` options, but I'm not familiar with the feature and the syntax you're using may have been added in subsequent versions of Elasticsearch. 

Next steps would be to dive into the code and see what's up, document current behavior properly, and open feature requests for anything that's not supported. I think this is domain of @macohen, but please don't let me stop from doing any of this @filipetavares, and thank you for your time here!

**Comment by filipetavares** [comment]
Sorry, I think I missed something. If the version docs that you sent me does contain the store flag and the documentation states that, by default, the fields are not stored unless we specify that we want to store them, we should not see any field in _source unless we set `store: true`, but again the tutorial doesn't specify the `store` parameter and every field is stored, or at least is returned in the _source.

My main question is, is there anyway to only index fields without storing them?

**Comment by macohen** [comment]
@filipetavares all fields by default are indexed without being stored, but the _source field is a bit different.

The _source field is special. _source gives you a single field with the entire document before it is indexed, but OpenSearch only stores it. It's not analyzed or indexed. To pull any specific data out of that field, I believe you need to pull the json and parse it yourself. There are ways to disable it if you're concerned about disk space, although it's not recommended (https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-source-field.html). 

If you take the string "The quick brown fox jumped over the Lazy Dog. Hmm!" and you created a field for it called "thing" with "store": true, OpenSearch would store the entire string in the "thing" field. If you leave store=false, and used the standard analyzer (https://opensearch.org/docs/latest/opensearch/query-dsl/text-analyzers/) at index time, the analyzer would lowercase all the words, remove the punctuation, remove stop words (like "the" if you specify), and indexes the document so you could search with "lazy" and find this document in the returned set. 

I hope that helps clarify things a bit. Can you confirm if this explanation helps or if I'm misunderstanding the issue?

**Comment by macohen** [comment]
@filipetavares I'm closing this. Feel free to re-open or create a new issue if this didn't address your question. I hope we were able to help.
