### ISSUE TITLE
[Remote Translog] Metadata file naming and its clean up

### ISSUE THREAD

**Issue by gbbafna** [opensearch-project/OpenSearch#5677]
**Is your feature request related to a problem? Please describe.**

Currently we append `timestamp` in metadata file name along with primary term and generation . Though we expect that for any given generation and primary term, metadata file will be uploaded only once. Uploading it twice would give `IO Exception`  and would never succeed in first place . 

**Describe the solution you'd like**

Simplication of naming by removing the `timestamp` from name. 

This would make downloads easier , handling duplicate metadata files at upload time and would make deletion of translog metadata files easier.

**Comment by ashking94** [comment]
@gbbafna  I have created an issue for purging up older translog metadata. We can keep this story to be specifically for the naming i.e. removing the timestamp from the metadata file name.
