### ISSUE TITLE
Introduce new sandbox module

### ISSUE THREAD

**Issue by nknize** [opensearch-project/OpenSearch#570]
A real nice feature of Lucene that keeps the innovation moving forward is the sandbox module. I'd like to propose adding one here to provide contributors a safe package location to try out `@opensearch.experimental` features. 

Aside from ensured security (as a by product of the release process) this module will not have any other guarantees; no backwards compatibility, no long term support, can be removed at any time. But it does give a nice place to keep innovation moving forward.

**Comment by mikemccand** [comment]
+1 this is a great idea!  Lucene's sandbox module has been a real innovation amplifier over the years.  Just look at the git history...

E.g. Lucene's dimensional points started there!
