### ISSUE TITLE
[BUG] OpenSearch should clean up temporary files created during segment merge incase segment merge fails

### ISSUE THREAD

**Issue by RS146BIJAY** [opensearch-project/OpenSearch#5710]
**Describe the bug**
Currently, during segment merge (both during auto merge and force merge), OpenSearch creates multiple temporary files while merging individual segment components. Once individual components of the segments are merged, `IndexWriter` creates a Compound file (`*.cfs`) containing all the Lucene components for a segment. At the end, OpenSearch deletes these temporary files.

Now, in case these temporary files consume all the space on the node (because enough amount of space is unavailable for segment merge to go through), segment merge will fail. Also, the files which got created during segment merge do not get cleaned up and it continues to occupy space on the node. This can cause FSHealthService checks to fail for this node, ultimately causing these nodes to be removed from cluster.

**Expected behavior**
In case Force segment merge fails, OpenSearch should remove the temporary files created during segment merge.

**Comment by anasalkouz** [comment]
Hi @RS146BIJAY, this Seems to be an important bug, are you actively working on it?

**Comment by anasalkouz** [comment]
@RS146BIJAY Any plan to fix again?

**Comment by RS146BIJAY** [comment]
Yeah. We are analysing where this fix should go in. We started observing few race condtion scenario with above change therefore had to revert the change. Will send the fix for this issue in few weeks time.

**Comment by RS146BIJAY** [comment]
Created a [github issue](https://github.com/apache/lucene/issues/12228) in Lucene as this issue seems to be introduced in this [Lucene commit](https://issues.apache.org/jira/browse/LUCENE-6579).

**Comment by RS146BIJAY** [comment]
Created a RFC document listing possible approaches to gain feedback: https://github.com/opensearch-project/OpenSearch/issues/8024
