### ISSUE TITLE
Maybe OP can be updated -- to mention the :00-:10 and :30-:40 plan?

### ISSUE THREAD

**Issue by jklc17** [opensearch-project/OpenSearch#574]
Maybe OP can be updated -- to mention the :00-:10 and :30-:40 plan?

_Originally posted by @pradyunsg in https://github.com/pypa/warehouse/issues/3411#issuecomment-376792786_

**Comment by CEHENKLE** [comment]
Hi -- I think we may have been tagged in here in error?

Thanks,
/C
