### ISSUE TITLE
[Flaky Test Failure] TransportReplicationActionTests.testClosedIndexOnReroute

### ISSUE THREAD

**Issue by gbbafna** [opensearch-project/OpenSearch#5765]
See 

https://github.com/opensearch-project/OpenSearch/pull/5764#issuecomment-1375917435 

https://github.com/opensearch-project/OpenSearch/pull/5722#issuecomment-1374027850

**Comment by Bukhtawar** [comment]
https://build.ci.opensearch.org/job/gradle-check/8963/

**Comment by gbbafna** [comment]
https://github.com/opensearch-project/OpenSearch/pull/5774#issuecomment-1376735861

https://build.ci.opensearch.org/job/gradle-check/9128/

**Comment by ashking94** [comment]
https://build.ci.opensearch.org/job/gradle-check/8953/

**Comment by dblock** [comment]
@gbbafna  are you working on this? Let’s not merge any more PRs in any branch with this or other failures

**Comment by andrross** [comment]
This was fixed in #5737 but not backported. I've started the backports now.

**Comment by andrross** [comment]
Backports complete
