### ISSUE TITLE
[TEST BUG] NodeJoinControllerTests.testRejectingJoinWithIncompatibleVersion is flaky

### ISSUE THREAD

**Issue by rmuir** [opensearch-project/OpenSearch#577]
This test fails about 50% of the time. It seems to have the following logic flow:

```
if (random.nextBoolean()) {
  testOneThing();
} else {
  testADifferentThing();
}
```

One of these things always fails with 0ba0e7cc26060f964fcbf6ee45bae53b3a9941d0 :) IMO it should simply be split into two separate tests.

**Comment by adnapibar** [comment]
Thanks @rmuir for reporting this. 

I have identified the change in [L610-L616](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/test/java/org/opensearch/discovery/zen/NodeJoinControllerTests.java#L610-L616) made by me in #555, introduced the issue.  For example, in this change, 

`badVersion = randomFrom(allVersions().stream().filter(v -> v.major < Version.CURRENT.major).collect(Collectors.toList()));`

to 

`badVersion = 
randomFrom(allVersions().stream().filter(v -> v.before(Version.CURRENT)).collect(Collectors.toList()));`

the filtering logic incorrectly identifies all `ES 7.*.*` versions as bad versions for joining which should not be the case. I have created a PR #598 to fix this.

I also agree that we should split the test in two separate tests. 

**Reproduce**

`./gradlew :server:test --tests "org.opensearch.discovery.zen.NodeJoinControllerTests.testRejectingJoinWithIncompatibleVersion"  -Dtests.seed=CF571C19C492BB6C:5061AF83FC8AB341`
