### ISSUE TITLE
[TEST BUG] SearchServiceTests.testSearchWhileIndexDeleted extremely slow

### ISSUE THREAD

**Issue by rmuir** [opensearch-project/OpenSearch#578]
This unit test is very slow (e.g. hundreds of seconds). Iterations or number of nodes or whatever should be toned down.

**Comment by abbashus** [comment]
Thanks, we will look into this how we can optimize this and reduce run time.

**Comment by CEHENKLE** [comment]
@abbashus Can you take pick this up and take a look at it?  Thanks!

**Comment by abbashus** [comment]
Sure @CEHENKLE, will go over this.

**Comment by abbashus** [comment]
**NOTE** : I would not call this is a bug. It's more of an opportunity for optimization. Even at max iterations it was taking 2m45s which I believe does not skews the total build time very much.


Reproduced this with following command and different build envs:

```
./gardlew clean && ./gradlew ':server:test'  --no-build-cache
```

Checked the following reports for test run time at 
```
file:///<path-to-OpenSearch-repo>/server/build/reports/tests/test/classes/org.opensearch.search.SearchServiceTests.html
```

| Build Environment                                                                                                             	| Min Time (100 iterations) 	| Max Time (10K iterations)  	| Max Time after tuning (1000 iterations) 	|
|-------------------------------------------------------------------------------------------------------------------------	|---------------------------	|----------------------------	|-----------------------------------------	|
| Amazon Linux  (Linux 5.11.0-1016-aws)<br>- 48 core<br>- 48 Gradle workers<br>- Max JVM memory heap size 3GB<br>- JVM 14 	| 2.477s                    	| 1m 32.742s                 	| 16.988s                                 	|
| Mac OS X 10.15.7<br>- 12 core<br>- 12 Gradle workers<br>- Max JVM memory heap size 3GB<br>- JVM 14                      	| 3.627s                    	| 2m 43.976s                 	| 1m 5.594s                               	|


After tuning down the max iteration by order of magnitude (10000 ->1000), I was able to reduce testing time by ~30 secs on MacOS and ~70 secs on Amazon Linux. I will be raising a PR based on this observations.
