### ISSUE TITLE
[BUG] NPE when queryResults.isEmpty() but hasAggs is true

### ISSUE THREAD

**Issue by janheise** [opensearch-project/OpenSearch#5785]
**Describe the bug**
We have the following occuring;

If there is an empty result:

https://github.com/opensearch-project/OpenSearch/blob/8c9481a2ca5f172157ba7ce30dd03324b0527428/server/src/main/java/org/opensearch/action/search/SearchPhaseController.java#L465-L467

returns with an almost empty `ReducedQueryPhase` instance, which further on in 

https://github.com/opensearch-project/OpenSearch/blob/8c9481a2ca5f172157ba7ce30dd03324b0527428/server/src/main/java/org/opensearch/action/search/QueryPhaseResultConsumer.java#L163-L165

creates an NPE if the query had aggregations.

It is probably related to the `multi_terms` aggregation.

**To Reproduce**
- Start a new/empty OpenSearch 2.4 instance
- create an index `PUT http://localhost:9200/test_jh`
- run the following query:
```
{
	"aggregations": {
		"agg": {
			"date_histogram": {
				"field": "timestamp",
				"format": "date_time",
				"fixed_interval": "30m"
			},
			"aggregations": {
				"agg": {
					"multi_terms": {
						"terms": [
							{
								"field": "field1"
							},
							{
								"field": "field2"
							}
						]
					}
				}
			}
		}
	}
}
```

The following error occurs:
```
{
	"error": {
		"root_cause": [
			{
				"type": "response_handler_failure_transport_exception",
				"reason": "java.lang.NullPointerException: Cannot invoke \"org.opensearch.common.io.stream.NamedWriteable.getWriteableName()\" because \"namedWriteable\" is null"
			}
		],
		"type": "search_phase_execution_exception",
		"reason": "",
		"phase": "fetch",
		"grouped": true,
		"failed_shards": [
			{
				"shard": 0,
				"index": "test_jh",
				"node": "NbG0fKofQ5OOkIagnOIXvA",
				"reason": {
					"type": "response_handler_failure_transport_exception",
					"reason": "java.lang.NullPointerException: Cannot invoke \"org.opensearch.common.io.stream.NamedWriteable.getWriteableName()\" because \"namedWriteable\" is null",
					"caused_by": {
						"type": "null_pointer_exception",
						"reason": "Cannot invoke \"org.opensearch.common.io.stream.NamedWriteable.getWriteableName()\" because \"namedWriteable\" is null"
					}
				}
			}
		],
		"caused_by": {
			"type": "null_pointer_exception",
			"reason": "Cannot invoke \"org.opensearch.search.aggregations.InternalAggregations.getSerializedSize()\" because \"reducePhase.aggregations\" is null"
		}
	},
	"status": 500
}
```
**Expected behavior**
There should be no NPE, the empty result should be propagated as is.

**Host/Environment (please complete the following information):**
 - OS: macOS, Ubuntu 20.04
 - Version 2.4

**Comment by janheise** [comment]
Added example to reproduce problem.

**Comment by dblock** [comment]
@janheise You did most of the work to debug this! Thank you. Want to try to implement a unit test and maybe even a fix?

**Comment by janheise** [comment]
@dblock I am currently too busy to tackle it myself - and am surprised about the `good first issue` label. From what I've seen (but I did not look into it too deeply), you need a lot of context to decide where the problem actually starts and how a bugfix should look.

**Comment by dblock** [comment]
@janheise Thanks! @anasalkouz triaged it as such, I imagine because there's a request/response repro (thank you). I think a unit test is not too difficult based on this, but I agree that fixing the problem may be much more involved. Would value a PR that just has the unit test, it will get whomever wants to fix this one step further.

**Comment by sarvajeetp** [comment]
When I tried to debug, it turned out that queryResults has size of 1 and hence it doesn't goes into below condition
`if (queryResults.isEmpty()) { // early terminate we have nothing to reduce
            final TotalHits totalHits = topDocsStats.getTotalHits();
            return new ReducedQueryPhase(`

Instead, below is evaluates to null, because bufferedAggs list is empty.
`final InternalAggregations aggregations = reduceAggs(aggReduceContextBuilder, performFinalReduce, bufferedAggs);`

**Comment by anasalkouz** [comment]
> am surprised about the good first issue label. From what I've seen (but I did not look into it too deeply), you need a lot of context to decide where the problem actually starts and how a bugfix should look.
Agreed, will keep the label for the unit test

**Comment by geetptl** [comment]
Hey @anasalkouz @janheise @dblock, I am going to pick this up since the previous assignee has left. Will reply here if I need any help

**Comment by anasalkouz** [comment]
Hi @geetptl, it has been a while, are you actively working on this?

**Comment by z002Holpp** [comment]
Could you give a rough estimate about when the issue could be solved or if someone actively works on it? We have some business decisions depending on that.

**Comment by dblock** [comment]
@z002Holpp I would say nobody is working on it unless it clearly says so, and looks like @geetptl isn't around to confirm they still are :( maybe you can help with some hands?

**Comment by geetptl** [comment]
Het @dblock, I'm not working on this, feel free to take it up!
