### ISSUE TITLE
Publish Artifacts to Maven Central

### ISSUE THREAD

**Issue by dblock** [opensearch-project/OpenSearch#581]
**Is your feature request related to a problem? Please describe.**

Publish -SHAPSHOT artifacts to Maven central so that plugin developers can be using them.

**Describe the solution you'd like**

A way for plugin developers to take a dependency on a -SHAPSHOT. Currently requires building OpenSearch and all dependencies, and publishing to local maven. See https://github.com/opensearch-project/opensearch-plugins/pull/1 for details.

**Describe alternatives you've considered**

https://github.com/opensearch-project/anomaly-detection/pull/13 builds dependencies locally via `./gradlew publishToMavenLocal` and consumes that local output.

**Comment by dblock** [comment]
Depends on https://github.com/opensearch-project/opensearch-build/issues/20

**Comment by dblock** [comment]
@mch2

**Comment by frotsch** [comment]
And please update the build.gradle files (https://github.com/opensearch-project/OpenSearch/issues/939) to include maven central and opensearch.org repo properly

**Comment by dlvenable** [comment]
This will be very helpful. I'd also like to request that the team include internal libraries. In particular, `org.opensearch.gradle:build-tools` and `org.opensearch.test:framework`.

**Comment by minalsha** [comment]
@mch2  could you please confirm if this issue has been addressed already? If yes, please close this issue. Thanks

**Comment by saratvemulapalli** [comment]
I can confirm, these artifacts are now published. 
https://aws.oss.sonatype.org/content/repositories/snapshots/org/opensearch/

Closing.
