### ISSUE TITLE
[BUG] SQL Plugin main branch BWC test faiiled

### ISSUE THREAD

**Issue by penghuo** [opensearch-project/OpenSearch#5815]
**Describe the bug**
* After OpenSearch bump 2.x to 2.6. SQL BWC test failed. https://github.com/opensearch-project/sql/actions/runs/3887469849/jobs/6633763589
* SQL plugin can not build 2.6 version because of opensearch 2.6.0 snapshot is not ready. https://github.com/opensearch-project/sql/pull/1248

**Expected behavior**
1. OpenSearch revert 2.x to 2.5. or
2. OpenSearch release 2.6 snapshot

**Host/Environment (please complete the following information):**

**Additional context**

**Comment by saratvemulapalli** [comment]
We now have 2.6 Snapshot in maven. 
The process for OpenSearch is always to to bump 2.x and add it as bwc for main.
Let us know if you have more questions.

**Comment by Yury-Fridlyand** [comment]
BWC tests are still failing. For example, [this job](https://github.com/opensearch-project/sql/actions/runs/3877197920/attempts/3) was started 30 min ago.
