### ISSUE TITLE
[Test Failure] BulkProcessorRetryIT tests failure

### ISSUE THREAD

**Issue by amkhar** [opensearch-project/OpenSearch#5830]
**Describe the bug**
[org.opensearch.action.bulk.BulkProcessorRetryIT.testBulkRejectionLoadWithBackoff](https://build.ci.opensearch.org/job/gradle-check/9286/testReport/junit/org.opensearch.action.bulk/BulkProcessorRetryIT/testBulkRejectionLoadWithBackoff/)
[org.opensearch.action.bulk.BulkProcessorRetryIT.testBulkRejectionLoadWithoutBackoff](https://build.ci.opensearch.org/job/gradle-check/9286/testReport/junit/org.opensearch.action.bulk/BulkProcessorRetryIT/testBulkRejectionLoadWithoutBackoff/)

**Expected behavior**
Integration tests should pass.

**Comment by anasalkouz** [comment]
Should be resolved, closing the issue. Feel free to re-open/ask to re-pen if the issue still exist.
