### ISSUE TITLE
Blank Dashboard and Discover Screen

### ISSUE THREAD

**Issue by emertoglu** [opensearch-project/OpenSearch#5842]
My scenario is as follows.

I created 2 roles[**role1, role2**] , 2 users[**user1, user2**] and 2 tenants[**tenant1, tenant2**] and I mapped roles to users.

I loaded the data with two different index names[index_u1-*, index_u2-*]

user1 index_u1-* and user2 index_u2-* have **read** , **write** **manage** index permissions

when i sign in with a user name and password, i see a blank screen. The Dashboard and Discover screens are blank and I can't create anything.

if I map the role of **kibana_user** to users, users can create dashboards, but this time they can see someone else's dashboards (they can't see the data because the indexes are different)

if I map **all_access** role to users, users can create dashboards, but this time they can see someone else's dashboards and data (although the indexes are different)

how can i fix the problem?

**Comment by minalsha** [comment]
@seanneumann  can this issue be looked upon by you?

**Comment by minalsha** [comment]
created an issue on dashboard side https://github.com/opensearch-project/dashboards-anywhere/issues/140, closing issue here.
