### ISSUE TITLE
Failed to start thread "Unknown thread" 

### ISSUE THREAD

**Issue by brian-grabau** [opensearch-project/OpenSearch#5846]
**Describe the bug**
Warm nodes keep crashing and dropping out of the cluster. Only error we see is
[62.331s][warning][os,thread] Failed to start thread "Unknown thread" - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 0k, detached.

**To Reproduce**
We are on Opensearch Version 1.3.5 we have been running fine on version for 2 months and now every time we restore the warm nodes after 2 days they begin to crash again even with very little or no data on warm nodes.

Heap is set correctly, overall shard count in cluster is around 9k and even with near 0 shard counts in warms they still get failed to start threads,

Also observed high amount of inter cluster traffic on port 9600 when system is having issues.

**Comment by brian-grabau** [comment]
Java Heap settings set as per documentation and our cluster size standards. 
Ulimits modified slightly higher than 65k , still the cluster crashes.

**Comment by minalsha** [comment]
@brian-grabau  you are running a self managed cluster, consisting of warm nodes. Can you please share some additional logs, cluster manager logs to help us triage.

**Comment by brian-grabau** [comment]
Yes self-managed. Ok issue turned out to be simple. Root disk full.
