### ISSUE TITLE
[BUG] #0 dump an error event: error_class=Fluent::Plugin::OpenSearchErrorHandler::OpenSearchError error="400 - Rejected by OpenSearch" 

### ISSUE THREAD

**Issue by type-kimchi** [opensearch-project/OpenSearch#5870]
**Describe the bug**
#0 dump an error event: error_class=Fluent::Plugin::OpenSearchErrorHandler::OpenSearchError error="400 - Rejected by OpenSearch" 

**To Reproduce**

**Expected behavior**
Fluentbit -> Fluentd -> opensearch pipeline and it shows dashboard well but when i see logs there is ErrorHandler log

**Plugins**
Please list all plugins currently enabled.

**Screenshots**
![image](https://user-images.githubusercontent.com/42171883/212612163-8615fd0a-741a-4559-aecd-ad4a75db9995.png)

When i have log pipeline there is errorhandler 400, rejected by opensearch... what is it and how i can troubleshoot?

**Comment by dblock** [comment]
Fluentd needs to show the actual error along with that 400. Is there something else in the logs?

**Comment by minalsha** [comment]
@type-kimchi  could you please share if you have any more details from the logs? Please see @dblock  comments above. Thanks

**Comment by minalsha** [comment]
@type-kimchi  we will keep this issue open until 2/10 for you to share details. Post 2/10, we will close this issue if we dont hear back from you. Feel free to reopen the issue once you have more details.
