### ISSUE TITLE
[Weighted Shard Routing] Disallow search requests with preference parameter with strict weighted shard routing

### ISSUE THREAD

**Issue by anshu1106** [opensearch-project/OpenSearch#5873]
**Is your feature request related to a problem? Please describe.**
With weighted shard routing, requests are distributed across data nodes in the ratio the weights are assigned. Since search requests with preference parameter runs the request only on the specified nodes, this won't honour weighted shard routing.
ie for a 3 az domain with weights (1, 2, 4) preference searches on nodes with weight 1 can cause more request on nodes with weight 1.

**Describe the solution you'd like**
Allow support for strict weighted shard routing using cluster setting.

**Describe alternatives you've considered**

**Additional context**

**Comment by anasalkouz** [comment]
@anshu1106 Are you actively working on this? can I assign it to you?

**Comment by anshu1106** [comment]
> @anshu1106 Are you actively working on this? can I assign it to you?

Yes
