### ISSUE TITLE
Reproducible test failure SearchWeightedRoutingIT.testPreferenceSearchWithWeightedRouting

### ISSUE THREAD

**Issue by mch2** [opensearch-project/OpenSearch#5929]
This fails 100% of the time with the following seed:

``
REPRODUCE WITH: gradlew ':server:internalClusterTest' --tests "org.opensearch.search.SearchWeightedRoutingIT.testPreferenceSearchWithWeightedRouting" -Dtests.seed=9C00D8285A96154B -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=en-CA -Dtests.timezone=Etc/GMT-1 -Druntime.java=19
``

**Comment by mch2** [comment]
another one
```
gradlew ':server:internalClusterTest' --tests "org.opensearch.search.SearchWeightedRoutingIT.testPreferenceSearchWithWeightedRouting" -Dtests.seed=2211E75A1B84F237 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=ar-AE -Dtests.timezone=Indian/Mahe
```

**Comment by mch2** [comment]
@anshu1106 Mind taking a look please?

**Comment by anshu1106** [comment]
Raise [PR](https://github.com/opensearch-project/OpenSearch/pull/5931) to fix this
