### ISSUE TITLE
Test failure ReindexClientYamlTestSuiteIT

### ISSUE THREAD

**Issue by mch2** [opensearch-project/OpenSearch#5930]
The following is failing 100% of the time on our Windows CI irrelevant of seed.  

``
gradlew ':modules:reindex:yamlRestTest' --tests "org.opensearch.index.reindex.ReindexClientYamlTestSuiteIT.test {yaml=reindex/90_remote/Reindex from remote that you can't connect to}" -Dtests.seed=2211E75A1B84F237 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=ko-KR -Dtests.timezone=America/Pangnirtung -Druntime.java=19
``

Expected: connect_exception|IIS Windows Server
         but: was "{root_cause=[{type=bind_exception, reason=Cannot assign requested address: connect, stack_trace=[Cannot assign requested address: connect]; nested: BindException[Cannot assign requested address: connect]

We have the comment next to this test 
```
      # sometimes IIS is listening on port 0. In that case we fail in other ways and this test isn't useful.
      # make sure to stop any local webservers if running this test locally otherwise an s_s_l handshake exception may occur
```
The error is because port 0 cannot be assigned.

**Comment by minalsha** [comment]
@xuezhou25  could you please update the status of this test failure fix?  Thanks

**Comment by minalsha** [comment]
@dreamer-89  did you follow up with @xuezhou25  on this issue? Whats the latest status on this one?

**Comment by dreamer-89** [comment]
Hey @minalsha , 
Sorry, I did not get a chance to work on this issue. Pinging current core oncall to take a look @kotwanikunal
