### ISSUE TITLE
[BUG] Delete All PITs returns 404 if no PITs are present

### ISSUE THREAD

**Issue by nhtruong** [opensearch-project/OpenSearch#5938]
**Describe the bug**
When hitting `DELETE /_search/point_in_time/_all` to delete all PITs, the server will return a 404 error if no PITs are present.

**To Reproduce**
Execute `DELETE /_search/point_in_time/_all` when there are not PITs.
Easiest way to do this is hitting that endpoint twice in a row.

**Expected behavior**
The server returns 200 StatusCode with `{ "pits": [] }` as the body when there are no PITs to delete.

**Plugins**
None

**Host/Environment (please complete the following information):**
 - OS: Mac
 - Version: OpenSearch 2.4.x

**Comment by anasalkouz** [comment]
Thanks @nhtruong for reporting this. 200 StatusCode with { "pits": [] } is make sense for me.
Would you mind to submit PR with your proposal?

**Comment by dennxa** [comment]
Hi! is anyone investigating this? If not, I'd like to work on it. Thanks!

**Comment by anasalkouz** [comment]
@dennxa, thanks for your interest. Yes, please go for it. I will assign the issue to you.

**Comment by harshjain2** [comment]
I have started working on this. I might take some time, as I am getting used to contribution and development process of the OpenSearch.

**Comment by anasalkouz** [comment]
Hi @harshjain2, I think @dennxa already start working on this, not sure if you are going to work on this together. Otherwise, feel free to pick another issue.

**Comment by harshjain2** [comment]
Sure @anasalkouz . I will pick some other issue.

**Comment by harshjain2** [comment]
@dennxa I think I found the issue. Do let me know if you have already started working on the fix. If not I can create a PR to fix this issue.

**Comment by dennxa** [comment]
Hi @harshjain2, I'm still working on it, but if you already fixed the issue feel free to create a PR.

**Comment by harshjain2** [comment]
@dennxa I have created the PR https://github.com/opensearch-project/OpenSearch/pull/6544.
I am not sure whether the fix is correct or not as this is my first commit to the OpenSearch repo. Will it be possible for you to provide the feedback on the correctness of the fix?

**Comment by anasalkouz** [comment]
Closing it, since the fix already merged.
Thanks @harshjain2 for your contribution.
