### ISSUE TITLE
[BUG] [Extensions] Extension onIndexModule times out even after successful response

### ISSUE THREAD

**Issue by dbwiddis** [opensearch-project/OpenSearch#5999]
**Describe the bug**

Following merge of #5646, adding a document to an index while an extension is running times out.

**To Reproduce**
1. Start any extension
2. Start OpenSearch with the extensions feature flag activated and extensions.yml pointing to the extension connection info
3. Add a document to an index, e.g.,
```json
POST http://localhost:9200/server_log_foo/_doc
{
  "Description": "This is just a sample document"
}
```
Above commands using curl on command line: 
```bash
curl -X POST http:///localhost:9200/server_log_foo/_doc -H 'Content-Type: application/json' -d '{"Description":"This is just a sample document"}'`)
```

4. Wait for the 10 second timeout and receive
```json
{
    "error": {
        "root_cause": [
            {
                "type": "runtime_exception",
                "reason": "java.util.concurrent.TimeoutException"
            }
        ],
        "type": "runtime_exception",
        "reason": "java.util.concurrent.TimeoutException",
        "caused_by": {
            "type": "timeout_exception",
            "reason": null
        }
    },
    "status": 500
}
```

**Expected behavior**
Document is registered in the index.
```json
{
    "_index": "server_log_foo",
    "_id": "lFr85YUBHCpwc2HGJ5rv",
    "_version": 1,
    "result": "created",
    "_shards": {
        "total": 2,
        "successful": 1,
        "failed": 0
    },
    "_seq_no": 0,
    "_primary_term": 1
}
```

**Plugins**
N/A

**Host/Environment (please complete the following information):**
 - OS: macOS
 - Version 12.6.2

**Additional context**

There is some reversed boolean logic in the `handleResponse()` (lines 517-519) and I initially submitted #5998 to fix that.  However, that code path never gets called, so it's not the root cause.

I suspect that if the `beforeIndexRemoved()` override is never called, that the future never completes.

**Comment by dbwiddis** [comment]
Looking further, that `beforeIndexRemoved` is just registering an event listener and it won't be triggered until that index is later removed, so it should not have any reference to the current thread's completable future.

**Comment by minalsha** [comment]
Closing this issue since the PR is merged. Feel free to reopen if the issue still exists.
