### ISSUE TITLE
[BUG] Distribution download task is broken for lack of distribution

### ISSUE THREAD

**Issue by dblock** [opensearch-project/OpenSearch#600]
**Describe the bug**
Plugins rely on [DistributionDownloadPlugin.java](https://github.com/opensearch-project/OpenSearch/blob/main/buildSrc/src/main/java/org/opensearch/gradle/DistributionDownloadPlugin.java) to fetch published artifacts in order to run integration tests. Currently those artifacts are not available as the team is figuring out how to maven, so the task is failing.

**To Reproduce**
1. Apply all changes described in https://github.com/opensearch-project/OpenSearch-plugins#building-with-opensearch to a. plugin, such as https://github.com/opensearch-project/anomaly-detection
2. Run `./gradlew integTest` in https://github.com/opensearch-project/anomaly-detection
3. Error:

```
Execution failed for task ':integTest'.
> Could not resolve all files for configuration ':opensearch_distro_extracted_testclusters--integTest-0-1.0.0-SNAPSHOT-'.
   > Could not resolve opensearch-distribution-snapshot:opensearch:1.0.0-SNAPSHOT.
     Required by:
         project :
      > Could not resolve opensearch-distribution-snapshot:opensearch:1.0.0-SNAPSHOT.
         > Could not get resource 'https://artifacts.opensearch.org/snapshots/downloads/opensearch/opensearch-1.0.0-SNAPSHOT-linux-x86_64.tar.gz'.
            > Could not HEAD 'https://artifacts.opensearch.org/snapshots/downloads/opensearch/opensearch-1.0.0-SNAPSHOT-linux-x86_64.tar.gz'. Received status code 403 from server
```

**Expected behavior**
Find a 1.0 snapshot somewhere.

**Comment by AmiStrn** [comment]
@dblock I got the same issue, however after changing the `testDistribution` value from ARCHIVE to INTEG_TEST in my `build.gradle` the tests ran perfectly. I'm working with @saratvemulapalli to figure this out.

**Comment by minalsha** [comment]
Closing the issue since this issue is fixed. Please let us know if you see an issue still persists and reopen the issue.
