### ISSUE TITLE
[Searchable Remote Index] Add a REST API for clearing file cache

### ISSUE THREAD

**Issue by adnapibar** [opensearch-project/OpenSearch#6030]
Meta issue #4964

The API enables users to clear the file caches of one or more indices.

**Comment by andrross** [comment]
For reference, here is the existing API for clearing the (query?) cache: https://opensearch.org/docs/latest/api-reference/index-apis/clear-index-cache/

We'll want to make sure the API across different caches is clear (or maybe even reuse the same API?).
