### ISSUE TITLE
[CLEANUP] Replace elastic.co links from opensearch.yml

### ISSUE THREAD

**Issue by abbashus** [opensearch-project/OpenSearch#609]
Replace `https://www.elastic.co/guide/en/elasticsearch/reference/index.html`  with opensearch doc link. Since we don't have the documentation published yet we will point it to `opensearch.org` for now. 

Issue to update doc link once we documentation online: #610

**Comment by adnapibar** [comment]
Why can we not make the change when the OpenSearch doc links are available. I don't see reason for making this change twice.

**Comment by abbashus** [comment]
@adnapibar Can you please point me to that link? I am not aware of it yet.

**Comment by adnapibar** [comment]
I mean, when the doc website is ready, we can make this change along with all such instances across the repository. This will minimize the effort and keep the change as part of a single PR.

**Comment by dblock** [comment]
I believe this is fully resolved, please reopen if otherwise.
