### ISSUE TITLE
Purge remote translog asynchronously from a dedicated threadpool to avoid penalties on indexing or flush latencies for remote-backed indexes

### ISSUE THREAD

**Issue by ashking94** [opensearch-project/OpenSearch#6104]
**Is your feature request related to a problem? Please describe.**
As part of of #5845, the translogs are purged considering the latest metadata. This makes sure that relocation/failover after a flush does not remove all translogs which leads to failure in cluster bootstrap. We have this as async, but there is no dedicated threadpool. 

**Describe the solution you'd like**
Create a dedicated threadpool for purging of remote translog files.

**Describe alternatives you've considered**

**Additional context**

**Comment by sachinpkale** [comment]
Completed with https://github.com/opensearch-project/OpenSearch/pull/6109
