### ISSUE TITLE
[BUG] Encountered IT failure during PR build - GeoTileGridIT.testGeoShapes

### ISSUE THREAD

**Issue by ashking94** [opensearch-project/OpenSearch#6107]
Failure occurrence - https://github.com/opensearch-project/OpenSearch/pull/6086#issuecomment-1410267643

Gradle build failure - https://build.ci.opensearch.org/job/gradle-check/10300/testReport/junit/org.opensearch.geo.search.aggregations.bucket/GeoTileGridIT/testGeoShapes/

**Comment by mch2** [comment]
Duplicate https://github.com/opensearch-project/OpenSearch/issues/6054
