### ISSUE TITLE
[Feature] Support for allow partial results for Delete-by-Query

### ISSUE THREAD

**Issue by Bukhtawar** [opensearch-project/OpenSearch#615]
**Is your feature request related to a problem? Please describe.**
If one or more shards are unavailable then the search part of the delete by query recommends setting allow partial results to true while we have a hard-coded overridden value used at

https://github.com/opensearch-project/OpenSearch/blob/0e9f74e35f1255cb9ec45be3d8960aad195a9f6e/server/src/main/java/org/opensearch/index/reindex/ClientScrollableHitSource.java#L74-L81

**Describe the solution you'd like**
Provide support for partial results to be used in DBQ

**Comment by anasalkouz** [comment]
Hi @Bukhtawar, could you please provide more input why do you think this is something good to implement? If we delete partial of the query results, this might lead to more confusion to customer. In my opinion, it's better to delete all matched results or none.

**Comment by anasalkouz** [comment]
Closing this due to lack of details. @Bukhtawar feel free to reopen if needed
