### ISSUE TITLE
[PROPOSAL] Delete 1.x branch

### ISSUE THREAD

**Issue by andrross** [opensearch-project/OpenSearch#6158]
1.3.x is the end of the line for OpenSearch 1.x. We'll continue patch releases on 1.3 [through the end of 2023](https://opensearch.org/releases.html), but there will be no 1.4 release. However, we've continued backporting dependency updates to 1.x, which I think is wasted work. Can we delete this branch? (even if we changed plans and did release 1.4 we could recreate the 1.x branch from the latest on 1.3)

/cc @reta

**Comment by reta** [comment]
:+1: , thanks @andrross , I think if there are no plans for 1.x beyond 1.3, we could drop `1.x`

**Comment by andrross** [comment]
Specifically, I propose that we tag the 1.x branch with `archive/1.x` and then delete it. Does that make sense?

**Comment by saratvemulapalli** [comment]
I understand 1.3 will be EOL but I would prefer to have `archive/1.x` incase a major CVE pops up and causes breaking changes.

**Comment by andrross** [comment]
I'm going to close this as I think consistency in how the BWC tests work probably outweighs the benefit of deleting the branch (BWC testing across branches is already complicated enough). If anyone feels strongly otherwise please reopen.
