### ISSUE TITLE
[BUG] GeoTileGridIT.testGeoShapes failure

### ISSUE THREAD

**Issue by andrross** [opensearch-project/OpenSearch#6187]
Seems to be reproducible:

```
./gradlew ':modules:geo:internalClusterTest' --tests "org.opensearch.geo.search.aggregations.bucket.GeoTileGridIT.testGeoShapes" -Dtests.seed=EC3F504EF22998E0

org.opensearch.geo.search.aggregations.bucket.GeoTileGridIT > testGeoShapes FAILED
    java.lang.AssertionError: Geotile 3/7/4 has wrong doc count  expected:<36> but was:<1>
        at __randomizedtesting.SeedInfo.seed([EC3F504EF22998E0:682E8817D55CBFD]:0)
        at org.junit.Assert.fail(Assert.java:89)
        at org.junit.Assert.failNotEquals(Assert.java:835)
        at org.junit.Assert.assertEquals(Assert.java:647)
        at org.opensearch.geo.search.aggregations.bucket.GeoTileGridIT.testGeoShapes(GeoTileGridIT.java:78)
```

https://build.ci.opensearch.org/job/gradle-check/10625/consoleFull

/cc @navneet1v

**Comment by navneet1v** [comment]
Did you pull in the latest change? We have recently fixed this flaky tests

**Comment by andrross** [comment]
See the build log, but it was built against [this commit](https://github.com/opensearch-project/OpenSearch/tree/708c4f0ffc9a88119a082ed34efc7c6ff68436a7), which includes some recent changes to that test.

**Comment by navneet1v** [comment]
Let me check again. We recently fixed the tests again.

**Comment by andrross** [comment]
@navneet1v The change from #6120 was present in the failed build above. I also opened #6222 for a test failure in GeoHashGridIT that had the change from #6120 as well.

**Comment by ashking94** [comment]
Facing build failures on PR builds - https://build.ci.opensearch.org/job/gradle-check/10797/#showFailuresLink. Let's mute these until fixed?

**Comment by navneet1v** [comment]
I am doing the final tests. The PR will be out soon.

**Comment by navneet1v** [comment]
@ashking94 PR is out.

**Comment by navneet1v** [comment]
The PR is merged. Resolving the issue.
