### ISSUE TITLE
Use IndexWriter's addDocs API instead of addDoc API

### ISSUE THREAD

**Issue by itiyamas** [opensearch-project/OpenSearch#619]
Lucene does some pre and post processing, including acquiring and releasing locks, per addDoc call. AddDocuments is a batch API that reduces this overhead to 1 call per batch. For large bulk requests, these calls end up happening for every single document, increasing the overhead even further. Acquiring and releasing these locks ends up creating contention in a high concurrent environment.  The proposal is to use addDocuments call instead of addDocument for bulk requests.

**Comment by rmuir** [comment]
this method is about atomicity, not performance. it should not be used except for indexing documents in a block where you need the semantics it provides (index-time join).

**Comment by dblock** [comment]
@itiyamas @rmuir What should we do with this issue?

**Comment by msfroh** [comment]
As @rmuir said, `addDocuments` is for blocks. 

We do use `addDocuments` for the `nested` field type to guarantee that the nested documents are indexed with their enclosing doc.
