### ISSUE TITLE
[Searchable Snapshot] Assess File System caching impact on heap memory 

### ISSUE THREAD

**Issue by aabukhalil** [opensearch-project/OpenSearch#6227]
Coming from https://github.com/opensearch-project/OpenSearch/issues/4964 and based on concerns raised from https://github.com/opensearch-project/OpenSearch/pull/5641#pullrequestreview-1285817231 

The cache is configured so that the total amount of disk spaced used by all the file chunks tracked by the cache entries is bounded to some fixed value. However, the File System Cache entries `<Path, IndexInput>` are tracked in heap memory and number of cache entries (IndexInput) is not bounded. The pathological case here in terms of heap size would be Lucene indexes with huge numbers of tiny segment files so that the heap is exhausted before the disk space limit.

This task is to decide how to bound heap usage by File System Cache.

I think we these options:
- Proof that this is not needed by computing heap footprint of each IndexInput and see if it is anyhow practical to really impact heap usage significantly before hitting other limits in the system (like file system size, file handlers, ...)
- If needed, then we need to implement heap circuit breaker. As initial release circuit breaker will just block new requests rather than trying to LRU evict entries because this will simplify cache design to not have two eviction policies (one on disk size and one on heap size which will increase chances of deadlock and resource starvation). Options for circuit breaker implementation:
    - one simple option to implement is to set max number of cache entries
    - another option is to implement actual heap circuit breaker based on heap usage

**Comment by adnapibar** [comment]
Ran a few experiments to figure out the heap memory footprint of the file cache. It doesn't look to be significant to prioritize a solution at this point for GA.  Single node cluster with 1 gb heap memory, with 1M docs in the *remote snapshot* index 

1 shard

![image](https://user-images.githubusercontent.com/2838888/222641528-b8d2b04b-18cf-4b16-9011-34b2fe4b36b0.png)

10 shards

![image](https://user-images.githubusercontent.com/2838888/222641801-d65e86ee-3ed3-4593-bd6f-24b49271892d.png)

50 shards

![image](https://user-images.githubusercontent.com/2838888/222641880-c9c54cef-266a-4bd6-a481-8f13894b4398.png)

**Comment by andrross** [comment]
I think we will need to at least do this, even if heap size isn't a constraint:

> one simple option to implement is to set max number of cache entries

See [this discussion](https://github.com/opensearch-project/OpenSearch/issues/6295#issuecomment-1453240299), but 8MB chunk sizes and an 8TB disk will lead to an explosion of files created in the cache, given the current design of one file per chunk. We should bound this number at some generally known-safe value even if most configurations won't run into that limit.

**Comment by adnapibar** [comment]
As discussed offline - it's not obvious what should be a good default max value for the number of cache entries. The second option of implementing a circuit breaker based on heap usage seems better. I have created an issue #6540
