### ISSUE TITLE
[Remote Translog] Purge older translog metadata files for remote-backed indexes 

### ISSUE THREAD

**Issue by ashking94** [opensearch-project/OpenSearch#6239]
**Is your feature request related to a problem? Please describe.**
With every translog upload, a metadata file is uploaded which keeps track of current translog readers. The same is also used at the  time of recovery/relocation for downloading translog. There is mechanism present in code to determine the latest translog metadata from the list of continuously growing list of metadata files. We need to continuously purge older translog metadata files from remote store.

**Describe the solution you'd like**
We keep only the latest metadata file.

**Comment by sachinpkale** [comment]
Fixed as part of https://github.com/opensearch-project/OpenSearch/pull/6238
