### ISSUE TITLE
[Searchable Snapshots] Prevent search node startup if there are more than a single data path

### ISSUE THREAD

**Issue by kotwanikunal** [opensearch-project/OpenSearch#6274]
**Is your feature request related to a problem? Please describe.**
- For a search node, we will store the file cache as a part of the default data path defined by the user.
- To simplify the approach for search nodes, we should fail node startup if there are multiple data paths configured.

**Describe the solution you'd like**
- At node bootstrap, check if the node has `search` role and multiple data paths, if yes, fail the bootstrap. 

**Describe alternatives you've considered**
- N/A

**Additional context**
- N/A

**Comment by dblock** [comment]
@kotwanikunal Link this back to a meta issue, alone it lacks context.

**Comment by kotwanikunal** [comment]
> @kotwanikunal Link this back to a meta issue, alone it lacks context.

Thanks. Missed linking this one.
