### ISSUE TITLE
[FEATURE] Add support to Gradle run task to spawn OpenSearch instances in debug mode

### ISSUE THREAD

**Issue by reta** [opensearch-project/OpenSearch#6276]
**Is your feature request related to a problem? Please describe.**
In OpenSearch, there is quite useful `run` Gradle task which allows to run OpenSearch instances locally for development [1].

```
./gradlew run
```

This task could also accept `--debug-jvm` option which tries to attach to running OpenSearch instance(s) instead. However, there is no out of the box option to run OpenSearch instance(s) locally with debugger support.

[1] https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#run-opensearch

**Describe the solution you'd like**
During the development, ability to run OpenSearch with debugger from time to time is quite handy. I am suggesting to add a new option `--debug-server-jvm` (to differentiate from `--debug-jvm`):

```
./gradlew run --debug-server-jvm
```
It will add the following arguments to JVM `-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=<port>` (default debug port is `5005`) so it will be possible to attach the debugger for running OpenSearch local process(es).

@dblock @andrross curious what do you think folks, thank you

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by andrross** [comment]
> This task could also accept --debug-jvm option which tries to attach to running OpenSearch instance(s) instead. However, there is no out of the box option to run OpenSearch instance(s) locally with debugger support.

The current behavior is that you can run OpenSearch as a debug client and with `--debug-jvm` and it expects to find a debug server, or else fails to start. Right?

I've always found that backwards to my expectation...I usually prefer for OpenSearch to start a debug server and I can attach a debug client to it, so I'm all for this new `--debug-server-jvm` option.

**Comment by reta** [comment]
> The current behavior is that you can run OpenSearch as a debug client and with `--debug-jvm` and it expects to find a debug server, or else fails to start. Right?

Exactly!
