### ISSUE TITLE
Support gradle `run` task for core plugins

### ISSUE THREAD

**Issue by lukas-vlcek** [opensearch-project/OpenSearch#6285]
**Is your feature request related to a problem? Please describe.**

When working on a "core" plugins there does not seem to be OOTB support for the `run` tasks that would automatically deploy the plugin into testcluster.

**Describe the solution you'd like**

It would be useful to be able to do something like `./gradlew run --plugins "xx,yy"` and get testcluster with core plugins xx and yy deployed.

**Describe alternatives you've considered**

I described a manual workaround here:
<https://gist.github.com/lukas-vlcek/26fd54fb7ba25debb5b5c5c8c390ad79>

**Additional context**

Core plugin authors would be :smile:

**Comment by dbwiddis** [comment]
Sounds like a good idea!

**Comment by dblock** [comment]
https://github.com/opensearch-project/OpenSearch/pull/11844 has this implemented.
