### ISSUE TITLE
Store Permissions in Index

### ISSUE THREAD

**Issue by scrawfor99** [opensearch-project/OpenSearch#6303]
We want to be able to store permissions in a system index instead of them being stored in a local map. 

When this issue is resolved, we should be able to perform the following operations on an index to: 

- [ ] Add permissions to the storage of the index 
- [ ] Fetch permissions from index store
- [ ] Delete permissions from the index store 
- [ ] Use replicated storage system native to OpenSearch 
- [ ] Multi-node cluster support

**Comment by peternied** [comment]
- Distinguish between lucence index and system index seems a little too detailed, lets conflate these together as 'system' index
- Using the word 'client' is that a user creating a REST call, or does that represent a PermissionService?  If the later, callout the overall scenario to provide context for the broader audience
- Include more 'whys' in this doc.  What is implemented, why isn't it enough? Why a system index?  What other options are used in the OpenSearch system, why not use them?
- Is this strongly or eventually consistent? 
- Where do the replicate(s) live, do we use read replicas to make 'read' operations faster vs writes?

**Comment by scrawfor99** [comment]
Thank you for your great feedback Peter. 

I am going to write the responses down here as well as update the original so that someone else can come along and not run into the same questions you have but also it is easy to see the specific answers. 


- Distinguish between lucence index and system index seems a little too detailed, lets conflate these together as 'system' index
  -  Will swap. The intention was to show down to shards since that gives replication but I agree it does not really matter for the design and is abstracted away from the user. 
- Using the word 'client' is that a user creating a REST call, or does that represent a PermissionService? If the later, callout the overall scenario to provide context for the broader audience
  - The client is supposed to be the PermissionService like you mention. I will clarify that in the document so it is clear. 
- Include more 'whys' in this doc. What is implemented, why isn't it enough? Why a system index? What other options are used in the OpenSearch system, why not use them?
  - I will update this in the original. Briefly, right now we just have a single store of all configurations. Likewise, we just have a hashmap holding permissions. 
- Is this strongly or eventually consistent?
  - Technically this will be eventually consistent. You can force it to be strongly consistent by using a request id so that we are able to ensure the replica shard is not hit before it is updated. 
- Where do the replicate(s) live, do we use read replicas to make 'read' operations faster vs writes?
  - Replica shards will just be stored the same as the normal indices with the caveat that OpenSearch always distributes shards across different nodes. I think we should have read replicas but we will need to use the id'ing method of preventing asynchronous issues.
