### ISSUE TITLE
[BUG] PutIndexTemplateRequest not populating the data_stream attribute

### ISSUE THREAD

**Issue by YANG-DB** [opensearch-project/OpenSearch#6308]
**Describe the bug**
When creating an Index template request using the `PutIndexTemplateRequest`, it doesn’t support `data_stream` field which is actually supported in the Rest equivalent API.

This is due to the fact that `PutIndexTemplateRequest` doesn’t override the default includeDataStreams method
```
default boolean includeDataStreams() {
        return false;
    }
```
The documentation explicitly allow this behaviour :
https://opensearch.org/docs/latest/opensearch/data-streams/

**To Reproduce**
1. Create a `PutIndexTemplateRequest` request with index pattern
2. Attempt creating a data_stream with that explicit index pattern
3. Request fails with `IllegalArgumentException: no matching index template found for data stream [...]`

**Expected behavior**
Creation of the data_stream should succeed as if it was created using the similar Rest based API

**Plugins**

Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**
 - Version [e.g. 2.5]

**Additional context**

**Comment by gaobinlong** [comment]
`PutIndexTemplateRequest` corresponds to the legacy create or update template API which will be deprecated in the future, and it doesn't support creating data stream templates, so instead,  `PutComposableIndexTemplateRequest` should be used to create a data stream templates: https://github.com/opensearch-project/OpenSearch/blob/e8c6f0f1b15acdfbeeba84a551a2b42024f8502b/client/rest-high-level/src/main/java/org/opensearch/client/indices/PutComposableIndexTemplateRequest.java#L53
, `PutComposableIndexTemplateRequest` corresponds to the template v2 API which supports creating data stream templates.
