### ISSUE TITLE
[BUG] The date fields are getting highlighted wrongly in response to query_string query when the search pattern with *** is used.

### ISSUE THREAD

**Issue by SuryaVeeragani** [opensearch-project/OpenSearch#6328]
**Description**
In an opensearch1.2.3 env, we created an index with fields Name("type": "text") and CreationDate("type" : "date"), in the name field we stored the value "*** Test Line" and in the date field, we are storing some date in epoch_millis format. When we run query_string query with the pattern "***", the date field is getting highlighted wrongly. 

**To Reproduce**
1. Create an index with following mappings and settings mentioned in the below text file.
[map.txt](https://github.com/opensearch-project/OpenSearch/files/10743017/map.txt)
`curl -XPUT -u"$pwd" --insecure https://localhost:9200/newtestindex2 -H 'Content-Type: application/json'  -d @/tmp/map.json
{"acknowledged":true,"shards_acknowledged":true,"index":"newtestindex2"}`

2. Create a document
`curl -XPUT -u"$pwd" --insecure https://localhost:9200/newtestindex2/_doc/1 -H 'Content-Type: application/json'  -d '{"CreationDate" : 1675411460000,"Name" : "*** Test Line"}'
{"_index":"newtestindex2","_type":"_doc","_id":"1","_version":1,"result":"created","_shards":{"total":2,"successful":2,"failed":0},"_seq_no":0,"_primary_term":1}`

3. Run the following query with pattern "***"
`curl -XGET -u"$pwd" --insecure "https://localhost:9200/newtestindex2/_doc/_search?pretty&size=25&from=0&search_type=query_then_fetch"  -H 'Content-Type: application/json' -d '{  "highlight": {    "number_of_fragments": 0, "pre_tags": [ "" ],    "post_tags": [ "" ],    "fields": { "CreationDate": { "require_field_match": false},      "Name": { "require_field_match": false},      "Name._ngram": {  "require_field_match": false }    }  },  "query": {                      "query_string": { "default_operator": "and","query": "***", "tie_breaker": 1, "fields": ["Name^2.5"] } },  "profile": true,  "_source": {    "includes": [ "CreationDate", "Name"    ]  },  "sort": [ {  "_score": "desc"    }  ]}'`

4. In response of the above query, we can see that CreationDate field is also present in "highlight", whereas only Name and Name._ngram fields are expected to be highlighted
`"highlight" : {
          "CreationDate" : [
            "1675411460000"
          ],
          "Name._ngram" : [
            "*** Test Line"
          ],
          "Name" : [
            "*** Test Line"
          ]
        }`

**Expected behavior**
"Name._ngram" and "Name" fields are expected in the response as they have "*** Test Line", whereas CreationDate also appeared in the highlights even though there is no match with the pattern "***".

**Plugins**
[root@testsveeraga6feb-esdata0 tmp]# curl -XGET -u"$pwd" --insecure https://localhost:9200/_cat/plugins?v
name                     component                        version
testsveeraga6feb-esdata0 analysis-icu                     1.2.3
testsveeraga6feb-esdata0 analysis-kuromoji                1.2.3
testsveeraga6feb-esdata0 analysis-nori                    1.2.3
testsveeraga6feb-esdata0 analysis-smartcn                 1.2.3
testsveeraga6feb-esdata0 ingest-attachment                1.2.3
testsveeraga6feb-esdata0 ingest-langdetect                1.2.3
testsveeraga6feb-esdata0 ltr                              1.5.4-os1.2.3
testsveeraga6feb-esdata0 opensearch-knn                   1.2.3.0-SNAPSHOT
testsveeraga6feb-esdata0 opensearch-olt-plugin            1.2.3
testsveeraga6feb-esdata0 opensearch-replace-filter-plugin 1.2.3
testsveeraga6feb-esdata0 opensearch-security              1.2.3.0
testsveeraga6feb-esdata0 repository-s3                    1.2.3
testsveeraga6feb-esdata2 analysis-icu                     1.2.3
testsveeraga6feb-esdata2 analysis-kuromoji                1.2.3
testsveeraga6feb-esdata2 analysis-nori                    1.2.3
testsveeraga6feb-esdata2 analysis-smartcn                 1.2.3
testsveeraga6feb-esdata2 ingest-attachment                1.2.3
testsveeraga6feb-esdata2 ingest-langdetect                1.2.3
testsveeraga6feb-esdata2 ltr                              1.5.4-os1.2.3
testsveeraga6feb-esdata2 opensearch-knn                   1.2.3.0-SNAPSHOT
testsveeraga6feb-esdata2 opensearch-olt-plugin            1.2.3
testsveeraga6feb-esdata2 opensearch-replace-filter-plugin 1.2.3
testsveeraga6feb-esdata2 opensearch-security              1.2.3.0
testsveeraga6feb-esdata2 repository-s3                    1.2.3
testsveeraga6feb-esdata1 analysis-icu                     1.2.3
testsveeraga6feb-esdata1 analysis-kuromoji                1.2.3
testsveeraga6feb-esdata1 analysis-nori                    1.2.3
testsveeraga6feb-esdata1 analysis-smartcn                 1.2.3
testsveeraga6feb-esdata1 ingest-attachment                1.2.3
testsveeraga6feb-esdata1 ingest-langdetect                1.2.3
testsveeraga6feb-esdata1 ltr                              1.5.4-os1.2.3
testsveeraga6feb-esdata1 opensearch-knn                   1.2.3.0-SNAPSHOT
testsveeraga6feb-esdata1 opensearch-olt-plugin            1.2.3
testsveeraga6feb-esdata1 opensearch-replace-filter-plugin 1.2.3
testsveeraga6feb-esdata1 opensearch-security              1.2.3.0
testsveeraga6feb-esdata1 repository-s3                    1.2.3
testsveeraga6feb-esdata3 analysis-icu                     1.2.3
testsveeraga6feb-esdata3 analysis-kuromoji                1.2.3
testsveeraga6feb-esdata3 analysis-nori                    1.2.3
testsveeraga6feb-esdata3 analysis-smartcn                 1.2.3
testsveeraga6feb-esdata3 ingest-attachment                1.2.3
testsveeraga6feb-esdata3 ingest-langdetect                1.2.3
testsveeraga6feb-esdata3 ltr                              1.5.4-os1.2.3
testsveeraga6feb-esdata3 opensearch-knn                   1.2.3.0-SNAPSHOT
testsveeraga6feb-esdata3 opensearch-olt-plugin            1.2.3
testsveeraga6feb-esdata3 opensearch-replace-filter-plugin 1.2.3
testsveeraga6feb-esdata3 opensearch-security              1.2.3.0
testsveeraga6feb-esdata3 repository-s3                    1.2.3

**Screenshots**
[Logs.txt](https://github.com/opensearch-project/OpenSearch/files/10743163/Logs.txt)

**Host/Environment (please complete the following information):**
 - OS: Linux
 - Version 4.14.35-2047.521.4.el7uek.x86_64

**Additional context**

**Comment by saratvemulapalli** [comment]
@SuryaVeeragani looks like you are using OpenSearch 1.2.x, can you repro the problem on 2.x?

**Comment by msfroh** [comment]
@SuryaVeeragani, the issue here seems to be that `*` in a `query_string` query is a wildcard, so a query for `***` means "match anything", so the `CreationDate` field *does* match the query string.

If you want to search for literal `***`, you would need to escape the `*` characters to indicate that they are not wildcard operators.

**Comment by dblock** [comment]
Thanks @msfroh. I think this is working as designed, @SuryaVeeragani feel free to reopen the issue if you disagree.
