### ISSUE TITLE
opensearch-env always sources /etc/default/elasticsearch even if you specify over-ride of ES_PATH_CONF at launch

### ISSUE THREAD

**Issue by mhoydis13** [opensearch-project/OpenSearch#633]
Line 81 of bin/opensearch-env will always source the environment from the hardcoded default environment file /etc/default/elasticsearch.  It will do this even if you over-ride the value of ES_PATH_CONF on launch (for example, from the systemd unit or some other launch method).  

https://github.com/opensearch-project/OpenSearch/blob/d09249c62760609040cd1aa190b8d7495c2eb540/distribution/src/bin/opensearch-env#L81

This is problematic if you are attempting to run multiple instances of opensearch on the same host.  In this case, you'd want to over-ride ES_PATH_CONF per instance from the launching mechanism, and not source the default environment.  

I suggest source'ing the default environment file on on the condition ES_PATH_CONF is not already defined.  Like this:  

> if [ -z "$ES_PATH_CONF" ]; then
>   source /etc/default/elasticsearch
> fi

This style test is consistent with other tests in this same script, and allows for the environment to be over-ridden from the launching mechanism, allowing for multiple opensearch instances on the same host.

**Comment by xuezhou25** [comment]
Hi @mhoydis13 
Are you talking about Opensearch or Elasticsearch? We don't have this code source `/etc/default/elasticsearch` cause it should be all renamed. Could you give more clarification on this issue?

**Comment by mhoydis13** [comment]
I did mean opensearch.  I'm working with both OpenDistro (which runs on elasticsearch-oss) and OpenSearch.  Github Issues from the OpenDistro project are being redirected to the OpenSearch github issues.  
The information I posted is still relatively correct.  Just go like s/elasticsearch/opensearch/g

**Comment by adnapibar** [comment]
Closed by #875
