### ISSUE TITLE
[BUG] Opensearch repository-s3 plugin cannot register s3 bucket as repository

### ISSUE THREAD

**Issue by annasunny** [opensearch-project/OpenSearch#6332]
**Describe the bug**
I am running an Opensearch cluster using Opensearch Operator in AWS EKS. I have created a k8s ServiceAccount in order to access an AWS S3 bucket to use for my snapshot but i get the following error:

```
Caused by: org.opensearch.repositories.RepositoryVerificationException: [<my-s3-repository-name>] path [<my-s3-path>] is not accessible on cluster-manager node
Caused by: java.io.IOException: Unable to upload object [test/tests--xxxxxxxxxxxxx/master.dat] using a single upload 
Caused by: org.opensearch.common.io.stream.NotSerializableExceptionWrapper: sdk_client_exception: Failed to connect to service endpoint: 
Caused by: java.io.IOException: Connect timed out
```

**To Reproduce**
1. Deploy an Opensearch cluster (image version 2.4.0) with repository-s3 plugin installed
2. Configure a Kubernetes service account to assume an IAM role
3. Configure s3.client.default.identity_token_file: /var/run/secrets/eks.amazonaws.com/serviceaccount/token
4. Go to opensearch dashboards, use dev tools to make a PUT request:
```
PUT _snapshot/<my-s3-repository-name>
{
  "type": "s3",
  "settings": {
    "bucket": "<my-s3-bucket-name>",
    "base_path": "<my-s3-path>"
  }
}
```

**Expected behavior**
The repository-s3 plugin should be able to register my s3 bucket. 

**Plugins**
repository-s3 plugin

**Screenshots**
<img width="1486" alt="Screen Shot 2023-02-15 at 3 47 59 PM" src="https://user-images.githubusercontent.com/5370146/219220852-b64a3de1-4d3d-46b4-a3cc-ee07bff3ccb2.png">
<img width="1152" alt="Screen Shot 2023-02-15 at 3 51 58 PM" src="https://user-images.githubusercontent.com/5370146/219221585-e973ddde-86dc-48a5-825a-66edc4497ac1.png">

**Host/Environment (please complete the following information):**
 - AWS EKS version 1.21
 - Opensearch cluster (image version 2.4.0) deployed with Opensearch Operator (version 2.1.1)

**Comment by reta** [comment]
I suspect you may need to specify region [1], but it would be helpful if you share the `s3.client.default.xxx` settings from `opensearch.yml`, thank you.

[1] https://opensearch.org/docs/latest/tuning-your-cluster/availability-and-recovery/snapshots/snapshot-restore/#amazon-s3

**Comment by annasunny** [comment]
Thank you @reta ! I'm using aws IAM roles for Kubernetes service accounts for authentication.
So I'm not using the `access_key` or `secret_key`, but I'm using the `AWS_WEB_IDENTITY_TOKEN_FILE`. 
Currently, I don't have any customized `s3.client.default.xxx `settings in my `opensearch.yml`, but I add one.

**Comment by annasunny** [comment]
There is a doc from Elastic community related to this issue. Might be helpful? 
https://www.elastic.co/guide/en/elasticsearch/reference/8.6/repository-s3.html#iam-kubernetes-service-accounts
`you need to add a symlink to the $AWS_WEB_IDENTITY_TOKEN_FILE environment variable (which should be automatically set by a Kubernetes pod) in the S3 repository config directory, so the repository can have the read access for the service account (a repository can’t read any files outside its config directory)`

**Comment by reta** [comment]
> There is a doc from Elastic community related to this issue. Might be helpful?

Thanks @annasunny , will update documentation to suggest using links instead of altering security policy

**Comment by annasunny** [comment]
Hi @reta, From this opensearch doc looks like another solution: https://opensearch.org/docs/2.4/tuning-your-cluster/availability-and-recovery/snapshots/snapshot-restore/.  
How can I update this `s3.client.default.identity_token_file` in my` opensearch.yml`? 

 
<img width="928" alt="Screen Shot 2023-02-15 at 5 34 58 PM" src="https://user-images.githubusercontent.com/5370146/219241376-be53caa0-7c1e-407c-a5a1-c6823a07bb67.png">

**Comment by reta** [comment]
> Looks like I can also update this s3.client.default.identity_token_file in my opensearch.yml?

That's correct but the location where `s3.client.default.identity_token_file` points to should be accessible by the `s3-repository plugin` (as the example shows).

**Comment by annasunny** [comment]
@reta I don't get that... Could you point me where/how I can update the `s3.client.default.identity_token_file`? 
I don't find it's default value anywhere from the [operator code](https://github.com/Opster/opensearch-k8s-operator) nor the [opensearch code](https://github.com/opensearch-project).

**Comment by annasunny** [comment]
https://github.com/Opster/opensearch-k8s-operator/blob/bce06fb94f2bec398e069dc7f59e69718e9d66b3/docs/userguide/main.md#add-secrets-to-keystore gives an example for editing :
`s3.client.default.access_key` and `s3.client.default.secret_key`, but I didn't find anywhere for `3.client.default.identity_token_file`

**Comment by reta** [comment]
@annasunny I think this section [1] is of your interest, the values in question should appear in `opensearch.yml`

[1] https://github.com/Opster/opensearch-k8s-operator/blob/bce06fb94f2bec398e069dc7f59e69718e9d66b3/docs/userguide/main.md#configuring-opensearchyml

**Comment by reta** [comment]
@annasunny I think we could close this one, since this is configuration issue

**Comment by kartg** [comment]
@annasunny I'll go ahead and close this. Please feel free to reopen if the issue persists and we can assist.
