### ISSUE TITLE
[BUG] [Searchable Snapshots] Potential deadlock in ConcurrentInvocationLinearizer

### ISSUE THREAD

**Issue by andrross** [opensearch-project/OpenSearch#6437]
**Describe the bug**
The key precondition is that the executor given to [ConcurrentInvocationLinearizer](https://github.com/opensearch-project/OpenSearch/blob/4dd0c5f00f6d21d3dbc29afcb2454d927ce7817f/server/src/main/java/org/opensearch/index/store/remote/utils/ConcurrentInvocationLinearizer.java) must be the same one that submits work to the ConcurrentInvocationLinearizer (this is exactly how it is wired up in the searchable snapshot code today). The deadlock is as follows.
- Assume executor with 2 threads
- Calling thread 1 submits a task to `ConcurrentInvocationLinearizer::linearize` with key "foo" and blocks on returned future
- Calling thread 2 submits a task to `ConcurrentInvocationLinearizer::linearize` with key "foo" and blocks on returned future
- Async thread in the completable future (from [`supplyAsync`](https://github.com/opensearch-project/OpenSearch/blob/4dd0c5f00f6d21d3dbc29afcb2454d927ce7817f/server/src/main/java/org/opensearch/index/store/remote/utils/ConcurrentInvocationLinearizer.java#L46)) is queued on executor to complete both futures returned above (this is racing with calling thread 2 and there is no guarantee whether this will happen before or after thread 2 starts work)
- Deadlock

**To Reproduce**
```
public void testDeadlock() throws Exception {
    final ExecutorService executorService = Executors.newFixedThreadPool(4);
    final ConcurrentInvocationLinearizer<String, String> invocationLinearizer = new ConcurrentInvocationLinearizer<>(executorService);
    List<Future<?>> futures = new ArrayList<>();
    for (int i = 0; i < 4; i++) {
        futures.add(executorService.submit(() -> invocationLinearizer.linearize("input", s -> "result").get()));
    }
    for (Future<?> f : futures) {
        f.get();
    }
}
```

**Additional context**
It is possible this is the cause of #6295. I found this bug independently through unit tests and haven't confirmed it is related to that issue though.

**Comment by reta** [comment]
@andrross this is interesting, I totally agree that using executors as such would deadlock but it looks that the implementation snippet is "abusing" the async flows:

```
 invocationLinearizer.linearize("input", s -> "result") - 
```

Is already async and returns CompletableFuture, we should not wrap it into another async call. Instead, use composition:thenCompose, thenCombine, ... (depending on use case)

**Comment by andrross** [comment]
@reta I agree. However, the code using this is essentially doing that pattern. I think the issue is that the calling code is fundamentally synchronous, e.g. when `IndexInput.readByte()` is invoked we have to return that byte. If that call results in downloading data we want to make sure concurrent threads asking for the same resource don't duplicate the work, but that's not the same as going fully async.

My inclination is to remove the async method from [TransferManager](https://github.com/opensearch-project/OpenSearch/blob/d9db89c3fbb8589526461a4623015dd5e892fb20/server/src/main/java/org/opensearch/index/store/remote/utils/TransferManager.java#L52), since we have no use case currently that does anything other than immediately block on the result. I could then remove the future from the ConcurrentInvocationLinearizer API as well. What do you think?

**Comment by andrross** [comment]
Also the current implementation unnecessarily uses an extra thread. The calling thread that initiates the download kicks off another thread to do the download and blocks on the result. The first thread could have just done the work itself.

**Comment by reta** [comment]
Thanks @andrross 

> My inclination is to remove the async method from [TransferManager](https://github.com/opensearch-project/OpenSearch/blob/d9db89c3fbb8589526461a4623015dd5e892fb20/server/src/main/java/org/opensearch/index/store/remote/utils/TransferManager.java#L52), since we have no use case currently that does anything other than immediately block on the result. I could then remove the future from the ConcurrentInvocationLinearizer API as well. What do you think?

If it is never used as async - definitely +1 to remove it
