### ISSUE TITLE
[BUG] Excluding system indices from snapshot fails with index_not_found_exception

### ISSUE THREAD

**Issue by pasztorl** [opensearch-project/OpenSearch#6458]
**Describe the bug**
When I want to restore a snapshot without .opendistro_security it fails.
Below in the example snapshot created with 2.2.1, The restore target is 2.4.1

**To Reproduce**

```
PUT _snapshot/backup/1
{
  "indices": "-.opendistro_security,-.kibana_1,-security-auditlog*",
  "include_global_state": false
}

response:

{
	"error": {
		"root_cause": [
			{
				"type": "index_not_found_exception",
				"reason": "no such index [-.opendistro_security]",
				"index": "-.opendistro_security",
				"resource.id": "-.opendistro_security",
				"resource.type": "index_or_alias",
				"index_uuid": "_na_"
			}
		],
		"type": "index_not_found_exception",
		"reason": "no such index [-.opendistro_security]",
		"index": "-.opendistro_security",
		"resource.id": "-.opendistro_security",
		"resource.type": "index_or_alias",
		"index_uuid": "_na_"
	},
	"status": 404
}
```
```
GET _cat/indices/.opendistro_security
{}

response:

[
	"green open .opendistro_security 95EuPX8yRnCBF7okGMUJvA 1 2 9 2 142.3kb 47.4kb"
]
```
So this index is exists, but can not skip from backup.

When I use:
```
PUT _snapshot/backup/1
{}
```
Works well and I use this way, BUT..

I wanted to restore the snapshot to an empty cluster this way:
```
POST _snapshot/backup/1/_restore
{
  "indices": "-.opendistro_security,-.kibana_1,-security-auditlog*",
  "include_global_state": false
}
```

and I got this response:
```
{
	"error": {
		"root_cause": [
			{
				"type": "security_exception",
				"reason": "no permissions for [] and User [name=admin, backend_roles=[manage_snapshots, admin], requestedTenant=null]"
			}
		],
		"type": "security_exception",
		"reason": "no permissions for [] and User [name=admin, backend_roles=[manage_snapshots, admin], requestedTenant=null]"
	},
	"status": 403
}
```
and in the log I got:
```
cluster:admin/snapshot/restore for '.opendistro_security' index is not allowed for a regular user
```
So I can't do backup without this index and I can't restore a backup which include this index.
Am I doing something wrong?

**Expected behavior**
Full backup (without skipping indexes) works well, good.
Restore from backup excluding .opendistro_security index should work too.

**Plugins**
s3, prometheus-exporter

**Screenshots**
I think screenshot not needed.

**Host/Environment (please complete the following information):**
Kubernetes 1.24.x, deployed with Opensearch operator 2.2.1

**Additional context**
n/a

**Comment by dblock** [comment]
@peternied do you know what prevents this index to be snapshot?

**Comment by peternied** [comment]
@pasztorl That error message `cluster:admin/snapshot/restore for '.opendistro_security' index is not allowed for a regular user` might be incorrect.  I've created a pull request to resolve this https://github.com/opensearch-project/security/pull/2525

It also looks like @Rishikesh1159 has started to look into this issue, they might be able to confirm additional troubleshooting steps.

**Comment by Rishikesh1159** [comment]
Sorry @peternied, I am not looking into this issue. I mistakenly assigned this issue to myself. I unassigned the myself and removed "CCI label"

**Comment by peternied** [comment]
@pasztorl I've looked into the kind of issue that is triggered as you've reported it.  Good news, this issue has been fixed and will be available in the 2.7 release of OpenSearch.  Duplicating this issue to https://github.com/opensearch-project/security/issues/1652.

**Comment by pasztorl** [comment]
Thanks for the update, great news! I see that the fix will be on 2.7. Now I locked on an older version because the application what I use not tested/supported at that version and who know when it will. There is a suggested workaround how I can backup/restore data from 2.2/2.4?

**Comment by peternied** [comment]
@scrawfor99 Do you know of a workaround?

**Comment by ict-one-nl** [comment]
Yes, use an admin certificate rather than basic auth. With the cert auth you can circumvent the error.
