### ISSUE TITLE
Metricbeat: “error getting group status: open /proc/<PID>/cgroup”

### ISSUE THREAD

**Issue by anaconda2196** [opensearch-project/OpenSearch#6484]
OpenSearch v2.5.0

Running Metricbeat-oss (docker.elastic.co/beats/metricbeat-oss:7.10.2) seeing the following error in logs:

instance/metrics.go:285 error getting group status: open `/proc/<PID>/cgroup`: no such file or directory"

Using ref document - https://www.elastic.co/guide/en/beats/metricbeat/7.10/running-on-kubernetes.html

Any suggestions or pointers to resources would be very much appreciated.

**Comment by minalsha** [comment]
@elfisher , @dblock  any feedback?

**Comment by dblock** [comment]
This looks similar to https://discuss.elastic.co/t/metricbeat-k8s-error-getting-group-status-open-proc-pid-cgroup/255371/12 and https://github.com/elastic/beats/issues/34670. I think this is an issue in Metricbeat, not OpenSearch.

**Comment by minalsha** [comment]
chatted with @brijos. We do not support Metricbeat in OpenSearch. Your question is more pertaining to a bug in Metricbeat and Elastic and hence closing this issue. Thanks
