### ISSUE TITLE
[BUG] Readme links to invalid Url

### ISSUE THREAD

**Issue by monu-aws** [opensearch-project/OpenSearch#6487]
**Describe the bug**
Readme links to invalid Url.

OpenSearch is [a community-driven, open source fork](https://aws.amazon.com/blogs/opensource/introducing-opensearch/) of [Elasticsearch](https://en.wikipedia.org/wiki/Elasticsearch) and [Kibana](https://en.wikipedia.org/wiki/Kibana) following the [licence change](https://opensource.org/node/1099) in early 2021. We're looking to sustain (and evolve!) a search and analytics suite for the multitude of businesses who are dependent on the rights granted by the original, [Apache v2.0 License](https://github.com/opensearch-project/OpenSearch/blob/main/LICENSE.txt).

licence change https://opensource.org/node/1099 - invalid

**Comment by kartg** [comment]
hi @monu-aws! I've [raised a PR](https://github.com/opensearch-project/OpenSearch/pull/6498) to update the link. Please feel free to contribute to the project if you spot any other errors in the future. Thanks for bringing this to our attention!
