### ISSUE TITLE
[BUG] JavaDoc uses a combination of &#64; and {@code

### ISSUE THREAD

**Issue by dblock** [opensearch-project/OpenSearch#649]
**Describe the bug**

AnalysisPlugin.java and others have this:

```
<pre>{@code
 * public class MyDiscoveryPlugin extends Plugin implements DiscoveryPlugin {
 *     &#64;Override
 ```

This doesn't actually render `@` in JavaDoc, it's either `@code` or `&#64;`, and `@literal @` inserts an extra space. So the solution is to get rid of `{@code` and escape `<` and `>`.

**Comment by setiah** [comment]
+1, I can confirm the same from published javadocs (see below)

```
 public class AnalysisPhoneticPlugin extends Plugin implements AnalysisPlugin {
     &#64;Override
     public Map<String, AnalysisProvider<TokenFilterFactory>> getTokenFilters() {
         return singletonMap("phonetic", PhoneticTokenFilterFactory::new);
     }
 }
```
