### ISSUE TITLE
[BUG] Inconsistent AWS Opensearch ingest attachment processor behaviour

### ISSUE THREAD

**Issue by pcvijayvignesh** [opensearch-project/OpenSearch#6494]
We are using AWS OpenSearch for one of our application. We have configured ingest attachment processor for extracting text from .docx files. 

Here is our environment setup details, 

Note: For DEV/QA, we use same instance with different index name.  

|Details|DEV/QA|UAT|
|-------|------|---|
|Version|1.1|1.1|
|Service Software Version|R20220223-P6|R20220928-P1|
|Dedicated Master Node|No|Yes|
|No of nodes|2|3|
|Instance Type|m5.large.search|m6g.xlarge.search|

**Flow:** Base64 of the .docx file is sent to the ingest attachment processor during indexing time, the text is extracted and saved into a field on opensearch. 

**Issue ( Inconsistent behavior):** Specific .docx file is not parsable by OpenSearch Attachment Processor and throwing the below error.

    [logstash.outputs.amazonelasticsearch][main][] Could not index event to Elasticsearch. {:status=>400, :action=>["index", {:_id=>"25220", :_index=>"test_index", :_type=>"_doc", :_routing=>nil, :pipeline=>"attachment_dev"}, #<LogStash::Event:0x904adf8>], :response=>{"index"=>{"_index"=>"test_index", "_type"=>"_doc", "_id"=>"25220", "status"=>400, "error"=>{"type"=>"parse_exception", "reason"=>"Error parsing document in field [form_data]", "caused_by"=>{"type"=>"tika_exception", "reason"=>"TIKA-198: Illegal IOException from org.apache.tika.parser.ParserDecorator$2@298392f1", "caused_by"=>{"type"=>"i_o_exception", "reason"=>"No such file or directory"}}}}}.

I use "on_failure" configuration to handle this. But the behavior is inconsistent. When I try to simulate(_ingest/pipeline/<>/_simulate) the text extraction by providing the base64 in request body, 

On DEV/QA - If I hit 5 times continuously, 4 time text extraction is happening properly and rest 1 time text is not getting extracted and on_failure method is executed. 

On UAT - If I hit 5 times continuously, all the five times text is not getting extracted and on_failure method is executed. 

Ingest attachment configuration and plugin version ( 1.1.0 ) is same between both the environments. Kindly help in resolving this issue.

**Comment by bbarani** [comment]
Similar issue reported on our Forums https://forum.opensearch.org/t/opensearch-ingest-attachment-processor-failed-to-extract-text-from-word-file/12098

**Comment by dblock** [comment]
@pcvijayvignesh Do you have a ticket with AWS customer support?

**Comment by dhwanilpatel** [comment]
@pcvijayvignesh this was known issue on AWS side, for the scenario you have mentioned. That has been fixed in latest software version. 

Please reach out to AWS customer support if you still face the issue. 

@minalsha  let's close this issue, since we haven't got response back from @pcvijayvignesh  in long time.

**Comment by pcvijayvignesh** [comment]
@dhwanilpatel : Hey sorry folks for no response in long time, thanks for the info. Is there any link i could get that this is an issue on AWS side. We haven't reached to their support yet since we modified the ingestion part now.

**Comment by dblock** [comment]
@dhwanilpatel do you have a reference to a ticket inside AWS or something for this?

I'll close this. @pcvijayvignesh please feel free to reopen if you're still seeing the problem.
