### ISSUE TITLE
Contributing to the project

### ISSUE THREAD

**Issue by mehmetali2003** [opensearch-project/OpenSearch#6497]
Hi,

Is there any prerequisite to contribute to this project?

**Comment by kartg** [comment]
hi @mehmetali2003 ! Please take a look at our [README](https://github.com/opensearch-project/OpenSearch/blob/main/README.md) and [Contributing](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md) guides for information on how to get started with contributing. If you're looking to contribute code, our [Developer Guide](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md) and [Testing](https://github.com/opensearch-project/OpenSearch/blob/main/TESTING.md) documentation are great resources.

I'll go ahead and close this issue, but please feel free to reopen it if you have questions that are not answered by the docs above. Looking forward to your contributions!
