### ISSUE TITLE
Enforce documentation for new features/enhancements

### ISSUE THREAD

**Issue by setiah** [opensearch-project/OpenSearch#652]
Some of the features or enhancements that are getting merged also need to be added in end user documentation, otherwise the documentation would diverge. Can we have a way to enforce the documentation check before merging the PR in CI? (either via issue, PR or signoff by reviewer) 
Since we do not have documentation at this point, acknowledgement could be a github issue to add it later for the enhancement getting checked in.

**Comment by Bukhtawar** [comment]
I guess we should create meta issues per feature or enhancement rather than a single Meta issue. WDYT?

**Comment by setiah** [comment]
Sure, that's even better. Probably the CI have a way to enforce reviewer/contributor to acknowledge for documentation (via issue, PR, or signoff) so the end user documentation does not diverge.

**Comment by setiah** [comment]
updated the issue title to reflect the discussion is around how can we enforce documentation check in first place

**Comment by adnapibar** [comment]
Do we have snippet testing for testing the code inside the docs? If then we can run that as part of the PR checks. Note that this only makes sure that we can catch changes which breaks something existing. For new features it can be manual process which falls under the reviewer's responsibility.

**Comment by dblock** [comment]
OpenSearch documentation lives separately in https://github.com/opensearch-project/documentation-website. Maybe a PR template should say "Will doc changes be needed? Did you open an issue in documentation-website?" will do?

**Comment by VachaShah** [comment]
PR templates now have a requirement to create documentation issues. Closing this.
