### ISSUE TITLE
Pinned query

### ISSUE THREAD

**Issue by Hronom** [opensearch-project/OpenSearch#653]
**Is your feature request related to a problem? Please describe.**
We need to promote a list of documents, for example 240. 
And at the same time all filters should be applied, so we make sure that this documents are searchable and match criteria's.

What we need already implemented in X-Pack https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-pinned-query.html#query-dsl-pinned-query

**Comment by tlfeng** [comment]
Hi Hronom, thanks for your feature request with your use case! 😁 We will consider it and there is also an old issue (https://github.com/opensearch-project/OpenSearch/issues/72) for tracking the feature of "Pinned Query".
In the meanwhile, we are also glad to see people in the community can drive it.

**Comment by Bukhtawar** [comment]
I guess we can keep just one of them open as a tracking issue and resolve the other as a duplicate, since both are around supporting Pinned queries as a feature

**Comment by dblock** [comment]
Let's close this as a duplicate. Thanks @tlfeng and @Bukhtawar!
