### ISSUE TITLE
[Optimization] Use different threadpool for batching tasks per executor in cluster manager

### ISSUE THREAD

**Issue by dhwanilpatel** [opensearch-project/OpenSearch#6567]
**Describe the bug**

In TaskBatcher.java, for batching it maintains a ConcurrentHashMap to find duplicates using the batching key (which is based on task executor) and update the tasks for the given key. On task submission, it will require block on key of the map to perform the batching. 

https://github.com/opensearch-project/OpenSearch/blame/8e0edee3d403e5f2339d176b800e9e5df1372692/server/src/main/java/org/opensearch/cluster/service/TaskBatcher.java#L98

This batching is performed on the transport threadpool itself. During storm of task of same type it can block the transport threads. This will impact the leader checks from the data nodes and can impact the overall cluster availability as well. 

**To Reproduce**
Generate too many pending tasks of same type on cluster manager nodes. We can see transport threads getting blocked on task batching part.

**Expected behavior**
We should perform the batching in separate threadpool and free up the transport threads early.

**Comment by shwetathareja** [comment]
@dhwanilpatel we should change the threadpool for enqueuing the cluster state changes in pending task queue in your experiments and ensure you are not seeing cluster manager threadpool blocked anymore as this poses cluster stability concerns and could cause follower/ leader checks to fail as well.
Once we change the threadpool, the problem will shift to different threadpool which will saturate after a while. we should re-visit this task deduplication which is being executing under lock.

**Comment by shwetathareja** [comment]
@dhwanilpatel The below logic which runs in synchronization block is checking for duplicate reference for same batchingKey. But, the issue is when there are too many tasks for single batching key e.g. putMapping, it requires iterating over that big list(100s of thousands of entries) again and again with every submit call. This could be maintained in a separate map which has key as BatchingKey+IdentityReference for task. This map also gets updated within the same synchronized block when adding/removing items from the main map ```tasksPerBatchingKey``` . With this the lookup would be O(1) and wouldn't require maintaining separating threadpool as well at the extra cost of maintaining more map.
```
            tasksPerBatchingKey.merge(firstTask.batchingKey, newTasks, (existingTasks, updatedTasks) -> {
                for (BatchedTask existing : existingTasks) {
                    // check that there won't be two tasks with the same identity for the same batching key
                    BatchedTask duplicateTask = tasksIdentity.get(existing.getTask());
                    if (duplicateTask != null) {
                        throw new IllegalStateException(
                            "task ["
                                + duplicateTask.describeTasks(Collections.singletonList(existing))
                                + "] with source ["
                                + duplicateTask.source
                                + "] is already queued"
                        );
```

**Comment by dhwanilpatel** [comment]
@shwetathareja , I agree we should improve the de-dup logic instead of moving it to different threadpool. 

Thanks for suggestion, I have looked into it. With this complexity will not be O(1) but O(# of tasks in single task submission). We will need to iterate over all tasks which are getting submitted in one submit call for de dup. Still it is great improvement compare to existing logic, which is O(existing tasks in queue).

Instead of `BatchingKey+identityReference` as key, we can keep `BatchingKey` as key and `list of IdentityReferance` as value, similar to tasksPerBatchingKey map. This will help in easily removing those identity when tasks are executed in batches, we will just remove that entry from map.

I will make sample code change and raise PR for it to review the approach..

**Comment by shwetathareja** [comment]
> Instead of BatchingKey+identityReference as key, we can keep BatchingKey as key and list of IdentityReferance as value, similar to tasksPerBatchingKey map. 

Thanks @dhwanilpatel for trying out. Actually i meant the same. with BatchingKey+identityReference essentially i meant identity reference for a unique task.

**Comment by dhwanilpatel** [comment]
@shwetathareja  I am planning to use LinkedHashSet to store Identity references against Batching Key, so search operation will be O(1), we wont need to iterate over the list again. 

Something like:
`final Map<Object, LinkedHashSet<Object>> taskIdentityPerBatchingKey = new ConcurrentHashMap<>();`

#7305
