### ISSUE TITLE
[Design Proposal] Locking Mechanism for Remote Store Md Files

### ISSUE THREAD

**Issue by harishbhakuni** [opensearch-project/OpenSearch#6576]
<h1>Problem Statement:</h1>

**How to Acquire/Release Locks on Shard Level Metadata Files in Remote Segment Store which will prevent their deletion during Metadata File Cleanup in Remote Store?**
Today, [Remote Store Feature](https://opensearch.org/docs/latest/tuning-your-cluster/availability-and-recovery/remote/) do not provide Async Garbage Collection, the logic is they keep X number of latest metadata files for a given shard. If the number of metadata files after a commit becomes greater than X, they just remove the last metadata file for the shard.
Also For [Snapshot Interoperability with Remote Store](https://github.com/opensearch-project/OpenSearch/issues/6575) Project, we need a way to lock shard level metadata files and keep them in remote segment store till the life of the snapshot. Similarly, in future there can be other features which could require locking of remote store metadata files.

The Aim of this document is to capture Design/Changes required to implement Locking Mechanism for Shard Level Metadata files in Remote Segment Store.

<h1>Requirements:</h1>

1. External components shall be able to acquire locks on remote metadata files to prevent deletion.
2. It should be possible to release lock for all the metadata files of a given index at once.

<h1>Solution:</h1>

The Idea is we will add Lock Files for shard level metadata files if they are currently in use by some operation. We will delete these lock files to invalidate or release locks from a given metadata file.

<h2>Remote Store MD Lock Manager:</h2>

![file_structure_rs1_new](https://user-images.githubusercontent.com/31981080/223545503-ef4d84f5-c78f-45b5-9c09-729aace7c97f.jpg)

**Remote Store MD Lock Manager** will be an abstraction which can be used by different components to acquire/release locks on Remote Store MD Files.

<h2>Low Level Approach: Create a lock directory at shard level and a lock acquiring resource directory at index level</h2>

![file_structure_rs1_new2](https://user-images.githubusercontent.com/31981080/223545985-268297ed-ed08-4add-9a50-30ef4c24c543.jpg)

The Idea is Shard Level Lock will be a lock file created at shard level for a given md file. we will keep all the locks for a shard in its lock directory.
Index Level Resource Lock file will be used to keep track of resources which are acquiring locks for a given index. Also these will be used to validate/invalidate Shard Level Locks. If a Shard Level Lock exists for a given md file but corresponding index level lock is not present for the resource, we will consider the shard level lock as invalid.

**Acquire Lock Operation:** To Acquire a lock on a remote store md file, we need to add a lock file in the shard level lock directory and then add a lock file in the index level resource lock directory.

**Release Lock Operation:** To Release Lock for a Remote Store md File, we just need to remove the resource lock from index level resource directory. Periodic Garbage Collection in Remote Store will take care of deletion of individual shard level lock files.

**Metadata File Cleanup Operation:** During Cleaning up a metadata file, we first need to figure out all the shard level locks for the metadata file, then for each shard level lock file, we need to see if the resource which acquired the lock still have the lock in index level resource lock directory.

With this approach, We have to do two put operations initially, first to add lock file at shard level and then to add resource lock file at index level. Shard Level Locks can be acquired or released from the data nodes where the primary shard exists whereas Index Level Locks will be only acquired or released from the cluster manager node.

<h2>Other Considered Approaches:</h2>

<h3>1: Create lock directory at index level</h3>

![xyzzzz_2](https://user-images.githubusercontent.com/31981080/223546261-a6ff2c16-13ca-4750-a0b4-b81b63598df5.jpg)

With this Approach, we will be keeping md lock directory at index level, i.e., for each resource we will be adding all the locks for shard level metadata at index level. in this case, multiple shards which might be in different data nodes will share the same lock directory. For Garbage Collection from the remote store side for a given md file, we need to pull all the lock files for all md files across shards. but to release locks, we can just delete the corresponding directory for that operation at index level at once. ( i.e., deleting the directory <IndexUUID>/lock/snapshotId1/).

We are not going with this approach because the metadata file cleanup will be very tricky in this case. to delete a metadata file, we need to pull all the locks for all the shards in the index in memory and then we will be able to figure out if a metadata file should be cleaned up or not.

<h3>2: Create lock directory at shard level:</h3>

![file_structure_rs13](https://user-images.githubusercontent.com/31981080/223546431-7e3aa0f4-c043-4890-88d5-8b1d36c7edf0.jpg)

Here, We are keeping the md lock directory at shard level. i.e., for a given shard, all the locks acquired on any of the md file of that shard will persist in the shard level lock directory. For Garbage Collection for a given md, we just need to see if a lock is present for that metadata file or not in the shard level lock directory. However for releasing lock, we need to remove lock from each shard individually.

We are not going with this Approach because here, to delete locks, the lock acquiring operation need to loop through each shard individually and then release the lock.

<h2>TTL for Metadata File Locks:</h2>

We are planning to keep a default TTL for Metadata file locks.
For first phase, we will not provide an ability for users to update the TTL for an existing snapshot. we can keep the default value as part of index settings (or repository settings), which user can update by updating the index settings. User can keep some defined value (let's say -1) if they do not want to keep a TTL for lock.

<h2>Open Questions:</h2>

1. Should the TTL field be a index setting or a repository setting?
2. Do we need to implement a separate Async Garbage Collection, or is it something Lock Manager can trigger?

**Comment by andrross** [comment]
Some initial nitpicks on the requirements:

> Garbage Collection on Remote Store Side should be able to easily figure out if a metadata file is available for deletion.

I think you could meet this requirement by not doing anything :) I think this requirement should be framed around something like "External components shall be able to tag remote metadata files to prevent deletion".

> Acquiring/Releasing Lock on a metadata file should be easy and feasible for any operation.

"easy" and "feasible" aren't particularly precise terms. What exactly do you mean here? What is the constraint?

**Comment by harishbhakuni21** [comment]
> I think you could meet this requirement by not doing anything :) I think this requirement should be framed around something like "External components shall be able to tag remote metadata files to prevent deletion".

makes sense. updated the requirement.

> "easy" and "feasible" aren't particularly precise terms. What exactly do you mean here? What is the constraint?

So for an external component (at least for snapshot), we need a way to release locks for an index at once, i.e., by just releasing lock once for the index, we should be able to invalidate all the shard level metadata file locks. updated the requirement.

**Comment by gbbafna** [comment]
Hi @harishbhakuni21 , Thanks for the design .  

Can you expand how index level locking work as in what is the content of the lock file ? Does it contain all the corresponding shard lock file names ? Or we create per shard lock file in index level directory as well ? 

> We are planning to keep a default TTL for Metadata file locks.

Is there a default TTL for index level lock ? First we would need to delete the index level lock followed by shard level lock

**Comment by harishbhakuni21** [comment]
> Can you expand how index level locking work as in what is the content of the lock file ? Does it contain all the corresponding shard lock file names ? Or we create per shard lock file in index level directory as well ?

So, shard level lock file name will be like <metadata_file_name>-<resourceID>.lock and index Level File will be like <resourceID>.lock. for now index level lock file will only store info like TTL and ResourceID, but going forward we can use this file to store more external component related data as well who is acquiring the lock.

> Is there a default TTL for index level lock ? First we would need to delete the index level lock followed by shard level lock

right, TTL will be per component lock, so it will be for index level lock only. If for some metadata, there is shard level lock, but no index level lock (or expired index level lock), we will consider the shard level lock as invalid.

**Comment by dblock** [comment]
Could you please elaborate on failure scenarios? For example, if a lock is taken but never released, can another instance reuse the remote store? What happens when we accidentally configure the same remote store from two instances of OpenSearch? Are there any potential deadlocks here?
