### ISSUE TITLE
update some UT for DocValueFormat

### ISSUE THREAD

**Issue by XiaochenNan** [opensearch-project/OpenSearch#6580]
**Is your feature request related to a problem? Please describe.**
no， just improve test coverage

**Describe the solution you'd like**
update some UT for DocValueFormat

**Describe alternatives you've considered**
no

**Additional context**
no

**Comment by minalsha** [comment]
@XiaochenNan  assigning the issue to you since you have a PR for this out. Thank you for your contribution.
