### ISSUE TITLE
Return a Server header with server version 

### ISSUE THREAD

**Issue by dblock** [opensearch-project/OpenSearch#6583]
**Is your feature request related to a problem? Please describe.**

Clients are trying to figure out what version of OpenSearch/Elasticsearch they are talking to. I've seen several ways of doing so.

### `GET /` 

Contains `distribution` and `number`.

```json
{
  "version" : {
    "distribution" : "opensearch",
    "number" : "2.3.0",
    "build_type" : "tar",
    "lucene_version" : "9.3.0",
    "minimum_wire_compatibility_version" : "7.10.0",
    "minimum_index_compatibility_version" : "7.0.0"
  },
  "tagline" : "The OpenSearch Project: https://opensearch.org/"
}
```

### `GET /_nodes` using node version (`version`)

```
{
  "BC0_Th12Rlu6QllMXsdJYw": {
    "name": "bc0162016d521a597c3e17070ad30fe2",
    "version": "2.3.0",
   ...
}
```

### `GET /_nodes` using module/plugin version info (`opensearch_version`)

```json
{
  "name" : "transport-netty4",
  "version" : "2.3.0",
  "opensearch_version" : "2.3.0",
  ...
}
```

### `GET /_cat/plugins`

YYMV

```
bc0162016d521a597c3e17070ad30fe2 analysis-icu                         2.3.0
bc0162016d521a597c3e17070ad30fe2 analysis-ik                          2.3.0
bc0162016d521a597c3e17070ad30fe2 analysis-kuromoji                    2.3.0
bc0162016d521a597c3e17070ad30fe2 analysis-phonetic                    2.3.0
bc0162016d521a597c3e17070ad30fe2 analysis-seunjeon                    2.3.0
bc0162016d521a597c3e17070ad30fe2 analysis-smartcn                     2.3.0
bc0162016d521a597c3e17070ad30fe2 analysis-stempel                     2.3.0
bc0162016d521a597c3e17070ad30fe2 analysis-thaichub2                   2.3.0
bc0162016d521a597c3e17070ad30fe2 analysis-ukrainian                   2.3.0
bc0162016d521a597c3e17070ad30fe2 discovery-ec2                        2.3.0
bc0162016d521a597c3e17070ad30fe2 elasticsearch-aes-iam                1.0.0
bc0162016d521a597c3e17070ad30fe2 elasticsearch-aes-remote-reindex     2.3.0
bc0162016d521a597c3e17070ad30fe2 ingest-attachment                    2.3.0
bc0162016d521a597c3e17070ad30fe2 kraken                               unspecified
bc0162016d521a597c3e17070ad30fe2 kraken-index-management-extension    x.x.x.x
bc0162016d521a597c3e17070ad30fe2 mapper-murmur3                       2.3.0
bc0162016d521a597c3e17070ad30fe2 mapper-size                          2.3.0
bc0162016d521a597c3e17070ad30fe2 opensearch-alerting                  x.x.x.x-SNAPSHOT
```

- Neither of these methods are very reliable and guaranteed to be future-proof.
- All these methods require a certain level of access/permissions. 
- An explicit request must be made to figure out the version of the server, ie. client must persist this information across requests and cannot be talking to multiple servers without remembering somewhere what the versions of each server are.
- It's particularly challenging to distinguish Elasticsearch vs. OpenSearch (e.g. both have versions 2.3).

**Describe the solution you'd like**

Return server version in a `Server: ` header with every response, e.g. `Server: OpenSearch/2.3.0 (Unix)`. 
Make it configurable, so cloud vendors can identify themselves, e.g. `Server: OpenSearch/2.3.0 (Amazon OpenSearch)`.

**Comment by aibarelemesov** [comment]
Can i take this issue?

**Comment by Sam-ScottLogic** [comment]
Id like to work on this issue. This is my first open-source issue contribution.

**Comment by dblock** [comment]
Thanks. Looking forward to some PRs!

**Comment by Sam-ScottLogic** [comment]
I've started work on this. I have a few queries. Within the describe the solution section above the two examples of the Server header are OpenSearch/2.3.0 (Unix) and OpenSearch/2.3.0 (Amazon OpenSearch). Firstly will the first part of this be OpenSearch or does this change? Secondly, where would I get the values from. Examples have been given how you can send requests off to obtain distribution ie the "OpenSearch" bit and the version number "2.3.0" but I doubt you want to send a request off during the building of a response and there is no example of how to get the "(Unix)" or "(Amazon OpenSearch)" part of the header value.

**Comment by Sam-ScottLogic** [comment]
Also where the best place to add the code to add the header in? I was thinking within DefaultRestChannel where custom headers are added

**Comment by dblock** [comment]
I would default to a dynamic header that produces "OpenSearch/2.3.0 (XYZ)", but also allow to overwrite it completely in the configuration, including the ability to set it to blank and therefore remove it. Thus someone running a managed service can say something/anything else including things like Amazon OpenSearch. For the configuration, there's the question of whether it should be a node/cluster-wide configuration, think about that one as you implement it.

Not familiar with this code path, so not sure where!

**Comment by dblock** [comment]
> How do I retrieve the text that's in the brackets (XYZ)? Would this be a user input? Or is there a value in the code base already

I think we can use the distribution type/target for this, the same stuff returned from `GET /`. I don't know where that code is, I'm sure you'll find it :)
