### ISSUE TITLE
[Discuss] When should plugins use system indices?

### ISSUE THREAD

**Issue by peternied** [opensearch-project/OpenSearch#6589]
**Describe the bug**
Many plugins in the OpenSearch distribution use SystemIndexes for their plugin metadata, such as [K-NN](https://github.com/opensearch-project/k-NN/pull/630). However, OpenSearch Dashboards does not use a system index for its metadata store.

Upon inspecting the usage of system indexes in OpenSearch, it was found that they provide [prioritization](https://github.dev/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/gateway/PriorityComparator.java#L67) and [thread pool isolation](https://github.com/search?q=repo%3Aopensearch-project%2FOpenSearch%20.isSystem()&type=code) distinctions that are not available in "normal" indices.

The security plugin prevents modification of system indexes without mechanisms to grant access to users. While this may seem like a safety measure, it forces plugins to operate at a [higher privilege level](https://github.com/opensearch-project/security/issues/2487), which is less safe and does not provide protection from one plugin reading/modifying the contents of another plugin.

When should plugins use system indexes?

As OpenSearch builds up [extensions](https://github.com/opensearch-project/OpenSearch/issues/2447) should extensions have access to these system indexes?

**Comment by peternied** [comment]
We are looking at how to support system indexes for extensions in the security plugin and this came up.  If there is strong direction either way it could impact how/if we build the feature.  Would love feedback on this thread or the decision doc below

- https://github.com/opensearch-project/security/issues/2530

**Comment by peternied** [comment]
@saratvemulapalli @minalsha @dbwiddis I think you might have strong options on this, love to get your thoughts.

**Comment by peternied** [comment]
@opensearch-project/plugins Do you have strong opinions on metadata storage for plugins, and them using system indexes?

**Comment by dblock** [comment]
I propose the following:

1. Access to system indices is sufficiently a special operation, that an extension can be allowed/disallowed to write to system indices separately from being allowed/disallowed to write to other indices.
2. Access to a system index is not different than an access to a regular index on top of (1), and can be allowed/disallowed index-by-index to all types of identities.

**Comment by kaituo** [comment]
There are two types of system indices: one used by the security plugin, and another used by the OpenSearch core. The latter has higher prioritization and employs a dedicated threadpool. However, AD does not use the latter but relies on the system index provided by the security plugin.

I propose the following:

In the case of system indices from OpenSearch core, plugins may choose not to use them if their indices are less important than other user indices. (Context: https://github.com/opendistro-for-elasticsearch/anomaly-detection/pull/394).

Regarding system indices from the security plugin, plugins use them to ensure that their metadata index cannot be modified by a user, as noted by @saratvemulapalli. Plugins may opt to use a normal user index if they wish to allow users to access the index for tasks such as plotting graphs on dashboards or enabling alerting.

**Comment by minalsha** [comment]
@peternied  what are the next steps for this issue since it is a Discuss issue.

**Comment by peternied** [comment]
I think this discussion has concluded, in the plugin ecosystem system indices are the assumed place to store data, there is no appetite to removing/replacing this mechanism.  Allowing these systems indices to be accessible in more context via specific permission [1] seems like the long term vision.

This topic might be revisited at a future time, but there are not outstanding questions.  Thanks for the feedback everyone!

- [1] https://github.com/opensearch-project/security/issues/2529
