### ISSUE TITLE
Help!!!  Need to log a complex object

### ISSUE THREAD

**Issue by VartuSharma** [opensearch-project/OpenSearch#6597]
Hello 
I am trying to sink logs into opensearch using serilog.
Is there any way I can customize the filed of Opensearch with complex object?
For reference, I have attached the screenshot.

<img width="380" alt="image" src="https://user-images.githubusercontent.com/127403724/224013843-332b9c7a-96b9-4a8a-a4b1-9c1aa2449b5e.png">

**Comment by VartuSharma** [comment]
I tried serializing the additional data, but it is looking like this. see attached image 
<img width="737" alt="image" src="https://user-images.githubusercontent.com/127403724/224629541-35481704-97d3-49f9-bb82-5ccccda38527.png">

**Comment by minalsha** [comment]
We understand your input. What would you like to see in OpenSearch to happen? Could you please share a specific example. Thanks

**Comment by VartuSharma** [comment]
Hello
It is done. I have used opensearch.client to log complex object in opensearch.

Thank you.

**Comment by dblock** [comment]
@VartuSharma would appreciate a note on what you did and how for the next person
