### ISSUE TITLE
[Documentation] Add documentation for default number of shards setting PR#625

### ISSUE THREAD

**Issue by setiah** [opensearch-project/OpenSearch#660]
Add documentation for the change - "[Make default number of shards configurable](https://github.com/opensearch-project/OpenSearch/pull/625)"

**Comment by setiah** [comment]
Closing this in favor of keeping #678 open under `documentation` label

**Comment by hackery** [comment]
It doesn't look like documentation was added via #678. In fact, I'm struggling to find any documentation of configuration loaded via Java properties. The commit referenced above appears to be unrelated and mis-linked.

Someone also opened opensearch-project/documentation-website#673 but no documentation was added via that, and I think the responders didn't understand what was required.
