### ISSUE TITLE
Deprecate Map, List, and Set in org.opensearch.common.collect

### ISSUE THREAD

**Issue by andrross** [opensearch-project/OpenSearch#6609]
Code links: [Map](https://github.com/opensearch-project/OpenSearch/blob/c557f2717ad45627cacd88e8243893dd84a56623/libs/common/src/main/java/org/opensearch/common/collect/Map.java), [List](https://github.com/opensearch-project/OpenSearch/blob/c557f2717ad45627cacd88e8243893dd84a56623/libs/common/src/main/java/org/opensearch/common/collect/List.java), [Set](https://github.com/opensearch-project/OpenSearch/blob/c557f2717ad45627cacd88e8243893dd84a56623/libs/common/src/main/java/org/opensearch/common/collect/Set.java)

These classes have been pass throughs to the `java.util` since Java 9. They are pretty harmless, except for the annoyance that sometimes your IDE imports the OpenSearch class and then has to fully qualify the `java.util` versions when you want to use those. The task here is to:

- Add `@Deprecated` annotations to these classes
- Replace all usages within the opensearch-project/OpenSearch repo with the `java.util` versions

**Comment by diliproshitha** [comment]
Can I work on this?

**Comment by andrross** [comment]
> Can I take this?

Sure! I'll assign it to you.

**Comment by diliproshitha** [comment]
Raised the following PR: https://github.com/opensearch-project/OpenSearch/pull/6631

**Comment by kotwanikunal** [comment]
Resolved with #6786
