### ISSUE TITLE
[Segment Replication] Provide option to turn on Segment Replication as default replication strategy.

### ISSUE THREAD

**Issue by mch2** [opensearch-project/OpenSearch#6656]
Today, users need to enable segment replication by both setting a feature flag and index level setting while creating the index.
https://opensearch.org/docs/latest/tuning-your-cluster/availability-and-recovery/segment-replication/configuration/

It would be ideal to provide an additional setting to pass via yml to make segrep the default replication strategy.

This setting should not replace the feature flag and should be an additional setting passed in opensearch.yml.  For now, it should only be enabled if the FF is also enabled.

**Comment by Rishikesh1159** [comment]
Currently, when user set cluster setting `"cluster.indices.replication.strategy"` in opensearch.yml, all the newly created indices will use segment replication as default replication strategy. But when user tries to fetch index settings `GET /<index>/_settings` the response does not show replication type as SEGMENT. So this is a bug and it might be confusing for users. I am currently looking for any other workarounds to fix this issue, I will update here as soon as I find something. Any other thoughts are much appreciated please.

**Comment by Rishikesh1159** [comment]
We have added new feature flag `SEGMENT_REPLICATION_EXPERIMENTAL `("opensearch.experimental.feature.segment_replication_experimental.enabled") in PR:https://github.com/opensearch-project/OpenSearch/pull/7006. All new segment replication experimental/beta features will be behind this feature flag.

As discussed previously the cluster setting  `CLUSTER_REPLICATION_TYPE_SETTING` ("cluster.indices.replication.strategy") has known bug. So, we don't want to release it until we fix the bug. Until then the `CLUSTER_REPLICATION_TYPE_SETTING` will be behind `SEGMENT_REPLICATION_EXPERIMENTAL` flag.

This cluster setting is not production ready yet. This should strictly be used only for testing purposes for now.
