### ISSUE TITLE
[BUG] WARNING: A terminally deprecated method in java.lang.System has been called

### ISSUE THREAD

**Issue by LHozzan** [opensearch-project/OpenSearch#6662]
**Describe the bug**
On fresh start OpenSearch image in K8s are generated the lines:
```
main WARNING: A terminally deprecated method in java.lang.System has been called
main WARNING: System::setSecurityManager has been called by org.opensearch.bootstrap.OpenSearch (file:/usr/share/opensearch/lib/opensearch-2.6.0.jar)
main WARNING: Please consider reporting this to the maintainers of org.opensearch.bootstrap.OpenSearch
main WARNING: System::setSecurityManager will be removed in a future release
```
OpenSearch but works fine. Have these lines sense?

**To Reproduce**
Just start OpenSearch instance and check log.

**Expected behavior**
The warning lines not be generated. It is confusing looking to warnings and OpenSearch works fine.

**Host/Environment (please complete the following information):**
- K8s (v1.24.4)
- AWS, Kind

**Additional context**
It seems, that same problem was reported to [ElasticSearch repository](https://github.com/elastic/elasticsearch/issues/80344). I cannot check, that this problem was solved here.

**Comment by MaxKsyunz** [comment]
It's a thorny issue to resolve -- https://github.com/opensearch-project/OpenSearch/issues/1687

**Comment by owaiskazi19** [comment]
Closing this as it is already covered in #1687. If there's anything not covered @LHozzan please feel to reopen the issue.
