### ISSUE TITLE
Add integration test for settings upgrade

### ISSUE THREAD

**Issue by dblock** [opensearch-project/OpenSearch#670]
**Is your feature request related to a problem? Please describe.**

Coming from https://github.com/opensearch-project/job-scheduler/pull/20 and https://github.com/opensearch-project/opensearch-plugins/pull/15 we want an integration test that sets a legacy setting with a previous version of ODFE/ES and ensures that the upgrade falls back to the previously set setting.

**Describe the solution you'd like**

An integration test, possibly ala https://github.com/opensearch-project/OpenSearch/blob/main/qa/full-cluster-restart/src/test/java/org/opensearch/upgrades/FullClusterRestartSettingsUpgradeIT.java.

**Describe alternatives you've considered**

A settings integ test ala https://github.com/opensearch-project/OpenSearch/blob/main/server/src/internalClusterTest/java/org/opensearch/common/settings/UpgradeSettingsIT.java, but that doesn't really test upgrade.

**Comment by dblock** [comment]
@saratvemulapalli Is this covered with another task?

**Comment by saratvemulapalli** [comment]
Pulling this to sprint backlog.
cc: @minalsha @anasalkouz
