### ISSUE TITLE
[BUG] TopNSearchTasksLogger settings are not recognised

### ISSUE THREAD

**Issue by PritLadani** [opensearch-project/OpenSearch#6708]
**Describe the bug**
We introduced Task Resource Consumer to log task resource information at a specified interval as a part of https://github.com/opensearch-project/OpenSearch/pull/2293. However, newly introduced dynamic settings `cluster.task.consumers.top_n.size` and `cluster.task.consumers.top_n.frequency` are not registered under `ClusterSettings.BUILT_IN_CLUSTER_SETTINGS` and hence not recognised when trying to change the value. We need to register them in `ClusterSettings.BUILT_IN_CLUSTER_SETTINGS` to make them dynamic.

**To Reproduce**
1. Try to change setting value for `cluster.task.consumers.top_n.size` or `cluster.task.consumers.top_n.frequency` and it will give error. 

**Expected behavior**
It should not give error and should change the setting value.

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**

**Comment by owaiskazi19** [comment]
@sruti1312 any idea about this bug?

**Comment by sruti1312** [comment]
This was intentional as changing these settings has impact on performance. Currently we need to change this config by updating the config files and requires OpenSearch process restart, this helps ensure that these values are modified only if absolutely required. But that being said, if we see a use case for this then we can make it dynamic.

**Comment by anasalkouz** [comment]
@sruti1312 What do you suggest? Keep it as is?
@PritLadani What do you think? could you elaborate more the use-case to make this config dynamic?

**Comment by PritLadani** [comment]
This has already been fixed by the PR https://github.com/opensearch-project/OpenSearch/pull/7241 and we can close this issue.
