### ISSUE TITLE
Scripting (painless/mustache) request processor

### ISSUE THREAD

**Issue by macohen** [opensearch-project/OpenSearch#6712]
As a user of search pipelines, I want to be able to insert a painless or mustache script to manipulate search requests.

**Comment by noCharger** [comment]
> manipulate search requests.

@macohen @msfroh Can we have some specific use cases here? In the injest pipeline, for example, script is used to filter/rewrite documents for ingestion.

**Comment by msfroh** [comment]
In this case, I would like the script to manipulate the search request based on logic implemented in the painless script.

The main input to the painless script would be the search request itself, which was probably programmatically generated by the search application.

For example, maybe my pipeline would say "If the search query matches on the `date` field, then set the `size` property to `min(size, 50)`" (as a contrived example).

**Comment by macohen** [comment]
documentation task to come with fields that can be read/written

**Comment by noCharger** [comment]
> documentation task to come with fields that can be read/written

Created https://github.com/opensearch-project/documentation-website/issues/4155

**Comment by noCharger** [comment]
Next steps for script processor
- [ ] Support non-primitive types in request body
- [ ] Support query context modification
