### ISSUE TITLE
Conditional Response Processor

### ISSUE THREAD

**Issue by macohen** [opensearch-project/OpenSearch#6715]
As a user of search pipelines, I want to be able to insert conditional checks on the search response into my pipeline to inform what the pipeline should execute next.

**Comment by macohen** [comment]
@noCharger commented in person that this could just be a specific ScriptResponseProcessor: #6713. If that's the case, I think putting effort into the scriptresponseprocessor and then seeing if we should have a specific processor that abstracts the choice made may be the right thing. Next step would be some info about how ScriptResponseProcessor could work for this case...

cc: @msfroh, @mingshl, @sejli

**Comment by msfroh** [comment]
If we want this to be consistent with ingest pipelines (which should be the guiding principle IMO), this wouldn't be a specific processor that users would add to their pipeline, but rather it would be a wrapper around another processor.

See e.g. https://www.elastic.co/guide/en/elasticsearch/reference/7.10/ingest-conditionals.html
