### ISSUE TITLE
Search pipeline metrics (at least on par w/ ingestion pipeline metrics).

### ISSUE THREAD

**Issue by macohen** [opensearch-project/OpenSearch#6723]
As a user of search pipelines I want to see metrics for my pipelines and individual processors in a generic way so I can measure performance and correctness of my pipelines.

**Comment by msfroh** [comment]
Assuming we follow the title of the issue, we would effectively copy https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/ingest/IngestStats.java

Following that model, the stats effectively form a 2D matrix. In one dimension, we have total time, total execution count, failure count, and active execution count (i.e. how many requests are executing right now). In the other dimension, we have stats for all pipelines, stats for each pipeline, and stats for each processor (across all processors).
