### ISSUE TITLE
Make default number of shards configurable

### ISSUE THREAD

**Issue by arunabh23** [opensearch-project/OpenSearch#678]
**Is your feature request related to a problem? Please describe.**
A way to modify the default number of shards for indices whose creation requests do not have the number of shards setting explicitly provided. This will be useful in cases where for such indices the cluster manager wants to have a default value other than the hardcoded value of 1 shard. Assumption is that most of the users will not need to modify this property but adding it as an option for cloud providers and for cases where most create requests don’t provide the number of shards explicitly.

**Describe the solution you'd like**
Opensearch already provides a way to configure the maximum number of shards for an index based on a system property. We can also have the default number of shards configurable in a similar manner instead of hardcoding it to 1.

**Describe alternatives you've considered**
Currently there is no other way than to have this in an index template or the create request.

**Comment by arunabh23** [comment]
PR: https://github.com/opensearch-project/OpenSearch/pull/625

**Comment by arunabh23** [comment]
Will be creating another PR for backporting it to Opensearch 1.0

**Comment by arunabh23** [comment]
Created a backport PR for 1.x branch

**Comment by dblock** [comment]
This is done.
