### ISSUE TITLE
[Proposal] Enable resolve all comments before PR merge option

### ISSUE THREAD

**Issue by kotwanikunal** [opensearch-project/OpenSearch#6807]
**Is your feature request related to a problem? Please describe.**
OpenSearch repo currently allows a PR to be merged without marking all the comments resolved. In case of multiple comments across commits, there can be comments from maintainers which might not be resolved. 
Although contributors walk through the comments addressing them, in the interest of missing out any comments, we should enable the feature to marking all comments as resolved before merging in the PR. 

**Describe the solution you'd like**
Github provides the capability under branch protection policy within repository settings to prevent merges until all comments have been marked as resolved. This should be enabled for all branches within the repository.

**Additional context**
The proposal is open for discussion. Please comment if there are any concerns or opinions around enabling this feature.

https://github.com/community/community/discussions/10304

**Comment by peternied** [comment]
- Are there examples of misses in this repo that this check would have caught? 
- Does anyone have experience with this check in practice another repo?
   - I would be concerned that bulk comment thread resolving wouldn't improve quality and become busy work.
   - IMO maintainer approval should consider all comments - include resolved one so this doesn't change that gate much
- What about folks that like to comment threads unresolved?
   - I use comments that point out quirks of the change that and unaddressed areas in this PR (even if an issue was filed).

**Comment by peternied** [comment]
@dbwiddis Thanks for the detailed response. I inspected several PRs in the [opensearch-sdk-java repo](https://github.com/opensearch-project/opensearch-sdk-java/pulls).  There is some helper UX that makes a difference to me, adding some screenshots.

#### Hint on mergeability pane
![image](https://user-images.githubusercontent.com/2754967/227504162-7dc6c87c-25c5-4af9-89f6-da4afb4ad35c.png)

#### Unresolved conversations shortcuts
_Found by clicking `View` from above_ 
![image](https://user-images.githubusercontent.com/2754967/227504076-d286a50e-c199-46c9-adc4-9126a82c396e.png)

**Comment by kotwanikunal** [comment]
I think @dbwiddis covered all of the concerns in detail. Thanks :) 
The other issue also has to do with the way GitHub UI deals with outdated comments. If I am on the code diff page with new changes, the previous comments go away, adding additional step for the maintainers to go back and look at the main PR page. 
Enabling the check will put all the information in a summarized fashion as @peternied has linked.

**Comment by dblock** [comment]
I'm good with this. Can I please have some +1s from other maintainers, maybe @nknize @Bukhtawar @reta @andrross?

**Comment by andrross** [comment]
@dblock I'm good with this as well. Seems like @dbwiddis really likes it in another repo. Should be trivial to turn off if we don't like it, right?

**Comment by reta** [comment]
I am on board as well

**Comment by kotwanikunal** [comment]
@dblock Can you please enable this? :)

**Comment by dblock** [comment]
Done. I also feel like we should enable the one above 🤔 but I'll close this issue.

![Screenshot 2023-05-04 at 4 42 43 PM](https://user-images.githubusercontent.com/542335/236324709-5b0e47a8-0512-4f52-8cab-38741963f0d2.png)

**Comment by bbarani** [comment]
@dblock Any reason why we shouldn't enable this feature for all repos?

**Comment by dbwiddis** [comment]
> Done. I also feel like we should enable the one above 🤔 but I'll close this issue.

Feel free to contribute (an issue). 😀
