### ISSUE TITLE
[BUG] gradlew check command fails due to license check / RPM build failure

### ISSUE THREAD

**Issue by camerski** [opensearch-project/OpenSearch#682]
**Describe the bug**
When I run `gradlew check` against the 1.x branch (and the main branch), the build fails with the following error:

```
Task :distribution:packages:arm64-rpm:checkLicenseMetadata FAILED
Execution failed for task ':distribution:packages:arm64-rpm:checkLicenseMetadata'.
> expected license [ASL-2.0] for [/workplace/camerski/opensearch/search/distribution/packages/arm64-rpm/build/distributions/opensearch-1.0.0-SNAPSHOT.aarch64.rpm] but was [ASL 2.0]
```

I have traced this to the `distribution/packages/build.gradle` file which has the offending license string at line 364; changing that to "ASL-2.0" solves that particular problem, but the next failure is more obscure:

```
> Task :distribution:packages:no-jdk-rpm:checkLicenseMetadata FAILED
Output for rpm:
error: /workplace/camerski/opensearch/search/distribution/packages/rpm/build/distributions/opensearch-1.0.0-SNAPSHOT.x86_64.rpm: rpmReadSignature failed: sigh load: BAD
error: /workplace/camerski/opensearch/search/distribution/packages/rpm/build/distributions/opensearch-1.0.0-SNAPSHOT.x86_64.rpm: not an rpm package (or package manifest)
```

At this point I'm at a loss to know how to proceed.

**To Reproduce**
* Check out `main` (commit ID 2581f3d4508651bdca22487109402e74475bcc92) and run `gradlew check`. Observe the first error.
* Change distribution/packages/build.gradle line 364 to read "license 'ASL-2.0'".
* Run `gradlew check` and observe the second error.

Do the same thing on the 1.x branch (commit b1b563dc39c39625b709d7f1ef97459f0e3b4e34).

**Expected behavior**
The build should succeed.

**Host/Environment (please complete the following information):**
 - OS: AL2

**Comment by camerski** [comment]
Hmm, might be my build environment...building commit b1b563dc39c39625b709d7f1ef97459f0e3b4e34 also fails on my machine...

Is there something I need in my environment to avoid the `> expected license [ASL-2.0] for [/workplace/camerski/opensearch/search/distribution/packages/arm64-rpm/build/distributions/opensearch-1.0.0-SNAPSHOT.aarch64.rpm] but was [ASL 2.0]` error?

**Comment by adnapibar** [comment]
PR #569 should fix this issue along with other distro tests.

**Comment by CEHENKLE** [comment]
#569 has been merged.  @camerski can you retest?

Thanks!
/C

**Comment by nknize** [comment]
Checking in on this one last time. It's stalled for a few weeks so I assume this can be closed.

**Comment by adnapibar** [comment]
> Checking in on this one last time. It's stalled for a few weeks so I assume this can be closed.

I reran it a couple of times now - the test fails as part of `.gradlew check` in AL2 but passes if I run the test by itself i.e. `./gradlew :distribution:packages:no-jdk-rpm:checkLicenseMetadata` or `./gradlew :distribution:packages:arm64-rpm:checkLicenseMetadata`

**Comment by dblock** [comment]
I closed this, but if you think we should do something about it @adnapibar reopen.

**Comment by owaiskazi19** [comment]
I faced the same issue. I ran `./gradlew :distribution:packages:no-jdk-rpm:checkLicenseMetadata` and `./gradlew :distribution:packages:arm64-rpm:checkLicenseMetadata` separately and then reran `.gradlew check`. It worked fine.
