### ISSUE TITLE
[Remote Store] `_cat/recovery` should provide progress of remote segment download during recovery

### ISSUE THREAD

**Issue by sachinpkale** [opensearch-project/OpenSearch#6821]
**Is your feature request related to a problem? Please describe.**
- `_cat/recovery` API provide details of progress of recovery. This helps in getting insight especially when shards are bigger in size.
- While restoring remote store backed index, entry is created but there is no data shown under `_cat/recovery`.
- This feature request adds the support of tracking segment download progress.
- Related issue of translog download progress: https://github.com/opensearch-project/OpenSearch/issues/6822

**Comment by DarshitChanpura** [comment]
Hey @sachinpkale, This issue will be marked for next-release `v2.8.0` on (Apr 17) as that is the [code-freeze](https://opensearch.org/releases.html) date for `v2.7.0`. Please let me know if otherwise.

**Comment by DarshitChanpura** [comment]
Tagging it for next release: `v2.8.0`

**Comment by sachinpkale** [comment]
Added as part of https://github.com/opensearch-project/OpenSearch/pull/6825
