### ISSUE TITLE
[CCI] Update Contributing guide - help newers to make first PR

### ISSUE THREAD

**Issue by Nicksqain** [opensearch-project/OpenSearch#6845]
**Note**: issue to speed up the entry threshold of the contribution process

### Description:

This markdown file should help all new contributors. And should describe the whole process:
from introduction to the first pulll-request.

And describes issues such as:

- How to work with Git: 

  - How to create commits
  - How to create PRs

**Comment by dblock** [comment]
We have a lot of getting started information in https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md. I would just add to that. For things that aren't OpenSearch specific, feel free to include external links, e.g. I usually share https://gist.github.com/Chaser324/ce0505fbed06b947d962 with new contributors.
