### ISSUE TITLE
Proposal: Allow custom plugin path when installing

### ISSUE THREAD

**Issue by dblock** [opensearch-project/OpenSearch#686]
**Is your feature request related to a problem? Please describe.**

Currently, when installing a plugin the path is set to some `function(plugin id) = folder`. Give plugin authors the ability to visibly name the folder into which the plugin is installed.

**Describe the solution you'd like**

- Allow plugin authors to declare the folder name for a plugin in the configuration, visibly.
- Allow plugin-install to override the folder name into which they are installed to help admins in case of conflicts.

**Additional context**

Coming from https://github.com/opensearch-project/OpenSearch-Dashboards/issues/322

**Comment by VachaShah** [comment]
I can take this.

**Comment by VachaShah** [comment]
The feature has been merged, will work on updating the documentation regarding the feature.
