### ISSUE TITLE
[Remote Store] Add cluster settings to enforce index creation with Remote storage.

### ISSUE THREAD

**Issue by linuxpi** [opensearch-project/OpenSearch#6861]
**Is your feature request related to a problem? Please describe.**
Today the user has a choice to create a remote store backed index in a cluster by providing certain settings during index creation. We should introduce cluster settings to allow user to create remote store backed indices without specifying remote store settings for each index during creation. If cluster settings is enabled all indices by default would be remote store backed

**Describe the solution you'd like**
Introduce new cluster settings to enable remote store cluster wide and another settings to specify the default repo to be used. Whenever a new index would be created it would be remote store backed

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by anasalkouz** [comment]
@sachinpkale is this in your radar?

**Comment by linuxpi** [comment]
> 

Yes @anasalkouz this for Durability and under @sachinpkale 's  radar
