### ISSUE TITLE
[BUG] SearchableSnapshotIT.testCacheFilesAreClosedAfterUse test failures

### ISSUE THREAD

**Issue by andrross** [opensearch-project/OpenSearch#6888]
```
REPRODUCE WITH: ./gradlew ':server:internalClusterTest' --tests "org.opensearch.snapshots.SearchableSnapshotIT.testCacheFilesAreClosedAfterUse" -Dtests.seed=FABDEC96AAADA3F2 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=ar-EG -Dtests.timezone=America/Antigua -Druntime.java=19

org.opensearch.snapshots.SearchableSnapshotIT > testCacheFilesAreClosedAfterUse FAILED
    java.lang.AssertionError: Cache file path isn't deleted.
        at __randomizedtesting.SeedInfo.seed([FABDEC96AAADA3F2:A74AFD6D02D27FBD]:0)
        at org.junit.Assert.fail(Assert.java:89)
        at org.opensearch.snapshots.SearchableSnapshotIT.testCacheFilesAreClosedAfterUse(SearchableSnapshotIT.java:564)
```

https://build.ci.opensearch.org/job/gradle-check/13061/console

**Comment by andrross** [comment]
This test logic seems to be wrong. The test is asserting the entire file cache directory does not exist, which isn't valid (only the contents of the directory should be deleted). It is also grabbing a random node from the cluster to do the test, which is probably why it sometimes passes because it grabs a node that never had an index on it.

**Comment by tlfeng** [comment]
Sorry about checking file cache on a random node regardless of the index location, it was due my ignorance.
I didn't realize that [internalCluster().getInstance()](https://github.com/opensearch-project/OpenSearch/blob/805e6d9dbca2c00dcc03e7851c42c85ef91dc72e/server/src/internalClusterTest/java/org/opensearch/snapshots/SearchableSnapshotIT.java#L561) only pickup a [random node](https://github.com/opensearch-project/OpenSearch/blob/2.6.0/test/framework/src/main/java/org/opensearch/test/InternalTestCluster.java#L1714), and there may be [more nodes](https://github.com/opensearch-project/OpenSearch/blob/2.6.0/test/framework/src/main/java/org/opensearch/test/InternalTestCluster.java#L680) than expected which doesn't have index when using [ensureAtLeastNumSearchAndDataNodes()](https://github.com/opensearch-project/OpenSearch/blob/805e6d9dbca2c00dcc03e7851c42c85ef91dc72e/server/src/internalClusterTest/java/org/opensearch/snapshots/SearchableSnapshotIT.java#L549).
