### ISSUE TITLE
Improve BinaryFieldMapper.CustomBinaryDocValuesField.bytes()

### ISSUE THREAD

**Issue by nknize** [opensearch-project/OpenSearch#6897]
Falling out of #6884 this issue is to explore improving (and benchmarking) the [BinaryFieldMapper.CustomBinaryDocValuesField.bytes()](https://github.com/opensearch-project/OpenSearch/blob/37b37c5b518c5bdb2dfdc5250117cfd39394edeb/server/src/main/java/org/opensearch/index/mapper/BinaryFieldMapper.java#L241) method to prevent sorting and deduping on every call. Options include switch from an `ArrayList<byte[]>` to a `TreeSet<byte[]>` or using sort/dedup after every add.

**Comment by nknize** [comment]
@navneet1v can I assign this one to you so you can own this exploration either here or upstream in Lucene?

**Comment by navneet1v** [comment]
> @navneet1v can I assign this one to you so you can own this exploration either here or upstream in Lucene? No rush... and I'd look at this as a follow on to just getting MultiValue in Lucene. I don't expect any performance improvements whether it's a `TreeSet` or something else to be terribly impactful but every little bit helps.

Yes sure.

**Comment by nknize** [comment]
Excellent!! Thank you!

**Comment by kkmr** [comment]
I chatted with @navneet1v.  I will be picking up this issue.

**Comment by navneet1v** [comment]
> I chatted with @navneet1v. I will be picking up this issue.

Thanks @kkmr for picking this up.
