### ISSUE TITLE
[BUG] string error response in GET /_alias for not existing index alias

### ISSUE THREAD

**Issue by szczepanczykd** [opensearch-project/OpenSearch#6904]
**Describe the bug**
The OpenSearch returns an error as a String instead of an Error object.
Because of that, we have to create a special ErrorHandler in the opensearch-java client.

**To Reproduce**
Run OpenSearch with docker-compose and open:
http://localhost:9200/_alias/test

see the response, and then compare with:
http://localhost:9200/not_existing_index/_search -> the error format is unified.

**Expected behavior**
The API returns an Error object instead of a plain string.

**Plugins**
None.

**Screenshots**
https://localhost:9200/_alias/not_existing_alias response:
![image](https://user-images.githubusercontent.com/48957041/228935710-2f1da78d-2a83-4e9c-92d1-dc612e5d5cf9.png)

An example proper API error:
![image](https://user-images.githubusercontent.com/48957041/228935834-59ba7606-1430-44d5-99fe-6938f9e048a8.png)

**Host/Environment (please complete the following information):**
 - Docker
 - OpenSearch 1.3.7

**Additional context**
See this GitHub issue:
https://github.com/opensearch-project/opensearch-java/issues/301
and
https://github.com/opensearch-project/opensearch-java/pull/399

OpenSearch code returning this error:
https://github.com/opensearch-project/OpenSearch/blob/8e0edee3d403e5f2339d176b800e9e5df1372692/server/src/main/java/org/opensearch/rest/action/admin/indices/RestGetAliasesAction.java

**Comment by vesnaIwakura18** [comment]
Hi! Could I take on the resolution of this issue?

**Comment by reta** [comment]
Fixed by https://github.com/opensearch-project/opensearch-java/pull/476
