### ISSUE TITLE
Reuse DirectoryFactory interface for remote store

### ISSUE THREAD

**Issue by Bukhtawar** [opensearch-project/OpenSearch#6929]
**Is your feature request related to a problem? Please describe.**
https://github.com/opensearch-project/OpenSearch/blob/c85d33e2e487242eb5ad60b64567ca2ec14fc88f/server/src/main/java/org/opensearch/plugins/IndexStorePlugin.java#L57-L83

**Describe the solution you'd like**
Remove redundant `RemoteDirectoryFactory` 

**Describe alternatives you've considered**

**Additional context**

**Comment by andrross** [comment]
Fixed by #6970
