### ISSUE TITLE
Update BaseRestHandler to implement default routes

### ISSUE THREAD

**Issue by saratvemulapalli** [opensearch-project/OpenSearch#694]
**Describe the bug**
Update BaseRestHandler to implement default routes() instead of an abstract class. 
This will help developers not to implement empty methods even though they don't need it.
They can always override the method if they'd like.

https://github.com/opensearch-project/OpenSearch/blob/0ba0e7cc26060f964fcbf6ee45bae53b3a9941d0/server/src/main/java/org/opensearch/rest/BaseRestHandler.java#L102

**Expected behavior**
Return an empty list so that classes which extend do not have implement empty methods even if they don't have to.

**Plugins**
OpenSearch Anomaly-Detection

**Host/Environment (please complete the following information):**
 - OS: Linux x64

**Comment by dblock** [comment]
In this case `routes` is not required because all the routes have `replacedRoutes`.

**Comment by VijayanB** [comment]
routes() method is from interface RestHandler, which already has default implementation [here](https://github.com/opensearch-project/OpenSearch/blob/0ba0e7cc26060f964fcbf6ee45bae53b3a9941d0/server/src/main/java/org/opensearch/rest/RestHandler.java#L84). May we should remove this method overriding from RestHandler at BaseRestHandler .

**Comment by Bukhtawar** [comment]
Can we have a way to enforce one of routes or replacedRoute as I don't think a RestHandler should exist without a route. This proposal can allow the plugin implementation to get away without providing any of them which breaks the contract

**Comment by vrozov** [comment]
Such a contract can't be enforced by Java. Any subclass that implements `RestHandler` can overwrite both `routes()` and `replacedRoutes()` and return empty list for both. Additionally, I don't think that enforcing that one of the methods returns a non-empty list is desirable. Some handlers may provide routes only under certain conditions/settings.
