### ISSUE TITLE
[BUG] OpenSearchRestTestCase support for Parameterized Tests is broken

### ISSUE THREAD

**Issue by saratvemulapalli** [opensearch-project/OpenSearch#695]
**Describe the bug**
OpenSearchRestTestCase supports ParameterizedTests using Carrot Randomized Runner and looks like the setup is broken.

**To Reproduce**
1. Go to a integ test case implemented with OpenSearchRestTestCase.
2. Setup ParameterizedTests using @Runwith
3. Run the test using gradle

Sample test:
```
@RunWith(class com.carrotsearch.randomizedtesting.RandomizedRunner.class)
public class SampleRestIT extends OpenSearchRestTestCase {
    private String parameter;
    public SampleRestIT(String parameter) {
        self.parameter = parameter;
         super();
    }

    @ParametersFactory
    public static Iterable<Object[]> parameters() throws Exception {
        return parameters(a,b,c);
    }
    public void testSampleParameterizedTest() {
        System.out.println(parameter);
        .....
    }
}
```

**Expected behavior**
`testSampleParameterizedTest` should be called 3 times with parameter set to a,b,c.

**Plugins**
OpenSearch Anomaly Detection

**Comment by dblock** [comment]
What's the error? ;)

**Comment by saratvemulapalli** [comment]
> What's the error? ;)

Good point, let me add the error. 
Also, I see it working for folks who use Yaml test case: https://github.com/AmiStrn/opensearch-plugin-template/blob/main/src/yamlRestTest/java/org/opensearch/path/to/plugin/TemplateClientYamlTestSuiteIT.java#L22

**Comment by saratvemulapalli** [comment]
Parameterized testing is working, its just how it is setup in AD which was a problem. 
Ref: 
https://github.com/search?q=org%3Aopensearch-project+ParametersFactory&type=code
