### ISSUE TITLE
Release Version 2.7.0

### ISSUE THREAD

**Issue by zelinh** [opensearch-project/OpenSearch#6967]
This is a component issue for 2.7.0.
Coming from [opensearch-build#3230](https://github.com/opensearch-project/opensearch-build/issues/3230). Please follow the following checklist.
__Please refer to the DATES in that post__.

<details><summary>How to use this issue</summary>
<p>

## This Component Release Issue

This issue captures the state of the OpenSearch release, on component/plugin level; its assignee is responsible for driving the release. Please contact them or @mention them on this issue for help.
Any release related work can be linked to this issue or added as comments to create visiblity into the release status.

## Release Steps

There are several steps to the release process; these steps are completed as the whole component release and components that are behind present risk to the release. The component owner resolves the tasks in this issue and communicate with the overall release owner to make sure each component are moving along as expected.

Steps have completion dates for coordinating efforts between the components of a release; components can start as soon as they are ready far in advance of a future release. The most current set of dates is on the overall release issue linked at the top of this issue.

## The Overall Release Issue

Linked at the top of this issue, the overall release issue captures the state of the entire OpenSearch release including references to this issue, the release owner which is the assignee is responsible for communicating the release status broadly.  Please contact them or @mention them on that issue for help.

## What should I do if my plugin isn't making any changes?

If including changes in this release, increment the version on `__2.x__` branch to `__2.7.0__` for Min/Core, and `__2.7.0.0__` for components. Otherwise, keep the version number unchanged for both.

</p>
</details>

### Preparation

- [x] Assign this issue to a release owner.
- [ ] Finalize scope and feature set and update [the Public Roadmap](https://github.com/orgs/opensearch-project/projects/1).
- [x] All the tasks in this issue have been reviewed by the release owner.
- [x] Create, update, triage and label all features and issues targeted for this release with `v2.7.0`.

### CI/CD

- [x] All code changes for `2.7.0` are complete.
- [x] Ensure working and passing CI.
- [x] Check that this repo is included in the [distribution manifest](https://github.com/opensearch-project/opensearch-build/blob/main/manifests/2.7.0).

### Pre-Release

- [x] Update to the `2.7` release branch in the [distribution manifest](https://github.com/opensearch-project/opensearch-build/blob/main/manifests/2.7.0).
- [x] Increment the version on the parent branch to the next development iteration.
- [x] Gather, review and publish release notes following the [rules](https://github.com/opensearch-project/opensearch-plugins/blob/main/RELEASE_NOTES.md) and back port it to the release branch.[git-release-notes](https://github.com/ariatemplates/git-release-notes) may be used to generate release notes from your commit history.
- [x] Confirm that all changes for `2.7.0` have been merged.
- [x] Add this repo to the [manifest](https://github.com/opensearch-project/opensearch-build/blob/main/manifests/) for the next developer iteration.

### Release Testing

- [x] Find/fix bugs using latest tarball and docker image provided in parent release issue and update the release notes if necessary.
- [x] Code Complete: Test within the distribution, ensuring integration, backwards compatibility, and performance tests pass.
- [x] Sanity Testing: Sanity testing *and* fixing of critical issues found.
- [x] File issues for all intermittent test failures.

### Release

- [x] Complete [documentation](https://github.com/opensearch-project/documentation-website).
- [x] Verify all issued labeled for this release are closed or labelled for the next release.
- [x] Verify the release date mentioned in release notes is correct and matches actual release date.

### Post Release

- [x] Prepare for an eventual security fix development iteration by incrementing the version on the release branch to the next eventual patch version.
- [ ] Add this repo to the [manifest](https://github.com/opensearch-project/opensearch-build/blob/main/manifests/) of the next eventual security patch version.
- [x] [Suggest improvements](https://github.com/opensearch-project/opensearch-build/issues/new) to [this template](https://github.com/opensearch-project/opensearch-build/blob/main/.github/ISSUE_TEMPLATE/component_release_template.md).
- [x] Conduct a retrospective, and publish its results.

**Comment by kotwanikunal** [comment]
Reached out to core feature owners: 
- https://github.com/opensearch-project/OpenSearch/issues/4244
- https://github.com/opensearch-project/OpenSearch/issues/1018

**Comment by Rishikesh1159** [comment]
>All code changes for 2.7.0 are complete.

Currently there is one [PR ](https://github.com/opensearch-project/OpenSearch/pull/7018) tagged with v2.7.0 label. Reached to author to update the PR. If  we don't see any response from author I will move this PR's scope out of v2.7.0 

Currently there is few [issues](https://github.com/opensearch-project/OpenSearch/issues?q=is%3Aopen+is%3Aissue+label%3Av2.7.0) tagged with v2.7.0. I will reachout to authors and update the issues.

**Comment by Rishikesh1159** [comment]
- Bump 2.x to 2.8.0 - https://github.com/opensearch-project/OpenSearch/pull/7237

- Adding 2.8.0 as BWC version in main - https://github.com/opensearch-project/OpenSearch/pull/7238

**Comment by Rishikesh1159** [comment]
>Check that this repo is included in the [distribution manifest](https://github.com/opensearch-project/opensearch-build/blob/main/manifests/2.6.0).
>Update to the 2.6 release branch in the [distribution manifest](https://github.com/opensearch-project/opensearch-build/blob/main/manifests/2.6.0).
>Add this repo to the [manifest](https://github.com/opensearch-project/opensearch-build/blob/main/manifests/) for the next developer iteration.

Starting from v2.4.0, the https://github.com/orgs/opensearch-project/teams/engineering-effectiveness team owns switching of .x branches to release branches in the manifest. The team will update the manifest once the release branch is created, so all of these tasks can be marked as done.

**Comment by Rishikesh1159** [comment]
Followed the same process mentioned by @kartg [here](https://github.com/opensearch-project/OpenSearch/issues/6360#issuecomment-1440766744) to generate release notes
