### ISSUE TITLE
Lower barrier to contribution

### ISSUE THREAD

**Issue by jesperolsson-se** [opensearch-project/OpenSearch#699]
I worry that potential contributors may walk away from this project. For any GitHub project, the `README` is the first (and often only) impression and must thus aim to engage the reader. When reading the current version, I mostly feel indifference.

Right now, the focus is on _what_ OpenSearch is, not _why_. It doesn't reflect any [values](https://opensource.org/node/1099) or [beliefs](https://aws.amazon.com/blogs/opensource/introducing-opensearch/), and does not inspire a sense of urgency—in [contrast](https://aws.amazon.com/blogs/opensource/stepping-up-for-a-truly-open-source-elasticsearch/) to the founding documents (which aren't even referenced!).

The change should be comparatively effortless: A short pitch at the beginning of the document and a couple of links to more in-depth discussions. Of course, I'd be happy to help out and produce a draft, but I'm not fully familiar with the implications of Elastic's decision.

**Comment by dblock** [comment]
Would like to see a PR for this. I would however leave this project's readme to mostly technical aspects and link to things like https://aws.amazon.com/blogs/opensource/introducing-opensearch/ that you're proposing.

**Comment by CEHENKLE** [comment]
@jesperolsson-se Thanks for the feedback.  I was trying to reference the "whys" by embedding the principles in the readme, but if there's more we should put in, I'm open to it.   Do you have examples of readmes you think do a good job?   

Also, as @dblock says, I welcome PRs (I added the help wanted labels). 

Thanks,
/C

**Comment by stockholmux** [comment]
@jesperolsson-se Content might be valuable over on the [project-website](https://github.com/opensearch-project/project-website) too. Contributions are welcome at that location as well.

**Comment by nknize** [comment]
> @jesperolsson-se Content might be valuable over on the [project-website](https://github.com/opensearch-project/project-website) too. Contributions are welcome at that location as well.

100% agree with this!

**Comment by jesperolsson-se** [comment]
Thank you all for your feedback! Please assign me and I'll start working on a PR as soon as I can find the time.

@CEHENKLE By and large, I think [these suggestions](https://www.yegor256.com/2019/04/23/elegant-readme.html) are pretty good advice (a few examples are linked at the bottom). Perhaps not all of them, and perhaps we should make some deviations—this being a fork and all.

**Comment by CEHENKLE** [comment]
@jesperolsson-se Done :)  And thanks!

**Comment by regnard** [comment]
Hey folks, I'm new to this project and this looks something a newb like me can do to gain momentum. How do I help out with this one?

**Comment by dblock** [comment]
@jesperolsson-se opened https://github.com/opensearch-project/OpenSearch/pull/712 that is being discussed there

**Comment by jesperolsson-se** [comment]
@regnard 

I apologise for the late reply. I was unsure of the scope of my PR and didn't want to answer prematurely. Although **I'm satisfied** with this ticket (as written), I'd say there are a couple of adjacent issues that you might want to **open new tickets** for. Please see the link I posted in a comment above, if you're looking for inspiration. Personally, I think that **badges** is a superb way to communicate the health and tool set of a project and would recommend looking into that (unfortunately, myself isn't too keen to try and reverse engineer the necessary information but I'm sure others would be happy to help out).
