### ISSUE TITLE
[Optimization] Duplication of mapping parameters across all indices

### ISSUE THREAD

**Issue by soosinha** [opensearch-project/OpenSearch#7001]
**Is your feature request related to a problem? Please describe.**
When there are large number of indices on a cluster, it increases the JVM footprint on a master/data node. This can cause the master/data node to go OOM.

**Simulation of Data Node OOM**
- A small cluster was created with 1 master and 1 data node with 1 GB heap size
- A large index template was created which had around 600 mappings.
- Around 600 indices were created using the template.
- Data node went out of memory.

**Analysis**
When an index is created, its metadata gets loaded in memory on the data node where it is present. When the heap dump for the data node was analyzed, it was found that around 80% of the heap space was occupied by `MapperService` classes. One instance of `MapperService` is created for every index present on the data node. There was about 1.2 MB space taken per instance of MapperService. Under each MapperService there was an instance of DocumentMapper which contained a hashmap of field level mappers. Each field mapper contained around 10-15 parameters for the field metadata. These field parameters are taking up space even though these are not explicitly defined for the field. When aggregated across around 600 fields in the 600 indices, these parameters take up the majority of the space. These is opportunity to optimize these by referring to some default parameters.
Code Path: `MapperService → mapper (DocumentMapper) → fieldMappers (Map) → builder (TextFieldMapper.Builder) → boost (ParameterizeFieldMapper.Parameter)`

<img width="1140" alt="issue" src="https://user-images.githubusercontent.com/81695996/230056994-fed8809e-f357-491c-93e5-44d09d32773b.png">

**Simulation of Master node OOM**
- A small cluster was created with 1 master and 2 data node with 1 GB heap size each
- A large index template was created which had around 600 mappings.
- Around 600 indices were created using the template.
- A single field mapping was updated across all the indices by using the wildcard `*` on `PUT _mappings` API
- Master node went out of memory

**Analysis**
When the heap dump of the master node was analyzed, similar objects like the data node issue were noticed. MapperService is not loaded usually on the master node. But when the mapping gets updated for indices, it loads the MapperService of those indices temporarily in memory. So again an optimization around the duplication of mapping parameters would help here.

**Describe the solution you'd like**
Everytime an index is created, new instances of mapping parameters are created and loaded in memory even though the parameters are not explicitly defined. We can use default instance for each mapping parameter and point the reference of the mapping parameter of a new index to the default instance.

**Comment by shwetathareja** [comment]
Thanks for the detailed analysis @soosinha 

One key aspect when creating singleton object for those mapping parameters would be to ensure immutability of those objects as otherwise it can cause data corruption/ overwrites across indices.

**Comment by soosinha** [comment]
Made changes to remove the builder instance from `TextFieldMapper`. The retained size of a TextFieldMapper object was reduced from 3300 bytes to 376 bytes (88%). So we should see great benefit in the JVM usage for cluster with lot of indices and lot of mappings.
In my test case, I created a cluster with 700 indices with each index having 600 field mappings(250 text type fields). The heap usage on a data node reduced from 900 MB to around 500 MB.

Draft PR for the changes: https://github.com/soosinha/OpenSearch/pull/1

**Comment by shwetathareja** [comment]
Thanks @soosinha!  for ```TextFieldMapper``` , the gain looks great. Left a comment on PR. From the cursory look, it looks safe to remove the builder object as it is not referenced later. Lets run the whole test suite on your changes.
