### ISSUE TITLE
Enabling certificate hostname verification for Netty

### ISSUE THREAD

**Issue by NotJoshu** [opensearch-project/OpenSearch#7030]
We have received a security notification to a vulnerability inside `io.netty:netty-handler`, which we are using transitively via `org.opensearch.plugin:transport-netty4-client`.

Vulnerability details: https://security.snyk.io/vuln/SNYK-JAVA-IONETTY-1042268

Netty doesn't have certificate hostname verification enabled by default in Netty 4, and has no plans to change this until the next major release of Netty 5. Other libraries have made changes to manually enable this:

https://github.com/aws/aws-sdk-java-v2/pull/1184/files#diff-0a4c5b5016e0d0df7ff524caf127245455248ce52c393853cec0a40c95a8f5a1R103
https://github.com/reactor/reactor-netty/pull/273/commits/7101ec7348bac163e1294dcd6952eea6276aea1c#diff-e05f77244b1855b5e7e8eef90ada5263d0593e3f01c691dd6326064b5cc792e0R95

Does something similar need to be applied to the OpenSearch clients?

**Comment by kotwanikunal** [comment]
@NotJoshu I had a chat within the team and the security team pointed out that we already have this applied as a part of the security package [here](https://github.com/opensearch-project/security/blob/main/src/main/java/org/opensearch/security/ssl/DefaultSecurityKeyStore.java#L685).

cc: @davidlago 

Additional context: 
From the searches: 
- https://github.com/search?q=org%3Aopensearch-project%20io.netty%3Anetty-handler&type=code
- https://github.com/search?q=org%3Aopensearch-project+setEndpointIdentificationAlgorithm&type=code

**Comment by NotJoshu** [comment]
That's great, thank you for confirming.
