### ISSUE TITLE
[Searchable Remote Index] Add safeguards to ensure a cluster cannot be over-subscribed

### ISSUE THREAD

**Issue by andrross** [opensearch-project/OpenSearch#7033]
A searchable snapshot index consumes some resources in the cluster and also requires some amount of local disk to store cached data. Therefore storage is not infinite and there are limits, beyond which the user experience will degrade to unacceptable levels. The goal of this task is to add safeguards to ensure a reasonable user experience is maintained.

We should implement limits to ensure the cluster stays healthy and cannot be unwittingly pushed into an unusable state. In particular, there are two areas to investigate here:
 - **([Broken out as separate issue](#7095))** At search time, if there are enough concurrent searches that there is no capacity remaining in the reserved disk cache, then searches should be rejected with an appropriate error message.
 - At searchable snapshot index creation time, we should implement limits and reject the requests if the cluster capacity is exceeded. This can likely be implemented as a ratio of cluster-based disk cache size to total data size in the remote repository.

Note that there is future work to implement features that give more of an "infinite" storage experience (at the cost of higher search latencies), but searchable snapshots as it is implemented today keeps some metadata loaded so that data readily searchable and therefore subject to some limits.

**Comment by kotwanikunal** [comment]
Digging a bit into this issue - 
>  This can likely be implemented as a ratio of cluster-based disk cache size to total data size in the remote repository.

I think this will have to be a function of `n *(restored_index_size)` and `m * (disk_cache_size)` where `n` is the number of indices the user has restored, and `m` is the number of `search` nodes the user has (corresponds to total disk cache size). 

When restoring an index, we will check if `n * (restored_index_size) + (requested_restored_index_size)` is within the bounds to the ratio of `m * (disk_cache_size)` or `total_disk_cache_size`.

**Comment by xiaoshi2013** [comment]
good
