### ISSUE TITLE
[Searchable Snapshot] Remove superfluous 'nodeId' in cache path

### ISSUE THREAD

**Issue by andrross** [opensearch-project/OpenSearch#7059]
The file cache path currently looks like: `/usr/share/opensearch/data/nodes/<node-lock-id>/cache/<node-lock-id>/<index-id>/<shard-id>/RemoteLocalStore`

The "node lock ID" part of the path is duplicated and the second one is unnecessarily added here: https://github.com/opensearch-project/OpenSearch/blob/06128a904964ce43813ebc8164417a5633d414a2/server/src/main/java/org/opensearch/env/NodeEnvironment.java#L1310

We should remove it for simplicity and to avoid future confusion. We should do that while the feature is experimental since this will be a breaking change.

**Comment by govegito** [comment]
Hi, @andrross !
I would like to work on this issue. Can you assign it to me, please?
