### ISSUE TITLE
Remove the workaround used to access Lucene's "expert" readLatestCommit API

### ISSUE THREAD

**Issue by kartg** [opensearch-project/OpenSearch#7084]
**Is your feature request related to a problem? Please describe.**
Currently, the "expert" `readLatestCommit` API is [package-private in Lucene](https://github.com/apache/lucene/blob/2d7908e3c93d326bd5ac967fe30120dfb13d4182/lucene/core/src/java/org/apache/lucene/index/SegmentInfos.java#L520), which prevents OpenSearch from accessing it directly. Thus, the code path that [enables searchable snapshots to read legacy versions](https://github.com/opensearch-project/OpenSearch/issues/5948) uses [a workaround](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/common/lucene/Lucene.java#L139-L145).

**Describe the solution you'd like**
Submit a PR to the Lucene code base to make this method publicly accessible so OpenSearch can invoke it directly, simplifying our implementation and eliminating the workaround.

**Describe alternatives you've considered**
Most callers in OpenSearch that invoke this method use the returned `SegmentInfos` object to access [userData](https://github.com/apache/lucene/blob/dba100313f9ba4d36e789525cd39f00e0b5e789c/lucene/core/src/java/org/apache/lucene/index/SegmentInfos.java#L988). Since userData is associated with a commit, the same information can be accessed via the `IndexCommit` via the `listCommits` API (which [uses the expert API internally](https://github.com/apache/lucene/blob/0a069ed4542ab672230d3610d91a9eababead199/lucene/core/src/java/org/apache/lucene/index/DirectoryReader.java#L267)):

```
List<IndexCommit> indexCommits = DirectoryReader.listCommits(directory);
IndexCommit latestCommit = indexCommits.get(indexCommits.size() - 1);
return latestCommit.getUserData();
```

Changing all callers to use an `IndexCommit` instead of a `SegmentInfos` object would require a considerable refactoring of the code. Further, the [Engine class](https://github.com/opensearch-project/OpenSearch/blob/2b779851a8042e302ee54dfdaeff9f251b2c9b18/server/src/main/java/org/opensearch/index/engine/Engine.java#L187) and its implementations rely on tracking the latest `SegmentInfos` object rather than the latest `IndexCommit`. Finally, there are a few instances where `totalMaxDoc` is accessed ([[1]](https://github.com/opensearch-project/OpenSearch/blob/0a2009250cd857d68cdfa87340f8cd1b906d8c6e/server/src/main/java/org/opensearch/index/engine/ReadOnlyEngine.java#L149), [[2]](https://github.com/opensearch-project/OpenSearch/blob/0a2009250cd857d68cdfa87340f8cd1b906d8c6e/server/src/main/java/org/opensearch/index/engine/NRTReplicationEngine.java#L368)), which has no equivalent API with `IndexCommit`.

**Additional context**
N/A

**Comment by kartg** [comment]
PR with Lucene - https://github.com/apache/lucene/pull/12229

**Comment by saratvemulapalli** [comment]
@kartg the PR on lucene is merged, is there anything else here for this issue?

**Comment by kartg** [comment]
@saratvemulapalli Yes we still need to remove the workaround in the OpenSearch code :)

Once https://github.com/opensearch-project/OpenSearch/pull/7505 is merged and backported, we can make those changes and then close out this issue
