### ISSUE TITLE
[DISCUSS] Is finishHim() an appropriate method name?

### ISSUE THREAD

**Issue by dbwiddis** [opensearch-project/OpenSearch#7087]
Disclaimer 1:  I have played [Mortal Kombat](https://en.wikipedia.org/wiki/Mortal_Kombat) in my younger days and fully recognize that the phrase "Finish Him!" is embedded in pop culture.   

Disclaimer 2: I do have a sense of humor.

Disclaimer 3: There may be some reference to inclusivity here, but it's not obvious.  Still, when I [encountered the `finishHim()` method in the OpenSearch codebase](https://github.com/search?q=repo%3Aopensearch-project%2FOpenSearch%20finishhim&type=code), it did [tweak my spidey-senses](https://en.wikipedia.org/wiki/Controversies_surrounding_Mortal_Kombat).

But in reality, even ignoring any inclusivity issues or references to violence, it's a very poorly named method. I don't know what it does.  I presume it closes some resource somewhere, analogous to the `kill` command.  That's cool.   And it's totally fine as an internal private method where it's localized.  Funny comments are fun. I get it.

But it's a protected method inherited from multiple classes, and has no JavaDoc anywhere, so the mass killing is spreading.

I'd like to suggest either:
 - rename the method to be more descriptive of what it actually does, or
 - document what it does and why we are paying homage to a 30-year-old video game (as awesome as it was/is)

**Comment by dblock** [comment]
Looks like https://github.com/opensearch-project/OpenSearch/blob/1c8421805955341ab692b003416b45b8d55ccd24/server/src/main/java/org/opensearch/action/search/AbstractSearchAsyncAction.java#L698 says that it's a tribute to @kimchy, maybe someone knows the history here? In general, I think cultural tributes are important to preserve as an element of respect to those who built the software, but it sounds like you'd like to rename the method for other good reasons, I would support that.

**Comment by dbwiddis** [comment]
I'm ok with leaving the tribute but perhaps the protected method, at least, should be documented better.

**Comment by dbwiddis** [comment]
Looked into this a bit more, realized this method dates from 2011 and 0.x versions, and while it deserves better documentation, doesn't need to be treated differently.
