### ISSUE TITLE
[BUG] GlobalAggregation with profile option enabled returns incorrect result

### ISSUE THREAD

**Issue by sohami** [opensearch-project/OpenSearch#7088]
**Describe the bug**
Global Aggregation in a search request should execute on all the documents instead of the documents filtered by the query provided in the request. When profile option is disabled this work as expected. When profile is enabled it aggregates only on the documents filtered by the query instead on all the documents.

**To Reproduce**
By enabling the profile option in the GlobalIT [here](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/internalClusterTest/java/org/opensearch/search/aggregations/bucket/GlobalIT.java#L86) the test starts failing

**Expected behavior**
With profile enabled the test should be successful

**Plugins**
N/A

**Screenshots**
N/A

**Host/Environment (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by sohami** [comment]
I know the fix for this and will be opening a PR soon

**Comment by andrross** [comment]
Fixed by #7114
