### ISSUE TITLE
[BUG] org.opensearch.index.reindex.ReindexRestClientSslTests#testClientSucceedsWithCertificateAuthorities - javax.net.ssl.SSLPeerUnverifiedException

### ISSUE THREAD

**Issue by npetzall** [opensearch-project/OpenSearch#710]
**Describe the bug**
Test assume that host name returned for 127.0.0.1 will be one of the Subject alternative names.

But due to Windows 10, Docker + Kubernetes, host name returned for 127.0.0.1 might be 'kubernetes.docker.internal'

**To Reproduce**
1. Windows 10, Docker desktop and kubernetes enabled.
2. Run test

**Expected behavior**
That the test would only use one of the subject alternative names since it's required for the test to pass.

**Host/Environment (please complete the following information):**
 - OS: Windows
 - Version 10

**Additional context**
Docker Desktop with Kubernetes enabled

Since both IP address for localhost (ipv4(127.0.0.1) and ipv6(0:0:0:0:0:0:0:1)) are subject alt names, `java.net.InetAddress#getHostAddress` could probably be used instead of `java.net.InetSocketAddress#getHostName`

**Exception thrown:**
```
org.opensearch.index.reindex.ReindexRestClientSslTests > testClientSucceedsWithCertificateAuthorities FAILED
    java.io.IOException: Host name 'kubernetes.docker.internal' does not match the certificate subject provided by the peer (CN=http)
        at __randomizedtesting.SeedInfo.seed([6594F1A74C93240B:C2C43EFC3F989FE6]:0)
        at org.opensearch.client.RestClient.extractAndWrapCause(RestClient.java:897)
        at org.opensearch.client.RestClient.performRequest(RestClient.java:296)
        at org.opensearch.client.RestClient.performRequest(RestClient.java:283)
        at org.opensearch.index.reindex.ReindexRestClientSslTests.testClientSucceedsWithCertificateAuthorities(ReindexRestClientSslTests.java:157)

        Caused by:
        javax.net.ssl.SSLPeerUnverifiedException: Host name 'kubernetes.docker.internal' does not match the certificate subject provided by the peer (CN=http)
            at org.apache.http.nio.conn.ssl.SSLIOSessionStrategy.verifySession(SSLIOSessionStrategy.java:209)
            at org.apache.http.nio.conn.ssl.SSLIOSessionStrategy$1.verify(SSLIOSessionStrategy.java:188)
            at org.apache.http.nio.reactor.ssl.SSLIOSession.doHandshake(SSLIOSession.java:360)
            at org.apache.http.nio.reactor.ssl.SSLIOSession.isAppInputReady(SSLIOSession.java:523)
            at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:120)
            at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162)
            at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337)
            at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
            at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276)
            at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
            at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:591)
            at java.base/java.lang.Thread.run(Thread.java:832)
```

**Comment by setiah** [comment]
Hi @npetzall, shouldn't this work by having a dns entry for host name `kubernetes.docker.internal` in docker/kubernetes equivalent of `/etc/hosts`? Seems to me more like a docker issue than opensearch. I see similar problems reported on docker project [here](https://github.com/docker/for-mac/issues/2965#issuecomment-757603343)

**Comment by npetzall** [comment]
@setiah sorry if I'm not clear in the issue. The test in OpenSearch starts a https server on localhost with ssl certificates with dns names like localhost, 127.0.0.1. The the test creates a client, which with the current implementation, does a reverse lookup of 127.0.0.1 which is `kubernetes.docker.internal`. Tries to connect to `kubernetes.docker.internal` and the exception is thrown in ssl verification which says `kubernetes.docker.internal` is not part of the ssl certificate of the https server.

Any host which has entry in etc/host for 127.0.0.1 that isn't localhost or one of the subject alt names in the certificate will get a failed test. I generalize here a bit any host that receives something other than localhost in 127.0.0.1 reverse lookup will fail.

So the problem is that I have and need to have `kubernetes.docker.internal` in my host-file.

I can add a second entry for localhost after the `kubernetes.docker.internal` but I say it's bad practice to modify hosts-files and a messy additional step when clearly setting up a server with certificates for localhost and connecting with a different name is bound to fail.

**Comment by setiah** [comment]
Thanks for the details @npetzall - this makes it clear.  

>I can add a second entry for localhost after the kubernetes.docker.internal but I say it's bad practice to modify hosts-files

Agree, it should not be done. 

>Since both IP address for localhost (ipv4(127.0.0.1) and ipv6(0:0:0:0:0:0:0:1)) are subject alt names, java.net.InetAddress#getHostAddress could probably be used instead of java.net.InetSocketAddress#getHostName

Your suggestion looks good to me, but i'm not sure if localhost IPs are by default included in SANs (are they?). If not we might need to add them.

Also these test certificates should be rotated IMO (not urgent though), as they are coming from legacy elasticsearch codebase. (cc: @nknize )

**Comment by npetzall** [comment]
@setiah certificate used in the test `modules/reindex/src/test/resources/org/opensearch/index/reindex/http/http.crt`
Common Name: http
Subject Alternative Names: localhost, localhost6.localdomain6, IP Address:127.0.0.1, IP Address:0:0:0:0:0:0:0:1 , localhost4, localhost6, localhost.localdomain, localhost4.localdomain4
Valid From: January 9, 2019
Valid To: May 26, 2046
Serial Number: 5f1960ff4fe0dd461e91758146990733ce0461f2

I would say that having localhost in certificates is not practical except when testing/developing. There might be an edge case for it. But it's not added by default in any of the PKI software that I've seen, but I've seen few such systems.

**Comment by setiah** [comment]
>I would say that having localhost in certificates is not practical except when testing/developing.

Agree, since it is only for testing, it should be fine. 

>Common Name: http
Subject Alternative Names: localhost, localhost6.localdomain6, IP Address:127.0.0.1, IP Address:0:0:0:0:0:0:0:1 , localhost4, localhost6, localhost.localdomain, localhost4.localdomain4
Valid From: January 9, 2019
Valid To: May 26, 2046
Serial Number: 5f1960ff4fe0dd461e91758146990733ce0461f2

Could you please share the source of this information?

The proposal looks good to me. Happy to review if you would like to raise a PR?

**Comment by npetzall** [comment]
@setiah  You can copy the cert information found in [modules/reindex/src/test/resources/org/opensearch/index/reindex/http/http.crt](https://raw.githubusercontent.com/opensearch-project/OpenSearch/main/modules/reindex/src/test/resources/org/opensearch/index/reindex/http/http.crt)

And use an online decoder like https://comodosslstore.com/ssltools/cert-decoder.php

**Comment by setiah** [comment]
@npetzall ah nice. I was doing the b64decode of the content earlier, which did return partial information with some garbled content. This is useful, thanks.

**Comment by reta** [comment]
@dblock I think we could close this one, thank you!

**Comment by dblock** [comment]
Thanks for your excellent work @reta!
