### ISSUE TITLE
[BUG]Unable to delete a specific index in OpenSearchServerless

### ISSUE THREAD

**Issue by huuyafwww** [opensearch-project/OpenSearch#7121]
**Describe the bug**
Cannot delete a specific index.

**To Reproduce**
Reproducibility is unknown, but that collection in OpenSearchServerless is the first collection created, and the indices that cannot be deleted are the first indices created in that collection.

**Expected behavior**
Indexes can be deleted without error.

**Plugins**
N/A

**Screenshots**
The following response is returned when requesting to delete an index in OpenSearchDashboard.
Of course, we are still checking that the corresponding index is available in "GET _cat/indices".

```json
{
  "error": {
    "root_cause": [
      {
        "type": "class_cast_exception",
        "reason": "class java.util.Collections$EmptyList cannot be cast to class java.util.ArrayList (java.util.Collections$EmptyList and java.util.ArrayList are in module java.base of loader 'bootstrap')"
      }
    ],
    "type": "class_cast_exception",
    "reason": "class java.util.Collections$EmptyList cannot be cast to class java.util.ArrayList (java.util.Collections$EmptyList and java.util.ArrayList are in module java.base of loader 'bootstrap')"
  },
  "status": 500
}
```

**Host/Environment (please complete the following information):**
 - OpenSearchServerless
 - region: ap-northeast-1

**Comment by dblock** [comment]
Do you have a ticket with OpenSearch Serverless yet? If not you should open one, please.

**Comment by dvjyothsna** [comment]
This is a confirmed bug and the team is working on the fix - https://app.asana.com/0/1204084198010796/1204384642330217/f
