### ISSUE TITLE
Upgrade path from odfe 1.13

### ISSUE THREAD

**Issue by pujan14** [opensearch-project/OpenSearch#7139]
We are planning to upgrade over moderately large cluster from odfe 1.13 to OpenSearch 2.6. After going through documentation I was not able to figure out exact upgrade path we need to take and if we need to plan downtime or we can do this with rolling restarts.

Also as part of the upgrade I understand some configuration parameters have changed names, is there any kind of backward compatibility in this aspect so we can rename/update parameter names in separate step after the upgrade?

**Comment by dblock** [comment]
You should be able to do a rolling upgrade per https://opensearch.org/docs/2.0/install-and-configure/upgrade-opensearch/index/ without downtime or any breaking changes to OpenSearch 1.x first. There's a lot of words and links in that doc that should be helpful.

A number of breaking changes were introduced in 2.0, which are YMMV. See https://opensearch.org/docs/2.0/breaking-changes/, you'll need to look into whether any of those are problematic for your client-side use-cases.

Either way you should test an upgrade first. We can help you at any step of the way, the best place is probably to ask questions as you run into issues on [the new OpenSearch Slack](https://opensearch.org/slack.html). I'll close this issue for now, but feel free to ask questions below if you need more help.
