### ISSUE TITLE
[Remote Store] Balanced distribution of remote store enabled shards across data nodes to avoid remote transfer hotspot on data nodes

### ISSUE THREAD

**Issue by linuxpi** [opensearch-project/OpenSearch#7157]
**Is your feature request related to a problem? Please describe.**
Remote store sync data to/from remote storage. Since a cluster can have both remote enabled and disabled indices at the same time, it is possible that most of the remote enabled shards end up on few of the data nodes and cause a hotspot in terms of remote transfers. 

**Describe the solution you'd like**
While allocating shards distribute remote shard evenly across data nodes. We can also consider other node attrs like zone etc while distributing shards. 

Goal would be avoid any kind of skew to a small group of nodes when it comes to remote data transfers. We should compare performance benefits after this is done

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by gbbafna** [comment]
Closing this now as we can't have remote enabled/disabled indices at the same time .
