### ISSUE TITLE
Update the segment replication documentation with recommended/optimal configuration for optimal results for SegRep

### ISSUE THREAD

**Issue by nandi-github** [opensearch-project/OpenSearch#7168]
**Is your feature request related to a problem? Please describe.**
Segment Replication replication method needs the configuration to be optimized for the best performance. 

**Describe the solution you'd like**
Engineering has identified this configuration, please document the recommended configuration in blog post and regular documentation

**Describe alternatives you've considered**
NA
**Additional context**
NA

**Comment by ariamarble** [comment]
documentation updated
