### ISSUE TITLE
[Segment Replication] Enable Segment Replication Backpressure by default

### ISSUE THREAD

**Issue by Rishikesh1159** [opensearch-project/OpenSearch#7182]
**Is your feature request related to a problem? Please describe.**
Segment Replication Backpressure mechanism is triggered when node setting `SEGMENT_REPLICATION_INDEXING_PRESSURE_ENABLED` is enabled. We want to enable this setting by default instead of user manually enabling this setting every time .

**Describe the solution you'd like**
Change the default value of `SEGMENT_REPLICATION_INDEXING_PRESSURE_ENABLED` to true.

**Describe alternatives you've considered**

**Additional context**

**Comment by dblock** [comment]
This was reverted in https://github.com/opensearch-project/OpenSearch/pull/7292#event-9082588877, let's reopen.
