### ISSUE TITLE
Setting.groupSetting does not support fallbackSetting

### ISSUE THREAD

**Issue by andy840314** [opensearch-project/OpenSearch#719]
While migrating settings from opendistro to opensearch for security plugin, we found that `Setting.groupSetting `does not support `fallbackSetting` like other setting does. This makes security plugin difficult to achieve backward compatibility for the settings that uses `Setting.groupSetting`.

This is one of the setting in security plugin that uses `Setting.groupSetting`:
[Link](https://github.com/opensearch-project/security/blob/f698fe6c2168da3765f9aa151774da64ec024412/src/main/java/com/amazon/opendistroforelasticsearch/security/OpenDistroSecurityPlugin.java#L880)

This is the `Setting.groupSetting` i am referring to:
https://github.com/opensearch-project/OpenSearch/blob/6732239f1cbcc91941f4f6e43f3909a5896b73fd/server/src/main/java/org/opensearch/common/settings/Setting.java#L1009

**Comment by nknize** [comment]
I don't think the omission of the static factory method was intentional. If this unblocks bwc for the security plugin we can open a PR to add something like:

```java
    public static Setting<Settings> groupSetting(String key, Setting<Settings> fallbackSetting, Consumer<Settings> validator, 
                                                 Property... properties) {
        return new GroupSetting(key, fallbackSetting, validator, properties);
    }

    public static Setting<Settings> groupSetting(String key, Setting<Settings> fallbackSetting, Property... properties) {
        return new GroupSetting(key, fallbackSetting, (s) -> {}, properties);
    }
```

Then just add the appropriate xtor in the `GroupSetting` private class. We can open the PR but I think this would be a good opportunity for you to do it and gain some of the experience? Do you want to take this issue @andy840314?

**Comment by dblock** [comment]
Attempt at an implementation in https://github.com/opensearch-project/OpenSearch/pull/743.

**Comment by andy840314** [comment]
@dblock Thanks for the implementation, this helps a lot!

> We can open the PR but I think this would be a good opportunity for you to do it and gain some of the experience? Do you want to take this issue @andy840314?

I could take the issue but given the timeline for settings migration, it would be really tight for me to get this done.

**Comment by dblock** [comment]
Closed in https://github.com/opensearch-project/OpenSearch/pull/743
