### ISSUE TITLE
[BUG] Snapshotting a searchable snapshot index should only copy metadata

### ISSUE THREAD

**Issue by andrross** [opensearch-project/OpenSearch#7204]
Related to #7179

Steps to reproduce:
- create and populate an index, e.g. `my-index`
- take a snapshot: 
```
PUT _snapshot/my-repo/my-snapshot
```
- delete `my-index`
- create a searchable snapshot index, e.g:
```
POST _snapshot/my-repo/my-snapshot
{
  "indices": "my-index",
  "rename_pattern": "(.+)",
  "rename_replacement": "remote_$1",
  "storage_type": "remote_snapshot"
}
```
- take a snapshot:
```
PUT _snapshot/my-repo/my-snapshot-2
```

Expected behavior:
The snapshot repo should look like:
```
<base path>/indices/<my-index id>/meta-uuid.dat
<base path>/indices/<my-index id>/<shard>/<data files...>
<base path>/indices/<remote-my-index id>/meta-uuid.dat
```

Actual behavior:
The snapshot repo looks like:
```
<base path>/indices/<my-index id>/meta-uuid.dat
<base path>/indices/<my-index id>/<shard>/<data files...>
<base path>/indices/<remote-my-index id>/meta-uuid.dat
<base path>/indices/<remote-my-index id>/<data files...>
```

The `<remote-my-index id>/meta-uuid.dat` contains the metadata for the searchable snapshot index that points to the data files in `my-index`. However, the system still redundantly copies the data files. This should be avoided. Upon restore, the right thing happens as `remote-my-index` is restored with pointers back to the `my-index` data files. The redundantly copied data files end up being unused in the repository.

**Comment by bbarani** [comment]
Are we targeting to fix this in 2.7.0 release?
