### ISSUE TITLE
Segment replication cancellation of in-sync allocation ids in ReplicationTracker

### ISSUE THREAD

**Issue by dreamer-89** [opensearch-project/OpenSearch#7213]
Coming from https://github.com/opensearch-project/OpenSearch/issues/6761 exercise, `RecoveryWhileUnderLoadIT.testRecoverWhileRelocating` fails due to missing replication files from target store, failing [assertion](https://github.com/dreamer-89/OpenSearch/blob/10ab178f54a9d6552d2b48757387071ed9ef8264/server/src/main/java/org/opensearch/indices/recovery/MultiFileWriter.java#L155). This happens due to cancellation of segment replication, followed by replica shard failure, where engine's close action clears the temporary replication files.
 
Existing cancellation [logic](https://github.com/dreamer-89/OpenSearch/blob/10ab178f54a9d6552d2b48757387071ed9ef8264/server/src/main/java/org/opensearch/indices/replication/SegmentReplicationSourceService.java#L175) works on routing table changes and cancels segment replication for allocation ids which are not part of cluster metadata's in-sync ids. This can be problematic for cases where shard allocation just [marked](https://github.com/dreamer-89/OpenSearch/blob/10ab178f54a9d6552d2b48757387071ed9ef8264/server/src/main/java/org/opensearch/indices/recovery/RecoverySourceHandler.java#L802) in-sync is not yet applied on cluster state.

**Comment by DarshitChanpura** [comment]
@dreamer-89 Closing this issue as it was fixed via #7214 and backported to 2.x line via #7220 & #7221. Feel free to re-open it.
