### ISSUE TITLE
[BUG] Dissect ingest processor cannot parse empty value with brackets

### ISSUE THREAD

**Issue by gaobinlong** [opensearch-project/OpenSearch#7223]
**Describe the bug**
Dissect ingest processor cannot parse empty value with brackets like [], {}, or () correctly, when there exists an empty value with brackets in the text incidentally, the dissect processor throws exception `Unable to find match for dissect pattern...`.

**To Reproduce**
1. Create an ingest pipeline:
```
PUT _ingest/pipeline/test
{
  "processors": [
      {
        "dissect": {
          "field": "message",
          "pattern": "[%{@timestamp}][%{logLevel}][%{class}]"
        }
      }
    ]
}
```
2. Ingest some documents and using the above pipeline:

**normal case:**
```
POST test1/_doc?pipeline=test
{
  "message":"[2023-04-13T15:09:03,947][INFO][o.o.n.Node]"
}
```
**abnormal case**, the field `message` contains an empty value with brackets:
```
POST test1/_doc?pipeline=test
{
  "message":"[2023-04-13T15:09:03,947][INFO][]"
}
```
you can see the error below:
```
{
  "error": {
    "root_cause": [
      {
        "type": "find_match",
        "reason": "Unable to find match for dissect pattern: [%{@timestamp}][%{logLevel}][%{class}] against source: [2023-04-13T15:09:03,947][INFO][]"
      }
    ],
    "type": "find_match",
    "reason": "Unable to find match for dissect pattern: [%{@timestamp}][%{logLevel}][%{class}] against source: [2023-04-13T15:09:03,947][INFO][]"
  },
  "status": 500
}
```

**Expected behavior**
The dissect ingest processor can handle the text containing empty value with brackets gracefully, assign the value to empty string for the matched field.

**Screenshots**
<img width="1875" alt="image" src="https://user-images.githubusercontent.com/15811131/232742112-fff270e9-4d47-4bbd-b38d-cb211af7413f.png">

**Host/Environment (please complete the following information):**
 - OS: [Mac OS]
 - Version [OpenSearch 2.6.0]

**Comment by gaobinlong** [comment]
Sure, I will try to fix it and add some test code.

**Comment by msfroh** [comment]
@gaobinlong -- are you still planning to work on this one?

**Comment by gaobinlong** [comment]
Closed by https://github.com/opensearch-project/OpenSearch/pull/9255.
