### ISSUE TITLE
[Discuss] Benchmark class method do not have documentation

### ISSUE THREAD

**Issue by jainankitk** [opensearch-project/OpenSearch#724]
**Describe the bug**
Currently benchmark class methods do not have documentation

**Expected behavior**
Wondering what is our take on that.

* At one hand benchmarks are like tests and should be fine for test methods to not have documentation?
* At the other hand, it is good to have documentation for any piece of well written code. In this case, should we enforce by adding javadoc check as part of gradle precommit?

**Comment by CEHENKLE** [comment]
@setiah @peternied Thoughts?

**Comment by saratvemulapalli** [comment]
@jainankitk taking a stab at this.
Are you looking for client benchmark docs? 

Let me start answering this question: 
1. We do have Java docs for benchmarks. See if this helps and let us know if this is what you were looking for. https://opensearch.org/javadocs/1.0.0/OpenSearch/benchmarks/build/docs/javadoc/index.html
2. Second part of the question, I see you suggest having a pre-check for java docs before the PR is allowed to merge. 
This needs a follow up as I am not sure if precommit already covers it, if not we could add it.

**Comment by minalsha** [comment]
@jainankitk can you please share your comments on #2 prposed by @saratvemulapalli  here: https://github.com/opensearch-project/OpenSearch/issues/724#issuecomment-925395772

**Comment by dagneyb** [comment]
@jainankitk please let us know if this is resolved with @saratvemulapalli feedback. If we dont hear back by Nov 22nd, we'll consider this resolved. Thanks!

**Comment by dagneyb** [comment]
Closing as we have not heard back.
