### ISSUE TITLE
[BUG] Gradle precommits across commits are failing: Maven repo down

### ISSUE THREAD

**Issue by saratvemulapalli** [opensearch-project/OpenSearch#7254]
**Describe the bug**
Gradle precommits are failing due to repo.maven.apache.org being down.
Sample runs:
https://github.com/opensearch-project/OpenSearch/actions/runs/4748367531/jobs/8436586535
https://github.com/opensearch-project/OpenSearch/actions/runs/4748623226/jobs/8435026609

**Additional context**
From twitter: https://twitter.com/panghy/status/1648834933258092546
repo1.maven.org/maven2/ seems to be working.

**Comment by reta** [comment]
@saratvemulapalli should be back online
