### ISSUE TITLE
MissingJavaDoc checker to support * for ignoring group of files

### ISSUE THREAD

**Issue by saratvemulapalli** [opensearch-project/OpenSearch#7264]
**Is your feature request related to a problem? Please describe.**
MissingJavaDoc gradle task doesnt support ignoring group of files. 
For example: Generated code dont follow our standards and have to be ignored. 
Coming from PR: https://github.com/opensearch-project/OpenSearch/pull/6960#discussion_r1173143665 

**Describe the solution you'd like**
Add support to ignore multiple files with `*`

Eg:
Before:
```
javadocMissingIgnore = [
    "org.opensearch.extensions.proto.ExtensionRequestProto",
    "org.opensearch.extensions.proto.ExtensionRequestProto.ExtensionRequestOrBuilder",
    "org.opensearch.extensions.proto"
  ]
```
After:
```
javadocMissingIgnore = [
    "org.opensearch.extensions.proto.*"
  ]
```

**Comment by dbwiddis** [comment]
OpenSearch might want to consider using Checkstyle for javadocs as we do on SDK.   I know Checkstyle was removed for _style_, but it's got an extremely powerful feature set for configuring javadoc checks and if it's limited to those, I think it could replace our existing missing javadoc check, which is an unmaintained, copied-from-Lucene/Solr hack that I don't think anyone should spend time updating.

See also #4541

**Comment by austintlee** [comment]
I had a quick look and this looks like a fairly straightforward thing to support (a few lines of code).  But is it "safe" to support this?  It seems to me that perhaps this was by design.  Supporting '*' could lead to misuse/abuse.

**Comment by dblock** [comment]
+1 to what @austintlee says, but also maybe it's NBD and a fine workaround to mark generated code as such

Another option is to generate code that complies with our checkstyle.

**Comment by austintlee** [comment]
@saratvemulapalli I created a PR to suggest a possible way to make this work using an allowlist.  One question I have is around where that allowlist should be placed.  Please, take a look.  Thanks!

**Comment by austintlee** [comment]
If we are OK with this approach in general, I can also add some unit tests for MissingDoclet.  At the moment, this whole package (org.opensearch.missingdoclet) has no unit tests.

**Comment by austintlee** [comment]
I am proceeding with an approach that allows only generated classes annotated with '@javax.annotation.Generated' to be ignored.

Of course, all other exceptions will still need to be added to build.gradle manually.
