### ISSUE TITLE
Upgrade AWS SDK to v2

### ISSUE THREAD

**Issue by dblock** [opensearch-project/OpenSearch#7312]
**Is your feature request related to a problem? Please describe.**

Coming from https://github.com/opensearch-project/OpenSearch/pull/7216, upgrade AWS SDK v1 to v2 in discovery-ec2, repository-s3, etc.

**Describe the solution you'd like**

Upgrade SDK v1 to v2. 

- [ ] https://github.com/opensearch-project/OpenSearch/pull/7372
- [ ] https://github.com/opensearch-project/OpenSearch/issues/7391

**Describe alternatives you've considered**

Use SDK v1 and v2 side-by-side.

**Additional context**

There are [quite a few changes](https://github.com/aws/aws-sdk-java-v2/blob/master/docs/LaunchChangelog.md#7-high-level-libraries) between the SDKs, and some options may need to be dropped. For example, one can configure the protocol in AWS SDK v1, but in v2 it's hard-coded to HTTPs and can only be changed via URI.

**Comment by shwetathareja** [comment]
It would require full regression testing of snapshots with sdk2.

**Comment by vikasvb90** [comment]
Have you added all dependencies of v2 in the plugin? 
`awscore` and `http` dependencies of `software.amazon.awssdk` group seem to be missing as per the errors.

**Comment by dblock** [comment]
@vikasvb90 thanks, that works, `./gradlew :plugin:discovery-ec2:compileJava` and `./gradlew :plugin:discovery-ec2:compileTestJava` is good - I'll keep working on this on my copious free time, if anyone wants to help feel free to make PRs into my branch in https://github.com/dblock/OpenSearch/tree/aws-sdk-v2

**Comment by vikasvb90** [comment]
You can refer to #7216 PR. It has required changes to add v2 SDK dependencies.

**Comment by dblock** [comment]
Thanks @vikasvb90. I got `./gradlew :plugins:discovery-ec2:test` passing in #7372. Appreciate any early comments.
