### ISSUE TITLE
[Concurrent Segment Search] Dynamically enable/disable concurrent search

### ISSUE THREAD

**Issue by sohami** [opensearch-project/OpenSearch#7356]
Provide a mechanism to dynamically toggle between concurrent and sequential search. This can be a cluster settings in phase 1 and later can be evaluated if it makes sense to have it at index level. It will be useful to have this during initial phase where users can evaluate if concurrent search mechanism is something which helps their use case or not. For more context https://github.com/opensearch-project/OpenSearch/issues/6798

**Comment by jed326** [comment]
@anasalkouz I can start taking a look at this one, could you assign this to me?

**Comment by kotwanikunal** [comment]
> @anasalkouz I can start taking a look at this one, could you assign this to me?

Assigned it to you @jed326

**Comment by jed326** [comment]
At first glance 2 problems stand out.
1. What should the behavior of the setting be when the feature flag is disabled? There is probably some precedence set by however segrep or other feature flags handle this so will look into that.
2. This will probably need to work with #7353 as well but we can look into that once #7514 is merged.
