### ISSUE TITLE
Adjust the range and default value for deletes_pct_allowed in merge policy for more control and optimal disk usage

### ISSUE THREAD

**Issue by nkumar04** [opensearch-project/OpenSearch#7360]
**Is your feature request related to a problem? Please describe.**
The default merge policy setting for deletes_pct_allowed controls the maximum percentage of deleted documents that can be tolerated in the index. Default value for this setting is 33% and it can be configured to any value between 20% to 50%

Lucene 9.5 has expanded the limits for TieredMergePolicy#deletesPctAllowed and has also updated the default value for the allowed percentage of deleted documents to 20% for an index. Please see [this](https://github.com/apache/lucene/pull/11831)  

[Experiments](https://github.com/apache/lucene/issues/11761#issuecomment-1251264246) done in the Lucene community shows that the write amplification increase is very small when the value for deletes_pct_allowed changed from 33%  to 20%.

**Describe the solution you'd like**
Aligning the defaults for this setting with Lucene can help optimize the disk usage. For users operating at scale, the default value 33% can translate into terabytes of wasted disk space occupied by deleted docs in an index. Also, indexes with fewer deleted docs would gain in search performance.

We are running some benchmarks to see the overhead on CPU and IO when policy setting for deletes_pct_allowed is set at 20%.

cc: @shwetathareja @mgodwan @itiyamas @vikasvb90 @dhwanilpatel

**Comment by shwetathareja** [comment]
Thanks @nkumar04 . Waiting for the nos. from your benchmark exercise.

**Comment by vikasvb90** [comment]
+1 to the comment by @shwetathareja

**Comment by nkumar04** [comment]
Findings from benchmark runs:

**RUN 1**
Test config:
- Single node domain
- Instance type: EC2 m5.4xlarge
- Updates: 50% of the total request
- Baseline:
    - OS_2.3
    - "index.merge.policy.deletes_pct_allowed" : "33.0"
- Target:
   - OS_2.3
   - "index.merge.policy.deletes_pct_allowed" : "20.0"

```
| Metrics | Baseline | Target |
------------------------------------
| Store size | 39gb | 37gb |
| Deleted docs percent | 22% | 18% |
| Avg. CPU | (42 - 53)% | (43 - 55)% |
| Write throughput | 11 - 15 mbps | 11 - 17 mbps |
| P90 search latency | 14.9 ms | 13.2 ms |
| P90 term query latency | 13.7 ms | 13.5 ms |
```

**RUN 2**
Test config:
- Single node domain
- Instance type: EC2 m5.4xlarge
- Updates: 75% of the total request
- Baseline:
    - OS_2.3
    - "index.merge.policy.deletes_pct_allowed" : "33.0"
- Target:
   - OS_2.3
   - "index.merge.policy.deletes_pct_allowed" : "20.0"

```
| Metrics | Baseline | Target |
------------------------------------
| Store size | 19.4gb | 17.7gb |
| Deleted docs percent | 22.8% | 15% |
| Avg. CPU | (43 - 53)% | (46 - 53)% |
| Write throughput | 9 - 14.5 mbps | 10 - 15.9 mbps |
| P90 search latency | 15.9 ms | 13.5 ms |
| P90 term query latency | 15.7 ms | 13.9 ms |
```


**RUN 3**
Test config:
- Single node domain
- Instance type: EC2 m5.4xlarge
- Updates: 80% of the total request
- Baseline:
    - OS_2.3
    - "index.merge.policy.deletes_pct_allowed" : "33.0"
- Target:
   - OS_2.3
   - "index.merge.policy.deletes_pct_allowed" : "20.0"

```
| Metrics | Baseline | Target |
------------------------------------
| Store size | 15.9gb | 14.6gb |
| Deleted docs percent | 24% | 18% |
| Avg. CPU | (46 - 52)% | (47 - 52)% |
| Write throughput | 9 - 13 mbps | 10 - 15 mbps |
| P90 search latency | 15.3 ms | 13.6 ms |
| P90 term query latency | 15.2 ms | 13.4 ms |
```

**Comment by nkumar04** [comment]
Tagging @dblock @reta @mch2 @andrross @shwetathareja @mgodwan @itiyamas  for feedback. Pls do tag others who can review this.

**Comment by reta** [comment]
@nkumar04 thank you for the comprehensive proposal, I think it makes sense to align with Apache Lucene, plus from the benchmarking you've done there are no noticeable regressions, rather improvements on certain metrics.

**Comment by mgodwan** [comment]
Thanks for the comprehensive benchmarks @nkumar04
This is a good improvement with sufficient evidence in Lucene towards improvement of overall performance, and makes sense to apply the same for OpenSearch. 

Do we know how the overall indexing latencies/throughput trend in these runs and if we see any improvement there for update operations?

**Comment by shwetathareja** [comment]
Thanks @nkumar04 for running the benchmarks. There are definitely improvements specially for update heavy workload in terms of both search latencies and write throughput.

> Do we plan to backport this as well?

This should be backported to 2.x branch.

**Comment by nkumar04** [comment]
Thanks @reta @mgodwan @shwetathareja for feedback. 
@mgodwan, indexing latency numbers are almost same in both cases, i have updated the benchmark result table with the same.

**Comment by nkumar04** [comment]
> benchmark result table with the same.
> 
> > 3. Do we plan to backport this as well?
> 
> yes
