### ISSUE TITLE
Upgrade aws sdk from v1 to v2 in repository-s3 plugin

### ISSUE THREAD

**Issue by vikasvb90** [opensearch-project/OpenSearch#7391]
This is an enhancement to upgrade AWS SDK from v1 to v2. This will be the first step in upgrading to v2 which will responsible solely to migrate existing v1 APIs to v2 sync APIs. Future iterations (outside of the scope of this feature) will involve exposing async counterparts of existing plugin APIs which will be based on non-blocking IO.

**Comment by raghuvanshraj** [comment]
Taking this up

**Comment by dblock** [comment]
Closing as a dup of https://github.com/opensearch-project/OpenSearch/issues/7312, doing it in a combination in https://github.com/opensearch-project/OpenSearch/pull/7372.
