### ISSUE TITLE
[Segment Replication] Update components of segrep backpressure to support remote store.

### ISSUE THREAD

**Issue by mch2** [opensearch-project/OpenSearch#7410]
Currently, Segment Replication pressure is enforced using a count of checkpoints and time a replica is behind its primary.  This data is kept in the primary's ReplicationTracker, given that writes are rejected at the primary, and updated from SegmentReplicationSource service when a primary has finished sending segments for a particular checkpoint to a replica.

With remote storage as the source of replication, this will have to change to return necessary data the no-op write path or perform an async poll of replica state so primaries can perform its bookkeeping.

**Comment by ankitkala** [comment]
I'll pick it up.
