### ISSUE TITLE
Implement prototype remote store directory/index input for search

### ISSUE THREAD

**Issue by yigithub** [opensearch-project/OpenSearch#7431]

**Comment by neetikasinghal** [comment]
Searchable snapshots implemented a [RemoteSnapshotDirectory](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/index/store/remote/directory/RemoteSnapshotDirectory.java) that provides access to files that are physically represented as a snapshot in a repository (the specific repository implementation is provided via a storage plugin). This task is to create a similar remote search-focused Directory implementation for searching remote-backed indexes stored in a repository. The bulk of the logic for the Lucene abstraction that implements the on-demand fetching and file caching is implemented in the class [OnDemandBlockIndexInput](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/index/store/remote/file/OnDemandBlockIndexInput.java) and will be reused here.

The remote-backed storage feature has implemented classes like [RemoteSegmentStoreDirectory](https://github.com/opensearch-project/OpenSearch/blob/31434a37f366f20afafb3aeba204908a586f1761/server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectory.java#L49) and [RemoteIndexInput](https://github.com/opensearch-project/OpenSearch/blob/31434a37f366f20afafb3aeba204908a586f1761/server/src/main/java/org/opensearch/index/store/RemoteIndexInput.java). There is some overlap as these classes must also understand the remote segment structure and metadata. Part of this prototype is to figure out how the pieces fit together, but particularly at the IndexInput level there will be distinct implementations as the remote search piece is built around on-demand partial file fetching, whereas the pieces used in the write path are designed to copy entire files to/and from the remote object store.

**Comment by neetikasinghal** [comment]
High-level Design

In the case of Searchable Snapshots, FileInfo class (part of BlobStoreIndexShardSnapshot class) contains the metadata for each segment/data file like file name, part size etc. The FileInfo object is used to make an object of BlobFetchRequest that is helpful in fetching/downloading the blocks of data from the remote store during the read path. 
In case of Remote Search, we can leverage the UploadedSegmentMetadata class and use it to form the object of BlobFetchRequest similar to Searchable Snapshots.

In current flow of remote store upload, there is a listener registered for each refresh, that takes care of uploading/updating the metadata of each shard to the remote store.  Current metadata is stored under a RemoteDirectory:

* Location - <IndexUUID>/<Shard ID>/segments/metadata/
* File Name - metadata__<Primary Term>__<Commit Generation>__<UUID>
* Content in the file for every segment file uploaded at each commit:  <OriginalSegmentFilename>::<UploadedSegmentFilename>::<Checksum> 
* Length of the file name

Create a new Directory - RemoteSearchDirectory and new IndexInput inheritor of OnDemandBlockIndexInput - OnDemandBlockSearchIndexInput

* Location(same location as the remote store metadata) - <IndexUUID>/<Shard ID>/segments/metadata/
* File Name(same file as the remote store metadata) - metadata__<Primary Term>__<Commit Generation>__<UUID>
* Content in the file for every segment file uploaded at each commit: UploadedSegmentMetadata objects


Initialization of the directory
The initialization of the Search based directory can be done at RemoteSearchDirectoryFactory , similar to the initialization of RemoteDirectory.

Upload/Update/Delete of metadata to the directory
Upload of metadata happens after every commit, update can happen after each refresh, at remote store.
The stale commit commit metadata files are deleted.

Content of metadata file
This contains UploadedSegmentMetadata of each of the segment file uploaded

Read/Loading the metadata file in the directory
OnDemandBlockSearchIndexInput class will be created to read the files in the directory newly created.
We can abstract out the class OnDemandBlockSnapshotIndexInput  as the new class to be created has a lot of functions that can be reused here.

**Comment by neetikasinghal** [comment]
Draft PR: https://github.com/opensearch-project/OpenSearch/pull/7417
