### ISSUE TITLE
[BUG] Flaky search.aggregation/230_composite_unsigned tests due to nested aggregations order

### ISSUE THREAD

**Issue by reta** [opensearch-project/OpenSearch#7507]
**Describe the bug**
Flaky search.aggregation/230_composite_unsigned tests due to nested aggregations order

**To Reproduce**
https://build.ci.opensearch.org/job/gradle-check/15189/testReport
https://build.ci.opensearch.org/job/gradle-check/15140/testReport

**Expected behavior**
Test must always pass

**Plugins**
Standard

**Screenshots**

**Host/Environment (please complete the following information):**
 - CI

**Additional context**
Reproducible locally with a seed

**Comment by kotwanikunal** [comment]
Resolved by #7548
