### ISSUE TITLE
[META][Distributed Tracing] - 2.12

### ISSUE THREAD

**Issue by Gaganjuneja** [opensearch-project/OpenSearch#7542]
Feature Request - 
#1061 

Distributed Tracing RFCs 
Overall feature includes both Tracing Framework and Collector #6750 
Tracing collector #7352 

Prototype Tracing framework
#7026 

Tracing framework tasks 

- [x] #7543 
- [x] #7544 
- [x] #7545  
- [x] #8426 
- [x] #8427
- [x] #8428
- [x] #8430
- [x] #8561
- [x] #8620 
- [x] #9197
- [x] #9449
- [x] #10121
- [x] #10293

**Comment by Naarcha-AWS** [comment]
@nandi-github: can we add this to the [Unified Backlog Tracker(https://github.com/orgs/opensearch-project/projects/96)

**Comment by nandi-github** [comment]
> @nandi-github: can we add this to the [Unified Backlog Tracker(https://github.com/orgs/opensearch-project/projects/96)

Sure, please go ahead and add it.

**Comment by DarshitChanpura** [comment]
@Gaganjuneja I've re-marked this to 2.11. If that is not the case, please label otherwise.

**Comment by getsaurabh02** [comment]
Hi @Gaganjuneja Since this is a long running item, can we break this into sub issue/tasks (milestones) and tag each of the sub-issues to releases such as 2.12, 2.13 etc. This single issue can continue to remain as META for this feature.

**Comment by Gaganjuneja** [comment]
@getsaurabh02 I will update by EOD. Thanks!

**Comment by andrross** [comment]
2.12 has been released and all linked issues are completed. Closing.
