### ISSUE TITLE
[Tracing Framework]Strict check Span Processor implementation

### ISSUE THREAD

**Issue by Gaganjuneja** [opensearch-project/OpenSearch#7545]
**Is your feature request related to a problem? Please describe.**
Strict check Span Processor implementation to catch the instances where span are not closed properly.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by dblock** [comment]
@Gaganjuneja would you mind please editing the issue and replacing "A clear and concise desc ..." with the actual description :)
