### ISSUE TITLE
Enabling Compression Level configuration of ZSTD and ZSTD (No Dict)

### ISSUE THREAD

**Issue by sarthakaggarwal97** [opensearch-project/OpenSearch#7555]
**Is your feature request related to a problem? Please describe.**
In the present implementation, zstd and zstd_no_dict uses default compression level i.e. 6 as mentioned [here](https://github.com/opensearch-project/OpenSearch/blob/main/sandbox/plugins/custom-codecs/src/main/java/org/opensearch/index/codec/customcodecs/ZstdNoDictCompressionMode.java#LL26C30-L26C55), [here](https://github.com/opensearch-project/OpenSearch/blob/main/sandbox/plugins/custom-codecs/src/main/java/org/opensearch/index/codec/customcodecs/ZstdCompressionMode.java#L31) and [here](https://github.com/opensearch-project/OpenSearch/blob/main/sandbox/plugins/custom-codecs/src/main/java/org/opensearch/index/codec/customcodecs/Lucene95CustomCodec.java#L18). According to [documentation](http://facebook.github.io/zstd/zstd_manual.html#Chapter1), these algorithms can support the compression level range of 1-22. Theoretically, configurable compression levels can help customers tune the tradeoff between storage and throughput according to their requirements.

**Describe the solution you'd like**
An introduction of configurable compression level as an index setting for zstd and zstd-no-dict

**Additional context**
https://github.com/opensearch-project/OpenSearch/issues/3354

cc: @mgodwan @backslasht @shwetathareja

**Comment by shwetathareja** [comment]
@sarthakaggarwal97 OpenSearch users can use some of the existing benchmarks for their reference when choosing the compression level. It would be great if you can share some of the benchmark runs as well across different levels.

**Comment by dblock** [comment]
We've been collaborating with the Intel team and benchmarking compression levels in additional real world scenarios with @backslasht. Stay tuned @shwetathareja!

**Comment by mgodwan** [comment]
Thanks for sharing these numbers.
Given level 3 is the default level used in zstd implementation as well and yields better results in terms of throughput in majority of the cases, it should be alright to proceed with the same.

Is there any comparison of storage used as well across these to get insights around the trade-off?

**Comment by sarthakaggarwal97** [comment]
> Thanks for sharing these numbers. Given level 3 is the default level used in zstd implementation as well and yields better results in terms of throughput in majority of the cases, it should be alright to proceed with the same.
> 
> Is there any comparison of storage used as well across these to get insights around the trade-off?

@mgodwan Adding comparison for store size along with indexing throughput. We roughly see 4% increase in the store size with level 3 having level 6 as baseline.

**NYC Taxis**

<img width="367" alt="image" src="https://github.com/opensearch-project/OpenSearch/assets/25262500/cf5b1371-b395-4c1e-81a4-6d7d4d2cf7d9">


---


**HTTP Logs**

<img width="373" alt="image" src="https://github.com/opensearch-project/OpenSearch/assets/25262500/afb8bf44-630b-40be-a3b2-51a7c853640e">

**Comment by backslasht** [comment]
Thanks @sarthakaggarwal97. This seems like a safe bet as the increase in indexing throughput and storage size are proportional. 

Have we run tests for sufficiently large time? wondering if it will also increase the background merge time as the segments might be large with compression level 3?

**Comment by sarthakaggarwal97** [comment]
@backslasht yes, I observed background merges were happening for the runs. The segments with level 3 should not be large enough to start affecting background merge time when compared to level 6. Level 3 looks like a good sweet spot.
I will raise the PR to change the default compression level to 3.

**Comment by dblock** [comment]
Can this be closed with https://github.com/opensearch-project/OpenSearch/pull/8471?

**Comment by backslasht** [comment]
@dblock - I think this will require #8312 to be closed.
