### ISSUE TITLE
Add opensearch.internal to ADDITIONAL_TAGS in IntelliJ IDEA Project Defaults

### ISSUE THREAD

**Issue by msfroh** [opensearch-project/OpenSearch#7575]
**Is your feature request related to a problem? Please describe.**
Whenever I'm adding new classes to OpenSearch that are not part of the public API, I add the `@opensearch.internal` tag to the class Javadoc. IntelliJ complains (with a warning) that the tag is invalid. Since I usually like to write code with no IDE warnings, this is distracting.

There is a file in source control (https://github.com/opensearch-project/OpenSearch/blob/main/.idea/inspectionProfiles/Project_Default.xml) that adds `opensearch.experimental` to the list of valid Javadoc tags, so that one doesn't generate warnings.

**Describe the solution you'd like**

I think we should add `opensearch.internal` (and `opensearch.api`) to https://github.com/opensearch-project/OpenSearch/blob/main/.idea/inspectionProfiles/Project_Default.xml so we stop getting warnings.

Arguments in favor of fixing it include: 
1. it's easier to catch typos in the Javadoc tag (since people could also end up ignoring a warning about `opensearch.intrenal` or something) and 
2. it lowers the barrier to submitting "warning-free" code, since it removes a false positive.

**Describe alternatives you've considered**
This is very mildly annoying. Up to now, I've just been ignoring those extra warnings. I can continue ignoring them. 

I can also click the "Add `@opensearch.internal` to custom tags" link in the warning (as shown in the screenshot below), but that will modify the Project_Default.xml file in my repo, which I need to either exclude from my commits or end up pushing it along with whatever changes I'm looking to submit (which would fix this issue, but I think this issue should be fixed intentionally, not as a side effect).

**Additional context**
![Screen Shot 2023-05-15 at 3 12 51 PM](https://github.com/opensearch-project/OpenSearch/assets/346194/59a89744-a43b-49dd-bbee-7eb161eece62)

**Comment by andrross** [comment]
@msfroh I think this is a good idea. We should add `@opensearch.api` as well, right?

**Comment by msfroh** [comment]
> We should add @opensearch.api as well, right?

Definitely. I'll add that to the issue description too.
