### ISSUE TITLE
Invalid HTTP method for PATCH _plugins/_security/api/rolesmapping

### ISSUE THREAD

**Issue by fdx0** [opensearch-project/OpenSearch#7614]
**Describe the bug**
When attempting to use the `PATCH _plugins/_security/api/rolesmapping` endpoint, it returns an error stating that the PATCH method used is invalid. 

According to the documentation, I should be able to use PATCH
https://opensearch.org/docs/latest/security/access-control/api/#patch-role-mappings

**To Reproduce**
1. Go to 'Dev Tools'
2. Try to execute the following on an existing role (replace the name of the role for your test)
```
PATCH _plugins/_security/api/rolesmapping
[
  {
    "op": "add", "path": "/test-role", "value": { "users": ["testing"] }
  }
]
```

**Expected behavior**
The PATCH method should be accepted. 

**Plugins**
N/A

**Screenshots**

![dev_tools_opensearch_rolesmapping_failure](https://github.com/opensearch-project/OpenSearch/assets/81383811/2cb03088-5cab-41ed-a27f-bad45f221cf0)
![dev_tools_opensearch_rolesmapping_invalid_method](https://github.com/opensearch-project/OpenSearch/assets/81383811/17be5c2a-339a-4aa8-8029-1e188efc99a9)

**Host/Environment (please complete the following information):**
 - OS: AWS Opensearch Service
 - Version OpenSearch_2_3_R20221114-P4

**Comment by kotwanikunal** [comment]
Seems to be a duplicate of https://github.com/opensearch-project/OpenSearch-Dashboards/issues/2343
@fdx0 Please follow the above issue for any updates or requests.
