### ISSUE TITLE
[BUG]Debug log configuration issue

### ISSUE THREAD

**Issue by suwei999** [opensearch-project/OpenSearch#7622]
We can configure the debug logs for reindex in the official way：

```
PUT /_cluster/settings
{
  "persistent" : {
    "logger.org.opensearch.index.reindex" : "DEBUG"
  }
}
```

But if it is a module or method that does not exist (such as logger. org. opensearch. index. aabbc) that can also be successfully configured, generally speaking, should not configuring debug for methods that do not exist be a failure

```
PUT /_cluster/settings
{
  "persistent" : {
    "logger.org.opensearch.index.aabbc" : "DEBUG"
  }
}
```

**Comment by dblock** [comment]
Sounds like a reasonable suggestion.
