### ISSUE TITLE
Use semver to decide whether a plugin can start or not

### ISSUE THREAD

**Issue by dblock** [opensearch-project/OpenSearch#763]
**Is your feature request related to a problem? Please describe.**

Currently, all versions between OpenSearch and plugins must match exactly for OpenSearch + plugin to start. Otherwise you get an error (TODO: details of the error). 

To work around this problem what we're doing is that we are pre-labelling everything the same version number, e.g. `1.0.0-rc1`, build everything with that version, then everything works together. Then we find bugs and do it again, so we end up with multiple artifacts called `1.0.0-rc1`. What should happen is that every build produces a new artifact, with a build number e.g. `1.0.0.45` and we don't need to label anything `rc1` or `beta1` (that just wastes time for everyone having to constantly update their build scripts), then we can assemble the artifacts that make up an `rc1` together, e.g. security 1.0.0.45, alerting 1.0.0.42, etc.  

**Describe the solution you'd like**

Fix https://github.com/opensearch-project/OpenSearch/issues/622 and use semver to decide whether the plugin is compatible with OpenSearch. Currently that would be that major and minor versions must match, but not a build number or a qualifier.

**Comment by dblock** [comment]
@nknize would like your comments

**Comment by dblock** [comment]
@mch2 want to take this assuming Nick agrees with what I'm proposing here?

**Comment by camerski** [comment]
I think we can do even better here: Split the plugin API into its own version namespace and use that to determine compatibility.

That gives us the ability to define Plugin API 1.0, and implement it in OpenSearch 1.x, 2.x, 3.x etc. Plugins can code against API 1.0 (or 2.0) and not have to care whether they are running in OpenSearch 1.x, 2.x, or 3.x - all they care about is whether this instance of OpenSearch supports the right Plugin API version.

Being able to evolve the plugin API independently of the implementation gives us a lot of flexibility.

Incidentally, I think we should do the same thing for the REST API as well.

**Comment by dblock** [comment]
@camerski suggestions are good, but I would first fix the problem we have to fix for 1.0, then redesign the compatibility matrix in some future

**Comment by camerski** [comment]
Yeah, makes sense. Can we relax the strict minor version requirement, though? It seems reasonable for plugin-1.3 to work with opensearch-1.0, or for plugin 1.0 to work with opensearch 1.5.

**Comment by tlfeng** [comment]
I'm a little confused how the problem in #622 occurs. Looks like currently the required OpenSearch version of a plugin is always consist of 3 numbers without the version qualifier (alpha, beta, rc ...)
The required version is stated in property "opensearch.version" in `plugin-descriptor.properties`, like below:
<img width="489" alt="image" src="https://user-images.githubusercontent.com/78394866/119400774-7f7a5180-bc8f-11eb-8dde-68b1fba22bfd.png">

It can be seen from the code, the version used there has 3 components:
https://github.com/opensearch-project/OpenSearch/blob/9c95cf424b405693196deb98f526b5a05916b905/buildSrc/src/main/groovy/org/opensearch/gradle/plugin/PluginBuildPlugin.groovy#L105

https://github.com/opensearch-project/OpenSearch/blob/9c95cf424b405693196deb98f526b5a05916b905/buildSrc/src/main/java/org/opensearch/gradle/Version.java#L104

**Comment by dblock** [comment]
I was seeing this at some point before beta1, it may have already been fixed, someone needs to double-confirm.

**Comment by tlfeng** [comment]
> I was seeing this at some point before beta1 and only with -SNAPSHOT and other qualifiers, it may have already been fixed, someone needs to double-confirm.

Seems there is no related changes after that. Looks like the required OpenSearch version is set without the build qualifier.
Meanwhile I think @camerski's idea can relax the developers a lot. 😄

**Comment by dblock** [comment]
I think the issue I remembered doesn't exist anymore. I installed beta1 and loaded an rc1 job-scheduler and it worked. I'll close this for now.

**Comment by dblock** [comment]
@camerski will you please open a new issue describing what you're suggesting?
