### ISSUE TITLE
[Enhancement] Make Distribution Downloader download from Snapshots instead of Releases and add `min` keywords

### ISSUE THREAD

**Issue by peterzhuamazon** [opensearch-project/OpenSearch#769]
**Describe the enhancement**

1. The current distribution downloader is using the RELEASES channel for downloading artifacts
https://github.com/opensearch-project/OpenSearch/blob/0e9f74e35f1255cb9ec45be3d8960aad195a9f6e/buildSrc/src/main/java/org/opensearch/gradle/DistributionDownloadPlugin.java#L159

This was due to an earlier decision that distribution downloader requires a static link, and cannot consume artifacts with dynamic build number.

The new approach is to have a snapshot artifact labeled as `latest` to avoid promoting to RELEASE channel.

2. Also, due to the plan to support core artifacts without plugins, we added `min` keyword in the core tarball naming convention, which also needs to be addressed in DistributionDownloader code.
https://github.com/opensearch-project/opensearch-build/issues/31

**Expected behavior**
The new link should point to 
```
/snapshots/core/opensearch/[revision]/[module]-min-[revision]-SNAPSHOT(-[classifier])-latest.[ext]
``` 
which results in something similar to:
```
opensearch-min-1.0.0-rc1-SNAPSHOT-linux-x64-latest.tar.gz
```

**Additional context**

**Comment by peterzhuamazon** [comment]
Have a quick conversation with @saratvemulapalli and we have some thoughts on this.

1. Instead of hardcoding it to snapshots, we can start fixing the actual snapshots ivyrepo setup here: https://github.com/opensearch-project/OpenSearch/blob/0e9f74e35f1255cb9ec45be3d8960aad195a9f6e/buildSrc/src/main/java/org/opensearch/gradle/DistributionDownloadPlugin.java#L172
2. We will have these two urls fixed for snapshots vs releases:
```
Snapshots: https://artifacts.opensearch.org/snapshots/core/opensearch/[revision]/[module]-min-[revision]-SNAPSHOT(-[classifier])-latest.[ext]

Releases: Snapshots: https://artifacts.opensearch.org/snapshots/core/opensearch/[revision]/[module]-min-[revision](-[classifier]).[ext]

```
This is based on the fact that snapshots is a moving target and releases is not.
You can expect snapshots changing on a daily basis but releases might change every release as stable builds.

3. We also expect to have snapshots and releases built from fresh

**Comment by saratvemulapalli** [comment]
Parent issue: https://github.com/opensearch-project/OpenSearch/issues/91

**Comment by mch2** [comment]
I put up a draft #904 of an idea on how to solve this issue.

This change will register the existing snapshot repo, so builds/integ tests executed with -Dopensearch.version with -SNAPSHOT will fetch from that repo.

It also adds a new release-candidate repo that exists as a fallback if a version is not in releases.  So for our current situation where we require a 1.0.0 bundle that is not a snapshot build yet has not yet been released, it can fetch from this staging repo and test against it.

@peterzhuamazon @camerski @saratvemulapalli thoughts?

**Comment by camerski** [comment]
Looks reasonable to me.

**Comment by saratvemulapalli** [comment]
Looks good to me.
