### ISSUE TITLE
[BUG] Artifacts are not correctly pulled by integ test distribution 

### ISSUE THREAD

**Issue by martin-gaievski** [opensearch-project/OpenSearch#7714]
**Describe the bug**
Integration tests that are using gradle command testClusters.integTest are failing in CI with exception

```
»  java.lang.NoClassDefFoundError: org/opensearch/core/common/Strings
»  	at org.opensearch.knn.index.query.KNNQueryBuilder.<init>(KNNQueryBuilder.java:68)
```

That is after PR that addresses this issue has been merged (https://github.com/opensearch-project/k-NN/pull/904). Here is code ref to import in the class mentioned in exception https://github.com/opensearch-project/k-NN/blob/main/src/main/java/org/opensearch/knn/index/query/KNNQueryBuilder.java#L9. 

Here is gradle script that runs cluster that failing: 
https://github.com/opensearch-project/k-NN/blob/main/build.gradle#L256 

**To Reproduce**
Run CI action "[Build and Test k-NN]" in plugin CI https://github.com/opensearch-project/k-NN/actions

Example of failed run: https://github.com/opensearch-project/k-NN/actions/runs/5026347104/jobs/9014512813?pr=904

It's reproducible in plugin locally, get latest k-NN from https://github.com/opensearch-project/k-NN, clean gradle and maven caches and run ```./gradlew integTest```

**Plugins**
Same behavior for knn and [neural-search](https://github.com/opensearch-project/neural-search) plugins

**Additional context**
Team has addressed issues related to refactoring in core under PR https://github.com/opensearch-project/OpenSearch/pull/7508

Initial assumption was that change is not yet propagated to all repositories, however it's highly unlikely as original PR has been merged on 5/18.

**Comment by dblock** [comment]
Is this because the snapshot build hasn't been published, or something like that?

**Comment by martin-gaievski** [comment]
Rechecked today, it's working now. I'm not sure what happened, it's ok to close this now.
