### ISSUE TITLE
[BUG] Flaky test :qa:mixed-cluster:v2.8.0#mixedClusterTest

### ISSUE THREAD

**Issue by raghuvanshraj** [opensearch-project/OpenSearch#7755]
**Describe the bug**
The YAML REST test `MixedClusterClientYamlTestSuiteIT` is failing intermittently with the following error:
```
java.lang.AssertionError: Failure at [tasks.list/10_basic:15]: field [nodes.$node_id.roles] doesn't have a true value
Expected: not null
     but: was null
```

**To Reproduce**
Build Failure: https://build.ci.opensearch.org/job/gradle-check/16265/testReport/org.opensearch.backwards/MixedClusterClientYamlTestSuiteIT/test__p0_tasks_list_10_basic_tasks_list_test_/

**Expected behavior**
Test should pass

**Comment by sandeshkr419** [comment]
Duplicate: https://github.com/opensearch-project/OpenSearch/issues/14294
