### ISSUE TITLE
Blocking snapshot of given index patterns

### ISSUE THREAD

**Issue by heemin32** [opensearch-project/OpenSearch#7778]
**Is your feature request related to a problem? Please describe.**
We are implementing a plugin which store proprietary data in OpenSearch indices of which cannot be stored longer than certain period, like 30 days. Therefore, we want to prevent creating snapshot of those indices.

**Describe the solution you'd like**
Provide a way to exclude index from being taken as snapshot through either by index setting or by plugin specifying index pattern.

**Describe alternatives you've considered**
Storing the data as a file in disk.

**Additional context**
https://github.com/opensearch-project/OpenSearch/issues/5856

**Comment by heemin32** [comment]
There are two options in implementations.
1. Add new index setting `index.snapshot_eligible`. Default is true. When the value is false, it is excluded when we resolve index name for snapshotting. https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/cluster/metadata/IndexNameExpressionResolver.java#L316
2. Add new field in SystemIndexDescriptor to determine if the index is snapshot eligible or not. In SnapshotService, exclude an index if the index is not eligible for snapshot. https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/plugins/SystemIndexPlugin.java#L55

First option give more flexibility as it allows any index to be excluded from snapshotting through index setting. Second option provide more strict policy where user cannot unblock the snapshot eligibility of an index once it is defined by plugins.

**Comment by kotwanikunal** [comment]
@heemin32 Trying to understand a bit more about the requirements. 

I think this already exists as a part of the [API currently](https://opensearch.org/docs/2.7/tuning-your-cluster/availability-and-recovery/snapshots/snapshot-restore/#take-snapshots) - 

```
indices | The indices you want to include in the snapshot. You can use , to create a list of indices, * to specify an index pattern, and - to exclude certain indices. Don’t put spaces between items. Default is all indices.
-- | --
```


Do you want to add a feature to mark an index/index pattern as not capable for backup?

**Comment by heemin32** [comment]
Current API is for user to exclude certain index pattern from being taken in snapshot. I want a way to exclude index pattern from being taken as snapshot by system.

**Comment by andrross** [comment]
One of the purposes of a snapshot is to be able to capture the state at a point in time such that a cluster can be restored to that state. Omitting a system index seems like it will violate that property.

**Comment by heemin32** [comment]
> One of the purposes of a snapshot is to be able to capture the state at a point in time such that a cluster can be restored to that state. Omitting a system index seems like it will violate that property.

In this case, we have two system index: one is to store metadata and another to store proprietary data and we are only blocking a snapshot of proprietary data. When the metadata index is restored, we will restore the proprietary data on the fly. Meanwhile a user might fail to use the data; in this case, ip2geo processor to convert ip to location data.

Due to a license issue, even if we store the snapshot of proprietary data, it won't be much usable once it gets older than 30 days when it is restored. User will see failure in such case anyway.

**Comment by muralikpbhat** [comment]
>When the metadata index is restored, we will restore the proprietary data on the fly

From where? You mean re-index from source?

Seems like your requirement should be 'delete from snapshots' rather than 'not take snapshot'? If the 'proprietary data' gets deleted in the cluster, isn't it better to delete the snapshots older than X days? By not taking snapshot at all, you will not be able restore data in case of failures within 30 days as well.

**Comment by heemin32** [comment]
> > When the metadata index is restored, we will restore the proprietary data on the fly
> 
> From where? You mean re-index from source?
> 
> Seems like your requirement should be 'delete from snapshots' rather than 'not take snapshot'? If the 'proprietary data' gets deleted in the cluster, isn't it better to delete the snapshots older than X days? By not taking snapshot at all, you will not be able restore data in case of failures within 30 days as well.

metadata index has information about where to download and generate the proprietary data. The proprietary data is downloaded from external endpoint outside of OpenSearch cluster.
If metadata index is restored, we will scan the metadata index and restore the proprietary data by downloading it from external endpoint. Such way, regardless whether the data is older than 30 days or not, it will get restored after few minutes.

Yes. Deleting snapshots older than 30 days could be more accurate requirement but I think blocking snapshot make the problem much more simpler with small drawback; restoring time.

**Comment by backslasht** [comment]
If I understand the use case correctly, you don't want to take the snapshot of those indices as the actual source of the data exists elsewhere and you prefer to restore the data from actual source instead of restoring it from snapshot.

In that case, I would suggest to add it as an index setting and make SnapshotsService ignore them (based on the setting value).

Also, how are you planning to restore the data during restore of metadata index?

**Comment by heemin32** [comment]
> If I understand the use case correctly, you don't want to take the snapshot of those indices as the actual source of the data exists elsewhere and you prefer to restore the data from actual source instead of restoring it from snapshot.
> 
> In that case, I would suggest to add it as an index setting and make SnapshotsService ignore them (based on the setting value).
> 
> Also, how are you planning to restore the data during restore of metadata index?

Correct. Actual source of the data exists elsewhere. For restoring, plugin will register itself to cluster state change event listener and act on metadata index restoring event. It will trigger background task of downloading proprietary data from the external endpoint and creating index again.

**Comment by backslasht** [comment]
Got it. The proposal looks clean to me.

**Comment by Bukhtawar** [comment]
I would still prefer the option of snapshotting and retaining it for 30 days since thats what snapshots are for. They help protect data from accidental deletion, modification and infrastructure failures. If you want to restore data from a different source that should still be possible with restore API that restores only indices with certain patterns.

**Comment by heemin32** [comment]
> I would still prefer the option of snapshotting and retaining it for 30 days since thats what snapshots are for. They help protect data from accidental deletion, modification and infrastructure failures. If you want to restore data from a different source that should still be possible with restore API that restores only indices with certain patterns.

There are two indices: metadata index, temp data index. We take snapshot of only metadata index but not temp data index. Once metadata index is restored from snapshot, the temp data will be restored from an external endpoint. Temp data index has no use without metadata index.

**Comment by heemin32** [comment]
Blocking restoring of snapshot could be another option.

**Comment by heemin32** [comment]
There are other case where this requirement is required. For example, job-scheduler create lock index when scheduled job try to acquire lock. It maintains job index separate from lock index. If job index is restored first and job is triggered before lock index is restored, it will create a new lock index. Then, lock index restoration will fail due to conflict index name.

**Comment by andrross** [comment]
What happens if I'm using this feature that requires proprietary data and I turn my cluster off for 31 days then turn it back on? How would that situation be different from restoring a 31 day old snapshot?

> Blocking certain index from restoring of snapshot could be another option.

Is the requirement that you can't use data that is older than 30 days? If so, then it seems like application logic to detect and delete invalid/expired data is maybe what you need and would be a more general solution to the problem.

**Comment by heemin32** [comment]
> What happens if I'm using this feature that requires proprietary data and I turn my cluster off for 31 days then turn it back on? How would that situation be different from restoring a 31 day old snapshot?
In my case, ingest processor use the data and if data is older than 31 days, it enrich document with error message. The data will be deleted in the next update interval. This situation is a little different with restoring from snapshot because 1. this is not general use case, 2. Every indices are there before cluster start whereas, index restoration restore index one by one which can cause race condition between restoring process and data generation process.

> Is the requirement that you can't use data that is older than 30 days? If so, then it seems like application logic to detect and delete invalid/expired data is maybe what you need and would be a more general solution to the problem.
That detecting and invalidating data is already there which could be enough. This blocking creation or restoration of snapshot is an additional safeguard to reduce a future risk of license violation.

**Comment by andrross** [comment]
> This blocking creation or restoration of snapshot is an additional safeguard to reduce a future risk of license violation, and avoid race condition.

re: license violation - I think this logic has to be correct regardless of snapshot behavior. My silly example above is one way data older than 30 days can be present, but there are many others, such as starting a cluster from an old EBS snapshot or hand-rolling snapshotting functionality by making a copy of the OpenSearch data directory. In other words, if any part of your license compliance story relied on not being able to take snapshots, then there are likely other loopholes.

re: avoid race condition - I believe there are multiple cases today where system indices get automatically created. When restoring a full snapshot to a new cluster a user generally has to make a choice as to whether to exclude those indices in the restore process (and therefore discard whatever settings or state was stored in them) or to close the indices on the destination cluster and take the data from the snapshot. Its a fair point to ask whether this experience can be improved, but I'm wary of taking such a heavy-handed approach to _always_ exclude a particular index from snapshotting, especially given that the exclusion can already happen today at both snapshot creation and restore time using the existing API.

**Comment by andrross** [comment]
> I am thinking if we can block users from direct querying to certain indices

Direct access to system indices is [currently deprecated for removal in a future version](https://github.com/opensearch-project/OpenSearch/blob/1e08b5a075fa6018be6c0af959b2d638c2743d56/server/src/main/java/org/opensearch/cluster/metadata/IndexNameExpressionResolver.java#L367-L371). This deprecation was inherited at the time of the fork and I'm not aware of any work actively being done to implement the logic to block users' access to system indices in 3.0, but this is in line with the planned direction as far as I know.

**Comment by anasalkouz** [comment]
Hey @heemin32 , based on the discussion, seems this proposal isn't the right solution todo, I am closing this issue for now, please feel free to comment to re-open if needed.
