### ISSUE TITLE
Launch OpenSearch 1.0

### ISSUE THREAD

**Issue by CEHENKLE** [opensearch-project/OpenSearch#779]
OpenSearch is a community-driven, open source search and analytics suite derived from Apache 2.0 licensed Elasticsearch 7.10.2 & Kibana 7.10.2.  OpenSearch enables people to easily ingest, secure, search, aggregate, view, and analyze data. These capabilities are popular for use cases such as application search, log analytics, and more. With OpenSearch people benefit from having an open source product they can use, modify, extend, monetize, and resell how they want. At the same time, OpenSearch will continue to provide a secure, high-quality search and analytics suite with a rich roadmap of new and innovative functionality.

This issue is where the party is :)

**Comment by CEHENKLE** [comment]
![jeff goldblum](https://user-images.githubusercontent.com/77301321/125363553-aff07a80-e325-11eb-9e5a-ee324125360b.gif)

Gif Party :)

**Comment by ahopp** [comment]
![abouttime](https://media.giphy.com/media/AuwBPJztsEWkw/giphy.gif)

**Comment by dblock** [comment]
https://opensearch.org/blog/updates/2021/07/opensearch-general-availability-announcement/
