### ISSUE TITLE
[UPGRADE] Path for properties fetched via system.getProperty

### ISSUE THREAD

**Issue by dblock** [opensearch-project/OpenSearch#780]
**Is your feature request related to a problem? Please describe.**

We have renamed properties, e.g. `es.distribution.type` has become `opensearch.distribution.type`. What is the path forward for those settings?

**Describe the solution you'd like**

Document the way this breaks for users. 
Provide a migration path.
Optionally provide tooling to aid users in the migration path.

**Additional context**
Coming from #640.

**Comment by nknize** [comment]
#846 will close this issue. Bumping to v1.1 release
