### ISSUE TITLE
SegRep with Remote: Fail fast on segment mismatch between replica and remote store. 

### ISSUE THREAD

**Issue by ankitkala** [opensearch-project/OpenSearch#7803]
Current implementation of copying segment from remote store ignores the checksum mismatch for segments between replica and remote store. In case the checksum is different, we simply re-download the file. 
Keeping parity with existing segment replication behaviour, we need to exit exceptionally if there segments mismatch.

**Comment by mch2** [comment]
If https://github.com/opensearch-project/OpenSearch/issues/7802 is done this is not needed as a separate fix.

**Comment by anasalkouz** [comment]
Duplicate of #7802
