### ISSUE TITLE
[UPGRADE] Path for environment variables fetched via System.getenv

### ISSUE THREAD

**Issue by dblock** [opensearch-project/OpenSearch#781]
**Is your feature request related to a problem? Please describe.**

We have renamed environment variables, e.g. `ES_TMPDIR` has become `OPENSEARCH_TMPDIR`. 
We have renamed `ES_JAVA_OPTS` to `OPENSEARCH_JAVA_OPTS` used in `opensearch-env`.
What is the path forward for those settings?

**Describe the solution you'd like**

Document the way this breaks for users.
Provide a migration path.
Optionally provide tooling to aid users in the migration path.

**Additional context**
Coming from #640.

**Comment by nknize** [comment]
#846 will close this. Bumping to v1.1 release

**Comment by dblock** [comment]
Closing with #846 done.
