### ISSUE TITLE
[UPGRADE] Path for elasticsearch.yml to opensearch.yml

### ISSUE THREAD

**Issue by dblock** [opensearch-project/OpenSearch#782]
**Is your feature request related to a problem? Please describe.**

We have renamed `elasticsearch.yml` into `opensearch.yml` which contains local node settings that themselves might contain names such as `opendistro.security...`. What is the path forward for that configuration file and its contents?

**Describe the solution you'd like**

Document the way this breaks for users.
Provide a migration path.
Optionally provide tooling to aid users in the migration path.

**Additional context**
Coming from #640.

**Comment by nknize** [comment]
will be closed by #846. bumping to 1.1 release

**Comment by dblock** [comment]
Closing with #846 done.
