### ISSUE TITLE
[BUG] FlatObjectFieldMapper calls getFields, not getField

### ISSUE THREAD

**Issue by marevol** [opensearch-project/OpenSearch#7835]
**Describe the bug**

In FlatObjectFieldMapper#parseValueAddFields, getFields is called, but getField needs to be used.
(In our performance tests, this issue reduced indexing speed.)

**To Reproduce**

Please see [FlatObjectFieldMapper.java#L631](https://github.com/opensearch-project/OpenSearch/blob/2.7.0/server/src/main/java/org/opensearch/index/mapper/FlatObjectFieldMapper.java#L631).

**Expected behavior**

Please replace _getFields_ with _getField_.

**Plugins**

None

**Screenshots**

None

**Host/Environment (please complete the following information):**

 - OS: OS-Independent
 - Version 2.7

**Additional context**

This issue was reported based on this [comment](https://forum.opensearch.org/t/flatobjectfieldmapper-calls-getfields-not-getfield/14451/1) from the Forum.

**Comment by andrross** [comment]
This is definitely a bug. The line in question is doing an `.equals()` operation on an `IndexableField[]` (_array_ type) and passing in a `Field` type, which by definition will always return false.

@marevol Any interest in putting up a PR to fix this? It would be great to create a unit test that fails with the current code as well.

**Comment by marevol** [comment]
I've created PR.
I checked the existing JUnit test code, and it looks good to me.
I think this is an indexing performance issue, not the data itself.
I couldn't come up with any test code to add at the moment...

**Comment by noCharger** [comment]
If there is a plan, we should backport this bugfix to all previous minor versions so that it can be included in the patch version.

**Comment by mingshl** [comment]
Thanks @marevol for the bug fixed ticket, it got in main and back-ported to 2.x.
