### ISSUE TITLE
[UPGRADE] Path for elasticsearch.keystore into opensearch.keystore

### ISSUE THREAD

**Issue by dblock** [opensearch-project/OpenSearch#785]
**Is your feature request related to a problem? Please describe.**

We have renamed elasticsearch.keystore into opensearch.keystore. What is the path forward for that keystore?

**Describe the solution you'd like**

Document the way this breaks for users.
Provide a migration path.
Optionally provide tooling to aid users in the migration path.

**Additional context**
Coming from #640. There's also https://github.com/opensearch-project/OpenSearch/issues/468 that needs to be fixed.

**Comment by nknize** [comment]
#846 will close this. bumping to v1.1 release

**Comment by dblock** [comment]
Closing with #846 done.
