### ISSUE TITLE
[BUG] Meta issue to track all BWC failed test cases

### ISSUE THREAD

**Issue by harold-wang** [opensearch-project/OpenSearch#786]
**Describe the bug**
The intent of this issue is to track failed BWC test cases:

**To reproduce**
Build:
       main
      + PR #775
      + build.gradle
           boolean bwc_tests_enabled = true
           final String bwc_tests_disabled_issue = ""

**To run BWC**
     ./gradlew bwcTest
     ./gradlew v7.9.2#bwcTest

**- [ ] git checkout failure**
    Task :distribution:bwc:bugfix:checkoutBwcBranch FAILED
    Performing checkout of opensearch-project/7.10...
    Exec output and error:
    Output for git:error: pathspec 'opensearch-project/7.10' did not match any file(s) known to git
**- [ ] Task :qa:rolling-upgrade:v6.8.0#oldClusterTest**
       ./gradlew ':qa:rolling-upgrade:v6.8.0#oldClusterTest' --tests 
      "org.opensearch.upgrades.UpgradeClusterClientYamlTestSuiteIT" -Dtests.method="test 
      {p0=old_cluster/20_date_range/Create index with joda style index that is incompatible with java.time. (6.0)}" - 
      Dtests.seed=DB0FF3ADB20AFCAE -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1" - 
     Dtests.locale=id-ID -Dtests.timezone=SystemV/AST4 -Druntime.java=15 -Dtests.rest.suite=old_cluster

**- [ ] Task :qa:mixed-cluster:v6.8.0#mixedClusterTest**
    ./gradlew ':qa:mixed-cluster:v6.8.0#mixedClusterTest' --tests 
    "org.opensearch.backwards.MixedClusterClientYamlTestSuiteIT" -Dtests.method="test {p0=cat.aliases/10_basic/Complex 
    alias (pre 7.4.0)}" -Dtests.seed=DB0FF3ADB20AFCAE -Dtests.security.manager=true -Dtests.jvm.argline="- 
    XX:TieredStopAtLevel=1" -Dtests.locale=fi-FI -Dtests.timezone=MST7MDT -Druntime.java=15

**- [ ] Task :qa:full-cluster-restart:v7.9.2#oldClusterTest**
./gradlew ':qa:full-cluster-restart:v7.9.2#oldClusterTest' --tests "org.opensearch.upgrades.FullClusterRestartIT.testOperationBasedRecovery" -Dtests.seed=709E5E3832D0B744 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1" -Dtests.locale=es-PA -Dtests.timezone=America/Recife -Druntime.java=15

**- [ ]Task :qa:repository-multi-version:v7.9.2#Step3OldClusterTest**
./gradlew ':qa:repository-multi-version:v7.9.2#Step3OldClusterTest' --tests "org.opensearch.upgrades.MultiVersionRepositoryAccessIT.testCreateAndRestoreSnapshot" -Dtests.seed=709E5E3832D0B744 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1" -Dtests.locale=sr-ME -Dtests.timezone=America/Catamarca -Druntime.java=15

**- [ ]Task :qa:full-cluster-restart:v7.9.2#oldClusterTest**
./gradlew ':qa:full-cluster-restart:v7.9.2#oldClusterTest' --tests "org.opensearch.upgrades.FullClusterRestartIT.testEnableSoftDeletesOnRestore" -Dtests.seed=709E5E3832D0B744 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1" -Dtests.locale=es-PA -Dtests.timezone=America/Recife -Druntime.java=15

**Comment by dblock** [comment]
I started looking at git checkout failure, looks like we need to be fetching from ES repo here or re-create 7.x tags in this one.

**Comment by dblock** [comment]
Attempted fix for `git checkout failure` in https://github.com/opensearch-project/OpenSearch/pull/788.

**Comment by adnapibar** [comment]
> Attempted fix for `git checkout failure` in #788.
> 
> @adnapibar is fixing this

Thanks @dblock

**Comment by dblock** [comment]
The change in https://github.com/opensearch-project/OpenSearch/pull/791 fixes the first problem for me.

**Comment by nknize** [comment]
closed by #775
