### ISSUE TITLE
[BUG] repository-s3 YAML rest tests and third party tests fail with region mismatch issue

### ISSUE THREAD

**Issue by raghuvanshraj** [opensearch-project/OpenSearch#7866]
**Describe the bug**
The [repository-s3 documentation](https://www.elastic.co/guide/en/elasticsearch/reference/8.8/repository-s3.html#repository-s3-client) mentions that the default region setting for the plugin is `us-east-1`, but upon migrating this plugin to AWS v2 SDK (#7372), which mandates setting a region, `s3ThirdPartyTests` and all yamlRestTest targets are failing with an exception similar to the following:
```
S3Exception[The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'us-west-2' (Service: S3, Status Code: 400, Request ID: 52FV4B8CJZRC68JR, Extended Request ID: IJII6RnMKQLDxPT4BZiAl24Wyvycc5C3Wp7BQexXO/gidyY1igDuXskSy2Tr62B9H7Dn6DqansI=)]
```

It is unclear how these tests were working with the v1 SDK, since there doesn't seem to be any override for region `us-west-2` in the code, which should be considering that the default is `us-east-1`.

**To Reproduce**
As of now I'm unable to reproduce it locally, but the following gradle CI runs might give some context:
- https://build.ci.opensearch.org/job/gradle-check/16649/
- https://build.ci.opensearch.org/job/gradle-check/16655/

In these runs, the region setting was defaulting to `us-east-1`, as opposed to an empty string being se before the v2 migration was undertaken.

**Expected behavior**
All tests, without any region overrides, should use the default region, which is `us-east-1`.

**Plugins**
repository-s3

**Host/Environment (please complete the following information):**
 - Jenkins

**Comment by reta** [comment]
Just to reiterate the difference between CI and local: on CI (Jenkins) we use real S3 service (test account).

**Comment by dblock** [comment]
So we rely on the fact that `test.s3.account` and friends are set somewhere, https://github.com/opensearch-project/OpenSearch/pull/7372#issuecomment-1572314484. @peterzhuamazon do you know where that's set for gradle checks?

**Comment by peterzhuamazon** [comment]
https://github.com/opensearch-project/opensearch-build-libraries/blob/main/vars/runGradleCheck.groovy#L23-L24

**Comment by dblock** [comment]
I think https://github.com/opensearch-project/OpenSearch/pull/7974#issuecomment-1583402773 is a clear explanation of what's going on. I can successfully run these tests with credentials and an S3 bucket that match (in us-east-1).
