### ISSUE TITLE
[UPGRADE] Plugin installation process during upgrade

### ISSUE THREAD

**Issue by mch2** [opensearch-project/OpenSearch#787]
Is your feature request related to a problem? Please describe.

What is the path forward for installing or uninstalling default plugins during an upgrade?  Is there config outside of opensearch.yml #782 that needs to be migrated?

Document the way this breaks for users.
Provide a migration path.
Optionally provide tooling to aid users in the migration path.

Additional context
Coming from #640.

**Comment by nknize** [comment]
Looks like this can be released as a new feature in 1.1?

**Comment by nknize** [comment]
Bumping to v1.2.0

**Comment by mch2** [comment]
Closing this as CLI tool is merged to 1.x and will be released with 1.2.
