### ISSUE TITLE
[BUG] Match query returns 0 results even when tokens are present in document

### ISSUE THREAD

**Issue by rishikeshvyas** [opensearch-project/OpenSearch#7884]
**Describe the bug**
Match query with default parameters returns 0 results when using custom analyzer even when some terms are common between query and document

**To Reproduce**
1. Create test index
```json
PUT test_index 
{
  "settings": {
      "index": {
        "analysis": {
          "filter": {
            "search_word_delimiter": {
              "split_on_numerics": "false",
              "split_on_case_change": "true",
              "generate_word_parts": "true",
              "type": "word_delimiter_graph",
              "preserve_original": "true",
              "generate_number_parts": "true"
            },
            "word_delimiter": {
              "split_on_numerics": "true",
              "split_on_case_change": "true",
              "generate_word_parts": "true",
              "type": "word_delimiter_graph",
              "preserve_original": "true",
              "generate_number_parts": "true"
            }
          },
          "analyzer": {
            "index_analyzer": {
              "filter": [
                "word_delimiter"
              ],
              "type": "custom",
              "tokenizer": "icu_tokenizer"
            },
            "search_analyzer": {
              "filter": [
                "search_word_delimiter"
              ],
              "type": "custom",
              "tokenizer": "icu_tokenizer"
            }
          }
        }
      }
    },
  "mappings": {
    "properties": {
      "testField": {
          "type": "text",
          "analyzer": "index_analyzer",
          "search_analyzer": "search_analyzer"
      }
    }
  }  
}
```
2. Index document
```json
PUT test_index/_doc/1
{
  "testField": "abcDef_efgHij"
} 
```

3. Check indexed tokens
GET test_index/_termvectors/1?fields=testField

tokens: ["Def", "Hij", "abc", "abcDef_efgHij", "efg"]

4. Check tokens for query "efgHi"
```json
POST test_index/_analyze
{
  "analyzer": "search_analyzer",
  "text": "efgHi"
}
```
tokens: ["efgHi", "efg", "Hi"]

5. Run match query
```json
GET test_index/_search
{
  "query": {
    "match": {
      "testField": "efgHi"
    }
  }
}
```
This gives no results even though "efg" token is present in the document.

**Expected behavior**
Indexed document should be returned.

**Plugins**
NA

**Screenshots**
NA

**Host/Environment (please complete the following information):**
Opensearch 1.0

**Additional context**

**Comment by msfroh** [comment]
Hey @rishikeshvyas, I think the issue here is that the word delimiter graph for query time is effectively:

```
(start) ----> efg --> Hi --> (end)
      |                        ^
      + --->    efgHi   ---->  +

```

That is, the search is saying "either match `efg` **followed by** `Hi` or match `efgHi`". As a query string, we would write that as `"efg Hi" OR efgHi`. Since the indexed token stream has `"efg Hij"`, the phrase query doesn't match.

Is your goal to match on any sub-term of the query string? I'm sure if that is possible with the underlying analyzers. I think you would need a filter that puts all the tokens in the same position, which I think would turn it into `efg OR Hi OR efgHi`.

**Comment by msfroh** [comment]
I'm going to close this, because it sounds like the word delimiter graph filter is behaving the way that it should -- a search for `efgHi` should match `efg` followed by `Hi` (as a phrase).

@rishikeshvyas, if you disagree, please feel free to reopen. Thanks!
