### ISSUE TITLE
Use IMDSv2 in disvovery-ec2

### ISSUE THREAD

**Issue by dblock** [opensearch-project/OpenSearch#7916]
**Is your feature request related to a problem? Please describe.**

IMDSv2 introduces [a number of security improvements](https://aws.amazon.com/blogs/security/defense-in-depth-open-firewalls-reverse-proxies-ssrf-vulnerabilities-ec2-instance-metadata-service/) over IMDSv1.

**Describe the solution you'd like**

Following upgrade to AWS SDK v2 in https://github.com/opensearch-project/OpenSearch/pull/7372, upgrade use of IMDSv1 to v2.

**Additional context**

See https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/configuring-instance-metadata-service.html

**Comment by Bukhtawar** [comment]
Duplicate of : https://github.com/opensearch-project/OpenSearch/issues/3040

**Comment by dblock** [comment]
Whoops. Closing in favor of https://github.com/opensearch-project/OpenSearch/issues/3040
