### ISSUE TITLE
[BUG] org.opensearch.cluster.coordination.CoordinatorTests.testUnresponsiveLeaderDetectedEventually flaky

### ISSUE THREAD

**Issue by dblock** [opensearch-project/OpenSearch#7973]
**Describe the bug**

```
REPRODUCE WITH: ./gradlew ':server:test' --tests "org.opensearch.cluster.coordination.CoordinatorTests.testUnresponsiveLeaderDetectedEventually" -Dtests.seed=162694DEF7CDB844 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=es-CU -Dtests.timezone=MST7MDT -Druntime.java=17

org.opensearch.cluster.coordination.CoordinatorTests > testUnresponsiveLeaderDetectedEventually FAILED
    java.lang.AssertionError: node0 has applied its state 
    Expected: <8L>
         but: was <7L>
        at __randomizedtesting.SeedInfo.seed([162694DEF7CDB844:6C4F939E12DF7B55]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:964)
        at org.opensearch.cluster.coordination.AbstractCoordinatorTestCase$Cluster.stabilise(AbstractCoordinatorTestCase.java:578)
        at org.opensearch.cluster.coordination.CoordinatorTests.testUnresponsiveLeaderDetectedEventually(CoordinatorTests.java:568)
```

https://github.com/opensearch-project/OpenSearch/pull/7971#issuecomment-1583066328

**Comment by scrawfor99** [comment]
Hi @dblock, what are your thoughts on closing this issue since it does not appear to be reproducible:

![Screenshot 2023-06-21 at 12 24 24 PM](https://github.com/opensearch-project/OpenSearch/assets/65832608/8789ea99-ee6a-47f0-8345-4f44ddbf0a74)

I ran 500+ iterations and could not get a failure; I am not sure how we will fix any issue that may exist if we have such a low occurrence rate.

**Comment by dblock** [comment]
Thanks for trying! It's probably still an issue :)

**Comment by r1walz** [comment]
Hi, @dblock. I'm also unable to repro this one. Are we sure it's a flaky test? [Console output](https://build.ci.opensearch.org/job/gradle-check/17152/consoleText) of original [gradle-check](https://github.com/opensearch-project/OpenSearch/pull/7971#issuecomment-1583066328) run complains ...

```sh
Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "pool-1-thread-1"
```

... which seems to be an issue with memory allocated to perform test (gradle client ran out of memory here?). It's been five months and we haven't seen this issue again. Shall we close it?

cc: @kotwanikunal @scrawfor99

**Comment by kotwanikunal** [comment]
@r1walz If thats the case and no one has reported in the past few months, we can close it. 
We can work on it if it resurfaces.
@dblock What do you think?

> Hi, @dblock. I'm also unable to repro this one. Are we sure it's a flaky test? [Console output](https://build.ci.opensearch.org/job/gradle-check/17152/consoleText) of original [gradle-check](https://github.com/opensearch-project/OpenSearch/pull/7971#issuecomment-1583066328) run complains ...
> 
> ```shell
> Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "pool-1-thread-1"
> ```
> 
> ... which seems to be an issue with memory allocated to perform test (gradle client ran out of memory here?). It's been five months and we haven't seen this issue again. Shall we close it?
> 
> cc: @kotwanikunal @scrawfor99

**Comment by dblock** [comment]
The [logs](https://build.ci.opensearch.org/job/gradle-check/17152/consoleText) show a clear test failure, and until someone can explain how `pool-1-thread-1` running out of memory would cause this specific test failure, I would say we're speculating, and a real problem may be hiding under these symptoms. I don't think we should be closing issues that are 1) not reproducible, 2) can't be explained. I'll close though because I don't want to die on hill number 2 :)
