### ISSUE TITLE
Run gradle checks on 1.x

### ISSUE THREAD

**Issue by dblock** [opensearch-project/OpenSearch#798]
**Is your feature request related to a problem? Please describe.**

We need to be running CI on main, and 1.xm, as they will be diverging (1.x will be 1.1 and main will be 2.0), including backward compatibility tests. In the future we'll want CI to automatically start running on 2.x.

**Describe the solution you'd like**

Make CI on main = CI on 1.x.

**Comment by adnapibar** [comment]
Can the CI be configured to run on any branch in addition to main that ends with **.x** so we don't have to keep creating issues to enable CI in 2.x, 3.x ... ?

**Comment by dblock** [comment]
@bbarani

**Comment by dblock** [comment]
This has a corresponding https://github.com/opensearch-project/opensearch-build/issues/39.

**Comment by mch2** [comment]
I believe this can be closed as a duplicate to https://github.com/opensearch-project/opensearch-build/issues/350.

@dblock thoughts?

**Comment by dblock** [comment]
I've renamed to "run gradle checks on 1.x"

**Comment by mch2** [comment]
I think we can close this issue - gradle checks currently run for any branch as long as 'start gradle check' comment is made on the PR.

I've opened a separate [issue](https://github.com/opensearch-project/opensearch-build/issues/417) to make the gradle check job public. 
We also have an [existing issue](https://github.com/opensearch-project/opensearch-build/issues/245) for setting up randomized testing that will be branch specific.
