### ISSUE TITLE
Run BWC checks on CI

### ISSUE THREAD

**Issue by adnapibar** [opensearch-project/OpenSearch#799]
**Is your feature request related to a problem? Please describe.**

Currently, only a small number of BWC checks are run as part of the `./gradlew check`. We need to make sure the changes are fully backwards compatible with the supported versions. 

**Describe the solution you'd like**
Run the entire suite of BWC checks on the CI as part of a separate job.

`./gradlew bwcTest`

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by dblock** [comment]
Is https://github.com/opensearch-project/OpenSearch/pull/796 now running these as part of `gradle check`? If so we can close this, right?

**Comment by adnapibar** [comment]
> Is #796 now running these as part of `gradle check`? If so we can close this, right?

`gradle check` doesn't run the full suite of BWC checks. These need to be separately run using `gradle bwcTest`

**Comment by dblock** [comment]
So do we want a separate job? A nightly job? @adnapibar

**Comment by adnapibar** [comment]
> So do we want a separate job? A nightly job? An on-demand admin-triggered `run gradle bwctest`? @adnapibar

Can be both - an automated nightly job but also can be started on demand if required on PRs that might introduce a breaking change. Also, we may want to run only for specific versions e.g. `gradle v7.10.2#bwcTest`. What do you think? 

In my opinion, all these checks (doc, precommit, unit, integrations, bwc, packaging ...) should run automatically on a PR (that's a separate conversation topic though!)

**Comment by dblock** [comment]
In terms of infrastructure it's probably wasteful to run it on all PRs, I'd be satisfied if we ran it "regularly", like nightly and on demand. I'll leave this to @bbarani.

**Comment by nknize** [comment]
With all of the BWC failures I think we need this as a separate "on demand" task that can be initiated through the PR comment (e.g., `run gradle bwctest`). I think adding the ability to specify a version is a "nice to have" but we just ran into a situation where OpenSearch 1.0 wasn't working w/ a 1.1 build because of a missing commit that wasn't backported. We need these tests to ensure those things don't happen in the future.

**Comment by saratvemulapalli** [comment]
@nknize agreed. 
As part of the CICD surge, we will now run nightly builds and run integration, bwc, perftests. 
I think we should be able to leverage BWC tests via nightly CI. 
Once we have nightly CI ready and operational we can stop running BWC tests on PR check.
Let me know what you think..
