### ISSUE TITLE
Document/create/add a migration guide from ES 7.10.2

### ISSUE THREAD

**Issue by FreCap** [opensearch-project/OpenSearch#801]
I work with a large deployment of ES, and planning on migrating on OpenSearch.

I was wondering if it would be possible to create a **migration guide from ES 7.10.2** to help SREs having a smooth migration and avoiding common pitfalls (e.g. forgotten configs, changed endpoints etc..)

In case OpenSearch can be used as a drop-in solution in which we just replace the ES executable with OS, it'd be even a better news!

Thank you,
Francesco

**Comment by dblock** [comment]
I believe @elifish is actively working on this, along with a compatibility FAQ. You might also want to check out https://github.com/opensearch-project/OpenSearch/issues/671.

**Comment by dblock** [comment]
Upgrading FAQ PR in https://github.com/opensearch-project/project-website/pull/103

**Comment by nknize** [comment]
any update here? /cc @elfisher

**Comment by dblock** [comment]
Migration guide was added in https://github.com/opensearch-project/documentation-website/pull/40.

https://docs-beta.opensearch.org/upgrade-to/upgrade-to/
