### ISSUE TITLE
Perform force merge only on primary shard of the index

### ISSUE THREAD

**Issue by sohami** [opensearch-project/OpenSearch#8021]
**Is your feature request related to a problem? Please describe.**
Currently, force merge works on both primary and replica shards by default. It doesn't provide option to merge primary shard only. For some cases, it will be beneficial if users don't want the replica shards to be merged to avoid resource utilization on replica nodes and only limit it to primary shards. For example: With support of searchable snapshot for better search performance user would want to merge the segments to 1 or fewer number before taking snapshot of the index. Using ISM users can 
trigger force merge on primary shard only and then take snapshot to use it later using searchable snapshot mechanism to have better query performance.

**Describe the solution you'd like**
Force merge request to provide option to merge primary only shard.

**Describe alternatives you've considered**
1) Index settings to control for which indices primary shard should be merged

**Additional context**
N/A

**Comment by jed326** [comment]
Resolved by https://github.com/opensearch-project/OpenSearch/pull/11269
