### ISSUE TITLE
primary weight factor should exchange primary and replica at the same in the smalll cluster in some case

### ISSUE THREAD

**Issue by kkewwei** [opensearch-project/OpenSearch#8060]
**Is your feature request related to a problem? Please describe.**
It is very much looking forward to introducing the primary weight factor in #6017, but it seems not work in the small cluster, for example:
index1 settings: 
```
 "number_of_replicas": "2",
 "number_of_shards": "3"
```
The cluster has three nodes: node0, node1, node2, the allocation of the index1 is:
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; node0  node1   node2
shard0  &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;  p   &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;  r  &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; r    
shard1  &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;  p   &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;  r  &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; r  
shard2  &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;  p   &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;  r  &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; r  
there are 3 primary shards in the node0.

When put the settings:
```
PUT _cluster/settings
{
    "persistent": {
        "cluster.routing.allocation.balance.prefer_primary":"true"
    }
}
```
There will no primary rebalance as expected, the reason is that a copy of this shard is already allocated to every target host.

**Describe the solution you'd like**
There are good reasons to rebalance primary shards. When rebalancing the primary ,and target node has the replica shard, if we should exchange the primary and replica at the same time.

In addition, I'm a little confused why we not Introduce `cluster.primary.shard.balance.constraint` in rebalance, the feature seems usefully in certain scenarios.

**Comment by Bukhtawar** [comment]
cc: @dreamer-89

**Comment by dreamer-89** [comment]
Thank you @kkewwei for opening this issue. 

> There are good reasons to rebalance primary shards. When rebalancing the primary ,and target node has the replica shard, if we should exchange the primary and replica at the same time.

There are few limitations today which prevent primary shard balancing. One of them prevents primary shard movement when target node already contains replica copy. This is known as [SameShardAllocationDecider](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/cluster/routing/allocation/decider/SameShardAllocationDecider.java). We do have issue open to fix this and tracked in https://github.com/opensearch-project/OpenSearch/issues/6481 . If you are interested please feel free to take up and work on this issue. 

>In addition, I'm a little confused why we not Introduce cluster.primary.shard.balance.constraint in rebalance, the feature seems usefully in certain scenarios.

We are actually using `cluster.primary.shard.balance.constraint` during shard rebalancing. We are using same constants for both allocation and rebalance actions. PR where this change was introduced https://github.com/opensearch-project/OpenSearch/pull/6422

**Comment by dreamer-89** [comment]
@kkewwei: Closing this issue since in favour https://github.com/opensearch-project/OpenSearch/issues/6481.

**Comment by kkewwei** [comment]
@dreamer-89 sorry to reopen the issue.
I'm did a little confused about `cluster.primary.shard.balance.constraint` during shard rebalancing. I test the local scenarios, and it doesn't work:
index* settings: 
```
 "number_of_replicas": "1",
 "number_of_shards": "1"
```
The cluster has three nodes: node0, node1, node2,  every index* has only one primary and one replica, the allocation is:
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; node0  node1   node2
index0  &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;  p   &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;  r  
index1  &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;  p   &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;    &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; r  
index2  &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;    &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;  p  &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; r  
the node0 has two primary shards, even if `cluster.routing.allocation.balance.prefer_primary=true`. 

In RebalanceConstraints, we don't set `cluster.primary.shard.balance.constraint`
https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/cluster/routing/allocation/RebalanceConstraints.java#L32

If we should add `cluster.primary.shard.balance.constraint` in RebalanceConstraints? or i miss something?

**Comment by kkewwei** [comment]
@dreamer-89  please confirm it in your spare time.

**Comment by dreamer-89** [comment]
Thank you @kkewwei for the comment and taking the effort to share the use case with detail. 

Today, rebalancing of primary shard is performed at index level i.e. primary shards belonging to same index are distributed equally. The issue you shared [above](https://github.com/opensearch-project/OpenSearch/issues/8060#issuecomment-1592335152) relates to primary balance across all indices. This is another problem that we have yet to solve and is tracked in separate issue https://github.com/opensearch-project/OpenSearch/issues/6642.
