### ISSUE TITLE
Benchmark Segment Replication with Remote Store

### ISSUE THREAD

**Issue by ankitkala** [opensearch-project/OpenSearch#8087]
Tracking issue to benchmark the Segment Replication using remote store against 
1. SegRep without remote store. 
2. Logical replciation

**Comment by rishabh6788** [comment]
We already have nightly benchmark runs for segrep without remote-store. See `Segement Replication` on https://opensearch.org/benchmarks. 
@ankitkala

**Comment by rishabh6788** [comment]
nightly-benchmark runs for remote-store feature has been enabled.

**Comment by mch2** [comment]
Closing this because nightlies are set-up - we can track manual runs here - https://github.com/opensearch-project/OpenSearch/issues/8109
