### ISSUE TITLE
[Segment Replication + Remote Store] GA test planning

### ISSUE THREAD

**Issue by mch2** [opensearch-project/OpenSearch#8109]
This issue contains a running list of testing required In preparation for the release of using [remote storage with segment replication](https://github.com/opensearch-project/OpenSearch/issues/4448).

### Objective

1. Show trade-offs when compared to document replication.
2. Show trade-offs when compared to segment node-node replication.
3. Learn break points & bottlenecks depending on cluster configuration/workload.

### General Hypothesis

1. Segrep + remote store (S&R) will achieve better ingest throughput, search latencies, and replication lag times as replica count grows. This is attributed to primary shards not incurring an incremental network cost per replica.
2. S&R would see higher primary refresh time when compared to node-node replication.  This is attributed to primary shards synchronously uploading to remote store in refresh path.
3. Overloaded clusters should result in remote store and/or segment replication backpressure applied.

### Performance Benchmark Plan <a href="#performance-heading" id="performance-heading">#</a>
Each use case listed below should also be performed with docrep & node-node replication and where possible added to our nightly runs on https://opensearch.org/benchmarks for easy ongoing comparison.

Metrics that should be captured in addition what OSB reports:
- Replication lag - Add to OSB.
- Network Throughput
- IOPS
- Thread pool stats - I think this may already be an optional return from OSB.

All clusters should have 3 dedicated cluster manager nodes.
Small cluster = ~3 nodes
Large cluster = ~40 nodes
Use m5.xlarge node type for consistency.

Use case | Workload(s) | Variations | Notes | Why | Assignee
-- | -- | -- | -- | -- | --
Ingest append-only | SO | Small cluster (3 nodes, 10 shards). 1 replica case and max replica case | Small cluster here is equivalent to existing nightlies. | General ingest performance |  
Update heavy / Large dataset | http_logs | large cluster (~10GB per shard)  - 1 replica case & max replica case |   | Validate assertions that segrep performs even better in update/delete cases. |  
  | http_logs | large cluster (~50GB per shard)  - 1 replica case & max replica case |   | Comparison as shards grow in size |  
  | http_logs | Small cluster - (~10GB per shard) 1 replica case & max replica case |   |   |  
  | http_logs | Small cluster - (50gb per shard) 1 replica case & max replica case |   |   |  
Concurrent ingest/search with deep replica counts | TBD |   | No OSB workload exists today that concurrently performs ingest & search. | Validate hypothesis 1 with consistent ingest/search traffic |  
Zero replicas configured | any |   |   | Ensure no downgrade to docrep. |  

Additional tests (nice to have):
Longevity testing - Longer running test with large cluster.
Architecture comparison (x86 v arm)

### Feature Stability and Testing <a href="#testing-heading" id="testing-heading">#</a>
This is a list of specific test cases that should be performed either through existing/new ITs or manual.
We are working on enabling S+R across our entire server suite as part of [this](https://github.com/opensearch-project/OpenSearch/issues/6761) issue, but are hitting challenges.  So in the meantime creating a running list of the most critical.

Feature / Type | Test Case | Notes:
-- | -- | --
Backpressure |   |  
  | Primary slow to upload |  
  | Replica slow to fetch |  
  | Slow checkpoint publish |  
Relocation |   |  
  | Primary-Primary |  
  | Replica or Primary to Replica |  
Shard events |   |  
  | Delete index |  
  | Replica removal |  
  | Replica add |  
  | Primary drop |  
  | Replica drop |  
  | Replica restart |  
  | Primary drop |  
  | Trigger a drop during segment download |  
Segrep Stats API |   |  
  | All metrics present |  
Mem leak / heap analysis |   | This would be manual, fetch a heap dump for analysis.
  | Constant calls to segrep stats API |  
  | Before/after replication events on primary |  
  | before/after replication events on replica |  
BWC |   |  
  | Test node-node for no breakage.  Add new tests in next release for remote store |  

Existing test packages to run with SR enabled in :server.
cluster
gateway
index
indexing
indices
ingest
recovery
remotestore
update

**Comment by ankitkala** [comment]
- Definitely agree with adding a telemetry device in OSB to capture the replication lag. [Here](https://github.com/opensearch-project/opensearch-benchmark/pull/104/files#diff-0d7e6a551776859739f9e87f08266161f045985a6d2dad88f933f504fe902d36R435-R465) is a similar change we did for CCR lag.



> Network Throughput
IOPS
Thread pool stats - I think this may already be an optional return from OSB.

These metrics can be published to a different cluster by OSB buy i don't think these are part of the test result.

**Comment by mch2** [comment]
Splitting this out into individual runs:

Here's what I'm thinking in terms of set up - 
All clusters should have 3 dedicated cluster manager nodes.
Small cluster = ~3 nodes
Large cluster = ~40 nodes
Use m5.xlarge node type for consistency.

Use case | Workload(s) | Variations | Notes | Why | Assignee
-- | -- | -- | -- | -- | --
Ingest append-only | SO | Small cluster (3 nodes, 10 shards). 1 replica case and max replica case | Small cluster here is equivalent to existing nightlies. | General ingest performance |  
Update heavy / Large dataset | http_logs | large cluster (~10GB per shard)  - 1 replica case & max replica case |   | Validate assertions that segrep performs even better in update/delete cases. |  
  | http_logs | large cluster (~50GB per shard)  - 1 replica case & max replica case |   | Comparison as shards grow in size |  
  | http_logs | Small cluster - (~10GB per shard) 1 replica case & max replica case |   |   |  
  | http_logs | Small cluster - (50gb per shard) 1 replica case & max replica case |   |   |  
Concurrent ingest/search with deep replica counts | TBD |   | No OSB workload exists today that concurrently performs ingest & search. | Validate hypothesis 1 with consistent ingest/search traffic |  
Zero replicas configured | any |   |   | Ensure no downgrade to docrep. |

**Comment by ankitkala** [comment]
For small cluster configuration, let's test with shards in multiple of 3 (currently testing with 3, 6, 12, 24). Similar configuration is being used for remote store perf testing as well

**Comment by mch2** [comment]
> Similar configuration is being used for remote store perf testing as well

Where can we track that testing? I expect there is overlap here given node-node replication is not used with remote store?
