### ISSUE TITLE
Add `skip gradle check` that doesn't run gradle checks but passes the `run gradle check` requirement.

### ISSUE THREAD

**Issue by dblock** [opensearch-project/OpenSearch#813]
**Is your feature request related to a problem? Please describe.**

We often make PRs such as https://github.com/opensearch-project/OpenSearch/pull/812 that are a README change or similar trivialities. This wastes a costly and time-consuming `run gradle check`.

**Describe the solution you'd like**

Admins should be able to comment `run gradle check` or `skip gradle check` which will respectively run or skip gradle check and satisfy the gradle check requirement. It should also be clear which one was chosen when looking at a PR.

**Describe alternatives you've considered**

Just always run gradle checks. In that case I'd want to be able to `[skip gradle check]` in the commit message.

**Additional context**

Related to https://github.com/opensearch-project/OpenSearch/issues/597

**Comment by andrross** [comment]
Closing now that #13498 is implemented
