### ISSUE TITLE
Pull requests to inherit labels from parent issues

### ISSUE THREAD

**Issue by anasalkouz** [opensearch-project/OpenSearch#8199]
**Is your feature request related to a problem? Please describe.**
Currently, we have 100+ open PRs and they are increasing week over week. It could be much easier for people to review PRs if they have clear component labels. For example if the PR has `indexing` label, then maintainers and contributors who have indexing experience can pick those related PRs and review/merge them easily.

**Describe the solution you'd like**
PR can automatically inherit labels from the associated issues. Once contributor connect PR to an issues, an automatic workflow will be triggered to copy labels from the issue to the PR.

There should be a logic to exclude some labels like `untriaged`

cc: @andrross @dblock

**Comment by anasalkouz** [comment]
@kotwanikunal did you have an example proof it works in core?

**Comment by kotwanikunal** [comment]
> @kotwanikunal did you have an example proof it works in core?

I was just testing it out. Sample here: https://github.com/opensearch-project/OpenSearch/pull/9694 :)

**Comment by msfroh** [comment]
I got autolabeled just after this went live: https://github.com/opensearch-project/OpenSearch/pull/10036 😄 

Very nice!
