### ISSUE TITLE
Introduce an OpenSearch output plugin for Logstash

### ISSUE THREAD

**Issue by elfisher** [opensearch-project/OpenSearch#820]
## Requirement/Problem - what kind of business use case are you trying to solve?

Many people who use open source Elasticsearch use Logstash for data ingestion. People will want to continue to use their Logstash deployments as they transition to OpenSearch. To make that transition easier, it would be good to provide an specific OpenSearch output plugin for Logstash that is tested and guaranteed to work.

## Proposal - what do you suggest to solve the problem or improve the existing situation?

We build an OpenSearch output plugin for open source Logstash 7.x. We should package this plugin with the most current version of Logstash available and provide a link to the installable binary. My proposal is to support the following:
1. OpenSearch 1.x
2. Elasticsearch OSS 7.x. This is to provide backwards compatibility for people still using older version of Elasticsearch OSS and enable them to run newer versions of Logstash such as 7.13.x
3. ODFE 1.x. This is for the same backwards compatibility reasons as Elasticsearch OSS.
4. (To be discussed) There are other output plugins like the Amazon ES one that just add auth. It would be nice to have this output plugin support a variety of authentication mechanisms so that there doesn't need to be a new output plugin just to add a new type of authentication.

**Comment by dblock** [comment]
This is https://github.com/opensearch-project/logstash-output-opensearch. Closing the issue.
