### ISSUE TITLE
Please allow fake-changing the version number for the sake of compatibility.

### ISSUE THREAD

**Issue by ShikiSuen** [opensearch-project/OpenSearch#822]
**Is your feature request related to a problem? Please describe.**
https://xenforo.com/community/threads/xfes-cannot-distinguish-version-number-between-elasticsearch-and-opensearch.195194/#post-1521132

**Describe the solution you'd like**
In case that XenForo Enhanced Search (XFES) hesitates to detect version number specifically for OpenSearch, the last resort is to allow OpenSearch users to change OpenSearch version number to any number above what XFES requires (currently 2.x and above).

**Describe alternatives you've considered**
The thread in XenForo Forum is already suggesting XFES to distinguish version number between ElasticSearch and OpenSearch.

**Additional context**
![image](https://user-images.githubusercontent.com/3164826/120913188-b3aa3500-c6c7-11eb-9d33-c6ba29b6700f.png)
![image](https://user-images.githubusercontent.com/3164826/120913190-b7d65280-c6c7-11eb-8874-d53b4a345119.png)

**Comment by dblock** [comment]
This is a dup of #693 and there's a PR open in https://github.com/opensearch-project/OpenSearch/pull/814. @ShikiSuen if you have a moment, it would be great if you could test it with XFES?

**Comment by dblock** [comment]
Will close as dup, but please do respond here if #814 is satisfactory.
