### ISSUE TITLE
What's difference between flat_object and ElastiSearch flattened

### ISSUE THREAD

**Issue by brucegaochina** [opensearch-project/OpenSearch#8245]
From the https://opensearch.org/blog/flat-object/ , we can see OpenSearch explore the flat_object. Just confirm that
OpenSearch was forked from ElasticSearch 7.10. As we know ElasticSearch has flattened field type since 7.3.

So I wanna know what's difference between flat_object and ElastiSearch [flattened](https://www.elastic.co/guide/en/elasticsearch/reference/7.3/flattened.html)?

**Comment by andrross** [comment]
@brucegaochina The Elasticsearch feature you're referencing has never been available in an open source distribution (X-Pack). [Flat object](https://opensearch.org/blog/flat-object/) is a new feature in OpenSearch developed under the open source Apache-2.0 license.

**Comment by andrross** [comment]
I'm going to close this, but please do reopen if you have more questions or concerns. Also, please do check out the [forum](https://forum.opensearch.org/) and the [Slack](https://opensearch.org/slack.html) which are great places to ask these types of questions.

**Comment by brucegaochina** [comment]
@andrross  Thanks for your reply. Got it!
