### ISSUE TITLE
 Access to Thread dumps for 

### ISSUE THREAD

**Issue by Astro1295** [opensearch-project/OpenSearch#8252]
We are actually investigating in some 429 errors (search threadpool queue exhaustion) on his main Elasticsearch (7.10) cluster. In order to better understand what he have in those threadpools during incidents, he would like to have access to the thread dump of the thread pool at the moment of the incident.

This feature is available on Elastic Cloud but not Opensearch through cli/api. We would like to have this feature because it's very important for our investigation during incident. 

Thank you

**Comment by andrross** [comment]
> We are actually investigating in some 429 errors (search threadpool queue exhaustion) on his main Elasticsearch (7.10) cluster

Trying to read between the lines here, but are you referring to Elasticsearch 7.10 hosted by AWS using Amazon OpenSearch Service? If so, you should contact AWS support for help. This repository is for the development of open source OpenSearch. If you're asking for a new feature or capability of OpenSearch, then this is the right place!

**Comment by dblock** [comment]
I'll close this. @Astro1295 please do reopen if you believe your problem is with OpenSearch software itself.
