### ISSUE TITLE
Adding roles to other roles and have rolemappings refreshed automatically accordingly 

### ISSUE THREAD

**Issue by asfoorial** [opensearch-project/OpenSearch#830]
Need to enable adding roles to other roles so that the role mapping of the containing role will be updated automatically to have all (direct and in-direct) users in the sub-roles.

Example: Below is an example with two roles
Role Name: all_employees
Role mapping: user1, user2

Role Name: engineers
Role mapping: user3, user4

After adding engineers to all_employees then the role mapping of all_employees become (user1, user2, user3, user4.

Removing engineers from all_employees will also result in removing (user3, user4) from the role mapping of all_employees.

**Comment by setiah** [comment]
Hi @asfoorial - This seems related to security plugin. Can you please re-open this issue - https://github.com/opensearch-project/security and close this?
Thanks!

**Comment by asfoorial** [comment]
Moved to Opensearch Security
