### ISSUE TITLE
[BUG] Publish snapshots to maven GA workflow frequently fails

### ISSUE THREAD

**Issue by reta** [opensearch-project/OpenSearch#8353]
**Describe the bug**
`Publish snapshots to maven` GA workflow fails most of the time with:

```
Run aws-actions/configure-aws-credentials@v1
Error: OpenIDConnect provider's HTTPS certificate doesn't match configured thumbprint
```

**To Reproduce**
See please https://github.com/opensearch-project/OpenSearch/actions/workflows/publish-maven-snapshots.yml

**Expected behavior**

**Plugins**
N/A

**Screenshots**

**Host/Environment (please complete the following information):**
 - GA

**Additional context**
https://github.com/opensearch-project/OpenSearch/actions/workflows/publish-maven-snapshots.yml

**Comment by reta** [comment]
@gaiksaya could you please help with this one? thank you

**Comment by gaiksaya** [comment]
Looks like the failures are random. Will check the thumbprint.

**Comment by gaiksaya** [comment]
This should be fixed now. 

I tried triggering maven workflow: https://github.com/opensearch-project/OpenSearch/actions/runs/5415304972
But GitHub itself is having issues: https://www.githubstatus.com/

**Comment by gaiksaya** [comment]
It worked: https://github.com/opensearch-project/OpenSearch/actions/runs/5415304972/jobs/9843503866

Thanks!

**Comment by reta** [comment]
thanks a lot @gaiksaya !
