### ISSUE TITLE
[Meta] Validate plugins compatibility with Remote Store

### ISSUE THREAD

**Issue by nandi-github** [opensearch-project/OpenSearch#8383]
**Describe the bug**
Ensure all plugins are compatible with Remote Store.

A simipler issues is created for Compatibility with Segment Replication. You can follow that for details
https://github.com/opensearch-project/OpenSearch/issues/8211

**To Reproduce**

**Expected behavior**

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**

**Comment by anasalkouz** [comment]
Closing this since it's duplicate of https://github.com/opensearch-project/OpenSearch/issues/8211
