### ISSUE TITLE
[BUG] no access to my dedicated index in RC

### ISSUE THREAD

**Issue by drBenway** [opensearch-project/OpenSearch#844]
**Describe the bug**
I want to create an index that is only visible to a dedicated user. This seems to work in the Dev Tools but the index doesnt show up in the discover view

**To Reproduce**
// create an index

```
PUT /bank-index/_doc/1 
{
  "type": "deposit",
  "amout": 200
}
```

```
PUT bank-index/_doc/2
{
    "type" : "transfer",
    "amout" : 100
}
```

// check the content

```
GET _mget
{
  "docs": [
    {
      "_index": "bank-index",
      "_id": "1"
    },
    {
      "_index": "bank-index",
      "_id": "2"
    }
  ]
}
```

=> result

```
{
  "docs" : [
    {
      "_index" : "bank-index",
      "_type" : "_doc",
      "_id" : "1",
      "_version" : 2,
      "_seq_no" : 2,
      "_primary_term" : 1,
      "found" : true,
      "_source" : {
        "type" : "deposit",
        "amout" : 200
      }
    },
    {
      "_index" : "bank-index",
      "_type" : "_doc",
      "_id" : "2",
      "_version" : 2,
      "_seq_no" : 3,
      "_primary_term" : 1,
      "found" : true,
      "_source" : {
        "type" : "transfer",
        "amout" : 100
      }
    }
  ]
}

```

// create a role

```
PUT _plugins/_security/api/roles/banker
{
   "cluster_permissions" : [
      "indices_all",
      "indices:data/read/search",
      "indices:admin/aliases/get"
    ],
  "index_permissions": [{
    "index_patterns": [
      "bank-*"
    ],
    "dls": "",
    "fls": [],
    "masked_fields": [],
    "allowed_actions": [
      "read"
    ]
  }]
}
```

=> result

```
{
  "status" : "CREATED",
  "message" : "'banker' created."
}
```

// create user

```
PUT _plugins/_security/api/internalusers/banker-tom
{
  "password": "TheHumanHasBeenNeutralized"
}

```
// add rolemapping

```
PUT _plugins/_security/api/rolesmapping/banker
{
  "users" : [ "banker-tom" ]
}
```

=> result
```
{
  "status" : "OK",
  "message" : "'banker' updated."
}
```

Result in the logs when going to http://localhost:5601/app/discover# :

opensearch-node1         | [2021-06-14T14:16:07,956][INFO ][o.o.s.p.PrivilegesEvaluator] [opensearch-node1] No permissions for [indices:data/read/search]
opensearch-dashboards    | {"type":"log","@timestamp":"2021-06-14T14:16:07Z","tags":["error","opensearch","data"],"pid":1,"message":"[security_exception]: no permissions for [indices:data/read/search] and User [name=banker-tom, backend_roles=[], requestedTenant=__user__]"}
opensearch-dashboards    | {"type":"response","@timestamp":"2021-06-14T14:16:07Z","tags":[],"pid":1,"method":"get","statusCode":403,"req":{"url":"/api/saved_objects/_find?fields=title&per_page=10000&type=index-pattern","method":"get","headers":{"host":"localhost:5601","user-agent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:89.0) Gecko/20100101 Firefox/89.0","accept":"*/*","accept-language":"en-US,en;q=0.5","accept-encoding":"gzip, deflate","referer":"http://localhost:5601/app/discover","content-type":"application/json","osd-version":"1.0.0-rc1","dnt":"1","connection":"keep-alive","securitytenant":"__user__"},"remoteAddress":"172.24.0.1","userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:89.0) Gecko/20100101 Firefox/89.0","referer":"http://localhost:5601/app/discover"},"res":{"statusCode":403,"responseTime":7,"contentLength":9},"message":"GET /api/saved_objects/_find?fields=title&per_page=10000&type=index-pattern 403 7ms - 9.0B"}

**Expected behavior**
See the bank-index in the discover view

**Plugins**
all the once in the default docker compose file for the RC

**Screenshots**

1. Empty discover view
![banker-tom-likes-to-discover](https://user-images.githubusercontent.com/1155682/121913329-97df0880-cd31-11eb-90c3-0638d709ba39.png)

2. banker-tom can query via the Dev tools
![banker-tom-get](https://user-images.githubusercontent.com/1155682/121913356-9f9ead00-cd31-11eb-9d57-cdd7a6338387.png)

3. In the admin view I have the settings below

![admin-banker-mapped-user](https://user-images.githubusercontent.com/1155682/121913492-bcd37b80-cd31-11eb-80c4-308b989ceb28.png)

![admin-internal-user-banker-tom](https://user-images.githubusercontent.com/1155682/121913502-bf35d580-cd31-11eb-8e53-1db3c330aaad.png)

![admin-role-banker-tom](https://user-images.githubusercontent.com/1155682/121913469-b6dd9a80-cd31-11eb-9f44-f47c90fdcaec.png)

**Host/Environment (please complete the following information):**
 - OS: Linux mint 21
 - Docker version 20.10.7, build f0df350

**Comment by drBenway** [comment]
Ticket can be closed, I got it working after I found an example in the docs.
[https://docs-beta.opensearch.org/security-plugin/access-control/users-roles/#sample-roles](https://docs-beta.opensearch.org/security-plugin/access-control/users-roles/#sample-roles)

Mapping the "banker" role and the internal " kibana_user" role to banker-tom fixed the issue.
The "kibana_read_only" made only the dashboard show up.

**Comment by CEHENKLE** [comment]
Thanks, @drBenway :)
