### ISSUE TITLE
[BUG] [Remote Store + Segment Replication] Discrepancy between main and 2.x branch of Flush() method causing test failures.

### ISSUE THREAD

**Issue by Rishikesh1159** [opensearch-project/OpenSearch#8443]
**Describe the bug**
The issue starts with this PR:https://github.com/opensearch-project/OpenSearch/pull/8281, This is a backport PR that successfully passed and merged on main but fails for [testPressureServiceStats](https://build.ci.opensearch.org/job/gradle-check/18675/) on 2.x branch.
The test class [SegmentReplicationRemoteStoreIT](https://github.com/opensearch-project/OpenSearch/blob/2e5195bbf0a1053dfd3647dd22071e1c385eb166/server/src/internalClusterTest/java/org/opensearch/remotestore/SegmentReplicationRemoteStoreIT.java#L31) fails on [Flush()](https://github.com/opensearch-project/OpenSearch/blob/2e5195bbf0a1053dfd3647dd22071e1c385eb166/server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java#L866).

**Reason for test Failure on 2.x:**
Test class [SegmentReplicationRemoteStoreIT](https://github.com/opensearch-project/OpenSearch/blob/2e5195bbf0a1053dfd3647dd22071e1c385eb166/server/src/internalClusterTest/java/org/opensearch/remotestore/SegmentReplicationRemoteStoreIT.java#L31) fails on [testPressureServiceStats()](https://github.com/opensearch-project/OpenSearch/blob/2e5195bbf0a1053dfd3647dd22071e1c385eb166/server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java#L866) when flush() is called. When [Flush()](https://github.com/opensearch-project/OpenSearch/blob/2e5195bbf0a1053dfd3647dd22071e1c385eb166/server/src/main/java/org/opensearch/index/engine/InternalEngine.java#L1923) is called on InternalEngine.java:
Step 1: we ensure translog can flush.
Step 2: Then we call [translogManager.getTranslog().rollGeneration()](https://github.com/opensearch-project/OpenSearch/blob/2e5195bbf0a1053dfd3647dd22071e1c385eb166/server/src/main/java/org/opensearch/index/engine/InternalEngine.java#L1958).
Step 3: Then we refresh.
Step 4: we call [translogManager.trimUnreferencedReaders()](https://github.com/opensearch-project/OpenSearch/blob/2e5195bbf0a1053dfd3647dd22071e1c385eb166/server/src/main/java/org/opensearch/index/engine/InternalEngine.java#L1973), which will further make call to [trimUnreferencedReaders()](https://github.com/opensearch-project/OpenSearch/blob/2e5195bbf0a1053dfd3647dd22071e1c385eb166/server/src/main/java/org/opensearch/index/translog/RemoteFsTranslog.java#L366) in RemoteFsTranslog.java  where we again make a call to
[deleteStaleRemotePrimaryTermsAndMetadataFiles()](https://github.com/opensearch-project/OpenSearch/blob/2e5195bbf0a1053dfd3647dd22071e1c385eb166/server/src/main/java/org/opensearch/index/translog/RemoteFsTranslog.java#L412) w[here](https://github.com/opensearch-project/OpenSearch/blob/2e5195bbf0a1053dfd3647dd22071e1c385eb166/server/src/main/java/org/opensearch/index/translog/RemoteFsTranslog.java#L418) we assert if readers are empty and the assertion fails here
```
java.lang.AssertionError: Expected non-empty readers
	at __randomizedtesting.SeedInfo.seed([3E8142758780CC4C]:0)
	at org.opensearch.index.translog.RemoteFsTranslog.deleteStaleRemotePrimaryTermsAndMetadataFiles(RemoteFsTranslog.java:418)
	at org.opensearch.index.translog.RemoteFsTranslog.trimUnreferencedReaders(RemoteFsTranslog.java:388)
	at org.opensearch.index.translog.InternalTranslogManager.trimUnreferencedReaders(InternalTranslogManager.java:388)
	at org.opensearch.index.engine.InternalEngine.flush(InternalEngine.java:1973)
	at org.opensearch.index.shard.IndexShard.flush(IndexShard.java:1398)
	at org.opensearch.action.admin.indices.flush.TransportShardFlushAction.lambda$shardOperationOnPrimary$1(TransportShardFlushAction.java:110)
	at org.opensearch.action.ActionListener.completeWith(ActionListener.java:342)
	at org.opensearch.action.admin.indices.flush.TransportShardFlushAction.shardOperationOnPrimary(TransportShardFlushAction.java:109)
	at org.opensearch.action.admin.indices.flush.TransportShardFlushAction.shardOperationOnPrimary(TransportShardFlushAction.java:63)
	at org.opensearch.action.support.replication.TransportReplicationAction$PrimaryShardReference.perform(TransportReplicationAction.java:1260)
	at org.opensearch.action.support.replication.ReplicationOperation.execute(ReplicationOperation.java:158)
```
The test fails because we are trying to delete StaleRemotePrimaryTermsAndMetadataFiles when there are no translog readers.

**Reason for test not Failing on main branch:**
When [Flush()](https://github.com/opensearch-project/OpenSearch/blob/2c5a22d167460a0a5d2ad61f16914ca309efe427/server/src/main/java/org/opensearch/index/engine/InternalEngine.java#L1811) method of InternalEngine called:
Step 1: we ensure translog can flush.
Step 2: Then we call [translogManager.rollTranslogGeneration()](https://github.com/opensearch-project/OpenSearch/blob/2c5a22d167460a0a5d2ad61f16914ca309efe427/server/src/main/java/org/opensearch/index/engine/InternalEngine.java#L1846), which internally makes a call to [translog.trimUnreferencedReaders()](https://github.com/opensearch-project/OpenSearch/blob/2c5a22d167460a0a5d2ad61f16914ca309efe427/server/src/main/java/org/opensearch/index/translog/InternalTranslogManager.java#L89C13-L89C48)
Step 3: Then we refresh.
Step 4: Then we call [trimUnreferencedReaders()](https://github.com/opensearch-project/OpenSearch/blob/2c5a22d167460a0a5d2ad61f16914ca309efe427/server/src/main/java/org/opensearch/index/engine/InternalEngine.java#L1861)
The test doesn't fail because trimUnreferencedReaders()  is called twice(and generationsTodelete will be empty) and we never make a call to [deleteStaleRemotePrimaryTermsAndMetadataFiles()](https://github.com/opensearch-project/OpenSearch/blob/2e5195bbf0a1053dfd3647dd22071e1c385eb166/server/src/main/java/org/opensearch/index/translog/RemoteFsTranslog.java#L412) in step 4 as we do in 2.x branch.
The difference in main and 2.x branch is only in step2. Where in 2.x branch we call [translogManager.getTranslog().rollGeneration()](https://github.com/opensearch-project/OpenSearch/blob/2e5195bbf0a1053dfd3647dd22071e1c385eb166/server/src/main/java/org/opensearch/index/engine/InternalEngine.java#L1958) but in main branch we call [translogManager.rollTranslogGeneration()](https://github.com/opensearch-project/OpenSearch/blob/2c5a22d167460a0a5d2ad61f16914ca309efe427/server/src/main/java/org/opensearch/index/engine/InternalEngine.java#L1846)

-> In this PR [#3751](https://github.com/opensearch-project/OpenSearch/pull/3751) of main branch changes made to [flush() method in InternalEngine](https://github.com/opensearch-project/OpenSearch/blob/1d2274045b42e129b8c06748f8185d2431aa5336/server/src/main/java/org/opensearch/index/engine/InternalEngine.java#L1846) of calling translogManager.rollTranslogGeneration()
-> But in 2.x backport of this [PR](https://github.com/opensearch-project/OpenSearch/pull/4095) , we did not backport these changes to [flush() method of InternalEngine](https://github.com/opensearch-project/OpenSearch/blob/c71654444159f643632fbd57588cc00c01b8bb7f/server/src/main/java/org/opensearch/index/engine/InternalEngine.java#L1958). 2.x still has translogManager.getTranslog().rollGeneration()

I am not sure why this change is not backported to 2.x. Might be because author thought it's breaking change or just forgot to include this change in backport.

**To Reproduce**

**Expected behavior**

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**

**Comment by Rishikesh1159** [comment]
Changing `translogManager.getTranslog().rollGeneration()` on 2.x to  `translogManager.rollTranslogGeneration() ` here on [Flush()](https://github.com/opensearch-project/OpenSearch/blob/9b9718fbe71ca4e32b465f876ca635fbc002949b/server/src/main/java/org/opensearch/index/engine/InternalEngine.java#L1958) of InternalEngine or backporting changes made to Flush() of InternalEngine in this PR #3751 would resolve the issue or fix [failing test](https://build.ci.opensearch.org/job/gradle-check/19122/).

@Bukhtawar @satyajitg28 @sachinpkale @mch2, please post your thoughts here if this change can be directly made / backported?

**Comment by Rishikesh1159** [comment]
Got it. Thanks @sachinpkale for confirmation. I will raise a PR that will change all the `translogManager.getTranslog()` occurrences in` InternalEngine` of 2.x branch

**Comment by Bukhtawar** [comment]
LGTM

**Comment by dreamer-89** [comment]
The related PR is merged, so closing this issue.
