### ISSUE TITLE
Remove excessive logging with SegRep using Remote store 

### ISSUE THREAD

**Issue by ankitkala** [opensearch-project/OpenSearch#8452]
For segment replication using remote store, with each refresh, we log the 
1. segment files present on remote store
2. segment files present on local shard
3. segment fails downloaded/skipped

This create a lots of logs per shard per few seconds(with refresh). I think we should keep this enabled while the feature is behind experimental flag. This issue is to track the change to clean up these logs(or move to debug) before GA.

**Comment by dreamer-89** [comment]
PR https://github.com/opensearch-project/OpenSearch/pull/8767  refactors the RemoteStoreReplicationSource and does not call [IndexShard.syncSegmentsFromRemoteSegmentStore](https://github.com/opensearch-project/OpenSearch/blob/57d5e90cd10033eb67e13731728af25ce76f484d/server/src/main/java/org/opensearch/index/shard/IndexShard.java#L4622) anymore which contains the [log statements](https://github.com/opensearch-project/OpenSearch/blob/57d5e90cd10033eb67e13731728af25ce76f484d/server/src/main/java/org/opensearch/index/shard/IndexShard.java#L4800). PR https://github.com/opensearch-project/OpenSearch/pull/8767 relies on replication source to perform this copy operation.
