### ISSUE TITLE
[Search Pipelines] Remove Experimental Flag

### ISSUE THREAD

**Issue by macohen** [opensearch-project/OpenSearch#8489]
I don't think this is the typical process, but I'd like to suggest that in the 2.9 release we update https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/common/util/FeatureFlags.java instead of just removing the feature flag itself. So, we would update:

```
public static final Setting<Boolean> SEARCH_PIPELINE_SETTING = Setting.boolSetting(SEARCH_PIPELINE, false, Property.NodeScope);
```
to 

```
public static final Setting<Boolean> SEARCH_PIPELINE_SETTING = Setting.boolSetting(SEARCH_PIPELINE, true, Property.NodeScope);
```

The advantage is that we minimize change in the first release and then remove the flag in 2.10. Of course, I may not understand how the feature flags work in the first place and we can only remove the flag instead of setting it to true first.

**Comment by macohen** [comment]
cc: @mingshl, @noCharger, @sejli

**Comment by noCharger** [comment]
The AI to fully remove the feature flag:

- [ ] Keep the setting, but make it true by default.
- [ ] Backport that to 2.x
- [ ] Stop enabling the setting for mixed cluster tests (because it is enabled on main and 2.x).
- [ ] Remove the setting.
