### ISSUE TITLE
[Segment Replication + Remote Store] SegRep with N2N with Index level overide should not be allowed to enable Remote store

### ISSUE THREAD

**Issue by nandi-github** [opensearch-project/OpenSearch#8498]
When the cluster is configured with **SegRep with N2N (Node to Node) with index level override** — configuration change should prevent user from enabling Remote Store.

**Describe the solution you'd like**
Upon detecting that the user is trying to enable Remote Store on a cluster with **SegRep with N2N with index level override**, the config should fail and keep the original configuration. The user should be notified of the failure and a proper error message with details should be provided.

Example error message : "Enabling Remote Store on clusters with **SegRep with N2N and index level override** is not allowed"

**Additional context**
This limitation should be documented in our docs.

**Comment by dreamer-89** [comment]
Already part of requirements in https://github.com/opensearch-project/OpenSearch/issues/8497. Closing in favour of https://github.com/opensearch-project/OpenSearch/issues/8497.
