### ISSUE TITLE
Report test coverage

### ISSUE THREAD

**Issue by saratvemulapalli** [opensearch-project/OpenSearch#850]
Report test coverage for all the tests done in OpenSearch.

One of the options include using https://github.com/codecov

**Comment by tlfeng** [comment]
Currently code coverage for specific tests can be obtained through Intellij IDEA when running the test manually.
As far as I know, the biggest obstacle to get code coverage report of Elasticsearch using JaCoCo Gradle plugin that mentioned in [ https://github.com/elastic/elasticsearch/issues/ 28867#issuecomment-372714244 ]
has been resolved in https://github.com/elastic/elasticsearch/commit/2b2a3f5086d4eee2363193c685b74596d159c4b9.
So using JaCoCo Gradle plugin to collect code coverage for unit tests of OpenSearch is possible, however there are still some known issues in using JaCoCo for integration tests.

**Comment by tlfeng** [comment]
There are several sub-projects in the whole repository that don't have tests, which can be found by searching for `test.enabled = false` in the code base.

**Comment by saratvemulapalli** [comment]
This is nice. Couple of questions:

1. How many tests do we have for `forbiddenApisTest`
2. How many and which subprojects do not have `test.enabled = false`

**Comment by tlfeng** [comment]
> How many and which subprojects do not have test.enabled = false

Sorry my above statement was not correct, the sub-projects that disabled `test` task (`test.enabled = false` ) means they don't have unit test, but they may have integration tests.
The sub-projects that don't have unit tests are:
```
':benchmarks'
':rest-api-spec' (but has `yamlRestTest` task)
':client:benchmark'
':client:client-benchmark-noop-api-plugin'
':client:test'
':example-plugins:custom-suggester' (but has `yamlRestTest` task)
':example-plugins:painless-whitelist' (but has `yamlRestTest` task)
':example-plugins:rest-handler' (but has `javaRestTest` and `yamlRestTest` task)
':example-plugins:script-expert-scoring' (but has `yamlRestTest` task)
':libs:opensearch-cli'
':libs:opensearch-plugin-classloader'
':modules:geo' (but has `yamlRestTest` task)
':plugins:discovery-azure-classic' (but has `internalClusterTest` and `yamlRestTest` task)
':plugins:mapper-size' (but has `internalClusterTest` and `yamlRestTest` task)
':qa:die-with-dignity' (but has `javaRestTest` task)
':qa:os'
':qa:wildfly' (but has `integTest` task)
':distribution:tools:java-version-checker'
':modules:lang-painless:spi'
':test:fixtures:azure-fixture'
':test:fixtures:gcs-fixture'
':test:fixtures:hdfs-fixture'
':test:fixtures:old-elasticsearch'
':test:fixtures:s3-fixture'
```

**Comment by tlfeng** [comment]
Created 3 issues to complete the code coverage reporting:
- [ ] #1320 
- [ ] #1323
- [ ] #1324

**Comment by dreamer-89** [comment]
@tlfeng : Thanks for the deep dive and summary of actions to be done. With jenkins still choice of infra; I think we are unblocked on #1320

**Comment by dreamer-89** [comment]
Generated codecov report on local machine and uploaded on server against forked repository. The results shows ~70% code coverage. 

https://app.codecov.io/gh/dreamer-89/OpenSearch/

<img width="1171" alt="Screen Shot 2022-06-14 at 4 06 47 PM" src="https://user-images.githubusercontent.com/79435743/173705045-279667a0-2b73-49c2-a072-0e8a8dd63853.png">

**Comment by peterzhuamazon** [comment]
Hi @dreamer-89 this is complete for now:
* https://github.com/opensearch-project/opensearch-build/issues/2193
