### ISSUE TITLE
Existing indices search stats feature returns SUM aggregation of metrics from the shard level

### ISSUE THREAD

**Issue by AmiStrn** [opensearch-project/OpenSearch#852]
**Describe the bug**
Indices stats API returns the sum of the metrics from the shard level rather than providing the data relevant to each level (indices, cluster).

**To Reproduce**
1. run opensearch `./gradle run`
2. PUT an index with more than one shard:
`curl -XPUT 'localhost:9200/my-index' -H 'Content-Type: application/json' -d '{"settings": {"index":{"number_of_shards":3,"number_of_replicas":2}}}'`
3. add a doc to the index: `curl -XPOST 'localhost:9200/my-index/_doc' -H 'Content-Type: application/json' -d '{"some":"data"}'`
4. Search the index **once**: `curl -XGET 'localhost:9200/my-index/_search' -H 'Content-Type: application/json' -d '{
    "query": {
        "bool": {
            "must": [
                {
                    "query_string": {
                        "query": "data"
                    }
                }]
            }
    }
}'`
Response: 
`{"took":63,"timed_out":false,"_shards":{"total":3,"successful":3,"skipped":0,"failed":0},"hits":{"total":{"value":1,"relation":"eq"},"max_score":0.2876821,"hits":[{"_index":"my-index","_type":"_doc","_id":"mhYVFXoBr1pUiHzSlzbY","_score":0.2876821,"_source":{"some":"data"}}]}}`
5. Retrive indices stats: `curl -XGET 'localhost:9200/my-index/_stats/search'`
Response:
```
{
	"_shards": {
		"total": 9,
		"successful": 3,
		"failed": 0
	},
	"_all": {
		"primaries": {
			"search": {
				"open_contexts": 0,
				"query_total": 3,
				"query_time_in_millis": 26,
				"query_current": 0,
				"fetch_total": 1,
				"fetch_time_in_millis": 9,
				"fetch_current": 0,
				"scroll_total": 0,
				"scroll_time_in_millis": 0,
				"scroll_current": 0,
				"suggest_total": 0,
				"suggest_time_in_millis": 0,
				"suggest_current": 0
			}
		},
		"total": {
			"search": {
				"open_contexts": 0,
				"query_total": 3,
				"query_time_in_millis": 26,
				"query_current": 0,
				"fetch_total": 1,
				"fetch_time_in_millis": 9,
				"fetch_current": 0,
				"scroll_total": 0,
				"scroll_time_in_millis": 0,
				"scroll_current": 0,
				"suggest_total": 0,
				"suggest_time_in_millis": 0,
				"suggest_current": 0
			}
		}
	},
	"indices": {
		"my-index": {
			"uuid": "I7mOMIY9S52D8soWfaYYlA",
			"primaries": {
				"search": {
					"open_contexts": 0,
					"query_total": 3,
					"query_time_in_millis": 26,
					"query_current": 0,
					"fetch_total": 1,
					"fetch_time_in_millis": 9,
					"fetch_current": 0,
					"scroll_total": 0,
					"scroll_time_in_millis": 0,
					"scroll_current": 0,
					"suggest_total": 0,
					"suggest_time_in_millis": 0,
					"suggest_current": 0
				}
			},
			"total": {
				"search": {
					"open_contexts": 0,
					"query_total": 3,
					"query_time_in_millis": 26,
					"query_current": 0,
					"fetch_total": 1,
					"fetch_time_in_millis": 9,
					"fetch_current": 0,
					"scroll_total": 0,
					"scroll_time_in_millis": 0,
					"scroll_current": 0,
					"suggest_total": 0,
					"suggest_time_in_millis": 0,
					"suggest_current": 0
				}
			}
		}
	}
}
```
6. Notice that: 
`"query_total": 3,				
  "query_time_in_millis": 26,`
  This is a SUM of the number of shards queried and the time in each is also summed here. 
  When sending the request with the param `level=shards` you see the breakdown. In this case, each shard had the query_total=1 and the query_time_in_millis were 7, 7, and 12 (different in each shard, the one that took 12 is also the one that had the fetch phase). 
  In bigger clusters the effect also causes the sum to be greater than the `took` field's value of the actual query (making it look like the query took over an hour in some cases with a large number of indices searched and many shards per index).

7. If we add another index `my-other-index` before running step (4): 
`curl -XPUT 'localhost:9200/my-other-index' -H 'Content-Type: application/json' -d '{"settings": {"index":{"number_of_shards":3,"number_of_replicas":2}}}'`
And then run the following:
`curl -XGET 'localhost:9200/my-*/_search' -H 'Content-Type: application/json' -d '{
    "query": {
        "bool": {
            "must": [
                {
                    "query_string": {
                        "query": "data"
                    }
                }]
            }
    }
}'`
And then: `curl -XGET 'localhost:9200/_stats/search'`
We get this response:
```
.
.
.
		"total": {
			"search": {
				"open_contexts": 0,
				"query_total": 6,
				"query_time_in_millis": 34,
.
.
.
```
So even though we searched once, it appears as though we searched 6 times. 
And even though the time the response took to return from the shards was 7 milliseconds, the response shows 34.

**Expected behavior**
I would expect the query_total to be 1 since I only sent the query once on the index level.
I would expect the query_time_in_millis to reflect the amount of time it took for the response to return from the shards. Effectively this would be the _max_ of the query_time_in_millis on the shards level.
**The current state is both misleading and not very useful for monitoring search stats.**

**Host/Environment (please complete the following information):**
 Irrelevant to the bug, as it seems it is a bug by (odd) design
 
**Additional context**
Solving this is the first part of [this issue](https://github.com/opensearch-project/OpenSearch/issues/539)
as seen in [this comment breaking down the feature](https://github.com/opensearch-project/OpenSearch/issues/539#issuecomment-850961488).

**Comment by AmiStrn** [comment]
working on the PR n the meantime:)

**Comment by CEHENKLE** [comment]
Thanks, @AmiStrn :)

**Comment by AmiStrn** [comment]
Solving this issue requires storing stats on the index level separately. The stats are on the shard level only, and they are summed up as described in the issue. However, in some test cases, I have been getting inconsistent results due to the fact that getting the max of the total number of queries is just wrong: 
- Send 1 query to `index-1`
- Send 1 query to `index-2` 
- get stats
the result will say that there was one query sent on the cluster level because when viewing things from the shards level that is the max. We can't differentiate which queries went to which indices when only looking at the shards' stats. 

Another approach may be to leave this as is and only handle the time measurement metrics. However, if one shard causes trouble the max would be stuck at a high max even if this was due to a temporary issue.

A lot to think on here:) back to the drawing board.

**Comment by AmiStrn** [comment]
This issue is not being handled, for now, the main reason being that the way stats are stored in the shard level does not support the use case I was after when opening the issue. 
Since it is stale and may be handled differently in the future I am closing the issue.
