### ISSUE TITLE
Segment Replication - Support realtime reads with GET requests

### ISSUE THREAD

**Issue by mch2** [opensearch-project/OpenSearch#8536]
**Describe the bug**
Today document replication provides the option for "realtime"  reads with the GET API that reads and parses source from the translog to serve strong reads.  This same option should be supported while using segment replication because each shard copy still has the ability to read the translog, however today the NRTReplicationEngine only reads the index when serving GET requests.

**Expected behavior**
GET requests "realtime" option  to be supported with segment replicaiton.

**Comment by mch2** [comment]
Took a closer look at this - WIP https://github.com/mch2/OpenSearch/commit/db72e96ada574197330bef0fb9aee0e0bbb6a28b

To support this on replicas we would need to use a versionMap similar to InternalEngine that tracks a live view of doc uuid to translog location.
There are two issues with this on NRT replicas.
1. LiveVersionMap is built to clear after every refresh because with docrep all refreshed on docs are now searchable in the index.  If the memory footprint of the map gets too large a local refresh will run that clears the map.  We can't do this with SR because we only refresh when a new set of external segments arrives.
2. The map is completely wiped after every refresh and a new one created.  With SR we can't assume all docs in our xlog have arrived with the latest set of segments and would need to preserve up to a certain translog loc/seqNo.

An alternative here is to update any Get req where "realtime" is specified to true to the primary shard in the group.  The problem with this is by default all Get requests have realtime=true enabled, which essentially routes all Get Reqs only to primary shards.

**Comment by Poojita-Raj** [comment]
> Took a closer look at this - WIP [mch2@db72e96](https://github.com/mch2/OpenSearch/commit/db72e96ada574197330bef0fb9aee0e0bbb6a28b)
> 
> To support this on replicas we would need to use a versionMap similar to InternalEngine that tracks a live view of doc uuid to translog location. There are two issues with this on NRT replicas.
> 
>     1. LiveVersionMap is built to clear after every refresh because with docrep all refreshed on docs are now searchable in the index.  If the memory footprint of the map gets too large a local refresh will run that clears the map.  We can't do this with SR because we only refresh when a new set of external segments arrives.  This is similar to why WAIT_UNTIL is not currently supported as a RefreshPolicy during ingest, because refresh listeners will pile up on each shard where no local action can be taken.
> 
>     2. The map is completely wiped after every refresh and a new one created.  With SR we can't assume all docs in our xlog have arrived with the latest set of segments and would need to preserve up to a certain translog loc/seqNo.
> 
> 
> An alternative here is to route any Get req where "realtime" is specified to true to the primary shard in the group. The problem with this is by [default](https://github.com/opensearch-project/OpenSearch/blob/1e08b5a075fa6018be6c0af959b2d638c2743d56/server/src/main/java/org/opensearch/action/get/GetRequest.java#L77) all Get requests have realtime=true enabled, so if we do this all Get reqs would only route to primary shards and can be problematic under heavy load. I think providing this option is a better solution though for sensitive requests and if users are performing a high volume of GET requests then document replication would be a better option.

The alternative scenario is: 
(1) when GET request realtime=true, we route requests to primary shards that will use Internal Engine's existing mechanism to read from translog
and (2) when GET request realtime=false, we continue with existing behavior where it might route to NRTReplicationEngine in which case, it will read from index and not xlog

Issue with this scenario: 
When realtime=true, users can also set the preference parameter for GET requests to "_local" or specific shards. In that case, we need to decide which parameter should take preference to decide where the requests should be routed to.

https://opensearch.org/docs/1.3/api-reference/document-apis/get-documents/
