### ISSUE TITLE
[BUG] Flaky test org.opensearch.index.shard.RemoteStoreRefreshListenerTests.testRefreshSuccessOnThirdAttemptAttempt

### ISSUE THREAD

**Issue by ashking94** [opensearch-project/OpenSearch#8549]
**Describe the bug**
org.opensearch.index.shard.RemoteStoreRefreshListenerTests.testRefreshSuccessOnThirdAttemptAttempt Test is flaky.

**To Reproduce**
Build - https://build.ci.opensearch.org/job/gradle-check/19505/

**Expected behavior**
Test should pass.

**Plugins**
Standard 

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**

**Comment by reta** [comment]
@ashking94  @sachinpkale  The issue is back :(:

```
[org.opensearch.index.shard.RemoteStoreRefreshListenerTests.testRefreshSuccessOnSecondAttempt](https://build.ci.opensearch.org/job/gradle-check/19883/testReport/junit/org.opensearch.index.shard/RemoteStoreRefreshListenerTests/testRefreshSuccessOnSecondAttempt/)
[org.opensearch.index.shard.RemoteStoreRefreshListenerTests.testRefreshSuccessOnThirdAttempt](https://build.ci.opensearch.org/job/gradle-check/19883/testReport/junit/org.opensearch.index.shard/RemoteStoreRefreshListenerTests/testRefreshSuccessOnThirdAttempt/)
```

[1] https://build.ci.opensearch.org/job/gradle-check/19883/
[2] https://build.ci.opensearch.org/job/gradle-check/19884

**Comment by ashking94** [comment]
@reta The flaky tests encountered earlier has been fixed with https://github.com/opensearch-project/OpenSearch/pull/8550.  The continuous failures coming now have come due to https://github.com/opensearch-project/OpenSearch/pull/7119 as mentioned by @Rishikesh1159.

**Comment by reta** [comment]
Thanks @ashking94 , the cause may change but the issue is sadly back

**Comment by ashking94** [comment]
I am closing this issue and tracking it a new issue as the issue itself is a different one caused on account of retry not being handled correctly in the above mentioned PR.
