### ISSUE TITLE
Add IAM signing to Java REST client

### ISSUE THREAD

**Issue by aetter** [opensearch-project/OpenSearch#855]
**Is your feature request related to a problem? Please describe.**
The Java REST client only supports basic authentication (I believe it's configured in the low-level client). We recently added IAM signing to the [OpenSearch CLI](https://github.com/opensearch-project/opensearch-cli#create-default-profile) and should consider it here, as well.

**Describe the solution you'd like**
When building a new client, have a configuration option for IAM signing and use something similar to the default credential chain (environment variables -> Java system properties -> local credential file), AWS service name (e.g. "es"), and AWS region (e.g. "us-east-1").

**Describe alternatives you've considered**
The [aws-request-signing-apache-interceptor](https://github.com/acm19/aws-request-signing-apache-interceptor) accomplishes this goal in a very clever way, but it's preferable for the client to handle signing rather than an intermediary.

**Comment by setiah** [comment]
If the Java REST client were outside of the OpenSearch, I would have not hesitated to add this as an extension, but adding this support to the core codebase looks a bit concerning to me for below reasons -
1. OpenSearch by itself is not based on IAM auth and having this in client codebase makes little sense. It seems better to keep this as an extension outside of core codebase as it is only applicable for those who use IAM as authentication mechanism.
2. It introduces more third party dependencies in the core, which is *generally* not a good idea.

**Comment by elfisher** [comment]
@setiah since there are multiple mechanisms to authenticate with OpenSearch, would it make sense to do this in an abstracted way? Similar to what is proposed for the logstash-output plugin https://github.com/opensearch-project/logstash-output-opensearch/issues/59
