### ISSUE TITLE
[Tracing Instrumentation] Add instrumentation at Rest Layer

### ISSUE THREAD

**Issue by Gaganjuneja** [opensearch-project/OpenSearch#8552]
**Is your feature request related to a problem? Please describe.**

Now the distributed tracing framework #7543 is available. We need to add the tracing instrumentation at several generic components like Rest Layer, Transport Actions and Task Manager levels. Opening up this issue specifically to address the instrumentation in the Rest layer component for all the incoming requests. If the tracing information is passed from the client as part of the header then we should also be able to use it as a root/parent span.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by dblock** [comment]
@Gaganjuneja can you please put some details in the issue?

**Comment by Gaganjuneja** [comment]
> @Gaganjuneja can you please put some details in the issue?

Thanks @dblock for calling it out. I had just created initially these tasks as place holders and now have updated the description.
