### ISSUE TITLE
[BUG] TracerFactory should return wrapped tracer

### ISSUE THREAD

**Issue by Gaganjuneja** [opensearch-project/OpenSearch#8561]
**Describe the bug**
[As per comment in this PR](https://github.com/opensearch-project/OpenSearch/pull/8408#discussion_r1254404731), we should return the wrapped Tracer from TracerFactory.

**To Reproduce**

**Expected behavior**

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**

**Comment by Gaganjuneja** [comment]
@suranjay Can you please take this up? We can simply write a new implementation of Tracer as a WrappedTracer which can wrap the getTracer() behaviour.

**Comment by suranjay** [comment]
> @suranjay Can you please take this up? We can simply write a new implementation of Tracer as a WrappedTracer which can wrap the getTracer() behaviour.

Sure, on it!
