### ISSUE TITLE
[Repository] Support multi-stream downloads within Repository

### ISSUE THREAD

**Issue by kotwanikunal** [opensearch-project/OpenSearch#8596]
**Is your feature request related to a problem? Please describe.**
- Coming in from #6354 and #6632 
- Multi stream support for the `Repository` interface was proposed as a part of #6354 and a design for multi-stream uploads was introduced as a part of #6632 
- As next steps of the interface improvement, we need to add support for multi-stream downloads as a part of the repository interface

**Describe the solution you'd like**
- Enhance the `Repository` interface to support multiple streams for downloads
- This task focuses on defining the next steps and laying out the plan for adding this support

**Possible tasks**
- [x] #8729 
- [x] Design for the enhanced Repository interface with multi-stream downloads
- [x] Implement the interface with required `InputStream` changes
- [x] Add support for all/any Repository implementations within core plugins (Azure/GCP/S3)
- [x] #10105 
- [x] #9784 
- [x] #10106
- [ ] #10107
- [x] #10108
- [x] #10282
- [x] #10283

**Comment by anasalkouz** [comment]
@kotwanikunal Do we need a documentation issue for this feature? anything setting/config that need to be documented?

**Comment by kotwanikunal** [comment]
> @kotwanikunal Do we need a documentation issue for this feature? anything setting/config that need to be documented?

As per the current design, we do not expose anything to the users. I will add in a documentation task if something changes.
