### ISSUE TITLE
[BUG] Opensearch 1.0.0 Alpha version  does'nt  work  with Curator

### ISSUE THREAD

**Issue by anish-adrot** [opensearch-project/OpenSearch#864]
**Describe the bug**
If curator is installed by setting disable_action:false ,then curator pod failed to start.This  is  due  to Opensearch version  incompactability

**To Reproduce**
Install  Opensearch  and  Curator [i.e setting disable_action:false] in  a  container
Check  Curator  pods .
It throws error in curator pods.

**Expected behavior**
Pods should be  up and running successfully

**Error**
{"@timestamp": "2021-06-02T15:35:11.576Z", "function": "do_version_check", "linenum": 926, "loglevel": "ERROR", "message": "Opensearch version 1.0.0 incompatible with this version of Curator (5.8.4)", "name": "curator.utils"}
{"@timestamp": "2021-06-02T15:35:11.576Z", "function": "do_version_check", "linenum": 927, "loglevel": "CRITICAL", "message": "Curator cannot continue due to version incompatibilites. Exiting", "name": "curator.utils"}

** Questions**
will Opensearch  works  with  curator 3PP's ?
Is there any alternate  3PP's  planned to  release by Opensearch in terms of curator.

**Comment by dblock** [comment]
Yes, with a backwards compatibility cluster setting, see https://github.com/opensearch-project/OpenSearch/pull/847 and https://opensearch.org/faq/#c3 for more general questions. 

@anish-adrot Care to open an issue on Curator, please, to add future OpenSearch support and link it here? If it does client-side version checks it can check `distribution=opensearch` and version 1.0 moving forward.

**Comment by nknize** [comment]
Any update on this?

**Comment by dblock** [comment]
I am going to close this, I expect [curator](https://github.com/elastic/curator) to work with OpenSearch 1.0 in [backwards compatibility mode](https://opensearch.org/docs/clients/agents-and-ingestion-tools/index/).
