### ISSUE TITLE
[BUG] Get tasks action does not refresh resource stats

### ISSUE THREAD

**Issue by jed326** [opensearch-project/OpenSearch#8655]
**Describe the bug**
Task resource usage stats are currently refreshed in 2 places:
1. In the List Tasks action https://github.com/opensearch-project/OpenSearch/blob/7dddb3105999d47c3f7dc6e5e16dac2c3821af95/server/src/main/java/org/opensearch/action/admin/cluster/node/tasks/list/TransportListTasksAction.java#L119
2. By the `SearchBackpressureService` https://github.com/opensearch-project/OpenSearch/blob/7dddb3105999d47c3f7dc6e5e16dac2c3821af95/server/src/main/java/org/opensearch/search/backpressure/SearchBackpressureService.java#L175-L176

However, this is not done in the get tasks action: https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/action/admin/cluster/node/tasks/get/TransportGetTaskAction.java

This means that if search backpressure is disabled, a user will not see any updates to the resource stats when only calling the get tasks API.

**Expected behavior**
Get tasks API should also update task resource usage stats.

**Comment by gaobinlong** [comment]
I've opened a [PR](https://github.com/opensearch-project/OpenSearch/pull/11531) for this bug, could anyone help to review?
