### ISSUE TITLE
Need FIPS 140-2 compliance mode in OpenSearch

### ISSUE THREAD

**Issue by nilanshakya** [opensearch-project/OpenSearch#867]
I don't see any way on the security plugin to enable FIPS 140-2 mode in OpenSearch. Is there a plan to support this feature?

**Comment by setiah** [comment]
This seems a duplicate for https://github.com/opensearch-project/security/issues/593. Please reopen under [security repo](https://github.com/opensearch-project/security) if you think this is different.
