### ISSUE TITLE
[Remote Store] Adding testing for relocation of primary

### ISSUE THREAD

**Issue by Poojita-Raj** [opensearch-project/OpenSearch#8672]
**Describe the bug**
While working on removing commits when remote store is enabled, needed to check if changes were affecting primary relocation. However, this situation is not covered by existing tests of the remote store. Need to add in tests for this with segment replication enabled. 

**Expected behavior**
As a starting point, we can extend the SegmentReplicationRelocationIT and run these tests with remote store enabled. This would be similar to what we have now with SegmentReplicationUsingRemoteStoreIT.
May require more testing.

**Comment by gbbafna** [comment]
Merged PR : https://github.com/opensearch-project/OpenSearch/pull/8578
