### ISSUE TITLE
two log4j2.properties instead of one for docker build

### ISSUE THREAD

**Issue by rursprung** [opensearch-project/OpenSearch#868]
for the docker build there are currently two separate `log4j2.properties` files in the repo:
* [distribution/docker/src/docker/config/log4j2.properties](https://github.com/opensearch-project/OpenSearch/blob/6018a5d6d3d4aa9e5fa9dd249edaf494c1fa1884/distribution/docker/src/docker/config/log4j2.properties)
* [distribution/docker/src/docker/config/oss/log4j2.properties](https://github.com/opensearch-project/OpenSearch/blob/6018a5d6d3d4aa9e5fa9dd249edaf494c1fa1884/distribution/docker/src/docker/config/oss/log4j2.properties)

i'm not quite sure how this will be resolved since a cursory look at the `build.gradle` hasn't shown which file gets picked - it seems to copy the whole `config` folder:
https://github.com/opensearch-project/OpenSearch/blob/6018a5d6d3d4aa9e5fa9dd249edaf494c1fa1884/distribution/docker/build.gradle#L102-L104

but based on the content i would presume that `config/oss/log4j2.properties` is the "correct" one while `config/log4j2.properties` contains some additional x-pack specifics which aren't relevant for OpenSearch anymore?

presumably one could move `config/oss/log4j2.properties` to `config/log4j2.properties` and accordingly overwrite the original `config/log4j2.properties` file and delete the `config/oss` folder, but i haven't tested this. but i'm not sure where the logic is which so far in some cases accessed the `oss` folder (maybe this had already been removed with the x-pack removal?).

**Comment by rursprung** [comment]
just found the relevant commit in elasticsearch which removed the OSS code there which also shows how the gradle build handled it before: https://github.com/elastic/elasticsearch/commit/a329677d4a3dca10a1d485157715096fd2869db5
so it seems that indeed this gradle code has also been removed here in opensearch already and probably currently the wrong file is being used

**Comment by adnapibar** [comment]
@rursprung Thanks for pointing this out. Yes, you're right that the wrong `log4j2.properties` is currently used while creating the image. And the fix is also just as you've mentioned in the description. Do you want to send a PR for this? If not, I can create one.

**Comment by rursprung** [comment]
i've created a PR: #878 but please see my notes there about myself not having tested it...
