### ISSUE TITLE
[DISCUSS] Replica's logic for replication failure incase remote store is empty

### ISSUE THREAD

**Issue by ankitkala** [opensearch-project/OpenSearch#8681]
For remote store enabled, we're relying on remote store data for replication and recovery. 
For a shard recovering from remote store(during initialisation or relocation), if the remote store doesn't have any data(no metadata file), there isn't a way to identify if its an acceptable state or a catastrophic failure(primary hasn't refreshed yet v/s uploads from primary are failing due to a bug).

To get around this, we've added check in SegRep path to be noop in such cases only if shard is not in active state. In other cases, it'll simply fail the replication. And if it is during recovery, it'll lead to shard recovery failure. 

However there can a scenario where a recovering replica shard would ignore the replication event if the metadata file is null. Even though this case shouldn't happen.

Ideally replica shouldn't have to worry about primary shard failing to upload data to remote store. But wanted to open this issue for discussing how the replica's behaviour in such cases.

**Comment by mch2** [comment]
I wouldn't expect the replica to know if there is an issue on the primary, only that it would eventually result in backpressure mechanisms getting applied and if reached the replicas falling stale/failed.

How does the primary currently handle upload failures?  Does it retry / apply pressure in the event of retry?  What if we know these are unrecoverable without user intervention? For example the repo does not exist?  IMO if it is an issue local to the primary & not cluster wide (primary store corruption?) we can fail the primary to force promotion of a non corrupt replica from store.

The issue you link I was referring specifically to primary-primary relocation to a new shard where a replica copy does not exist. In this case the new primary is not yet started.  If it cannot sync with the remote store for the latest segments I wouldn't want the handoff to proceed.
