### ISSUE TITLE
Marking files with licensing information

### ISSUE THREAD

**Issue by CEHENKLE** [opensearch-project/OpenSearch#87]
To make sure we're being fully transparent about the licensing, we want to mark all the files in repo with  the correct licensing attribution.

To do this, we want to go through the code base and ensure that each source code file is clearly marked with the licensing (and copyright attribution) in comment headers at the top using SPDX (https://spdx.github.io/spdx-spec/appendix-V-using-SPDX-short-identifiers-in-source-files/)

Any file that does not already have an attribution, add:

SPDX-License-Identifier:  Apache-2.0

If you find any files that have attribution other than apache-2.0, please flag them.

**Comment by adnapibar** [comment]
@CEHENKLE Can this be closed  (Resolved by #510) ?

**Comment by tlfeng** [comment]
I think this can be closed, as mentioned above #510 updated the header for new files, #437 updated the "gradle precommit check" to make sure all files have got SPDX license header, and #509 update the license header for all existing files in the code base.
