### ISSUE TITLE
[Opensearch 1.0.0-rc1] SqlJet  Library reports  a  GPL-2.0-only/ GPL-3.0-only License  issue  during fossa Scan

### ISSUE THREAD

**Issue by anish-adrot** [opensearch-project/OpenSearch#874]
While  performing  the  fossa scanning  for  Opensearch 1.0.0-rc1 , it  reports  couple  of  Flagged Dependencies in SqlJet Library under  GPL-2.0-only/GPL-3.0-only License.
As we know GPL License are copy-left license.will there  be any  impact  due to this .
If yes ,How to  move forward  regarding the issue .

Attachment 
[fossa.opensearch.report.zip](https://github.com/opensearch-project/OpenSearch/files/6702088/fossa.opensearch.report.zip)

**Comment by dblock** [comment]
I can't find any references to SqlJet, @anish-adrot is there any more info? Where is this coming from?

**Comment by anish-adrot** [comment]
SqlJet was  used  in  build tools  dependency  for  opensearch.we  have  removed it  and  did  our  scanning .because  is  was  not included in opensearch application. Now  the scans are fine without  any flagged dependency
Thanks for your response

**Comment by dblock** [comment]
Thanks. I'll close this. @anish-adrot what do you use to do fossa scanning?

We have some tools that do similar things that we're using right now internally at Amazon, but they aren't exposed publicly. I'd like to expose the tools or publish results from those tools to avoid duplicate efforts out there. It would be helpful to understand what your requirements are and what you do today in a new issue in https://github.com/opensearch-project/opensearch-build and we could try and work backwards from there?
