### ISSUE TITLE
[BUG] Unexpected json key in nodes stats

### ISSUE THREAD

**Issue by Jakob3xD** [opensearch-project/OpenSearch#8744]
**Describe the bug**
The `_nodes/stats/jvm` endpoint returns an unexpected json key containing spaces and single quotes `mapped - 'non-volatile memory'` causing issues with golang when encoding/marshal back to json. 

**To Reproduce**
I could not find a reproduction for this issue and I am also not sure where to start.
It did not show up in my current staging setup with 3 nodes but no load. It is always present with our production cluster having some load.
More over it is listed in the [docs](https://opensearch.org/docs/latest/api-reference/nodes-apis/nodes-stats/#example-response).

**Expected behavior**
I would expect a json key with at least not single quotes but even better no spaces. 

**Plugins**
opensearch-alerting                  2.7.0.0
opensearch-anomaly-detection         2.7.0.0
opensearch-asynchronous-search       2.7.0.0
opensearch-cross-cluster-replication 2.7.0.0
opensearch-geospatial                2.7.0.0
opensearch-index-management          2.7.0.0
opensearch-job-scheduler             2.7.0.0
opensearch-knn                       2.7.0.0
opensearch-ml                        2.7.0.0
opensearch-neural-search             2.7.0.0
opensearch-notifications             2.7.0.0
opensearch-notifications-core        2.7.0.0
opensearch-observability             2.7.0.0
opensearch-reports-scheduler         2.7.0.0
opensearch-security                  2.7.0.0
opensearch-security-analytics        2.7.0.0
opensearch-sql                       2.7.0.0
prometheus-exporter                  2.7.0.0
repository-s3                        2.7.0

**Screenshots**

**Host/Environment (please complete the following information):**
 - OS: Docker on Ubuntu
 - Version: 22.04

**Comment by andrross** [comment]
>  I would expect a json key with at least not single quotes but even better no spaces.

@Jakob3xD I believe `mapped - 'non-volatile memory'` is valid JSON. What makes you think that is not valid? As @dreamer-89 mentioned, this is an expected field per the documentation.

**Comment by andrross** [comment]
`mapped - 'non-volatile memory'` is the literal name of the buffer pool as reported by the JVM that was added in https://openjdk.org/jeps/352. I would lean towards finding a way to handle this on the client side as opposed to adding logic to rename things reported by the JVM. What are the options in the opensearch-go client to properly handle this text?

**Comment by dblock** [comment]
As much as I dislike the cosmetics of quotes, the right fix is to fix the client to parse valid JSON :(

**Comment by Jakob3xD** [comment]
:(
> is there an issue in the go parser for the quote problem?

It is not directly about quote but more general https://github.com/golang/go/issues/22518

I'll workaround it by making it a map and not parsing/encoding the key directly.

**Comment by dblock** [comment]
@Jakob3xD is there an alternative json parser that complies to spec in golang?

**Comment by andrross** [comment]
@Jakob3xD I think the client will need to be quite flexible for APIs like JVM stats. The service defines the overall structure of the response, but the specific names of some of these entities (which are used as JSON keys), are coming directly from the JVM. That means there could be a pretty wide variation in the specific values observed depending on the operating system and Java distribution that is being used to run OpenSearch.
