### ISSUE TITLE
[BUG] Segment_N file cleanup not happening on replicas for indexes with segrep using remote store replication

### ISSUE THREAD

**Issue by ashking94** [opensearch-project/OpenSearch#8777]
**Describe the bug**
Observed this issue on replica shards where the segment_N file is not getting removed even after the commits (flushes). 

**To Reproduce**
Create index with segment replication using remote store replication. Index docs, refresh, & then flush. On the primary, the segment_N+1 would appear and segment_N would be deleted, but on replica both segment_N and segment_N+1 file shows up. If you repeat the (Index docs, refresh, & then flush), then more and more segment_N files shows up on replica. 

**Expected behavior**
There should be only 1 segment_N file in steady state. 

**Plugins**
Standard

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**

**Comment by Poojita-Raj** [comment]
This is happening due to changes introduced by #8050 which removes replica commits and as a side-effect the cleanup of these files as part of the commit process is being skipped.

**Comment by mch2** [comment]
This will be fixed with https://github.com/opensearch-project/OpenSearch/pull/9111
