### ISSUE TITLE
Provide access to new settings for HyphenationCompoundWordTokenFilter

### ISSUE THREAD

**Issue by MartinDemberger** [opensearch-project/OpenSearch#8796]
**Is your feature request related to a problem? Please describe.**
In Lucene two additional settings for HyphenationCompoundWordTokenFilter are added. They should be available in opensearch

**Describe the solution you'd like**
The new parameters should be supported.

**Describe alternatives you've considered**

**Additional context**
See https://github.com/apache/lucene/issues/9231 which adds the settings.

**Comment by macohen** [comment]
@evankielley are you working on this? I want to assign to you (I see the PR), but I can't until you have participated in the issue itself. thanks.

**Comment by evankielley** [comment]
Hey, yes, sorry, I dropped off a bit while on vacation. You can assign this to me, I think I just need to rebase and get my PR re-reviewed

**Comment by msfroh** [comment]
@hasnain2808, you expressed some interest in working on this, right?

**Comment by hasnain2808** [comment]
Hey
Could you please assign this to me!

**Comment by getsaurabh02** [comment]
We discussed this in the Search community meeting today. @hasnain2808 we hope you are still interested in this.

**Comment by hasnain2808** [comment]
@getsaurabh02 
I will get to this soon!
Is there some deadline for this?

**Comment by getsaurabh02** [comment]
Thanks, @hasnain2808, for opening the PR. There's no strict deadline for this issue, so we can address it once changes are ready at your end.
