### ISSUE TITLE
Remove distribution from main response in compatibility mode

### ISSUE THREAD

**Issue by dblock** [opensearch-project/OpenSearch#880]
**Is your feature request related to a problem? Please describe.**

Coming from https://github.com/opensearch-project/OpenSearch/issues/693#issuecomment-867803575, clients may be confused by the extra "distribution" field when running in compatibility mode.

@nknize says that the `distribution` key-value was [added](https://github.com/opensearch-project/OpenSearch/commit/6e04778d0c8aa33b3360bf6b000f85da93cec650#diff-dd348945320568d6b330e1ae112fb2f2d3906e19c307a9a75fee64bacb59718dR178) as a way of tracking compatibility and "forked" distributions. It's a new field in OpenSearch that legacy clients (forward compatibilty) will not even be aware of so there should be no issue.  Nevertheless, for completeness we could simply not set this field when running in "compatibility" mode so that MainResponse looks exactly like the legacy response.

**Describe the solution you'd like**
Remove the `distribution` field from main response in compat mode.

**Comment by dblock** [comment]
@mch2 are you taking this?

**Comment by mch2** [comment]
Yeah I'll take care of this change.

**Comment by adnapibar** [comment]
Resolved by #898
