### ISSUE TITLE
[BUG]Restore of snapshot from Elasticsearch to Opensearch throwing error

### ISSUE THREAD

**Issue by sivatarunp** [opensearch-project/OpenSearch#8811]
**Describe the bug**
We are trying to take snapshot from Elasticsearch and restore it in opensearch. As per documentation its possible, but when we try to do this, its throwing the below error.
```
{"error":{"root_cause":[{"type":"snapshot_restore_exception","reason":"[shared-repo-5:<snapshot_name>/<id>] cannot restore index [<index_name>] because it cannot be upgraded"}],"type":"snapshot_restore_exception","reason":"[shared-repo-5:<snapshot_name>/<id>] cannot restore index [<index_name>] because it cannot be upgraded","caused_by":{"type":"illegal_state_exception","reason":"The index [[<index_name>/<index_id>]] was created with version [6.8.4] but the minimum compatible version is OpenSearch 1.0.0 (or Elasticsearch 7.0.0). It should be re-indexed in OpenSearch 1.x (or Elasticsearch 7.x) before upgrading to 2.8.0."}},"status":500}
```
As per the above error statement, we need to first reindex the data to 1.x Opensearch or 7.x ES and then restore it in 2.8 Opensearch. We have tried both with 1.x opensearch and 7.x ES but still we are getting the same error.

What is the issue with it? Is the restoration from snapshot taken in 6.8.4 oss Elasticsearch possible in 2.8.0 Opensearch ?

**To Reproduce**
1. Take snapshot of index from 6.8.4 oss Elasticsearch 
2. Restore the snapshot taken in step 1 in opensearch 1.3.2/ Elasticsearch 7.0.0
3. Take snapshot of the index in opensearch 1.3.2/Elasticsearch 7.0.0
4. Restore the snapshot taken in step 3 in opensearch 2.8.0

**Comment by andrross** [comment]
> Is the restoration from snapshot taken in 6.8.4 oss Elasticsearch possible in 2.8.0 Opensearch ?

No, that is not possible. It _is_ possible to restore the 6.8.4 snapshot into OpenSearch 1.x (which you did in step 2). However, you must then [reindex](https://opensearch.org/docs/latest/im-plugin/reindex-data/) the data in OpenSearch 1.x, which will rewrite the OpenSearch and Lucene data in the OpenSearch 1.x format. If you then snapshot that reindexed data, you will be able to restore it in OpenSearch 2.x. Does that make sense?

**Comment by andrross** [comment]
I'm going to close this issue, but please do reopen if you think there is a bug. I also encourage you to join the discussion on [Slack](https://opensearch.org/slack.html) or the [forums](https://forum.opensearch.org/) if you have general questions or need help. Thanks!
