### ISSUE TITLE
insecure permissions set on `/etc/opensearch/` directory?

### ISSUE THREAD

**Issue by artificial-intelligence** [opensearch-project/OpenSearch#8821]
Hi,

there seems to be an error regarding the correct filesystem permissions for opensearch in conjunction with the opensearch security plugin, which runs by default when installing the opensearch provided deb package.

the code sets the bits, afaik here:

https://github.com/opensearch-project/OpenSearch/blob/611ecc2ad50c7e1833e7fe8ef2a6cabeb6028c57/distribution/packages/build.gradle#L216C15-L216C20

but opensearch security plugin, which runs by default in your debian based installs, btw, despite a comment in the code saying it should not be run in production (sic!), complains:

```
[2023-07-21T13:11:54,849][INFO ][o.o.s.OpenSearchSecurityPlugin] [controller3-LAB] Clustername: opensearch
[2023-07-21T13:11:54,857][WARN ][o.o.s.OpenSearchSecurityPlugin] [controller3-LAB] Directory /etc/opensearch has insecure file permissions (should be 0700)
```

see a bugreport we got in the openstack kolla-ansible deployment of opensearch:

https://bugs.launchpad.net/kolla-ansible/+bug/2028376

Logs:

https://paste.opendev.org/show/bC7trEauLd93b9osSQQi/

Permissions on the file system:

https://paste.opendev.org/show/b853xDI5mOLeKwRaGokf/

Am I missing something here?

Thanks for taking a look!

**Comment by dblock** [comment]
@davidlago help sort this out?

**Comment by davidlago** [comment]
@opensearch-project/engineering-effectiveness might be a good first stop to take a look as this has to do (it sounds like) with how we build and bundle.

> despite a comment in the code saying it should not be run in production (sic!)

Which comment are you referring to and how are you running OpenSearch? Just want to make sure... the warnings we usually print out are when a cluster is run with the demo configuration (the ones with the demo certificates etc) as those are well know and thus offer not much in terms of security (see red box warning [here](https://opensearch.org/docs/latest/install-and-configure/install-opensearch/debian/#step-2-optional-test-opensearch)

**Comment by bbarani** [comment]
Adding @peterzhuamazon and @prudhvigodithi to this thread for further analysis.

**Comment by lukas-fichtner** [comment]
any updates on this?

**Comment by minalsha** [comment]
@bbarani , @peterzhuamazon , @prudhvigodithi  can you please share your inputs from your assessment?

**Comment by davidlago** [comment]
@artificial-intelligence the default installation has a set of demo certificates and default settings to get it up and running, but any production installation requires more configuration (updating passwords, providing your certificates etc).

I am not familiar with your use case or how you end up running the artifacts you consume from OpenSearch. Are you not providing your own certificates and changing those default passwords too?

FYI we are starting to invest some cycles into securing the default installation out of the box, https://github.com/opensearch-project/OpenSearch/issues/1618, starting with the default admin passwords (https://github.com/opensearch-project/security/issues/1576).

**Comment by davidlago** [comment]
> still the question remains - if my analysis is correct - why the security plugin and the installation process for opensearch seem to have a desync when it comes to opinions about file system permissions.

Sorry, yes... we have been talking about this "side quest" but the main question is still unanswered. @bbarani / @peterzhuamazon / @prudhvigodithi please make sure this is still on your radar.

**Comment by peterzhuamazon** [comment]
Close this as it is duplicate to opensearch-project/opensearch-build#3815.
