### ISSUE TITLE
[BUG] Multiple UTs in org.opensearch.repositories.blobstore.BlobStoreRepositoryTests are flaky

### ISSUE THREAD

**Issue by ashking94** [opensearch-project/OpenSearch#8834]
**Describe the bug**
Encountered flaky tests in BlobStoreRepositoryTests. Below are the flaky tests -
 - [org.opensearch.repositories.blobstore.BlobStoreRepositoryTests.testRetrieveShallowCopySnapshotCase1](https://build.ci.opensearch.org/job/gradle-check/20753/testReport/junit/org.opensearch.repositories.blobstore/BlobStoreRepositoryTests/testRetrieveShallowCopySnapshotCase1/)
 - [org.opensearch.repositories.blobstore.BlobStoreRepositoryTests.testRetrieveShallowCopySnapshotCase2](https://build.ci.opensearch.org/job/gradle-check/20753/testReport/junit/org.opensearch.repositories.blobstore/BlobStoreRepositoryTests/testRetrieveShallowCopySnapshotCase2/)
 - [org.opensearch.repositories.blobstore.BlobStoreRepositoryTests.testGetRemoteStoreShallowCopyShardMetadata](https://build.ci.opensearch.org/job/gradle-check/20753/testReport/junit/org.opensearch.repositories.blobstore/BlobStoreRepositoryTests/testGetRemoteStoreShallowCopyShardMetadata/)

**To Reproduce**
Check console output in https://build.ci.opensearch.org/job/gradle-check/20753

**Expected behavior**
Tests should pass.

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**

**Comment by ashking94** [comment]
Reproducible on main with -
```
./gradlew ':server:test' --tests "org.opensearch.repositories.blobstore.BlobStoreRepositoryTests.testRetrieveShallowCopySnapshotCase1" -Dtests.seed=F6DEB85546834F2C -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=no-NO -Dtests.timezone=Antarctica/Rothera -Druntime.java=20
```

**Comment by linuxpi** [comment]
Looks like this flakyness is introduced with https://github.com/opensearch-project/OpenSearch/pull/8719

We mandated use of translog enabled remote indices, earlier these tests were just using segment store enabled remote indices
