### ISSUE TITLE
[Concurrent Segment Search] Update search.concurrent.max_slice setting to dynamic cluster setting

### ISSUE THREAD

**Issue by sohami** [opensearch-project/OpenSearch#8870]
**Is your feature request related to a problem? Please describe.**
As part of https://github.com/opensearch-project/OpenSearch/issues/7358 a new static setting `search.concurrent.max_slice` is introduced. This issue is to track updating it to dynamic setting once the lucene change https://github.com/apache/lucene/pull/12374 is available in the OpenSearch

**Describe the solution you'd like**
Making the setting dynamic instead of static

**Describe alternatives you've considered**
N/A

**Additional context**
Related to https://github.com/opensearch-project/OpenSearch/issues/7358

**Comment by jed326** [comment]
Setting was made dynamic as a part of backport PR https://github.com/opensearch-project/OpenSearch/pull/10606
