### ISSUE TITLE
OpenSearch Research

### ISSUE THREAD

**Issue by apasun** [opensearch-project/OpenSearch#8892]
**I need a repo with OpenSearch research and testing

**Describe the solution you'd like**
A new repo for OpenSearch project that hosts developer participation request

**Describe alternatives you've considered**
I current have in product mechanisms to collect data or use the forum

**Additional context**
See open-source survey project. I need host projects similar [to this](https://github.com/github/open-source-survey)

**Comment by ashwin-pc** [comment]
Are you requesting a repo to host a survey or just the results/analysis from the survey? The repo you like does not collect the data, it just allows the use to view/download the survey data.

**Comment by dblock** [comment]
@apasun, happy to help with any new repos, probably best to discuss online or (public) slack rather than here (will ping you), this repo is for core engine issues
