### ISSUE TITLE
[BUG] Custom interceptor not attached to the Remote reindex Rest client

### ISSUE THREAD

**Issue by soosinha** [opensearch-project/OpenSearch#890]
**Describe the bug**
Remote Reindex plugin was extended in PR #547 to be able to add a custom interceptor. But the when adding a custom interceptor, it is not getting attached to the Rest client as the Rest client was initialized before the interceptor was set. This should be fixed by correcting the initialization of Rest client to use the interceptor.

**Additional context**
Follow up on the PR : https://github.com/opensearch-project/OpenSearch/pull/547

**Comment by nknize** [comment]
will merge in 1.0.0 if a CVE PR is needed; otherwise this will be merged in a patch release (1.0.1)

**Comment by minalsha** [comment]
The PRs:https://github.com/opensearch-project/OpenSearch/pull/876 and https://github.com/opensearch-project/OpenSearch/pull/891 has been merged in main and 1.x. hence closing this issue.
