### ISSUE TITLE
[BUG] FileAlreadyExistsException during round of segment replication with remote store

### ISSUE THREAD

**Issue by dreamer-89** [opensearch-project/OpenSearch#8905]
Coming from [comment](https://github.com/opensearch-project/OpenSearch/pull/8767#issuecomment-1652792987) on PR https://github.com/opensearch-project/OpenSearch/pull/8767

While working on https://github.com/opensearch-project/OpenSearch/pull/8767, I see during recovery process (engine not open), the shards are refreshed with incremental refresh points that results in segment files on replica store but without corresponding segment_N file. These files are orphan files and is not a correct state for the shard to be in. Also, as engine is not open, these files does not serve any purpose on store. It is also problematic to handle the [deletion logic](https://github.com/opensearch-project/OpenSearch/blob/b4b25dc0ef845d0f7a45b7db0ab931dcf783c560/server/src/main/java/org/opensearch/index/engine/NRTReplicationEngine.java#L126) as these files do not belong to commit point. The sync method today downloads all missing files onto local store today and does not honour `refreshLevelSegmentSync` flag passed in to`refreshLevelSegmentSync`.  

CC @sachinpkale @ankitkala @ashking94 

---
From PR https://github.com/opensearch-project/OpenSearch/pull/8767

Hit `FileAlreadyExistsException` error condition during round of segment replication in tests with refactoring work in https://github.com/opensearch-project/OpenSearch/pull/8767. The failure happens because replica already containing segment files from remote store syncs during recovery but without corresponding segment_N file (incremental refreshes). [Without commits](https://github.com/opensearch-project/OpenSearch/blob/99f28cb6f6bd73a6d832c6bbb88e5b9c2ccdb139/server/src/main/java/org/opensearch/index/shard/IndexShard.java#L4666) on replica, these files remain on store without corresponding segment_N. Thus, replica's latest segment infos does not include these. During next round of segment replication, while calculating files to catch from primary, replica shard uses it's latest segment infos vs whats on store. Thus, replica request these files again from remote store and during download hits this exception. There are couple of optoins to solve this:

1. During recovery
Skip download of incremental segment files (i.e. without corresponding segment_N file). This safe to do so as replica shard is not yet active to serve traffic.

2. During segment replication
Avoid requesting files which are already present on store. This needs to read local store files and needs special handling to identify missing files and is thus not clean.

Option 1 seems logically right as keeping the replica shard upto a commit point and doesn't have known issues.

**Comment by dreamer-89** [comment]
The sync method today downloads all missing files onto local store today and does not honour refreshLevelSegmentSync flag passed in to [refreshLevelSegmentSync](https://github.com/opensearch-project/OpenSearch/blob/b4b25dc0ef845d0f7a45b7db0ab931dcf783c560/server/src/main/java/org/opensearch/index/shard/IndexShard.java#L4622) method. This task can be splitted into two parts:
1. Consider `refreshLevelSegmentSync` flag for downloading files. When `true` downloads all files (existing logic) and when `false` only download files which are part of last commit point.
2. Update calls to syncSegmentsFromRemoteSegmentStore method and use `refreshLevelSegmentSync` to `false` during recovery for replica shards. We still want to download all files when shard is primary mode.

**Comment by mch2** [comment]
@dreamer-89 +1 to the changes you propose.

On replicas we can't immediately load the in-memory infos onto a reader if the engine is not yet open.  So it would leave unreferenced segments dangling in the store.  Further we want the engine to clear any unreferenced segments on startup. We can rely on the force-sync during recovery to bring the replica to the latest refresh point.

**Comment by dreamer-89** [comment]
This change is not needed immediately as with https://github.com/opensearch-project/OpenSearch/pull/8767, we are continuing to perform commits on replica. Closing this issue
