### ISSUE TITLE
Make repository a first-class citizen for remote store backed cluster

### ISSUE THREAD

**Issue by Bukhtawar** [opensearch-project/OpenSearch#8917]
**Is your feature request related to a problem? Please describe.**
With remote store we need repository to be bootstrapped with the cluster to ensure internal system indices are also durably backed-up. Repositories are traditionally registered into the cluster state by an external API which poses durability risks to the cluster if repositories are mutated in inconsistent ways. 
Also when we need to recover from quorum loss, we shouldn't require to rely on cluster state to fetch the repository information, which might create a cyclic dependency on recovery.
The repository information should sit locally on the nodes and the cluster should be able to bootstrap automatically with a repository being a first class citizen

Relates to #8623 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by mch2** [comment]
related - https://github.com/opensearch-project/OpenSearch/issues/8158

**Comment by sachinpkale** [comment]
@Bukhtawar I believe the change is made related to this issue. Closing it now. Feel free to open if still pending.
