### ISSUE TITLE
[Remote Store] Support enabling remote store directly in OpenSearchIntegTestCase to run Integ Test suite with remote store enabled

### ISSUE THREAD

**Issue by Rishikesh1159** [opensearch-project/OpenSearch#8965]
**Is your feature request related to a problem? Please describe.**
Currently we don't run existing Integ Test suite with remote store enabled. So we need to use existing remote store (FeatureFlags.REMOTE_STORE) feature flag to enable remote store on `OpenSearchIntegTestCase`(parent class for all Integ tests) so that entire Integ test suite can be ran with remote store enabled.

**Describe the solution you'd like**
Our goal here is to run Integ Test suite with remote store enabled. We need to to create a simple way to enable remote store so that we can leverage our CI to run main branch with remote store enabled. We can use existing remote store feature flag to enable remote store and pass it in from gradle command using `-D` flag to enable remote store on `OpenSearchIntegTestCase`.

**Describe alternatives you've considered**
I found existing remote store feature flag to be quick and simple solution for the need here. I am open to other alternatives as well. 

**Additional context**
We expect few test failures when Integ test suite is run with remote store. Our high level goal to create this issue is to capture test failures with remote store enabled.

**Comment by reta** [comment]
@Rishikesh1159 we already have a feature flag for it (FeatureFlags.REMOTE_STORE) and could use the existing test cases for turning it on / off

**Comment by Rishikesh1159** [comment]
Thanks @reta what you said is right. I think we can leverage the existing remote store feature flag for this case as well. I will change the issue description and update the goal of this issue to support enabling remote store directly in `OpenSearchIntegTestCase` by passing feature flag from cmd line.

**Comment by mch2** [comment]
+1 lets not introduce more flags.  I think the change here is that passing the flag will now need to enable all of the settings that the feature flag gates and for remote store specifically will need to register a repository.

**Comment by Rishikesh1159** [comment]
@mch2 what you said makes sense. But I don’t think currently we have a way to pass in cluster settings from cmd line as we can for feature flag

**Comment by neetikasinghal** [comment]
@Rishikesh1159 to solve this problem temporarily for the concurrent search use-case, we are running periodic integration tests for concurrent search with feature flag enabled via github action in order to monitor the tests. You can look into it if you are interested: [link](https://github.com/neetikasinghal/OpenSearch/blob/main/.github/workflows/concurrent-search.yml)

Long term solution is being discussed in https://github.com/opensearch-project/OpenSearch/issues/8673

**Comment by harishbhakuni21** [comment]
@Rishikesh1159 thanks for creating this issue.
but it's a bit unclear what we want to achieve here, we need FeatureFlags.REMOTE_STORE flag because it's an experimental feature right now, once it's GA we would not need this flag anymore. 

Also, to enable remote store feature, just this feature flag is not sufficient, we need to add remote store related settings in index settings as well, as we support doc rep indices as well as remote store enabled indices in the same cluster today.

**Comment by Rishikesh1159** [comment]
Thanks @neetikasinghal for the suggestion here, I like the idea of enabling feature flag via github action.

**Comment by Rishikesh1159** [comment]
> @Rishikesh1159 thanks for creating this issue. but it's a bit unclear what we want to achieve here, we need FeatureFlags.REMOTE_STORE flag because it's an experimental feature right now, once it's GA we would not need this flag anymore.
> 
> Also, to enable remote store feature, just this feature flag is not sufficient, we need to add remote store related settings in index settings as well, as we support doc rep indices as well as remote store enabled indices in the same cluster today.

@harishbhakuni21 yes you are right to enable remote store just enabling feature flag is not suffiecient. We need to set few settings and register a repository. The purpose of this issue is to figure out a way to fully enable remote and run all integTests with it just by passing in feature flag from command line.

The reason we are trying to have a way to enable remote store for integTests from cmd line flag is because we want to have a separte CI running gradle check with remote store enabled. Currently if we enable remote store on gradle check we will see lots of integ tests failures.

Our main goal is to have a place in public to see all integ tests failures with remote store. So we need a CI to run gradle check with remote store enabled to capture all failures and fix them iteratively. To enable remote store settings from CI we need this issue.(Figuring out way to set remote store from cmd line).

We need to have confidence for GA, we need all relevant integ tests passing with remote store enabled. The purpose of doing this excercise (running from CI) is have more confidence (covering edge cases) before GA release.

**Comment by reta** [comment]
> The reason we are trying to have a way to enable remote store for integTests from cmd line flag is because we want to have a separte CI running gradle check with remote store enabled. Currently if we enable remote store on gradle check we will see lots of integ tests failures.

@Rishikesh1159 I think this is not the right way to deal with the problem. First, we should not modify the Github workflows for each and every feature flag (yes, we are talking about REMOTE_STORE here but we could generalize the approach to any feature flag, imagine the similar need in the future). Second, why we cannot open the pull request with feature flag enabled (that would give you the picture which tests are failing) and then address each test suite one by one? You could do this in feature branch or send small incremental pull request to `main` / `2.x` ...
