### ISSUE TITLE
Allow test extending OpenSearchSingleNodeTestCase to configure featureFlagSettings similar to OpenSearchIntegTestCase

### ISSUE THREAD

**Issue by sohami** [opensearch-project/OpenSearch#8969]
**Describe the solution you'd like**
We have featureflags mechanism in the core to control enabling/disabling experimental features and configurations related to it. The tests extending from `OpenSearchIntegTestCase` can [configure these featureFlags](https://github.com/opensearch-project/OpenSearch/blob/main/test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java#L784) whereas it is not available for tests extending `OpenSearchSingleNodeTestCase`. We should add it over there as well.

**Comment by stefano-maglione** [comment]
Hi can I contribute on this?
