### ISSUE TITLE
OpenSearch's Unreliable Dependency - A Call for Enhanced API Compatibility

### ISSUE THREAD

**Issue by peternied** [opensearch-project/OpenSearch#8982]
_This issue aims to shed light on a frustrating experience that is negatively impacting contributors, including myself. The intention is not to shame or punish but rather to address the problem constructively and foster a conversation for a potential solution._

### Describe the bug
OpenSearch's main does not have any requirements for public API compatibility.  This often causes changes on snapshot builds that break compilation of plugins or integration tests of plugins to fail.  This issues are difficult to debug and consumer considerable time on its plugins.

Breaking changes are backported in previous major version numbers, these layers make it hard to know where new issues are coming from.

### To Reproduce
Maintain a plugin that depends on OpenSearch.

### Expected behavior
There are several options:

#### Keep the Status Quo:
- OpenSearch core continues to grow with added functionalities.
- Plugins contribute more functionality into the core codebase to reduce the burden of maintenance.

#### Strictly Follow SemVer:
- OpenSearch adheres to Semantic Versioning, ensuring no public API changes without a major version increment.
- Plugin teams can have operational build pipelines and better control over migration.
- OpenSearch core contributions are more strictly monitored, limiting the introduction of non-essential breaking changes.

#### Increase Verification of Pull Requests:
- OpenSearch pull requests undergo verification against plugins' GitHub Actions checks before merging.
- Plugin teams integrate test suites that are run before pull requests are merged, enabling them to be considered as a blocking consumer.

### Additional context
- Issue impact security plugin https://github.com/opensearch-project/security/issues/3064
- Core refactoring initiative- driving this kind of issue https://github.com/opensearch-project/OpenSearch/issues/5910

**Comment by peternied** [comment]
Recent change:
- https://github.com/opensearch-project/OpenSearch/pull/9006

**Comment by peternied** [comment]
@nknize I know you are at work with refactoring components in core [1], the breaking changes being pushed out to plugin teams are painful.  Is there a quantification of how far along that work is / for how much time plugin teams will have broken builds due to these changes?

- [1] https://github.com/opensearch-project/OpenSearch/issues/5910

**Comment by nknize** [comment]
Hey @peternied. I missed this message before posting [my comment](https://github.com/opensearch-project/OpenSearch/pull/9044#issuecomment-1661109328) on the PR to detect compatibility impact.

 > Is there a quantification of how far along that work is / for how much time plugin teams will have broken builds due to these changes?

I'd like to target Phase 0 of #8110 to be complete no later than 2.11. 

Of course that could slip, however, depending on the downstream surface area impacted once `module-info.java` is added to the core modules. That effort will likely bias towards minimal exports, which means downstreams will be temporarily cut off from some classes they currently extend. We'll take each breakage on a case by case basis and bias towards exporting, but quickly redesigning what needs to be redesigned to properly enforce semver.

**Comment by peternied** [comment]
@nknize Do you know who would be able to help assemble that list of breaking changes that should be expected?

**Comment by peternied** [comment]
Five days ago downstream pull requests [1] were needed to handle the task foundaction refactor [2]    This change was backported today, and presumably will require another set of changes to be backported.

- [1] Follow up pull requests to handle task refactor
  - https://github.com/opensearch-project/ml-commons/pull/1200
  - https://github.com/opensearch-project/security/pull/3153
  - https://github.com/opensearch-project/neural-search/pull/249
  - https://github.com/opensearch-project/ml-commons/pull/1202
  - https://github.com/opensearch-project/job-scheduler/pull/463
  - https://github.com/opensearch-project/sql/pull/1958
  - https://github.com/opensearch-project/k-NN/pull/1038
  - https://github.com/opensearch-project/observability/pull/1590
  - https://github.com/opensearch-project/job-scheduler/pull/467
  - https://github.com/opensearch-project/security-analytics/pull/510
  - https://github.com/opensearch-project/reporting/commit/ce1c03ff9b999493311e5d81955526451ae11471
  - https://github.com/opensearch-project/common-utils/pull/507
  - https://github.com/opensearch-project/anomaly-detection/pull/976
  - https://github.com/opensearch-project/performance-analyzer/pull/522
  - https://github.com/opensearch-project/asynchronous-search/pull/292
- [2] https://github.com/opensearch-project/OpenSearch/pull/9082

**Comment by peternied** [comment]
Capturing this proposal on how we could change the consumption model within OpenSearch Project

> > How does apache foundation handle cases like this?
> 
> It's varies by project. I can only speak for Lucene and Solr (and Elasticsearch, and even OpenSearch). Solr (and Elasticsearch, and OpenSearch core) absorbs upstream changes "on demand" the same way we do it here with Lucene. This is what I have been suggesting for a while. 
> 
> Instead of upstream core OpenSearch repo force feeding per-merge `SNAPSHOT` artifacts to all downstreams, the downstreams should manually (or on some automated, e.g., weekly, cron period) trigger a snapshot build and update their `${opensearch_version}` in `build.gradle` to their own created sha (e.g., `2.10.0-SNAPSHOT-4373c3b`). This would keep downstream builds stable. The unpleasant side affect would depend on how often those snapshots are updated, but that would be under the control of the downstream repo community. It's not perfect (breaking changes never are) but least then the downstream controls their own pain. This happens a lot on Solr, OpenSearch, Elasticsearch when large changes are made to lucene (e.g., JPMS, gradle change from ant, Endianness changes)

https://github.com/opensearch-project/OpenSearch/pull/9367#issuecomment-1679673558

**Comment by nknize** [comment]
Follow up [comment](https://github.com/opensearch-project/OpenSearch/pull/9367#issuecomment-1679703871):

> I wonder if we could invent a "toggle" mechanism to allow downstreams to switch between the two approaches at will? Maybe there's a GHA to enable/disable "force fed" snapshots? This could prove useful during large scale refactors to clot the bleeding? Downstreams cut over to the manual snapshot consumption model, and switch back when the change storm has passed?

**Comment by dblock** [comment]
@peternied I think there are two major shortcomings with this proposal, all while it does solve the problem for plugins to depend on a more stable core. It actually resembles the ODFE state where plugins depended on a previously released version of core, except that every plugin will be able to depend on some random snapshot build. That did not work well.

1. In order to produce a working distribution build all plugins must depend on one specific snapshot build of OpenSearch - so how do you see us having any such build during the development cycle? The opensearch-build distribution builds everything from the top, from source. It cannot work without all plugins being at the same snapshot version, which will become very rare.
2. What will prevent a plugin to simply never integrate with a newer version of core SNAPSHOT until the very last moment? this means that downstream impact of a large change is deferred to the very latest, and closest to release (aka worst) moment. This will likely slip release dates.

**Comment by peternied** [comment]
RE: CompatibilityCheck:
Good news, the compatibility check is using the correct commits for the evaluation, you can confirm by looking at the SHA on the message.
