### ISSUE TITLE
[Segment Replication] Handle failover in mixed cluster mode

### ISSUE THREAD

**Issue by Poojita-Raj** [opensearch-project/OpenSearch#9027]
**Is your feature request related to a problem? Please describe.**
In the event of failover for a segment replication enabled cluster, need to avoid a case where the replica with the highest opensearch version gets promoted to primary. If that happens, the replicas on older opensearch versions will not be able to read the segments sent by this primary. 

**Describe the solution you'd like**
We want to ensure that the replica that's on the oldest opensearch version is promoted to primary in the event of a failover in a segment replication enabled cluster, which would take care of this problem in mixed version clusters. 

**Additional context**
Created as follow up to #8265 
Parent issue: #3881

**Comment by mch2** [comment]
@Poojita-Raj by furthest ahead/behind do you mean OpenSearch version or segments?

**Comment by Poojita-Raj** [comment]
Sorry for the confusion @mch2 - Furthest ahead/behind refers to OpenSearch version. Updated the description accordingly.
