### ISSUE TITLE
[BUG] Test DeletePitMultiNodeIT.testDeleteWhileSearch is flaky

### ISSUE THREAD

**Issue by mch2** [opensearch-project/OpenSearch#9048]
```
REPRODUCE WITH: ./gradlew ':server:internalClusterTest' --tests "org.opensearch.search.pit.DeletePitMultiNodeIT.testDeleteWhileSearch" -Dtests.seed=CE842172B3367A4B -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=es-MX -Dtests.timezone=Europe/London -Druntime.java=20
```

from 
Gradle Check (Jenkins) Run Completed with:
RESULT: UNSTABLE ❕
TEST FAILURES:
      1 org.opensearch.search.pit.DeletePitMultiNodeIT.testDeleteWhileSearch
URL: https://build.ci.opensearch.org/job/gradle-check/21640/
CommitID: https://github.com/opensearch-project/OpenSearch/commit/7d261931a92516ced757da26c22da7c6dbd0758d
Please review all [flaky tests](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#flaky-tests) that succeeded after retry and create an issue if one does not already exist to track the flaky failure.

**Comment by macohen** [comment]
Removed the search label and added indexing to direct this to the right place. 

cc: @anasalkouz

**Comment by peternied** [comment]
Fixed in https://github.com/opensearch-project/OpenSearch/pull/10946
