### ISSUE TITLE
Remove Elastic repo urls from DistributionDownloadPlugin

### ISSUE THREAD

**Issue by setiah** [opensearch-project/OpenSearch#91]
These URLs are used for setting up download service.

```
    private static void setupDownloadServiceRepo(Project project) {
        if (project.getRepositories().findByName(DOWNLOAD_REPO_NAME) != null) {
            return;
        }

        //TODO: remove
        addIvyRepo(project, DOWNLOAD_REPO_NAME, "https://artifacts-no-kpi.elastic.co", FAKE_IVY_GROUP);
        addIvyRepo(project, SNAPSHOT_REPO_NAME, "https://snapshots-no-kpi.elastic.co", FAKE_SNAPSHOT_IVY_GROUP);
    }
```

- [x] Ivy repository for releases
- [ ] Ivy repository for snapshots

**Comment by adnapibar** [comment]
This is resolved by #483 - can this be closed?

**Comment by harold-wang** [comment]
I think we should update addIvyRepo with different endpoint URL for ES and opensearch, right? @saratvemulapalli @adnapibar

**Comment by saratvemulapalli** [comment]
Thats true for backwards compatibility tests we need to point to ES as well.

**Comment by setiah** [comment]
@saratvemulapalli can we close this?

**Comment by saratvemulapalli** [comment]
@setiah I do not think so. We have to update 2 URLs.
1. Ivy repository for Releases. - Done
2. Ivy repository for Snapshots. - Yet to be done.

I've updated the issue to make it easier to understand whats left.

**Comment by dblock** [comment]
Looking at https://github.com/opensearch-project/OpenSearch/blob/59563fbf7236b46a339bd549d18bc598f3a35986/buildSrc/src/main/java/org/opensearch/gradle/DistributionDownloadPlugin.java#L190 I think we're done here. @saratvemulapalli want to confirm and close?

**Comment by saratvemulapalli** [comment]
> Looking at
> 
> https://github.com/opensearch-project/OpenSearch/blob/59563fbf7236b46a339bd549d18bc598f3a35986/buildSrc/src/main/java/org/opensearch/gradle/DistributionDownloadPlugin.java#L190
> 
> I think we're done here. @saratvemulapalli want to confirm and close?

We can definitely close this one as @peterzhuamazon opened up another issue to track snapshot repositories.
#769
