### ISSUE TITLE
[BUG] org.opensearch.remotestore.RemoteStoreIT.testRemoteTranslogRestoreWithNoDataPostRefresh is flaky

### ISSUE THREAD

**Issue by sachinpkale** [opensearch-project/OpenSearch#9185]
**Describe the bug**
`org.opensearch.remotestore.RemoteStoreIT.testRemoteTranslogRestoreWithNoDataPostRefresh` is flaky

**Additional context**
https://build.ci.opensearch.org/job/gradle-check/21299/testReport/junit/org.opensearch.remotestore/RemoteStoreIT/testRemoteTranslogRestoreWithNoDataPostRefresh/

**Comment by sachinpkale** [comment]
Running the test on local for 100+ times did not fail.

Trying with same seed which failed in [Build 1](https://build.ci.opensearch.org/job/gradle-check/21299/testReport/junit/org.opensearch.remotestore/RemoteStoreIT/testRemoteTranslogRestoreWithNoDataPostRefresh/) and [Build 2](https://build.ci.opensearch.org/job/gradle-check/20987/testReport/junit/org.opensearch.remotestore/RemoteStoreIT/testRemoteTranslogRestoreWithNoDataPostRefresh/)

**Comment by reta** [comment]
https://build.ci.opensearch.org/job/gradle-check/32320/testReport/junit/org.opensearch.remotestore/RemoteStoreRestoreIT/testRemoteTranslogRestoreWithNoDataPostRefresh/

**Comment by sachinpkale** [comment]
Not able to reproduce on local even after 2500+ iterations.
