### ISSUE TITLE
[Remote Store] Verify All Integ Tests are Passing with Remote Store Enabled

### ISSUE THREAD

**Issue by Rishikesh1159** [opensearch-project/OpenSearch#9196]
**Describe the bug**
Currently few integ tests fail with remote store enabled. This issue will be used to track all the integ tests failures withremote store enabled.

This issue is being tracked as a sub task and part of meta issue https://github.com/opensearch-project/OpenSearch/issues/6761

Sub Tasks:
   - [x] #9158 

**Expected behavior**
We should have 0 integ tests failing with remote store enabled.

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**

**Comment by sachinpkale** [comment]
@Rishikesh1159 Closing this issue. I will open a new issue where support for integ tests to run with remote store parameter will be discussed.
