### ISSUE TITLE
[BUG] Compatibility check by OpenSearch Trigger Bot SQL reporting issue

### ISSUE THREAD

**Issue by MitchellGale** [opensearch-project/OpenSearch#9235]
**Describe the bug**
OpenSearch SQL plugin incorrectly listed as compatible by `[opensearch-trigger-bot](https://github.com/apps/opensearch-trigger-bot)` from breaking change in https://github.com/opensearch-project/OpenSearch/pull/9082.

OpenSearch SQL Issue:
https://github.com/opensearch-project/sql/issues/1953

**Expected behavior**
SQL should be reported as `incompatible`.

**Plugins**
SQL

**Comment by peternied** [comment]
This also impacted the security plugin, unclear what happened / didn't happen.  Found the task execution, but wasn't much help https://github.com/opensearch-project/OpenSearch/actions/runs/5813855301/job/15762293745
- https://github.com/opensearch-project/security/issues/3151

**Comment by peternied** [comment]
@MitchellGale Want to take a look at #9280 and see if there is anything else that should be added to make it clearer what went wrong?

**Comment by peternied** [comment]
There was an issue with the wrong version of the change being used for the compatibility check that has been fixed by [1].  Please reopen if this occurs again.

- [1] https://github.com/opensearch-project/OpenSearch/pull/9374
