### ISSUE TITLE
[BUG] OpenSearch does not build in ARM environments

### ISSUE THREAD

**Issue by peternied** [opensearch-project/OpenSearch#925]
**Describe the bug**
Unable to build OpenSearch in in ARM environments due to an architecture string conversion bug, `==` should be replaced with `.equals(...)`

**To Reproduce**
1. Clone OpenSearch repo onto a ARM (AARCH64) environment
2. Try to build
3. See error

```
unknown architecture [arm64] for jdk [provisioned_runtime], must be one of [aarch64, x64]
```

**Expected behavior**
The environment should be recognized as aarch64, code defect is in [../gradle/Jdk.java](https://github.com/peternied/OpenSearch-1/blob/bd9ca7cce55cf31dfdfab4ed65f7c719136963c0/buildSrc/src/main/java/org/opensearch/gradle/Jdk.java#L237)

**Plugins**
Please list all plugins currently enabled.

**Host/Environment (please complete the following information):**
 - OS: Amazon Linux 2 - Arm

**Comment by peternied** [comment]
Fixed in main #809

**Comment by peternied** [comment]
Backporting the fix to v1.0.0 with #917

**Comment by tlfeng** [comment]
Hi Peter, when you get a chance, could you create PR to backport the fix to `1.x` branch? (Otherwise I think we can help you. 😉)
We just decided to create PR to `1.x` branch and then cherry-pick the commit from `1.x` to `1.0` branch, if the code change are shared in the same major version.

**Comment by saratvemulapalli** [comment]
@peternied can you back port this to 1.x as well.

**Comment by peternied** [comment]
> Thanks for creating the issue. I made a mistake and didn't pay attention that this PR was against 1.0. We should be opening the PRs against the 1.x branch and then we'll cherry-pick to 1.0. /cc @adnapibar

**Comment by tlfeng** [comment]
Just a note, the change in PR #809 has been backported to `1.x` branch in PR https://github.com/opensearch-project/OpenSearch/pull/927 . 😁

**Comment by saratvemulapalli** [comment]
Thanks guys. Looks like we did everything but just didn't close the issue.
