### ISSUE TITLE
[BUG] return null_pointer_exception if the definition of processor is null when creating or updating a ingest pipeline

### ISSUE THREAD

**Issue by gaobinlong** [opensearch-project/OpenSearch#9257]
**Describe the bug**
When creating or updating a ingest pipeline by `PUT _ingest/pipeline/xx`, if the definition of the processor is null, then OpenSearch throws null_pointer_exception with 500 http status code.

**To Reproduce**
1. Create a ingest pipeline
```
PUT _ingest/pipeline/x
{
  "processors": [
    {
      "set": null
    }
  ]
}
```
then you  can see the error:
```
{
  "error": {
    "root_cause": [
      {
        "type": "null_pointer_exception",
        "reason": "Cannot invoke \"Object.getClass()\" because \"config\" is null"
      }
    ],
    "type": "null_pointer_exception",
    "reason": "Cannot invoke \"Object.getClass()\" because \"config\" is null"
  },
  "status": 500
}
```

**Expected behavior**
Validate the definition of the processor, returns 400 bad request error if the definition is null.

**Screenshots**
<img width="1291" alt="image" src="https://github.com/opensearch-project/OpenSearch/assets/15811131/c81c1528-e81e-4790-a2f5-10574bd9d84f">

**Host/Environment (please complete the following information):**
 - OS: [macOS]
 - Version [2.9]

**Comment by msfroh** [comment]
Does it make sense to create a `set` processor with a `null` config?

I agree that a NullPointerException is not ideal, but it should still throw an error, right?

**Comment by reta** [comment]
> I agree that a NullPointerException is not ideal, but it should still throw an error, right?

Yes, it does exactly that now - an error instead of NPE
