### ISSUE TITLE
[BUG] Stale file handle

### ISSUE THREAD

**Issue by zalseryani** [opensearch-project/OpenSearch#9288]
# Stale file handle after configuring NFS storage for snapshot repository.

- NFS repository created using NFS provisioned on kubernetes cluster. 
- extra volume and extra volume mounts are added in opensearch 2.9 helm chart. 
- snapshots taken and working fine. 

--> but the issue of stale occurs frequently, I am not sure why and how. 

Kindly advise. 

![image](https://github.com/opensearch-project/OpenSearch/assets/49269877/5af6bb8b-b2d5-402a-9de2-9d346a54e1fd)
![image](https://github.com/opensearch-project/OpenSearch/assets/49269877/67d8a199-761c-4945-8c41-fc97b614b3a0)

# Deployment Information
- opensearch cluster deployed with helm chart. 
- opensearch version 2.9 
- NFS provisioner deployed with helm chart. 
- Kubernetes Version : v1.25.10-gke.1400 

Knowing that the issue appeared on the previous opensearch version 2.7

**Comment by dblock** [comment]
A stale file handle [is a deleted directory](https://stackoverflow.com/questions/20105260/what-does-stale-file-handle-in-linux-mean), isn't it? When does `backups` get created/deleted?

**Comment by zalseryani** [comment]
@dblock 
The directory is not deleted, we are using nfs provisioned on kubernetes cluster to be able to use the RWM by using nfs storage class. 

The NFS Provisioner is still available and running, but when we scale down opensearch pods and scale them up, the remount again the PVC and it works fine again.

**Comment by gbbafna** [comment]
[Storage Triage] - Attendees [1](https://github.com/ltaragi) [2](https://github.com/reta) [3](https://github.com/skumawat2025) [4](https://github.com/gbbafna) [5](https://github.com/linuxpi)

Closing as there is no response . Feel free to comment or open a new issue if you are still facing the issue .
