### ISSUE TITLE
[BWC and API enforcement] Introduce checks for enforcing the API backward compatibility

### ISSUE THREAD

**Issue by reta** [opensearch-project/OpenSearch#9305]
**Is your feature request related to a problem? Please describe.**
This is the final goal, once we have the API outlined (annotated with @PublicApi), we could enforce the compatibility rules that have to be applied between version. 

**Describe the solution you'd like**
The [japicmp](https://siom79.github.io/japicmp/), that was explored here https://github.com/opensearch-project/OpenSearch/pull/9044, is one of the most advanced tools we could use for these purposes.

**Describe alternatives you've considered**

**Additional context**
Part of https://github.com/opensearch-project/OpenSearch/issues/8127

**Comment by peternied** [comment]
@reta I think we've got enough surface area to start enforcing the Public APIs, as we add more in they would be enforced, such as #9303 that is still outstanding
