### ISSUE TITLE
[BUG] favicon.ico file in the project is the elastic one, this should beupdated to an OpenSearch favicon

### ISSUE THREAD

**Issue by AmiStrn** [opensearch-project/OpenSearch#931]
**Describe the bug**
favicon.ico file is elasticsearch's favicon

**To Reproduce**
1. run opensearch locally 
2. go to any browser that uses favicons in the tabs (chrome for example)
3. in url write the address for the opensearch instance `localhost:9200`
4. See elasticsearch favicon

**Expected behavior**
An opensearch favicon

![Screen Shot 2021-07-02 at 22 36 07](https://user-images.githubusercontent.com/24204949/124321183-ef7cd100-db85-11eb-85a5-7e1fdaa0a8b0.png)

**Comment by CEHENKLE** [comment]
Holy smokes, your timing is good @AmiStrn ;)  Nice find, let me take a look.

**Comment by adnapibar** [comment]
https://raw.githubusercontent.com/opensearch-project/OpenSearch/main/server/src/main/resources/config/favicon.ico
