### ISSUE TITLE
[BUG] RemoteRestoreSnapshotIT.testRestoreInSameRemoteStoreEnabledIndex is Flaky

### ISSUE THREAD

**Issue by mch2** [opensearch-project/OpenSearch#9326]
https://build.ci.opensearch.org/job/gradle-check/22710/testReport/org.opensearch.remotestore/RemoteRestoreSnapshotIT/testRestoreInSameRemoteStoreEnabledIndex/

**Comment by andrross** [comment]
At least two failures of this test in #9083

**Comment by sachinpkale** [comment]
Duplicate of https://github.com/opensearch-project/OpenSearch/issues/9116
