### ISSUE TITLE
[BUG] RemoteStoreIT.testRemoteTranslogCleanup is flaky

### ISSUE THREAD

**Issue by mch2** [opensearch-project/OpenSearch#9327]
https://github.com/opensearch-project/OpenSearch/pull/9324#issuecomment-1678205658

**Comment by dreamer-89** [comment]
This test also fails in `org.opensearch.remotestore.multipart.RemoteStoreMultipartIT.testRemoteTranslogCleanup`. 
Gradle check: https://build.ci.opensearch.org/job/gradle-check/22714/

**Comment by anasalkouz** [comment]
@mch2 Shall we track it in the meta issue #9467 ?

**Comment by linuxpi** [comment]
@BhumikaSaini-Amazon can you take a look at this test?

**Comment by BhumikaSaini-Amazon** [comment]
Unable to repro this one on the latest `main` branch even after 2000 iterations on local. Closing this issue.

**Comment by andrross** [comment]
@BhumikaSaini-Amazon Reopening because this issue is still be referenced by a disabled test:

https://github.com/opensearch-project/OpenSearch/blob/127501789334d6deb19d206bf76d8475a9e27c54/test/framework/src/main/java/org/opensearch/remotestore/RemoteStoreCoreTestCase.java#L203
