### ISSUE TITLE
[BUG] SmokeTestMultiNodeClientYamlTestSuiteIT flaky test failure

### ISSUE THREAD

**Issue by dreamer-89** [opensearch-project/OpenSearch#9332]
Flaky test failure
```
org.opensearch.smoketest.SmokeTestMultiNodeClientYamlTestSuiteIT.test {yaml=pit/10_basic/Delete all}
```
Gradle check: https://build.ci.opensearch.org/job/gradle-check/22717/

**Comment by ashking94** [comment]
https://github.com/opensearch-project/OpenSearch/pull/10819#issuecomment-1773910227

**Comment by reta** [comment]
Closing in favour of https://github.com/opensearch-project/OpenSearch/issues/14408
