### ISSUE TITLE
[BWC] Temporarily Disable BWC Testing to remove stale joda flag in DocValueFormat

### ISSUE THREAD

**Issue by nknize** [opensearch-project/OpenSearch#9349]
This issue is to track temporary disablement of BWC testing until ignore & removal of joda flag in [`DocValueFormat`](https://github.com/opensearch-project/OpenSearch/blob/134257816acfa69db9b1a969e1854f4ece5a6e55/server/src/main/java/org/opensearch/search/DocValueFormat.java#L267) is backported. Back story, in Legacy 7.0 [joda was removed](https://github.com/elastic/elasticsearch/pull/36363) in favor of java time to support nanoseconds properly. To support BWC in docvalues a boolean flag was added. As of Legacy 7.7 this flag is always false and can be removed.

**Comment by peternied** [comment]
@nknize I'm not sure how we can know if this issue is resolved or not - in the associated PR I didn't see any tests specifically being disabled.  Could you add that detail so another contributor can address and then remove the untriaged label?
