### ISSUE TITLE
Maven repositories in gradle

### ISSUE THREAD

**Issue by frotsch** [opensearch-project/OpenSearch#939]
Just tried to code something in OpenSearch :server project which depends on an external library.
Adding them to build.gradle makes gradle only to look in the jcenter repo but not locally in .m2 or on maven central.
I suggest to define for all project the following repos: 

```
repositories {
  mavenLocal()
  mavenCentral()
  jcenter()
  //+ an opensearch maven repo if we have one
}
```

**Comment by dblock** [comment]
Once https://github.com/opensearch-project/opensearch-build/issues/20 is done we will get this updated.

**Comment by dblock** [comment]
I believe this is long done, closing.
