### ISSUE TITLE
Retrieve the total hits value that is locked during the PIT creation

### ISSUE THREAD

**Issue by Raja18lakshmi** [opensearch-project/OpenSearch#9427]
In point in time pagination technique, it is considered that OpenSearch locks a set of segments for those indexes, freezing them in time. So when we create a pit id using the query POST <index>/_search/point_in_time?keep_alive=1d . 
 We need to get the total hits for the particular PIT created.

Like the below query:
 POST /<index>/_search?track_total_hits=true&size=0
{
pit:{id:"xxxxxxxx"}
}

**Comment by Bukhtawar** [comment]
Cc: @bharath-techie

**Comment by msfroh** [comment]
@Raja18lakshmi -- can you please add some more details?

Would a match-all-docs query with `size:0` executed against the PIT provide the total hit count you're looking for?

Can you please clarify what you're trying to do with the total hit count? Thanks

**Comment by bharath-techie** [comment]
Based on @msfroh 's comment : 

Here's an example to get total hits with a sample request:

```
{
    "pit": {
	"id":  "<pit id>
    }, 
    "size": "0",
    "query": {
        "match_all": {}
    }
}
```
Sample response :
hits.total.value gives the total hits
```
{
    "pit_id": "<pit_id>",
    "took": 3,
    "timed_out": false,
    "_shards": {
        "total": 2,
        "successful": 2,
        "skipped": 0,
        "failed": 0
    },
    "hits": {
        "total": {
            "value": 5,
            "relation": "eq"
        },
        "max_score": null,
        "hits": []
    }
}
```
