### ISSUE TITLE
[BUG] Updates needed in DEVELOPER_GUIDE.md, TESTING.md, etc.

### ISSUE THREAD

**Issue by ahopp** [opensearch-project/OpenSearch#943]
**Describe the bug**
There are some documentation issues that need to be addressed in the repo docs. 

- [x] In DEVELOPER_GUIDE.md under the heading 'Project Layout', it mentions that 'docs' contains the documentation for the project. This is incorrect as that folder no longer exists.
- [x] In CONTRIBUTING.md, "please see OpenSearch Docs repo." points to README.md but I think it should point to [here](https://github.com/opensearch-project/documentation-website) since the docs folder no longer exists. 
- [ ] The MAINTAINERS.md lists 13 maintainers and points to [this](https://github.com/opensearch-project/.github/blob/main/MAINTAINERS.md) file which lists 2. If there is a difference we should make it clear, if not we should should correct. 
- [x] In TESTING.md under the heading "Testing Backwards Compatibility" it references x-pack in an example e.g. "specific tests from the x-pack rolling upgrade from 7.7.0".
- [ ] RELEASING.md has blank/empty TODO at the bottom. 
- [x] In TESTING.md under the heading "Testing Backwards Compatibility" it references the link to VersionCollection which is 404ing.
- [x] In TESTING.md under the heading "Refactor code to make it easier to test" it references an Elastic issue. We should remove or update to an OpenSearch example. 
- [x]  In TESTING.md under the heading "Test coverage analysis" it says "Test coverage reporting used to be possible with JaCoCo when OpenSearch was using Maven as its build system" but this is inaccurate. OpenSearch never used maven. This paragraph also mentions an elastic issue. I would suggest dropping the whole paragraph.
- [x] We lowered the requirements for Java from 14 to 11. This [doc](https://github.com/opensearch-project/OpenSearch/blob/main/TESTING.md#requirements) should be updated.
- [x] In TESTING.md under the heading "Building with extra plugins" 'opensearch-extra' should be formatted as inline code.
- [x] In DEVELOPER_GUIDE.md under the heading 'Project Layout', it mentions that 'plugins' contains the 'Officially supported plugins to OpenSearch' - while it might be meaningful for ODFE plugins, it's confusing for OpenSearch. 
- [x] In client/benchmark/README.md references a document on benchmarks.elasticsearch.org.s3.amazonaws.com.

Lastly, TESTING.md references Rally - I'm not sure that OpenSearch will work with Rally and we should change this to OpenSearch Benchmarks as soon as it is released. My suggestion would be to drop the benchmarking section until OpenSearch Benchmarks is out.

**To Reproduce**
Open repo docs. 

**Expected behavior**
Listed above

**Plugins**
N/A

**Screenshots**
N/A

**Host/Environment (please complete the following information):**
 - OS: N/A
 - Version: N/A

**Additional context**
None.

**Comment by dblock** [comment]
@ahopp I think you almost have the diff for this :) PR?

**Comment by dblock** [comment]
I'll take this.

**Comment by mch2** [comment]
@ahopp We lowered the requirements for Java from 14 to 11 only on the Main branch, this has not been backported to 1.x or 1.0.

**Comment by ahopp** [comment]
> I'll take this.

I appreciate it db!

**Comment by dblock** [comment]
Did in https://github.com/opensearch-project/OpenSearch/pull/946. There are a couple of open items that belong in the .github repo, I opened https://github.com/opensearch-project/.github/issues/20.

**Comment by skkosuri-amzn** [comment]
Tagging: README issue: https://github.com/opensearch-project/OpenSearch/issues/948
