### ISSUE TITLE
Parameterize Search ITs to run with Concurrent Search Feature enabled.

### ISSUE THREAD

**Issue by harishbhakuni** [opensearch-project/OpenSearch#9443]
As part of [Concurrent Search Feature](https://github.com/opensearch-project/OpenSearch/issues/2587), we are parameterizing current search related ITs to run with concurrent search feature as well.

As per the approach discussed in #8673, We need to update all the required IT classes to extend the new base class and add a new constructor in those classes.

Related Issue: #7440

**Comment by neetikasinghal** [comment]
Subtask of https://github.com/opensearch-project/OpenSearch/issues/7440
