### ISSUE TITLE
[BUG] README refers to candidate GA build as alpha version

### ISSUE THREAD

**Issue by skkosuri-amzn** [opensearch-project/OpenSearch#948]
**Describe the bug**
OpenSearch is an open source search and analytics engine derived from Elasticsearch 7.10.2, and is currently in an **alpha** state

**To Reproduce**
1. Install the 7/8/2021 candidate GA build of OpenSearch. (used tar version)
2. Open the README.md in the root folder and line-5 refers to this build as alpha version.

**Expected behavior**
Remove reference to alpha version.

**Host/Environment (please complete the following information):**
 - OS: Linux AL2

**Comment by dblock** [comment]
This is the README text on 1.0 branch. If we want to fix it we'd need to rebuild core. I suggest punting to 1.x.

**Comment by skkosuri-amzn** [comment]
Thanks for checking @dblock 1.x Sounds good to me.

**Comment by dblock** [comment]
Resolved in https://github.com/opensearch-project/OpenSearch/pull/950 for 1.x and didn't backport to 1.0.
