### ISSUE TITLE
[BUG] `bin/opensearch-env` and `config/jvm.options` scripts have Elasticsearch 7.13 version links.

### ISSUE THREAD

**Issue by skkosuri-amzn** [opensearch-project/OpenSearch#949]
**Describe the bug**
`bin/opensearch-env` and `config/jvm.options` scripts have Elasticsearch 7.13 (current) version links.

1. bin/opensearch-env
Line: 111
`  # see https://www.elastic.co/guide/en/elasticsearch/reference/current/settings.html#_setting_default_settings`

2. config/jvm.options
Line: 14 
` ## See https://www.elastic.co/guide/en/elasticsearch/reference/current/heap-size.html`

**To Reproduce**
1. Install the 7/8/2021 candidate GA build of OpenSearch. (used tar version)
2. Check above two files.

**Expected behavior**
1. Remove those links or link to 7.10.2 version.

**Host/Environment (please complete the following information):**
 - OS: Linux AL2

**Comment by Poojita-Raj** [comment]
Looking into this right now

**Comment by saratvemulapalli** [comment]
@Poojita-Raj please backport the PR to 1.x and we can close this issue.

**Comment by saratvemulapalli** [comment]
Closing as back port is complete.
