### ISSUE TITLE
[BUG] /_refresh causes a 500 error when there are warm indexes

### ISSUE THREAD

**Issue by wbeckler** [opensearch-project/OpenSearch#9493]
**To Reproduce**
On a POST /_refresh, the response is a 500 if there are warm indexes

**Expected behavior**
Either skip warm indexes or return an error that a global refresh (not index-specific) cannot run when there are warm indexes.

**Comment by gbbafna** [comment]
Hi @wbeckler , At present there is no concept of warm indexes in OpenSearch . I think you might be  referring to ultrawarm in Amazon OpenSearch Service . Please help clarify the issue.

**Comment by sachinpkale** [comment]
@wbeckler If you are referring to ultrawarm in Amazon OpenSearch Service, please contact AWS support team. Closing this issue.
