### ISSUE TITLE
[BUG] Fixing unblock condition for index create block

### ISSUE THREAD

**Issue by RS146BIJAY** [opensearch-project/OpenSearch#9531]
**Describe the bug**
As of now condition check for releasing IndexCreate block is that there should be an existing IndexCreateBlock on the cluster and auto release of the index create block is enabled. Issue in this condition is it will always evaluates to true in alternate iterations if auto release is enabled. So first time block got applied because of less space. Then in subsequent iteration it will get released due to above bug. Since DiskThresoldMonitor is also resetting the last runtime milliseconds every time we add and release blocks, nodes once evaluated to be above high watermarkwill never removed from this list even if enough space is available on the node. So all the node will always be considered above high watermark. Thus reapplying block. This keeps going in a loop.

**To Reproduce**
Reduce the space on all the nodes on cluster such that all nodes are below high watermark. In first iteration of DiskThresholdMonitor, block will be added on the cluster. In the next it will be removed. This will keep on going in loop.

**Expected behavior**
DiskThresholdMonitor should only remove block incase any node is no longer breaching high watermark.

**Comment by sachinpkale** [comment]
Fixed with https://github.com/opensearch-project/OpenSearch/pull/9437
