### ISSUE TITLE
[BUG] maintainers missing in codeowners

### ISSUE THREAD

**Issue by dblock** [opensearch-project/OpenSearch#9534]
**Describe the bug**

Since https://github.com/opensearch-project/OpenSearch/pull/9173, @abbashus and @adnapibar were re-added to MAINTAINERS, but not to CODEOWNERS. Please re-add so that they can be notified on PRs as code reviewers.

**Comment by dblock** [comment]
Seems like that's not correct.

![Screenshot 2023-10-24 at 12 31 08 PM](https://github.com/opensearch-project/OpenSearch/assets/542335/3d2d72fe-802c-40e8-8a44-a51169035402)

**Comment by msfroh** [comment]
> Seems like that's not correct.
> 
> ![Screenshot 2023-10-24 at 12 31 08 PM](https://user-images.githubusercontent.com/542335/277737781-3d2d72fe-802c-40e8-8a44-a51169035402.png)

Hmm... is that a permissions issue on the repo? 

They both exist as GitHub users:
* https://github.com/adnapibar
* https://github.com/tlfeng

How is write access to the repository managed? I assume a project (or repo?) admin is able to manage that. As I'm neither, I don't know who does or doesn't have write access.

**Comment by msfroh** [comment]
I talked with @prudhvigodithi  -- I think the permissions were changed?

**Comment by peternied** [comment]
@tlfeng @adnapibar I've sent invitations to rejoin as maintainers, sorry for the misaligned images:

![image](https://github.com/opensearch-project/OpenSearch/assets/2754967/b4f682de-18a9-4017-93e2-c25a137dcfd9)
![image](https://github.com/opensearch-project/OpenSearch/assets/2754967/d38318cf-59a1-4011-be30-720b3154f44a)

**Comment by peternied** [comment]
@prudhvigodithi can you investigate audit and see if there was an operation error or if this was related to another change? Maybe this had to do with them leaving the OpenSearch-Project organization.

**Comment by dblock** [comment]
If these folks left the org they need to be readded as external collaborators and permissions reinstanted, or revert https://github.com/opensearch-project/OpenSearch/pull/9173 and https://github.com/opensearch-project/OpenSearch/pull/10681.

**Comment by prudhvigodithi** [comment]
Hey @peternied I ran the audit again, the only drift now for OpenSearch repo is `tlfeng` to be part of the collaborators, should be solved once @tlfeng accept the invite as maintainers.

**Comment by tlfeng** [comment]
@peternied @prudhvigodithi I accepted the invitation, and thank you for your effort. Sorry for the late reply!

**Comment by prudhvigodithi** [comment]
Thanks @tlfeng I can see the OpenSearch repo is complaint now, the collaborators, code owners and maintainers are in sync now.
@dblock can we proceed to close this issue?
Thank you

**Comment by dblock** [comment]
Looks like https://github.com/opensearch-project/OpenSearch/blob/main/.github/CODEOWNERS is valid now.
