### ISSUE TITLE
Cannot index event publisher.Event{Content:beat.

### ISSUE THREAD

**Issue by SabyasachiRana** [opensearch-project/OpenSearch#955]
{"type":"illegal_argument_exception","reason":"mapper [predecoder.timestamp] cannot be changed from type [keyword] to [text]"}

 I'm trying to load a custom json in filebeat with OpenSearch . the same JSON file perfectly running in  Filebeat + opendistro

**Comment by dblock** [comment]
This is a dup of https://github.com/opensearch-project/OpenSearch/issues/667, resolved with https://github.com/opensearch-project/OpenSearch/pull/847. Set `compatibility.override_main_response_version` to put the cluster into a configuration that returns 7.10.2 as with ES OSS in OpenSearch GA.

**Comment by SabyasachiRana** [comment]
java.lang.IllegalArgumentException: unknown setting [compatibility.override_main_response_version] please check that any required plugins are installed,

**Comment by dblock** [comment]
> java.lang.IllegalArgumentException: unknown setting [compatibility.override_main_response_version] please check that any required plugins are installed,
> @dblock

Are you running GA OpenSearch from https://opensearch.org/downloads.html? Can you please `curl <your host>:9200` and provide output?

**Comment by SabyasachiRana** [comment]
@dblock thanks problem Soled with New Release
