### ISSUE TITLE
[BUG] RemoteIndexRecoveryIT.testRerouteRecovery is flaky

### ISSUE THREAD

**Issue by mch2** [opensearch-project/OpenSearch#9604]
https://github.com/opensearch-project/OpenSearch/pull/9595#issuecomment-1696573657

**Comment by mch2** [comment]
oops - closing as dup of https://github.com/opensearch-project/OpenSearch/issues/2502

**Comment by tlfeng** [comment]
It's not exact an duplicate, because the error message is not the same, but I will summarize it in issue #9580.
