### ISSUE TITLE
[BUG] flaky test faiure - testNRTReplicaWithRemoteStorePromotedAsPrimaryRefreshRefresh

### ISSUE THREAD

**Issue by tlfeng** [opensearch-project/OpenSearch#9624]
Related to https://github.com/opensearch-project/OpenSearch/issues/9586, https://github.com/opensearch-project/OpenSearch/issues/9589 and https://github.com/opensearch-project/OpenSearch/issues/9598
introduced in https://github.com/opensearch-project/OpenSearch/pull/8767, all the four sub-tests are flaky.
https://github.com/opensearch-project/OpenSearch/blob/bb7d23ca3c31140b03899d83648948dbe7229cf2/server/src/test/java/org/opensearch/index/shard/RemoteIndexShardTests.java#L66-L82

I don't know whether it's caused by the commit https://github.com/opensearch-project/OpenSearch/commit/22e84947ec0a0c733589f5c7e543239d04c2f829 mentioned in https://github.com/opensearch-project/OpenSearch/issues/9620 or not.

**Comment by tlfeng** [comment]
Those tests are being retried in Gradle check task after the PR https://github.com/opensearch-project/OpenSearch/pull/9597 merged.

**Comment by shwetathareja** [comment]
All the tests failed here again https://build.ci.opensearch.org/job/gradle-check/23917/

**Comment by shwetathareja** [comment]
@ dreamer-89 Can you look into these failure on urgent priority?
