### ISSUE TITLE
[BUG] Docker: Can't run securityadmin.sh out-of-box as $JAVA_HOME unset

### ISSUE THREAD

**Issue by sparksalot** [opensearch-project/OpenSearch#963]
**Describe the bug**
Running `securityadmin.sh` in the OpenSearch 1.0.0 docker image fails if the working directory is not first changed to the bundled Java directory, as the `java` command is not on the path and `JAVA_HOME` environment variable is not set, and therefore the script fails.

Excerpt of `securityadmin.sh` showing usage of `java` and `$JAVA_HOME`:
```sh
BIN_PATH="java"

if [ -z "$JAVA_HOME" ]; then
    echo "WARNING: JAVA_HOME not set, will use $(which $BIN_PATH)"
else
    BIN_PATH="$JAVA_HOME/bin/java"
fi

"$BIN_PATH" $JAVA_OPTS -Dorg.apache.logging.log4j.simplelog.StatusLogger.level=OFF -cp "$DIR/../*:$DIR/../../../lib/*:$DIR/../deps/*" org.opensearch.security.tools.SecurityAdmin "$@" 2>/dev/null
```

As described, `java` is not on the path:
```text
[opensearch@2b4b31c3b532 ~]$ command java
bash: java: command not found
```

Similarly, `JAVA_HOME` environment variable is not defined:
```text
[opensearch@2b4b31c3b532 ~]$ echo $JAVA_HOME

[opensearch@2b4b31c3b532 ~]$
```

**To Reproduce**
1. Download the docker-compose.yml from the OpenSearch site
2. `docker-compose up`
2. Exec into one of the two OpenSearch containers.  Either do not change directory (staying in the home dir/working dir, `/usr/share/opensearch`) or change directory to the script location (at `/usr/share/opensearch/plugins/opensearch-security/tools`) 
3. Execute `securityadmin.sh` using:  `sh /usr/share/opensearch/plugins/opensearch-security/tools/securityadmin.sh`
3. Observe the failure - the script does not print its usage information (which would normally complain that no parameters have been passed)

**Expected behavior**
`securityadmin.sh` to run.  With no additional configuration options provided, the script should then print its parameters/usage information.

**Plugins**
100% stock.  No extra plugins installed.
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**
 - OS: Docker v1.13.1 on top of CentOS 7.9
 - Version: OpenSearch 1.0.0 (`opensearchproject/opensearch:1.0.0`)

**Additional context**
None

**Comment by tlfeng** [comment]
Hi @sparksalot , thanks for providing the detailed steps and description!
The issue related to the Docker image belongs to [opensearch-build](https://github.com/opensearch-project/opensearch-build) repo, and there is an issue to track this problem https://github.com/opensearch-project/opensearch-build/issues/49.
Luckily it is said the fix will be applied in the next release. 👍

**Comment by sparksalot** [comment]
Ah, sorry!  
Thanks!
