### ISSUE TITLE
Base image incompatible with securityadmin.sh script (which: command not found)

### ISSUE THREAD

**Issue by flavienbwk** [opensearch-project/OpenSearch#964]
**Describe the bug**

I'm trying to set-up OpenSearch with TLS certificates on Docker `opensearchproject/opensearch:1.0.0`.

My probem is when I run the `securityadmin.sh` script:

```
docker-compose exec os01 bash -c "bash plugins/opensearch-security/tools/securityadmin.sh -cd plugins/opensearch-security/securityconfig -icl -nhnv -cacert config/certificates/ca/ca.pem -cert config/certificates/ca/admin.pem -key config/certificates/ca/admin.key -h localhost"
```

I get the following error : 

```
plugins/opensearch-security/tools/securityadmin.sh: line 20: which: command not found
WARNING: JAVA_HOME not set, will use
```

So the problem is `which: command not found`

**To Reproduce**

The exact docker-compose configuration [can be found in my repo](https://github.com/flavienbwk/opensearch-docker-compose/blob/main/docker-compose.yml).

```
git clone https://github.com/flavienbwk/opensearch-docker-compose
cd opensearch-docker-compose
bash generate-certs.sh
docker-compose up -d

docker-compose exec os01 bash -c "bash plugins/opensearch-security/tools/securityadmin.sh -cd plugins/opensearch-security/securityconfig -icl -nhnv -cacert config/certificates/ca/ca.pem -cert config/certificates/ca/admin.pem -key config/certificates/ca/admin.key -h localhost"
```

**Expected behavior**

That the securityadmin.sh script can be run (`which` command must be available)

**Plugins**

OpenSearch Security

**Screenshots**

**Host/Environment (please complete the following information):**

 - OS: Ubuntu 18.04
 - Docker image `opensearchproject/opensearch:1.0.0`

**Comment by ict-one-nl** [comment]
Here is your problem:

https://github.com/opensearch-project/opensearch-build/issues/49

Set the JAVA_HOME env var to /usr/share/opensearch/jdk
          }

**Comment by flavienbwk** [comment]
This doesn't fix the problem. I've already added the env variable. The problem is that the `which` command is missing in the base image (the sh script can't be run without it).

**Comment by ict-one-nl** [comment]
Sorry misread, that is very very strange. Using the same image and this small script in the container

```
#!/bin/bash

cd ../plugins/opensearch-security/tools
chmod +x securityadmin.sh
./securityadmin.sh -cd ../securityconfig/ -icl -nhnv -cacert ../../../config/certs/root-ca.pem -cert ../../../config/certs/admin.pem -key ../../../config/certs/admin-key.pem
```

Works like a charm.

**Comment by cebor** [comment]
I can confirm this issue. `docker run --rm -it opensearchproject/opensearch:1.0.0 which` returns the issue as described above.

Also not able to run `./securityadmin.sh`

**Comment by flavienbwk** [comment]
It seems like I didn't set it correctly, it works with `JAVA_HOME: /usr/share/opensearch/jdk` ! Thanks
