### ISSUE TITLE
Question: Why does the `OS/ARCH` at docker hub read `linux/amd64`?

### ISSUE THREAD

**Issue by TimHeckel** [opensearch-project/OpenSearch#965]
![image](https://user-images.githubusercontent.com/83935/125667692-458f2d6b-91b6-44e1-994d-2a190021241e.png)

[The roadmap says that won't be available until August 30th](https://github.com/orgs/opensearch-project/projects/1#column-14092178).

I did pull this down and ran `docker-compose up` on a new AWS c6 instance and received the below error, which tells me that the docker image is x86.

`standard_init_linux.go:219: exec user process caused: exec format error`

Thanks for clarifying!

**Comment by setiah** [comment]
AMD64 is x86 only (x86_64). I think the roadmap talks about ARM64 docker image, which is different and seems to be planned for 1.1.

**Comment by TimHeckel** [comment]
Thanks for clarifying!
