### ISSUE TITLE
[BUG] Searchable snapshot dependency on repository `chunk_size`

### ISSUE THREAD

**Issue by andrross** [opensearch-project/OpenSearch#9676]
## Background

Every repository implementation accepts an [optional `chunk_size` parameter](https://opensearch.org/docs/latest/api-reference/snapshots/create-repository/) at repository creation time. This property defines the maximum file size that will be uploaded to the repository. Any files larger than that will be broken into smaller files of `chunk_size` size (with the last chunk potentially smaller).

Searchable snapshots work by fetching partial index files on-demand at search time, and storing these parts as 8MiB (current hard-coded default) files on disk (unless the entire file is smaller than 8MiB). A virtual `IndexInput` wraps this logic, given the appearance to the upper layers of a single file while the implementation fetches and reads what is needed from these 8MiB partial files. [Some clever logic in this code](https://github.com/opensearch-project/OpenSearch/blob/7da292ba2a75fd394dc782b5ee66c0b560cac9db/server/src/main/java/org/opensearch/index/store/remote/file/OnDemandBlockIndexInput.java#L351-L361) relies on the partial file size being a power of 2 to leverage bit shifting techniques to convert "block number" into an actual byte offset.

## Bug

The searchable snapshot code [does not handle the case that fetching an 8MiB section of a file might cross one of the snapshot chunk boundaries](https://github.com/opensearch-project/OpenSearch/blob/c42ada8e6d63295684303d46492216f3a6f94049/server/src/main/java/org/opensearch/index/store/remote/file/OnDemandBlockSnapshotIndexInput.java#L139-L155). This means that if the repository `chunk_size` parameter is not a multiple of 8MiB, then this code will fail. In practice, all default chunk sizes are in fact a multiple of 8MiB (fs: no chunking, s3: 1GiB, gcs: 5TiB, hdfs: no chunking). However a user can configure any value. This was discovered while attempting to implement #9514 and some repositories choose a random value between 100 and 1000 bytes for the test case.

## Possible solution
- Improve OnDemandBlockSnapshotIndexInput to always download the configured block size (i.e. 8MiB) even if that means downloading multiple file parts from the repository.

**Comment by kkmr** [comment]
I'm looking into this

**Comment by kotwanikunal** [comment]
@kkmr Are you still looking at it?
