### ISSUE TITLE
[BUG] Intellij IDEA can not find 'org.opensearch.gradle.info.BuildParams'

### ISSUE THREAD

**Issue by frotsch** [opensearch-project/OpenSearch#969]
**Describe the bug**
When importing the project into Intellij IDEA Ultimate then the IDE is complaining that serveral build.gradle files (for example server/build.gradle) can not find 'org.opensearch.gradle.info.BuildParams' (import red unterlined). For the Classic AzureDiscoveryPlugin IDEA can also not find 'org.opensearch.gradle.LoggedExec'.

**Host/Environment (please complete the following information):**
 - OS: Mac Catalina
 - Up to date Intellij IDEA
 - Current main branch of OpenSearch

**Comment by owaiskazi19** [comment]
Hi @frotsch! Not sure but did you try doing `File->Invalid Cache/Restart` in Intellij. It worked for me

**Comment by dagneyb** [comment]
@frotsch can you confirm if this is still an issue? If we don't hear back by Nov 22nd, we'll consider this resolved. Thanks!

**Comment by dagneyb** [comment]
Closing as we have not heard back.
