### ISSUE TITLE
OpenSearch Upgrade Tool Enhancements & Bug Fixes

### ISSUE THREAD

**Issue by adnapibar** [opensearch-project/OpenSearch#972]
This is a meta issue for tracking all changes related to the new `opensearch-upgrade` CLI tool.  This can also be referred to when back-porting the changes to 1.x 

- [x] Initial code for the `opensearch-upgrade` #846 
- [x]  Add validation to only install official plugins #973

**Comment by nknize** [comment]
bumping to v1.2.0
