### ISSUE TITLE
[BUG] It is not clear what file to use for IDE code style (formatting) settings from developer guide

### ISSUE THREAD

**Issue by vrozov** [opensearch-project/OpenSearch#975]
**Describe the bug**
Developer guide refers to importing "the same settings file" (https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#editor--ide-support), but it is completely unclear what file it actually refers to without looking into how spotless plugin is configured.

**Comment by dblock** [comment]
Let's also add enforcement of style that automatically fails builds and has a way to auto-format for developers.
