### ISSUE TITLE
Add support for linear in rank_feature

### ISSUE THREAD

**Issue by Hronom** [opensearch-project/OpenSearch#977]
**Describe the bug**
`rank_feature` throw exception when using `linear` function
https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-rank-feature-query.html#rank-feature-query-linear

Support for https://github.com/apache/lucene-solr/pull/2051

**To Reproduce**
1. Create index
```
PUT /test
{
  "mappings": {
    "properties": {
      "pagerank": {
        "type": "rank_feature"
      },
      "url_length": {
        "type": "rank_feature",
        "positive_score_impact": false
      },
      "topics": {
        "type": "rank_features"
      }
    }
  }
}
```

2. Add test docs
```
PUT /test/_doc/1?refresh
{
  "url": "https://en.wikipedia.org/wiki/2016_Summer_Olympics",
  "content": "Rio 2016",
  "pagerank": 50.3,
  "url_length": 42,
  "topics": {
    "sports": 50,
    "brazil": 30
  }
}

PUT /test/_doc/2?refresh
{
  "url": "https://en.wikipedia.org/wiki/2016_Brazilian_Grand_Prix",
  "content": "Formula One motor race held on 13 November 2016",
  "pagerank": 50.3,
  "url_length": 47,
  "topics": {
    "sports": 35,
    "formula one": 65,
    "brazil": 20
  }
}

PUT /test/_doc/3?refresh
{
  "url": "https://en.wikipedia.org/wiki/Deadpool_(film)",
  "content": "Deadpool is a 2016 American superhero film",
  "pagerank": 50.3,
  "url_length": 37,
  "topics": {
    "movies": 60,
    "super hero": 65
  }
}
```

3. Execute query
```
GET /test/_search
{
  "query": {
    "rank_feature": {
      "field": "pagerank",
      "linear": {}
    }
  }
}
```

**Expected behavior**
As described here https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-rank-feature-query.html#rank-feature-query-linear

**Comment by Hronom** [comment]
Workaround https://github.com/elastic/elasticsearch/issues/49859#issuecomment-562590517

**Comment by dblock** [comment]
Looks like we need to reimplement https://github.com/elastic/elasticsearch/pull/67670

**Comment by anasalkouz** [comment]
Seem the fix already merged. closing the ticket. please feel free to re-open if needed.
