### ISSUE TITLE
[BUG] Snapshot restore API calls would fail in mixed cluster mode between 2.9 and 2.10 (upcoming)

### ISSUE THREAD

**Issue by shourya035** [opensearch-project/OpenSearch#9792]
**Describe the bug**
Today, the `sourceRemoteStoreRepository` field in `RestoreSnapshotRequest` is undergoing Ser-De only if the remote-store based feature flag `FeatureFlags.REMOTE_STORE` is enabled.

https://github.com/opensearch-project/OpenSearch/blob/9d6c43ae78875ce5d1dd6ef77616edf02f2f4e6a/server/src/main/java/org/opensearch/action/admin/cluster/snapshots/restore/RestoreSnapshotRequest.java#L155-L157

https://github.com/opensearch-project/OpenSearch/blob/9d6c43ae78875ce5d1dd6ef77616edf02f2f4e6a/server/src/main/java/org/opensearch/action/admin/cluster/snapshots/restore/RestoreSnapshotRequest.java#L179-L181

This would cause an issue in 2.10 where we are planning on removing the feature flag altogether to mark the feature as GA. BwC is not retained here in the following situation:

- End user migrating from 2.9 cluster to 2.10 with the `FeatureFlags.REMOTE_STORE` disabled. The `sourceRemoteStoreRepository` does not get ser-de'ed in 2.9 but the 2.10 node expects this field.

**Expected behavior**
Field Ser-De's should not be wrapped with Feature flags to ensute that BwCs are maintained across the commonly used APIs (like snapshot restore)

**Comment by shourya035** [comment]
The stop-gap solution is to change the version check to `Version.V_2_10_0`. This would retain BwC for users who had the feature flag disabled on their 2.9 cluster. But this would still break if the flag was enabled in 2.9.

This approach would be safer as experimental features are not guaranteed to have BwC across versions

**Comment by gbbafna** [comment]
[Storage Triage - attendees [1](https://github.com/reta) [2](https://github.com/lukas-vlcek) [3](https://github.com/akolarkunnu) [4](https://github.com/gbbafna) [5](https://github.com/linuxpi) [6](https://github.com/ltaragi) [7](https://github.com/sachinpkale) [8](https://github.com/astute-decipher) [9](https://github.com/BhumikaSaini-Amazon) 

Closing this issue as remote store is no more experimental , so this is not an issue anymore.
