### ISSUE TITLE
Support for Heap after GC stats

### ISSUE THREAD

**Issue by Bukhtawar** [opensearch-project/OpenSearch#981]
JVM stats published today represents the point in time usage of the heap across pools. While
MemoryPoolMXBean#getCollectionUsage based on docs

"Returns the memory usage after the Java virtual machine most recently expended effort in recycling unused objects in this memory pool"

provides a better indicator of GC throughput. This would typically be of interest for Old gen. If the collection usage increases it most likely indicates some trouble.

**Comment by reta** [comment]
@Bukhtawar would you mind if I will take this one? thank you!

**Comment by Bukhtawar** [comment]
@reta sure please go ahead. Thanks for contributing

**Comment by reta** [comment]
Thanks a lot @dblock for merging the change, may I ask you please to add 2.0 label and close this one? Thank you!

**Comment by dblock** [comment]
If we want this in 1.2 you can backport it to 1.x, too.

**Comment by reta** [comment]
> If we want this in 1.2 you can backport it to 1.x, too.

:+1:, that would be great, I would need lower the version requirement to 1.2.0 and backport this small change back to `main`, if you have no objections, will do that tomorrow :-) thank you!

**Comment by dblock** [comment]
No objections from me. You can generally backport small features as long as no backwards compatibility is broken.

**Comment by reta** [comment]
Thanks @dblock! The PR is out, nay I ask you please, if the official documentation has to be manually updated (since this is user-facing API) or it is automatically generated? I had troubles to find the details, thank you!

**Comment by dblock** [comment]
I am not sure re: documentation, if it's javadoc then it's automatic, otherwise it goes manually to https://github.com/opensearch-project/documentation-website
