### ISSUE TITLE
Feature Request - Alerting output to index

### ISSUE THREAD

**Issue by dh-aus** [opensearch-project/OpenSearch#984]
**Is your feature request related to a problem? Please describe.**
I want the output of my alert queries to be in an opensearch index, and it's frustrating that I have to webhook them out to then use a log ETL tool in order to write them back in.

**Describe the solution you'd like**
Add a new destination to the alerting plugin:
-output to an index

**Describe alternatives you've considered**
Currently we webhook to logstash, where we have a pipeline running which then outputs the alert back into opensearch, as you would be aware this is problematic in that we have to freeze the logstash version to avoid the license check.

**Additional context**
N/A - happy to discuss further.

**Comment by AmiStrn** [comment]
hi @dh-aus! I think perhaps this issue belongs in the [Alerting plugin repo](https://github.com/opensearch-project/alerting)

**Comment by dh-aus** [comment]
Oh thanks @AmiStrn - sorry I just found this - https://github.com/opensearch-project/alerting/issues/81, I'll close
