### ISSUE TITLE
[BUG] org.opensearch.telemetry.tracing.DefaultTracerTests.testSpanAcrossThreads is flaky

### ISSUE THREAD

**Issue by harishbhakuni** [opensearch-project/OpenSearch#9860]
**Describe the bug**
org.opensearch.telemetry.tracing.DefaultTracerTests.testSpanAcrossThreads is flaky.

getting java.lang.AssertionError: expected:<org.opensearch.test.telemetry.tracing.MockSpan@710d0529> but was:<null>

**To Reproduce**
REPRODUCE WITH: ./gradlew ':libs:opensearch-telemetry:test' --tests "org.opensearch.telemetry.tracing.DefaultTracerTests.testSpanAcrossThreads" -Dtests.seed=FD83D787DE9D75AC -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=es-US -Dtests.timezone=America/Guayaquil -Druntime.java=20

**Expected behavior**
test should always pass.

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**

**Comment by harishbhakuni** [comment]
https://build.ci.opensearch.org/job/gradle-check/24799/testReport/junit/org.opensearch.telemetry.tracing/DefaultTracerTests/testSpanAcrossThreads/

**Comment by Gaganjuneja** [comment]
This has already been fixed as part of this fix - https://github.com/opensearch-project/OpenSearch/pull/9782
