### ISSUE TITLE
Licensing of org.opensearch.core.common.logging.LoggerMessageFormat.java

### ISSUE THREAD

**Issue by ker2x** [opensearch-project/OpenSearch#9879]
While documenting code i noticed that : 
```libs/core/src/main/java/org/opensearch/core/common/logging/LoggerMessageFormat.java```

 is an almost identical copy of : 
https://github.com/qos-ch/slf4j/blob/master/slf4j-api/src/main/java/org/slf4j/helpers/MessageFormatter.java
which is under the MIT License.

It's pretty much a non-issue since, as far as i know, it's not forbidden by the MIT License. But i'm not a licensing expert.

This code have both elasticsearch and opensearch license header (both Apache 2.0)

I wanted to add this in the javadoc :
```
/**
 * Format string for OpenSearch log messages.
 * <p>
 * This class is almost a copy of {@code org.slf4j.helpers.MessageFormatter}<p>
 * The original code is licensed under the MIT License and is available at :
 * <a href="https://github.com/qos-ch/slf4j/blob/7c164fab8d54f823dd55c01a5a839c153f578297/slf4j-api/src/main/java/org/slf4j/helpers/MessageFormatter.java">MessageFormatter.java</a>
 *
 * @opensearch.internal
 */
``` 
 but it's a little bit weird to have this in the javadoc and i'd appreciate some feedback.

Thank you.

**Comment by ker2x** [comment]
added to https://github.com/opensearch-project/OpenSearch/pull/9976
The licensing issue in itself may or may not be a problem.

**Comment by hyandell** [comment]
Digging into this, it looks like there was a 2010 fork of code from sfl4j that went on quite a journey from there. Kudos to GitHub for letting me walk back through the codebases, this stuff gets ugly when you can't easily skip back along file renames :)

MIT doesn't add any additional conditions to OpenSearch (for example it's on the ASF's Category A list on https://www.apache.org/legal/resolved.html), but the original source header should have been maintained to the forked files.

**Comment by hyandell** [comment]
Okay, here's the proposed license header:

```
/*
 * This code is based on code from SFL4J 1.5.11
 * Copyright (c) 2004-2007 QOS.ch
 * All rights reserved.
 * SPDX-License-Identifier: MIT
 */
```

The original commit that introduced this was https://github.com/elastic/elasticsearch/commit/bda476eee846b674846a0ac6b3e52e11ef275365

While many files were affected then, it looks like https://github.com/opensearch-project/OpenSearch/blob/main/libs/core/src/main/java/org/opensearch/core/common/logging/LoggerMessageFormat.java is the descendant of these files today.

**Comment by hyandell** [comment]
@ker2x/@dblock - can you get the 6 lines above added at [L32](https://github.com/opensearch-project/OpenSearch/blob/8673fa937db405b8d614f8d4a02c0aa52587c037/libs/core/src/main/java/org/opensearch/core/common/logging/LoggerMessageFormat.java#L32)  of the file please?

**Comment by dblock** [comment]
Thanks for PRing it @hyandell.

**Comment by ker2x** [comment]
Nice ! thx !
