### ISSUE TITLE
[Concurrent Segment Search] Experimental release readiness for 2.10

### ISSUE THREAD

**Issue by sohami** [opensearch-project/OpenSearch#9913]
We want to announce the experimental release of concurrent segment search in 2.10. This issue is to track items needed for that. All the changes are merged in with fixes for known issues. With experimental release, users should be able to enable the feature and try it out for their search workload on non-production setup and provide their feedback.

Doc update:
- How to use enable/disable this experimental feature and other settings available
- New profile API stats that are added in 2.10
- New search stats that are added for concurrent search
- How `terminate_after` is handled differently with concurrent segment search
- Add the link to project board to track all the open items

**Comment by sohami** [comment]
https://github.com/opensearch-project/documentation-website/issues/4989

**Comment by DarshitChanpura** [comment]
@sohami Is this still targeting 2.10? If the feature is not already merged, then it is past code-freeze and we should move it to 2.11?

**Comment by sohami** [comment]
@DarshitChanpura We are tracking for experimental release and not GA. So changes already in 2.10 branch has majority of functionality already in it.

**Comment by yigithub** [comment]
Closing as the experimental feature is launched in 2.10.
