### ISSUE TITLE
Improve leader node-left logging to indicate timeout/coordination state rejection

### ISSUE THREAD

**Issue by Bukhtawar** [opensearch-project/OpenSearch#992]
## Problem
Production systems generally don't have debug logging enabled, to look at historical reasons for `node-left` reasons it becomes tricky to find if follower rejected with `CoordinationStateRejectedException` causing followers check retry count exceeded or was it a slow node with maybe long GC or slow resource which failed to respond back within the default 10s timeout.

While I understand it might be tricky though is conclude the reason if there is a mix of multiple reasons across attempts, but maybe fine to log last or all

**Comment by Poojita-Raj** [comment]
Looking into this.

**Comment by kartg** [comment]
Change merged
