### ISSUE TITLE
[BUG] Exception when using tf Painless method suggests using the deprecated classic similarity

### ISSUE THREAD

**Issue by kolchfa-aws** [opensearch-project/OpenSearch#9958]
**Describe the bug**
Without the correct setup, if a user calls the `tf` Painless method in the `script_score` query, the user gets back an UnsupportedOperationException:
```
{
  "error": {
    "root_cause": [
      {
        "type": "unsupported_operation_exception",
        "reason": "unsupported_operation_exception: requires a TFIDFSimilarity (such as ClassicSimilarity)"
      }
    ],
    "type": "search_phase_execution_exception",
    "reason": "all shards failed",
    "phase": "query",
    "grouped": true,
    "failed_shards": [
      {
        "shard": 0,
        "index": "test",
        "node": "sQkgvgQWRT2pfI4leTC8lg",
        "reason": {
          "type": "script_exception",
          "reason": "runtime error",
          "script_stack": [
            "org.opensearch.ExceptionsHelper.convertToOpenSearchException(ExceptionsHelper.java:86)",
            "org.opensearch.script.ScoreScriptUtils$TF.tf(ScoreScriptUtils.java:113)",
            "tf(params.field, params.term)",
            "                       ^---- HERE"
          ],
          "script": "tf(params.field, params.term)",
          "lang": "painless",
          "position": {
            "offset": 23,
            "start": 0,
            "end": 29
          },
          "caused_by": {
            "type": "exception",
            "reason": "java.lang.UnsupportedOperationException: requires a TFIDFSimilarity (such as ClassicSimilarity)",
            "caused_by": {
              "type": "unsupported_operation_exception",
              "reason": "unsupported_operation_exception: requires a TFIDFSimilarity (such as ClassicSimilarity)"
            }
          }
        }
      }
    ],
    "caused_by": {
      "type": "unsupported_operation_exception",
      "reason": "unsupported_operation_exception: requires a TFIDFSimilarity (such as ClassicSimilarity)"
    }
  },
  "status": 400
}
```
This exception instructs the user to use `classic` similarity. If the user then executes a query to set the similarity to classic:

```
PUT /test/_mapping
{
  "properties": {
    "<field_name>": {
      "type": "text",
      "similarity": "classic"
    }
  }
}
```
the user gets an exception saying that the `classic` similarity is deprecated and to use the `BM25` similarity in its place. 

**To Reproduce**
1. Run a query above
2. See the UnsupportedOperationException error

**Expected behavior**
Instead of `classic`, the exception should instruct the user to use the `BM25` similarity:

`unsupported_operation_exception: requires a TFIDFSimilarity (such as BM25Similarity)`

**Host/Environment (please complete the following information):**
 - Version 2.10

**Additional context**
See discussion in the documentation PR https://github.com/opensearch-project/documentation-website/pull/4988

**Comment by noCharger** [comment]
@kolchfa-aws I just learned that classic similarity has been removed from main branch, but not from 2.10. https://github.com/opensearch-project/OpenSearch/blob/2.10/server/src/main/java/org/opensearch/index/similarity/SimilarityService.java#L78-L98

Could you please confirm that 2.10 works properly?

**Comment by msfroh** [comment]
Should we have added support for the `tf` function if it depends on `TFIDFSimilarity` and we don't allow users to use `ClassicSimilarity` (the only subclass of `TFIDFSimilarity` that was shipping with Lucene)? I know it was requested in https://github.com/opensearch-project/OpenSearch/issues/7558, but was there any consideration for how it would work in practice? Is there a valid way for users to make use of the `tf` function with the available similarities in OpenSearch?

**Comment by noCharger** [comment]
> Should we have added support for the `tf` function if it depends on `TFIDFSimilarity` and we don't allow users to use `ClassicSimilarity` (the only subclass of `TFIDFSimilarity` that ships with Lucene)? I know it was requested in #7558, but was there any consideration for how it would work in practice? Is there a valid way for users to make use of the `tf` function with the available similarities in OpenSearch?

Good point, unless OpenSearch support ClassicSimilarity users could not really use tf() function in practice. The bugfix should remove the support of `tf()`.
