### ISSUE TITLE
[BUG] Native Plugin Installation request for .asc and OpenSearch repo has the wrong Public Key

### ISSUE THREAD

**Issue by peterzhuamazon** [opensearch-project/OpenSearch#996]
**Describe the bug**

Two issues:

1. When install the native plugin directly, `opensearch-plugin` request to use `.asc` file for validation instead of `.sig` file, which we included in the signing and release process.

```
$ ./opensearch-plugin install repository-s3
-> Installing repository-s3
-> Downloading repository-s3 from opensearch
[=================================================] 100%
-> Failed installing repository-s3
-> Rolling back repository-s3
-> Rolled back repository-s3
Exception in thread "main" java.io.IOException: Server returned HTTP response code: 403 for URL: https://artifacts.opensearch.org/releases/plugins/repository-s3/1.0.0/repository-s3-1.0.0.zip.asc
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1932)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1528)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
	at java.base/java.net.URL.openStream(URL.java:1167)
	at org.opensearch.plugins.InstallPluginCommand.urlOpenStream(InstallPluginCommand.java:482)
	at org.opensearch.plugins.InstallPluginCommand.verifySignature(InstallPluginCommand.java:622)
	at org.opensearch.plugins.InstallPluginCommand.downloadAndValidate(InstallPluginCommand.java:600)
	at org.opensearch.plugins.InstallPluginCommand.download(InstallPluginCommand.java:306)
	at org.opensearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:260)
	at org.opensearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:237)
	at org.opensearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:99)
	at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:140)
	at org.opensearch.cli.MultiCommand.execute(MultiCommand.java:104)
	at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:140)
	at org.opensearch.cli.Command.main(Command.java:103)
	at org.opensearch.plugins.PluginCli.main(PluginCli.java:60)

```

2. OpenSearch includes the wrong Public Key here:
https://github.com/opensearch-project/OpenSearch/commit/05a6fde676e6436bd1e3d5dfe7de26889a69f0cb

The correct public key is here:
https://opensearch.org/verify-signatures.html
https://artifacts.opensearch.org/publickeys/opensearch.pgp

**To Reproduce**
See Above

**Expected behavior**
Install success

**Plugins**
analysis-icu
analysis-kuromoji
analysis-nori
analysis-phonetic
analysis-smartcn
analysis-stempel
analysis-ukrainian
discovery-azure-classic
discovery-ec2
discovery-gce
ingest-attachment
mapper-annotated-text
mapper-murmur3
mapper-size
repository-azure
repository-gcs
repository-hdfs
repository-s3
store-smb
transport-nio

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**

**Comment by saratvemulapalli** [comment]
Answering questions in order:

1. OpenSearch expects the plugins to be signed by `.asc` and specifically looks for that file. 
Ref: https://github.com/opensearch-project/OpenSearch/blob/4906a3c1b029f55e41bf60ef214ebff61939ba6d/distribution/tools/plugin-cli/src/main/java/org/opensearch/plugins/InstallPluginCommand.java#L615
We can definitely discuss `.asc` vs `.sig`.

2. The key committed to the repository was in PR https://github.com/opensearch-project/OpenSearch/commit/05a6fde676e6436bd1e3d5dfe7de26889a69f0cb

Given that I see:
1. See if there is a short term path for GA: i.e without changing the key which was already bundled, can we sign the plugins using the key which was bundled and publish them.
2. Longer term: Decide `.asc` vs `.sig` and if needed update OpenSearch with the new key for next release (v1.1.0)

**Comment by peterzhuamazon** [comment]
1. Consider not even knowing what key is https://github.com/opensearch-project/OpenSearch/commit/05a6fde676e6436bd1e3d5dfe7de26889a69f0cb I would say we wont even able to retrieve the private key to sign.
2. We dont have to change .asc to .sig but the conversation can still go on. The next release we should bundle the correct public key and use .asc/.sig to validate.
3. Dont really think we can unblock 1.0.0 GA if the bundled public key is not correct as described in 1.

**Comment by nknize** [comment]
The key from https://github.com/opensearch-project/OpenSearch/commit/05a6fde676e6436bd1e3d5dfe7de26889a69f0cb was generated back on April 9th for the public release build to pass. This was communicated back then when the pgp key was created and registered in the MIT keystore and was supposed to be the key used for signing the artifacts. Seems that was forgotten somewhere between April 9th and whenever https://opensearch.org/verify-signatures.html was generated so a different key was created. We can open a PR to use the new key but it would probably be a good idea to revoke the one that was initially created. /cc @camerski

**Comment by nknize** [comment]
> Consider not even knowing what key is 05a6fde I would say we wont even able to retrieve the private key to sign.

I've got all the info for the original key if you want to use that one instead of going through the process of revoking the original one.

**Comment by peterzhuamazon** [comment]
> > Consider not even knowing what key is [05a6fde](https://github.com/opensearch-project/OpenSearch/commit/05a6fde676e6436bd1e3d5dfe7de26889a69f0cb) I would say we wont even able to retrieve the private key to sign.
> 
> I've got all the info for the original key if you want to use that one instead of going through the process of revoking the original one.

Sure, lets sync up on this one. Thanks.

**Comment by dblock** [comment]
What are we doing about this?

**Comment by minalsha** [comment]
@peterzhuamazon/@camerski : has this issue been resolved? If not, could you move this issue to the right project?

**Comment by peterzhuamazon** [comment]
Hi @nknize can we have a talk on this? Thanks.

**Comment by peterzhuamazon** [comment]
Apparently it is only doing this for official plugins:
https://github.com/opensearch-project/OpenSearch/blob/4906a3c1b029f55e41bf60ef214ebff61939ba6d/distribution/tools/plugin-cli/src/main/java/org/opensearch/plugins/InstallPluginCommand.java#L599

The plugins.txt is generated and save somewhere so all the native plugins are going through the verification:
https://github.com/opensearch-project/OpenSearch/blob/7d18eaf3a49732ced1ec3e92b5aa82790368bff2/server/build.gradle#L210

We need to discuss more on how to properly resolve this issue.

**Comment by nknize** [comment]
[Here's the original key](https://pgp.mit.edu/pks/lookup?op=vindex&search=0x0934A65836A51424) registered with pgp.mit.edu that matches the [public_key.asc file](https://github.com/opensearch-project/OpenSearch/commit/05a6fde676e6436bd1e3d5dfe7de26889a69f0cb#diff-3f3e1d9abc9071642e231c3d27f8212ffd557bfbda7b63c4c052e2e8accc83fd) in PR #512.

What do you want to do?  Use it, or revoke it in favor of the other one (4096R/67F3A6AA) that was created?

**Comment by camerski** [comment]
As we discussed today, the preferred solution for OpenSearch 1.1.0 and beyond is to change the signature check to use the user's normal PGP keyring so they can trust whichever public keys they choose, and add an option to the plugin installer to skip signature verification.

For existing users we are discussing a couple of options for how to get them unblocked until 1.1.0 is ready. The options are:

1. Create a second set of signatures for the core plugins using the hard-coded key from PR #512 and publish those.
2. In OpenSearch 1.0.1, sign the core plugins using the main OpenSearch signing key and update the hard-coded key to the correct public master key. No support for unblocking users of 1.0.0 with this option.
3. Wait for 1.1.0 (not a great option, obviously, but ruling it out should be a decision, not an assumption).
4. Add the `skip-signature-verification` argument to the plugin installer in OpenSearch 1.0.1

Any other options? Thoughts?

**Comment by AmiStrn** [comment]
What is the status of this issue? 
We could really use this fix, as we need to be using these plugins to use v1.0.0 or v1.0.1 but definitely cant wait for v1.1 

> As we discussed today

Where was that discussed? was it in a thread in the forums? Was it in an internal AWS meeting perhaps?

> For existing users we are discussing a couple of options for how to get them unblocked until 1.1.0 is ready

What would you suggest users that require this fix to upgrade to opensearch? Should they stop their upgrade efforts because of this? If so, we are going to need to add a breaking change or notice to v1.0.0 so users don't upgrade from a perfectly good ES cluster to one that right away breaks...

**Comment by CEHENKLE** [comment]
@bbarani @peterzhuamazon Hey Peter, I've assigned this to you, but if you're the wrong person, please feel free to assign.   Can you answer @AmiStrn's question?

Thanks!
/C

**Comment by CEHENKLE** [comment]
Talking to @nknize, it sounds like the only thing left to do is to update the public key to match what Marc published on pgp.mit.edu

@bbarani I don't believe we have permissions do to that -- can you assign someone in infra to do this?

Thanks!

/C

**Comment by peterzhuamazon** [comment]
Hi Charlotte,

1. Nick need to add either a skip signature check param, or implement read public key from keyring.
2. If 1 not doable for the next release, then we need to replace the existing public key save in OpenSearch repo to the one actual public key we use and posted on opensearch.org (https://artifacts.opensearch.org/publickeys/opensearch.pgp)
3. When generating all the new native plugin zips, we need to convert the sig files to .asc so the existing functionalities can verify the signatures.

Thanks.

**Comment by bbarani** [comment]
@nknize @CEHENKLE Please let us know if there is a plan to fix this in 1.1 release. This is not tied to 1.1 release but we would like to close this out as soon as possible to unblock community from installing those plugins.

**Comment by nknize** [comment]
Looking into this and will update labels shortly.

**Comment by andresbravog** [comment]
This is still happening in tarball `1.1.0` release.

**Comment by andresbravog** [comment]
Thanks, @peterzhuamazon that fixed the error.
