### ISSUE TITLE
[Remote Store] Optimize remote store restore flow to not download all the files from remote if local disk already has data

### ISSUE THREAD

**Issue by linuxpi** [opensearch-project/OpenSearch#9984]
**Is your feature request related to a problem? Please describe.**
- When we trigger remote restore via `RemoteStoreRecoverySource`, we download all the segment files from remote irrespective of the fact that local disk may contain some of those files. 
- We should provide a choice through RemoteStoreRestore flow whether all segment files should be downloaded from remote even if local disk already contains some of them

**Describe the solution you'd like**
Provide a parameter/setting to the user which allows them to control whether to download all segment files from remote during recovery of a remote backed shard

**Comment by shwetathareja** [comment]
@linuxpi does this issue still exist?

**Comment by linuxpi** [comment]
@shwetathareja I dont think we changes anything around this. I'll update this issue with more details

**Comment by gbbafna** [comment]
Storage Triage : Attendees [1](https://github.com/lukas-vlcek]) [2](https://github.com/skumawat2025) [3](https://github.com/astute-decipher) [4](https://github.com/gbbafna)  [5](https://github.com/linuxpi) [6](https://github.com/sachinpkale) 

This is not relevant anymore as we only recover unassigned shards in remote restore.
